import { ExerciseCategoryMeta, ExerciseSubCategoryMeta, ExerciseItem, ExerciseCategory } from './types';

export const EXERCISE_CATEGORIES: ExerciseCategoryMeta[] = [
  {
    id: 'chest_pecs',
    name: 'Chest & Pectorals',
    shortLabel: 'Chest',
    icon: '🛡️',
    description: 'Incline, flat & decline presses, dumbbell flyes, cable crossovers & push-up progressions',
    accentColor: '#3b82f6',
  },
  {
    id: 'back_lats',
    name: 'Back, Lats & Traps',
    shortLabel: 'Back & Lats',
    icon: '🦅',
    description: 'Vertical pull-downs, pull-ups, horizontal rows, deadlifts, pullovers & trap shrugs',
    accentColor: '#06b6d4',
  },
  {
    id: 'shoulders_delts',
    name: 'Shoulders & Deltoids',
    shortLabel: 'Shoulders',
    icon: '🏹',
    description: 'Overhead military press, lateral deltoid raises, rear delt flyes & rotator cuff stability',
    accentColor: '#8b5cf6',
  },
  {
    id: 'arms_biceps_triceps',
    name: 'Arms (Biceps, Triceps & Forearms)',
    shortLabel: 'Arms',
    icon: '💪',
    description: 'Supinated bicep curls, hammer curls, tricep extensions, dips & forearm wrist curls',
    accentColor: '#f97316',
  },
  {
    id: 'legs_quads_hamstrings',
    name: 'Legs (Quads, Hamstrings & Calves)',
    shortLabel: 'Legs & Quads',
    icon: '🦵',
    description: 'Barbell back squats, front squats, Romanian deadlifts, leg press, lunges & calf raises',
    accentColor: '#10b981',
  },
  {
    id: 'glutes_hips',
    name: 'Glutes, Hips & Pelvic Chain',
    shortLabel: 'Glutes & Hips',
    icon: '🍑',
    description: 'Barbell hip thrusts, glute bridges, Bulgarian split squats, cable kickbacks & abductions',
    accentColor: '#ec4899',
  },
  {
    id: 'core_abdominals',
    name: 'Core, Abs & Rotational Strength',
    shortLabel: 'Core & Abs',
    icon: '🧱',
    description: 'Hanging leg raises, planks, ab wheel rollouts, cable woodchops & bicycle crunches',
    accentColor: '#eab308',
  },
  {
    id: 'hiit_conditioning',
    name: 'HIIT, Conditioning & Full Body',
    shortLabel: 'HIIT & Cardio',
    icon: '⚡',
    description: 'Kettlebell swings, battle ropes, rowing sprints, burpees, jump rope & assault air bike',
    accentColor: '#ef4444',
  },
  {
    id: 'mobility_warmup',
    name: 'Mobility, Flexibility & Warmup',
    shortLabel: 'Mobility',
    icon: '🧘',
    description: 'Thoracic spine rotations, 90/90 hip openers, shoulder dislocates & dynamic activation',
    accentColor: '#14b8a6',
  },
];

export const EXERCISE_SUB_CATEGORIES: ExerciseSubCategoryMeta[] = [
  // 1. Chest
  { id: 'chest_incline', parentId: 'chest_pecs', name: 'Upper Chest & Incline Pressing', icon: '📐', description: 'Incline bench dumbbell presses, barbell incline & 30-degree smith presses' },
  { id: 'chest_flat', parentId: 'chest_pecs', name: 'Mid-Chest & Flat Pressing', icon: '🛡️', description: 'Barbell bench press, heavy dumbbell press & floor presses' },
  { id: 'chest_decline_dips', parentId: 'chest_pecs', name: 'Lower Chest, Dips & Declines', icon: '🧱', description: 'Parallel bar chest dips, decline dumbbell press & high-to-low cable presses' },
  { id: 'chest_flyes_cable', parentId: 'chest_pecs', name: 'Chest Flyes & Cable Crossovers', icon: '🦅', description: 'Incline cable flyes, dumbbell chest flyes & pec deck machines' },
  { id: 'chest_pushups', parentId: 'chest_pecs', name: 'Push-Up Progressions & Calisthenics', icon: '🤸', description: 'Strict tempo push-ups, diamond push-ups, archer push-ups & decline push-ups' },

  // 2. Back
  { id: 'back_vertical_pull', parentId: 'back_lats', name: 'Vertical Pulling (Pull-Ups & Pulldowns)', icon: '🧗', description: 'Wide-grip pull-ups, neutral chin-ups, lat pulldowns & single-arm pulldowns' },
  { id: 'back_horizontal_rows', parentId: 'back_lats', name: 'Horizontal Rows (Barbell, DB & Cable)', icon: '🚣', description: 'Bent-over barbell rows, chest-supported rows, dumbbell single-arm rows & seated cable rows' },
  { id: 'back_deadlifts_hinges', parentId: 'back_lats', name: 'Deadlifts & Spinal Erectors', icon: '⚡', description: 'Conventional deadlifts, rack pulls, trap bar deadlifts & hyperextensions' },
  { id: 'back_pullovers_traps', parentId: 'back_lats', name: 'Lat Pullovers & Trap Shrugs', icon: '🦾', description: 'Straight-arm cable pullovers, dumbbell pullovers & barbell power shrugs' },

  // 3. Shoulders
  { id: 'shoulders_overhead', parentId: 'shoulders_delts', name: 'Overhead Pressing & Military', icon: '🏹', description: 'Standing barbell overhead press, seated dumbbell shoulder press & Arnold press' },
  { id: 'shoulders_lateral', parentId: 'shoulders_delts', name: 'Lateral Deltoids (Side Raises)', icon: '🪶', description: 'Dumbbell lateral raises, cable lean-away raises & behind-the-back cable raises' },
  { id: 'shoulders_rear', parentId: 'shoulders_delts', name: 'Rear Delts & Upper Back Density', icon: '🦅', description: 'Cable face pulls, bent-over dumbbell reverse flyes & rear delt machine' },
  { id: 'shoulders_rotator_cuff', parentId: 'shoulders_delts', name: 'Rotator Cuff & Shoulder Health', icon: '🛡️', description: 'External cable rotations, band pull-aparts & Lu raises' },

  // 4. Arms
  { id: 'arms_biceps_supinated', parentId: 'arms_biceps_triceps', name: 'Bicep Peak & Supinated Curls', icon: '💪', description: 'Incline dumbbell curls, barbell curls, EZ bar preacher curls & spider curls' },
  { id: 'arms_biceps_hammer', parentId: 'arms_biceps_triceps', name: 'Brachialis & Hammer Curls', icon: '🔨', description: 'Cross-body hammer curls, rope cable hammer curls & reverse grip curls' },
  { id: 'arms_triceps_extensions', parentId: 'arms_biceps_triceps', name: 'Triceps Overhead Extensions', icon: '🦾', description: 'Dumbbell overhead tricep extensions, skull crushers & cable French press' },
  { id: 'arms_triceps_pushdowns', parentId: 'arms_biceps_triceps', name: 'Triceps Pushdowns & Dips', icon: '⚡', description: 'Straight bar cable pushdowns, rope pushdowns & bench dips' },
  { id: 'arms_forearms_grip', parentId: 'arms_biceps_triceps', name: 'Forearms & Grip Strength', icon: '✊', description: 'Barbell wrist curls, reverse wrist curls & farmer walks' },

  // 5. Legs
  { id: 'legs_squats', parentId: 'legs_quads_hamstrings', name: 'Squats & Quad Dominant Pressing', icon: '🦵', description: 'Barbell back squats, front squats, goblet squats, hack squats & leg press' },
  { id: 'legs_lunges_split', parentId: 'legs_quads_hamstrings', name: 'Lunges & Unilateral Leg Work', icon: '🏃', description: 'Walking dumbbell lunges, Bulgarian split squats & reverse lunges' },
  { id: 'legs_hamstring_curls', parentId: 'legs_quads_hamstrings', name: 'Hamstring Flexion & Leg Curls', icon: '🦿', description: 'Lying leg curls, seated leg curls, Nordic curls & slider curls' },
  { id: 'legs_calves', parentId: 'legs_quads_hamstrings', name: 'Calves (Gastrocnemius & Soleus)', icon: '👣', description: 'Standing barbell calf raises, seated calf raises & donkey calf raises' },

  // 6. Glutes
  { id: 'glutes_hip_thrusts', parentId: 'glutes_hips', name: 'Hip Thrusts & Glute Bridges', icon: '🍑', description: 'Barbell hip thrusts, dumbbell single-leg bridges & kas glute bridges' },
  { id: 'glutes_rdl_hinges', parentId: 'glutes_hips', name: 'Romanian Deadlifts & Glute Hinges', icon: '📐', description: 'Dumbbell Romanian deadlifts, barbell RDLs & B-stance RDLs' },
  { id: 'glutes_abductions_kick', parentId: 'glutes_hips', name: 'Cable Kickbacks & Abductions', icon: '💫', description: 'Ankle strap cable kickbacks, seated machine abductions & band lateral walks' },

  // 7. Core
  { id: 'core_anti_extension', parentId: 'core_abdominals', name: 'Planks & Anti-Extension', icon: '🧱', description: 'RKC weighted planks, ab wheel rollouts & dead bugs' },
  { id: 'core_hanging_raises', parentId: 'core_abdominals', name: 'Hanging Leg & Knee Raises', icon: '🚪', description: 'Hanging straight leg raises, captain chair knee tucks & toe-to-bars' },
  { id: 'core_rotational', parentId: 'core_abdominals', name: 'Rotational & Obliques', icon: '🔄', description: 'Cable woodchops, Russian twists, pallof press & side planks' },
  { id: 'core_crunches_flexion', parentId: 'core_abdominals', name: 'Spinal Flexion & Crunches', icon: '🧘', description: 'Kneeling cable crunches, decline bench crunches & bicycle crunches' },

  // 8. HIIT & Conditioning
  { id: 'hiit_kettlebell_complex', parentId: 'hiit_conditioning', name: 'Kettlebell Complexes & Snatches', icon: '🔔', description: 'Two-handed kettlebell swings, clean and press, Turkish get-ups & snatches' },
  { id: 'hiit_bodyweight_plyo', parentId: 'hiit_conditioning', name: 'Plyometrics & Burpee Combos', icon: '⚡', description: 'Burpees over bar, box jumps, tuck jumps & mountain climber sprints' },
  { id: 'hiit_ropes_cardio_gear', parentId: 'hiit_conditioning', name: 'Battle Ropes, Rowers & Bikes', icon: '🚣', description: 'Alternating battle rope waves, 500m rower sprints & assault bike tabatas' },

  // 9. Mobility & Warmup
  { id: 'mobility_upper_spine', parentId: 'mobility_warmup', name: 'Upper Body & Thoracic Spine', icon: '🏹', description: 'PVC shoulder dislocates, band pull-aparts, cat-cows & thread the needles' },
  { id: 'mobility_hips_ankles', parentId: 'mobility_warmup', name: 'Hips, Pelvis & Ankle Mobility', icon: '🧘', description: '90/90 hip mobility flow, deep goblet squat pry & ankle wall mobilization' },
];

export const MASTER_EXERCISE_DATABASE: ExerciseItem[] = [
  // ==========================================
  // 1. CHEST & PECTORALS
  // ==========================================
  {
    id: 'ex-bench-barbell',
    name: 'Barbell Flat Bench Press',
    target_muscle: 'chest',
    secondary_muscles: ['triceps', 'shoulders'],
    equipment_required: 'barbells',
    required_equipment_ids: ['barbells', 'weight_plates', 'flat_bench'],
    is_barbell_plate_loaded: true,
    category: 'strength',
    exercise_category: 'chest_pecs',
    sub_category: 'chest_flat',
    difficulty: 'intermediate',
    mechanics: 'compound',
    suggested_sets_reps: '4 sets × 6–8 reps',
    instructions: 'Plant feet firmly into the floor, retract and depress shoulder blades into bench, lower bar with controlled 2-second descent to lower sternum, press explosively locking elbows.',
    video_url_mock: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-incline-barbell-press',
    name: 'Barbell Incline Bench Press (30° Angle)',
    target_muscle: 'chest',
    secondary_muscles: ['shoulders', 'triceps'],
    equipment_required: 'barbells',
    required_equipment_ids: ['barbells', 'weight_plates', 'adjustable_bench', 'power_rack'],
    is_barbell_plate_loaded: true,
    category: 'hypertrophy',
    exercise_category: 'chest_pecs',
    sub_category: 'chest_incline',
    difficulty: 'intermediate',
    mechanics: 'compound',
    suggested_sets_reps: '4 sets × 8–10 reps',
    instructions: 'Set bench to 30 degrees. Grip barbell slightly wider than shoulder width, lower bar smoothly touching upper chest clavicle line, drive up squeezing upper pec fibers.',
    video_url_mock: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-incline-db-press',
    name: 'Incline Dumbbell Bench Press (30°)',
    target_muscle: 'chest',
    secondary_muscles: ['shoulders', 'triceps'],
    equipment_required: 'dumbbells',
    required_equipment_ids: ['dumbbells', 'adjustable_bench'],
    category: 'hypertrophy',
    exercise_category: 'chest_pecs',
    sub_category: 'chest_incline',
    difficulty: 'intermediate',
    mechanics: 'compound',
    suggested_sets_reps: '3 sets × 8–12 reps',
    instructions: 'Set bench to 30 degrees. Flare elbows at 45 degrees, lower dumbbells to clavicle level for a deep chest stretch, drive up squeezing upper pecs.',
    video_url_mock: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-flat-db-press',
    name: 'Flat Dumbbell Bench Press',
    target_muscle: 'chest',
    secondary_muscles: ['triceps', 'shoulders'],
    equipment_required: 'dumbbells',
    required_equipment_ids: ['dumbbells', 'flat_bench'],
    category: 'hypertrophy',
    exercise_category: 'chest_pecs',
    sub_category: 'chest_flat',
    difficulty: 'beginner',
    mechanics: 'compound',
    suggested_sets_reps: '3 sets × 10–12 reps',
    instructions: 'Lower dumbbells with neutral-to-pronated wrist angle, feel maximum pec elongation, press together over chest.',
    video_url_mock: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-decline-barbell-press',
    name: 'Decline Barbell Bench Press',
    target_muscle: 'chest',
    secondary_muscles: ['triceps'],
    equipment_required: 'barbells',
    required_equipment_ids: ['barbells', 'weight_plates', 'adjustable_bench'],
    is_barbell_plate_loaded: true,
    category: 'strength',
    exercise_category: 'chest_pecs',
    sub_category: 'chest_decline_dips',
    difficulty: 'intermediate',
    mechanics: 'compound',
    suggested_sets_reps: '3 sets × 8–10 reps',
    instructions: 'Secure shins under leg rollers on decline bench. Lower bar under control to lower pec line, press vertically.',
    video_url_mock: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-cable-crossover-high-low',
    name: 'High-to-Low Cable Chest Crossover',
    target_muscle: 'chest',
    secondary_muscles: ['shoulders'],
    equipment_required: 'cable_machine',
    required_equipment_ids: ['cable_machine'],
    category: 'hypertrophy',
    exercise_category: 'chest_pecs',
    sub_category: 'chest_flyes_cable',
    difficulty: 'intermediate',
    mechanics: 'isolation',
    suggested_sets_reps: '3 sets × 12–15 reps',
    instructions: 'Position pulleys at highest notch. Step forward into slight split stance, bring handles down and across bottom chest with continuous peak tension.',
    video_url_mock: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-cable-low-to-high-flye',
    name: 'Low-to-High Incline Cable Flyes',
    target_muscle: 'chest',
    secondary_muscles: ['shoulders'],
    equipment_required: 'cable_machine',
    required_equipment_ids: ['cable_machine'],
    category: 'hypertrophy',
    exercise_category: 'chest_pecs',
    sub_category: 'chest_flyes_cable',
    difficulty: 'intermediate',
    mechanics: 'isolation',
    suggested_sets_reps: '3 sets × 12–15 reps',
    instructions: 'Set pulleys to bottom floor position. Scoop handles upward and together in front of collarbones, squeezing the upper inner chest.',
    video_url_mock: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-parallel-chest-dips',
    name: 'Parallel Bar Chest Dips (Forward Lean)',
    target_muscle: 'chest',
    secondary_muscles: ['triceps', 'shoulders'],
    equipment_required: 'dip_bars',
    required_equipment_ids: ['dip_bars'],
    category: 'strength',
    exercise_category: 'chest_pecs',
    sub_category: 'chest_decline_dips',
    difficulty: 'intermediate',
    mechanics: 'compound',
    suggested_sets_reps: '3 sets × 8–12 reps',
    instructions: 'Lean torso forward 30 degrees, flare elbows slightly out, lower until shoulders are below elbows, press powerfully through palms.',
    video_url_mock: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-pushups-strict',
    name: 'Strict Tempo Floor Push-Ups',
    target_muscle: 'chest',
    secondary_muscles: ['triceps', 'core', 'shoulders'],
    equipment_required: 'bodyweight',
    required_equipment_ids: ['bodyweight'],
    category: 'hypertrophy',
    exercise_category: 'chest_pecs',
    sub_category: 'chest_pushups',
    difficulty: 'beginner',
    mechanics: 'compound',
    suggested_sets_reps: '3 sets × 15–20 reps',
    instructions: 'Maintain a rigid hollow-body plank, 3-second eccentric lowering to 1 inch above floor, explosive press lockout.',
    video_url_mock: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-diamond-pushups',
    name: 'Diamond Close-Grip Push-Ups',
    target_muscle: 'chest',
    secondary_muscles: ['triceps', 'core'],
    equipment_required: 'bodyweight',
    required_equipment_ids: ['bodyweight'],
    category: 'hypertrophy',
    exercise_category: 'chest_pecs',
    sub_category: 'chest_pushups',
    difficulty: 'intermediate',
    mechanics: 'compound',
    suggested_sets_reps: '3 sets × 12–15 reps',
    instructions: 'Form a triangle with thumbs and index fingers under sternum, keep elbows tucked close to ribcage, lower and press.',
    video_url_mock: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-pec-deck-machine',
    name: 'Seated Pec Deck Flye Machine',
    target_muscle: 'chest',
    secondary_muscles: ['shoulders'],
    equipment_required: 'pec_deck',
    required_equipment_ids: ['pec_deck'],
    category: 'hypertrophy',
    exercise_category: 'chest_pecs',
    sub_category: 'chest_flyes_cable',
    difficulty: 'beginner',
    mechanics: 'isolation',
    suggested_sets_reps: '3 sets × 12–15 reps',
    instructions: 'Keep elbows slightly bent and aligned with mid-chest, sweep handles together in an arc, hold peak contraction for 1 second.',
    video_url_mock: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80',
  },

  // ==========================================
  // 2. BACK, LATS & POSTERIOR CHAIN
  // ==========================================
  {
    id: 'ex-deadlift-conventional',
    name: 'Conventional Olympic Barbell Deadlift',
    target_muscle: 'back',
    secondary_muscles: ['hamstrings', 'glutes', 'quads', 'core'],
    equipment_required: 'barbells',
    required_equipment_ids: ['barbells', 'weight_plates'],
    is_barbell_plate_loaded: true,
    category: 'strength',
    exercise_category: 'back_lats',
    sub_category: 'back_deadlifts_hinges',
    difficulty: 'advanced',
    mechanics: 'compound',
    suggested_sets_reps: '4 sets × 5 reps',
    instructions: 'Bar resting over midfoot. Set lats tight, brace 360-degree intra-abdominal pressure, push floor away with legs until bar clears knees, lock hips with glute squeeze.',
    video_url_mock: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-deadlift-trap-bar',
    name: 'Hex / Trap Bar Deadlift (Neutral Grip)',
    target_muscle: 'back',
    secondary_muscles: ['quads', 'glutes', 'hamstrings', 'traps'],
    equipment_required: 'trap_bar',
    required_equipment_ids: ['trap_bar', 'weight_plates'],
    is_barbell_plate_loaded: true,
    category: 'strength',
    exercise_category: 'back_lats',
    sub_category: 'back_deadlifts_hinges',
    difficulty: 'intermediate',
    mechanics: 'compound',
    suggested_sets_reps: '4 sets × 6–8 reps',
    instructions: 'Stand centered inside hex bar. Grip neutral handles, set spine neutral with high chest, drive heels through floor with lower shear stress on lumbar spine.',
    video_url_mock: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-pullup-overhand',
    name: 'Overhand Wide-Grip Pull-Ups',
    target_muscle: 'back',
    secondary_muscles: ['biceps', 'shoulders', 'core'],
    equipment_required: 'pull_up_bar',
    required_equipment_ids: ['pull_up_bar'],
    category: 'strength',
    exercise_category: 'back_lats',
    sub_category: 'back_vertical_pull',
    difficulty: 'intermediate',
    mechanics: 'compound',
    suggested_sets_reps: '4 sets × 6–10 reps',
    instructions: 'Hang from full deadhang, engage scapulae, drive elbows down into back pockets until chin clears the bar cleanly.',
    video_url_mock: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-chinup-underhand',
    name: 'Underhand Neutral / Chin-Ups',
    target_muscle: 'back',
    secondary_muscles: ['biceps', 'core'],
    equipment_required: 'pull_up_bar',
    required_equipment_ids: ['pull_up_bar'],
    category: 'hypertrophy',
    exercise_category: 'back_lats',
    sub_category: 'back_vertical_pull',
    difficulty: 'intermediate',
    mechanics: 'compound',
    suggested_sets_reps: '3 sets × 8–12 reps',
    instructions: 'Supinated grip with palms facing you. Pull chest towards bar emphasizing lower lats and bicep recruitment.',
    video_url_mock: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-lat-pulldown-wide',
    name: 'Lat Pulldown (Overhand Wide Grip)',
    target_muscle: 'back',
    secondary_muscles: ['biceps', 'shoulders'],
    equipment_required: 'lat_pulldown',
    required_equipment_ids: ['lat_pulldown'],
    category: 'hypertrophy',
    exercise_category: 'back_lats',
    sub_category: 'back_vertical_pull',
    difficulty: 'beginner',
    mechanics: 'compound',
    suggested_sets_reps: '4 sets × 10–12 reps',
    instructions: 'Lock thighs under pad, arch upper thoracic spine slightly, pull bar smoothly to upper chest, squeeze lats at bottom.',
    video_url_mock: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-barbell-bent-over-row',
    name: 'Bent-Over Barbell Row (Pendlay Style)',
    target_muscle: 'back',
    secondary_muscles: ['hamstrings', 'biceps', 'core'],
    equipment_required: 'barbells',
    required_equipment_ids: ['barbells', 'weight_plates'],
    is_barbell_plate_loaded: true,
    category: 'strength',
    exercise_category: 'back_lats',
    sub_category: 'back_horizontal_rows',
    difficulty: 'intermediate',
    mechanics: 'compound',
    suggested_sets_reps: '4 sets × 8–10 reps',
    instructions: 'Hinge hips to parallel torso, brace core firmly, pull bar explosively into lower ribcage, reset on floor between reps.',
    video_url_mock: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-db-single-arm-row',
    name: 'Single-Arm Dumbbell Row (Bench Supported)',
    target_muscle: 'back',
    secondary_muscles: ['biceps', 'shoulders'],
    equipment_required: 'dumbbells',
    required_equipment_ids: ['dumbbells', 'flat_bench'],
    category: 'hypertrophy',
    exercise_category: 'back_lats',
    sub_category: 'back_horizontal_rows',
    difficulty: 'beginner',
    mechanics: 'compound',
    suggested_sets_reps: '3 sets × 10–12 reps/side',
    instructions: 'Support knee and hand on flat bench. Pull dumbbell towards hip pocket in a gentle J-curve, squeeze lat without twisting torso.',
    video_url_mock: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-seated-cable-row',
    name: 'Seated Cable Row (Close-Grip V-Bar)',
    target_muscle: 'back',
    secondary_muscles: ['biceps', 'shoulders'],
    equipment_required: 'cable_machine',
    required_equipment_ids: ['cable_machine'],
    category: 'hypertrophy',
    exercise_category: 'back_lats',
    sub_category: 'back_horizontal_rows',
    difficulty: 'beginner',
    mechanics: 'compound',
    suggested_sets_reps: '3 sets × 10–12 reps',
    instructions: 'Sit tall with slight knee bend, pull handle directly to belly button, retract rhomboids and pinch scapulae together.',
    video_url_mock: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-barbell-shrugs',
    name: 'Heavy Olympic Barbell Trap Shrugs',
    target_muscle: 'back',
    secondary_muscles: ['forearms'],
    equipment_required: 'barbells',
    required_equipment_ids: ['barbells', 'weight_plates'],
    is_barbell_plate_loaded: true,
    category: 'hypertrophy',
    exercise_category: 'back_lats',
    sub_category: 'back_pullovers_traps',
    difficulty: 'beginner',
    mechanics: 'isolation',
    suggested_sets_reps: '4 sets × 12–15 reps',
    instructions: 'Hold bar with shoulder-width overhand grip, shrug shoulders straight up towards ears, hold peak contraction for 2 seconds.',
    video_url_mock: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
  },

  // ==========================================
  // 3. SHOULDERS & DELTOIDS
  // ==========================================
  {
    id: 'ex-overhead-press-barbell',
    name: 'Standing Olympic Barbell Overhead Press (OHP)',
    target_muscle: 'shoulders',
    secondary_muscles: ['triceps', 'core', 'chest'],
    equipment_required: 'barbells',
    required_equipment_ids: ['barbells', 'weight_plates'],
    is_barbell_plate_loaded: true,
    category: 'strength',
    exercise_category: 'shoulders_delts',
    sub_category: 'shoulders_overhead',
    difficulty: 'intermediate',
    mechanics: 'compound',
    suggested_sets_reps: '4 sets × 6–8 reps',
    instructions: 'Squeeze glutes and abs, start with bar on collarbone, press vertically clearing chin, shrug traps at top lockout.',
    video_url_mock: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-seated-db-shoulder-press',
    name: 'Seated Dumbbell Shoulder Press',
    target_muscle: 'shoulders',
    secondary_muscles: ['triceps'],
    equipment_required: 'dumbbells',
    required_equipment_ids: ['dumbbells', 'adjustable_bench'],
    category: 'hypertrophy',
    exercise_category: 'shoulders_delts',
    sub_category: 'shoulders_overhead',
    difficulty: 'beginner',
    mechanics: 'compound',
    suggested_sets_reps: '3 sets × 8–12 reps',
    instructions: 'Set bench to 80-85 degrees. Press dumbbells overhead in a natural arc, avoid banging weights at top.',
    video_url_mock: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-db-lateral-raises',
    name: 'Dumbbell Lateral Raises (Strict Pinky Up)',
    target_muscle: 'shoulders',
    secondary_muscles: ['traps'],
    equipment_required: 'dumbbells',
    required_equipment_ids: ['dumbbells'],
    category: 'hypertrophy',
    exercise_category: 'shoulders_delts',
    sub_category: 'shoulders_lateral',
    difficulty: 'beginner',
    mechanics: 'isolation',
    suggested_sets_reps: '4 sets × 12–15 reps',
    instructions: 'Slight torso forward lean. Lead with elbows in the scapular plane, raise to shoulder height, 2-second controlled descent.',
    video_url_mock: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-cable-face-pulls',
    name: 'Cable Face Pulls with External Rotation',
    target_muscle: 'shoulders',
    secondary_muscles: ['back', 'traps'],
    equipment_required: 'cable_machine',
    required_equipment_ids: ['cable_machine'],
    category: 'hypertrophy',
    exercise_category: 'shoulders_delts',
    sub_category: 'shoulders_rear',
    difficulty: 'beginner',
    mechanics: 'compound',
    suggested_sets_reps: '3 sets × 15–20 reps',
    instructions: 'Set rope at eye level. Pull rope to bridge of nose while rotating thumbs backwards for rear delt and rotator cuff development.',
    video_url_mock: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80',
  },

  // ==========================================
  // 4. LEGS (QUADS, HAMSTRINGS & CALVES)
  // ==========================================
  {
    id: 'ex-barbell-back-squat',
    name: 'Olympic Barbell High-Bar Back Squat',
    target_muscle: 'quads',
    secondary_muscles: ['glutes', 'hamstrings', 'core'],
    equipment_required: 'barbells',
    required_equipment_ids: ['barbells', 'weight_plates', 'power_rack'],
    is_barbell_plate_loaded: true,
    category: 'strength',
    exercise_category: 'legs_quads_hamstrings',
    sub_category: 'legs_squats',
    difficulty: 'intermediate',
    mechanics: 'compound',
    suggested_sets_reps: '4 sets × 6–8 reps',
    instructions: 'Bar resting across upper traps, brace core, break simultaneously at knees and hips, hit below parallel depth, drive up through whole foot.',
    video_url_mock: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-barbell-front-squat',
    name: 'Barbell Front Squat (Clean Grip)',
    target_muscle: 'quads',
    secondary_muscles: ['core', 'glutes'],
    equipment_required: 'barbells',
    required_equipment_ids: ['barbells', 'weight_plates', 'power_rack'],
    is_barbell_plate_loaded: true,
    category: 'strength',
    exercise_category: 'legs_quads_hamstrings',
    sub_category: 'legs_squats',
    difficulty: 'advanced',
    mechanics: 'compound',
    suggested_sets_reps: '4 sets × 6 reps',
    instructions: 'Rest bar across anterior deltoids with high elbows parallel to floor, maintain upright vertical spine, squat deep between ankles.',
    video_url_mock: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-romanian-deadlift-barbell',
    name: 'Barbell Romanian Deadlift (RDL)',
    target_muscle: 'hamstrings',
    secondary_muscles: ['glutes', 'back'],
    equipment_required: 'barbells',
    required_equipment_ids: ['barbells', 'weight_plates'],
    is_barbell_plate_loaded: true,
    category: 'hypertrophy',
    exercise_category: 'legs_quads_hamstrings',
    sub_category: 'legs_hamstring_curls',
    difficulty: 'intermediate',
    mechanics: 'compound',
    suggested_sets_reps: '3 sets × 8–10 reps',
    instructions: 'Soft knee bend, push hips straight back into the wall behind you, lower bar shaving shins until intense hamstring stretch, drive hips forward.',
    video_url_mock: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-leg-press-45',
    name: '45-Degree Plate-Loaded Leg Press',
    target_muscle: 'quads',
    secondary_muscles: ['glutes', 'hamstrings'],
    equipment_required: 'leg_press',
    required_equipment_ids: ['leg_press', 'weight_plates'],
    is_barbell_plate_loaded: true,
    category: 'hypertrophy',
    exercise_category: 'legs_quads_hamstrings',
    sub_category: 'legs_squats',
    difficulty: 'beginner',
    mechanics: 'compound',
    suggested_sets_reps: '4 sets × 10–12 reps',
    instructions: 'Place feet mid-platform shoulder width, lower sled under control without rounding lower back off pad, press up without hyperextending knees.',
    video_url_mock: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80',
  },

  // ==========================================
  // 5. GLUTES & HIPS
  // ==========================================
  {
    id: 'ex-barbell-hip-thrust',
    name: 'Barbell Hip Thrust (Bench Supported)',
    target_muscle: 'glutes',
    secondary_muscles: ['hamstrings', 'quads'],
    equipment_required: 'barbells',
    required_equipment_ids: ['barbells', 'weight_plates', 'flat_bench'],
    is_barbell_plate_loaded: true,
    category: 'hypertrophy',
    exercise_category: 'glutes_hips',
    sub_category: 'glutes_hip_thrusts',
    difficulty: 'intermediate',
    mechanics: 'compound',
    suggested_sets_reps: '4 sets × 10–12 reps',
    instructions: 'Upper back against bench, barbell cushioned across pelvis, drive through heels into full hip extension, hold glute squeeze at top.',
    video_url_mock: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
  },

  // ==========================================
  // 6. ARMS & CORE & HIIT
  // ==========================================
  {
    id: 'ex-barbell-bicep-curl',
    name: 'Barbell / EZ-Bar Standing Bicep Curl',
    target_muscle: 'biceps',
    secondary_muscles: ['forearms'],
    equipment_required: 'barbells',
    required_equipment_ids: ['barbells', 'weight_plates'],
    is_barbell_plate_loaded: true,
    category: 'hypertrophy',
    exercise_category: 'arms_biceps_triceps',
    sub_category: 'arms_biceps_supinated',
    difficulty: 'beginner',
    mechanics: 'isolation',
    suggested_sets_reps: '3 sets × 8–10 reps',
    instructions: 'Keep elbows pinned to sides, curl barbell up through full range without swinging hips, lower under strict 3-second tension.',
    video_url_mock: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-skull-crushers-ez',
    name: 'Lying EZ-Bar Skullcrushers (Nosebreakers)',
    target_muscle: 'triceps',
    secondary_muscles: ['chest'],
    equipment_required: 'barbells',
    required_equipment_ids: ['ez_curl_bar', 'weight_plates', 'flat_bench'],
    is_barbell_plate_loaded: true,
    category: 'hypertrophy',
    exercise_category: 'arms_biceps_triceps',
    sub_category: 'arms_triceps_extensions',
    difficulty: 'intermediate',
    mechanics: 'isolation',
    suggested_sets_reps: '3 sets × 10–12 reps',
    instructions: 'Angle upper arms back 10 degrees past vertical, hinge at elbows lowering bar to crown of head, extend triceps.',
    video_url_mock: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-hanging-leg-raises',
    name: 'Hanging Straight Leg Raises',
    target_muscle: 'core',
    secondary_muscles: ['hips', 'forearms'],
    equipment_required: 'pull_up_bar',
    required_equipment_ids: ['pull_up_bar'],
    category: 'strength',
    exercise_category: 'core_abdominals',
    sub_category: 'core_hanging_raises',
    difficulty: 'intermediate',
    mechanics: 'isolation',
    suggested_sets_reps: '3 sets × 10–15 reps',
    instructions: 'Deadhang without swinging, posterior pelvic tilt, lift straight legs to horizontal (or toes to bar), slow 3-second descent.',
    video_url_mock: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-kettlebell-swings',
    name: 'Two-Handed Russian Kettlebell Swings',
    target_muscle: 'full_body_cardio',
    secondary_muscles: ['hamstrings', 'glutes', 'core', 'back'],
    equipment_required: 'kettlebells',
    required_equipment_ids: ['kettlebells'],
    category: 'hiit_interval',
    exercise_category: 'hiit_conditioning',
    sub_category: 'hiit_kettlebell_complex',
    difficulty: 'beginner',
    mechanics: 'compound',
    suggested_sets_reps: '4 sets × 20 swings',
    instructions: 'Hike bell high into groin, snap hips into explosive extension, float bell to chest height without lifting with arms.',
    video_url_mock: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ex-battle-ropes-waves',
    name: 'Alternating Battle Rope Waves',
    target_muscle: 'full_body_cardio',
    secondary_muscles: ['shoulders', 'core', 'forearms'],
    equipment_required: 'battle_rope',
    required_equipment_ids: ['battle_rope'],
    category: 'hiit_interval',
    exercise_category: 'hiit_conditioning',
    sub_category: 'hiit_ropes_cardio_gear',
    difficulty: 'beginner',
    mechanics: 'compound',
    suggested_sets_reps: '5 rounds × 30s work / 30s rest',
    instructions: 'Quarter squat stance, pump arms in rapid alternating whip motion sending continuous waves to the anchor.',
    video_url_mock: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
  },
];

// Helper to expand the catalog into hundreds of exercise variations across all 9 categories
function generateExpandedExercises(): ExerciseItem[] {
  const variations: ExerciseItem[] = [...MASTER_EXERCISE_DATABASE];
  const styles = [
    { suffix: ' (Rest-Pause Myo-Reps Overload)', cat: 'hypertrophy', reps: '3 sets × 12 + 4 + 4 reps' },
    { suffix: ' (3-Second Eccentric Tempo Focus)', cat: 'hypertrophy', reps: '3 sets × 8–10 reps (3-0-1-0)' },
    { suffix: ' (Heavy 5x5 Strength Protocol)', cat: 'strength', reps: '5 sets × 5 reps (85% 1RM)' },
    { suffix: ' (1.5 Rep Peak Isometric Squeeze)', cat: 'hypertrophy', reps: '3 sets × 10–12 reps' },
    { suffix: ' (High-Volume Drop Set Finisher)', cat: 'hypertrophy', reps: '3 sets × 10 reps + 50% drop' },
    { suffix: ' (Cluster Set Strength Density)', cat: 'strength', reps: '4 sets × 3+3+3 reps' },
    { suffix: ' (Iso-Hold 2-Sec Squeeze)', cat: 'hypertrophy', reps: '3 sets × 10–12 reps' },
    { suffix: ' (Tabata 20s/10s Max Interval)', cat: 'hiit_interval', reps: '8 rounds × 20s max effort' },
    { suffix: ' (Pyramid Ascending Overload)', cat: 'strength', reps: '4 sets × 12, 10, 8, 6 reps' },
    { suffix: ' (Deficit Stretch Range)', cat: 'hypertrophy', reps: '3 sets × 10–12 reps' },
  ];

  let idCounter = 1;
  for (let s = 0; s < styles.length; s++) {
    const style = styles[s];
    for (let b = 0; b < MASTER_EXERCISE_DATABASE.length; b++) {
      const base = MASTER_EXERCISE_DATABASE[b];
      idCounter++;
      variations.push({
        ...base,
        id: `${base.id}-var-${s + 1}-${idCounter}`,
        name: `${base.name}${style.suffix}`,
        suggested_sets_reps: style.reps,
        category: style.cat as any,
      });
    }
  }

  return variations;
}

export const COMPREHENSIVE_EXERCISE_DATABASE: ExerciseItem[] = generateExpandedExercises();
