import { FoodCategory, FoodSubCategoryMeta, FoodItem } from './types';

export interface FoodCategoryMeta {
  id: FoodCategory;
  name: string;
  shortLabel: string;
  icon: string;
  description: string;
  accentColor: string;
}

export function normalizeFoodCategory(category: string): FoodCategory {
  switch (category) {
    case 'protein':
      return 'poultry_meat';
    case 'carbohydrate':
      return 'grains_carbs';
    case 'fruit':
      return 'fruits';
    case 'vegetable':
      return 'vegetables';
    case 'healthy_fat':
      return 'nuts_fats_oils';
    case 'dairy_alternative':
      return 'dairy_eggs';
    case 'beverage':
      return 'beverages_hydration';
    case 'pantry_staple':
      return 'snacks_pantry';
    default:
      return (category as FoodCategory) || 'snacks_pantry';
  }
}

export const FOOD_CATEGORIES: FoodCategoryMeta[] = [
  {
    id: 'poultry_meat',
    name: 'Poultry & Lean Meats',
    shortLabel: 'Poultry & Meat',
    icon: '🍗',
    description: 'Chicken, turkey, beef steaks, lean ground meats, pork tenderloin & game',
    accentColor: '#f97316',
  },
  {
    id: 'fish_seafood',
    name: 'Fish & Seafood',
    shortLabel: 'Fish & Seafood',
    icon: '🐟',
    description: 'Wild salmon, cod, tuna, shrimp, halibut, tilapia, scallops & crab',
    accentColor: '#06b6d4',
  },
  {
    id: 'dairy_eggs',
    name: 'Eggs, Dairy & Plant Milks',
    shortLabel: 'Eggs & Dairy',
    icon: '🥚',
    description: 'Whole eggs, egg whites, Greek yogurt, cottage cheese & almond milk',
    accentColor: '#3b82f6',
  },
  {
    id: 'plant_protein',
    name: 'Plant Protein & Legumes',
    shortLabel: 'Plant Protein',
    icon: '🌱',
    description: 'Tofu, tempeh, edamame, black beans, chickpeas, lentils & seitan',
    accentColor: '#10b981',
  },
  {
    id: 'grains_carbs',
    name: 'Grains, Bread & Potatoes',
    shortLabel: 'Grains & Carbs',
    icon: '🍚',
    description: 'Rolled oats, jasmine rice, sweet potatoes, quinoa, whole grain bread & pasta',
    accentColor: '#eab308',
  },
  {
    id: 'fruits',
    name: 'Fruits & Berries',
    shortLabel: 'Fruits & Berries',
    icon: '🍓',
    description: 'Blueberries, strawberries, apples, bananas, watermelon & citrus',
    accentColor: '#ec4899',
  },
  {
    id: 'vegetables',
    name: 'Vegetables & Leafy Greens',
    shortLabel: 'Vegetables & Greens',
    icon: '🥦',
    description: 'Broccoli, spinach, asparagus, kale, bell peppers, carrots & zucchini',
    accentColor: '#22c55e',
  },
  {
    id: 'nuts_fats_oils',
    name: 'Healthy Fats, Nuts & Seeds',
    shortLabel: 'Nuts & Healthy Fats',
    icon: '🥑',
    description: 'Avocado, olive oil, almonds, walnuts, peanut butter, chia seeds & flax',
    accentColor: '#84cc16',
  },
  {
    id: 'beverages_hydration',
    name: 'Hydration & Beverages',
    shortLabel: 'Beverages',
    icon: '☕',
    description: 'Black coffee, green tea, sparkling water, coconut water & electrolytes',
    accentColor: '#6366f1',
  },
  {
    id: 'snacks_pantry',
    name: 'Pantry Staples & Snacks',
    shortLabel: 'Pantry & Snacks',
    icon: '🍯',
    description: 'Protein powders, rice cakes, honey, hummus, salsa, mustard & spices',
    accentColor: '#a855f7',
  },
];

export const FOOD_SUB_CATEGORIES: FoodSubCategoryMeta[] = [
  // 1. Poultry & Meats
  { id: 'chicken', parentId: 'poultry_meat', name: 'Chicken Cuts & Preps', icon: '🐔', description: 'Breasts, thighs, tenders, rotisserie & lean cuts' },
  { id: 'turkey', parentId: 'poultry_meat', name: 'Turkey & Ground Turkey', icon: '🦃', description: 'Lean ground turkey, cutlets & roast breast' },
  { id: 'beef', parentId: 'poultry_meat', name: 'Beef Steaks & Lean Roasts', icon: '🥩', description: 'Sirloin, tenderloin, flank & top round steaks' },
  { id: 'ground_meats', parentId: 'poultry_meat', name: 'Lean Ground Meats', icon: '🍔', description: '96/4, 90/10 beef, ground bison & pork' },
  { id: 'pork', parentId: 'poultry_meat', name: 'Lean Pork Cuts', icon: '🐖', description: 'Pork tenderloin, loin chops & Canadian bacon' },
  { id: 'game_lamb', parentId: 'poultry_meat', name: 'Bison, Lamb & Game', icon: '🦬', description: 'Bison sirloin, venison, lamb loin & elk' },
  { id: 'deli_meats', parentId: 'poultry_meat', name: 'Deli & Prepared Meats', icon: '🥓', description: 'Oven-roasted deli turkey, roast beef & ham' },

  // 2. Fish & Seafood
  { id: 'salmon_trout', parentId: 'fish_seafood', name: 'Salmon & Fatty Fish', icon: '🐟', description: 'Wild Atlantic, sockeye, king salmon & trout' },
  { id: 'white_fish', parentId: 'fish_seafood', name: 'Lean White Fish', icon: '🐟', description: 'Cod, halibut, tilapia, haddock & mahi mahi' },
  { id: 'tuna_swordfish', parentId: 'fish_seafood', name: 'Tuna & Fresh Steaks', icon: '🐟', description: 'Yellowfin ahi tuna, albacore & swordfish' },
  { id: 'shrimp_shellfish', parentId: 'fish_seafood', name: 'Shrimp & Prawns', icon: '🦐', description: 'Jumbo white shrimp, tiger prawns & pink shrimp' },
  { id: 'scallops_crab_lobster', parentId: 'fish_seafood', name: 'Scallops, Crab & Lobster', icon: '🦪', description: 'Sea scallops, king crab, lobster tail & clams' },
  { id: 'canned_seafood', parentId: 'fish_seafood', name: 'Canned & Preserved Fish', icon: '🥫', description: 'Canned tuna in water, wild sardines & mackerel' },

  // 3. Dairy, Eggs & Plant Milks
  { id: 'eggs', parentId: 'dairy_eggs', name: 'Whole Eggs & Egg Whites', icon: '🥚', description: 'Pasture eggs, liquid egg whites & boiled eggs' },
  { id: 'greek_yogurt', parentId: 'dairy_eggs', name: 'Greek Yogurt & Skyr', icon: '🥣', description: '0% Nonfat, 2% Low-fat Greek yogurt & Icelandic skyr' },
  { id: 'cottage_cheese', parentId: 'dairy_eggs', name: 'Cottage Cheese', icon: '🥣', description: 'Low-fat 2%, 4% whole milk & nonfat cottage cheese' },
  { id: 'cheeses', parentId: 'dairy_eggs', name: 'Cheeses & Hard Cheeses', icon: '🧀', description: 'Mozzarella string cheese, cheddar, feta & parmesan' },
  { id: 'dairy_milks', parentId: 'dairy_eggs', name: 'Dairy & Filtered Milks', icon: '🥛', description: 'Fairlife ultra-filtered skim milk & low-fat milk' },
  { id: 'plant_milks', parentId: 'dairy_eggs', name: 'Plant-Based Milks', icon: '🥛', description: 'Unsweetened almond milk, oat milk & soy milk' },

  // 4. Plant Protein & Legumes
  { id: 'tofu_tempeh', parentId: 'plant_protein', name: 'Tofu, Tempeh & Edamame', icon: '🥢', description: 'Extra firm tofu, soy tempeh & steamed edamame' },
  { id: 'beans', parentId: 'plant_protein', name: 'Black Beans & Legumes', icon: '🫘', description: 'Cooked black beans, pinto, kidney & cannellini' },
  { id: 'chickpeas_lentils', parentId: 'plant_protein', name: 'Chickpeas & Lentils', icon: '🥣', description: 'Garbanzo chickpeas, red, brown & green lentils' },
  { id: 'seitan_wheat', parentId: 'plant_protein', name: 'Seitan & Wheat Protein', icon: '🌾', description: 'Organic seitan strips, wheat gluten & grounds' },
  { id: 'super_plant_proteins', parentId: 'plant_protein', name: 'Super Seeds & Yeast', icon: '🌿', description: 'Nutritional yeast flakes, hemp hearts & spirulina' },

  // 5. Grains, Bread & Starchy Carbs
  { id: 'oats_cereals', parentId: 'grains_carbs', name: 'Oats & Hot Cereals', icon: '🥣', description: 'Rolled oats, steel-cut oats, cream of rice & oat bran' },
  { id: 'rice_grains', parentId: 'grains_carbs', name: 'Rice, Quinoa & Grains', icon: '🍚', description: 'Jasmine rice, brown basmati, quinoa & farro' },
  { id: 'potatoes_yams', parentId: 'grains_carbs', name: 'Potatoes & Sweet Yams', icon: '🥔', description: 'Sweet potatoes, russet, red bliss & butternut squash' },
  { id: 'breads_toast', parentId: 'grains_carbs', name: 'Artisan & Sourdough Breads', icon: '🍞', description: 'Sourdough, Ezekiel sprouted bread & bagel thins' },
  { id: 'pastas_noodles', parentId: 'grains_carbs', name: 'Pastas & Healthy Noodles', icon: '🍝', description: 'Whole wheat pasta, chickpea pasta & soba noodles' },
  { id: 'tortillas_wraps', parentId: 'grains_carbs', name: 'Tortillas & Flatbreads', icon: '🌮', description: 'Yellow corn tortillas, whole wheat wraps & pitas' },

  // 6. Fruits & Berries
  { id: 'berries', parentId: 'fruits', name: 'Berries & Super Berries', icon: '🫐', description: 'Blueberries, strawberries, raspberries & blackberries' },
  { id: 'orchard_fruits', parentId: 'fruits', name: 'Apples, Pears & Stone Fruit', icon: '🍎', description: 'Honeycrisp apples, pears, peaches & sweet cherries' },
  { id: 'tropical_fruits', parentId: 'fruits', name: 'Tropical Fruits & Bananas', icon: '🍌', description: 'Bananas, pineapple, mango, papaya & kiwi' },
  { id: 'melons', parentId: 'fruits', name: 'Melons & High-Water Fruit', icon: '🍉', description: 'Watermelon, cantaloupe & honeydew melon' },
  { id: 'citrus_fruits', parentId: 'fruits', name: 'Citrus Fruits', icon: '🍊', description: 'Navel oranges, clementines, grapefruit & lemons' },
  { id: 'grapes_figs', parentId: 'fruits', name: 'Grapes & Figs', icon: '🍇', description: 'Red seedless grapes, black mission figs & dates' },

  // 7. Vegetables & Leafy Greens
  { id: 'cruciferous_veg', parentId: 'vegetables', name: 'Cruciferous Vegetables', icon: '🥦', description: 'Broccoli, cauliflower, Brussels sprouts & cabbage' },
  { id: 'leafy_greens', parentId: 'vegetables', name: 'Leafy Salad Greens & Spinach', icon: '🥬', description: 'Baby spinach, kale, arugula, romaine & chard' },
  { id: 'root_veg', parentId: 'vegetables', name: 'Root Vegetables & Carrots', icon: '🥕', description: 'Carrots, red beets, radishes & parsnips' },
  { id: 'nightshades', parentId: 'vegetables', name: 'Peppers & Tomatoes', icon: '🫑', description: 'Bell peppers, cherry tomatoes & jalapeños' },
  { id: 'crisp_veg', parentId: 'vegetables', name: 'Crisp Vegetables & Asparagus', icon: '🥒', description: 'Cucumbers, asparagus, celery, zucchini & green beans' },
  { id: 'mushrooms_alliums', parentId: 'vegetables', name: 'Mushrooms & Alliums', icon: '🍄', description: 'Cremini mushrooms, white button, onions & garlic' },

  // 8. Healthy Fats, Nuts & Seeds
  { id: 'avocados_olives', parentId: 'nuts_fats_oils', name: 'Avocados & Olives', icon: '🥑', description: 'Hass avocados, Kalamata olives & fresh guacamole' },
  { id: 'whole_nuts', parentId: 'nuts_fats_oils', name: 'Whole Tree Nuts', icon: '🥜', description: 'Almonds, walnuts, cashews, pistachios & pecans' },
  { id: 'nut_butters', parentId: 'nuts_fats_oils', name: 'Natural Nut & Seed Butters', icon: '🥜', description: 'Peanut butter, almond butter & tahini' },
  { id: 'super_seeds', parentId: 'nuts_fats_oils', name: 'Super Seeds', icon: '🌻', description: 'Chia seeds, flaxseed meal, pumpkin & hemp seeds' },
  { id: 'healthy_oils', parentId: 'nuts_fats_oils', name: 'Cold-Pressed Oils & Ghee', icon: '🫒', description: 'Extra virgin olive oil, avocado oil & coconut oil' },

  // 9. Hydration & Beverages
  { id: 'coffee_espresso', parentId: 'beverages_hydration', name: 'Coffee & Espresso', icon: '☕', description: 'Black drip coffee, cold brew & double espresso' },
  { id: 'teas_infusions', parentId: 'beverages_hydration', name: 'Teas & Herbal Infusions', icon: '🍵', description: 'Green tea, matcha, black tea & chamomile' },
  { id: 'waters_sparkling', parentId: 'beverages_hydration', name: 'Sparkling & Mineral Waters', icon: '💧', description: 'Sparkling water, seltzer & San Pellegrino' },
  { id: 'functional_hydration', parentId: 'beverages_hydration', name: 'Electrolytes & Coconut Water', icon: '🥥', description: 'Pure coconut water & zero-sugar electrolyte hydrators' },

  // 10. Pantry Staples & Snacks
  { id: 'protein_powders', parentId: 'snacks_pantry', name: 'Protein Powders & RTDs', icon: '🥤', description: '100% Whey isolate, casein & plant protein' },
  { id: 'rice_cakes_snacks', parentId: 'snacks_pantry', name: 'Rice Cakes & Crispbreads', icon: '🍘', description: 'Organic plain rice cakes & whole grain crackers' },
  { id: 'condiments_sauces', parentId: 'snacks_pantry', name: 'Sauces, Salsas & Mustards', icon: '🌶️', description: 'Fresh salsa, Dijon mustard, hot sauce & balsamic' },
  { id: 'natural_sweeteners', parentId: 'snacks_pantry', name: 'Natural Honey & Maple Syrup', icon: '🍯', description: 'Raw wildflower honey, pure maple syrup & stevia' },
  { id: 'spices_seasonings', parentId: 'snacks_pantry', name: 'Spices & Pure Cocoa', icon: '🌿', description: 'Ceylon cinnamon, turmeric, cocoa powder & dark chocolate' },
];

export const COMPREHENSIVE_FOOD_DATABASE: FoodItem[] = [
  // =========================================================================
  // 1. POULTRY & LEAN MEATS
  // =========================================================================
  // --- Chicken Cuts ---
  {
    id: 'pm-chk-1',
    name: 'Boneless Skinless Chicken Breast (Raw)',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 120,
    protein_per_100g: 26.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-2',
    name: 'Grilled / Cooked Chicken Breast',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 165,
    protein_per_100g: 31.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 3.6,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-3',
    name: 'Boneless Skinless Chicken Thigh (Cooked)',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 177,
    protein_per_100g: 24.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 8.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-4',
    name: 'Chicken Tenderloins (Raw)',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 110,
    protein_per_100g: 24.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-5',
    name: 'Rotisserie Chicken Breast (Skin Removed)',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 140,
    protein_per_100g: 28.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 3.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-6',
    name: '99/1 Extra Lean Ground Chicken Breast',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 115,
    protein_per_100g: 25.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-7',
    name: '92/8 Lean Ground Chicken',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 150,
    protein_per_100g: 21.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 7.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },

  // --- Turkey ---
  {
    id: 'pm-trk-1',
    name: '93/7 Lean Ground Turkey',
    category: 'poultry_meat',
    sub_category: 'turkey',
    calories_per_100g: 152,
    protein_per_100g: 22.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 7.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-trk-2',
    name: '99/1 Extra Lean Ground Turkey Breast',
    category: 'poultry_meat',
    sub_category: 'turkey',
    calories_per_100g: 110,
    protein_per_100g: 26.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-trk-3',
    name: 'Turkey Breast Cutlet (Raw)',
    category: 'poultry_meat',
    sub_category: 'turkey',
    calories_per_100g: 114,
    protein_per_100g: 24.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-trk-4',
    name: 'Oven Roasted Turkey Breast',
    category: 'poultry_meat',
    sub_category: 'turkey',
    calories_per_100g: 135,
    protein_per_100g: 29.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 2.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-trk-5',
    name: 'Uncured Turkey Bacon (Cooked)',
    category: 'poultry_meat',
    sub_category: 'turkey',
    calories_per_100g: 218,
    protein_per_100g: 28.0,
    carbs_per_100g: 2.0,
    fat_per_100g: 11.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 60,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },

  // --- Beef & Steaks ---
  {
    id: 'pm-bf-1',
    name: 'Grass-Fed Sirloin Steak (Trimmed)',
    category: 'poultry_meat',
    sub_category: 'beef',
    calories_per_100g: 183,
    protein_per_100g: 27.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 8.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 170,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-bf-2',
    name: 'Beef Tenderloin / Filet Mignon',
    category: 'poultry_meat',
    sub_category: 'beef',
    calories_per_100g: 190,
    protein_per_100g: 26.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 9.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-bf-3',
    name: 'Flank Steak (Lean Trimmed)',
    category: 'poultry_meat',
    sub_category: 'beef',
    calories_per_100g: 192,
    protein_per_100g: 28.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 8.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-bf-4',
    name: 'Top Round Steak / London Broil',
    category: 'poultry_meat',
    sub_category: 'beef',
    calories_per_100g: 165,
    protein_per_100g: 29.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 4.8,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-bf-5',
    name: 'NY Strip Steak (Lean Choice Trimmed)',
    category: 'poultry_meat',
    sub_category: 'beef',
    calories_per_100g: 215,
    protein_per_100g: 26.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 12.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 170,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },

  // --- Ground Meats ---
  {
    id: 'pm-grd-1',
    name: '96/4 Extra Lean Ground Beef',
    category: 'poultry_meat',
    sub_category: 'ground_meats',
    calories_per_100g: 133,
    protein_per_100g: 22.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 4.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-grd-2',
    name: '90/10 Lean Ground Beef',
    category: 'poultry_meat',
    sub_category: 'ground_meats',
    calories_per_100g: 176,
    protein_per_100g: 20.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 10.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-grd-3',
    name: 'Lean Ground Bison (90/10)',
    category: 'poultry_meat',
    sub_category: 'ground_meats',
    calories_per_100g: 146,
    protein_per_100g: 20.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 7.2,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-grd-4',
    name: '90/10 Lean Ground Pork',
    category: 'poultry_meat',
    sub_category: 'ground_meats',
    calories_per_100g: 172,
    protein_per_100g: 19.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 10.2,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },

  // --- Lean Pork ---
  {
    id: 'pm-prk-1',
    name: 'Pork Tenderloin Roast (Trimmed)',
    category: 'poultry_meat',
    sub_category: 'pork',
    calories_per_100g: 143,
    protein_per_100g: 26.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 3.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-prk-2',
    name: 'Center Cut Pork Chops (Boneless, Lean)',
    category: 'poultry_meat',
    sub_category: 'pork',
    calories_per_100g: 165,
    protein_per_100g: 25.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 6.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-prk-3',
    name: 'Canadian Bacon (Lean Back Bacon)',
    category: 'poultry_meat',
    sub_category: 'pork',
    calories_per_100g: 157,
    protein_per_100g: 20.5,
    carbs_per_100g: 1.5,
    fat_per_100g: 7.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 60,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },

  // --- Game & Lamb ---
  {
    id: 'pm-gam-1',
    name: 'Bison Top Sirloin Steak',
    category: 'poultry_meat',
    sub_category: 'game_lamb',
    calories_per_100g: 145,
    protein_per_100g: 28.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 3.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-gam-2',
    name: 'Venison Steak / Roast (Lean)',
    category: 'poultry_meat',
    sub_category: 'game_lamb',
    calories_per_100g: 120,
    protein_per_100g: 23.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 2.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-gam-3',
    name: 'Lamb Loin Chops (Lean Trimmed)',
    category: 'poultry_meat',
    sub_category: 'game_lamb',
    calories_per_100g: 198,
    protein_per_100g: 24.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 10.8,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },

  // --- Deli Meats ---
  {
    id: 'pm-dli-1',
    name: 'Oven-Roasted Deli Turkey Breast',
    category: 'poultry_meat',
    sub_category: 'deli_meats',
    calories_per_100g: 104,
    protein_per_100g: 17.5,
    carbs_per_100g: 4.0,
    fat_per_100g: 2.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-dli-2',
    name: 'Lean Roast Beef Deli Slices',
    category: 'poultry_meat',
    sub_category: 'deli_meats',
    calories_per_100g: 125,
    protein_per_100g: 20.0,
    carbs_per_100g: 2.0,
    fat_per_100g: 4.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },

  // =========================================================================
  // 2. FISH & SEAFOOD
  // =========================================================================
  // --- Salmon & Fatty Fish ---
  {
    id: 'fs-sal-1',
    name: 'Wild Atlantic Salmon Fillet',
    category: 'fish_seafood',
    sub_category: 'salmon_trout',
    calories_per_100g: 208,
    protein_per_100g: 20.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 13.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fatty_protein',
  },
  {
    id: 'fs-sal-2',
    name: 'Wild Alaskan Sockeye Salmon',
    category: 'fish_seafood',
    sub_category: 'salmon_trout',
    calories_per_100g: 169,
    protein_per_100g: 22.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 8.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fatty_protein',
  },
  {
    id: 'fs-sal-3',
    name: 'Rainbow Trout Fillet',
    category: 'fish_seafood',
    sub_category: 'salmon_trout',
    calories_per_100g: 141,
    protein_per_100g: 20.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 6.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fatty_protein',
  },
  {
    id: 'fs-sal-4',
    name: 'Smoked Salmon / Nova Lox',
    category: 'fish_seafood',
    sub_category: 'salmon_trout',
    calories_per_100g: 117,
    protein_per_100g: 18.3,
    carbs_per_100g: 0.0,
    fat_per_100g: 4.3,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 85,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fatty_protein',
  },

  // --- White Fish ---
  {
    id: 'fs-wht-1',
    name: 'Atlantic Cod Fillet',
    category: 'fish_seafood',
    sub_category: 'white_fish',
    calories_per_100g: 82,
    protein_per_100g: 18.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.7,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 170,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-wht-2',
    name: 'Fresh Tilapia Fillet',
    category: 'fish_seafood',
    sub_category: 'white_fish',
    calories_per_100g: 96,
    protein_per_100g: 20.1,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.7,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-wht-3',
    name: 'Pacific Halibut Fillet',
    category: 'fish_seafood',
    sub_category: 'white_fish',
    calories_per_100g: 110,
    protein_per_100g: 23.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.6,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-wht-4',
    name: 'Mahi Mahi Fillet',
    category: 'fish_seafood',
    sub_category: 'white_fish',
    calories_per_100g: 85,
    protein_per_100g: 18.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.7,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-wht-5',
    name: 'Haddock Fillet',
    category: 'fish_seafood',
    sub_category: 'white_fish',
    calories_per_100g: 90,
    protein_per_100g: 20.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.7,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },

  // --- Tuna & Steaks ---
  {
    id: 'fs-tna-1',
    name: 'Fresh Yellowfin Ahi Tuna Steak',
    category: 'fish_seafood',
    sub_category: 'tuna_swordfish',
    calories_per_100g: 130,
    protein_per_100g: 29.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-tna-2',
    name: 'Swordfish Steak',
    category: 'fish_seafood',
    sub_category: 'tuna_swordfish',
    calories_per_100g: 144,
    protein_per_100g: 20.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 6.6,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },

  // --- Shrimp & Prawns ---
  {
    id: 'fs-shm-1',
    name: 'Raw Jumbo White Shrimp (Peeled)',
    category: 'fish_seafood',
    sub_category: 'shrimp_shellfish',
    calories_per_100g: 85,
    protein_per_100g: 20.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-shm-2',
    name: 'Wild Tiger Prawns (Steamed)',
    category: 'fish_seafood',
    sub_category: 'shrimp_shellfish',
    calories_per_100g: 99,
    protein_per_100g: 24.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.3,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },

  // --- Scallops, Crab, Lobster ---
  {
    id: 'fs-scl-1',
    name: 'Wild Sea Scallops (Raw)',
    category: 'fish_seafood',
    sub_category: 'scallops_crab_lobster',
    calories_per_100g: 69,
    protein_per_100g: 12.0,
    carbs_per_100g: 3.2,
    fat_per_100g: 0.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-scl-2',
    name: 'Wild King Crab Meat (Steamed)',
    category: 'fish_seafood',
    sub_category: 'scallops_crab_lobster',
    calories_per_100g: 84,
    protein_per_100g: 18.3,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.6,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 140,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-scl-3',
    name: 'Maine Lobster Tail Meat (Steamed)',
    category: 'fish_seafood',
    sub_category: 'scallops_crab_lobster',
    calories_per_100g: 89,
    protein_per_100g: 19.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.9,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 140,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },

  // --- Canned Seafood ---
  {
    id: 'fs-can-1',
    name: 'Canned Chunk Light Tuna (in Water)',
    category: 'fish_seafood',
    sub_category: 'canned_seafood',
    calories_per_100g: 116,
    protein_per_100g: 25.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.8,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-can-2',
    name: 'Canned Solid White Albacore (in Water)',
    category: 'fish_seafood',
    sub_category: 'canned_seafood',
    calories_per_100g: 128,
    protein_per_100g: 27.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 2.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-can-3',
    name: 'Wild Sardines (in Spring Water)',
    category: 'fish_seafood',
    sub_category: 'canned_seafood',
    calories_per_100g: 208,
    protein_per_100g: 24.6,
    carbs_per_100g: 0.0,
    fat_per_100g: 11.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 90,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'fatty_protein',
  },

  // =========================================================================
  // 3. EGGS, DAIRY & PLANT MILKS
  // =========================================================================
  // --- Eggs ---
  {
    id: 'de-egg-1',
    name: 'Pasture-Raised Whole Eggs',
    category: 'dairy_eggs',
    sub_category: 'eggs',
    calories_per_100g: 143,
    protein_per_100g: 12.6,
    carbs_per_100g: 0.7,
    fat_per_100g: 9.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'egg_source',
  },
  {
    id: 'de-egg-2',
    name: '100% Pure Liquid Egg Whites',
    category: 'dairy_eggs',
    sub_category: 'eggs',
    calories_per_100g: 52,
    protein_per_100g: 11.0,
    carbs_per_100g: 0.7,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'de-egg-3',
    name: 'Hard-Boiled Egg',
    category: 'dairy_eggs',
    sub_category: 'eggs',
    calories_per_100g: 155,
    protein_per_100g: 12.6,
    carbs_per_100g: 1.1,
    fat_per_100g: 10.6,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 50,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'egg_source',
  },

  // --- Greek Yogurt & Skyr ---
  {
    id: 'de-yog-1',
    name: 'Non-Fat Plain Greek Yogurt (0%)',
    category: 'dairy_eggs',
    sub_category: 'greek_yogurt',
    calories_per_100g: 59,
    protein_per_100g: 10.3,
    carbs_per_100g: 3.6,
    fat_per_100g: 0.4,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 200,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },
  {
    id: 'de-yog-2',
    name: '2% Low-Fat Greek Yogurt (Plain)',
    category: 'dairy_eggs',
    sub_category: 'greek_yogurt',
    calories_per_100g: 73,
    protein_per_100g: 10.0,
    carbs_per_100g: 4.0,
    fat_per_100g: 2.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 200,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },
  {
    id: 'de-yog-3',
    name: 'Icelandic Skyr (Plain Nonfat)',
    category: 'dairy_eggs',
    sub_category: 'greek_yogurt',
    calories_per_100g: 63,
    protein_per_100g: 11.0,
    carbs_per_100g: 3.8,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 170,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },

  // --- Cottage Cheese ---
  {
    id: 'de-cot-1',
    name: 'Low-Fat Cottage Cheese (2% Milkfat)',
    category: 'dairy_eggs',
    sub_category: 'cottage_cheese',
    calories_per_100g: 81,
    protein_per_100g: 11.0,
    carbs_per_100g: 4.7,
    fat_per_100g: 2.3,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },
  {
    id: 'de-cot-2',
    name: 'Fat-Free Cottage Cheese (0%)',
    category: 'dairy_eggs',
    sub_category: 'cottage_cheese',
    calories_per_100g: 72,
    protein_per_100g: 12.5,
    carbs_per_100g: 4.5,
    fat_per_100g: 0.3,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },

  // --- Cheeses ---
  {
    id: 'de-chs-1',
    name: 'Part-Skim Mozzarella String Cheese',
    category: 'dairy_eggs',
    sub_category: 'cheeses',
    calories_per_100g: 280,
    protein_per_100g: 24.0,
    carbs_per_100g: 2.5,
    fat_per_100g: 20.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },
  {
    id: 'de-chs-2',
    name: 'Sharp Cheddar Cheese',
    category: 'dairy_eggs',
    sub_category: 'cheeses',
    calories_per_100g: 403,
    protein_per_100g: 25.0,
    carbs_per_100g: 1.3,
    fat_per_100g: 33.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'healthy_fat',
  },
  {
    id: 'de-chs-3',
    name: 'Crumbled Feta Cheese',
    category: 'dairy_eggs',
    sub_category: 'cheeses',
    calories_per_100g: 264,
    protein_per_100g: 14.2,
    carbs_per_100g: 4.1,
    fat_per_100g: 21.3,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'healthy_fat',
  },
  {
    id: 'de-chs-4',
    name: 'Aged Parmesan Cheese (Grated)',
    category: 'dairy_eggs',
    sub_category: 'cheeses',
    calories_per_100g: 431,
    protein_per_100g: 38.5,
    carbs_per_100g: 4.1,
    fat_per_100g: 28.6,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 20,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'healthy_fat',
  },

  // --- Milks & Plant Milks ---
  {
    id: 'de-mlk-1',
    name: 'Fairlife Ultra-Filtered Skim Milk',
    category: 'dairy_eggs',
    sub_category: 'dairy_milks',
    calories_per_100g: 35,
    protein_per_100g: 5.4,
    carbs_per_100g: 2.5,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },
  {
    id: 'de-mlk-2',
    name: 'Unsweetened Almond Milk',
    category: 'dairy_eggs',
    sub_category: 'plant_milks',
    calories_per_100g: 15,
    protein_per_100g: 0.6,
    carbs_per_100g: 0.3,
    fat_per_100g: 1.2,
    fiber_per_100g: 0.2,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'de-mlk-3',
    name: 'Unsweetened Oat Milk',
    category: 'dairy_eggs',
    sub_category: 'plant_milks',
    calories_per_100g: 45,
    protein_per_100g: 1.0,
    carbs_per_100g: 6.5,
    fat_per_100g: 1.5,
    fiber_per_100g: 0.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'de-mlk-4',
    name: 'Unsweetened Organic Soy Milk',
    category: 'dairy_eggs',
    sub_category: 'plant_milks',
    calories_per_100g: 33,
    protein_per_100g: 3.3,
    carbs_per_100g: 1.2,
    fat_per_100g: 1.7,
    fiber_per_100g: 0.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },

  // =========================================================================
  // 4. PLANT PROTEIN & LEGUMES
  // =========================================================================
  {
    id: 'pp-tof-1',
    name: 'Organic Extra Firm Tofu',
    category: 'plant_protein',
    sub_category: 'tofu_tempeh',
    calories_per_100g: 83,
    protein_per_100g: 10.0,
    carbs_per_100g: 1.5,
    fat_per_100g: 5.0,
    fiber_per_100g: 0.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'plant_protein',
  },
  {
    id: 'pp-tof-2',
    name: 'Organic Soy Tempeh',
    category: 'plant_protein',
    sub_category: 'tofu_tempeh',
    calories_per_100g: 192,
    protein_per_100g: 20.3,
    carbs_per_100g: 7.6,
    fat_per_100g: 10.8,
    fiber_per_100g: 5.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'plant_protein',
  },
  {
    id: 'pp-tof-3',
    name: 'Steamed Edamame (Shelled Beans)',
    category: 'plant_protein',
    sub_category: 'tofu_tempeh',
    calories_per_100g: 121,
    protein_per_100g: 11.9,
    carbs_per_100g: 8.9,
    fat_per_100g: 5.2,
    fiber_per_100g: 5.2,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'plant_protein',
  },
  {
    id: 'pp-ben-1',
    name: 'Cooked Black Beans',
    category: 'plant_protein',
    sub_category: 'beans',
    calories_per_100g: 132,
    protein_per_100g: 8.9,
    carbs_per_100g: 23.7,
    fat_per_100g: 0.5,
    fiber_per_100g: 8.7,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'pp-ben-2',
    name: 'Cooked Pinto Beans',
    category: 'plant_protein',
    sub_category: 'beans',
    calories_per_100g: 143,
    protein_per_100g: 9.0,
    carbs_per_100g: 26.2,
    fat_per_100g: 0.7,
    fiber_per_100g: 9.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'pp-chk-1',
    name: 'Cooked Chickpeas (Garbanzo)',
    category: 'plant_protein',
    sub_category: 'chickpeas_lentils',
    calories_per_100g: 164,
    protein_per_100g: 8.9,
    carbs_per_100g: 27.4,
    fat_per_100g: 2.6,
    fiber_per_100g: 7.6,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'pp-len-1',
    name: 'Cooked Red Lentils',
    category: 'plant_protein',
    sub_category: 'chickpeas_lentils',
    calories_per_100g: 116,
    protein_per_100g: 9.0,
    carbs_per_100g: 20.0,
    fat_per_100g: 0.4,
    fiber_per_100g: 7.9,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'pp-len-2',
    name: 'Cooked Brown Lentils',
    category: 'plant_protein',
    sub_category: 'chickpeas_lentils',
    calories_per_100g: 115,
    protein_per_100g: 9.0,
    carbs_per_100g: 20.1,
    fat_per_100g: 0.4,
    fiber_per_100g: 7.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'pp-stn-1',
    name: 'Organic Traditional Seitan Strips',
    category: 'plant_protein',
    sub_category: 'seitan_wheat',
    calories_per_100g: 140,
    protein_per_100g: 25.0,
    carbs_per_100g: 5.0,
    fat_per_100g: 1.5,
    fiber_per_100g: 1.0,
    is_gluten_free: false,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pp-nut-1',
    name: 'Nutritional Yeast Flakes',
    category: 'plant_protein',
    sub_category: 'super_plant_proteins',
    calories_per_100g: 380,
    protein_per_100g: 50.0,
    carbs_per_100g: 35.0,
    fat_per_100g: 5.0,
    fiber_per_100g: 25.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 15,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'powder_protein',
  },

  // =========================================================================
  // 5. GRAINS, BREAD & STARCHY CARBS
  // =========================================================================
  // --- Oats & Cereals ---
  {
    id: 'gc-oat-1',
    name: 'Certified Gluten-Free Rolled Oats',
    category: 'grains_carbs',
    sub_category: 'oats_cereals',
    calories_per_100g: 379,
    protein_per_100g: 13.2,
    carbs_per_100g: 67.7,
    fat_per_100g: 6.5,
    fiber_per_100g: 10.1,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 60,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-oat-2',
    name: 'Steel-Cut Oats (Dry)',
    category: 'grains_carbs',
    sub_category: 'oats_cereals',
    calories_per_100g: 375,
    protein_per_100g: 12.5,
    carbs_per_100g: 68.0,
    fat_per_100g: 6.0,
    fiber_per_100g: 10.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 50,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-oat-3',
    name: 'Cream of Rice Hot Cereal (Dry)',
    category: 'grains_carbs',
    sub_category: 'oats_cereals',
    calories_per_100g: 360,
    protein_per_100g: 7.0,
    carbs_per_100g: 80.0,
    fat_per_100g: 0.5,
    fiber_per_100g: 1.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 45,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },

  // --- Rice & Grains ---
  {
    id: 'gc-ric-1',
    name: 'Steamed Jasmine White Rice',
    category: 'grains_carbs',
    sub_category: 'rice_grains',
    calories_per_100g: 130,
    protein_per_100g: 2.7,
    carbs_per_100g: 28.2,
    fat_per_100g: 0.3,
    fiber_per_100g: 0.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 180,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-ric-2',
    name: 'Cooked Brown Basmati Rice',
    category: 'grains_carbs',
    sub_category: 'rice_grains',
    calories_per_100g: 123,
    protein_per_100g: 2.7,
    carbs_per_100g: 25.6,
    fat_per_100g: 1.0,
    fiber_per_100g: 1.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 180,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-ric-3',
    name: 'Organic Tri-Color Quinoa (Cooked)',
    category: 'grains_carbs',
    sub_category: 'rice_grains',
    calories_per_100g: 120,
    protein_per_100g: 4.4,
    carbs_per_100g: 21.3,
    fat_per_100g: 1.9,
    fiber_per_100g: 2.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },

  // --- Potatoes & Yams ---
  {
    id: 'gc-pot-1',
    name: 'Baked Garnet Sweet Potato',
    category: 'grains_carbs',
    sub_category: 'potatoes_yams',
    calories_per_100g: 90,
    protein_per_100g: 2.0,
    carbs_per_100g: 20.7,
    fat_per_100g: 0.2,
    fiber_per_100g: 3.3,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 200,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-pot-2',
    name: 'Boiled Russet / Idaho Potatoes',
    category: 'grains_carbs',
    sub_category: 'potatoes_yams',
    calories_per_100g: 87,
    protein_per_100g: 1.9,
    carbs_per_100g: 20.1,
    fat_per_100g: 0.1,
    fiber_per_100g: 1.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 200,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-pot-3',
    name: 'Red Baby Potatoes (Roasted)',
    category: 'grains_carbs',
    sub_category: 'potatoes_yams',
    calories_per_100g: 89,
    protein_per_100g: 2.2,
    carbs_per_100g: 20.0,
    fat_per_100g: 0.2,
    fiber_per_100g: 2.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 180,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'complex_carb',
  },

  // --- Breads ---
  {
    id: 'gc-brd-1',
    name: '100% Sourdough Artisan Bread Slice',
    category: 'grains_carbs',
    sub_category: 'breads_toast',
    calories_per_100g: 240,
    protein_per_100g: 8.5,
    carbs_per_100g: 48.0,
    fat_per_100g: 1.2,
    fiber_per_100g: 2.5,
    is_gluten_free: false,
    is_dairy_free: true,
    serving_size_g: 50,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-brd-2',
    name: 'Ezekiel 4:9 Sprouted Grain Bread',
    category: 'grains_carbs',
    sub_category: 'breads_toast',
    calories_per_100g: 235,
    protein_per_100g: 14.0,
    carbs_per_100g: 44.0,
    fat_per_100g: 1.5,
    fiber_per_100g: 7.5,
    is_gluten_free: false,
    is_dairy_free: true,
    serving_size_g: 45,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-brd-3',
    name: 'Plain Bagel Thins',
    category: 'grains_carbs',
    sub_category: 'breads_toast',
    calories_per_100g: 240,
    protein_per_100g: 10.0,
    carbs_per_100g: 48.0,
    fat_per_100g: 1.0,
    fiber_per_100g: 4.0,
    is_gluten_free: false,
    is_dairy_free: true,
    serving_size_g: 46,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },

  // --- Pastas & Tortillas ---
  {
    id: 'gc-pst-1',
    name: 'Cooked Whole Wheat Penne Pasta',
    category: 'grains_carbs',
    sub_category: 'pastas_noodles',
    calories_per_100g: 124,
    protein_per_100g: 5.3,
    carbs_per_100g: 26.5,
    fat_per_100g: 0.5,
    fiber_per_100g: 3.9,
    is_gluten_free: false,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-pst-2',
    name: 'Chickpea Pasta (Banza Cooked)',
    category: 'grains_carbs',
    sub_category: 'pastas_noodles',
    calories_per_100g: 150,
    protein_per_100g: 9.5,
    carbs_per_100g: 24.0,
    fat_per_100g: 2.2,
    fiber_per_100g: 4.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 140,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-tor-1',
    name: 'Yellow Corn Tortillas',
    category: 'grains_carbs',
    sub_category: 'tortillas_wraps',
    calories_per_100g: 218,
    protein_per_100g: 5.7,
    carbs_per_100g: 45.0,
    fat_per_100g: 2.9,
    fiber_per_100g: 6.3,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 50,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },

  // =========================================================================
  // 6. FRUITS & BERRIES
  // =========================================================================
  {
    id: 'fb-ber-1',
    name: 'Fresh Blueberries',
    category: 'fruits',
    sub_category: 'berries',
    calories_per_100g: 57,
    protein_per_100g: 0.7,
    carbs_per_100g: 14.5,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 125,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-ber-2',
    name: 'Fresh Strawberries',
    category: 'fruits',
    sub_category: 'berries',
    calories_per_100g: 32,
    protein_per_100g: 0.7,
    carbs_per_100g: 7.7,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-ber-3',
    name: 'Fresh Raspberries',
    category: 'fruits',
    sub_category: 'berries',
    calories_per_100g: 52,
    protein_per_100g: 1.2,
    carbs_per_100g: 11.9,
    fat_per_100g: 0.7,
    fiber_per_100g: 6.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 125,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-ber-4',
    name: 'Fresh Blackberries',
    category: 'fruits',
    sub_category: 'berries',
    calories_per_100g: 43,
    protein_per_100g: 1.4,
    carbs_per_100g: 9.6,
    fat_per_100g: 0.5,
    fiber_per_100g: 5.3,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 125,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-orc-1',
    name: 'Honeycrisp Apple (Medium)',
    category: 'fruits',
    sub_category: 'orchard_fruits',
    calories_per_100g: 52,
    protein_per_100g: 0.3,
    carbs_per_100g: 13.8,
    fat_per_100g: 0.2,
    fiber_per_100g: 2.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 180,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-orc-2',
    name: 'Sweet Dark Cherries',
    category: 'fruits',
    sub_category: 'orchard_fruits',
    calories_per_100g: 63,
    protein_per_100g: 1.1,
    carbs_per_100g: 16.0,
    fat_per_100g: 0.2,
    fiber_per_100g: 2.1,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 140,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-trp-1',
    name: 'Fresh Cavendish Banana',
    category: 'fruits',
    sub_category: 'tropical_fruits',
    calories_per_100g: 89,
    protein_per_100g: 1.1,
    carbs_per_100g: 22.8,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.6,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-trp-2',
    name: 'Fresh Pineapple Chunks',
    category: 'fruits',
    sub_category: 'tropical_fruits',
    calories_per_100g: 50,
    protein_per_100g: 0.5,
    carbs_per_100g: 13.1,
    fat_per_100g: 0.1,
    fiber_per_100g: 1.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-mel-1',
    name: 'Fresh Watermelon Slices',
    category: 'fruits',
    sub_category: 'melons',
    calories_per_100g: 30,
    protein_per_100g: 0.6,
    carbs_per_100g: 7.6,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 200,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-cit-1',
    name: 'Navel Orange',
    category: 'fruits',
    sub_category: 'citrus_fruits',
    calories_per_100g: 47,
    protein_per_100g: 0.9,
    carbs_per_100g: 11.8,
    fat_per_100g: 0.1,
    fiber_per_100g: 2.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },

  // =========================================================================
  // 7. VEGETABLES & LEAFY GREENS
  // =========================================================================
  {
    id: 'vg-cru-1',
    name: 'Fresh Steamed Broccoli Florets',
    category: 'vegetables',
    sub_category: 'cruciferous_veg',
    calories_per_100g: 35,
    protein_per_100g: 2.4,
    carbs_per_100g: 7.2,
    fat_per_100g: 0.4,
    fiber_per_100g: 2.6,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'cruciferous_veg',
  },
  {
    id: 'vg-cru-2',
    name: 'Steamed Cauliflower Florets',
    category: 'vegetables',
    sub_category: 'cruciferous_veg',
    calories_per_100g: 25,
    protein_per_100g: 1.9,
    carbs_per_100g: 5.0,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'cruciferous_veg',
  },
  {
    id: 'vg-cru-3',
    name: 'Brussels Sprouts (Halved & Roasted)',
    category: 'vegetables',
    sub_category: 'cruciferous_veg',
    calories_per_100g: 43,
    protein_per_100g: 3.4,
    carbs_per_100g: 9.0,
    fat_per_100g: 0.3,
    fiber_per_100g: 3.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'cruciferous_veg',
  },
  {
    id: 'vg-lfg-1',
    name: 'Organic Baby Spinach (Raw/Steamed)',
    category: 'vegetables',
    sub_category: 'leafy_greens',
    calories_per_100g: 23,
    protein_per_100g: 2.9,
    carbs_per_100g: 3.6,
    fat_per_100g: 0.4,
    fiber_per_100g: 2.2,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'leafy_veg',
  },
  {
    id: 'vg-lfg-2',
    name: 'Tuscan Lacinato Kale (Raw/Cooked)',
    category: 'vegetables',
    sub_category: 'leafy_greens',
    calories_per_100g: 49,
    protein_per_100g: 4.3,
    carbs_per_100g: 8.8,
    fat_per_100g: 0.9,
    fiber_per_100g: 3.6,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'leafy_veg',
  },
  {
    id: 'vg-csp-1',
    name: 'Fresh Green Asparagus Spears',
    category: 'vegetables',
    sub_category: 'crisp_veg',
    calories_per_100g: 20,
    protein_per_100g: 2.2,
    carbs_per_100g: 3.9,
    fat_per_100g: 0.1,
    fiber_per_100g: 2.1,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },
  {
    id: 'vg-csp-2',
    name: 'Zucchini / Courgette Slices',
    category: 'vegetables',
    sub_category: 'crisp_veg',
    calories_per_100g: 17,
    protein_per_100g: 1.2,
    carbs_per_100g: 3.1,
    fat_per_100g: 0.3,
    fiber_per_100g: 1.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },
  {
    id: 'vg-ngt-1',
    name: 'Sweet Red Bell Peppers (Sliced)',
    category: 'vegetables',
    sub_category: 'nightshades',
    calories_per_100g: 31,
    protein_per_100g: 1.0,
    carbs_per_100g: 6.0,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.1,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },

  // =========================================================================
  // 8. HEALTHY FATS, NUTS & SEEDS
  // =========================================================================
  {
    id: 'hf-avo-1',
    name: 'Fresh Hass Avocado',
    category: 'nuts_fats_oils',
    sub_category: 'avocados_olives',
    calories_per_100g: 160,
    protein_per_100g: 2.0,
    carbs_per_100g: 8.5,
    fat_per_100g: 14.7,
    fiber_per_100g: 6.7,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 75,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'healthy_fat',
  },
  {
    id: 'hf-oil-1',
    name: 'Extra Virgin First Cold-Pressed Olive Oil',
    category: 'nuts_fats_oils',
    sub_category: 'healthy_oils',
    calories_per_100g: 884,
    protein_per_100g: 0.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 100.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 15,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'cooking_fat',
  },
  {
    id: 'hf-oil-2',
    name: 'Pure Avocado Oil',
    category: 'nuts_fats_oils',
    sub_category: 'healthy_oils',
    calories_per_100g: 884,
    protein_per_100g: 0.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 100.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 15,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'cooking_fat',
  },
  {
    id: 'hf-nut-1',
    name: 'Raw Whole Almonds',
    category: 'nuts_fats_oils',
    sub_category: 'whole_nuts',
    calories_per_100g: 579,
    protein_per_100g: 21.2,
    carbs_per_100g: 21.6,
    fat_per_100g: 49.9,
    fiber_per_100g: 12.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'nut_fat',
  },
  {
    id: 'hf-nut-2',
    name: 'Raw English Walnut Halves',
    category: 'nuts_fats_oils',
    sub_category: 'whole_nuts',
    calories_per_100g: 654,
    protein_per_100g: 15.2,
    carbs_per_100g: 13.7,
    fat_per_100g: 65.2,
    fiber_per_100g: 6.7,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'nut_fat',
  },
  {
    id: 'hf-but-1',
    name: 'Natural Creamy Peanut Butter (100% Peanuts)',
    category: 'nuts_fats_oils',
    sub_category: 'nut_butters',
    calories_per_100g: 588,
    protein_per_100g: 25.0,
    carbs_per_100g: 20.0,
    fat_per_100g: 50.0,
    fiber_per_100g: 8.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 32,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'nut_fat',
  },
  {
    id: 'hf-but-2',
    name: 'Natural Creamy Almond Butter',
    category: 'nuts_fats_oils',
    sub_category: 'nut_butters',
    calories_per_100g: 614,
    protein_per_100g: 21.0,
    carbs_per_100g: 19.0,
    fat_per_100g: 55.5,
    fiber_per_100g: 10.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 32,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'nut_fat',
  },
  {
    id: 'hf-sed-1',
    name: 'Organic Whole Chia Seeds',
    category: 'nuts_fats_oils',
    sub_category: 'super_seeds',
    calories_per_100g: 486,
    protein_per_100g: 16.5,
    carbs_per_100g: 42.1,
    fat_per_100g: 30.7,
    fiber_per_100g: 34.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 20,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'healthy_fat',
  },
  {
    id: 'hf-sed-2',
    name: 'Ground Golden Flaxseed Meal',
    category: 'nuts_fats_oils',
    sub_category: 'super_seeds',
    calories_per_100g: 534,
    protein_per_100g: 18.3,
    carbs_per_100g: 28.9,
    fat_per_100g: 42.2,
    fiber_per_100g: 27.3,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 15,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'healthy_fat',
  },
  {
    id: 'hf-sed-3',
    name: 'Raw Pumpkin Seeds (Pepitas)',
    category: 'nuts_fats_oils',
    sub_category: 'super_seeds',
    calories_per_100g: 559,
    protein_per_100g: 30.2,
    carbs_per_100g: 10.7,
    fat_per_100g: 49.0,
    fiber_per_100g: 6.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'nut_fat',
  },

  // =========================================================================
  // 9. BEVERAGES & HYDRATION
  // =========================================================================
  {
    id: 'bv-cof-1',
    name: 'Black Drip Coffee (Unsweetened)',
    category: 'beverages_hydration',
    sub_category: 'coffee_espresso',
    calories_per_100g: 2,
    protein_per_100g: 0.3,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'bv-tea-1',
    name: 'Organic Green Tea (Brewed Unsweetened)',
    category: 'beverages_hydration',
    sub_category: 'teas_infusions',
    calories_per_100g: 1,
    protein_per_100g: 0.2,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'bv-wat-1',
    name: 'Pure Sparkling Water / Seltzer (0 Cal)',
    category: 'beverages_hydration',
    sub_category: 'waters_sparkling',
    calories_per_100g: 0,
    protein_per_100g: 0.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 355,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'bv-coc-1',
    name: '100% Pure Coconut Water',
    category: 'beverages_hydration',
    sub_category: 'functional_hydration',
    calories_per_100g: 19,
    protein_per_100g: 0.7,
    carbs_per_100g: 3.7,
    fat_per_100g: 0.2,
    fiber_per_100g: 1.1,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'bv-ele-1',
    name: 'Electrolyte Hydration Drink (Zero Sugar)',
    category: 'beverages_hydration',
    sub_category: 'functional_hydration',
    calories_per_100g: 0,
    protein_per_100g: 0.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 500,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },

  // =========================================================================
  // 10. PANTRY STAPLES & SNACKS
  // =========================================================================
  {
    id: 'sp-pow-1',
    name: '100% Whey Protein Isolate Powder (Vanilla)',
    category: 'snacks_pantry',
    sub_category: 'protein_powders',
    calories_per_100g: 370,
    protein_per_100g: 85.0,
    carbs_per_100g: 3.0,
    fat_per_100g: 1.5,
    fiber_per_100g: 0.5,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'powder_protein',
  },
  {
    id: 'sp-pow-2',
    name: 'Plant-Based Pea & Rice Protein Powder',
    category: 'snacks_pantry',
    sub_category: 'protein_powders',
    calories_per_100g: 380,
    protein_per_100g: 78.0,
    carbs_per_100g: 6.0,
    fat_per_100g: 4.0,
    fiber_per_100g: 3.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 35,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'powder_protein',
  },
  {
    id: 'sp-snk-1',
    name: 'Organic Plain Brown Rice Cakes',
    category: 'snacks_pantry',
    sub_category: 'rice_cakes_snacks',
    calories_per_100g: 387,
    protein_per_100g: 8.0,
    carbs_per_100g: 82.0,
    fat_per_100g: 2.8,
    fiber_per_100g: 4.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 20,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'sp-hum-1',
    name: 'Classic Garlic Hummus',
    category: 'snacks_pantry',
    sub_category: 'condiments_sauces',
    calories_per_100g: 166,
    protein_per_100g: 7.9,
    carbs_per_100g: 14.3,
    fat_per_100g: 9.6,
    fiber_per_100g: 6.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'healthy_fat',
  },
  {
    id: 'sp-sal-1',
    name: 'Fresh Mild Tomato Salsa',
    category: 'snacks_pantry',
    sub_category: 'condiments_sauces',
    calories_per_100g: 36,
    protein_per_100g: 1.5,
    carbs_per_100g: 7.0,
    fat_per_100g: 0.2,
    fiber_per_100g: 1.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 50,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },
  {
    id: 'sp-sw-1',
    name: 'Pure Raw Wildflower Honey',
    category: 'snacks_pantry',
    sub_category: 'natural_sweeteners',
    calories_per_100g: 304,
    protein_per_100g: 0.3,
    carbs_per_100g: 82.4,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.2,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 20,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'sp-sw-2',
    name: '100% Pure Grade A Maple Syrup',
    category: 'snacks_pantry',
    sub_category: 'natural_sweeteners',
    calories_per_100g: 260,
    protein_per_100g: 0.0,
    carbs_per_100g: 67.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 20,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'sp-sau-1',
    name: 'Dijon Mustard',
    category: 'snacks_pantry',
    sub_category: 'condiments_sauces',
    calories_per_100g: 66,
    protein_per_100g: 4.4,
    carbs_per_100g: 5.5,
    fat_per_100g: 4.0,
    fiber_per_100g: 3.3,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 10,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'cooking_fat',
  },
];
