import { FoodCategory, FoodItem } from './types';

export interface FoodCategoryMeta {
  id: FoodCategory;
  name: string;
  shortLabel: string;
  icon: string;
  description: string;
  accentColor: string;
}

export function normalizeFoodCategory(category: string): FoodCategory {
  switch (category) {
    case 'protein':
      return 'poultry_meat';
    case 'carbohydrate':
      return 'grains_carbs';
    case 'fruit':
      return 'fruits';
    case 'vegetable':
      return 'vegetables';
    case 'healthy_fat':
      return 'nuts_fats_oils';
    case 'dairy_alternative':
      return 'dairy_eggs';
    case 'beverage':
      return 'beverages_hydration';
    case 'pantry_staple':
      return 'snacks_pantry';
    default:
      return (category as FoodCategory) || 'snacks_pantry';
  }
}

export const FOOD_CATEGORIES: FoodCategoryMeta[] = [
  {
    id: 'poultry_meat',
    name: 'Poultry & Lean Meats',
    shortLabel: 'Poultry & Meat',
    icon: '🍗',
    description: 'Chicken breast, turkey, sirloin steak, lean ground meats & pork tenderloin',
    accentColor: '#f97316',
  },
  {
    id: 'fish_seafood',
    name: 'Fish & Seafood',
    shortLabel: 'Fish & Seafood',
    icon: '🐟',
    description: 'Wild salmon, cod, tuna, shrimp, halibut, tilapia & scallops',
    accentColor: '#06b6d4',
  },
  {
    id: 'dairy_eggs',
    name: 'Eggs, Dairy & Plant Milks',
    shortLabel: 'Eggs & Dairy',
    icon: '🥚',
    description: 'Whole eggs, egg whites, Greek yogurt, cottage cheese & almond milk',
    accentColor: '#3b82f6',
  },
  {
    id: 'plant_protein',
    name: 'Plant Protein & Legumes',
    shortLabel: 'Plant Protein',
    icon: '🌱',
    description: 'Tofu, tempeh, edamame, black beans, chickpeas, lentils & seitan',
    accentColor: '#10b981',
  },
  {
    id: 'grains_carbs',
    name: 'Grains, Bread & Potatoes',
    shortLabel: 'Grains & Carbs',
    icon: '🍚',
    description: 'Rolled oats, jasmine rice, sweet potatoes, quinoa, whole grain bread & pasta',
    accentColor: '#eab308',
  },
  {
    id: 'fruits',
    name: 'Fruits & Berries',
    shortLabel: 'Fruits & Berries',
    icon: '🍓',
    description: 'Blueberries, strawberries, apples, bananas, watermelon & citrus',
    accentColor: '#ec4899',
  },
  {
    id: 'vegetables',
    name: 'Vegetables & Leafy Greens',
    shortLabel: 'Vegetables & Greens',
    icon: '🥦',
    description: 'Broccoli, spinach, asparagus, kale, bell peppers, carrots & zucchini',
    accentColor: '#22c55e',
  },
  {
    id: 'nuts_fats_oils',
    name: 'Healthy Fats, Nuts & Seeds',
    shortLabel: 'Nuts & Healthy Fats',
    icon: '🥑',
    description: 'Avocado, olive oil, almonds, walnuts, peanut butter, chia seeds & flax',
    accentColor: '#84cc16',
  },
  {
    id: 'beverages_hydration',
    name: 'Hydration & Beverages',
    shortLabel: 'Beverages',
    icon: '☕',
    description: 'Black coffee, green tea, sparkling water, coconut water & electrolytes',
    accentColor: '#6366f1',
  },
  {
    id: 'snacks_pantry',
    name: 'Pantry Staples & Snacks',
    shortLabel: 'Pantry & Snacks',
    icon: '🍯',
    description: 'Protein powders, rice cakes, honey, hummus, salsa, mustard & spices',
    accentColor: '#a855f7',
  },
];

export const COMPREHENSIVE_FOOD_DATABASE: FoodItem[] = [
  // ==========================================
  // 1. POULTRY & LEAN MEATS
  // ==========================================
  {
    id: 'pm-1',
    name: 'Boneless Skinless Chicken Breast',
    category: 'poultry_meat',
    calories_per_100g: 165,
    protein_per_100g: 31.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 3.6,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-2',
    name: 'Skinless Chicken Thigh (Trimmed)',
    category: 'poultry_meat',
    calories_per_100g: 177,
    protein_per_100g: 24.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 8.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-3',
    name: '93/7 Lean Ground Turkey',
    category: 'poultry_meat',
    calories_per_100g: 152,
    protein_per_100g: 22.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 7.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-4',
    name: '99/1 Extra Lean Ground Turkey Breast',
    category: 'poultry_meat',
    calories_per_100g: 110,
    protein_per_100g: 26.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-5',
    name: '90/10 Lean Ground Beef',
    category: 'poultry_meat',
    calories_per_100g: 176,
    protein_per_100g: 20.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 10.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-6',
    name: '96/4 Extra Lean Ground Beef',
    category: 'poultry_meat',
    calories_per_100g: 133,
    protein_per_100g: 22.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 4.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-7',
    name: 'Grass-Fed Beef Sirloin Steak',
    category: 'poultry_meat',
    calories_per_100g: 183,
    protein_per_100g: 27.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 8.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 170,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-8',
    name: 'Beef Tenderloin / Filet Mignon',
    category: 'poultry_meat',
    calories_per_100g: 190,
    protein_per_100g: 26.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 9.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-9',
    name: 'Pork Tenderloin (Lean Roast)',
    category: 'poultry_meat',
    calories_per_100g: 143,
    protein_per_100g: 26.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 3.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-10',
    name: 'Lean Ground Bison',
    category: 'poultry_meat',
    calories_per_100g: 146,
    protein_per_100g: 20.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 7.2,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-11',
    name: 'Oven-Roasted Deli Turkey Breast',
    category: 'poultry_meat',
    calories_per_100g: 104,
    protein_per_100g: 17.5,
    carbs_per_100g: 4.0,
    fat_per_100g: 2.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-12',
    name: 'Turkey Bacon (Uncured)',
    category: 'poultry_meat',
    calories_per_100g: 218,
    protein_per_100g: 28.0,
    carbs_per_100g: 2.0,
    fat_per_100g: 11.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 60,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },

  // ==========================================
  // 2. FISH & SEAFOOD
  // ==========================================
  {
    id: 'fs-1',
    name: 'Wild Atlantic Salmon Fillet',
    category: 'fish_seafood',
    calories_per_100g: 208,
    protein_per_100g: 20.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 13.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fatty_protein',
  },
  {
    id: 'fs-2',
    name: 'Atlantic Cod Fillet',
    category: 'fish_seafood',
    calories_per_100g: 82,
    protein_per_100g: 18.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.7,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 170,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-3',
    name: 'Canned Chunk Light Tuna (in Water)',
    category: 'fish_seafood',
    calories_per_100g: 116,
    protein_per_100g: 25.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.8,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-4',
    name: 'Raw Jumbo Shrimp (Peeled & Deveined)',
    category: 'fish_seafood',
    calories_per_100g: 85,
    protein_per_100g: 20.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-5',
    name: 'Fresh Tilapia Fillet',
    category: 'fish_seafood',
    calories_per_100g: 96,
    protein_per_100g: 20.1,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.7,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-6',
    name: 'Fresh Yellowfin Tuna Steak',
    category: 'fish_seafood',
    calories_per_100g: 130,
    protein_per_100g: 29.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-7',
    name: 'Sea Scallops (Raw)',
    category: 'fish_seafood',
    calories_per_100g: 69,
    protein_per_100g: 12.0,
    carbs_per_100g: 3.2,
    fat_per_100g: 0.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-8',
    name: 'Pacific Halibut Fillet',
    category: 'fish_seafood',
    calories_per_100g: 110,
    protein_per_100g: 23.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.6,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-9',
    name: 'Wild Sardines (in Spring Water)',
    category: 'fish_seafood',
    calories_per_100g: 208,
    protein_per_100g: 24.6,
    carbs_per_100g: 0.0,
    fat_per_100g: 11.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 90,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'fatty_protein',
  },

  // ==========================================
  // 3. EGGS, DAIRY & PLANT MILKS
  // ==========================================
  {
    id: 'de-1',
    name: 'Pasture-Raised Whole Eggs',
    category: 'dairy_eggs',
    calories_per_100g: 143,
    protein_per_100g: 12.6,
    carbs_per_100g: 0.7,
    fat_per_100g: 9.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'egg_source',
  },
  {
    id: 'de-2',
    name: '100% Pure Liquid Egg Whites',
    category: 'dairy_eggs',
    calories_per_100g: 52,
    protein_per_100g: 11.0,
    carbs_per_100g: 0.7,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'de-3',
    name: 'Non-Fat Plain Greek Yogurt (0%)',
    category: 'dairy_eggs',
    calories_per_100g: 59,
    protein_per_100g: 10.3,
    carbs_per_100g: 3.6,
    fat_per_100g: 0.4,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 200,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },
  {
    id: 'de-4',
    name: '2% Low-Fat Greek Yogurt',
    category: 'dairy_eggs',
    calories_per_100g: 73,
    protein_per_100g: 10.0,
    carbs_per_100g: 4.0,
    fat_per_100g: 2.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 200,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },
  {
    id: 'de-5',
    name: 'Low-Fat Cottage Cheese (2%)',
    category: 'dairy_eggs',
    calories_per_100g: 81,
    protein_per_100g: 11.0,
    carbs_per_100g: 4.7,
    fat_per_100g: 2.3,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },
  {
    id: 'de-6',
    name: 'Part-Skim Mozzarella String Cheese',
    category: 'dairy_eggs',
    calories_per_100g: 280,
    protein_per_100g: 24.0,
    carbs_per_100g: 2.5,
    fat_per_100g: 20.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },
  {
    id: 'de-7',
    name: 'Sharp Cheddar Cheese',
    category: 'dairy_eggs',
    calories_per_100g: 403,
    protein_per_100g: 25.0,
    carbs_per_100g: 1.3,
    fat_per_100g: 33.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'healthy_fat',
  },
  {
    id: 'de-8',
    name: 'Unsweetened Almond Milk',
    category: 'dairy_eggs',
    calories_per_100g: 15,
    protein_per_100g: 0.6,
    carbs_per_100g: 0.3,
    fat_per_100g: 1.2,
    fiber_per_100g: 0.2,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'de-9',
    name: 'Unsweetened Oat Milk',
    category: 'dairy_eggs',
    calories_per_100g: 45,
    protein_per_100g: 1.0,
    carbs_per_100g: 6.5,
    fat_per_100g: 1.5,
    fiber_per_100g: 0.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'de-10',
    name: 'Fairlife Ultra-Filtered Skim Milk',
    category: 'dairy_eggs',
    calories_per_100g: 35,
    protein_per_100g: 5.4,
    carbs_per_100g: 2.5,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },

  // ==========================================
  // 4. PLANT PROTEINS & LEGUMES
  // ==========================================
  {
    id: 'pp-1',
    name: 'Organic Extra Firm Tofu',
    category: 'plant_protein',
    calories_per_100g: 83,
    protein_per_100g: 10.0,
    carbs_per_100g: 1.5,
    fat_per_100g: 5.0,
    fiber_per_100g: 0.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'plant_protein',
  },
  {
    id: 'pp-2',
    name: 'Organic Soy Tempeh',
    category: 'plant_protein',
    calories_per_100g: 192,
    protein_per_100g: 20.3,
    carbs_per_100g: 7.6,
    fat_per_100g: 10.8,
    fiber_per_100g: 5.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'plant_protein',
  },
  {
    id: 'pp-3',
    name: 'Steamed Edamame (Shelled)',
    category: 'plant_protein',
    calories_per_100g: 121,
    protein_per_100g: 11.9,
    carbs_per_100g: 8.9,
    fat_per_100g: 5.2,
    fiber_per_100g: 5.2,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'plant_protein',
  },
  {
    id: 'pp-4',
    name: 'Cooked Black Beans',
    category: 'plant_protein',
    calories_per_100g: 132,
    protein_per_100g: 8.9,
    carbs_per_100g: 23.7,
    fat_per_100g: 0.5,
    fiber_per_100g: 8.7,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'pp-5',
    name: 'Cooked Chickpeas (Garbanzo Beans)',
    category: 'plant_protein',
    calories_per_100g: 164,
    protein_per_100g: 8.9,
    carbs_per_100g: 27.4,
    fat_per_100g: 2.6,
    fiber_per_100g: 7.6,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'pp-6',
    name: 'Cooked Red Lentils',
    category: 'plant_protein',
    calories_per_100g: 116,
    protein_per_100g: 9.0,
    carbs_per_100g: 20.0,
    fat_per_100g: 0.4,
    fiber_per_100g: 7.9,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'pp-7',
    name: 'Nutritional Yeast Flakes',
    category: 'plant_protein',
    calories_per_100g: 380,
    protein_per_100g: 50.0,
    carbs_per_100g: 35.0,
    fat_per_100g: 5.0,
    fiber_per_100g: 25.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 15,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'powder_protein',
  },

  // ==========================================
  // 5. GRAINS, BREAD & STARCHY CARBS
  // ==========================================
  {
    id: 'gc-1',
    name: 'Certified Gluten-Free Rolled Oats',
    category: 'grains_carbs',
    calories_per_100g: 379,
    protein_per_100g: 13.2,
    carbs_per_100g: 67.7,
    fat_per_100g: 6.5,
    fiber_per_100g: 10.1,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 60,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-2',
    name: 'Steamed Jasmine White Rice',
    category: 'grains_carbs',
    calories_per_100g: 130,
    protein_per_100g: 2.7,
    carbs_per_100g: 28.2,
    fat_per_100g: 0.3,
    fiber_per_100g: 0.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 180,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-3',
    name: 'Cooked Brown Basmati Rice',
    category: 'grains_carbs',
    calories_per_100g: 123,
    protein_per_100g: 2.7,
    carbs_per_100g: 25.6,
    fat_per_100g: 1.0,
    fiber_per_100g: 1.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 180,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-4',
    name: 'Organic Tri-Color Quinoa (Cooked)',
    category: 'grains_carbs',
    calories_per_100g: 120,
    protein_per_100g: 4.4,
    carbs_per_100g: 21.3,
    fat_per_100g: 1.9,
    fiber_per_100g: 2.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-5',
    name: 'Baked Sweet Potato (Flesh Only)',
    category: 'grains_carbs',
    calories_per_100g: 90,
    protein_per_100g: 2.0,
    carbs_per_100g: 20.7,
    fat_per_100g: 0.2,
    fiber_per_100g: 3.3,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 200,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-6',
    name: 'Boiled Russet / Gold Potatoes',
    category: 'grains_carbs',
    calories_per_100g: 87,
    protein_per_100g: 1.9,
    carbs_per_100g: 20.1,
    fat_per_100g: 0.1,
    fiber_per_100g: 1.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 200,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-7',
    name: '100% Sourdough Artisan Bread Slice',
    category: 'grains_carbs',
    calories_per_100g: 240,
    protein_per_100g: 8.5,
    carbs_per_100g: 48.0,
    fat_per_100g: 1.2,
    fiber_per_100g: 2.5,
    is_gluten_free: false,
    is_dairy_free: true,
    serving_size_g: 50,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-8',
    name: 'Ezekiel Sprouted Grain Bread Slice',
    category: 'grains_carbs',
    calories_per_100g: 235,
    protein_per_100g: 14.0,
    carbs_per_100g: 44.0,
    fat_per_100g: 1.5,
    fiber_per_100g: 7.5,
    is_gluten_free: false,
    is_dairy_free: true,
    serving_size_g: 45,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-9',
    name: 'Cooked Whole Wheat Pasta (Penne/Spaghetti)',
    category: 'grains_carbs',
    calories_per_100g: 124,
    protein_per_100g: 5.3,
    carbs_per_100g: 26.5,
    fat_per_100g: 0.5,
    fiber_per_100g: 3.9,
    is_gluten_free: false,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-10',
    name: 'Yellow Corn Tortillas',
    category: 'grains_carbs',
    calories_per_100g: 218,
    protein_per_100g: 5.7,
    carbs_per_100g: 45.0,
    fat_per_100g: 2.9,
    fiber_per_100g: 6.3,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 50,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },

  // ==========================================
  // 6. FRUITS & BERRIES
  // ==========================================
  {
    id: 'fb-1',
    name: 'Fresh Blueberries',
    category: 'fruits',
    calories_per_100g: 57,
    protein_per_100g: 0.7,
    carbs_per_100g: 14.5,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 125,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-2',
    name: 'Fresh Strawberries',
    category: 'fruits',
    calories_per_100g: 32,
    protein_per_100g: 0.7,
    carbs_per_100g: 7.7,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-3',
    name: 'Fresh Raspberries',
    category: 'fruits',
    calories_per_100g: 52,
    protein_per_100g: 1.2,
    carbs_per_100g: 11.9,
    fat_per_100g: 0.7,
    fiber_per_100g: 6.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 125,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-4',
    name: 'Medium Banana',
    category: 'fruits',
    calories_per_100g: 89,
    protein_per_100g: 1.1,
    carbs_per_100g: 22.8,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.6,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-5',
    name: 'Honeycrisp Apple (Medium)',
    category: 'fruits',
    calories_per_100g: 52,
    protein_per_100g: 0.3,
    carbs_per_100g: 13.8,
    fat_per_100g: 0.2,
    fiber_per_100g: 2.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 180,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-6',
    name: 'Fresh Watermelon Chunks',
    category: 'fruits',
    calories_per_100g: 30,
    protein_per_100g: 0.6,
    carbs_per_100g: 7.6,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 200,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-7',
    name: 'Fresh Pineapple Chunks',
    category: 'fruits',
    calories_per_100g: 50,
    protein_per_100g: 0.5,
    carbs_per_100g: 13.1,
    fat_per_100g: 0.1,
    fiber_per_100g: 1.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-8',
    name: 'Navel Orange',
    category: 'fruits',
    calories_per_100g: 47,
    protein_per_100g: 0.9,
    carbs_per_100g: 11.8,
    fat_per_100g: 0.1,
    fiber_per_100g: 2.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },

  // ==========================================
  // 7. VEGETABLES & LEAFY GREENS
  // ==========================================
  {
    id: 'vg-1',
    name: 'Fresh Steamed Broccoli Florets',
    category: 'vegetables',
    calories_per_100g: 35,
    protein_per_100g: 2.4,
    carbs_per_100g: 7.2,
    fat_per_100g: 0.4,
    fiber_per_100g: 2.6,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'cruciferous_veg',
  },
  {
    id: 'vg-2',
    name: 'Organic Baby Spinach',
    category: 'vegetables',
    calories_per_100g: 23,
    protein_per_100g: 2.9,
    carbs_per_100g: 3.6,
    fat_per_100g: 0.4,
    fiber_per_100g: 2.2,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'leafy_veg',
  },
  {
    id: 'vg-3',
    name: 'Fresh Green Asparagus Spears',
    category: 'vegetables',
    calories_per_100g: 20,
    protein_per_100g: 2.2,
    carbs_per_100g: 3.9,
    fat_per_100g: 0.1,
    fiber_per_100g: 2.1,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },
  {
    id: 'vg-4',
    name: 'Zucchini / Courgette Slices',
    category: 'vegetables',
    calories_per_100g: 17,
    protein_per_100g: 1.2,
    carbs_per_100g: 3.1,
    fat_per_100g: 0.3,
    fiber_per_100g: 1.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },
  {
    id: 'vg-5',
    name: 'Sweet Red Bell Peppers (Sliced)',
    category: 'vegetables',
    calories_per_100g: 31,
    protein_per_100g: 1.0,
    carbs_per_100g: 6.0,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.1,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },
  {
    id: 'vg-6',
    name: 'Steamed Cauliflower Florets',
    category: 'vegetables',
    calories_per_100g: 25,
    protein_per_100g: 1.9,
    carbs_per_100g: 5.0,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'cruciferous_veg',
  },
  {
    id: 'vg-7',
    name: 'Tuscan Kale (Lacinato)',
    category: 'vegetables',
    calories_per_100g: 49,
    protein_per_100g: 4.3,
    carbs_per_100g: 8.8,
    fat_per_100g: 0.9,
    fiber_per_100g: 3.6,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'leafy_veg',
  },
  {
    id: 'vg-8',
    name: 'Fresh Brussels Sprouts (Halved)',
    category: 'vegetables',
    calories_per_100g: 43,
    protein_per_100g: 3.4,
    carbs_per_100g: 9.0,
    fat_per_100g: 0.3,
    fiber_per_100g: 3.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'cruciferous_veg',
  },
  {
    id: 'vg-9',
    name: 'Crisp English Cucumbers (Sliced)',
    category: 'vegetables',
    calories_per_100g: 15,
    protein_per_100g: 0.7,
    carbs_per_100g: 3.6,
    fat_per_100g: 0.1,
    fiber_per_100g: 0.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },
  {
    id: 'vg-10',
    name: 'Sliced White / Cremini Mushrooms',
    category: 'vegetables',
    calories_per_100g: 22,
    protein_per_100g: 3.1,
    carbs_per_100g: 3.3,
    fat_per_100g: 0.3,
    fiber_per_100g: 1.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },

  // ==========================================
  // 8. HEALTHY FATS, NUTS & SEEDS
  // ==========================================
  {
    id: 'hf-1',
    name: 'Fresh Hass Avocado',
    category: 'nuts_fats_oils',
    calories_per_100g: 160,
    protein_per_100g: 2.0,
    carbs_per_100g: 8.5,
    fat_per_100g: 14.7,
    fiber_per_100g: 6.7,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 75,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'healthy_fat',
  },
  {
    id: 'hf-2',
    name: 'Extra Virgin Olive Oil',
    category: 'nuts_fats_oils',
    calories_per_100g: 884,
    protein_per_100g: 0.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 100.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 15,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'cooking_fat',
  },
  {
    id: 'hf-3',
    name: 'Pure Avocado Oil',
    category: 'nuts_fats_oils',
    calories_per_100g: 884,
    protein_per_100g: 0.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 100.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 15,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'cooking_fat',
  },
  {
    id: 'hf-4',
    name: 'Raw Whole Almonds',
    category: 'nuts_fats_oils',
    calories_per_100g: 579,
    protein_per_100g: 21.2,
    carbs_per_100g: 21.6,
    fat_per_100g: 49.9,
    fiber_per_100g: 12.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'nut_fat',
  },
  {
    id: 'hf-5',
    name: 'Raw English Walnut Halves',
    category: 'nuts_fats_oils',
    calories_per_100g: 654,
    protein_per_100g: 15.2,
    carbs_per_100g: 13.7,
    fat_per_100g: 65.2,
    fiber_per_100g: 6.7,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'nut_fat',
  },
  {
    id: 'hf-6',
    name: 'Natural Creamy Peanut Butter (100% Peanuts)',
    category: 'nuts_fats_oils',
    calories_per_100g: 588,
    protein_per_100g: 25.0,
    carbs_per_100g: 20.0,
    fat_per_100g: 50.0,
    fiber_per_100g: 8.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 32,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'nut_fat',
  },
  {
    id: 'hf-7',
    name: 'Natural Almond Butter',
    category: 'nuts_fats_oils',
    calories_per_100g: 614,
    protein_per_100g: 21.0,
    carbs_per_100g: 19.0,
    fat_per_100g: 55.5,
    fiber_per_100g: 10.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 32,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'nut_fat',
  },
  {
    id: 'hf-8',
    name: 'Organic Whole Chia Seeds',
    category: 'nuts_fats_oils',
    calories_per_100g: 486,
    protein_per_100g: 16.5,
    carbs_per_100g: 42.1,
    fat_per_100g: 30.7,
    fiber_per_100g: 34.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 20,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'healthy_fat',
  },
  {
    id: 'hf-9',
    name: 'Ground Golden Flaxseed Meal',
    category: 'nuts_fats_oils',
    calories_per_100g: 534,
    protein_per_100g: 18.3,
    carbs_per_100g: 28.9,
    fat_per_100g: 42.2,
    fiber_per_100g: 27.3,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 15,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'healthy_fat',
  },
  {
    id: 'hf-10',
    name: 'Raw Pumpkin Seeds (Pepitas)',
    category: 'nuts_fats_oils',
    calories_per_100g: 559,
    protein_per_100g: 30.2,
    carbs_per_100g: 10.7,
    fat_per_100g: 49.0,
    fiber_per_100g: 6.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'nut_fat',
  },

  // ==========================================
  // 9. BEVERAGES & HYDRATION
  // ==========================================
  {
    id: 'bv-1',
    name: 'Black Drip Coffee (Unsweetened)',
    category: 'beverages_hydration',
    calories_per_100g: 2,
    protein_per_100g: 0.3,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'bv-2',
    name: 'Organic Green Tea (Brewed)',
    category: 'beverages_hydration',
    calories_per_100g: 1,
    protein_per_100g: 0.2,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'bv-3',
    name: 'Pure Sparkling Water / Seltzer (0 Cal)',
    category: 'beverages_hydration',
    calories_per_100g: 0,
    protein_per_100g: 0.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 355,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'bv-4',
    name: '100% Pure Coconut Water',
    category: 'beverages_hydration',
    calories_per_100g: 19,
    protein_per_100g: 0.7,
    carbs_per_100g: 3.7,
    fat_per_100g: 0.2,
    fiber_per_100g: 1.1,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'bv-5',
    name: 'Electrolyte Hydration Drink (Zero Sugar)',
    category: 'beverages_hydration',
    calories_per_100g: 0,
    protein_per_100g: 0.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 500,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },

  // ==========================================
  // 10. PANTRY STAPLES & SNACKS
  // ==========================================
  {
    id: 'sp-1',
    name: '100% Whey Protein Isolate Powder (Vanilla/Choc)',
    category: 'snacks_pantry',
    calories_per_100g: 370,
    protein_per_100g: 85.0,
    carbs_per_100g: 3.0,
    fat_per_100g: 1.5,
    fiber_per_100g: 0.5,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'powder_protein',
  },
  {
    id: 'sp-2',
    name: 'Plant-Based Pea & Rice Protein Powder',
    category: 'snacks_pantry',
    calories_per_100g: 380,
    protein_per_100g: 78.0,
    carbs_per_100g: 6.0,
    fat_per_100g: 4.0,
    fiber_per_100g: 3.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 35,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'powder_protein',
  },
  {
    id: 'sp-3',
    name: 'Organic Plain Rice Cakes',
    category: 'snacks_pantry',
    calories_per_100g: 387,
    protein_per_100g: 8.0,
    carbs_per_100g: 82.0,
    fat_per_100g: 2.8,
    fiber_per_100g: 4.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 20,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'sp-4',
    name: 'Classic Garlic Hummus',
    category: 'snacks_pantry',
    calories_per_100g: 166,
    protein_per_100g: 7.9,
    carbs_per_100g: 14.3,
    fat_per_100g: 9.6,
    fiber_per_100g: 6.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'healthy_fat',
  },
  {
    id: 'sp-5',
    name: 'Fresh Mild Tomato Salsa',
    category: 'snacks_pantry',
    calories_per_100g: 36,
    protein_per_100g: 1.5,
    carbs_per_100g: 7.0,
    fat_per_100g: 0.2,
    fiber_per_100g: 1.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 50,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },
  {
    id: 'sp-6',
    name: 'Pure Raw Wildflower Honey',
    category: 'snacks_pantry',
    calories_per_100g: 304,
    protein_per_100g: 0.3,
    carbs_per_100g: 82.4,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.2,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 20,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'sp-7',
    name: '100% Pure Maple Syrup',
    category: 'snacks_pantry',
    calories_per_100g: 260,
    protein_per_100g: 0.0,
    carbs_per_100g: 67.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 20,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'sp-8',
    name: 'Dijon Mustard',
    category: 'snacks_pantry',
    calories_per_100g: 66,
    protein_per_100g: 4.4,
    carbs_per_100g: 5.5,
    fat_per_100g: 4.0,
    fiber_per_100g: 3.3,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 10,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'cooking_fat',
  },
];
