export interface SimpleMovementActivity {
  id: string;
  title: string;
  category: 'walking' | 'mobility' | 'strength' | 'cardio_fun' | 'custom';
  category_label: string;
  icon: string;
  duration_minutes: number;
  estimated_calories: number;
  estimated_steps: number;
  description: string;
  benefits: string;
  intensity: 'gentle' | 'moderate' | 'energizing';
  completed?: boolean;
  completed_at?: string;
}

export const POPULAR_MOVEMENT_CHOICES: SimpleMovementActivity[] = [
  // 1. Walking & Daily Steps
  {
    id: 'walk_20',
    title: '20-Minute Brisk Walk',
    category: 'walking',
    category_label: 'Walking & Steps',
    icon: '🚶',
    duration_minutes: 20,
    estimated_calories: 100,
    estimated_steps: 2200,
    description: 'Head outside, breathe fresh air, get natural sunlight, and boost your cardiovascular circulation.',
    benefits: 'Improves heart health, lowers blood sugar, and clears the mind.',
    intensity: 'gentle',
  },
  {
    id: 'walk_45_hike',
    title: '45-Minute Nature Walk / Hike',
    category: 'walking',
    category_label: 'Walking & Steps',
    icon: '👟',
    duration_minutes: 45,
    estimated_calories: 225,
    estimated_steps: 5000,
    description: 'A longer, refreshing walk through your neighborhood, local park, or scenic outdoor trail.',
    benefits: 'Builds stamina, elevates daily step count, and reduces stress.',
    intensity: 'moderate',
  },
  {
    id: 'walk_15_postmeal',
    title: '15-Minute Post-Meal Stroll',
    category: 'walking',
    category_label: 'Walking & Steps',
    icon: '🐾',
    duration_minutes: 15,
    estimated_calories: 75,
    estimated_steps: 1600,
    description: 'A light, relaxed walk after breakfast, lunch, or dinner to aid digestion and prevent post-meal slumps.',
    benefits: 'Aids digestive transit and smooths post-meal glucose response.',
    intensity: 'gentle',
  },
  {
    id: 'jog_20',
    title: '20-Minute Easy Jog / Run-Walk',
    category: 'walking',
    category_label: 'Walking & Steps',
    icon: '🏃',
    duration_minutes: 20,
    estimated_calories: 190,
    estimated_steps: 2600,
    description: 'Alternating between a comfortable jog and gentle walking intervals at your own pace.',
    benefits: 'Boosts lung capacity, heart strength, and endorphin release.',
    intensity: 'energizing',
  },

  // 2. Mobility & Yoga
  {
    id: 'stretch_10',
    title: '10-Minute Morning Stretch',
    category: 'mobility',
    category_label: 'Mobility & Stretching',
    icon: '🧘',
    duration_minutes: 10,
    estimated_calories: 35,
    estimated_steps: 0,
    description: 'Gentle mobility routine to release tension in your neck, shoulders, lower back, and hips.',
    benefits: 'Increases flexibility, relieves stiffness, and improves morning posture.',
    intensity: 'gentle',
  },
  {
    id: 'yoga_20',
    title: '20-Minute Gentle Yoga Flow',
    category: 'mobility',
    category_label: 'Mobility & Stretching',
    icon: '🌸',
    duration_minutes: 20,
    estimated_calories: 80,
    estimated_steps: 0,
    description: 'Flowing through sun salutations, warrior poses, and deep breathing to center your body and mind.',
    benefits: 'Enhances balance, core stability, joint mobility, and inner calm.',
    intensity: 'gentle',
  },
  {
    id: 'bedtime_stretch_10',
    title: '10-Minute Bedtime Wind-Down',
    category: 'mobility',
    category_label: 'Mobility & Stretching',
    icon: '🌙',
    duration_minutes: 10,
    estimated_calories: 30,
    estimated_steps: 0,
    description: 'Floor stretches and relaxing leg elevation against the wall to prepare for deep, restful sleep.',
    benefits: 'Lowers nervous system arousal and relaxes tight muscles before bed.',
    intensity: 'gentle',
  },
  {
    id: 'posture_reset_10',
    title: '10-Minute Posture & Desk Reset',
    category: 'mobility',
    category_label: 'Mobility & Stretching',
    icon: '🪑',
    duration_minutes: 10,
    estimated_calories: 40,
    estimated_steps: 0,
    description: 'Quick chest openers, shoulder rolls, and neck glides for anyone spending time sitting at a desk.',
    benefits: 'Reverses hunching and relieves upper spine stiffness.',
    intensity: 'gentle',
  },

  // 3. Home Strength & Tone
  {
    id: 'home_tone_15',
    title: '15-Minute Full Body Tone',
    category: 'strength',
    category_label: 'Strength & Tone',
    icon: '💪',
    duration_minutes: 15,
    estimated_calories: 95,
    estimated_steps: 300,
    description: 'Simple bodyweight squats, wall push-ups, knee planks, and arm reaches to feel strong and toned.',
    benefits: 'Builds functional strength, protects bone density, and tones muscles.',
    intensity: 'moderate',
  },
  {
    id: 'core_posture_12',
    title: '12-Minute Core & Balance',
    category: 'strength',
    category_label: 'Strength & Tone',
    icon: '🛡️',
    duration_minutes: 12,
    estimated_calories: 70,
    estimated_steps: 0,
    description: 'Bird-dogs, glute bridges, deadbugs, and side knee lifts to build a rock-solid core and lower back support.',
    benefits: 'Supports lower back, strengthens abdominals, and stabilizes the pelvis.',
    intensity: 'gentle',
  },
  {
    id: 'band_dumbbell_20',
    title: '20-Minute Light Weights / Bands',
    category: 'strength',
    category_label: 'Strength & Tone',
    icon: '🏋️',
    duration_minutes: 20,
    estimated_calories: 130,
    estimated_steps: 400,
    description: 'Bicep curls, shoulder presses, rows, and goblet squats using light dumbbells or resistance bands.',
    benefits: 'Improves muscular endurance, posture, and lean body mass.',
    intensity: 'moderate',
  },
  {
    id: 'lower_body_tone_15',
    title: '15-Minute Legs & Glutes Tone',
    category: 'strength',
    category_label: 'Strength & Tone',
    icon: '🦵',
    duration_minutes: 15,
    estimated_calories: 90,
    estimated_steps: 450,
    description: 'Chair sit-to-stands, lunges, calf raises, and glute kickbacks for strong, shapely legs.',
    benefits: 'Tones leg musculature and makes stair-climbing effortless.',
    intensity: 'moderate',
  },

  // 4. Active Fun & Cardio
  {
    id: 'cycling_25',
    title: '25-Minute Bike Ride / Spin',
    category: 'cardio_fun',
    category_label: 'Active Fun & Cardio',
    icon: '🚴',
    duration_minutes: 25,
    estimated_calories: 160,
    estimated_steps: 0,
    description: 'Cruising around your neighborhood on a bicycle or an energizing indoor stationary bike spin.',
    benefits: 'High cardio burn with smooth, low-impact motion on knees and joints.',
    intensity: 'moderate',
  },
  {
    id: 'swimming_20',
    title: '20-Minute Pool Swim / Water Walk',
    category: 'cardio_fun',
    category_label: 'Active Fun & Cardio',
    icon: '🏊',
    duration_minutes: 20,
    estimated_calories: 175,
    estimated_steps: 0,
    description: 'Gentle laps, water aerobics, or pool walking for total body resistance with zero joint impact.',
    benefits: 'Relieves arthritis/joint pressure while providing full-body aerobic conditioning.',
    intensity: 'moderate',
  },
  {
    id: 'dance_20',
    title: '20-Minute Feel-Good Dance / Zumba',
    category: 'cardio_fun',
    category_label: 'Active Fun & Cardio',
    icon: '💃',
    duration_minutes: 20,
    estimated_calories: 145,
    estimated_steps: 1800,
    description: 'Put on your favorite upbeat music and dance around the room, or follow along to a fun rhythm session.',
    benefits: 'Elevates mood, burns calories rapidly, and improves rhythm and coordination.',
    intensity: 'energizing',
  },
  {
    id: 'gardening_30',
    title: '30-Minute Gardening & Active Play',
    category: 'cardio_fun',
    category_label: 'Active Fun & Cardio',
    icon: '🌿',
    duration_minutes: 30,
    estimated_calories: 130,
    estimated_steps: 1500,
    description: 'Pruning plants, raking leaves, playing active games with family/pets, or outdoor yard work.',
    benefits: 'Functional daily movement, grip strength, and natural sunshine.',
    intensity: 'gentle',
  },
  {
    id: 'pickleball_30',
    title: '30-Minute Pickleball / Racket Play',
    category: 'cardio_fun',
    category_label: 'Active Fun & Cardio',
    icon: '🎾',
    duration_minutes: 30,
    estimated_calories: 185,
    estimated_steps: 2800,
    description: 'Social and fun racket sports game focusing on quick steps, volleys, and hand-eye coordination.',
    benefits: 'Agility, hand-eye coordination, social connection, and high calorie burn.',
    intensity: 'energizing',
  },
];

export const DEFAULT_SIMPLE_DAILY_CHOICES: SimpleMovementActivity[] = [
  { ...POPULAR_MOVEMENT_CHOICES[0], completed: false }, // 20-Minute Brisk Walk
  { ...POPULAR_MOVEMENT_CHOICES[4], completed: false }, // 10-Minute Morning Stretch
  { ...POPULAR_MOVEMENT_CHOICES[8], completed: false }, // 15-Minute Full Body Tone
];
