import { RecipeItem, RecipeCategory, RecipeSubCategory, RecipeSubCategoryMeta } from './types';

export const RECIPE_SUB_CATEGORIES: RecipeSubCategoryMeta[] = [
  // Breakfast
  { id: 'high_protein_eggs', category: 'breakfast', name: 'Eggs & Scrambles', emoji: '🍳', description: 'High-protein omelets, scrambles, and breakfast skillets' },
  { id: 'oats_pancakes', category: 'breakfast', name: 'Oats & Pancakes', emoji: '🥞', description: 'Protein-packed pancakes, overnight oats, and baked porridge' },
  { id: 'smoothies_bowls', category: 'breakfast', name: 'Smoothies & Bowls', emoji: '🥤', description: 'Quick superfood shakes, protein fluffs, and yogurt bowls' },
  { id: 'quick_grab_go', category: 'breakfast', name: 'Grab & Go', emoji: '🧁', description: 'Prep-ahead egg muffins, breakfast wraps, and sandwiches' },

  // Lunch
  { id: 'power_bowls', category: 'lunch', name: 'Power Bowls', emoji: '🥗', description: 'Macro-balanced grain, protein, and vegetable fuel bowls' },
  { id: 'wraps_sandwiches', category: 'lunch', name: 'Wraps & Pockets', emoji: '🌯', description: 'Crisp wraps, loaded pita pockets, and panini sandwiches' },
  { id: 'fresh_salads', category: 'lunch', name: 'Crisp Salads', emoji: '🥗', description: 'Hearty protein salads with homemade light vinaigrettes' },
  { id: 'soups_chilis', category: 'lunch', name: 'Soups & Chilis', emoji: '🍲', description: 'Comforting, high-protein stews and hearty chilis' },

  // Dinner
  { id: 'poultry_dishes', category: 'dinner', name: 'Poultry & Chicken', emoji: '🍗', description: 'Air-fried cutlets, skillet chicken, and turkey entrees' },
  { id: 'beef_steaks', category: 'dinner', name: 'Steaks & Sirloin', emoji: '🥩', description: 'Cast-iron seared steaks, lean beef roasts, and smash burgers' },
  { id: 'seafood_fish', category: 'dinner', name: 'Seafood & Fish', emoji: '🐟', description: 'Omega-3 wild salmon, blackened mahi, shrimp, and cod' },
  { id: 'pasta_comfort', category: 'dinner', name: 'Pastas & Bakes', emoji: '🍝', description: 'High-protein bolognese, cottage cheese alfredo, and lasagnas' },

  // Bulk Meal Prep
  { id: 'sheet_pan_meals', category: 'bulk_meal_prep', name: 'Sheet-Pan Preps', emoji: '🥘', description: '1-pan oven roasted proteins and vegetables for the week' },
  { id: 'slow_cooker_instant_pot', category: 'bulk_meal_prep', name: 'Slow Cooker & Pot', emoji: '🍲', description: 'Set-and-forget shredded meats, curries, and carnitas' },
  { id: 'casseroles_bakes', category: 'bulk_meal_prep', name: 'Casserole Bakes', emoji: '🥧', description: 'Hearty baked casseroles, shepherd pies, and enchilada bakes' },
  { id: 'prepped_proteins_sides', category: 'bulk_meal_prep', name: 'Proteins & Grains', emoji: '🍚', description: 'Bulk batch grilled chicken, sweet potatoes, and brown rice' },

  // Snacks & Desserts
  { id: 'protein_bites_bars', category: 'snack_dessert', name: 'Bars & Bites', emoji: '🍫', description: 'No-bake protein balls, homemade bars, and energy bites' },
  { id: 'sweet_treats', category: 'snack_dessert', name: 'Sweet Treats', emoji: '🍨', description: 'Anabolic protein fluff, yogurt bark, and mug cakes' },
  { id: 'savory_crunch', category: 'snack_dessert', name: 'Savory Crunches', emoji: '🧆', description: 'Crispy chickpeas, edamame, and whipped cottage cheese dips' },
];

export const COMPREHENSIVE_RECIPE_DATABASE: RecipeItem[] = [
  // ==========================================
  // BREAKFAST - EGGS & SCRAMBLES
  // ==========================================
  {
    id: 'recipe-spinach-feta-scramble',
    title: 'Spinach, Feta & Sun-Dried Tomato Scramble',
    description: 'Fluffy whole egg and liquid egg white scramble loaded with baby spinach, tangy Greek feta, and sun-dried tomatoes.',
    category: 'breakfast',
    sub_category: 'high_protein_eggs',
    prep_time_minutes: 5,
    cook_time_minutes: 8,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['High-Protein', 'Low-Carb', 'Keto-Friendly', 'Vegetarian', 'Quick Breakfast'],
    calories_per_serving: 360,
    protein_g_per_serving: 34,
    carbs_g_per_serving: 8,
    fat_g_per_serving: 20,
    icon_emoji: '🍳',
    ingredients: [
      { food_id: 'whole-eggs', name: 'Large Whole Eggs', amount_imperial: '2 whole', amount_metric: '2 whole', raw_weight_grams_base: 100, department: 'dairy_eggs' },
      { food_id: 'liquid-egg-whites', name: 'Liquid Egg Whites', amount_imperial: '1/2 cup (4 oz)', amount_metric: '120 ml', raw_weight_grams_base: 120, department: 'dairy_eggs' },
      { food_id: 'baby-spinach', name: 'Fresh Baby Spinach', amount_imperial: '1.5 cups', amount_metric: '45g', raw_weight_grams_base: 45, department: 'produce' },
      { food_id: 'feta-cheese', name: 'Crumbled Greek Feta Cheese', amount_imperial: '2 tablespoons (1 oz)', amount_metric: '28g', raw_weight_grams_base: 28, department: 'dairy_eggs' },
      { food_id: 'sundried-tomatoes', name: 'Sun-Dried Tomatoes (Drained)', amount_imperial: '1 tablespoon chopped', amount_metric: '15g', raw_weight_grams_base: 15, department: 'pantry_spices' },
      { food_id: 'olive-oil-spray', name: 'Extra Virgin Olive Oil Cooking Spray', amount_imperial: '1-second spray', amount_metric: '1 spray', raw_weight_grams_base: 2, department: 'healthy_fats' },
    ],
    instructions: [
      'Whisk whole eggs and liquid egg whites in a small bowl with a pinch of sea salt and black pepper.',
      'Heat a non-stick skillet over medium heat and mist lightly with olive oil spray.',
      'Add baby spinach and sun-dried tomatoes. Sauté for 60 seconds until spinach is wilted.',
      'Pour egg mixture into skillet. Gently fold with a spatula to form soft curds.',
      'Fold in crumbled feta cheese and serve warm.',
    ],
    chef_notes: 'Combining 2 whole eggs with liquid egg whites delivers rich flavor while boosting pure protein to over 34 grams.',
  },
  {
    id: 'recipe-southwest-turkey-breakfast-burrito',
    title: 'Southwestern Turkey Sausage Breakfast Burrito',
    description: 'Warm whole wheat tortilla packed with lean turkey sausage crumbles, scrambled eggs, black beans, and salsa fresca.',
    category: 'breakfast',
    sub_category: 'high_protein_eggs',
    prep_time_minutes: 10,
    cook_time_minutes: 10,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['High-Protein', 'Meal Prep Ready', 'High-Fiber', 'On-the-Go'],
    calories_per_serving: 440,
    protein_g_per_serving: 42,
    carbs_g_per_serving: 36,
    fat_g_per_serving: 14,
    icon_emoji: '🌯',
    ingredients: [
      { food_id: 'turkey-sausage', name: 'Lean Ground Turkey Sausage (93/7)', amount_imperial: '4 oz', amount_metric: '115g', raw_weight_grams_base: 115, department: 'meat_seafood' },
      { food_id: 'liquid-egg-whites', name: 'Liquid Egg Whites', amount_imperial: '1/2 cup (4 oz)', amount_metric: '120 ml', raw_weight_grams_base: 120, department: 'dairy_eggs' },
      { food_id: 'whole-eggs', name: 'Large Whole Egg', amount_imperial: '1 whole', amount_metric: '1 whole', raw_weight_grams_base: 50, department: 'dairy_eggs' },
      { food_id: 'black-beans', name: 'Canned Black Beans (Rinsed)', amount_imperial: '1/4 cup', amount_metric: '45g', raw_weight_grams_base: 45, department: 'pantry_spices' },
      { food_id: 'cheddar-light', name: 'Shredded Reduced-Fat Cheddar', amount_imperial: '2 tablespoons', amount_metric: '21g', raw_weight_grams_base: 21, department: 'dairy_eggs' },
      { food_id: 'tortilla-carb', name: 'Whole Wheat Low-Carb Wrap / Tortilla', amount_imperial: '1 large (2.2 oz)', amount_metric: '62g', raw_weight_grams_base: 62, department: 'grains_bakery' },
      { food_id: 'salsa', name: 'Fresh Chunky Salsa', amount_imperial: '2 tablespoons', amount_metric: '30g', raw_weight_grams_base: 30, department: 'produce' },
    ],
    instructions: [
      'Brown ground turkey sausage in a skillet over medium-high heat (5-6 mins). Drain and set aside.',
      'Scramble whole egg and egg whites in the skillet until fluffy.',
      'Warm tortilla in a dry pan for 15 seconds per side.',
      'Layer eggs, turkey sausage, black beans, cheddar, and salsa down the center.',
      'Roll tightly into a burrito and toast seam-side down in the skillet for 1 minute.',
    ],
    chef_notes: 'Wrap in foil and freeze for up to 1 month. Reheat in an air fryer at 350°F for 10 minutes.',
  },
  {
    id: 'recipe-loaded-cottage-cheese-frittata',
    title: 'Loaded Cottage Cheese & Garden Veggie Frittata',
    description: 'Golden oven-baked frittata enriched with blended cottage cheese for an ultra-creamy, high-protein crustless quiche.',
    category: 'breakfast',
    sub_category: 'high_protein_eggs',
    prep_time_minutes: 10,
    cook_time_minutes: 25,
    servings_yield: 2,
    difficulty: 'easy',
    tags: ['High-Protein', 'Low-Carb', 'Batch Friendly', 'Keto-Friendly'],
    calories_per_serving: 310,
    protein_g_per_serving: 32,
    carbs_g_per_serving: 9,
    fat_g_per_serving: 16,
    icon_emoji: '🥧',
    ingredients: [
      { food_id: 'whole-eggs', name: 'Large Whole Eggs', amount_imperial: '4 whole', amount_metric: '4 whole', raw_weight_grams_base: 200, department: 'dairy_eggs' },
      { food_id: 'cottage-cheese', name: 'Low-Fat 2% Cottage Cheese', amount_imperial: '1 cup (8 oz)', amount_metric: '226g', raw_weight_grams_base: 226, department: 'dairy_eggs' },
      { food_id: 'bell-pepper', name: 'Diced Red Bell Pepper', amount_imperial: '1/2 medium', amount_metric: '60g', raw_weight_grams_base: 60, department: 'produce' },
      { food_id: 'broccoli-florets', name: 'Finely Chopped Broccoli Florets', amount_imperial: '1 cup', amount_metric: '70g', raw_weight_grams_base: 70, department: 'produce' },
      { food_id: 'parmesan', name: 'Grated Parmesan Cheese', amount_imperial: '2 tablespoons', amount_metric: '15g', raw_weight_grams_base: 15, department: 'dairy_eggs' },
    ],
    instructions: [
      'Preheat oven to 375°F (190°C) and grease an 8-inch oven-safe skillet.',
      'Blend eggs, cottage cheese, salt, pepper, and garlic powder for 20 seconds until smooth.',
      'Sauté bell pepper and broccoli in the skillet for 3 minutes until tender-crisp.',
      'Pour blended egg mixture over vegetables, top with parmesan, and bake for 22-25 minutes.',
    ],
    chef_notes: 'Blending cottage cheese eliminates all curds and yields a velvety soufflé texture.',
  },
  {
    id: 'recipe-mediterranean-shakshuka',
    title: 'Mediterranean Shakshuka with Poached Eggs & Pita',
    description: 'Whole eggs gently poached in a rich, spiced tomato and bell pepper sauce with cumin, paprika, and warm whole wheat pita.',
    category: 'breakfast',
    sub_category: 'high_protein_eggs',
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['High-Protein', 'Mediterranean', 'Vegetarian', 'Comfort Food'],
    calories_per_serving: 420,
    protein_g_per_serving: 28,
    carbs_g_per_serving: 38,
    fat_g_per_serving: 18,
    icon_emoji: '🍳',
    ingredients: [
      { food_id: 'whole-eggs', name: 'Large Whole Eggs', amount_imperial: '3 whole', amount_metric: '3 whole', raw_weight_grams_base: 150, department: 'dairy_eggs' },
      { food_id: 'crushed-tomatoes', name: 'Canned Crushed Tomatoes', amount_imperial: '1 cup (8 oz)', amount_metric: '240g', raw_weight_grams_base: 240, department: 'pantry_spices' },
      { food_id: 'bell-pepper', name: 'Diced Bell Pepper & Onions', amount_imperial: '1/2 cup mix', amount_metric: '75g', raw_weight_grams_base: 75, department: 'produce' },
      { food_id: 'feta-cheese', name: 'Crumbled Feta Cheese', amount_imperial: '2 tablespoons', amount_metric: '28g', raw_weight_grams_base: 28, department: 'dairy_eggs' },
      { food_id: 'pita-pocket', name: 'Whole Wheat Pita Pocket', amount_imperial: '1 whole', amount_metric: '50g', raw_weight_grams_base: 50, department: 'grains_bakery' },
      { name: 'Cumin, Paprika, Garlic & Fresh Cilantro', amount_imperial: '1/2 tsp each', amount_metric: '4g', raw_weight_grams_base: 4, department: 'pantry_spices' },
    ],
    instructions: [
      'Sauté diced peppers and onions in a skillet with olive oil spray until softened.',
      'Pour in crushed tomatoes, cumin, paprika, garlic, salt, and pepper. Simmer for 5 minutes.',
      'Make 3 small wells in the sauce and crack whole eggs directly into the wells.',
      'Cover with a lid and simmer gently for 5-7 minutes until egg whites are set and yolks remain runny.',
      'Sprinkle with crumbled feta and cilantro, and serve with toasted whole wheat pita.',
    ],
    chef_notes: 'Dip warm whole wheat pita into the rich spiced tomato sauce and runny yolk for an authentic Mediterranean breakfast.',
  },

  // ==========================================
  // BREAKFAST - OATS & PANCAKES
  // ==========================================
  {
    id: 'recipe-banana-vanilla-protein-pancakes',
    title: 'Fluffy Banana Vanilla Protein Pancakes',
    description: 'Golden stack of high-protein oat pancakes naturally sweetened with ripe banana and whipped with whey isolate.',
    category: 'breakfast',
    sub_category: 'oats_pancakes',
    prep_time_minutes: 5,
    cook_time_minutes: 8,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['High-Protein', 'Gluten-Free', 'Pre-Workout Fuel', 'Comfort Food'],
    calories_per_serving: 420,
    protein_g_per_serving: 40,
    carbs_g_per_serving: 50,
    fat_g_per_serving: 6,
    icon_emoji: '🥞',
    ingredients: [
      { food_id: 'rolled-oats', name: 'Old-Fashioned Rolled Oats', amount_imperial: '1/2 cup (1.5 oz)', amount_metric: '45g', raw_weight_grams_base: 45, department: 'grains_bakery' },
      { food_id: 'whey-isolate', name: 'Vanilla Whey Protein Isolate', amount_imperial: '1 scoop (1.1 oz)', amount_metric: '32g', raw_weight_grams_base: 32, department: 'supplements' },
      { food_id: 'banana', name: 'Ripe Medium Banana', amount_imperial: '1 medium (4 oz)', amount_metric: '115g', raw_weight_grams_base: 115, department: 'produce' },
      { food_id: 'whole-eggs', name: 'Large Whole Egg', amount_imperial: '1 whole', amount_metric: '1 whole', raw_weight_grams_base: 50, department: 'dairy_eggs' },
      { food_id: 'baking-powder', name: 'Baking Powder & Cinnamon', amount_imperial: '1/2 tsp each', amount_metric: '2g each', raw_weight_grams_base: 4, department: 'pantry_spices' },
      { food_id: 'almond-milk', name: 'Unsweetened Almond Milk', amount_imperial: '1/4 cup (2 oz)', amount_metric: '60 ml', raw_weight_grams_base: 60, department: 'dairy_eggs' },
    ],
    instructions: [
      'Blend rolled oats, protein powder, banana, egg, baking powder, cinnamon, and almond milk until smooth.',
      'Heat a non-stick griddle over medium heat and mist with cooking spray.',
      'Pour batter to form 3-4 pancakes. Cook for 2 minutes, flip, and cook for 1-2 minutes until golden.',
      'Serve warm topped with fresh berries and sugar-free syrup.',
    ],
    chef_notes: 'Keep heat medium-low to prevent whey protein from drying out.',
  },
  {
    id: 'recipe-blueberry-chia-overnight-oats',
    title: 'Blueberry Chia & Greek Yogurt Overnight Oats',
    description: 'Cool, creamy morning fuel soaked overnight with rolled oats, Greek yogurt, chia seeds, and antioxidant-rich blueberries.',
    category: 'breakfast',
    sub_category: 'oats_pancakes',
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['No-Cook', 'High-Protein', 'High-Fiber', 'Meal Prep Favorite'],
    calories_per_serving: 390,
    protein_g_per_serving: 32,
    carbs_g_per_serving: 54,
    fat_g_per_serving: 8,
    icon_emoji: '🥣',
    ingredients: [
      { food_id: 'rolled-oats', name: 'Old-Fashioned Rolled Oats', amount_imperial: '1/2 cup (1.5 oz)', amount_metric: '45g', raw_weight_grams_base: 45, department: 'grains_bakery' },
      { food_id: 'greek-yogurt', name: 'Plain Non-Fat Greek Yogurt', amount_imperial: '1/2 cup (4.5 oz)', amount_metric: '130g', raw_weight_grams_base: 130, department: 'dairy_eggs' },
      { food_id: 'almond-milk', name: 'Unsweetened Vanilla Almond Milk', amount_imperial: '1/2 cup (4 oz)', amount_metric: '120 ml', raw_weight_grams_base: 120, department: 'dairy_eggs' },
      { food_id: 'chia-seeds', name: 'Organic Chia Seeds', amount_imperial: '1 tablespoon', amount_metric: '12g', raw_weight_grams_base: 12, department: 'healthy_fats' },
      { food_id: 'blueberries', name: 'Fresh or Frozen Blueberries', amount_imperial: '1/2 cup (2.5 oz)', amount_metric: '75g', raw_weight_grams_base: 75, department: 'produce' },
    ],
    instructions: [
      'In a jar or container, stir oats, chia seeds, Greek yogurt, and almond milk together.',
      'Fold in blueberries, seal with a lid, and refrigerate overnight (minimum 4 hours).',
      'Enjoy chilled with an extra dash of cinnamon.',
    ],
    chef_notes: 'Chia seeds absorb 10x their weight in liquid, creating a thick pudding texture.',
  },
  {
    id: 'recipe-apple-cinnamon-baked-oatmeal',
    title: 'Apple Cinnamon Baked Protein Oatmeal Squares',
    description: 'Warm, fragrant baked oatmeal squares with diced Honeycrisp apples, walnuts, cinnamon, and vanilla whey.',
    category: 'breakfast',
    sub_category: 'oats_pancakes',
    prep_time_minutes: 10,
    cook_time_minutes: 25,
    servings_yield: 4,
    difficulty: 'easy',
    tags: ['4-Serving Batch', 'High-Fiber', 'Meal Prep Breakfast', 'Comfort Food'],
    calories_per_serving: 320,
    protein_g_per_serving: 22,
    carbs_g_per_serving: 42,
    fat_g_per_serving: 8,
    icon_emoji: '🥧',
    ingredients: [
      { food_id: 'rolled-oats', name: 'Old-Fashioned Rolled Oats', amount_imperial: '2 cups', amount_metric: '180g', raw_weight_grams_base: 180, department: 'grains_bakery' },
      { food_id: 'whey-vanilla', name: 'Vanilla Whey Isolate', amount_imperial: '2 scoops (2.2 oz)', amount_metric: '64g', raw_weight_grams_base: 64, department: 'supplements' },
      { food_id: 'apple', name: 'Diced Honeycrisp Apples', amount_imperial: '2 medium apples', amount_metric: '250g', raw_weight_grams_base: 250, department: 'produce' },
      { food_id: 'walnuts', name: 'Chopped Raw Walnuts', amount_imperial: '1/4 cup', amount_metric: '30g', raw_weight_grams_base: 30, department: 'healthy_fats' },
      { food_id: 'almond-milk', name: 'Unsweetened Almond Milk', amount_imperial: '1.5 cups', amount_metric: '360 ml', raw_weight_grams_base: 360, department: 'dairy_eggs' },
      { name: 'Ground Cinnamon, Nutmeg & Baking Powder', amount_imperial: '1 tsp cinnamon + 1 tsp baking powder', amount_metric: '8g', raw_weight_grams_base: 8, department: 'pantry_spices' },
    ],
    instructions: [
      'Preheat oven to 375°F (190°C) and grease an 8x8-inch baking dish.',
      'In a large bowl, mix oats, protein powder, cinnamon, nutmeg, and baking powder.',
      'Stir in almond milk, diced apples, and chopped walnuts.',
      'Pour into baking dish and bake for 25-30 minutes until set and edges are golden.',
      'Slice into 4 large squares. Keeps in the fridge all week.',
    ],
    chef_notes: 'Reheat individual squares in the microwave for 45 seconds with a splash of milk for a warm autumn breakfast.',
  },

  // ==========================================
  // BREAKFAST - SMOOTHIES & BOWLS
  // ==========================================
  {
    id: 'recipe-super-green-power-smoothie',
    title: 'Super Green Power Protein Smoothie',
    description: 'Refreshing nutrient-dense smoothie blended with fresh baby spinach, crisp green apple, whey isolate, and creamy avocado.',
    category: 'breakfast',
    sub_category: 'smoothies_bowls',
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['High-Protein', 'Antioxidant-Rich', '1-Min Prep', 'Gut Health'],
    calories_per_serving: 350,
    protein_g_per_serving: 36,
    carbs_g_per_serving: 32,
    fat_g_per_serving: 9,
    icon_emoji: '🥤',
    ingredients: [
      { food_id: 'whey-vanilla', name: 'Vanilla Whey Protein Isolate', amount_imperial: '1 scoop (1.1 oz)', amount_metric: '32g', raw_weight_grams_base: 32, department: 'supplements' },
      { food_id: 'baby-spinach', name: 'Fresh Baby Spinach', amount_imperial: '2 packed cups', amount_metric: '60g', raw_weight_grams_base: 60, department: 'produce' },
      { food_id: 'green-apple', name: 'Green Granny Smith Apple (Diced)', amount_imperial: '1/2 medium', amount_metric: '90g', raw_weight_grams_base: 90, department: 'produce' },
      { food_id: 'avocado', name: 'Fresh Ripe Avocado', amount_imperial: '1/4 medium (1 oz)', amount_metric: '35g', raw_weight_grams_base: 35, department: 'produce' },
      { food_id: 'almond-milk', name: 'Unsweetened Almond Milk', amount_imperial: '1 cup (8 oz)', amount_metric: '240 ml', raw_weight_grams_base: 240, department: 'dairy_eggs' },
    ],
    instructions: [
      'Add almond milk and fresh spinach to blender first.',
      'Add green apple, avocado, whey protein, and 1 cup of ice cubes.',
      'Blend on high for 60 seconds until silky smooth.',
      'Pour and enjoy immediately.',
    ],
    chef_notes: 'Adding liquid first prevents protein powder from sticking to the blender walls.',
  },
  {
    id: 'recipe-peanut-butter-banana-shake',
    title: 'Peanut Butter Banana Muscle Fuel Shake',
    description: 'Thick, creamy shake with real peanut butter, ripe banana, chocolate whey, and chia seeds for heavy workout recovery.',
    category: 'breakfast',
    sub_category: 'smoothies_bowls',
    prep_time_minutes: 3,
    cook_time_minutes: 0,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['High-Protein', 'Post-Workout', 'Calorie Dense', 'Quick Fuel'],
    calories_per_serving: 490,
    protein_g_per_serving: 44,
    carbs_g_per_serving: 46,
    fat_g_per_serving: 16,
    icon_emoji: '🥜',
    ingredients: [
      { food_id: 'whey-chocolate', name: 'Chocolate Whey Protein Isolate', amount_imperial: '1.5 scoops (1.6 oz)', amount_metric: '48g', raw_weight_grams_base: 48, department: 'supplements' },
      { food_id: 'banana', name: 'Frozen Banana', amount_imperial: '1 medium', amount_metric: '120g', raw_weight_grams_base: 120, department: 'frozen' },
      { food_id: 'peanut-butter', name: 'Natural Creamy Peanut Butter', amount_imperial: '1.5 tablespoons', amount_metric: '24g', raw_weight_grams_base: 24, department: 'healthy_fats' },
      { food_id: 'almond-milk', name: 'Unsweetened Almond Milk', amount_imperial: '1.25 cups (10 oz)', amount_metric: '300 ml', raw_weight_grams_base: 300, department: 'dairy_eggs' },
      { food_id: 'chia-seeds', name: 'Chia Seeds', amount_imperial: '1 teaspoon', amount_metric: '5g', raw_weight_grams_base: 5, department: 'healthy_fats' },
    ],
    instructions: [
      'Place almond milk, chocolate protein powder, frozen banana, peanut butter, and chia seeds in a blender.',
      'Blend on high for 45-60 seconds until creamy and frothy.',
      'Pour into a shaker bottle or glass and enjoy.',
    ],
    chef_notes: 'Using frozen banana slices gives a milkshake-like texture without needing ice.',
  },

  // ==========================================
  // BREAKFAST - GRAB & GO
  // ==========================================
  {
    id: 'recipe-bacon-egg-meal-prep-muffins',
    title: 'Bacon, Egg White & Cheddar Prep Muffins',
    description: 'Savory portable egg muffins baked with uncured bacon crumbles, sharp cheddar, spinach, and bell peppers.',
    category: 'breakfast',
    sub_category: 'quick_grab_go',
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings_yield: 3,
    difficulty: 'easy',
    tags: ['3-Serving Batch', 'High-Protein', 'Low-Carb', 'Grab-and-Go'],
    calories_per_serving: 290,
    protein_g_per_serving: 32,
    carbs_g_per_serving: 4,
    fat_g_per_serving: 16,
    icon_emoji: '🧁',
    ingredients: [
      { food_id: 'liquid-egg-whites', name: 'Liquid Egg Whites', amount_imperial: '1.5 cups (12 oz)', amount_metric: '360 ml', raw_weight_grams_base: 360, department: 'dairy_eggs' },
      { food_id: 'whole-eggs', name: 'Large Whole Eggs', amount_imperial: '3 whole', amount_metric: '3 whole', raw_weight_grams_base: 150, department: 'dairy_eggs' },
      { food_id: 'bacon-center-cut', name: 'Crisp Center-Cut Bacon (Crumbled)', amount_imperial: '4 strips', amount_metric: '56g', raw_weight_grams_base: 56, department: 'meat_seafood' },
      { food_id: 'cheddar-cheese', name: 'Shredded Sharp Cheddar', amount_imperial: '1/3 cup (1.5 oz)', amount_metric: '40g', raw_weight_grams_base: 40, department: 'dairy_eggs' },
      { food_id: 'baby-spinach', name: 'Finely Chopped Baby Spinach', amount_imperial: '1 cup', amount_metric: '30g', raw_weight_grams_base: 30, department: 'produce' },
    ],
    instructions: [
      'Preheat oven to 350°F (175°C) and grease a 6-cup standard muffin tin with cooking spray.',
      'Distribute crumbled bacon, chopped spinach, and cheddar evenly into the 6 muffin cups.',
      'Whisk whole eggs and egg whites with salt and pepper, then pour evenly over the fillings.',
      'Bake for 18-20 minutes until eggs are set and tops are lightly golden.',
      'Cool on a wire rack. Portion 2 muffins per serving.',
    ],
    chef_notes: 'Keeps for 5 days in the fridge. Microwave for 30 seconds for an instant hot breakfast on busy mornings.',
  },

  // ==========================================
  // LUNCH - POWER BOWLS
  // ==========================================
  {
    id: 'recipe-mediterranean-quinoa-harvest-bowl',
    title: 'Mediterranean Grilled Chicken & Quinoa Harvest Bowl',
    description: 'Juicy herb-marinated chicken breast over fluffy cooked quinoa, cucumber-tomato salad, kalamata olives, and tzatziki.',
    category: 'lunch',
    sub_category: 'power_bowls',
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['High-Protein', 'Clean Eating', 'Meal Prep Gold Standard', 'Gluten-Free'],
    calories_per_serving: 540,
    protein_g_per_serving: 48,
    carbs_g_per_serving: 46,
    fat_g_per_serving: 18,
    icon_emoji: '🥗',
    ingredients: [
      { food_id: 'chicken-breast', name: 'Boneless Skinless Chicken Breast', amount_imperial: '6 oz', amount_metric: '170g', raw_weight_grams_base: 170, department: 'meat_seafood' },
      { food_id: 'quinoa', name: 'Cooked Quinoa', amount_imperial: '3/4 cup cooked', amount_metric: '140g', raw_weight_grams_base: 140, department: 'grains_bakery' },
      { food_id: 'cucumber', name: 'Diced English Cucumber', amount_imperial: '1/2 cup', amount_metric: '75g', raw_weight_grams_base: 75, department: 'produce' },
      { food_id: 'cherry-tomatoes', name: 'Halved Cherry Tomatoes', amount_imperial: '1/2 cup', amount_metric: '75g', raw_weight_grams_base: 75, department: 'produce' },
      { food_id: 'tzatziki', name: 'Greek Yogurt Tzatziki Sauce', amount_imperial: '2 tablespoons', amount_metric: '30g', raw_weight_grams_base: 30, department: 'dairy_eggs' },
      { food_id: 'kalamata-olives', name: 'Kalamata Olives', amount_imperial: '1 tablespoon', amount_metric: '15g', raw_weight_grams_base: 15, department: 'pantry_spices' },
    ],
    instructions: [
      'Grill or sear seasoned chicken breast for 6 minutes per side until 165°F. Rest and slice.',
      'Place cooked quinoa at base of bowl.',
      'Arrange sliced chicken, cucumber, tomatoes, and olives in sections.',
      'Dollop tzatziki in the center and serve.',
    ],
    chef_notes: 'Keeps for 4 days in the fridge without losing crunch.',
  },
  {
    id: 'recipe-chipotle-ground-sirloin-bowl',
    title: 'Chipotle-Style Lean Sirloin Burrito Power Bowl',
    description: 'Seasoned lean ground sirloin over cilantro lime brown rice, black beans, sweet corn, fire-roasted salsa, and sliced avocado.',
    category: 'lunch',
    sub_category: 'power_bowls',
    prep_time_minutes: 10,
    cook_time_minutes: 12,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['High-Protein', 'High-Iron', 'Athlete Meal Prep', 'Gluten-Free'],
    calories_per_serving: 580,
    protein_g_per_serving: 46,
    carbs_g_per_serving: 58,
    fat_g_per_serving: 16,
    icon_emoji: '🥑',
    ingredients: [
      { food_id: 'ground-beef', name: 'Extra Lean Ground Sirloin (93/7)', amount_imperial: '5 oz', amount_metric: '140g', raw_weight_grams_base: 140, department: 'meat_seafood' },
      { food_id: 'brown-rice', name: 'Cooked Brown Rice', amount_imperial: '3/4 cup cooked', amount_metric: '145g', raw_weight_grams_base: 145, department: 'grains_bakery' },
      { food_id: 'black-beans', name: 'Canned Black Beans (Rinsed)', amount_imperial: '1/3 cup', amount_metric: '60g', raw_weight_grams_base: 60, department: 'pantry_spices' },
      { food_id: 'sweet-corn', name: 'Sweet Yellow Corn', amount_imperial: '1/4 cup', amount_metric: '40g', raw_weight_grams_base: 40, department: 'frozen' },
      { food_id: 'avocado', name: 'Fresh Avocado', amount_imperial: '1/4 medium', amount_metric: '35g', raw_weight_grams_base: 35, department: 'produce' },
      { food_id: 'salsa', name: 'Fire-Roasted Salsa', amount_imperial: '3 tablespoons', amount_metric: '45g', raw_weight_grams_base: 45, department: 'produce' },
    ],
    instructions: [
      'Brown ground sirloin with taco seasonings in a skillet for 6 minutes.',
      'Spoon brown rice into a bowl, arrange spiced beef, black beans, and corn alongside.',
      'Top with salsa and fresh avocado slices.',
    ],
    chef_notes: 'High in bioavailable iron and zinc to support athletic performance and recovery.',
  },
  {
    id: 'recipe-teriyaki-chicken-power-bowl',
    title: 'Teriyaki Glazed Chicken & Steamed Broccoli Bowl',
    description: 'Tender chicken breast glazed in a light ginger teriyaki sauce over steamed jasmine rice with crisp broccoli florets and sesame seeds.',
    category: 'lunch',
    sub_category: 'power_bowls',
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['High-Protein', 'Clean Asian Flavor', 'Low-Fat', 'Meal Prep Favorite'],
    calories_per_serving: 510,
    protein_g_per_serving: 48,
    carbs_g_per_serving: 58,
    fat_g_per_serving: 8,
    icon_emoji: '🍱',
    ingredients: [
      { food_id: 'chicken-breast', name: 'Diced Chicken Breast', amount_imperial: '6 oz', amount_metric: '170g', raw_weight_grams_base: 170, department: 'meat_seafood' },
      { food_id: 'jasmine-rice', name: 'Cooked Jasmine White Rice', amount_imperial: '3/4 cup cooked', amount_metric: '130g', raw_weight_grams_base: 130, department: 'grains_bakery' },
      { food_id: 'broccoli-florets', name: 'Steamed Fresh Broccoli Florets', amount_imperial: '1.5 cups', amount_metric: '130g', raw_weight_grams_base: 130, department: 'produce' },
      { food_id: 'teriyaki-sauce', name: 'Reduced-Sugar Teriyaki Glaze', amount_imperial: '2 tablespoons', amount_metric: '30 ml', raw_weight_grams_base: 30, department: 'pantry_spices' },
      { name: 'Toasted Sesame Seeds & Green Onions', amount_imperial: '1 tsp each', amount_metric: '5g', raw_weight_grams_base: 5, department: 'pantry_spices' },
    ],
    instructions: [
      'Pan-sear diced chicken in a skillet over medium-high heat until cooked through (6-7 minutes).',
      'Pour teriyaki sauce into the pan, tossing chicken to coat in the bubbling glaze for 60 seconds.',
      'Steam broccoli florets until tender-crisp (4 minutes).',
      'Layer rice in bowl, top with teriyaki chicken and broccoli. Garnish with sesame seeds and green onions.',
    ],
    chef_notes: 'Jasmine rice provides fast-digesting clean carbohydrates ideal for midday workout refueling.',
  },

  // ==========================================
  // LUNCH - WRAPS & SANDWICHES
  // ==========================================
  {
    id: 'recipe-turkey-bacon-avocado-club-wrap',
    title: 'Roasted Turkey, Bacon & Avocado Club Wrap',
    description: 'Thinly sliced deli roast turkey breast, crisp center-cut bacon, sliced ripe avocado, romaine, and tomato wrapped in a high-fiber tortilla.',
    category: 'lunch',
    sub_category: 'wraps_sandwiches',
    prep_time_minutes: 8,
    cook_time_minutes: 4,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['High-Protein', 'Quick Lunch', 'High-Fiber', 'Desk-Friendly'],
    calories_per_serving: 460,
    protein_g_per_serving: 44,
    carbs_g_per_serving: 28,
    fat_g_per_serving: 20,
    icon_emoji: '🌯',
    ingredients: [
      { food_id: 'turkey-breast-deli', name: 'Lean Sliced Roasted Turkey Breast', amount_imperial: '5 oz', amount_metric: '140g', raw_weight_grams_base: 140, department: 'meat_seafood' },
      { food_id: 'bacon-center-cut', name: 'Center-Cut Bacon (Cooked Crisp)', amount_imperial: '2 strips', amount_metric: '28g', raw_weight_grams_base: 28, department: 'meat_seafood' },
      { food_id: 'avocado', name: 'Sliced Avocado', amount_imperial: '1/4 medium', amount_metric: '35g', raw_weight_grams_base: 35, department: 'produce' },
      { food_id: 'romaine-lettuce', name: 'Crisp Romaine Leaves', amount_imperial: '2 large leaves', amount_metric: '30g', raw_weight_grams_base: 30, department: 'produce' },
      { food_id: 'tomato', name: 'Tomato Slices', amount_imperial: '2 thick slices', amount_metric: '60g', raw_weight_grams_base: 60, department: 'produce' },
      { food_id: 'tortilla-carb', name: 'High-Fiber Low-Carb Wrap', amount_imperial: '1 large (2.2 oz)', amount_metric: '62g', raw_weight_grams_base: 62, department: 'grains_bakery' },
      { food_id: 'dijon-mayo', name: 'Dijon Mustard & Light Mayo', amount_imperial: '1 tsp each', amount_metric: '10g', raw_weight_grams_base: 10, department: 'pantry_spices' },
    ],
    instructions: [
      'Spread wrap with mustard and light mayo.',
      'Layer romaine, tomato slices, sliced turkey, avocado, and crispy bacon.',
      'Roll tightly, slice diagonally, and enjoy.',
    ],
    chef_notes: 'High fiber count from the low-carb wrap provides long-lasting satiety without afternoon energy crashes.',
  },
  {
    id: 'recipe-buffalo-chicken-pita-pocket',
    title: 'Spicy Buffalo Chicken Pocket with Greek Ranch',
    description: 'Tender shredded chicken tossed in spicy Frank\'s RedHot stuffed into whole wheat pita pockets with crisp celery, lettuce, and homemade Greek yogurt ranch.',
    category: 'lunch',
    sub_category: 'wraps_sandwiches',
    prep_time_minutes: 8,
    cook_time_minutes: 0,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['High-Protein', 'Spicy', 'Under 400 kcal', 'Quick Lunch'],
    calories_per_serving: 390,
    protein_g_per_serving: 46,
    carbs_g_per_serving: 32,
    fat_g_per_serving: 7,
    icon_emoji: '🌯',
    ingredients: [
      { food_id: 'chicken-breast-cooked', name: 'Cooked Shredded Chicken Breast', amount_imperial: '5 oz', amount_metric: '140g', raw_weight_grams_base: 140, department: 'meat_seafood' },
      { food_id: 'buffalo-sauce', name: "Frank's RedHot Buffalo Sauce", amount_imperial: '2 tablespoons', amount_metric: '30 ml', raw_weight_grams_base: 30, department: 'pantry_spices' },
      { food_id: 'greek-yogurt', name: 'Plain Greek Yogurt (for Ranch)', amount_imperial: '3 tablespoons (1.5 oz)', amount_metric: '45g', raw_weight_grams_base: 45, department: 'dairy_eggs' },
      { food_id: 'pita-pocket', name: 'Whole Wheat Pita Pocket (Halved)', amount_imperial: '1 whole pita', amount_metric: '60g', raw_weight_grams_base: 60, department: 'grains_bakery' },
      { food_id: 'celery-lettuce', name: 'Diced Celery & Shredded Romaine', amount_imperial: '1/2 cup mix', amount_metric: '50g', raw_weight_grams_base: 50, department: 'produce' },
    ],
    instructions: [
      'In a small bowl, mix Greek yogurt with garlic powder, dill, salt, and black pepper to create high-protein ranch.',
      'In another bowl, toss shredded chicken with buffalo sauce.',
      'Open the pita pocket halves, layer with romaine and diced celery, and stuff generously with buffalo chicken.',
      'Drizzle Greek yogurt ranch over top and serve.',
    ],
    chef_notes: 'Greek yogurt ranch replaces high-fat bottled dressings while packing an extra 6g of pure protein.',
  },

  // ==========================================
  // LUNCH - CRISP SALADS
  // ==========================================
  {
    id: 'recipe-blackened-shrimp-cobb-salad',
    title: 'Blackened Gulf Shrimp & Avocado Cobb Salad',
    description: 'Seared blackened shrimp over crisp romaine, hard-boiled egg, avocado, cherry tomatoes, and crumbled blue cheese with light lemon vinaigrette.',
    category: 'lunch',
    sub_category: 'fresh_salads',
    prep_time_minutes: 10,
    cook_time_minutes: 6,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['High-Protein', 'Low-Carb', 'Keto-Friendly', 'Pescatarian'],
    calories_per_serving: 460,
    protein_g_per_serving: 44,
    carbs_g_per_serving: 12,
    fat_g_per_serving: 26,
    icon_emoji: '🍤',
    ingredients: [
      { food_id: 'shrimp-raw', name: 'Raw Jumbo Gulf Shrimp (Peeled & Deveined)', amount_imperial: '6 oz (8-10 shrimp)', amount_metric: '170g', raw_weight_grams_base: 170, department: 'meat_seafood' },
      { food_id: 'hard-boiled-egg', name: 'Hard-Boiled Large Egg', amount_imperial: '1 whole (sliced)', amount_metric: '50g', raw_weight_grams_base: 50, department: 'dairy_eggs' },
      { food_id: 'avocado', name: 'Fresh Sliced Avocado', amount_imperial: '1/3 medium', amount_metric: '45g', raw_weight_grams_base: 45, department: 'produce' },
      { food_id: 'romaine-lettuce', name: 'Chopped Crisp Romaine Lettuce', amount_imperial: '3 cups', amount_metric: '140g', raw_weight_grams_base: 140, department: 'produce' },
      { food_id: 'cherry-tomatoes', name: 'Halved Cherry Tomatoes', amount_imperial: '1/2 cup', amount_metric: '75g', raw_weight_grams_base: 75, department: 'produce' },
      { food_id: 'blue-cheese', name: 'Crumbled Blue Cheese or Feta', amount_imperial: '1.5 tablespoons', amount_metric: '18g', raw_weight_grams_base: 18, department: 'dairy_eggs' },
      { name: 'Blackening Seasoning & Lemon Dressing', amount_imperial: '1 tsp spice + 1 tbsp dressing', amount_metric: '20g', raw_weight_grams_base: 20, department: 'pantry_spices' },
    ],
    instructions: [
      'Toss shrimp with blackening seasoning (smoked paprika, cayenne, garlic, onion powder).',
      'Sear shrimp in a hot skillet for 2-3 minutes per side until pink and opaque.',
      'Place chopped romaine in a large salad bowl.',
      'Arrange blackened shrimp, sliced egg, avocado, tomatoes, and blue cheese in neat rows across the lettuce.',
      'Drizzle with light vinaigrette and freshly squeezed lemon.',
    ],
    chef_notes: 'Shrimp is one of the leanest protein sources on earth with virtually zero carbohydrate or dietary fat.',
  },

  // ==========================================
  // LUNCH - SOUPS & CHILIS
  // ==========================================
  {
    id: 'recipe-hearty-turkey-black-bean-chili',
    title: 'Hearty Lean Turkey & Black Bean Power Chili',
    description: 'Thick, comforting chili packed with 93% lean ground turkey, black beans, kidney beans, crushed fire-roasted tomatoes, and smoky spices.',
    category: 'lunch',
    sub_category: 'soups_chilis',
    prep_time_minutes: 10,
    cook_time_minutes: 30,
    servings_yield: 4,
    difficulty: 'easy',
    tags: ['4-Serving Batch', 'High-Protein', 'High-Fiber', 'Freezer-Friendly', 'Comfort Food'],
    calories_per_serving: 420,
    protein_g_per_serving: 42,
    carbs_g_per_serving: 44,
    fat_g_per_serving: 8,
    icon_emoji: '🍲',
    ingredients: [
      { food_id: 'ground-turkey', name: 'Lean Ground Turkey (93/7)', amount_imperial: '1.25 lbs (20 oz)', amount_metric: '567g', raw_weight_grams_base: 567, department: 'meat_seafood' },
      { food_id: 'black-beans', name: 'Canned Black Beans (Rinsed)', amount_imperial: '1 can (15 oz)', amount_metric: '425g', raw_weight_grams_base: 425, department: 'pantry_spices' },
      { food_id: 'kidney-beans', name: 'Canned Red Kidney Beans (Rinsed)', amount_imperial: '1 can (15 oz)', amount_metric: '425g', raw_weight_grams_base: 425, department: 'pantry_spices' },
      { food_id: 'crushed-tomatoes', name: 'Fire-Roasted Crushed Tomatoes', amount_imperial: '1 can (28 oz)', amount_metric: '794g', raw_weight_grams_base: 794, department: 'pantry_spices' },
      { food_id: 'onion-garlic', name: 'Diced Yellow Onion & Garlic', amount_imperial: '1 onion + 4 cloves garlic', amount_metric: '180g', raw_weight_grams_base: 180, department: 'produce' },
      { name: 'Chili Powder, Cumin, Smoked Paprika & Oregano', amount_imperial: '2 tbsp spice blend', amount_metric: '15g', raw_weight_grams_base: 15, department: 'pantry_spices' },
    ],
    instructions: [
      'In a large pot, sauté diced onion and garlic for 3 minutes until fragrant.',
      'Add ground turkey and brown thoroughly, breaking up into small crumbles (6-7 minutes).',
      'Add chili powder, cumin, paprika, oregano, salt, and pepper. Toast spices for 1 minute.',
      'Pour in crushed tomatoes, black beans, and kidney beans. Bring to a boil.',
      'Reduce heat to low, cover, and simmer for 25-30 minutes, stirring occasionally.',
      'Divide into 4 meal prep containers.',
    ],
    chef_notes: 'Freezes flawlessly for up to 3 months. Tastes even better the second day after spices meld.',
  },

  // ==========================================
  // DINNER - POULTRY & CHICKEN
  // ==========================================
  {
    id: 'recipe-crispy-air-fryer-chicken-thighs',
    title: 'Crispy Lemon Garlic Air-Fryer Chicken Thighs',
    description: 'Juicy, seasoned boneless skinless chicken thighs air-fried to golden perfection and served with roasted garlic green beans.',
    category: 'dinner',
    sub_category: 'poultry_dishes',
    prep_time_minutes: 8,
    cook_time_minutes: 16,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['Air-Fryer', 'High-Protein', 'Low-Carb', 'Juicy & Crispy', '15-Min Dinner'],
    calories_per_serving: 480,
    protein_g_per_serving: 46,
    carbs_g_per_serving: 8,
    fat_g_per_serving: 28,
    icon_emoji: '🍗',
    ingredients: [
      { food_id: 'chicken-thighs', name: 'Boneless Skinless Chicken Thighs', amount_imperial: '7 oz', amount_metric: '200g', raw_weight_grams_base: 200, department: 'meat_seafood' },
      { food_id: 'green-beans', name: 'Fresh Green Beans', amount_imperial: '1.5 cups', amount_metric: '150g', raw_weight_grams_base: 150, department: 'produce' },
      { food_id: 'olive-oil', name: 'Extra Virgin Olive Oil', amount_imperial: '1 tablespoon', amount_metric: '15 ml', raw_weight_grams_base: 14, department: 'healthy_fats' },
      { name: 'Garlic, Paprika & Thyme', amount_imperial: '1/2 tsp each', amount_metric: '6g', raw_weight_grams_base: 6, department: 'pantry_spices' },
    ],
    instructions: [
      'Toss chicken thighs with olive oil, garlic powder, paprika, thyme, salt, and pepper.',
      'Air fry at 390°F (200°C) for 14-16 minutes, flipping halfway through.',
      'Add green beans in the last 6 minutes to roast alongside chicken.',
      'Finish with fresh lemon juice.',
    ],
    chef_notes: 'Chicken thighs retain rich moisture and stay juicy even when reheated.',
  },
  {
    id: 'recipe-healthy-chicken-piccata',
    title: 'Classic Light Chicken Piccata with Capers',
    description: 'Thin chicken cutlets seared in a bright lemon white wine sauce with briny non-pareil capers and fresh parsley.',
    category: 'dinner',
    sub_category: 'poultry_dishes',
    prep_time_minutes: 10,
    cook_time_minutes: 12,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['High-Protein', 'Gourmet', 'Under 400 kcal', '15-Min Dinner'],
    calories_per_serving: 380,
    protein_g_per_serving: 50,
    carbs_g_per_serving: 6,
    fat_g_per_serving: 14,
    icon_emoji: '🍗',
    ingredients: [
      { food_id: 'chicken-breast', name: 'Chicken Breast (Pounded Thin into Cutlets)', amount_imperial: '6 oz', amount_metric: '170g', raw_weight_grams_base: 170, department: 'meat_seafood' },
      { food_id: 'capers', name: 'Non-Pareil Capers (Drained)', amount_imperial: '1 tablespoon', amount_metric: '15g', raw_weight_grams_base: 15, department: 'pantry_spices' },
      { food_id: 'lemon-juice', name: 'Fresh Squeezed Lemon Juice', amount_imperial: '2 tablespoons', amount_metric: '30 ml', raw_weight_grams_base: 30, department: 'produce' },
      { food_id: 'chicken-broth', name: 'Low-Sodium Chicken Broth', amount_imperial: '1/3 cup', amount_metric: '80 ml', raw_weight_grams_base: 80, department: 'pantry_spices' },
      { food_id: 'butter', name: 'Grass-Fed Butter', amount_imperial: '1/2 tablespoon', amount_metric: '7g', raw_weight_grams_base: 7, department: 'dairy_eggs' },
      { food_id: 'olive-oil', name: 'Olive Oil', amount_imperial: '1 teaspoon', amount_metric: '5 ml', raw_weight_grams_base: 5, department: 'healthy_fats' },
    ],
    instructions: [
      'Pound chicken breasts to 1/2-inch thickness. Season with salt and pepper.',
      'Heat olive oil in a skillet over medium-high heat. Sear cutlets for 3-4 minutes per side until golden. Remove to a plate.',
      'Add chicken broth, lemon juice, and capers to the pan, scraping up browned bits. Simmer for 2 minutes to reduce.',
      'Swirl in butter to create a silky sauce. Return chicken cutlets to the pan to coat in sauce.',
      'Garnish with chopped fresh parsley and serve.',
    ],
    chef_notes: 'Pounding chicken thin ensures fast, uniform cooking without drying out the edges.',
  },

  // ==========================================
  // DINNER - STEAKS & SIRLOIN
  // ==========================================
  {
    id: 'recipe-cast-iron-flank-steak-asparagus',
    title: 'Cast-Iron Garlic Butter Flank Steak & Asparagus',
    description: 'High-heat seared lean flank steak basted with garlic and rosemary, accompanied by charred crisp asparagus.',
    category: 'dinner',
    sub_category: 'beef_steaks',
    prep_time_minutes: 10,
    cook_time_minutes: 10,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['High-Protein', 'Low-Carb', 'Keto-Friendly', 'Iron-Rich', '10-Min Cook'],
    calories_per_serving: 510,
    protein_g_per_serving: 52,
    carbs_g_per_serving: 6,
    fat_g_per_serving: 30,
    icon_emoji: '🥩',
    ingredients: [
      { food_id: 'flank-steak', name: 'Lean Beef Flank Steak', amount_imperial: '7 oz', amount_metric: '200g', raw_weight_grams_base: 200, department: 'meat_seafood' },
      { food_id: 'asparagus', name: 'Fresh Asparagus Spears', amount_imperial: '1.5 cups', amount_metric: '200g', raw_weight_grams_base: 200, department: 'produce' },
      { food_id: 'butter', name: 'Grass-Fed Butter', amount_imperial: '1 tablespoon', amount_metric: '14g', raw_weight_grams_base: 14, department: 'dairy_eggs' },
      { food_id: 'garlic-cloves', name: 'Garlic & Rosemary', amount_imperial: '2 cloves + 1 sprig', amount_metric: '10g', raw_weight_grams_base: 10, department: 'produce' },
    ],
    instructions: [
      'Pat flank steak dry and season with coarse salt and black pepper.',
      'Sear in a smoking hot cast iron skillet for 4 minutes per side, basting with garlic butter and rosemary.',
      'Rest steak on cutting board for 6 minutes, then slice thinly against the grain.',
      'Sauté asparagus in pan drippings for 4 minutes and serve alongside steak.',
    ],
    chef_notes: 'Slice against the grain at a 45-degree angle for maximum tenderness.',
  },
  {
    id: 'recipe-lean-bison-smash-burgers',
    title: 'Homemade Lean Bison Smash Burgers & Sweet Potato Fries',
    description: 'Crispy-edged seared lean bison patties topped with cheddar and caramelized onions on a brioche bun with baked sweet potato fries.',
    category: 'dinner',
    sub_category: 'beef_steaks',
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['High-Protein', 'High-Iron', 'Cheat Meal Re-Engineered', 'Fan Favorite'],
    calories_per_serving: 570,
    protein_g_per_serving: 48,
    carbs_g_per_serving: 46,
    fat_g_per_serving: 20,
    icon_emoji: '🍔',
    ingredients: [
      { food_id: 'ground-bison', name: 'Lean Ground Bison (90/10)', amount_imperial: '6 oz (two 3-oz balls)', amount_metric: '170g', raw_weight_grams_base: 170, department: 'meat_seafood' },
      { food_id: 'cheddar-slice', name: 'Sharp Cheddar Cheese Slice', amount_imperial: '1 slice (1 oz)', amount_metric: '28g', raw_weight_grams_base: 28, department: 'dairy_eggs' },
      { food_id: 'brioche-bun', name: 'Light Brioche Burger Bun', amount_imperial: '1 bun', amount_metric: '50g', raw_weight_grams_base: 50, department: 'grains_bakery' },
      { food_id: 'sweet-potato', name: 'Sweet Potato Fries (Baked/Air-Fried)', amount_imperial: '1 cup (approx. 4 oz)', amount_metric: '115g', raw_weight_grams_base: 115, department: 'produce' },
      { food_id: 'onion', name: 'Thinly Sliced Red Onion & Pickles', amount_imperial: '2 tbsp each', amount_metric: '30g', raw_weight_grams_base: 30, department: 'produce' },
    ],
    instructions: [
      'Preheat cast iron skillet over high heat until smoking.',
      'Place two 3-oz bison balls onto the dry hot skillet and smash flat with a sturdy spatula.',
      'Season with salt and pepper and sear undisturbed for 2.5 minutes until a deep caramelized crust forms.',
      'Flip patties, top one with cheddar, stack patties, and cook for 1 minute.',
      'Toast bun, assemble burger with onion and pickles, and serve with baked sweet potato fries.',
    ],
    chef_notes: 'Bison is leaner than conventional beef while containing higher concentrations of creatine, CLA, and iron.',
  },

  // ==========================================
  // DINNER - SEAFOOD & FISH
  // ==========================================
  {
    id: 'recipe-sheet-pan-wild-salmon-sweet-potato',
    title: 'Sheet-Pan Wild Salmon & Herb Roasted Sweet Potato',
    description: 'Crispy wild Atlantic salmon filet paired with caramelized sweet potato wedges and tender garlic asparagus.',
    category: 'dinner',
    sub_category: 'seafood_fish',
    prep_time_minutes: 15,
    cook_time_minutes: 20,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['1-Pan', 'High-Protein', 'Omega-3s', 'Gluten-Free', '15-Min Prep'],
    calories_per_serving: 580,
    protein_g_per_serving: 46,
    carbs_g_per_serving: 48,
    fat_g_per_serving: 22,
    icon_emoji: '🐟',
    ingredients: [
      { food_id: 'salmon-wild', name: 'Wild Atlantic Salmon Filet', amount_imperial: '6 oz', amount_metric: '170g', raw_weight_grams_base: 170, department: 'meat_seafood' },
      { food_id: 'sweet-potato', name: 'Diced Sweet Potato', amount_imperial: '1 medium (7 oz)', amount_metric: '200g', raw_weight_grams_base: 200, department: 'produce' },
      { food_id: 'asparagus', name: 'Fresh Asparagus Spears', amount_imperial: '1 cup (5 oz)', amount_metric: '140g', raw_weight_grams_base: 140, department: 'produce' },
      { food_id: 'olive-oil', name: 'Extra Virgin Olive Oil', amount_imperial: '1 tablespoon', amount_metric: '15 ml', raw_weight_grams_base: 14, department: 'healthy_fats' },
    ],
    instructions: [
      'Roast diced sweet potatoes in olive oil on baking sheet for 10 minutes at 400°F (200°C).',
      'Add salmon filet and asparagus, drizzle with oil and seasonings, and roast for another 12 minutes.',
      'Squeeze fresh lemon over salmon and serve.',
    ],
    chef_notes: 'Wild Atlantic salmon contains potent anti-inflammatory EPA and DHA Omega-3 fatty acids.',
  },
  {
    id: 'recipe-blackened-mahi-mahi-tacos',
    title: 'Blackened Mahi-Mahi Fish Tacos with Lime Slaw',
    description: 'Flaky blackened mahi-mahi filets tucked into warm corn tortillas with crunchy cilantro lime cabbage slaw and avocado crema.',
    category: 'dinner',
    sub_category: 'seafood_fish',
    prep_time_minutes: 10,
    cook_time_minutes: 8,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['High-Protein', 'Fresh Coastal', 'Gluten-Free', 'Under 450 kcal'],
    calories_per_serving: 430,
    protein_g_per_serving: 44,
    carbs_g_per_serving: 36,
    fat_g_per_serving: 12,
    icon_emoji: '🌮',
    ingredients: [
      { food_id: 'mahi-mahi', name: 'Wild Mahi-Mahi Filet', amount_imperial: '6 oz', amount_metric: '170g', raw_weight_grams_base: 170, department: 'meat_seafood' },
      { food_id: 'corn-tortillas', name: 'White Corn Tortillas', amount_imperial: '3 small tortillas', amount_metric: '75g', raw_weight_grams_base: 75, department: 'grains_bakery' },
      { food_id: 'shredded-cabbage', name: 'Shredded Red & Green Cabbage', amount_imperial: '1 cup', amount_metric: '70g', raw_weight_grams_base: 70, department: 'produce' },
      { food_id: 'greek-yogurt', name: 'Plain Greek Yogurt (for Crema)', amount_imperial: '2 tablespoons', amount_metric: '30g', raw_weight_grams_base: 30, department: 'dairy_eggs' },
      { food_id: 'lime-cilantro', name: 'Fresh Lime & Cilantro', amount_imperial: '1 lime + 2 tbsp cilantro', amount_metric: '30g', raw_weight_grams_base: 30, department: 'produce' },
      { name: 'Cajun Blackening Spices', amount_imperial: '1 teaspoon', amount_metric: '4g', raw_weight_grams_base: 4, department: 'pantry_spices' },
    ],
    instructions: [
      'Coat mahi-mahi in blackening seasoning.',
      'Sear in a hot skillet with olive oil spray for 3-4 minutes per side until fish flakes easily.',
      'Mix shredded cabbage with Greek yogurt, lime juice, and chopped cilantro.',
      'Warm corn tortillas, flake mahi-mahi evenly across tortillas, and top with crunchy lime slaw.',
    ],
    chef_notes: 'Mahi-mahi is firm and holds its shape exceptionally well for tacos compared to softer white fish.',
  },

  // ==========================================
  // DINNER - PASTAS & BAKES
  // ==========================================
  {
    id: 'recipe-lean-turkey-bolognese-chickpea-pasta',
    title: 'High-Protein Lean Turkey Bolognese over Chickpea Pasta',
    description: 'Slow-simmered rich Italian meat sauce made with 93% lean ground turkey, crushed San Marzano tomatoes, and garlic over high-protein chickpea pasta.',
    category: 'dinner',
    sub_category: 'pasta_comfort',
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['High-Protein', 'Gluten-Free', 'Comfort Food', 'Meal Prep Friendly'],
    calories_per_serving: 590,
    protein_g_per_serving: 56,
    carbs_g_per_serving: 52,
    fat_g_per_serving: 16,
    icon_emoji: '🍝',
    ingredients: [
      { food_id: 'ground-turkey', name: 'Lean Ground Turkey (93/7)', amount_imperial: '6 oz', amount_metric: '170g', raw_weight_grams_base: 170, department: 'meat_seafood' },
      { food_id: 'chickpea-pasta', name: 'Chickpea Penne Pasta (Dry)', amount_imperial: '2 oz (1 cup cooked)', amount_metric: '56g', raw_weight_grams_base: 56, department: 'grains_bakery' },
      { food_id: 'crushed-tomatoes', name: 'Crushed San Marzano Tomatoes', amount_imperial: '3/4 cup', amount_metric: '180g', raw_weight_grams_base: 180, department: 'pantry_spices' },
      { food_id: 'parmesan', name: 'Freshly Grated Parmesan', amount_imperial: '2 tablespoons', amount_metric: '15g', raw_weight_grams_base: 15, department: 'dairy_eggs' },
    ],
    instructions: [
      'Boil chickpea pasta for 7-8 minutes until al dente. Drain.',
      'Brown ground turkey with garlic and onion in a saucepan for 6 minutes.',
      'Stir in crushed tomatoes and Italian herbs; simmer for 12 minutes.',
      'Toss pasta in sauce, plate, and top with parmesan cheese.',
    ],
    chef_notes: 'Chickpea pasta delivers double the protein of traditional pasta with identical texture.',
  },
  {
    id: 'recipe-creamy-cottage-cheese-alfredo',
    title: 'Creamy Garlic Cottage Cheese Alfredo & Chicken Pasta',
    description: 'Silky, guilt-free Alfredo sauce blended from low-fat cottage cheese, garlic, and parmesan tossed with grilled chicken and penne.',
    category: 'dinner',
    sub_category: 'pasta_comfort',
    prep_time_minutes: 10,
    cook_time_minutes: 12,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['High-Protein', 'Comfort Food', 'Guilt-Free Alfredo', 'Under 500 kcal'],
    calories_per_serving: 510,
    protein_g_per_serving: 58,
    carbs_g_per_serving: 46,
    fat_g_per_serving: 10,
    icon_emoji: '🍝',
    ingredients: [
      { food_id: 'chicken-breast', name: 'Sliced Grilled Chicken Breast', amount_imperial: '5 oz', amount_metric: '140g', raw_weight_grams_base: 140, department: 'meat_seafood' },
      { food_id: 'cottage-cheese', name: 'Low-Fat 2% Cottage Cheese', amount_imperial: '3/4 cup (6 oz)', amount_metric: '170g', raw_weight_grams_base: 170, department: 'dairy_eggs' },
      { food_id: 'chickpea-pasta', name: 'Penne or Fettuccine Pasta (Dry)', amount_imperial: '2 oz', amount_metric: '56g', raw_weight_grams_base: 56, department: 'grains_bakery' },
      { food_id: 'parmesan', name: 'Grated Parmesan Cheese', amount_imperial: '2 tablespoons', amount_metric: '15g', raw_weight_grams_base: 15, department: 'dairy_eggs' },
      { food_id: 'garlic-cloves', name: 'Minced Garlic & Black Pepper', amount_imperial: '2 cloves', amount_metric: '10g', raw_weight_grams_base: 10, department: 'produce' },
    ],
    instructions: [
      'Boil pasta in salted water until al dente. Reserve 2 tablespoons of pasta water, then drain.',
      'In a blender, blend cottage cheese, parmesan, minced garlic, pasta water, salt, and black pepper until completely smooth and velvety.',
      'Pour sauce into a warm pan over low heat (do not boil).',
      'Toss pasta and sliced chicken in the creamy alfredo sauce until warmed through.',
      'Garnish with cracked black pepper and fresh parsley.',
    ],
    chef_notes: 'Blended cottage cheese creates a decadent Alfredo sauce with 80% less fat and 3x more protein than heavy cream.',
  },

  // ==========================================
  // BULK MEAL PREP - SHEET-PAN PREPS
  // ==========================================
  {
    id: 'recipe-sheet-pan-sausage-peppers-potatoes',
    title: 'Sheet-Pan Turkey Sausage, Peppers & Baby Gold Potatoes',
    description: 'Crisp roasted turkey sausage coins tossed with rainbow bell peppers, red onions, and seasoned baby gold potatoes.',
    category: 'bulk_meal_prep',
    sub_category: 'sheet_pan_meals',
    prep_time_minutes: 15,
    cook_time_minutes: 25,
    servings_yield: 4,
    difficulty: 'easy',
    tags: ['4-Serving Batch', '1-Pan', 'High-Protein', 'Easy Cleanup', 'Gluten-Free'],
    calories_per_serving: 440,
    protein_g_per_serving: 36,
    carbs_g_per_serving: 42,
    fat_g_per_serving: 14,
    icon_emoji: '🥘',
    ingredients: [
      { food_id: 'turkey-smoked-sausage', name: 'Lean Smoked Turkey Sausage Links (Sliced)', amount_imperial: '16 oz (1 lb)', amount_metric: '454g', raw_weight_grams_base: 454, department: 'meat_seafood' },
      { food_id: 'baby-potatoes', name: 'Baby Yukon Gold Potatoes (Halved)', amount_imperial: '1.5 lbs (24 oz)', amount_metric: '680g', raw_weight_grams_base: 680, department: 'produce' },
      { food_id: 'bell-peppers-mix', name: 'Assorted Bell Peppers (Sliced)', amount_imperial: '3 large peppers', amount_metric: '450g', raw_weight_grams_base: 450, department: 'produce' },
      { food_id: 'red-onion', name: 'Red Onion (Cut into Wedges)', amount_imperial: '1 large onion', amount_metric: '180g', raw_weight_grams_base: 180, department: 'produce' },
      { food_id: 'olive-oil', name: 'Extra Virgin Olive Oil', amount_imperial: '2 tablespoons', amount_metric: '30 ml', raw_weight_grams_base: 28, department: 'healthy_fats' },
    ],
    instructions: [
      'Roast halved baby potatoes in olive oil on baking sheet at 400°F (200°C) for 12 minutes.',
      'Add sliced turkey sausage, bell peppers, and onions to the sheet with remaining oil and seasonings.',
      'Roast for another 18-20 minutes until potatoes are crispy and sausage edges are caramelized.',
      'Divide evenly into 4 meal prep containers.',
    ],
    chef_notes: 'An all-in-one meal prep staple that reheats crisply all week.',
  },

  // ==========================================
  // BULK MEAL PREP - SLOW COOKER & POT
  // ==========================================
  {
    id: 'recipe-slow-cooker-salsa-verde-chicken',
    title: 'Slow Cooker 4-Ingredient Salsa Verde Shredded Chicken',
    description: 'Tender, juicy Mexican shredded chicken breast slow cooked in tangy tomatillo salsa verde, cumin, and lime for effortless weekly bowls and tacos.',
    category: 'bulk_meal_prep',
    sub_category: 'slow_cooker_instant_pot',
    prep_time_minutes: 5,
    cook_time_minutes: 240,
    servings_yield: 5,
    difficulty: 'easy',
    tags: ['5-Serving Batch', 'Slow-Cooker', 'Ultra High-Protein', 'Low-Fat', 'Keto-Friendly'],
    calories_per_serving: 260,
    protein_g_per_serving: 46,
    carbs_g_per_serving: 4,
    fat_g_per_serving: 4,
    icon_emoji: '🍲',
    ingredients: [
      { food_id: 'chicken-breast', name: 'Boneless Skinless Chicken Breasts', amount_imperial: '2.5 lbs (40 oz)', amount_metric: '1.13 kg', raw_weight_grams_base: 1130, department: 'meat_seafood' },
      { food_id: 'salsa-verde', name: 'Jarred Salsa Verde / Tomatillo Salsa', amount_imperial: '1 jar (16 oz)', amount_metric: '454g', raw_weight_grams_base: 454, department: 'pantry_spices' },
      { food_id: 'lime-juice', name: 'Fresh Lime Juice', amount_imperial: '2 limes', amount_metric: '40 ml', raw_weight_grams_base: 40, department: 'produce' },
      { name: 'Ground Cumin & Garlic Powder', amount_imperial: '1 tbsp total', amount_metric: '10g', raw_weight_grams_base: 10, department: 'pantry_spices' },
    ],
    instructions: [
      'Place raw chicken breasts in slow cooker.',
      'Season with cumin and garlic powder, and pour jar of salsa verde over top.',
      'Cover and cook on LOW for 6-7 hours or HIGH for 3.5 hours.',
      'Shred chicken with two forks directly in the pot juices, squeeze with lime, and portion into 5 containers.',
    ],
    chef_notes: 'Use across rice bowls, wraps, salads, or high-protein quesadillas.',
  },

  // ==========================================
  // BULK MEAL PREP - CASSEROLES & BAKES
  // ==========================================
  {
    id: 'recipe-high-protein-shepherds-pie',
    title: 'High-Protein Turkey & Sweet Potato Shepherd\'s Pie',
    description: 'Savory stew of lean ground turkey, carrots, peas, and rich bone broth gravy topped with velvety whipped sweet potato mash.',
    category: 'bulk_meal_prep',
    sub_category: 'casseroles_bakes',
    prep_time_minutes: 15,
    cook_time_minutes: 30,
    servings_yield: 4,
    difficulty: 'easy',
    tags: ['4-Serving Batch', 'High-Protein', 'Clean Carbs', 'Comfort Food'],
    calories_per_serving: 460,
    protein_g_per_serving: 42,
    carbs_g_per_serving: 46,
    fat_g_per_serving: 12,
    icon_emoji: '🥧',
    ingredients: [
      { food_id: 'ground-turkey', name: 'Lean Ground Turkey (93/7)', amount_imperial: '1.25 lbs (20 oz)', amount_metric: '567g', raw_weight_grams_base: 567, department: 'meat_seafood' },
      { food_id: 'sweet-potatoes', name: 'Mashed Cooked Sweet Potatoes', amount_imperial: '3 medium (20 oz)', amount_metric: '560g', raw_weight_grams_base: 560, department: 'produce' },
      { food_id: 'peas-carrots', name: 'Frozen Peas & Carrots Medley', amount_imperial: '1.5 cups', amount_metric: '200g', raw_weight_grams_base: 200, department: 'frozen' },
      { food_id: 'beef-broth', name: 'Beef Bone Broth', amount_imperial: '3/4 cup', amount_metric: '180 ml', raw_weight_grams_base: 180, department: 'pantry_spices' },
      { food_id: 'tomato-paste', name: 'Tomato Paste & Worcestershire Sauce', amount_imperial: '1 tbsp each', amount_metric: '30g', raw_weight_grams_base: 30, department: 'pantry_spices' },
    ],
    instructions: [
      'Brown ground turkey with onions in a skillet. Stir in tomato paste, Worcestershire, broth, peas, and carrots. Simmer 5 mins.',
      'Transfer meat filling into a 9x13 inch baking dish.',
      'Spread mashed sweet potatoes evenly over top. Score with a fork for crispy peaks.',
      'Bake at 400°F (200°C) for 25 minutes until bubbling and golden on top.',
      'Portion into 4 containers.',
    ],
    chef_notes: 'Sweet potatoes provide steady low-glycemic carbohydrates alongside rich vitamin A and beta-carotene.',
  },

  // ==========================================
  // SNACKS & DESSERTS - BARS & BITES
  // ==========================================
  {
    id: 'recipe-chewy-peanut-butter-protein-bars',
    title: 'Homemade Chewy Peanut Butter Chocolate Protein Bars',
    description: 'No-bake, chewy protein bars made with creamy natural peanut butter, rolled oats, whey isolate, and dark chocolate drizzle.',
    category: 'snack_dessert',
    sub_category: 'protein_bites_bars',
    prep_time_minutes: 10,
    cook_time_minutes: 0,
    servings_yield: 6,
    difficulty: 'easy',
    tags: ['No-Bake', 'High-Protein', 'Meal Prep Snack', '6-Serving Batch'],
    calories_per_serving: 280,
    protein_g_per_serving: 20,
    carbs_g_per_serving: 22,
    fat_g_per_serving: 12,
    icon_emoji: '🍫',
    ingredients: [
      { food_id: 'peanut-butter', name: 'Natural Creamy Peanut Butter', amount_imperial: '1/2 cup', amount_metric: '128g', raw_weight_grams_base: 128, department: 'healthy_fats' },
      { food_id: 'honey', name: 'Pure Honey or Maple Syrup', amount_imperial: '1/3 cup', amount_metric: '110g', raw_weight_grams_base: 110, department: 'pantry_spices' },
      { food_id: 'whey-isolate', name: 'Vanilla or Chocolate Whey Isolate', amount_imperial: '3 scoops (3.4 oz)', amount_metric: '96g', raw_weight_grams_base: 96, department: 'supplements' },
      { food_id: 'rolled-oats', name: 'Old-Fashioned Rolled Oats', amount_imperial: '1 cup', amount_metric: '90g', raw_weight_grams_base: 90, department: 'grains_bakery' },
      { food_id: 'dark-chocolate', name: 'Dark Chocolate Chips (Melted)', amount_imperial: '2 tablespoons', amount_metric: '30g', raw_weight_grams_base: 30, department: 'pantry_spices' },
    ],
    instructions: [
      'Warm peanut butter and honey in a microwave-safe bowl for 20 seconds.',
      'Stir in whey protein and oats until a thick dough forms.',
      'Press into an 8x8 baking pan lined with parchment, drizzle with melted dark chocolate, and freeze for 20 minutes.',
      'Slice into 6 bars and store in the fridge.',
    ],
    chef_notes: '100% whole food ingredients with zero chemical fillers.',
  },

  // ==========================================
  // SNACKS & DESSERTS - SWEET TREATS
  // ==========================================
  {
    id: 'recipe-anabolic-protein-fluff',
    title: 'Anabolic Post-Workout Berry Protein Fluff',
    description: 'High-volume frozen dessert whipped with whey isolate, frozen berries, and almond milk into an ice-cream like texture.',
    category: 'snack_dessert',
    sub_category: 'sweet_treats',
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['Post-Workout', 'High-Volume', 'Under 250 kcal', 'Craving Crusher'],
    calories_per_serving: 230,
    protein_g_per_serving: 32,
    carbs_g_per_serving: 22,
    fat_g_per_serving: 2,
    icon_emoji: '🍨',
    ingredients: [
      { food_id: 'whey-protein', name: 'Vanilla or Strawberry Whey Isolate', amount_imperial: '1 scoop (1.1 oz)', amount_metric: '32g', raw_weight_grams_base: 32, department: 'supplements' },
      { food_id: 'strawberries', name: 'Frozen Strawberries or Mixed Berries', amount_imperial: '1 cup frozen (5 oz)', amount_metric: '140g', raw_weight_grams_base: 140, department: 'frozen' },
      { food_id: 'almond-milk', name: 'Unsweetened Almond Milk', amount_imperial: '1/3 cup (splash)', amount_metric: '80 ml', raw_weight_grams_base: 80, department: 'dairy_eggs' },
      { name: 'Xanthan Gum (Optional for extra volume)', amount_imperial: '1/4 teaspoon', amount_metric: '1g', raw_weight_grams_base: 1, department: 'pantry_spices' },
    ],
    instructions: [
      'Pulse frozen berries and almond milk in a blender into a slush.',
      'Add whey protein and xanthan gum.',
      'Blend on high with tamper for 2-3 minutes until volume doubles into fluffy soft-serve ice cream.',
      'Enjoy immediately in a chilled bowl with a spoon.',
    ],
    chef_notes: 'Massive volume that crushes sweet cravings while delivering 32g protein.',
  },
  {
    id: 'recipe-greek-yogurt-berry-bark',
    title: 'High-Protein Frozen Greek Yogurt Berry Bark',
    description: 'Crisp frozen snack bark made with Greek yogurt, honey, fresh berries, chia seeds, and sliced almonds.',
    category: 'snack_dessert',
    sub_category: 'sweet_treats',
    prep_time_minutes: 8,
    cook_time_minutes: 0,
    servings_yield: 4,
    difficulty: 'easy',
    tags: ['4-Serving Batch', 'High-Protein', 'Freezer Snack', 'Kid Friendly'],
    calories_per_serving: 140,
    protein_g_per_serving: 14,
    carbs_g_per_serving: 14,
    fat_g_per_serving: 3,
    icon_emoji: '🍓',
    ingredients: [
      { food_id: 'greek-yogurt', name: 'Plain Non-Fat Greek Yogurt', amount_imperial: '2 cups (18 oz)', amount_metric: '500g', raw_weight_grams_base: 500, department: 'dairy_eggs' },
      { food_id: 'honey', name: 'Pure Honey or Maple Syrup', amount_imperial: '2 tablespoons', amount_metric: '40g', raw_weight_grams_base: 40, department: 'pantry_spices' },
      { food_id: 'strawberries', name: 'Diced Fresh Strawberries & Blueberries', amount_imperial: '1 cup mix', amount_metric: '150g', raw_weight_grams_base: 150, department: 'produce' },
      { food_id: 'sliced-almonds', name: 'Toasted Sliced Almonds & Chia Seeds', amount_imperial: '2 tbsp each', amount_metric: '30g', raw_weight_grams_base: 30, department: 'healthy_fats' },
    ],
    instructions: [
      'Mix Greek yogurt and honey together in a bowl.',
      'Line a baking sheet with parchment paper and spread yogurt evenly to 1/4-inch thickness.',
      'Scatter fresh berries, sliced almonds, and chia seeds over the yogurt and press gently.',
      'Freeze for 2-3 hours until completely solid. Break or snap into bark pieces.',
      'Store in a freezer bag for a quick grab-and-go cooling snack.',
    ],
    chef_notes: 'A guilt-free high-protein replacement for ice cream bars during hot summer afternoons.',
  },

  // ==========================================
  // SNACKS & DESSERTS - SAVORY CRUNCH
  // ==========================================
  {
    id: 'recipe-crispy-air-fried-chickpeas',
    title: 'Crispy Sea Salt & Smoked Paprika Air-Fried Chickpeas',
    description: 'Crunchy, addictive roasted chickpeas seasoned with smoked paprika, garlic, and sea salt for a high-fiber savory snack.',
    category: 'snack_dessert',
    sub_category: 'savory_crunch',
    prep_time_minutes: 5,
    cook_time_minutes: 15,
    servings_yield: 2,
    difficulty: 'easy',
    tags: ['High-Fiber', 'Plant Protein', 'Air-Fryer', 'Crunchy Snack'],
    calories_per_serving: 180,
    protein_g_per_serving: 8,
    carbs_g_per_serving: 26,
    fat_g_per_serving: 5,
    icon_emoji: '🧆',
    ingredients: [
      { food_id: 'chickpeas', name: 'Canned Chickpeas (Drained & Dried)', amount_imperial: '1 can (15 oz)', amount_metric: '250g', raw_weight_grams_base: 250, department: 'pantry_spices' },
      { food_id: 'olive-oil', name: 'Extra Virgin Olive Oil', amount_imperial: '1 teaspoon', amount_metric: '5 ml', raw_weight_grams_base: 5, department: 'healthy_fats' },
      { name: 'Paprika, Garlic & Sea Salt', amount_imperial: '1/2 tsp each', amount_metric: '4g', raw_weight_grams_base: 4, department: 'pantry_spices' },
    ],
    instructions: [
      'Pat chickpeas completely dry with paper towels.',
      'Toss in olive oil and seasonings.',
      'Air fry at 390°F (200°C) for 12-15 minutes, shaking every 4 minutes until golden and crunchy.',
      'Let cool for 5 minutes before snacking.',
    ],
    chef_notes: 'Prebiotic fiber fuels healthy gut microbiome while satisfying chip cravings.',
  },
];
