import { RecipeItem, RecipeCategory, UnitPreference } from './types';

export const COMPREHENSIVE_RECIPE_DATABASE: RecipeItem[] = [
  {
    id: 'recipe-salmon-sweet-potato',
    title: 'Sheet-Pan Wild Salmon & Herb Roasted Sweet Potato',
    description: 'Crispy wild Atlantic salmon filet paired with caramelized sweet potato wedges and tender garlic asparagus.',
    category: 'dinner',
    prep_time_minutes: 15,
    cook_time_minutes: 20,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['1-Pan', 'High-Protein', 'Omega-3s', 'Gluten-Free', '15-Min Prep'],
    calories_per_serving: 580,
    protein_g_per_serving: 46,
    carbs_g_per_serving: 48,
    fat_g_per_serving: 22,
    icon_emoji: '🐟',
    ingredients: [
      {
        food_id: 'salmon-wild',
        name: 'Wild Atlantic Salmon Filet',
        amount_imperial: '6 oz',
        amount_metric: '170g',
        raw_weight_grams_base: 170,
        department: 'meat_seafood',
        notes: 'Skin-on for crispy edges',
      },
      {
        food_id: 'sweet-potato',
        name: 'Diced Sweet Potato',
        amount_imperial: '1 medium (approx. 7 oz)',
        amount_metric: '200g',
        raw_weight_grams_base: 200,
        department: 'produce',
        notes: 'Cut into 1/2-inch cubes',
      },
      {
        food_id: 'asparagus',
        name: 'Fresh Asparagus Spears',
        amount_imperial: '1 cup (approx. 5 oz)',
        amount_metric: '140g',
        raw_weight_grams_base: 140,
        department: 'produce',
        notes: 'Tough woody ends trimmed',
      },
      {
        food_id: 'olive-oil',
        name: 'Extra Virgin Olive Oil',
        amount_imperial: '1 tablespoon',
        amount_metric: '15 ml',
        raw_weight_grams_base: 14,
        department: 'healthy_fats',
        notes: 'Divided between potatoes & salmon',
      },
      {
        name: 'Garlic Powder, Sea Salt & Smoked Paprika',
        amount_imperial: '1/2 teaspoon each',
        amount_metric: '1/2 tsp each',
        raw_weight_grams_base: 4,
        department: 'pantry_spices',
        notes: 'To taste',
      },
      {
        name: 'Fresh Lemon Wedges',
        amount_imperial: '2 wedges',
        amount_metric: '2 wedges',
        raw_weight_grams_base: 30,
        department: 'produce',
        notes: 'For finishing squeeze',
      },
    ],
    instructions: [
      'Preheat oven to 400°F (200°C) and line a large baking sheet with parchment paper.',
      'Toss the diced sweet potatoes in half of the olive oil, salt, garlic powder, and smoked paprika. Spread evenly on one side of the baking sheet and roast for 10 minutes.',
      'Remove sheet from oven, add the salmon filet (skin-side down) and trimmed asparagus to the other side. Drizzle remaining olive oil and seasonings over the salmon and asparagus.',
      'Return sheet pan to oven and roast for another 12-14 minutes, until salmon flakes easily with a fork and sweet potatoes are fork-tender.',
      'Finish with a generous squeeze of fresh lemon juice and serve immediately.',
    ],
    chef_notes: 'For extra crispy salmon skin, pat the filet completely dry with a paper towel before seasoning.',
  },
  {
    id: 'recipe-grilled-chicken-rice-bowl',
    title: 'Grilled Lemon Herb Chicken & Jasmine Rice Power Bowl',
    description: 'Tender marinated chicken breast sliced over fragrant steamed jasmine rice and crisp steamed broccoli florets.',
    category: 'lunch',
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['High-Protein', 'Clean Fuel', 'Meal Prep Favorite', 'Gluten-Free'],
    calories_per_serving: 520,
    protein_g_per_serving: 52,
    carbs_g_per_serving: 56,
    fat_g_per_serving: 10,
    icon_emoji: '🥗',
    ingredients: [
      {
        food_id: 'chicken-breast',
        name: 'Boneless Skinless Chicken Breast',
        amount_imperial: '7 oz',
        amount_metric: '200g',
        raw_weight_grams_base: 200,
        department: 'meat_seafood',
        notes: 'Trimmed and butterflied for fast cooking',
      },
      {
        food_id: 'jasmine-rice',
        name: 'Steamed Jasmine Rice (Cooked)',
        amount_imperial: '1 cup',
        amount_metric: '180g',
        raw_weight_grams_base: 75,
        department: 'grains_bakery',
        notes: 'White or brown jasmine rice',
      },
      {
        food_id: 'broccoli',
        name: 'Fresh Broccoli Florets',
        amount_imperial: '1.5 cups',
        amount_metric: '130g',
        raw_weight_grams_base: 130,
        department: 'produce',
        notes: 'Steamed tender-crisp',
      },
      {
        food_id: 'olive-oil',
        name: 'Extra Virgin Olive Oil',
        amount_imperial: '1/2 tablespoon',
        amount_metric: '7.5 ml',
        raw_weight_grams_base: 7,
        department: 'healthy_fats',
        notes: 'For skillet searing',
      },
      {
        name: 'Italian Herb Seasoning & Sea Salt',
        amount_imperial: '1 teaspoon',
        amount_metric: '1 tsp',
        raw_weight_grams_base: 3,
        department: 'pantry_spices',
        notes: 'Oregano, thyme, rosemary',
      },
    ],
    instructions: [
      'Season chicken breast thoroughly on both sides with Italian herbs, sea salt, black pepper, and garlic powder.',
      'Heat olive oil in a non-stick skillet or grill pan over medium-high heat.',
      'Sear chicken for 5-6 minutes per side until golden brown and internal temperature reaches 165°F (74°C). Rest for 3 minutes, then slice into strips.',
      'Steam broccoli florets in a small pot with 2 tbsp of water for 4 minutes until bright green and crisp.',
      'Assemble bowl: Add warm jasmine rice, top with sliced chicken breast and steamed broccoli. Drizzle with pan juices.',
    ],
    chef_notes: 'Cook 4x portions on Sunday for 4 days of grab-and-go athletic lunches.',
  },
  {
    id: 'recipe-berry-chia-oatmeal',
    title: 'Berry Chia Protein Power Oatmeal',
    description: 'Hearty rolled oats simmered with chia seeds, topped with fresh blueberries, sliced strawberries, and whey protein.',
    category: 'breakfast',
    prep_time_minutes: 5,
    cook_time_minutes: 5,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['Quick 10-Min', 'High-Fiber', 'Pre-Workout Fuel', 'Heart-Healthy'],
    calories_per_serving: 420,
    protein_g_per_serving: 34,
    carbs_g_per_serving: 58,
    fat_g_per_serving: 8,
    icon_emoji: '🥣',
    ingredients: [
      {
        food_id: 'rolled-oats',
        name: 'Old Fashioned Rolled Oats',
        amount_imperial: '1/2 cup (approx. 1.7 oz)',
        amount_metric: '50g',
        raw_weight_grams_base: 50,
        department: 'grains_bakery',
        notes: 'Gluten-free certified if desired',
      },
      {
        food_id: 'whey-protein',
        name: 'Vanilla Whey / Plant Protein Powder',
        amount_imperial: '1 scoop (approx. 1 oz)',
        amount_metric: '30g',
        raw_weight_grams_base: 30,
        department: 'supplements',
        notes: 'Stirred in at the end',
      },
      {
        food_id: 'blueberries',
        name: 'Fresh Blueberries',
        amount_imperial: '1/2 cup',
        amount_metric: '75g',
        raw_weight_grams_base: 75,
        department: 'produce',
        notes: 'Or fresh strawberries',
      },
      {
        food_id: 'chia-seeds',
        name: 'Chia Seeds',
        amount_imperial: '1 tablespoon',
        amount_metric: '12g',
        raw_weight_grams_base: 12,
        department: 'healthy_fats',
        notes: 'For healthy omega-3 fats and fiber',
      },
      {
        food_id: 'almond-milk',
        name: 'Unsweetened Almond Milk or Water',
        amount_imperial: '1 cup',
        amount_metric: '240 ml',
        raw_weight_grams_base: 240,
        department: 'dairy_eggs',
        notes: 'For cooking oats',
      },
      {
        name: 'Ground Cinnamon',
        amount_imperial: '1/2 teaspoon',
        amount_metric: '1/2 tsp',
        raw_weight_grams_base: 2,
        department: 'pantry_spices',
        notes: 'For warmth and natural sweetness',
      },
    ],
    instructions: [
      'In a small saucepan, combine rolled oats, chia seeds, cinnamon, and almond milk (or water).',
      'Bring to a gentle simmer over medium heat and cook for 4-5 minutes, stirring occasionally until thick and creamy.',
      'Remove saucepan from heat and allow to cool for 1 minute (prevents protein powder from clumping).',
      'Stir in the vanilla protein powder until completely smooth and velvety.',
      'Pour into a bowl and top with fresh blueberries and sliced strawberries.',
    ],
    chef_notes: 'Do not boil protein powder directly on high heat; always stir it in once oats are off the flame.',
  },
  {
    id: 'recipe-beef-bell-pepper-skillet',
    title: 'Lean Grass-Fed Beef & Bell Pepper Fajita Skillet',
    description: 'Sizzling lean ground beef sautéed with vibrant red and yellow bell peppers, red onions, and warm fajita spices.',
    category: 'dinner',
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['1-Pan', 'High-Protein', 'Iron-Rich', 'Keto/Low-Carb Friendly'],
    calories_per_serving: 490,
    protein_g_per_serving: 48,
    carbs_g_per_serving: 18,
    fat_g_per_serving: 24,
    icon_emoji: '🥩',
    ingredients: [
      {
        food_id: 'ground-beef-93',
        name: '93/7 Lean Ground Beef',
        amount_imperial: '7 oz',
        amount_metric: '200g',
        raw_weight_grams_base: 200,
        department: 'meat_seafood',
        notes: 'Or extra-lean ground turkey',
      },
      {
        food_id: 'bell-peppers',
        name: 'Bell Peppers (Red & Yellow)',
        amount_imperial: '1.5 cups sliced',
        amount_metric: '150g',
        raw_weight_grams_base: 150,
        department: 'produce',
        notes: 'Cut into strips',
      },
      {
        name: 'Red Onion',
        amount_imperial: '1/2 cup sliced',
        amount_metric: '60g',
        raw_weight_grams_base: 60,
        department: 'produce',
        notes: 'Thinly sliced',
      },
      {
        food_id: 'olive-oil',
        name: 'Olive Oil',
        amount_imperial: '1/2 tablespoon',
        amount_metric: '7.5 ml',
        raw_weight_grams_base: 7,
        department: 'healthy_fats',
        notes: 'For sautéing peppers',
      },
      {
        name: 'Ground Cumin, Chili Powder, Garlic & Sea Salt',
        amount_imperial: '1.5 teaspoons total',
        amount_metric: '1.5 tsp',
        raw_weight_grams_base: 5,
        department: 'pantry_spices',
        notes: 'Fajita spice blend',
      },
      {
        food_id: 'avocado',
        name: 'Fresh Avocado Slices',
        amount_imperial: '1/4 whole avocado (approx. 1.5 oz)',
        amount_metric: '40g',
        raw_weight_grams_base: 40,
        department: 'produce',
        notes: 'Garnish',
      },
    ],
    instructions: [
      'Heat a large skillet or cast iron pan over medium-high heat with olive oil.',
      'Add sliced bell peppers and red onions. Sauté for 5-6 minutes until slightly blistered and tender-crisp. Transfer vegetables to a side plate.',
      'In the same hot skillet, add the lean ground beef. Break apart with a wooden spoon and brown for 6-8 minutes.',
      'Add cumin, chili powder, garlic, sea salt, and black pepper. Stir well to coat the beef in spices.',
      'Return the peppers and onions back to the skillet and toss everything together for 1 minute.',
      'Serve warm topped with fresh avocado slices and a squeeze of lime.',
    ],
    chef_notes: 'Serve as a low-carb bowl, or wrap in warm corn tortillas for a higher carb refuel day.',
  },
  {
    id: 'recipe-greek-yogurt-crunch-bowl',
    title: 'Greek Yogurt Crunch Bowl with Berries & Walnuts',
    description: 'Thick non-fat Greek yogurt layered with fresh strawberries, blueberries, raw honey, and crunchy walnuts.',
    category: 'snack_dessert',
    prep_time_minutes: 3,
    cook_time_minutes: 0,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['No-Cook', 'Quick 3-Min', 'High-Protein', 'Probiotic-Rich'],
    calories_per_serving: 310,
    protein_g_per_serving: 28,
    carbs_g_per_serving: 28,
    fat_g_per_serving: 10,
    icon_emoji: '🍓',
    ingredients: [
      {
        food_id: 'greek-yogurt-0',
        name: 'Plain 0% Non-Fat Greek Yogurt',
        amount_imperial: '1 cup (approx. 8 oz)',
        amount_metric: '225g',
        raw_weight_grams_base: 225,
        department: 'dairy_eggs',
        notes: 'High-protein strained yogurt',
      },
      {
        food_id: 'strawberries',
        name: 'Sliced Fresh Strawberries',
        amount_imperial: '1/2 cup',
        amount_metric: '75g',
        raw_weight_grams_base: 75,
        department: 'produce',
        notes: 'Freshly sliced',
      },
      {
        food_id: 'blueberries',
        name: 'Fresh Blueberries',
        amount_imperial: '1/4 cup',
        amount_metric: '40g',
        raw_weight_grams_base: 40,
        department: 'produce',
        notes: 'Washed and dried',
      },
      {
        food_id: 'walnuts',
        name: 'Raw Walnuts (Crushed)',
        amount_imperial: '1 tablespoon (approx. 0.5 oz)',
        amount_metric: '14g',
        raw_weight_grams_base: 14,
        department: 'healthy_fats',
        notes: 'Crushed for crunch',
      },
      {
        name: 'Pure Honey or Pure Maple Syrup',
        amount_imperial: '1 teaspoon',
        amount_metric: '5 ml',
        raw_weight_grams_base: 7,
        department: 'pantry_spices',
        notes: 'Light natural drizzle',
      },
    ],
    instructions: [
      'Spoon plain Greek yogurt into a chilled bowl.',
      'Arrange sliced strawberries and blueberries across the top.',
      'Sprinkle crushed raw walnuts evenly over the fruit.',
      'Drizzle with 1 tsp of honey and enjoy immediately.',
    ],
    chef_notes: 'Perfect fast breakfast or evening post-dinner snack rich in slow-digesting casein protein.',
  },
  {
    id: 'recipe-avocado-toast-eggs',
    title: 'Artisan Avocado Toast with Soft-Boiled Eggs',
    description: 'Toasted sourdough or sprouted bread topped with mashed avocado, soft-boiled pasture-raised eggs, and red pepper flakes.',
    category: 'breakfast',
    prep_time_minutes: 5,
    cook_time_minutes: 7,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['Quick 12-Min', 'Healthy Fats', 'Vegetarian', 'Choline-Rich'],
    calories_per_serving: 440,
    protein_g_per_serving: 22,
    carbs_g_per_serving: 36,
    fat_g_per_serving: 24,
    icon_emoji: '🥑',
    ingredients: [
      {
        food_id: 'sourdough-bread',
        name: 'Sprouted Grain or Sourdough Bread',
        amount_imperial: '2 slices (approx. 2.5 oz)',
        amount_metric: '70g',
        raw_weight_grams_base: 70,
        department: 'grains_bakery',
        notes: 'Toasted golden and crisp',
      },
      {
        food_id: 'eggs-whole',
        name: 'Whole Pasture-Raised Eggs',
        amount_imperial: '2 large eggs',
        amount_metric: '2 large eggs',
        raw_weight_grams_base: 100,
        department: 'dairy_eggs',
        notes: 'Soft-boiled or sunny-side up',
      },
      {
        food_id: 'avocado',
        name: 'Ripe Avocado',
        amount_imperial: '1/2 whole avocado (approx. 3 oz)',
        amount_metric: '80g',
        raw_weight_grams_base: 80,
        department: 'produce',
        notes: 'Mashed with fork',
      },
      {
        name: 'Lemon Juice, Flaky Sea Salt & Red Pepper Flakes',
        amount_imperial: '1/2 teaspoon each',
        amount_metric: '1/2 tsp each',
        raw_weight_grams_base: 3,
        department: 'pantry_spices',
        notes: 'To taste',
      },
    ],
    instructions: [
      'Bring a small pot of water to a gentle boil. Lower the 2 cold eggs into the water and boil for exactly 6.5 minutes for jammy soft yolks (or 8 minutes for firm yolks).',
      'Transfer eggs immediately to an ice bath for 3 minutes, then gently peel.',
      'Toast the 2 bread slices until golden brown and sturdy.',
      'In a small bowl, mash the avocado with a squeeze of fresh lemon juice, sea salt, and black pepper.',
      'Spread mashed avocado generously over warm toast. Slice eggs in half and place on top.',
      'Garnish with flaky sea salt and crushed red pepper flakes.',
    ],
    chef_notes: 'Ice bath makes peeling soft-boiled eggs effortless without tearing the whites.',
  },
  {
    id: 'recipe-air-fryer-turkey-meatballs',
    title: 'Air-Fryer Crispy Turkey Meatballs with Marinara',
    description: 'Juicy Italian-seasoned lean turkey meatballs air-fried until golden, served with warm marinara and steamed zucchini noodles.',
    category: 'dinner',
    prep_time_minutes: 15,
    cook_time_minutes: 12,
    servings_yield: 2,
    difficulty: 'easy',
    tags: ['Air-Fryer', 'High-Protein', 'Low-Carb Option', 'Meal Prep Ready'],
    calories_per_serving: 420,
    protein_g_per_serving: 44,
    carbs_g_per_serving: 18,
    fat_g_per_serving: 16,
    icon_emoji: '🧆',
    ingredients: [
      {
        food_id: 'ground-turkey-93',
        name: '93% Lean Ground Turkey',
        amount_imperial: '14 oz (approx. 0.9 lb)',
        amount_metric: '400g',
        raw_weight_grams_base: 400,
        department: 'meat_seafood',
        notes: 'Yields ~10-12 meatballs',
      },
      {
        food_id: 'eggs-whole',
        name: 'Whole Egg',
        amount_imperial: '1 large egg',
        amount_metric: '1 large egg',
        raw_weight_grams_base: 50,
        department: 'dairy_eggs',
        notes: 'Binder',
      },
      {
        name: 'Almond Flour or Breadcrumbs',
        amount_imperial: '1/4 cup',
        amount_metric: '28g',
        raw_weight_grams_base: 28,
        department: 'grains_bakery',
        notes: 'For texture and moisture',
      },
      {
        name: 'Grated Parmesan Cheese',
        amount_imperial: '2 tablespoons',
        amount_metric: '15g',
        raw_weight_grams_base: 15,
        department: 'dairy_eggs',
        notes: 'For savory umami',
      },
      {
        food_id: 'marinara-sauce',
        name: 'No-Sugar-Added Marinara Sauce',
        amount_imperial: '1 cup (approx. 8 oz)',
        amount_metric: '240g',
        raw_weight_grams_base: 240,
        department: 'pantry_spices',
        notes: 'Warmed for serving',
      },
      {
        food_id: 'zucchini',
        name: 'Fresh Zucchini Noodles (Zoodles)',
        amount_imperial: '3 cups spiralized',
        amount_metric: '300g',
        raw_weight_grams_base: 300,
        department: 'produce',
        notes: 'Lightly sautéed or raw',
      },
    ],
    instructions: [
      'In a bowl, combine ground turkey, egg, almond flour (or breadcrumbs), parmesan, Italian seasoning, garlic powder, salt, and pepper.',
      'Gently mix until combined (do not overwork meat). Shape into 10-12 uniform golf-ball sized meatballs.',
      'Preheat air fryer to 380°F (195°C). Lightly spray basket with olive oil spray.',
      'Place meatballs in air fryer basket in a single layer with space between each. Air fry for 10-12 minutes, shaking basket at the 6-minute mark, until internal temp reaches 165°F.',
      'Warm marinara sauce in a small pot. Sauté zucchini noodles for 2 minutes in a pan.',
      'Plate zucchini noodles, top with crispy meatballs, and ladle warm marinara sauce over top.',
    ],
    chef_notes: 'Meatballs freeze wonderfully for up to 3 months; reheat in air fryer in just 5 minutes.',
  },
  {
    id: 'recipe-overnight-protein-oats',
    title: 'Overnight High-Protein Rolled Oats with Chia & Vanilla',
    description: 'Grab-and-go breakfast prepared the night before in a mason jar with rolled oats, vanilla whey, chia seeds, and almond milk.',
    category: 'bulk_meal_prep',
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['No-Cook', 'Meal Prep Essential', 'Grab & Go', 'High-Fiber'],
    calories_per_serving: 390,
    protein_g_per_serving: 35,
    carbs_g_per_serving: 46,
    fat_g_per_serving: 7,
    icon_emoji: '🫙',
    ingredients: [
      {
        food_id: 'rolled-oats',
        name: 'Rolled Oats',
        amount_imperial: '1/2 cup (approx. 1.7 oz)',
        amount_metric: '50g',
        raw_weight_grams_base: 50,
        department: 'grains_bakery',
      },
      {
        food_id: 'whey-protein',
        name: 'Vanilla Protein Powder',
        amount_imperial: '1 scoop',
        amount_metric: '30g',
        raw_weight_grams_base: 30,
        department: 'supplements',
      },
      {
        food_id: 'chia-seeds',
        name: 'Chia Seeds',
        amount_imperial: '1 tablespoon',
        amount_metric: '12g',
        raw_weight_grams_base: 12,
        department: 'healthy_fats',
      },
      {
        food_id: 'almond-milk',
        name: 'Unsweetened Almond Milk',
        amount_imperial: '3/4 cup',
        amount_metric: '180 ml',
        raw_weight_grams_base: 180,
        department: 'dairy_eggs',
      },
      {
        food_id: 'greek-yogurt-0',
        name: '0% Greek Yogurt',
        amount_imperial: '2 tablespoons (approx. 1.5 oz)',
        amount_metric: '40g',
        raw_weight_grams_base: 40,
        department: 'dairy_eggs',
        notes: 'Creates extra creamy texture',
      },
    ],
    instructions: [
      'In a 16 oz mason jar or airtight glass container, add rolled oats, chia seeds, and protein powder.',
      'Pour in the almond milk and Greek yogurt. Stir vigorously with a spoon until all protein powder is completely dissolved and no dry clumps remain.',
      'Seal jar with lid and refrigerate overnight (or for at least 4 hours).',
      'In the morning, give it a quick stir and top with a few fresh berries before eating cold.',
    ],
    chef_notes: 'Prep 4 jars on Sunday night to have breakfast ready Monday through Thursday.',
  },
  {
    id: 'recipe-tuna-avocado-salad-bowl',
    title: 'Mediterranean Tuna, Avocado & Cucumber Salad Bowl',
    description: 'Wild albacore tuna tossed with crisp cucumbers, diced ripe avocado, kalamata olives, lemon juice, and olive oil.',
    category: 'lunch',
    prep_time_minutes: 8,
    cook_time_minutes: 0,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['No-Cook', 'Quick 8-Min', 'High-Protein', 'Low-Carb', 'Omega-3s'],
    calories_per_serving: 410,
    protein_g_per_serving: 42,
    carbs_g_per_serving: 12,
    fat_g_per_serving: 22,
    icon_emoji: '🥗',
    ingredients: [
      {
        food_id: 'canned-tuna',
        name: 'Wild Albacore Tuna in Water (Drained)',
        amount_imperial: '1 can (approx. 5 oz)',
        amount_metric: '140g',
        raw_weight_grams_base: 140,
        department: 'meat_seafood',
        notes: 'Sustainably caught',
      },
      {
        food_id: 'avocado',
        name: 'Ripe Avocado (Diced)',
        amount_imperial: '1/2 whole avocado (approx. 3 oz)',
        amount_metric: '80g',
        raw_weight_grams_base: 80,
        department: 'produce',
      },
      {
        food_id: 'cucumber',
        name: 'Diced English Cucumber',
        amount_imperial: '1 cup',
        amount_metric: '120g',
        raw_weight_grams_base: 120,
        department: 'produce',
      },
      {
        name: 'Kalamata Olives (Pitted & Halved)',
        amount_imperial: '6 olives (approx. 1 oz)',
        amount_metric: '25g',
        raw_weight_grams_base: 25,
        department: 'pantry_spices',
      },
      {
        food_id: 'olive-oil',
        name: 'Extra Virgin Olive Oil',
        amount_imperial: '1/2 tablespoon',
        amount_metric: '7.5 ml',
        raw_weight_grams_base: 7,
        department: 'healthy_fats',
      },
      {
        name: 'Fresh Lemon Juice & Dried Oregano',
        amount_imperial: '1 tablespoon juice + 1/2 tsp oregano',
        amount_metric: '15 ml + 1/2 tsp',
        raw_weight_grams_base: 15,
        department: 'pantry_spices',
      },
    ],
    instructions: [
      'Drain the canned tuna thoroughly and place in a salad bowl.',
      'Flake the tuna with a fork into bite-sized chunks.',
      'Add the diced cucumber, diced avocado, and halved kalamata olives.',
      'Drizzle with olive oil and fresh lemon juice. Season with dried oregano, sea salt, and freshly cracked black pepper.',
      'Toss gently so the avocado stays intact and serve chilled.',
    ],
    chef_notes: 'Zero cooking required. Packed with lean protein, healthy heart fats, and crisp hydration.',
  },
  {
    id: 'recipe-slow-cooker-chicken-salsa',
    title: 'Slow-Cooker Shredded Salsa Verde Chicken',
    description: 'Tender, juicy chicken breasts slow-cooked with tomatillo salsa verde and cumin, shredded for multi-day meal prep.',
    category: 'bulk_meal_prep',
    prep_time_minutes: 5,
    cook_time_minutes: 240,
    servings_yield: 4,
    difficulty: 'easy',
    tags: ['Slow-Cooker', 'Batch Meal Prep', '4 Servings', 'Ultra High-Protein'],
    calories_per_serving: 360,
    protein_g_per_serving: 55,
    carbs_g_per_serving: 8,
    fat_g_per_serving: 8,
    icon_emoji: '🍲',
    ingredients: [
      {
        food_id: 'chicken-breast',
        name: 'Boneless Skinless Chicken Breasts',
        amount_imperial: '2 lbs (approx. 32 oz)',
        amount_metric: '900g',
        raw_weight_grams_base: 900,
        department: 'meat_seafood',
        notes: 'Yields 4 large athletic portions',
      },
      {
        name: 'Tomatillo Salsa Verde (Jar)',
        amount_imperial: '1 jar (approx. 16 oz)',
        amount_metric: '450g',
        raw_weight_grams_base: 450,
        department: 'pantry_spices',
        notes: 'Medium or mild heat',
      },
      {
        name: 'Ground Cumin & Garlic Powder',
        amount_imperial: '1 teaspoon each',
        amount_metric: '1 tsp each',
        raw_weight_grams_base: 6,
        department: 'pantry_spices',
      },
      {
        name: 'Fresh Cilantro & Lime',
        amount_imperial: '1/4 cup chopped + 1 lime',
        amount_metric: '15g + 1 lime',
        raw_weight_grams_base: 50,
        department: 'produce',
        notes: 'For finishing garnish',
      },
    ],
    instructions: [
      'Place whole raw chicken breasts into the bottom of a slow cooker (Crock-Pot) or Instant Pot.',
      'Sprinkle cumin, garlic powder, and a pinch of salt over the chicken.',
      'Pour the entire jar of salsa verde over the chicken, making sure all pieces are submerged.',
      'Cover and cook on LOW for 6-7 hours or on HIGH for 3.5-4 hours (or Instant Pot Manual High for 14 minutes).',
      'Remove lid and use two forks to shred the chicken directly in the hot juices.',
      'Stir in chopped cilantro and fresh lime juice. Divide into 4 glass meal prep containers.',
    ],
    chef_notes: 'Pairs perfectly over brown rice, black beans, roasted peppers, or mixed salad greens.',
  },
  {
    id: 'recipe-flank-steak-asparagus',
    title: 'Cast-Iron Garlic Herb Flank Steak with Asparagus',
    description: 'Seared lean flank steak basted in garlic and rosemary, sliced thin against the grain with roasted asparagus.',
    category: 'dinner',
    prep_time_minutes: 10,
    cook_time_minutes: 12,
    servings_yield: 1,
    difficulty: 'moderate',
    tags: ['Cast-Iron', 'High-Protein', 'Iron & Zinc', 'Gluten-Free'],
    calories_per_serving: 540,
    protein_g_per_serving: 56,
    carbs_g_per_serving: 12,
    fat_g_per_serving: 28,
    icon_emoji: '🥩',
    ingredients: [
      {
        food_id: 'flank-steak',
        name: 'Lean Flank Steak',
        amount_imperial: '8 oz',
        amount_metric: '225g',
        raw_weight_grams_base: 225,
        department: 'meat_seafood',
        notes: 'Brought to room temp before cooking',
      },
      {
        food_id: 'asparagus',
        name: 'Fresh Asparagus',
        amount_imperial: '1.5 cups (approx. 6 oz)',
        amount_metric: '170g',
        raw_weight_grams_base: 170,
        department: 'produce',
        notes: 'Trimmed',
      },
      {
        food_id: 'olive-oil',
        name: 'Extra Virgin Olive Oil',
        amount_imperial: '1 tablespoon',
        amount_metric: '15 ml',
        raw_weight_grams_base: 14,
        department: 'healthy_fats',
      },
      {
        name: 'Fresh Garlic (Minced) & Rosemary',
        amount_imperial: '2 cloves + 1 sprig',
        amount_metric: '2 cloves + 1 sprig',
        raw_weight_grams_base: 10,
        department: 'produce',
      },
    ],
    instructions: [
      'Pat flank steak dry with paper towels. Season generously on both sides with kosher salt and coarse black pepper.',
      'Heat a heavy cast iron skillet over high heat until lightly smoking. Add olive oil.',
      'Lay steak into the skillet and sear for 4-5 minutes without moving until a deep caramelized crust forms.',
      'Flip steak, add minced garlic and rosemary sprig to the skillet, and cook for another 3-4 minutes for medium-rare (internal temp 130°F).',
      'Transfer steak to a cutting board and let rest for 5-7 minutes.',
      'Toss asparagus directly into the hot skillet with remaining garlic oil and sauté for 4 minutes.',
      'Slice steak thinly AGAINST the grain at a 45-degree angle. Plate with asparagus.',
    ],
    chef_notes: 'Slicing thinly across/against the grain is the essential secret to exceptionally tender flank steak.',
  },
  {
    id: 'recipe-anabolic-protein-fluff',
    title: 'Anabolic Post-Workout Berry Protein Fluff',
    description: 'High-volume frozen dessert whipped with whey isolate, frozen berries, and almond milk into an ice-cream like texture.',
    category: 'snack_dessert',
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    servings_yield: 1,
    difficulty: 'easy',
    tags: ['Post-Workout', 'High-Volume', 'Under 250 kcal', 'Craving Crusher'],
    calories_per_serving: 230,
    protein_g_per_serving: 32,
    carbs_g_per_serving: 22,
    fat_g_per_serving: 2,
    icon_emoji: '🍨',
    ingredients: [
      {
        food_id: 'whey-protein',
        name: 'Vanilla or Strawberry Whey Isolate',
        amount_imperial: '1 scoop (approx. 1.1 oz)',
        amount_metric: '32g',
        raw_weight_grams_base: 32,
        department: 'supplements',
      },
      {
        food_id: 'strawberries',
        name: 'Frozen Strawberries or Mixed Berries',
        amount_imperial: '1 cup frozen (approx. 5 oz)',
        amount_metric: '140g',
        raw_weight_grams_base: 140,
        department: 'frozen',
      },
      {
        food_id: 'almond-milk',
        name: 'Unsweetened Almond Milk',
        amount_imperial: '1/3 cup (splash)',
        amount_metric: '80 ml',
        raw_weight_grams_base: 80,
        department: 'dairy_eggs',
        notes: 'Keep minimal for thick texture',
      },
      {
        name: 'Xanthan Gum (Optional for extra fluff volume)',
        amount_imperial: '1/4 teaspoon',
        amount_metric: '1g',
        raw_weight_grams_base: 1,
        department: 'pantry_spices',
        notes: 'Whips volume up 3x',
      },
    ],
    instructions: [
      'In a high-powered blender or food processor, pulse frozen berries and almond milk until broken down into a fine slush.',
      'Add protein powder and xanthan gum.',
      'Blend on high speed with tamper or food processor blade for 2-3 minutes until volume doubles into thick, fluffy soft-serve ice cream.',
      'Spoon into a large chilled bowl and enjoy immediately with a spoon.',
    ],
    chef_notes: 'Massive volume that satisfies sweet tooth cravings while delivering over 30g of fast-absorbing post-workout protein.',
  },
];
