import { MasterScheduleTemplate } from './types';

export const MASTER_SCHEDULE_TEMPLATES: MasterScheduleTemplate[] = [
  {
    id: 'template_5x5_concept2_hybrid',
    title: 'StrongLifts 5×5 & Concept2® Rowing Hybrid Master Protocol',
    subtitle: 'Periodized Barbell Strength, High-Wattage Erg Conditioning & 16:8 Fasting',
    description:
      'The premier all-around athletic roadmap combining 3 heavy compound 5×5 barbell lifting sessions per week, 2 high-performance Concept2 indoor rowing engine sessions, designated batch prep/grocery milestones, and circadian nutrient timing.',
    icon: '⚡',
    accent_color: '#3b82f6',
    recommended_duration_weeks: 12,
    weekly_rhythm: [
      {
        day_of_week: 1,
        day_label: 'Monday',
        workout_title: '5×5 Workout A (Squat, Bench Press, Barbell Row)',
        workout_category: 'strength_5x5',
        program_id: 'stronglifts_5x5_classic',
        exercises: [
          { id: '5x5-sq-1', name: 'Barbell Back Squat', target_muscle: 'quads', suggested_sets: 5, suggested_reps: '5 reps', instructions: 'Hip crease below knee, explosive drive.' },
          { id: '5x5-bp-1', name: 'Barbell Flat Bench Press', target_muscle: 'chest', suggested_sets: 5, suggested_reps: '5 reps', instructions: 'Retract scapulae, touch sternum, lock out.' },
          { id: '5x5-br-1', name: 'Barbell Bent-Over Row', target_muscle: 'back', suggested_sets: 5, suggested_reps: '5 reps', instructions: 'Pull bar to lower ribs from dead stop.' },
        ],
        target_steps: 10000,
        calorie_offset: 250,
        carb_focus: 'high',
        fasting_protocol: '16_8',
        water_goal_oz: 120,
        planned_meal_names: ['Oatmeal & Wild Blueberries Bowl', 'Seared Chicken & Jasmine Rice Bowl', 'Wild Salmon with Roasted Sweet Potatoes'],
        is_grocery_day: false,
        is_batch_prep_day: false,
        notes: 'Heavy training day: Fuel with complex carbs and hydrate aggressively before squatting.',
      },
      {
        day_of_week: 2,
        day_label: 'Tuesday',
        workout_title: 'Concept2® Pete Plan: 8 × 500m Interval Sprints',
        workout_category: 'concept2_rowing',
        program_id: 'concept2_pete_plan',
        exercises: [
          { id: 'c2-pp-1', name: 'Concept2 Rower: 8 × 500m Sprints (3:30 Rest)', target_muscle: 'full_body_cardio', suggested_sets: 8, suggested_reps: '500m @ 2K Pace', instructions: 'Stroke rate 28–32 SPM. Maintain consistent wattage across all 8 rounds.' },
          { id: 'c2-pp-cd', name: 'Cool Down Paddle & Posterior Chain Stretch', target_muscle: 'mobility', suggested_sets: 1, suggested_reps: '1,000m light', instructions: 'Flush lactate and restore resting heart rate.' },
        ],
        target_steps: 11000,
        calorie_offset: 0,
        carb_focus: 'moderate',
        fasting_protocol: '16_8',
        water_goal_oz: 120,
        planned_meal_names: ['Greek Yogurt Berry Parfait', 'Turkey & Avocado Quinoa Salad', 'Grass-Fed Ground Beef & Brown Rice Bowl'],
        is_grocery_day: false,
        is_batch_prep_day: false,
        notes: 'High-intensity anaerobic threshold day. Focus on quick catch and full leg extension.',
      },
      {
        day_of_week: 3,
        day_label: 'Wednesday',
        workout_title: '5×5 Workout B (Squat, Overhead Press, Deadlift)',
        workout_category: 'strength_5x5',
        program_id: 'stronglifts_5x5_classic',
        exercises: [
          { id: '5x5-sq-2', name: 'Barbell Back Squat', target_muscle: 'quads', suggested_sets: 5, suggested_reps: '5 reps', instructions: 'Deep squat with tight core brace.' },
          { id: '5x5-ohp-1', name: 'Barbell Standing Overhead Press', target_muscle: 'shoulders', suggested_sets: 5, suggested_reps: '5 reps', instructions: 'Press directly vertical, squeeze glutes.' },
          { id: '5x5-dl-1', name: 'Barbell Conventional Deadlift', target_muscle: 'hamstrings', suggested_sets: 1, suggested_reps: '5 reps (Heavy Working Set)', instructions: 'Chest up, drive floor away with heels.' },
        ],
        target_steps: 10000,
        calorie_offset: 250,
        carb_focus: 'high',
        fasting_protocol: '16_8',
        water_goal_oz: 120,
        planned_meal_names: ['Scrambled Eggs on Ezekiel Toast', 'Chipotle Chicken & Rice Bowl', 'Sirloin Steak with Baked Potato & Asparagus'],
        is_grocery_day: false,
        is_batch_prep_day: false,
        notes: 'Deadlift day: Squeeze lats tight and ensure neutral spine throughout.',
      },
      {
        day_of_week: 4,
        day_label: 'Thursday',
        workout_title: 'Concept2® Aerobic Base: 10,000m Steady State Row',
        workout_category: 'concept2_rowing',
        program_id: 'concept2_2k_peaking_protocol',
        exercises: [
          { id: 'c2-10k-1', name: 'Concept2 Rower: 10,000m Continuous Zone 2 Row', target_muscle: 'full_body_cardio', suggested_sets: 1, suggested_reps: '10,000m @ 18–20 SPM', instructions: 'Maintain 65–75% HRmax. Smooth power curve and patient recovery slide.' },
          { id: 'c2-10k-foam', name: 'Full-Body Foam Rolling & Thoracic Opener', target_muscle: 'mobility', suggested_sets: 1, suggested_reps: '8 minutes', instructions: 'Decompress spine, foam roll lats, glutes, and hamstrings.' },
        ],
        target_steps: 12000,
        calorie_offset: 0,
        carb_focus: 'moderate',
        fasting_protocol: '16_8',
        water_goal_oz: 120,
        planned_meal_names: ['Protein Smoothie Bowl with Chia Seeds', 'Chicken Breast Salad with Olive Oil', 'Baked Cod with Quinoa & Steamed Broccoli'],
        is_grocery_day: false,
        is_batch_prep_day: false,
        notes: 'Mitochondrial aerobic capacity builder. Keep stroke rate strictly at 18–20 SPM.',
      },
      {
        day_of_week: 5,
        day_label: 'Friday',
        workout_title: '5×5 Workout A (Squat, Bench Press, Barbell Row)',
        workout_category: 'strength_5x5',
        program_id: 'stronglifts_5x5_classic',
        exercises: [
          { id: '5x5-sq-3', name: 'Barbell Back Squat', target_muscle: 'quads', suggested_sets: 5, suggested_reps: '5 reps', instructions: 'Maintain upright torso, drive out of bottom.' },
          { id: '5x5-bp-2', name: 'Barbell Flat Bench Press', target_muscle: 'chest', suggested_sets: 5, suggested_reps: '5 reps', instructions: 'Elbows tucked at 45° angle, full lockout.' },
          { id: '5x5-br-2', name: 'Barbell Bent-Over Row', target_muscle: 'back', suggested_sets: 5, suggested_reps: '5 reps', instructions: 'Strict torso angle, pull with lats.' },
        ],
        target_steps: 10000,
        calorie_offset: 250,
        carb_focus: 'high',
        fasting_protocol: '16_8',
        water_goal_oz: 120,
        planned_meal_names: ['Berry Protein Oatmeal', 'Grilled Chicken Caesar Salad Bowl', 'Bison Burger with Sweet Potato Wedges'],
        is_grocery_day: false,
        is_batch_prep_day: false,
        notes: 'End of week compound strength. Track weight progression on all three lifts.',
      },
      {
        day_of_week: 6,
        day_label: 'Saturday',
        workout_title: 'Joint Mobility, CARs & Weekly Batch Meal Prep',
        workout_category: 'mobility',
        program_id: 'functional_joint_mobility_decompression',
        exercises: [
          { id: 'mob-sat-1', name: 'Controlled Articular Rotations (CARs Flow)', target_muscle: 'mobility', suggested_sets: 3, suggested_reps: '10 mins', instructions: 'Neck, shoulder, hip, and ankle full-range circular articulations.' },
          { id: 'mob-sat-2', name: '90/90 Hip Internal & External Rotations', target_muscle: 'mobility', suggested_sets: 3, suggested_reps: '90s per side', instructions: 'Sink into posterior capsule with tall spine.' },
        ],
        target_steps: 10000,
        calorie_offset: -100,
        carb_focus: 'moderate',
        fasting_protocol: '14_10',
        water_goal_oz: 100,
        planned_meal_names: ['Avocado Omelet with Sourdough', 'Meal Prep Batch Bowl (Chicken & Sweet Potato)', 'Salmon Fillet with Mixed Greens'],
        is_grocery_day: false,
        is_batch_prep_day: true,
        notes: 'Batch cooking day: Cook chicken breasts, rice, and sweet potatoes for the upcoming week.',
      },
      {
        day_of_week: 7,
        day_label: 'Sunday',
        workout_title: 'Full Digestive Rest, Nature Walk & Grocery Requisition',
        workout_category: 'rest',
        program_id: 'vinyasa_yoga_active_recovery',
        exercises: [
          { id: 'rest-sun-1', name: 'Gentle 45-Minute Nature Walk', target_muscle: 'full_body_cardio', suggested_sets: 1, suggested_reps: '45 minutes', instructions: 'Comfortable conversation pace, fresh air.' },
          { id: 'rest-sun-2', name: 'Vinyasa Savasana Rest & Down-Regulation', target_muscle: 'mobility', suggested_sets: 1, suggested_reps: '10 minutes', instructions: 'Deep diaphragmatic breathing.' },
        ],
        target_steps: 8000,
        calorie_offset: -200,
        carb_focus: 'low',
        fasting_protocol: '16_8',
        water_goal_oz: 96,
        planned_meal_names: ['Scrambled Eggs with Spinach & Mushrooms', 'Light Tuna Salad Wrap', 'Herb Roasted Chicken Thighs with Steamed Asparagus'],
        is_grocery_day: true,
        is_batch_prep_day: false,
        notes: 'Grocery shopping day: Generate your smart list and restock fridge with fresh produce and lean proteins.',
      },
    ],
  },
  {
    id: 'template_hypertrophy_ppl',
    title: 'Hypertrophy Push/Pull/Legs & Batch Prep Master System',
    subtitle: '6-Day Muscle Growth Split with Calorie Cycling & Precision Fuel',
    description:
      'High-volume hypertrophy system organizing Push, Pull, and Leg workouts with programmed refeed days, weekly meal batching, and active rowing recovery.',
    icon: '💪',
    accent_color: '#8b5cf6',
    recommended_duration_weeks: 12,
    weekly_rhythm: [
      {
        day_of_week: 1,
        day_label: 'Monday',
        workout_title: 'Push Power (Chest, Front Delts, Triceps)',
        workout_category: 'bodybuilding',
        exercises: [
          { id: 'ppl-p-1', name: 'Dumbbell Incline Bench Press', target_muscle: 'chest', suggested_sets: 4, suggested_reps: '8–12 reps', instructions: '30° incline bench, deep stretch at bottom.' },
          { id: 'ppl-p-2', name: 'Barbell Flat Bench Press', target_muscle: 'chest', suggested_sets: 3, suggested_reps: '6–8 reps', instructions: 'Heavy progressive overload.' },
          { id: 'ppl-p-3', name: 'Cable Lateral Raises', target_muscle: 'shoulders', suggested_sets: 4, suggested_reps: '12–15 reps', instructions: 'Squeeze side delts at top.' },
          { id: 'ppl-p-4', name: 'Overhead Tricep Rope Extension', target_muscle: 'triceps', suggested_sets: 3, suggested_reps: '12–15 reps', instructions: 'Flare rope at peak extension.' },
        ],
        target_steps: 10000,
        calorie_offset: 200,
        carb_focus: 'high',
        fasting_protocol: '16_8',
        water_goal_oz: 120,
        is_grocery_day: false,
        is_batch_prep_day: false,
        notes: 'Push hypertrophy focus. Emphasize mind-muscle connection and full extension.',
      },
      {
        day_of_week: 2,
        day_label: 'Tuesday',
        workout_title: 'Pull Density (Lats, Rhomboids, Biceps)',
        workout_category: 'bodybuilding',
        exercises: [
          { id: 'ppl-pl-1', name: 'Lat Pulldowns or Weighted Pull-Ups', target_muscle: 'back', suggested_sets: 4, suggested_reps: '8–10 reps', instructions: 'Drive elbows down into hips.' },
          { id: 'ppl-pl-2', name: 'Seated Cable Cable Row', target_muscle: 'back', suggested_sets: 4, suggested_reps: '10–12 reps', instructions: 'Squeeze shoulder blades together.' },
          { id: 'ppl-pl-3', name: 'Incline Dumbbell Bicep Curls', target_muscle: 'biceps', suggested_sets: 3, suggested_reps: '10–12 reps', instructions: 'Full bicep stretch, supinated twist.' },
        ],
        target_steps: 10000,
        calorie_offset: 200,
        carb_focus: 'high',
        fasting_protocol: '16_8',
        water_goal_oz: 120,
        is_grocery_day: false,
        is_batch_prep_day: false,
        notes: 'Pull density day. Focus on scapular retraction and strict bicep isolation.',
      },
      {
        day_of_week: 3,
        day_label: 'Wednesday',
        workout_title: 'Legs & Quads (Squats, Lunges, Calves)',
        workout_category: 'bodybuilding',
        exercises: [
          { id: 'ppl-l-1', name: 'Barbell Back Squat', target_muscle: 'quads', suggested_sets: 4, suggested_reps: '8–10 reps', instructions: 'Clean depth, upright posture.' },
          { id: 'ppl-l-2', name: 'Romanian Deadlift (RDL)', target_muscle: 'hamstrings', suggested_sets: 3, suggested_reps: '10–12 reps', instructions: 'Hinge hips back, feel deep hamstring stretch.' },
          { id: 'ppl-l-3', name: 'Walking Dumbbell Lunges', target_muscle: 'quads', suggested_sets: 3, suggested_reps: '20 total steps', instructions: 'Knee tracking over toes.' },
        ],
        target_steps: 10000,
        calorie_offset: 300,
        carb_focus: 'high',
        fasting_protocol: '16_8',
        water_goal_oz: 130,
        is_grocery_day: false,
        is_batch_prep_day: false,
        notes: 'High-calorie training day. Prioritize intra-workout hydration.',
      },
      {
        day_of_week: 4,
        day_label: 'Thursday',
        workout_title: 'Concept2® Tabata WOD & Calorie Burner',
        workout_category: 'concept2_rowing',
        exercises: [
          { id: 'ppl-c2-1', name: 'Concept2 Rower: 30-Minute Pyramids & Sprints', target_muscle: 'full_body_cardio', suggested_sets: 1, suggested_reps: '30 mins', instructions: 'Alternate 2 mins hard pace / 1 min easy paddle.' },
        ],
        target_steps: 12000,
        calorie_offset: 0,
        carb_focus: 'moderate',
        fasting_protocol: '16_8',
        water_goal_oz: 120,
        is_grocery_day: false,
        is_batch_prep_day: false,
        notes: 'Aerobic recovery and active flush day.',
      },
      {
        day_of_week: 5,
        day_label: 'Friday',
        workout_title: 'Upper Body Hypertrophy (Chest & Back Superset)',
        workout_category: 'bodybuilding',
        exercises: [
          { id: 'ppl-u-1', name: 'Dumbbell Flat Bench Press', target_muscle: 'chest', suggested_sets: 4, suggested_reps: '10–12 reps', instructions: 'Squeeze pecs at lockout.' },
          { id: 'ppl-u-2', name: 'Chest-Supported Dumbbell Row', target_muscle: 'back', suggested_sets: 4, suggested_reps: '10–12 reps', instructions: 'Eliminate momentum, pull with upper back.' },
        ],
        target_steps: 10000,
        calorie_offset: 200,
        carb_focus: 'high',
        fasting_protocol: '16_8',
        water_goal_oz: 120,
        is_grocery_day: false,
        is_batch_prep_day: false,
        notes: 'Upper body pump session before the weekend.',
      },
      {
        day_of_week: 6,
        day_label: 'Saturday',
        workout_title: 'Lower Body & Hamstrings + Batch Prep Day',
        workout_category: 'bodybuilding',
        exercises: [
          { id: 'ppl-lh-1', name: 'Leg Press or Front Squats', target_muscle: 'quads', suggested_sets: 4, suggested_reps: '12–15 reps', instructions: 'Smooth tempo, constant tension.' },
          { id: 'ppl-lh-2', name: 'Seated or Lying Hamstring Curls', target_muscle: 'hamstrings', suggested_sets: 4, suggested_reps: '12–15 reps', instructions: 'Full curl to glutes.' },
        ],
        target_steps: 10000,
        calorie_offset: 100,
        carb_focus: 'moderate',
        fasting_protocol: '14_10',
        water_goal_oz: 100,
        is_grocery_day: false,
        is_batch_prep_day: true,
        notes: 'Meal prep day: Prep proteins and carbs in bulk for the coming week.',
      },
      {
        day_of_week: 7,
        day_label: 'Sunday',
        workout_title: 'Full Recovery, Mobility & Grocery Requisition',
        workout_category: 'rest',
        exercises: [
          { id: 'ppl-r-1', name: 'Full-Body Foam Rolling & Stretching', target_muscle: 'mobility', suggested_sets: 1, suggested_reps: '15 mins', instructions: 'Relax nervous system and restore connective tissue.' },
        ],
        target_steps: 8000,
        calorie_offset: -200,
        carb_focus: 'low',
        fasting_protocol: '16_8',
        water_goal_oz: 96,
        is_grocery_day: true,
        is_batch_prep_day: false,
        notes: 'Grocery day: Restock all weekly ingredients.',
      },
    ],
  },
  {
    id: 'template_daily_wellness_16_8',
    title: 'Daily Wellness & Lean 16:8 Circadian Routine',
    subtitle: 'Balanced Daily Movement, Wholesome Nutrition & Consistent Habit Tracking',
    description:
      'Intuitive, sustainable schedule focused on daily 10,000 steps, wholesome balanced meals, 16:8 intermittent fasting, and weekly grocery restocking.',
    icon: '✨',
    accent_color: '#10b981',
    recommended_duration_weeks: 12,
    weekly_rhythm: [
      {
        day_of_week: 1,
        day_label: 'Monday',
        workout_title: 'Morning Energizing Walk & Gentle Core',
        workout_category: 'mobility',
        exercises: [
          { id: 'w-m-1', name: 'Brisk Outdoor Morning Walk', target_muscle: 'full_body_cardio', suggested_sets: 1, suggested_reps: '30 minutes', instructions: 'Get morning sunlight and brisk pace.' },
        ],
        target_steps: 10000,
        calorie_offset: 0,
        carb_focus: 'moderate',
        fasting_protocol: '16_8',
        water_goal_oz: 96,
        is_grocery_day: false,
        is_batch_prep_day: false,
        notes: 'Start the week with steady hydration and 10,000 steps.',
      },
      {
        day_of_week: 2,
        day_label: 'Tuesday',
        workout_title: 'Full-Body Feel-Good Movement',
        workout_category: 'mobility',
        exercises: [
          { id: 'w-t-1', name: 'Bodyweight Squats & Wall Push-Ups', target_muscle: 'quads', suggested_sets: 3, suggested_reps: '15 reps each', instructions: 'Smooth pain-free movement.' },
        ],
        target_steps: 10000,
        calorie_offset: 0,
        carb_focus: 'moderate',
        fasting_protocol: '16_8',
        water_goal_oz: 96,
        is_grocery_day: false,
        is_batch_prep_day: false,
        notes: 'Keep meals balanced and colorful with fresh vegetables.',
      },
      {
        day_of_week: 3,
        day_label: 'Wednesday',
        workout_title: 'Midweek Cardio & Step Booster',
        workout_category: 'full_body_cardio',
        exercises: [
          { id: 'w-w-1', name: 'Brisk Walk or Light Erg Row', target_muscle: 'full_body_cardio', suggested_sets: 1, suggested_reps: '30 minutes', instructions: 'Rhythmic breathing and steady heart rate.' },
        ],
        target_steps: 11000,
        calorie_offset: 0,
        carb_focus: 'moderate',
        fasting_protocol: '16_8',
        water_goal_oz: 96,
        is_grocery_day: false,
        is_batch_prep_day: false,
        notes: 'Hit hydration goals by 6:00 PM.',
      },
      {
        day_of_week: 4,
        day_label: 'Thursday',
        workout_title: 'Joint Mobility & Spine Release',
        workout_category: 'mobility',
        exercises: [
          { id: 'w-th-1', name: 'Cat-Cow & Hamstring Lengthening', target_muscle: 'mobility', suggested_sets: 3, suggested_reps: '10 waves', instructions: 'Gentle spinal decompression.' },
        ],
        target_steps: 10000,
        calorie_offset: 0,
        carb_focus: 'moderate',
        fasting_protocol: '16_8',
        water_goal_oz: 96,
        is_grocery_day: false,
        is_batch_prep_day: false,
        notes: 'Focus on posture and comfortable deep breathing.',
      },
      {
        day_of_week: 5,
        day_label: 'Friday',
        workout_title: 'End-of-Week Step Target & Walk',
        workout_category: 'full_body_cardio',
        exercises: [
          { id: 'w-f-1', name: 'Afternoon Sunset Walk', target_muscle: 'full_body_cardio', suggested_sets: 1, suggested_reps: '40 minutes', instructions: 'Enjoy fresh air and complete step goal.' },
        ],
        target_steps: 10000,
        calorie_offset: 0,
        carb_focus: 'moderate',
        fasting_protocol: '16_8',
        water_goal_oz: 96,
        is_grocery_day: false,
        is_batch_prep_day: false,
        notes: 'Celebrate your 5-day weekday consistency streak!',
      },
      {
        day_of_week: 6,
        day_label: 'Saturday',
        workout_title: 'Weekend Active Play & Batch Cooking',
        workout_category: 'mobility',
        exercises: [
          { id: 'w-sa-1', name: 'Outdoor Activity / Yard Walk', target_muscle: 'full_body_cardio', suggested_sets: 1, suggested_reps: '45 minutes', instructions: 'Free movement.' },
        ],
        target_steps: 10000,
        calorie_offset: 0,
        carb_focus: 'moderate',
        fasting_protocol: '14_10',
        water_goal_oz: 96,
        is_grocery_day: false,
        is_batch_prep_day: true,
        notes: 'Batch prep favorite wholesome soups, roasted sweet potatoes, and proteins.',
      },
      {
        day_of_week: 7,
        day_label: 'Sunday',
        workout_title: 'Mindful Rest & Grocery Restocking Day',
        workout_category: 'rest',
        exercises: [
          { id: 'w-su-1', name: 'Gentle Stretching & Savasana', target_muscle: 'mobility', suggested_sets: 1, suggested_reps: '15 minutes', instructions: 'Total physical relaxation.' },
        ],
        target_steps: 8000,
        calorie_offset: 0,
        carb_focus: 'moderate',
        fasting_protocol: '16_8',
        water_goal_oz: 96,
        is_grocery_day: true,
        is_batch_prep_day: false,
        notes: 'Grocery store restock: Fresh berries, greens, eggs, and lean proteins.',
      },
    ],
  },
];
