import { CatalogGroceryItem, GroceryStoreTag, FoodCategory } from './types';

export interface StoreBrandProduct extends CatalogGroceryItem {
  brand: string;
  package_size: string;
  store_tag_primary: 'sams_club' | 'aldi' | 'meijer' | 'costco' | 'walmart';
}

// =========================================================================
// 1. SAM'S CLUB (Member's Mark Wholesale & Bulk)
// =========================================================================
export const SAMS_CLUB_PRODUCTS: StoreBrandProduct[] = [
  {
    id: 'sam_chicken_breast',
    name: "Member's Mark Boneless Skinless Chicken Breasts",
    brand: "Member's Mark (Sam's Club)",
    package_size: '6.5 lb Vacuum Pack',
    department: 'poultry_meat' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'pack (6.5 lbs)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 120,
    protein_g: 26,
    carbs_g: 0,
    fat_g: 1.5,
    common_substitutes: [
      { name: "Member's Mark 93/7 Lean Ground Turkey (4 x 1 lb)", department: 'poultry_meat' as any, default_unit: 'pack', conversion_ratio: 1.0, reason: 'Bulk lean poultry alternative' },
      { name: "Member's Mark Wild Alaskan Sockeye Salmon", department: 'fish_seafood' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'High Omega-3 bulk fish' },
    ],
    icon_emoji: '🍗',
  },
  {
    id: 'sam_ground_turkey',
    name: "Member's Mark 93/7 Lean Ground Turkey",
    brand: "Member's Mark (Sam's Club)",
    package_size: '4 x 1 lb Vacuum Packs (4 lbs total)',
    department: 'poultry_meat' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'pack (4 lbs)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 160,
    protein_g: 22,
    carbs_g: 0,
    fat_g: 8,
    common_substitutes: [
      { name: "Member's Mark Boneless Skinless Chicken Breasts", department: 'poultry_meat' as any, default_unit: 'pack', conversion_ratio: 1.0, reason: 'Leaner poultry cut' },
    ],
    icon_emoji: '🦃',
  },
  {
    id: 'sam_top_sirloin',
    name: "Member's Mark USDA Choice Angus Beef Top Sirloin Steaks",
    brand: "Member's Mark (Sam's Club)",
    package_size: '3.5 lb Multi-Pack',
    department: 'poultry_meat' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'pack (3.5 lbs)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 180,
    protein_g: 27,
    carbs_g: 0,
    fat_g: 7,
    common_substitutes: [
      { name: "Member's Mark Boneless Skinless Chicken Breasts", department: 'poultry_meat' as any, default_unit: 'pack', conversion_ratio: 1.0, reason: 'Lean poultry alternative' },
    ],
    icon_emoji: '🥩',
  },
  {
    id: 'sam_sockeye_salmon',
    name: "Member's Mark Wild Alaskan Sockeye Salmon Portions",
    brand: "Member's Mark (Sam's Club)",
    package_size: '2 lb Bag (Frozen Skin-On Portions)',
    department: 'fish_seafood' as any,
    shelf_life: 'freezer_monthly',
    default_unit: 'bag (2 lbs)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 150,
    protein_g: 24,
    carbs_g: 0,
    fat_g: 5.5,
    common_substitutes: [
      { name: "Member's Mark Raw Tail-On Wild Gulf Shrimp", department: 'fish_seafood' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'Lean high-protein shellfish' },
    ],
    icon_emoji: '🐟',
  },
  {
    id: 'sam_wild_shrimp',
    name: "Member's Mark Raw Tail-On Wild Gulf Shrimp (21-25 ct)",
    brand: "Member's Mark (Sam's Club)",
    package_size: '2 lb Bag (Peeled & Deveined)',
    department: 'fish_seafood' as any,
    shelf_life: 'freezer_monthly',
    default_unit: 'bag (2 lbs)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 90,
    protein_g: 20,
    carbs_g: 0,
    fat_g: 1,
    common_substitutes: [
      { name: "Member's Mark Wild Alaskan Sockeye Salmon", department: 'fish_seafood' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'Heart-healthy fatty fish' },
    ],
    icon_emoji: '🦐',
  },
  {
    id: 'sam_cage_free_eggs',
    name: "Member's Mark Cage-Free Grade A Large White Eggs",
    brand: "Member's Mark (Sam's Club)",
    package_size: '2 x 18 count (36 count total)',
    department: 'dairy_eggs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'carton (36 eggs)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 70,
    protein_g: 6,
    carbs_g: 0.5,
    fat_g: 5,
    common_substitutes: [
      { name: "Member's Mark 100% Pure Liquid Egg Whites (6 x 16oz)", department: 'dairy_eggs' as any, default_unit: 'pack', conversion_ratio: 1.0, reason: 'Zero-fat albumin protein' },
    ],
    icon_emoji: '🥚',
  },
  {
    id: 'sam_liquid_egg_whites',
    name: "Member's Mark 100% Pure Liquid Egg Whites",
    brand: "Member's Mark (Sam's Club)",
    package_size: '6 x 16 oz Cartons (96 oz / 6 lbs total)',
    department: 'dairy_eggs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'pack (6 x 16oz)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 25,
    protein_g: 5,
    carbs_g: 0,
    fat_g: 0,
    common_substitutes: [
      { name: "Member's Mark Cage-Free Eggs", department: 'dairy_eggs' as any, default_unit: 'carton', conversion_ratio: 0.8, reason: 'Whole eggs with nutrient-rich yolks' },
    ],
    icon_emoji: '🥛',
  },
  {
    id: 'sam_greek_yogurt',
    name: "Member's Mark Plain Nonfat Greek Yogurt",
    brand: "Member's Mark (Sam's Club)",
    package_size: '48 oz Tub (3 lbs)',
    department: 'dairy_eggs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'tub (48 oz)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 90,
    protein_g: 16,
    carbs_g: 6,
    fat_g: 0,
    common_substitutes: [
      { name: "Member's Mark Low Fat 2% Cottage Cheese (48 oz)", department: 'dairy_eggs' as any, default_unit: 'tub', conversion_ratio: 1.0, reason: 'Casein protein slow release' },
    ],
    icon_emoji: '🥣',
  },
  {
    id: 'sam_rolled_oats',
    name: "Member's Mark Organic Old Fashioned Rolled Oats",
    brand: "Member's Mark (Sam's Club)",
    package_size: '10 lb Box (2 x 5 lb bags)',
    department: 'grains_carbs' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'box (10 lbs)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 150,
    protein_g: 5,
    carbs_g: 27,
    fat_g: 2.5,
    common_substitutes: [
      { name: "Member's Mark Organic Tri-Color Quinoa (4.5 lbs)", department: 'grains_carbs' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'Complete amino acid grain' },
    ],
    icon_emoji: '🥣',
  },
  {
    id: 'sam_jasmine_rice',
    name: "Member's Mark Thai Hom Mali Jasmine White Rice",
    brand: "Member's Mark (Sam's Club)",
    package_size: '25 lb Heavy Duty Sack',
    department: 'grains_carbs' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'bag (25 lbs)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 160,
    protein_g: 3,
    carbs_g: 36,
    fat_g: 0,
    common_substitutes: [
      { name: "Member's Mark Organic Rolled Oats (10 lbs)", department: 'grains_carbs' as any, default_unit: 'box', conversion_ratio: 1.0, reason: 'High fiber whole grain' },
    ],
    icon_emoji: '🍚',
  },
  {
    id: 'sam_evoo',
    name: "Member's Mark Organic Extra Virgin Olive Oil (Cold-Pressed)",
    brand: "Member's Mark (Sam's Club)",
    package_size: '2 Liter Bottle (67.6 fl oz)',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'bottle (2L)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 120,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 14,
    common_substitutes: [
      { name: "Member's Mark 100% Pure Avocado Oil (1L)", department: 'nuts_fats_oils' as any, default_unit: 'bottle', conversion_ratio: 1.0, reason: 'High-heat cooking oil' },
    ],
    icon_emoji: '🫒',
  },
  {
    id: 'sam_raw_almonds',
    name: "Member's Mark Whole Natural California Raw Almonds",
    brand: "Member's Mark (Sam's Club)",
    package_size: '3 lb Bag (48 oz Resealable)',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'bag (3 lbs)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 160,
    protein_g: 6,
    carbs_g: 6,
    fat_g: 14,
    common_substitutes: [
      { name: "Member's Mark Raw California Walnuts (3 lbs)", department: 'nuts_fats_oils' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'Plant-based Omega-3 ALA' },
    ],
    icon_emoji: '🥜',
  },
  {
    id: 'sam_baby_spinach',
    name: "Member's Mark Organic Baby Spinach Clamshell",
    brand: "Member's Mark (Sam's Club)",
    package_size: '16 oz (1 lb) Clear Clamshell',
    department: 'vegetables' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'clamshell (16 oz)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 25,
    protein_g: 3,
    carbs_g: 4,
    fat_g: 0.5,
    common_substitutes: [
      { name: "Member's Mark Fresh Cut Broccoli Florets (3 lbs)", department: 'vegetables' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'Cruciferous nutrient density' },
    ],
    icon_emoji: '🍃',
  },
  {
    id: 'sam_frozen_blueberries',
    name: "Member's Mark Organic Frozen Wild Blueberries",
    brand: "Member's Mark (Sam's Club)",
    package_size: '3 lb Bag (48 oz)',
    department: 'fruits' as any,
    shelf_life: 'freezer_monthly',
    default_unit: 'bag (3 lbs)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 70,
    protein_g: 1,
    carbs_g: 17,
    fat_g: 0.5,
    common_substitutes: [
      { name: "Member's Mark Organic Frozen Triple Berry Blend (3 lbs)", department: 'fruits' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'Mixed berries with raspberries' },
    ],
    icon_emoji: '🫐',
  },
  {
    id: 'sam_premier_protein',
    name: 'Premier Protein 30g High Protein Shakes (Vanilla / Chocolate)',
    brand: "Sam's Club Bulk Case",
    package_size: '18 x 11.5 fl oz Pack',
    department: 'beverages_hydration' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'case (18 shakes)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 160,
    protein_g: 30,
    carbs_g: 4,
    fat_g: 3,
    common_substitutes: [
      { name: "Member's Mark Plain Nonfat Greek Yogurt (48 oz)", department: 'dairy_eggs' as any, default_unit: 'tub', conversion_ratio: 1.0, reason: 'Whole-food dairy protein' },
    ],
    icon_emoji: '🥤',
  },
  {
    id: 'sam_oatmeal_maple',
    name: "Member's Mark Instant Oatmeal (Maple & Brown Sugar)",
    brand: "Member's Mark (Sam's Club)",
    package_size: '60 Count Variety Box',
    department: 'grains_carbs' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'box (60 packets)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 160,
    protein_g: 4,
    carbs_g: 32,
    fat_g: 2,
    common_substitutes: [
      { name: "Member's Mark Rolled Oats", department: 'grains_carbs' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'Unsweetened whole oats' },
    ],
    icon_emoji: '🥣',
  },
  {
    id: 'sam_whole_wheat_bread',
    name: "Member's Mark 100% Whole Wheat Bread (Twin Pack)",
    brand: "Member's Mark (Sam's Club)",
    package_size: '2 x 24 oz Loaves',
    department: 'grains_carbs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'twin pack (2 loaves)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 70,
    protein_g: 4,
    carbs_g: 13,
    fat_g: 1,
    common_substitutes: [
      { name: "Member's Mark Artisan Sourdough", department: 'grains_carbs' as any, default_unit: 'loaf', conversion_ratio: 1.0, reason: 'Artisan bakery bread' },
    ],
    icon_emoji: '🍞',
  },
  {
    id: 'sam_creamy_peanut_butter',
    name: "Member's Mark Creamy Peanut Butter (Twin Pack)",
    brand: "Member's Mark (Sam's Club)",
    package_size: '2 x 48 oz Jars (6 lbs total)',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'pack (2 x 48 oz jars)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 190,
    protein_g: 7,
    carbs_g: 7,
    fat_g: 16,
    common_substitutes: [
      { name: "Member's Mark Almond Butter", department: 'nuts_fats_oils' as any, default_unit: 'jar', conversion_ratio: 1.0, reason: 'Tree nut butter' },
    ],
    icon_emoji: '🥜',
  },
  {
    id: 'sam_salted_butter_sticks',
    name: "Member's Mark Salted Sweet Cream Butter (Sticks)",
    brand: "Member's Mark (Sam's Club)",
    package_size: '4 x 1 lb Boxes (16 Sticks total)',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'box (16 sticks)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 100,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 11,
    common_substitutes: [
      { name: "Member's Mark Unsalted Butter", department: 'nuts_fats_oils' as any, default_unit: 'box', conversion_ratio: 1.0, reason: 'Sodium-free butter' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'sam_unsalted_butter_sticks',
    name: "Member's Mark Unsalted Sweet Cream Butter (Sticks)",
    brand: "Member's Mark (Sam's Club)",
    package_size: '4 x 1 lb Boxes (16 Sticks total)',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'box (16 sticks)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 100,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 11,
    common_substitutes: [
      { name: "Member's Mark Salted Butter", department: 'nuts_fats_oils' as any, default_unit: 'box', conversion_ratio: 1.0, reason: 'Salted table butter' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'sam_butter_canola_tub',
    name: "Member's Mark Spreadable Butter with Canola Oil (Tub)",
    brand: "Member's Mark (Sam's Club)",
    package_size: '32 oz Tub',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'tub (32 oz)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 100,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 11,
    common_substitutes: [
      { name: "Member's Mark Salted Butter Sticks", department: 'nuts_fats_oils' as any, default_unit: 'box', conversion_ratio: 1.0, reason: 'Baking sticks' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'sam_strawberry_spread',
    name: "Member's Mark Organic Strawberry Fruit Spread",
    brand: "Member's Mark (Sam's Club)",
    package_size: '42 oz Glass Jar',
    department: 'snacks_pantry' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'jar (42 oz)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 40,
    protein_g: 0,
    carbs_g: 10,
    fat_g: 0,
    common_substitutes: [
      { name: "Member's Mark Pure Honey", department: 'snacks_pantry' as any, default_unit: 'bottle', conversion_ratio: 0.8, reason: 'Natural sweetener' },
    ],
    icon_emoji: '🍓',
  },
  {
    id: 'sam_sugar_free_syrup',
    name: "Member's Mark Sugar Free Pancake Syrup",
    brand: "Member's Mark (Sam's Club)",
    package_size: '2 x 33.8 fl oz Twin Pack',
    department: 'snacks_pantry' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'pack (2 bottles)',
    default_quantity: 1,
    store_tags: ['sams_club'],
    store_tag_primary: 'sams_club',
    calories_per_serving: 20,
    protein_g: 0,
    carbs_g: 6,
    fat_g: 0,
    common_substitutes: [
      { name: "Member's Mark 100% Pure Maple Syrup", department: 'snacks_pantry' as any, default_unit: 'jug', conversion_ratio: 1.0, reason: 'Pure maple alternative' },
    ],
    icon_emoji: '🥞',
  },
];

// =========================================================================
// 2. ALDI (Simply Nature, Friendly Farms, Earth Grown, Specially Selected)
// =========================================================================
export const ALDI_PRODUCTS: StoreBrandProduct[] = [
  {
    id: 'aldi_organic_beef',
    name: 'Simply Nature 100% Organic Grass-Fed 85/15 Ground Beef',
    brand: 'Simply Nature (Aldi)',
    package_size: '1 lb Vacuum Sealed Brick',
    department: 'poultry_meat' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'pack (1 lb)',
    default_quantity: 2,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 215,
    protein_g: 21,
    carbs_g: 0,
    fat_g: 15,
    common_substitutes: [
      { name: 'Simply Nature Organic Boneless Chicken Breasts', department: 'poultry_meat' as any, default_unit: 'pack', conversion_ratio: 1.0, reason: 'Ultra-lean organic poultry' },
    ],
    icon_emoji: '🥩',
  },
  {
    id: 'aldi_organic_chicken',
    name: 'Simply Nature Organic Boneless Skinless Chicken Breasts',
    brand: 'Simply Nature (Aldi)',
    package_size: '1.25 lb Tray',
    department: 'poultry_meat' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'pack (1.25 lbs)',
    default_quantity: 2,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 120,
    protein_g: 26,
    carbs_g: 0,
    fat_g: 1.5,
    common_substitutes: [
      { name: 'Simply Nature Organic Grass-Fed Ground Beef', department: 'poultry_meat' as any, default_unit: 'pack', conversion_ratio: 1.0, reason: 'Grass-fed red meat' },
      { name: 'Specially Selected Wild Caught Salmon Fillets', department: 'fish_seafood' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'Wild Alaskan omega-3 fish' },
    ],
    icon_emoji: '🍗',
  },
  {
    id: 'aldi_wild_salmon',
    name: 'Specially Selected Wild Caught Alaskan Salmon Fillets',
    brand: 'Specially Selected (Aldi)',
    package_size: '16 oz (1 lb) Frozen Portions',
    department: 'fish_seafood' as any,
    shelf_life: 'freezer_monthly',
    default_unit: 'bag (1 lb)',
    default_quantity: 2,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 140,
    protein_g: 22,
    carbs_g: 0,
    fat_g: 5,
    common_substitutes: [
      { name: 'Fremont Fish Market Wild Caught Raw Shrimp', department: 'fish_seafood' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'Lean seafood staple' },
    ],
    icon_emoji: '🐟',
  },
  {
    id: 'aldi_pasture_eggs',
    name: 'Simply Nature Organic Pasture-Raised Grade A Large Eggs',
    brand: 'Simply Nature (Aldi)',
    package_size: '12 count Carton',
    department: 'dairy_eggs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'dozen',
    default_quantity: 2,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 70,
    protein_g: 6,
    carbs_g: 0,
    fat_g: 5,
    common_substitutes: [
      { name: 'Fit & Active 100% Liquid Egg Whites (32 oz)', department: 'dairy_eggs' as any, default_unit: 'carton', conversion_ratio: 1.0, reason: 'Pure lean egg albumin' },
    ],
    icon_emoji: '🥚',
  },
  {
    id: 'aldi_liquid_egg_whites',
    name: 'Fit & Active 100% Liquid Egg Whites',
    brand: 'Fit & Active (Aldi)',
    package_size: '32 oz Carton (Quart)',
    department: 'dairy_eggs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'carton (32 oz)',
    default_quantity: 2,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 25,
    protein_g: 5,
    carbs_g: 0,
    fat_g: 0,
    common_substitutes: [
      { name: 'Simply Nature Organic Pasture-Raised Eggs', department: 'dairy_eggs' as any, default_unit: 'dozen', conversion_ratio: 0.8, reason: 'Whole eggs with nutrient yolks' },
    ],
    icon_emoji: '🥛',
  },
  {
    id: 'aldi_greek_yogurt',
    name: 'Friendly Farms Nonfat Plain Greek Yogurt (0% Fat)',
    brand: 'Friendly Farms (Aldi)',
    package_size: '32 oz Tub',
    department: 'dairy_eggs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'tub (32 oz)',
    default_quantity: 2,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 90,
    protein_g: 16,
    carbs_g: 6,
    fat_g: 0,
    common_substitutes: [
      { name: 'Friendly Farms Lowfat 1% Cottage Cheese', department: 'dairy_eggs' as any, default_unit: 'tub', conversion_ratio: 1.0, reason: 'Casein protein slow digest' },
    ],
    icon_emoji: '🥣',
  },
  {
    id: 'aldi_organic_tofu',
    name: 'Simply Nature Organic Extra Firm Tofu',
    brand: 'Simply Nature (Aldi)',
    package_size: '14 oz Water Pack Block',
    department: 'plant_protein' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'block (14 oz)',
    default_quantity: 2,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 90,
    protein_g: 10,
    carbs_g: 2,
    fat_g: 5,
    common_substitutes: [
      { name: 'Earth Grown Meatless Vegan Burger Patties', department: 'plant_protein' as any, default_unit: 'box', conversion_ratio: 1.0, reason: 'Plant patty staple' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'aldi_millville_oats',
    name: 'Millville Old Fashioned 100% Whole Grain Rolled Oats',
    brand: 'Millville (Aldi)',
    package_size: '42 oz Canister',
    department: 'grains_carbs' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'canister (42 oz)',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 150,
    protein_g: 5,
    carbs_g: 27,
    fat_g: 2.5,
    common_substitutes: [
      { name: 'Simply Nature Organic Brown Jasmine Rice', department: 'grains_carbs' as any, default_unit: 'pouch', conversion_ratio: 1.0, reason: 'Easy steam whole grain' },
    ],
    icon_emoji: '🥣',
  },
  {
    id: 'aldi_sourdough',
    name: 'Specially Selected 100% Whole Wheat Sourdough Loaf',
    brand: 'Specially Selected (Aldi)',
    package_size: '24 oz Artisan Loaf',
    department: 'grains_carbs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'loaf',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 130,
    protein_g: 5,
    carbs_g: 25,
    fat_g: 1,
    common_substitutes: [
      { name: 'Millville Old Fashioned Rolled Oats', department: 'grains_carbs' as any, default_unit: 'canister', conversion_ratio: 1.0, reason: 'Whole grain oats' },
    ],
    icon_emoji: '🍞',
  },
  {
    id: 'aldi_organic_evoo',
    name: 'Simply Nature 100% Organic Extra Virgin Olive Oil',
    brand: 'Simply Nature (Aldi)',
    package_size: '16.9 fl oz Glass Bottle',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'bottle (16.9 oz)',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 120,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 14,
    common_substitutes: [
      { name: 'Simply Nature Organic Creamy Peanut Butter', department: 'nuts_fats_oils' as any, default_unit: 'jar', conversion_ratio: 1.0, reason: 'Healthy nut fat source' },
    ],
    icon_emoji: '🫒',
  },
  {
    id: 'aldi_cc_butter_salted_sticks',
    name: 'Countryside Creamery Salted Sweet Cream Butter (4 Sticks)',
    brand: 'Countryside Creamery (Aldi)',
    package_size: '16 oz (1 lb) 4 Sticks Pack',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'box (4 sticks)',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 100,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 11,
    common_substitutes: [
      { name: 'Countryside Creamery Unsalted Butter (4 Sticks)', department: 'nuts_fats_oils' as any, default_unit: 'box', conversion_ratio: 1.0, reason: 'Sodium-free baking butter' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'aldi_cc_butter_unsalted_sticks',
    name: 'Countryside Creamery Unsalted Sweet Cream Butter (4 Sticks)',
    brand: 'Countryside Creamery (Aldi)',
    package_size: '16 oz (1 lb) 4 Sticks Pack',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'box (4 sticks)',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 100,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 11,
    common_substitutes: [
      { name: 'Countryside Creamery Salted Butter (4 Sticks)', department: 'nuts_fats_oils' as any, default_unit: 'box', conversion_ratio: 1.0, reason: 'Table butter' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'aldi_cc_butter_canola_tub',
    name: 'Countryside Creamery Butter with Canola Oil (Spreadable Tub)',
    brand: 'Countryside Creamery (Aldi)',
    package_size: '15 oz Spreadable Tub',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'tub (15 oz)',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 100,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 11,
    common_substitutes: [
      { name: 'Countryside Creamery Salted Butter (4 Sticks)', department: 'nuts_fats_oils' as any, default_unit: 'box', conversion_ratio: 1.0, reason: 'Stick butter alternative' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'aldi_cc_homestyle_spread',
    name: 'Countryside Creamery Homestyle Spread (Tub)',
    brand: 'Countryside Creamery (Aldi)',
    package_size: '45 oz Value Tub',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'tub (45 oz)',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 60,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 7,
    common_substitutes: [
      { name: 'Countryside Creamery Butter with Canola Oil (Tub)', department: 'nuts_fats_oils' as any, default_unit: 'tub', conversion_ratio: 1.0, reason: 'Higher butterfat spread' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'aldi_cc_irish_butter_sticks',
    name: 'Countryside Creamery Pure Irish Butter - Salted (Gold Foil Bar)',
    brand: 'Countryside Creamery (Aldi)',
    package_size: '8 oz Gold Foil Bar',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'bar (8 oz)',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 100,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 11,
    common_substitutes: [
      { name: 'Kerrygold Pure Irish Butter', department: 'nuts_fats_oils' as any, default_unit: 'bar', conversion_ratio: 1.0, reason: 'Imported grass-fed butter' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'aldi_cc_irish_butter_tub',
    name: 'Countryside Creamery Naturally Softer Pure Irish Butter (Tub)',
    brand: 'Countryside Creamery (Aldi)',
    package_size: '7.5 oz Spreadable Tub',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'tub (7.5 oz)',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 100,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 11,
    common_substitutes: [
      { name: 'Countryside Creamery Pure Irish Butter (Bar)', department: 'nuts_fats_oils' as any, default_unit: 'bar', conversion_ratio: 1.0, reason: 'Foil bar format' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'aldi_cc_plant_butter_sticks',
    name: 'Countryside Creamery Plant Based Butter with Olive Oil (Sticks)',
    brand: 'Countryside Creamery (Aldi)',
    package_size: '16 oz (4 Sticks) Box',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'box (4 sticks)',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 100,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 11,
    common_substitutes: [
      { name: 'Countryside Creamery Plant Butter (Tub)', department: 'nuts_fats_oils' as any, default_unit: 'tub', conversion_ratio: 1.0, reason: 'Spreadable tub plant butter' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'aldi_cc_plant_butter_tub',
    name: 'Countryside Creamery Plant Based Butter with Olive Oil (Tub)',
    brand: 'Countryside Creamery (Aldi)',
    package_size: '15 oz Tub',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'tub (15 oz)',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 100,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 11,
    common_substitutes: [
      { name: 'Countryside Creamery Plant Butter (Sticks)', department: 'nuts_fats_oils' as any, default_unit: 'box', conversion_ratio: 1.0, reason: 'Baking sticks' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'aldi_millville_instant_original',
    name: 'Millville Instant Oatmeal (Original / Plain, 12 Packets)',
    brand: 'Millville (Aldi)',
    package_size: '11.8 oz Box (12 x 0.98 oz Packets)',
    department: 'grains_carbs' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'box (12 packets)',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 100,
    protein_g: 4,
    carbs_g: 19,
    fat_g: 2,
    common_substitutes: [
      { name: 'Millville Old Fashioned Rolled Oats (42 oz)', department: 'grains_carbs' as any, default_unit: 'canister', conversion_ratio: 1.0, reason: 'Canister whole grain oats' },
    ],
    icon_emoji: '🥣',
  },
  {
    id: 'aldi_millville_instant_maple',
    name: 'Millville Instant Oatmeal (Maple & Brown Sugar, 10 Packets)',
    brand: 'Millville (Aldi)',
    package_size: '15.1 oz Box (10 x 1.51 oz Packets)',
    department: 'grains_carbs' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'box (10 packets)',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 160,
    protein_g: 4,
    carbs_g: 32,
    fat_g: 2,
    common_substitutes: [
      { name: 'Millville Instant Oatmeal Original', department: 'grains_carbs' as any, default_unit: 'box', conversion_ratio: 1.0, reason: 'Plain unsweetened instant oats' },
    ],
    icon_emoji: '🥣',
  },
  {
    id: 'aldi_organic_spinach',
    name: 'Simply Nature Organic Baby Spinach Clamshell',
    brand: 'Simply Nature (Aldi)',
    package_size: '16 oz (1 lb) Clamshell',
    department: 'vegetables' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'clamshell (16 oz)',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 25,
    protein_g: 3,
    carbs_g: 4,
    fat_g: 0.5,
    common_substitutes: [
      { name: 'Simply Nature Organic Chopped Tuscan Kale', department: 'vegetables' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'Hearty braising green' },
    ],
    icon_emoji: '🍃',
  },
  {
    id: 'aldi_hass_avocados',
    name: 'Aldi Fresh Hass Avocados Bag',
    brand: 'Aldi Fresh Produce',
    package_size: '4 Count Bag',
    department: 'fruits' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'bag (4 count)',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 160,
    protein_g: 2,
    carbs_g: 9,
    fat_g: 15,
    common_substitutes: [
      { name: 'Simply Nature Organic Extra Virgin Olive Oil', department: 'nuts_fats_oils' as any, default_unit: 'bottle', conversion_ratio: 0.3, reason: 'Pure monounsaturated oil' },
    ],
    icon_emoji: '🥑',
  },
  {
    id: 'aldi_organic_blueberries',
    name: 'Simply Nature Organic Fresh Blueberries Pint',
    brand: 'Simply Nature (Aldi)',
    package_size: '1 Pint Container (16 oz)',
    department: 'fruits' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'pint',
    default_quantity: 2,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 85,
    protein_g: 1,
    carbs_g: 21,
    fat_g: 0.5,
    common_substitutes: [
      { name: "Season's Choice Frozen Wild Blueberries", department: 'fruits' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'Frozen antioxidant berries' },
    ],
    icon_emoji: '🫐',
  },
  {
    id: 'aldi_peanut_delight_creamy',
    name: 'Peanut Delight Creamy Peanut Butter',
    brand: 'Peanut Delight (Aldi)',
    package_size: '16 oz Jar',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'jar (16 oz)',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 190,
    protein_g: 7,
    carbs_g: 7,
    fat_g: 16,
    common_substitutes: [
      { name: 'Peanut Delight Crunchy Peanut Butter', department: 'nuts_fats_oils' as any, default_unit: 'jar', conversion_ratio: 1.0, reason: 'Crunchy texture' },
    ],
    icon_emoji: '🥜',
  },
  {
    id: 'aldi_peanut_delight_crunchy',
    name: 'Peanut Delight Crunchy Peanut Butter',
    brand: 'Peanut Delight (Aldi)',
    package_size: '16 oz Jar',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'jar (16 oz)',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 190,
    protein_g: 7,
    carbs_g: 7,
    fat_g: 16,
    common_substitutes: [
      { name: 'Peanut Delight Creamy Peanut Butter', department: 'nuts_fats_oils' as any, default_unit: 'jar', conversion_ratio: 1.0, reason: 'Smooth spread' },
    ],
    icon_emoji: '🥜',
  },
  {
    id: 'aldi_loven_whole_wheat',
    name: "L'oven Fresh 100% Whole Wheat Bread",
    brand: "L'oven Fresh (Aldi)",
    package_size: '20 oz Loaf',
    department: 'grains_carbs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'loaf (20 oz)',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 60,
    protein_g: 4,
    carbs_g: 12,
    fat_g: 0.5,
    common_substitutes: [
      { name: "L'oven Fresh Classic White Bread", department: 'grains_carbs' as any, default_unit: 'loaf', conversion_ratio: 1.0, reason: 'White sandwich bread' },
    ],
    icon_emoji: '🍞',
  },
  {
    id: 'aldi_loven_white_bread',
    name: "L'oven Fresh Classic White Bread",
    brand: "L'oven Fresh (Aldi)",
    package_size: '20 oz Loaf',
    department: 'grains_carbs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'loaf (20 oz)',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 70,
    protein_g: 2,
    carbs_g: 13,
    fat_g: 1,
    common_substitutes: [
      { name: "L'oven Fresh 100% Whole Wheat Bread", department: 'grains_carbs' as any, default_unit: 'loaf', conversion_ratio: 1.0, reason: 'High fiber alternative' },
    ],
    icon_emoji: '🍞',
  },
  {
    id: 'aldi_loven_english_muffins',
    name: "L'oven Fresh Plain English Muffins",
    brand: "L'oven Fresh (Aldi)",
    package_size: '12 oz (6 Count Pack)',
    department: 'grains_carbs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'pack (6 count)',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 120,
    protein_g: 4,
    carbs_g: 25,
    fat_g: 1,
    common_substitutes: [
      { name: "L'oven Fresh 100% Whole Wheat Bread", department: 'grains_carbs' as any, default_unit: 'loaf', conversion_ratio: 1.0, reason: 'Whole wheat sliced bread' },
    ],
    icon_emoji: '🥯',
  },
  {
    id: 'aldi_specially_strawberry_preserves',
    name: 'Specially Selected Strawberry Preserves',
    brand: 'Specially Selected (Aldi)',
    package_size: '10 oz Jar',
    department: 'snacks_pantry' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'jar (10 oz)',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 40,
    protein_g: 0,
    carbs_g: 10,
    fat_g: 0,
    common_substitutes: [
      { name: 'Grandessa Concord Grape Jelly', department: 'snacks_pantry' as any, default_unit: 'jar', conversion_ratio: 1.0, reason: 'Grape jelly alternative' },
    ],
    icon_emoji: '🍓',
  },
  {
    id: 'aldi_grandessa_grape_jelly',
    name: 'Grandessa Concord Grape Jelly',
    brand: 'Grandessa (Aldi)',
    package_size: '30 oz Jar',
    department: 'snacks_pantry' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'jar (30 oz)',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 50,
    protein_g: 0,
    carbs_g: 13,
    fat_g: 0,
    common_substitutes: [
      { name: 'Specially Selected Strawberry Preserves', department: 'snacks_pantry' as any, default_unit: 'jar', conversion_ratio: 1.0, reason: 'Strawberry preserve alternative' },
    ],
    icon_emoji: '🍇',
  },
  {
    id: 'aldi_aunt_maples_sugar_free_syrup',
    name: "Aunt Maple's Sugar Free Pancake Syrup",
    brand: "Aunt Maple's (Aldi)",
    package_size: '24 fl oz Bottle',
    department: 'snacks_pantry' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'bottle (24 oz)',
    default_quantity: 1,
    store_tags: ['aldi'],
    store_tag_primary: 'aldi',
    calories_per_serving: 20,
    protein_g: 0,
    carbs_g: 6,
    fat_g: 0,
    common_substitutes: [
      { name: "Aunt Maple's 100% Pure Maple Syrup", department: 'snacks_pantry' as any, default_unit: 'bottle', conversion_ratio: 1.0, reason: 'Pure maple syrup' },
    ],
    icon_emoji: '🥞',
  },
];

// =========================================================================
// 3. MEIJER (True Goodness & Frederik's by Meijer)
// =========================================================================
export const MEIJER_PRODUCTS: StoreBrandProduct[] = [
  {
    id: 'meijer_true_chicken',
    name: 'True Goodness Organic Boneless Skinless Chicken Breasts',
    brand: 'True Goodness by Meijer',
    package_size: '1.5 lb Recyclable Tray',
    department: 'poultry_meat' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'pack (1.5 lbs)',
    default_quantity: 2,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 120,
    protein_g: 26,
    carbs_g: 0,
    fat_g: 1.5,
    common_substitutes: [
      { name: 'True Goodness 99% Fat Free Ground Turkey Breast', department: 'poultry_meat' as any, default_unit: 'pack', conversion_ratio: 1.0, reason: 'Ultra lean ground turkey' },
      { name: "Frederik's by Meijer Fresh Atlantic Salmon Fillet", department: 'fish_seafood' as any, default_unit: 'lb', conversion_ratio: 1.0, reason: 'Rich Omega-3 salmon' },
    ],
    icon_emoji: '🍗',
  },
  {
    id: 'meijer_true_beef',
    name: 'True Goodness Organic 90/10 Grass-Fed Ground Beef',
    brand: 'True Goodness by Meijer',
    package_size: '1 lb Vacuum Sealed Brick',
    department: 'poultry_meat' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'pack (1 lb)',
    default_quantity: 2,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 175,
    protein_g: 23,
    carbs_g: 0,
    fat_g: 10,
    common_substitutes: [
      { name: 'True Goodness Organic Chicken Breasts', department: 'poultry_meat' as any, default_unit: 'pack', conversion_ratio: 1.0, reason: 'Lower fat poultry' },
    ],
    icon_emoji: '🥩',
  },
  {
    id: 'meijer_frederiks_salmon',
    name: "Frederik's by Meijer Fresh Atlantic Salmon Fillet",
    brand: "Frederik's by Meijer",
    package_size: 'Fresh Farmed Seafood Counter (Per Lb)',
    department: 'fish_seafood' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'lbs',
    default_quantity: 1.5,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 190,
    protein_g: 21,
    carbs_g: 0,
    fat_g: 12,
    common_substitutes: [
      { name: "Frederik's by Meijer Raw Jumbo White Shrimp 16-20 ct", department: 'fish_seafood' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'Lean protein shellfish' },
    ],
    icon_emoji: '🐟',
  },
  {
    id: 'meijer_frederiks_shrimp',
    name: "Frederik's by Meijer Raw Jumbo White Shrimp (16-20 ct)",
    brand: "Frederik's by Meijer",
    package_size: '16 oz (1 lb) Bag (Peeled & Deveined)',
    department: 'fish_seafood' as any,
    shelf_life: 'freezer_monthly',
    default_unit: 'bag (1 lb)',
    default_quantity: 2,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 90,
    protein_g: 20,
    carbs_g: 0,
    fat_g: 1,
    common_substitutes: [
      { name: "Frederik's by Meijer Fresh Atlantic Salmon Fillet", department: 'fish_seafood' as any, default_unit: 'lbs', conversion_ratio: 1.0, reason: 'Essential fatty acids' },
    ],
    icon_emoji: '🦐',
  },
  {
    id: 'meijer_true_eggs',
    name: 'True Goodness Organic Pasture-Raised Large Brown Eggs',
    brand: 'True Goodness by Meijer',
    package_size: '12 count Carton',
    department: 'dairy_eggs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'dozen',
    default_quantity: 2,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 70,
    protein_g: 6,
    carbs_g: 0,
    fat_g: 5,
    common_substitutes: [
      { name: 'Meijer 100% Liquid Egg Whites (32 oz)', department: 'dairy_eggs' as any, default_unit: 'carton', conversion_ratio: 1.0, reason: 'Fat-free albumin protein' },
    ],
    icon_emoji: '🥚',
  },
  {
    id: 'meijer_liquid_egg_whites',
    name: 'Meijer 100% Liquid Egg Whites (Pasteurized)',
    brand: 'Meijer Fresh',
    package_size: '32 oz Carton',
    department: 'dairy_eggs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'carton (32 oz)',
    default_quantity: 2,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 25,
    protein_g: 5,
    carbs_g: 0,
    fat_g: 0,
    common_substitutes: [
      { name: 'True Goodness Organic Pasture-Raised Eggs', department: 'dairy_eggs' as any, default_unit: 'dozen', conversion_ratio: 0.8, reason: 'Whole eggs with nutrient yolks' },
    ],
    icon_emoji: '🥛',
  },
  {
    id: 'meijer_true_greek_yogurt',
    name: 'True Goodness Organic Plain Greek Yogurt',
    brand: 'True Goodness by Meijer',
    package_size: '32 oz Tub',
    department: 'dairy_eggs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'tub (32 oz)',
    default_quantity: 2,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 100,
    protein_g: 15,
    carbs_g: 6,
    fat_g: 2,
    common_substitutes: [
      { name: 'Meijer Lowfat 1% Cottage Cheese (24 oz)', department: 'dairy_eggs' as any, default_unit: 'tub', conversion_ratio: 1.0, reason: 'Casein protein slow digest' },
    ],
    icon_emoji: '🥣',
  },
  {
    id: 'meijer_true_oats',
    name: 'True Goodness Organic Rolled Oats (100% Whole Grain)',
    brand: 'True Goodness by Meijer',
    package_size: '42 oz Canister',
    department: 'grains_carbs' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'canister (42 oz)',
    default_quantity: 1,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 150,
    protein_g: 5,
    carbs_g: 27,
    fat_g: 2.5,
    common_substitutes: [
      { name: 'True Goodness Organic Tri-Color Quinoa (16 oz)', department: 'grains_carbs' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'High protein whole grain' },
    ],
    icon_emoji: '🥣',
  },
  {
    id: 'meijer_instant_oatmeal_original',
    name: 'Meijer Instant Oatmeal (Original / Plain, 12 Packets)',
    brand: 'Meijer',
    package_size: '11.8 oz Box (12 x 0.98 oz Packets)',
    department: 'grains_carbs' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'box (12 packets)',
    default_quantity: 1,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 100,
    protein_g: 4,
    carbs_g: 19,
    fat_g: 2,
    common_substitutes: [
      { name: 'True Goodness Organic Rolled Oats (42 oz)', department: 'grains_carbs' as any, default_unit: 'canister', conversion_ratio: 1.0, reason: 'Bulk plain whole grain rolled oats' },
    ],
    icon_emoji: '🥣',
  },
  {
    id: 'meijer_instant_oatmeal_maple',
    name: 'Meijer Instant Oatmeal (Maple & Brown Sugar, 10 Packets)',
    brand: 'Meijer',
    package_size: '15.1 oz Box (10 x 1.51 oz Packets)',
    department: 'grains_carbs' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'box (10 packets)',
    default_quantity: 1,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 160,
    protein_g: 4,
    carbs_g: 32,
    fat_g: 2,
    common_substitutes: [
      { name: 'Meijer Instant Oatmeal (Original / Plain, 12 Packets)', department: 'grains_carbs' as any, default_unit: 'box', conversion_ratio: 1.0, reason: 'Lower sugar plain instant oats' },
    ],
    icon_emoji: '🥣',
  },
  {
    id: 'meijer_frederiks_sourdough',
    name: "Frederik's by Meijer Artisan Sourdough Boule",
    brand: "Frederik's by Meijer",
    package_size: '18 oz Artisan Bakery Round',
    department: 'grains_carbs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'loaf',
    default_quantity: 1,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 130,
    protein_g: 4,
    carbs_g: 26,
    fat_g: 1,
    common_substitutes: [
      { name: 'True Goodness Organic Rolled Oats', department: 'grains_carbs' as any, default_unit: 'canister', conversion_ratio: 1.0, reason: 'Clean breakfast carbohydrate' },
    ],
    icon_emoji: '🍞',
  },
  {
    id: 'meijer_true_evoo',
    name: 'True Goodness Organic Extra Virgin Olive Oil (Cold-Extracted)',
    brand: 'True Goodness by Meijer',
    package_size: '16.9 fl oz Glass Bottle',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'bottle (16.9 oz)',
    default_quantity: 1,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 120,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 14,
    common_substitutes: [
      { name: 'True Goodness Organic Creamy Valencia Peanut Butter', department: 'nuts_fats_oils' as any, default_unit: 'jar', conversion_ratio: 1.0, reason: 'Healthy monounsaturated fat' },
    ],
    icon_emoji: '🫒',
  },
  {
    id: 'meijer_true_spinach',
    name: 'True Goodness Organic Baby Spinach (Triple Washed)',
    brand: 'True Goodness by Meijer',
    package_size: '16 oz (1 lb) Clamshell',
    department: 'vegetables' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'clamshell (16 oz)',
    default_quantity: 1,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 25,
    protein_g: 3,
    carbs_g: 4,
    fat_g: 0.5,
    common_substitutes: [
      { name: 'Meijer Steamable Fresh Cut Broccoli Florets (12 oz)', department: 'vegetables' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'Cruciferous greens' },
    ],
    icon_emoji: '🍃',
  },
  {
    id: 'meijer_true_apples',
    name: 'True Goodness Organic Honeycrisp Apples',
    brand: 'True Goodness by Meijer',
    package_size: '3 lb Tote Bag',
    department: 'fruits' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'bag (3 lbs)',
    default_quantity: 1,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 95,
    protein_g: 0.5,
    carbs_g: 25,
    fat_g: 0.3,
    common_substitutes: [
      { name: 'True Goodness Organic Frozen Blueberries (32 oz)', department: 'fruits' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'Anthocyanin antioxidant fruit' },
    ],
    icon_emoji: '🍎',
  },
  {
    id: 'meijer_true_blueberries',
    name: 'True Goodness Organic Frozen Blueberries',
    brand: 'True Goodness by Meijer',
    package_size: '32 oz (2 lb) Resealable Bag',
    department: 'fruits' as any,
    shelf_life: 'freezer_monthly',
    default_unit: 'bag (32 oz)',
    default_quantity: 1,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 80,
    protein_g: 1,
    carbs_g: 19,
    fat_g: 0.5,
    common_substitutes: [
      { name: 'True Goodness Organic Honeycrisp Apples (3 lbs)', department: 'fruits' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'Crisp fresh orchard fruit' },
    ],
    icon_emoji: '🫐',
  },
  {
    id: 'meijer_bone_broth',
    name: 'True Goodness Organic Grass-Fed Beef Bone Broth',
    brand: 'True Goodness by Meijer',
    package_size: '32 oz Carton',
    department: 'snacks_pantry' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'carton (32 oz)',
    default_quantity: 2,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 45,
    protein_g: 10,
    carbs_g: 1,
    fat_g: 0.5,
    common_substitutes: [
      { name: 'True Goodness Organic Chicken Broth', department: 'snacks_pantry' as any, default_unit: 'carton', conversion_ratio: 1.0, reason: 'Savory cooking stock' },
    ],
    icon_emoji: '🥣',
  },
  {
    id: 'meijer_instant_oatmeal_sf',
    name: 'Meijer Sugar Free Instant Oatmeal (Maple & Brown Sugar)',
    brand: 'Meijer',
    package_size: '12.1 oz Box (10 x 34g Packets)',
    department: 'grains_carbs' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'box (10 packets)',
    default_quantity: 1,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 120,
    protein_g: 4,
    carbs_g: 24,
    fat_g: 2,
    common_substitutes: [
      { name: 'Meijer Instant Oatmeal Maple & Brown Sugar', department: 'grains_carbs' as any, default_unit: 'box', conversion_ratio: 1.0, reason: 'Regular instant oatmeal' },
    ],
    icon_emoji: '🥣',
  },
  {
    id: 'meijer_100_whole_wheat_bread',
    name: 'Meijer 100% Whole Wheat Bread',
    brand: 'Meijer',
    package_size: '20 oz Loaf',
    department: 'grains_carbs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'loaf (20 oz)',
    default_quantity: 1,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 60,
    protein_g: 4,
    carbs_g: 12,
    fat_g: 0.5,
    common_substitutes: [
      { name: 'Meijer Classic White Sandwich Bread', department: 'grains_carbs' as any, default_unit: 'loaf', conversion_ratio: 1.0, reason: 'White bread' },
    ],
    icon_emoji: '🍞',
  },
  {
    id: 'meijer_white_sandwich_bread',
    name: 'Meijer Classic White Sandwich Bread',
    brand: 'Meijer',
    package_size: '20 oz Loaf',
    department: 'grains_carbs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'loaf (20 oz)',
    default_quantity: 1,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 70,
    protein_g: 2,
    carbs_g: 13,
    fat_g: 1,
    common_substitutes: [
      { name: 'Meijer 100% Whole Wheat Bread', department: 'grains_carbs' as any, default_unit: 'loaf', conversion_ratio: 1.0, reason: 'Whole grain alternative' },
    ],
    icon_emoji: '🍞',
  },
  {
    id: 'meijer_creamy_peanut_butter',
    name: 'Meijer Creamy Peanut Butter',
    brand: 'Meijer',
    package_size: '16 oz Jar',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'jar (16 oz)',
    default_quantity: 1,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 190,
    protein_g: 7,
    carbs_g: 7,
    fat_g: 16,
    common_substitutes: [
      { name: 'Meijer Crunchy Peanut Butter', department: 'nuts_fats_oils' as any, default_unit: 'jar', conversion_ratio: 1.0, reason: 'Crunchy style' },
    ],
    icon_emoji: '🥜',
  },
  {
    id: 'meijer_crunchy_peanut_butter',
    name: 'Meijer Crunchy Peanut Butter',
    brand: 'Meijer',
    package_size: '16 oz Jar',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'jar (16 oz)',
    default_quantity: 1,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 190,
    protein_g: 7,
    carbs_g: 7,
    fat_g: 16,
    common_substitutes: [
      { name: 'Meijer Creamy Peanut Butter', department: 'nuts_fats_oils' as any, default_unit: 'jar', conversion_ratio: 1.0, reason: 'Smooth texture' },
    ],
    icon_emoji: '🥜',
  },
  {
    id: 'meijer_salted_butter_sticks',
    name: 'Meijer Salted Butter (Sticks)',
    brand: 'Meijer',
    package_size: '16 oz (4 Sticks) Box',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'box (4 sticks)',
    default_quantity: 1,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 100,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 11,
    common_substitutes: [
      { name: 'Meijer Unsalted Butter (Sticks)', department: 'nuts_fats_oils' as any, default_unit: 'box', conversion_ratio: 1.0, reason: 'Sodium-free butter' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'meijer_unsalted_butter_sticks',
    name: 'Meijer Unsalted Butter (Sticks)',
    brand: 'Meijer',
    package_size: '16 oz (4 Sticks) Box',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'box (4 sticks)',
    default_quantity: 1,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 100,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 11,
    common_substitutes: [
      { name: 'Meijer Salted Butter (Sticks)', department: 'nuts_fats_oils' as any, default_unit: 'box', conversion_ratio: 1.0, reason: 'Salted table butter' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'meijer_butter_canola_tub',
    name: 'Meijer Butter with Canola Oil (Spreadable Tub)',
    brand: 'Meijer',
    package_size: '15 oz Tub',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'tub (15 oz)',
    default_quantity: 1,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 100,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 11,
    common_substitutes: [
      { name: 'Meijer Salted Butter Sticks', department: 'nuts_fats_oils' as any, default_unit: 'box', conversion_ratio: 1.0, reason: 'Baking sticks' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'meijer_oil_spread_tub',
    name: 'Meijer Original Vegetable Oil Spread (Tub)',
    brand: 'Meijer',
    package_size: '45 oz Tub',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'tub (45 oz)',
    default_quantity: 1,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 60,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 7,
    common_substitutes: [
      { name: 'Meijer Butter with Canola Oil (Tub)', department: 'nuts_fats_oils' as any, default_unit: 'tub', conversion_ratio: 1.0, reason: 'Rich butter spread' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'meijer_grape_jelly',
    name: 'Meijer Concord Grape Jelly',
    brand: 'Meijer',
    package_size: '30 oz Jar',
    department: 'snacks_pantry' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'jar (30 oz)',
    default_quantity: 1,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 50,
    protein_g: 0,
    carbs_g: 13,
    fat_g: 0,
    common_substitutes: [
      { name: 'Meijer Strawberry Jam', department: 'snacks_pantry' as any, default_unit: 'jar', conversion_ratio: 1.0, reason: 'Strawberry alternative' },
    ],
    icon_emoji: '🍇',
  },
  {
    id: 'meijer_strawberry_jam',
    name: 'Meijer Strawberry Jam',
    brand: 'Meijer',
    package_size: '30 oz Jar',
    department: 'snacks_pantry' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'jar (30 oz)',
    default_quantity: 1,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 50,
    protein_g: 0,
    carbs_g: 13,
    fat_g: 0,
    common_substitutes: [
      { name: 'Meijer Concord Grape Jelly', department: 'snacks_pantry' as any, default_unit: 'jar', conversion_ratio: 1.0, reason: 'Grape alternative' },
    ],
    icon_emoji: '🍓',
  },
  {
    id: 'meijer_strawberry_spread_sf',
    name: 'Meijer Sugar Free Strawberry Fruit Spread',
    brand: 'Meijer',
    package_size: '10 oz Jar',
    department: 'snacks_pantry' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'jar (10 oz)',
    default_quantity: 1,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 10,
    protein_g: 0,
    carbs_g: 5,
    fat_g: 0,
    common_substitutes: [
      { name: 'Meijer Strawberry Jam', department: 'snacks_pantry' as any, default_unit: 'jar', conversion_ratio: 1.0, reason: 'Traditional jam' },
    ],
    icon_emoji: '🍓',
  },
  {
    id: 'meijer_sugar_free_syrup',
    name: 'Meijer Sugar Free Pancake Syrup',
    brand: 'Meijer',
    package_size: '24 fl oz Bottle',
    department: 'snacks_pantry' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'bottle (24 oz)',
    default_quantity: 1,
    store_tags: ['meijer'],
    store_tag_primary: 'meijer',
    calories_per_serving: 20,
    protein_g: 0,
    carbs_g: 6,
    fat_g: 0,
    common_substitutes: [
      { name: 'Meijer 100% Pure Maple Syrup', department: 'snacks_pantry' as any, default_unit: 'bottle', conversion_ratio: 1.0, reason: 'Pure maple syrup' },
    ],
    icon_emoji: '🥞',
  },
];

// =========================================================================
// 4. COSTCO WHOLESALE (Kirkland Signature Bulk & Fresh)
// =========================================================================
export const COSTCO_PRODUCTS: StoreBrandProduct[] = [
  {
    id: 'costco_chicken_breast',
    name: 'Kirkland Signature Boneless Skinless Chicken Breasts',
    brand: 'Kirkland Signature (Costco)',
    package_size: '6.5 lb Vacuum Sealed Fresh Multi-Pack',
    department: 'poultry_meat' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'pack (6.5 lbs)',
    default_quantity: 1,
    store_tags: ['costco'],
    store_tag_primary: 'costco',
    calories_per_serving: 120,
    protein_g: 26,
    carbs_g: 0,
    fat_g: 1.5,
    common_substitutes: [
      { name: 'Kirkland Signature Wild Alaskan Sockeye Salmon', department: 'fish_seafood' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'Wild seafood alternative' },
    ],
    icon_emoji: '🍗',
  },
  {
    id: 'costco_organic_ground_beef',
    name: 'Kirkland Signature Organic 85/15 Ground Beef',
    brand: 'Kirkland Signature (Costco)',
    package_size: '3 x 1.34 lb Vacuum Packs (4 lbs total)',
    department: 'poultry_meat' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'pack (4 lbs)',
    default_quantity: 1,
    store_tags: ['costco'],
    store_tag_primary: 'costco',
    calories_per_serving: 240,
    protein_g: 21,
    carbs_g: 0,
    fat_g: 17,
    common_substitutes: [
      { name: 'Kirkland Signature Boneless Skinless Chicken Breasts', department: 'poultry_meat' as any, default_unit: 'pack', conversion_ratio: 1.0, reason: 'Lean poultry alternative' },
    ],
    icon_emoji: '🥩',
  },
  {
    id: 'costco_salmon',
    name: 'Kirkland Signature Wild Alaskan Sockeye Salmon Portions',
    brand: 'Kirkland Signature (Costco)',
    package_size: '3 lb Frozen Resealable Bag',
    department: 'fish_seafood' as any,
    shelf_life: 'freezer_monthly',
    default_unit: 'bag (3 lbs)',
    default_quantity: 1,
    store_tags: ['costco'],
    store_tag_primary: 'costco',
    calories_per_serving: 150,
    protein_g: 23,
    carbs_g: 0,
    fat_g: 6,
    common_substitutes: [
      { name: 'Kirkland Signature Raw Tail-On Jumbo Shrimp (2 lbs)', department: 'fish_seafood' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'Lean high-protein seafood' },
    ],
    icon_emoji: '🐟',
  },
  {
    id: 'costco_greek_yogurt',
    name: 'Kirkland Signature Organic Non-Fat Plain Greek Yogurt',
    brand: 'Kirkland Signature (Costco)',
    package_size: '48 oz (3 lbs) Tub',
    department: 'dairy_eggs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'tub (48 oz)',
    default_quantity: 1,
    store_tags: ['costco'],
    store_tag_primary: 'costco',
    calories_per_serving: 100,
    protein_g: 18,
    carbs_g: 6,
    fat_g: 0,
    common_substitutes: [
      { name: 'Kirkland Signature Organic Pasture-Raised Eggs', department: 'dairy_eggs' as any, default_unit: 'carton', conversion_ratio: 1.0, reason: 'Whole farm egg protein' },
    ],
    icon_emoji: '🥣',
  },
  {
    id: 'costco_organic_eggs',
    name: 'Kirkland Signature Organic Pasture-Raised Large Brown Eggs',
    brand: 'Kirkland Signature (Costco)',
    package_size: '2 x 18 Count (36 Eggs Total)',
    department: 'dairy_eggs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'pack (36 eggs)',
    default_quantity: 1,
    store_tags: ['costco'],
    store_tag_primary: 'costco',
    calories_per_serving: 70,
    protein_g: 6,
    carbs_g: 0,
    fat_g: 5,
    common_substitutes: [
      { name: 'Kirkland Signature Organic Non-Fat Plain Greek Yogurt', department: 'dairy_eggs' as any, default_unit: 'tub', conversion_ratio: 1.0, reason: 'High-protein cultured dairy' },
    ],
    icon_emoji: '🥚',
  },
  {
    id: 'costco_olive_oil',
    name: 'Kirkland Signature Organic Extra Virgin Olive Oil',
    brand: 'Kirkland Signature (Costco)',
    package_size: '2 Liter (67.6 fl oz) Bottle',
    department: 'healthy_fats' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'bottle (2L)',
    default_quantity: 1,
    store_tags: ['costco'],
    store_tag_primary: 'costco',
    calories_per_serving: 120,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 14,
    common_substitutes: [
      { name: 'Kirkland Signature Pure Avocado Oil (1 Liter)', department: 'healthy_fats' as any, default_unit: 'bottle', conversion_ratio: 1.0, reason: 'High-heat cooking oil' },
    ],
    icon_emoji: '🫒',
  },
  {
    id: 'costco_quinoa',
    name: 'Kirkland Signature Organic White Royal Quinoa',
    brand: 'Kirkland Signature (Costco)',
    package_size: '4.5 lb Bag',
    department: 'grains_bakery' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'bag (4.5 lbs)',
    default_quantity: 1,
    store_tags: ['costco'],
    store_tag_primary: 'costco',
    calories_per_serving: 170,
    protein_g: 6,
    carbs_g: 30,
    fat_g: 3,
    common_substitutes: [
      { name: 'Kirkland Signature Organic Jasmine Rice', department: 'grains_bakery' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'Clean fast-digesting carb' },
    ],
    icon_emoji: '🌾',
  },
  {
    id: 'costco_berries',
    name: 'Kirkland Signature Organic Three Berry Blend (Blueberries, Raspberries, Blackberries)',
    brand: 'Kirkland Signature (Costco)',
    package_size: '4 lb Frozen Bag',
    department: 'fruits' as any,
    shelf_life: 'freezer_monthly',
    default_unit: 'bag (4 lbs)',
    default_quantity: 1,
    store_tags: ['costco'],
    store_tag_primary: 'costco',
    calories_per_serving: 70,
    protein_g: 1,
    carbs_g: 15,
    fat_g: 0.5,
    common_substitutes: [
      { name: 'Kirkland Signature Organic Whole Strawberries (4 lbs)', department: 'fruits' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'Whole antioxidant fruit' },
    ],
    icon_emoji: '🫐',
  },
  {
    id: 'costco_organic_oatmeal',
    name: 'Kirkland Signature Organic Instant Oatmeal (Whole Grain Oats)',
    brand: 'Kirkland Signature (Costco)',
    package_size: '68 Count Bulk Box',
    department: 'grains_carbs' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'box (68 packets)',
    default_quantity: 1,
    store_tags: ['costco'],
    store_tag_primary: 'costco',
    calories_per_serving: 130,
    protein_g: 5,
    carbs_g: 25,
    fat_g: 2.5,
    common_substitutes: [
      { name: 'Kirkland Signature Organic White Quinoa', department: 'grains_bakery' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'Whole grain carb' },
    ],
    icon_emoji: '🥣',
  },
  {
    id: 'costco_whole_wheat_bread',
    name: 'Kirkland Signature 100% Whole Wheat Bread (Twin Pack)',
    brand: 'Kirkland Signature (Costco)',
    package_size: '2 x 24 oz Loaves',
    department: 'grains_carbs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'twin pack (2 loaves)',
    default_quantity: 1,
    store_tags: ['costco'],
    store_tag_primary: 'costco',
    calories_per_serving: 70,
    protein_g: 4,
    carbs_g: 13,
    fat_g: 1,
    common_substitutes: [
      { name: 'Kirkland Signature Country French Sourdough Bread', department: 'grains_carbs' as any, default_unit: 'loaf', conversion_ratio: 1.0, reason: 'Artisan sourdough' },
    ],
    icon_emoji: '🍞',
  },
  {
    id: 'costco_country_sourdough',
    name: 'Kirkland Signature Country French Sourdough Bread',
    brand: 'Kirkland Signature (Costco)',
    package_size: '24 oz Bakery Loaf',
    department: 'grains_carbs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'loaf (24 oz)',
    default_quantity: 1,
    store_tags: ['costco'],
    store_tag_primary: 'costco',
    calories_per_serving: 140,
    protein_g: 4,
    carbs_g: 28,
    fat_g: 0.5,
    common_substitutes: [
      { name: 'Kirkland Signature 100% Whole Wheat Bread', department: 'grains_carbs' as any, default_unit: 'twin pack', conversion_ratio: 0.5, reason: 'Whole grain bread' },
    ],
    icon_emoji: '🍞',
  },
  {
    id: 'costco_organic_peanut_butter',
    name: 'Kirkland Signature Organic Creamy Peanut Butter (Twin Pack)',
    brand: 'Kirkland Signature (Costco)',
    package_size: '2 x 28 oz Jars',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'pack (2 x 28 oz)',
    default_quantity: 1,
    store_tags: ['costco'],
    store_tag_primary: 'costco',
    calories_per_serving: 190,
    protein_g: 8,
    carbs_g: 6,
    fat_g: 16,
    common_substitutes: [
      { name: 'Kirkland Signature Creamy Almond Butter', department: 'nuts_fats_oils' as any, default_unit: 'jar', conversion_ratio: 1.0, reason: 'Tree nut butter' },
    ],
    icon_emoji: '🥜',
  },
  {
    id: 'costco_salted_butter_sticks',
    name: 'Kirkland Signature Salted Sweet Cream Butter (Sticks)',
    brand: 'Kirkland Signature (Costco)',
    package_size: '4 x 1 lb Boxes (16 Sticks total)',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'box (16 sticks)',
    default_quantity: 1,
    store_tags: ['costco'],
    store_tag_primary: 'costco',
    calories_per_serving: 100,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 11,
    common_substitutes: [
      { name: 'Kirkland Signature Unsalted Sweet Cream Butter', department: 'nuts_fats_oils' as any, default_unit: 'box', conversion_ratio: 1.0, reason: 'Unsalted baking butter' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'costco_unsalted_butter_sticks',
    name: 'Kirkland Signature Unsalted Sweet Cream Butter (Sticks)',
    brand: 'Kirkland Signature (Costco)',
    package_size: '4 x 1 lb Boxes (16 Sticks total)',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'box (16 sticks)',
    default_quantity: 1,
    store_tags: ['costco'],
    store_tag_primary: 'costco',
    calories_per_serving: 100,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 11,
    common_substitutes: [
      { name: 'Kirkland Signature Salted Sweet Cream Butter', department: 'nuts_fats_oils' as any, default_unit: 'box', conversion_ratio: 1.0, reason: 'Table butter' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'costco_grass_fed_butter_sticks',
    name: 'Kirkland Signature Grass-Fed Salted Butter (New Zealand Foil Sticks)',
    brand: 'Kirkland Signature (Costco)',
    package_size: '4 x 8 oz Foil Bars (2 lbs total)',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'pack (4 foil bars)',
    default_quantity: 1,
    store_tags: ['costco'],
    store_tag_primary: 'costco',
    calories_per_serving: 100,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 11,
    common_substitutes: [
      { name: 'Kerrygold Pure Irish Butter', department: 'nuts_fats_oils' as any, default_unit: 'pack', conversion_ratio: 1.0, reason: 'Imported grass-fed butter' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'costco_organic_strawberry_spread',
    name: 'Kirkland Signature Organic Strawberry Spread',
    brand: 'Kirkland Signature (Costco)',
    package_size: '42 oz Glass Jar',
    department: 'snacks_pantry' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'jar (42 oz)',
    default_quantity: 1,
    store_tags: ['costco'],
    store_tag_primary: 'costco',
    calories_per_serving: 40,
    protein_g: 0,
    carbs_g: 10,
    fat_g: 0,
    common_substitutes: [
      { name: 'Kirkland Signature 100% Pure Raw Honey', department: 'snacks_pantry' as any, default_unit: 'bottle', conversion_ratio: 0.8, reason: 'Raw sweetener' },
    ],
    icon_emoji: '🍓',
  },
];

// =========================================================================
// 5. WALMART (Great Value & Marketside Fresh)
// =========================================================================
export const WALMART_PRODUCTS: StoreBrandProduct[] = [
  {
    id: 'walmart_chicken_breast',
    name: 'Marketside All Natural Fresh Boneless Skinless Chicken Breasts',
    brand: 'Marketside (Walmart)',
    package_size: '3 lb Family Tray',
    department: 'poultry_meat' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'tray (3 lbs)',
    default_quantity: 1,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 120,
    protein_g: 26,
    carbs_g: 0,
    fat_g: 1.5,
    common_substitutes: [
      { name: 'Great Value 93/7 Lean Ground Beef (1 lb Roll)', department: 'poultry_meat' as any, default_unit: 'roll', conversion_ratio: 1.0, reason: 'Lean ground beef' },
    ],
    icon_emoji: '🍗',
  },
  {
    id: 'walmart_lean_beef',
    name: 'Great Value 93/7 All Natural Lean Ground Beef',
    brand: 'Great Value (Walmart)',
    package_size: '1 lb Roll',
    department: 'poultry_meat' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'roll (1 lb)',
    default_quantity: 2,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 170,
    protein_g: 24,
    carbs_g: 0,
    fat_g: 8,
    common_substitutes: [
      { name: 'Marketside All Natural Fresh Boneless Skinless Chicken Breasts', department: 'poultry_meat' as any, default_unit: 'tray', conversion_ratio: 1.0, reason: 'Lean poultry alternative' },
    ],
    icon_emoji: '🥩',
  },
  {
    id: 'walmart_greek_yogurt',
    name: 'Great Value Plain Nonfat Greek Yogurt',
    brand: 'Great Value (Walmart)',
    package_size: '32 oz Tub',
    department: 'dairy_eggs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'tub (32 oz)',
    default_quantity: 1,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 90,
    protein_g: 16,
    carbs_g: 6,
    fat_g: 0,
    common_substitutes: [
      { name: 'Great Value Large White Cage-Free Eggs (18 Count)', department: 'dairy_eggs' as any, default_unit: 'carton', conversion_ratio: 1.0, reason: 'Fresh whole eggs' },
    ],
    icon_emoji: '🥣',
  },
  {
    id: 'walmart_2pct_milk',
    name: 'Great Value 2% Reduced-Fat Milk',
    brand: 'Great Value (Walmart)',
    package_size: '1 Gallon Jug',
    department: 'dairy_eggs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'gallon',
    default_quantity: 1,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 120,
    protein_g: 8,
    carbs_g: 12,
    fat_g: 5,
    common_substitutes: [
      { name: 'Great Value Whole Vitamin D Milk (1 Gallon)', department: 'dairy_eggs' as any, default_unit: 'gallon', conversion_ratio: 1.0, reason: 'Rich whole dairy milk' },
    ],
    icon_emoji: '🥛',
  },
  {
    id: 'walmart_eggs',
    name: 'Great Value Large White Cage-Free Grade A Eggs',
    brand: 'Great Value (Walmart)',
    package_size: '18 Count Carton',
    department: 'dairy_eggs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'carton (18 eggs)',
    default_quantity: 1,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 70,
    protein_g: 6,
    carbs_g: 0,
    fat_g: 5,
    common_substitutes: [
      { name: 'Great Value 100% Pure Liquid Egg Whites (32 oz)', department: 'dairy_eggs' as any, default_unit: 'carton', conversion_ratio: 1.0, reason: 'Pure lean protein whites' },
    ],
    icon_emoji: '🥚',
  },
  {
    id: 'walmart_jasmine_rice',
    name: 'Great Value Authentic Thai Jasmine Rice',
    brand: 'Great Value (Walmart)',
    package_size: '5 lb Bag',
    department: 'grains_bakery' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'bag (5 lbs)',
    default_quantity: 1,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 160,
    protein_g: 3,
    carbs_g: 36,
    fat_g: 0,
    common_substitutes: [
      { name: 'Great Value 100% Whole Grain Brown Rice (5 lbs)', department: 'grains_bakery' as any, default_unit: 'bag', conversion_ratio: 1.0, reason: 'High-fiber whole grain' },
    ],
    icon_emoji: '🍚',
  },
  {
    id: 'walmart_frozen_broccoli',
    name: 'Great Value Steamable Broccoli Florets',
    brand: 'Great Value (Walmart)',
    package_size: '12 oz Steamable Bag',
    department: 'vegetables' as any,
    shelf_life: 'freezer_monthly',
    default_unit: 'bag (12 oz)',
    default_quantity: 2,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 30,
    protein_g: 3,
    carbs_g: 6,
    fat_g: 0,
    common_substitutes: [
      { name: 'Marketside Fresh Asparagus Spears (1 lb)', department: 'vegetables' as any, default_unit: 'bunch', conversion_ratio: 1.0, reason: 'Fresh tender spears' },
    ],
    icon_emoji: '🥦',
  },
  {
    id: 'walmart_olive_oil',
    name: 'Great Value 100% Extra Virgin Olive Oil',
    brand: 'Great Value (Walmart)',
    package_size: '16.9 fl oz (500 ml) Glass Bottle',
    department: 'healthy_fats' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'bottle (16.9 oz)',
    default_quantity: 1,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 120,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 14,
    common_substitutes: [
      { name: 'Great Value 100% Pure Avocado Oil (16.9 oz)', department: 'healthy_fats' as any, default_unit: 'bottle', conversion_ratio: 1.0, reason: 'High-heat cooking fat' },
    ],
    icon_emoji: '🫒',
  },
  {
    id: 'walmart_oatmeal_maple',
    name: 'Great Value Instant Oatmeal (Maple & Brown Sugar)',
    brand: 'Great Value (Walmart)',
    package_size: '15.1 oz Box (10 Packets)',
    department: 'grains_carbs' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'box (10 packets)',
    default_quantity: 1,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 160,
    protein_g: 4,
    carbs_g: 32,
    fat_g: 2,
    common_substitutes: [
      { name: 'Great Value Instant Oatmeal Original', department: 'grains_carbs' as any, default_unit: 'box', conversion_ratio: 1.0, reason: 'Plain oats' },
    ],
    icon_emoji: '🥣',
  },
  {
    id: 'walmart_oatmeal_original',
    name: 'Great Value Instant Oatmeal (Original / Plain)',
    brand: 'Great Value (Walmart)',
    package_size: '11.8 oz Box (12 Packets)',
    department: 'grains_carbs' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'box (12 packets)',
    default_quantity: 1,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 100,
    protein_g: 4,
    carbs_g: 19,
    fat_g: 2,
    common_substitutes: [
      { name: 'Great Value Rolled Oats', department: 'grains_carbs' as any, default_unit: 'canister', conversion_ratio: 1.0, reason: 'Bulk oats' },
    ],
    icon_emoji: '🥣',
  },
  {
    id: 'walmart_oatmeal_apples',
    name: 'Great Value Instant Oatmeal (Apples & Cinnamon)',
    brand: 'Great Value (Walmart)',
    package_size: '15.1 oz Box (10 Packets)',
    department: 'grains_carbs' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'box (10 packets)',
    default_quantity: 1,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 160,
    protein_g: 3,
    carbs_g: 33,
    fat_g: 2,
    common_substitutes: [
      { name: 'Great Value Instant Oatmeal Maple & Brown Sugar', department: 'grains_carbs' as any, default_unit: 'box', conversion_ratio: 1.0, reason: 'Maple flavor' },
    ],
    icon_emoji: '🥣',
  },
  {
    id: 'walmart_whole_wheat_bread',
    name: 'Great Value 100% Whole Wheat Bread',
    brand: 'Great Value (Walmart)',
    package_size: '20 oz Loaf',
    department: 'grains_carbs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'loaf (20 oz)',
    default_quantity: 1,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 60,
    protein_g: 4,
    carbs_g: 12,
    fat_g: 0.5,
    common_substitutes: [
      { name: 'Great Value White Sandwich Bread', department: 'grains_carbs' as any, default_unit: 'loaf', conversion_ratio: 1.0, reason: 'White bread' },
    ],
    icon_emoji: '🍞',
  },
  {
    id: 'walmart_white_bread',
    name: 'Great Value White Sandwich Bread',
    brand: 'Great Value (Walmart)',
    package_size: '20 oz Loaf',
    department: 'grains_carbs' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'loaf (20 oz)',
    default_quantity: 1,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 70,
    protein_g: 2,
    carbs_g: 13,
    fat_g: 1,
    common_substitutes: [
      { name: 'Great Value 100% Whole Wheat Bread', department: 'grains_carbs' as any, default_unit: 'loaf', conversion_ratio: 1.0, reason: 'Whole grain alternative' },
    ],
    icon_emoji: '🍞',
  },
  {
    id: 'walmart_creamy_peanut_butter',
    name: 'Great Value Creamy Peanut Butter',
    brand: 'Great Value (Walmart)',
    package_size: '16 oz Jar',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'jar (16 oz)',
    default_quantity: 1,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 190,
    protein_g: 7,
    carbs_g: 7,
    fat_g: 16,
    common_substitutes: [
      { name: 'Great Value Crunchy Peanut Butter', department: 'nuts_fats_oils' as any, default_unit: 'jar', conversion_ratio: 1.0, reason: 'Crunchy style' },
    ],
    icon_emoji: '🥜',
  },
  {
    id: 'walmart_crunchy_peanut_butter',
    name: 'Great Value Crunchy Peanut Butter',
    brand: 'Great Value (Walmart)',
    package_size: '16 oz Jar',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'jar (16 oz)',
    default_quantity: 1,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 190,
    protein_g: 7,
    carbs_g: 7,
    fat_g: 16,
    common_substitutes: [
      { name: 'Great Value Creamy Peanut Butter', department: 'nuts_fats_oils' as any, default_unit: 'jar', conversion_ratio: 1.0, reason: 'Smooth style' },
    ],
    icon_emoji: '🥜',
  },
  {
    id: 'walmart_salted_butter_sticks',
    name: 'Great Value Sweet Cream Salted Butter (Sticks)',
    brand: 'Great Value (Walmart)',
    package_size: '16 oz (4 Sticks) Box',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'box (4 sticks)',
    default_quantity: 1,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 100,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 11,
    common_substitutes: [
      { name: 'Great Value Sweet Cream Unsalted Butter', department: 'nuts_fats_oils' as any, default_unit: 'box', conversion_ratio: 1.0, reason: 'Sodium-free butter' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'walmart_unsalted_butter_sticks',
    name: 'Great Value Sweet Cream Unsalted Butter (Sticks)',
    brand: 'Great Value (Walmart)',
    package_size: '16 oz (4 Sticks) Box',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'box (4 sticks)',
    default_quantity: 1,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 100,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 11,
    common_substitutes: [
      { name: 'Great Value Sweet Cream Salted Butter', department: 'nuts_fats_oils' as any, default_unit: 'box', conversion_ratio: 1.0, reason: 'Salted butter' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'walmart_butter_canola_tub',
    name: 'Great Value Butter with Canola Oil (Spreadable Tub)',
    brand: 'Great Value (Walmart)',
    package_size: '15 oz Tub',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'tub (15 oz)',
    default_quantity: 1,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 100,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 11,
    common_substitutes: [
      { name: 'Great Value Salted Butter Sticks', department: 'nuts_fats_oils' as any, default_unit: 'box', conversion_ratio: 1.0, reason: 'Baking sticks' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'walmart_oil_spread_tub',
    name: 'Great Value Vegetable Oil Spread (Tub)',
    brand: 'Great Value (Walmart)',
    package_size: '45 oz Tub',
    department: 'nuts_fats_oils' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'tub (45 oz)',
    default_quantity: 1,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 60,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 7,
    common_substitutes: [
      { name: 'Great Value Butter with Canola Oil (Tub)', department: 'nuts_fats_oils' as any, default_unit: 'tub', conversion_ratio: 1.0, reason: 'Butterfat spread' },
    ],
    icon_emoji: '🧈',
  },
  {
    id: 'walmart_grape_jelly',
    name: 'Great Value Concord Grape Jelly',
    brand: 'Great Value (Walmart)',
    package_size: '30 oz Jar',
    department: 'snacks_pantry' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'jar (30 oz)',
    default_quantity: 1,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 50,
    protein_g: 0,
    carbs_g: 13,
    fat_g: 0,
    common_substitutes: [
      { name: 'Great Value Strawberry Preserves', department: 'snacks_pantry' as any, default_unit: 'jar', conversion_ratio: 1.0, reason: 'Strawberry preserve' },
    ],
    icon_emoji: '🍇',
  },
  {
    id: 'walmart_strawberry_preserves',
    name: 'Great Value Strawberry Preserves',
    brand: 'Great Value (Walmart)',
    package_size: '30 oz Jar',
    department: 'snacks_pantry' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'jar (30 oz)',
    default_quantity: 1,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 50,
    protein_g: 0,
    carbs_g: 13,
    fat_g: 0,
    common_substitutes: [
      { name: 'Great Value Concord Grape Jelly', department: 'snacks_pantry' as any, default_unit: 'jar', conversion_ratio: 1.0, reason: 'Grape jelly' },
    ],
    icon_emoji: '🍓',
  },
  {
    id: 'walmart_strawberry_preserves_sf',
    name: 'Great Value Sugar Free Strawberry Preserves',
    brand: 'Great Value (Walmart)',
    package_size: '10 oz Jar',
    department: 'snacks_pantry' as any,
    shelf_life: 'fresh_weekly',
    default_unit: 'jar (10 oz)',
    default_quantity: 1,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 10,
    protein_g: 0,
    carbs_g: 5,
    fat_g: 0,
    common_substitutes: [
      { name: 'Great Value Strawberry Preserves', department: 'snacks_pantry' as any, default_unit: 'jar', conversion_ratio: 1.0, reason: 'Traditional preserves' },
    ],
    icon_emoji: '🍓',
  },
  {
    id: 'walmart_sugar_free_syrup',
    name: 'Great Value Sugar Free Pancake Syrup',
    brand: 'Great Value (Walmart)',
    package_size: '24 fl oz Bottle',
    department: 'snacks_pantry' as any,
    shelf_life: 'pantry_monthly',
    default_unit: 'bottle (24 oz)',
    default_quantity: 1,
    store_tags: ['walmart'],
    store_tag_primary: 'walmart',
    calories_per_serving: 20,
    protein_g: 0,
    carbs_g: 6,
    fat_g: 0,
    common_substitutes: [
      { name: 'Great Value 100% Pure Maple Syrup', department: 'snacks_pantry' as any, default_unit: 'bottle', conversion_ratio: 1.0, reason: 'Pure maple syrup' },
    ],
    icon_emoji: '🥞',
  },
];

/**
 * Get products for a specific store
 */
export function getStoreSpecificProducts(store: 'sams_club' | 'aldi' | 'meijer' | 'costco' | 'walmart'): StoreBrandProduct[] {
  switch (store) {
    case 'sams_club':
      return SAMS_CLUB_PRODUCTS;
    case 'aldi':
      return ALDI_PRODUCTS;
    case 'meijer':
      return MEIJER_PRODUCTS;
    case 'costco':
      return COSTCO_PRODUCTS;
    case 'walmart':
      return WALMART_PRODUCTS;
  }
}
