import { FoodItem, RecipeItem, RecipeIngredient } from './types';

export interface WholesomeMeal {
  id: string;
  name: string;
  shortName: string;
  desc: string;
  cals: number;
  protein_g: number;
  carbs_g: number;
  fat_g: number;
  mealIndex: 1 | 2 | 3 | 4; // 1: Breakfast, 2: Lunch, 3: Dinner, 4: Snack
  category: 'breakfast' | 'lunch' | 'dinner' | 'snack';
  categoryLabel: string;
  foodName: string;
  grams: number;
  emoji: string;
  tags: string[];
  is_gluten_free: boolean;
  is_dairy_free: boolean;
  recipe: RecipeItem;
}

export const WHOLESOME_MEAL_CATALOG: WholesomeMeal[] = [
  // =========================================================================
  // BREAKFAST (Meal 1)
  // =========================================================================
  {
    id: 'oatmeal-berries',
    name: '🥣 Warm Berry & Almond Butter Oatmeal',
    shortName: 'Berry & Almond Oatmeal',
    desc: 'Slow-simmered rolled oats, fresh wild blueberries, and a dollop of raw almond butter',
    cals: 350,
    protein_g: 14,
    carbs_g: 54,
    fat_g: 10,
    mealIndex: 1,
    category: 'breakfast',
    categoryLabel: 'Breakfast • Meal 1',
    foodName: 'Rolled Oats with Wild Blueberries & Raw Almond Butter',
    grams: 220,
    emoji: '🥣',
    tags: ['Wholesome', 'High-Fiber', 'Whole Grain', 'Heart-Healthy'],
    is_gluten_free: true,
    is_dairy_free: true,
    recipe: {
      id: 'wholesome-oatmeal-berries',
      title: 'Warm Berry & Almond Butter Oatmeal',
      description: 'Slow-simmered whole rolled oats cooked with filtered water, wild blueberries, a pinch of cinnamon, and raw stoneground almond butter.',
      category: 'breakfast',
      sub_category: 'oats_pancakes',
      prep_time_minutes: 5,
      cook_time_minutes: 5,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'High-Fiber', 'Heart-Healthy', 'Dairy-Free'],
      calories_per_serving: 350,
      protein_g_per_serving: 14,
      carbs_g_per_serving: 54,
      fat_g_per_serving: 10,
      icon_emoji: '🥣',
      ingredients: [
        {
          name: 'Old Fashioned Rolled Oats',
          amount_imperial: '1 cup (dry)',
          amount_metric: '80g',
          raw_weight_grams_base: 80,
          calories_base: 240,
          protein_g_base: 9,
          carbs_g_base: 44,
          fat_g_base: 4,
          department: 'grains_bakery',
          food_category: 'grains_carbs',
        },
        {
          name: 'Fresh Wild Blueberries',
          amount_imperial: '1/2 cup',
          amount_metric: '75g',
          raw_weight_grams_base: 75,
          calories_base: 42,
          protein_g_base: 1,
          carbs_g_base: 10,
          fat_g_base: 0,
          department: 'produce',
          food_category: 'fruits',
        },
        {
          name: 'Raw Almond Butter',
          amount_imperial: '1 tbsp',
          amount_metric: '16g',
          raw_weight_grams_base: 16,
          calories_base: 95,
          protein_g_base: 3.5,
          carbs_g_base: 3,
          fat_g_base: 8,
          department: 'healthy_fats',
          food_category: 'nuts_fats_oils',
        },
        {
          name: 'Ground Cinnamon & Vanilla Extract',
          amount_imperial: '1/4 tsp each',
          amount_metric: '2g',
          raw_weight_grams_base: 2,
          calories_base: 5,
          protein_g_base: 0.5,
          carbs_g_base: 1,
          fat_g_base: 0,
          department: 'pantry_spices',
          food_category: 'pantry_staple',
        },
      ],
      instructions: [
        'Add rolled oats and 1 cup of water or unsweetened almond milk to a small saucepan over medium heat.',
        'Simmer gently for 4-5 minutes, stirring continuously until thick, creamy, and fragrant.',
        'Remove saucepan from heat and stir in ground cinnamon and vanilla extract.',
        'Pour into a bowl, scatter fresh blueberries across the top, and drizzle with creamy almond butter.',
      ],
      chef_notes: 'Blueberries provide powerful anthocyanin antioxidants while raw almond butter delivers slow-burning monounsaturated fats.',
    },
  },
  {
    id: 'mediterranean-shakshuka',
    name: '🍳 Mediterranean Shakshuka Skillet',
    shortName: 'Mediterranean Shakshuka',
    desc: '3 gently poached eggs in rich spiced tomato & bell pepper sauce with whole wheat pita',
    cals: 380,
    protein_g: 24,
    carbs_g: 22,
    fat_g: 22,
    mealIndex: 1,
    category: 'breakfast',
    categoryLabel: 'Breakfast • Meal 1',
    foodName: 'Mediterranean Shakshuka with Poached Eggs & Whole Wheat Pita',
    grams: 260,
    emoji: '🍳',
    tags: ['Wholesome', 'High-Protein', 'Low-Glycemic', 'Antioxidants'],
    is_gluten_free: false,
    is_dairy_free: false,
    recipe: {
      id: 'wholesome-mediterranean-shakshuka',
      title: 'Mediterranean Shakshuka with Poached Eggs & Whole Wheat Pita',
      description: 'Pasture-raised eggs gently poached in a rich, cumin-spiced crushed tomato and charred bell pepper sauce with crumbled sheep feta.',
      category: 'breakfast',
      sub_category: 'high_protein_eggs',
      prep_time_minutes: 10,
      cook_time_minutes: 15,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'High-Protein', 'Mediterranean', 'Whole Food'],
      calories_per_serving: 380,
      protein_g_per_serving: 24,
      carbs_g_per_serving: 22,
      fat_g_per_serving: 22,
      icon_emoji: '🍳',
      ingredients: [
        {
          name: 'Large Pasture-Raised Whole Eggs',
          amount_imperial: '3 whole',
          amount_metric: '150g',
          raw_weight_grams_base: 150,
          calories_base: 210,
          protein_g_base: 18,
          carbs_g_base: 1,
          fat_g_base: 15,
          department: 'dairy_eggs',
          food_category: 'dairy_eggs',
        },
        {
          name: 'Canned Crushed San Marzano Tomatoes',
          amount_imperial: '3/4 cup (6 oz)',
          amount_metric: '180g',
          raw_weight_grams_base: 180,
          calories_base: 40,
          protein_g_base: 2,
          carbs_g_base: 8,
          fat_g_base: 0,
          department: 'pantry_spices',
          food_category: 'vegetables',
        },
        {
          name: 'Diced Bell Pepper & Red Onions',
          amount_imperial: '1/2 cup mix',
          amount_metric: '75g',
          raw_weight_grams_base: 75,
          calories_base: 25,
          protein_g_base: 1,
          carbs_g_base: 5,
          fat_g_base: 0,
          department: 'produce',
          food_category: 'vegetables',
        },
        {
          name: 'Crumbled Greek Feta Cheese',
          amount_imperial: '2 tbsp (1 oz)',
          amount_metric: '28g',
          raw_weight_grams_base: 28,
          calories_base: 75,
          protein_g_base: 4,
          carbs_g_base: 1,
          fat_g_base: 6,
          department: 'dairy_eggs',
          food_category: 'dairy_eggs',
        },
        {
          name: 'Whole Wheat Pita Pocket',
          amount_imperial: '1/2 whole pocket',
          amount_metric: '25g',
          raw_weight_grams_base: 25,
          calories_base: 65,
          protein_g_base: 3,
          carbs_g_base: 13,
          fat_g_base: 0.5,
          department: 'grains_bakery',
          food_category: 'grains_carbs',
        },
      ],
      instructions: [
        'Sauté diced peppers and onions in a non-stick skillet with olive oil spray for 3 minutes until softened.',
        'Stir in crushed tomatoes, ground cumin, smoked paprika, minced garlic, sea salt, and black pepper; simmer for 4 minutes.',
        'Use a wooden spoon to create 3 wells in the sauce and crack the eggs gently into each well.',
        'Cover with a lid and simmer over medium-low heat for 6-7 minutes until whites are firm and yolks remain jammy.',
        'Garnish with crumbled feta and fresh cilantro. Dip warm toasted pita directly into the skillet.',
      ],
      chef_notes: 'Runny yolks combine with the spiced tomato reduction to form a natural rich sauce without excess oil.',
    },
  },
  {
    id: 'greek-yogurt-parfait',
    name: '🍓 Greek Yogurt & Strawberry Honey Parfait',
    shortName: 'Greek Yogurt Parfait',
    desc: 'Creamy non-fat Greek yogurt, fresh strawberries, chia seeds, and raw clover honey',
    cals: 220,
    protein_g: 22,
    carbs_g: 26,
    fat_g: 2,
    mealIndex: 1,
    category: 'breakfast',
    categoryLabel: 'Breakfast • Meal 1',
    foodName: 'Nonfat Greek Yogurt Parfait with Strawberries & Honey',
    grams: 200,
    emoji: '🍓',
    tags: ['Wholesome', 'High-Protein', 'Gut Health', 'Probiotics'],
    is_gluten_free: true,
    is_dairy_free: false,
    recipe: {
      id: 'wholesome-greek-yogurt-parfait',
      title: 'Greek Yogurt & Strawberry Honey Parfait',
      description: 'Strained nonfat Greek yogurt layered with sliced ripe strawberries, organic black chia seeds, and raw clover honey.',
      category: 'breakfast',
      sub_category: 'smoothies_bowls',
      prep_time_minutes: 5,
      cook_time_minutes: 0,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'High-Protein', 'Probiotic', 'Quick Grab'],
      calories_per_serving: 220,
      protein_g_per_serving: 22,
      carbs_g_per_serving: 26,
      fat_g_per_serving: 2,
      icon_emoji: '🍓',
      ingredients: [
        {
          name: 'Plain Nonfat Greek Yogurt (0%)',
          amount_imperial: '3/4 cup (6 oz)',
          amount_metric: '170g',
          raw_weight_grams_base: 170,
          calories_base: 130,
          protein_g_base: 19,
          carbs_g_base: 6,
          fat_g_base: 0,
          department: 'dairy_eggs',
          food_category: 'dairy_eggs',
        },
        {
          name: 'Fresh Sliced Strawberries',
          amount_imperial: '1/2 cup',
          amount_metric: '75g',
          raw_weight_grams_base: 75,
          calories_base: 25,
          protein_g_base: 0.5,
          carbs_g_base: 6,
          fat_g_base: 0,
          department: 'produce',
          food_category: 'fruits',
        },
        {
          name: 'Raw Clover Honey',
          amount_imperial: '1 tsp',
          amount_metric: '7g',
          raw_weight_grams_base: 7,
          calories_base: 22,
          protein_g_base: 0,
          carbs_g_base: 6,
          fat_g_base: 0,
          department: 'pantry_spices',
          food_category: 'pantry_staple',
        },
        {
          name: 'Organic Black Chia Seeds',
          amount_imperial: '1 tsp',
          amount_metric: '5g',
          raw_weight_grams_base: 5,
          calories_base: 25,
          protein_g_base: 1,
          carbs_g_base: 2,
          fat_g_base: 1.5,
          department: 'healthy_fats',
          food_category: 'nuts_fats_oils',
        },
      ],
      instructions: [
        'Spoon plain Greek yogurt into a glass cup or bowl.',
        'Arrange fresh sliced strawberries evenly across the top.',
        'Drizzle raw clover honey over the fruit and sprinkle with organic chia seeds.',
        'Enjoy chilled immediately or chill in the fridge for an easy grab-and-go morning bowl.',
      ],
      chef_notes: '0% Greek yogurt packs over 19g of pure casein and whey protein with zero added sugars.',
    },
  },
  {
    id: 'protein-oat-pancakes',
    name: '🥞 Golden High-Protein Oat Pancakes',
    shortName: 'Protein Oat Pancakes',
    desc: 'Ground whole oat & egg white flapjacks served with warm cinnamon apple slices',
    cals: 390,
    protein_g: 32,
    carbs_g: 44,
    fat_g: 8,
    mealIndex: 1,
    category: 'breakfast',
    categoryLabel: 'Breakfast • Meal 1',
    foodName: 'High-Protein Oat Pancakes with Warm Cinnamon Apples',
    grams: 240,
    emoji: '🥞',
    tags: ['Wholesome', 'High-Protein', 'Complex Carbs', 'Clean Fuel'],
    is_gluten_free: true,
    is_dairy_free: true,
    recipe: {
      id: 'wholesome-protein-oat-pancakes',
      title: 'Golden High-Protein Oat Pancakes',
      description: 'Blended whole rolled oats, egg whites, and vanilla protein batter griddled golden brown, served with sautéed cinnamon apples.',
      category: 'breakfast',
      sub_category: 'oats_pancakes',
      prep_time_minutes: 5,
      cook_time_minutes: 8,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'High-Protein', 'Gluten-Free', 'Post-Workout'],
      calories_per_serving: 390,
      protein_g_per_serving: 32,
      carbs_g_per_serving: 44,
      fat_g_per_serving: 8,
      icon_emoji: '🥞',
      ingredients: [
        {
          name: 'Rolled Oats (ground to flour)',
          amount_imperial: '1/2 cup (dry)',
          amount_metric: '40g',
          raw_weight_grams_base: 40,
          calories_base: 150,
          protein_g_base: 5,
          carbs_g_base: 27,
          fat_g_base: 2.5,
          department: 'grains_bakery',
          food_category: 'grains_carbs',
        },
        {
          name: 'Liquid Egg Whites',
          amount_imperial: '1/2 cup',
          amount_metric: '120g',
          raw_weight_grams_base: 120,
          calories_base: 60,
          protein_g_base: 13,
          carbs_g_base: 1,
          fat_g_base: 0,
          department: 'dairy_eggs',
          food_category: 'dairy_eggs',
        },
        {
          name: 'Vanilla Whey Protein Isolate',
          amount_imperial: '1/2 scoop',
          amount_metric: '15g',
          raw_weight_grams_base: 15,
          calories_base: 60,
          protein_g_base: 12,
          carbs_g_base: 1,
          fat_g_base: 0.5,
          department: 'supplements',
          food_category: 'protein',
        },
        {
          name: 'Sliced Gala Apple',
          amount_imperial: '1/2 apple',
          amount_metric: '60g',
          raw_weight_grams_base: 60,
          calories_base: 40,
          protein_g_base: 0.3,
          carbs_g_base: 10,
          fat_g_base: 0.2,
          department: 'produce',
          food_category: 'fruits',
        },
        {
          name: 'Virgin Coconut Oil (for pan)',
          amount_imperial: '1/2 tsp',
          amount_metric: '2.5g',
          raw_weight_grams_base: 2.5,
          calories_base: 22,
          protein_g_base: 0,
          carbs_g_base: 0,
          fat_g_base: 2.5,
          department: 'healthy_fats',
          food_category: 'nuts_fats_oils',
        },
      ],
      instructions: [
        'Blend rolled oats, egg whites, whey protein, and 2 tbsp water in a blender for 30 seconds into smooth batter.',
        'Heat a non-stick skillet over medium-low heat with coconut oil.',
        'Pour 3 medium rounds and cook for 2-3 minutes until bubbles appear on the surface.',
        'Flip gently and cook for 1-2 minutes until golden on both sides.',
        'Warm sliced apples in the pan with a dusting of cinnamon and serve over the stack.',
      ],
      chef_notes: 'Grinding oats creates a light, fluffy pancake without processed white flour or refined syrups.',
    },
  },
  {
    id: 'avocado-egg-toast',
    name: '🥑 Smashed Avocado & Sunny Egg Toast',
    shortName: 'Avocado & Egg Toast',
    desc: 'Artisan sourdough slice, fresh crushed Hass avocado, and two pasture-raised sunny eggs',
    cals: 360,
    protein_g: 18,
    carbs_g: 32,
    fat_g: 18,
    mealIndex: 1,
    category: 'breakfast',
    categoryLabel: 'Breakfast • Meal 1',
    foodName: 'Sourdough Toast with Smashed Avocado & Pasture Eggs',
    grams: 190,
    emoji: '🥑',
    tags: ['Wholesome', 'Healthy Fats', 'Whole Food', 'Balanced'],
    is_gluten_free: false,
    is_dairy_free: true,
    recipe: {
      id: 'wholesome-avocado-egg-toast',
      title: 'Smashed Avocado & Sunny Pasture Egg Sourdough Toast',
      description: 'Slow-fermented artisan sourdough toasted crisp, topped with lime-mashed ripe Hass avocado and two sunny pasture eggs.',
      category: 'breakfast',
      sub_category: 'quick_grab_go',
      prep_time_minutes: 5,
      cook_time_minutes: 5,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'Healthy Fats', 'Whole Food', 'Clean Nutrition'],
      calories_per_serving: 360,
      protein_g_per_serving: 18,
      carbs_g_per_serving: 32,
      fat_g_per_serving: 18,
      icon_emoji: '🥑',
      ingredients: [
        {
          name: 'Artisan Sourdough Bread Slice',
          amount_imperial: '1 slice (thick cut)',
          amount_metric: '45g',
          raw_weight_grams_base: 45,
          calories_base: 120,
          protein_g_base: 4,
          carbs_g_base: 24,
          fat_g_base: 1,
          department: 'grains_bakery',
          food_category: 'grains_carbs',
        },
        {
          name: 'Ripe Hass Avocado',
          amount_imperial: '1/3 whole avocado',
          amount_metric: '50g',
          raw_weight_grams_base: 50,
          calories_base: 80,
          protein_g_base: 1,
          carbs_g_base: 4,
          fat_g_base: 7.5,
          department: 'produce',
          food_category: 'fruits',
        },
        {
          name: 'Large Pasture-Raised Whole Eggs',
          amount_imperial: '2 whole',
          amount_metric: '100g',
          raw_weight_grams_base: 100,
          calories_base: 140,
          protein_g_base: 12,
          carbs_g_base: 1,
          fat_g_base: 10,
          department: 'dairy_eggs',
          food_category: 'dairy_eggs',
        },
        {
          name: 'Crushed Red Pepper Flakes & Flaky Sea Salt',
          amount_imperial: '1 pinch',
          amount_metric: '1g',
          raw_weight_grams_base: 1,
          calories_base: 2,
          protein_g_base: 0.1,
          carbs_g_base: 0.3,
          fat_g_base: 0,
          department: 'pantry_spices',
          food_category: 'pantry_staple',
        },
      ],
      instructions: [
        'Toast the sourdough slice until golden and crunchy.',
        'Mash the ripe avocado with a squeeze of fresh lemon or lime juice and a pinch of salt.',
        'Heat a skillet with olive oil spray and fry the two eggs sunny-side up for 3 minutes until whites are set.',
        'Spread the mashed avocado over the toasted sourdough, top with eggs, and finish with red pepper flakes.',
      ],
      chef_notes: 'Naturally fermented sourdough is gentle on digestion and has a lower glycemic response than commercial wheat bread.',
    },
  },
  {
    id: 'green-superfood-smoothie',
    name: '🥤 Green Spinach & Protein Super Shake',
    shortName: 'Green Superfood Shake',
    desc: 'Baby spinach, ripe banana, vanilla whey isolate, and cold filtered almond milk',
    cals: 280,
    protein_g: 28,
    carbs_g: 30,
    fat_g: 4,
    mealIndex: 1,
    category: 'breakfast',
    categoryLabel: 'Breakfast • Meal 1',
    foodName: 'Spinach Banana Protein Super Shake',
    grams: 350,
    emoji: '🥤',
    tags: ['Wholesome', 'Fast Digestion', 'Micronutrients', 'High-Protein'],
    is_gluten_free: true,
    is_dairy_free: true,
    recipe: {
      id: 'wholesome-green-superfood-smoothie',
      title: 'Green Spinach & Vanilla Protein Super Shake',
      description: 'Cold blended baby spinach, ripe sweet banana, vanilla whey isolate, and unsweetened almond milk for fast morning nutrition.',
      category: 'breakfast',
      sub_category: 'smoothies_bowls',
      prep_time_minutes: 3,
      cook_time_minutes: 0,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'Green Fuel', 'High-Protein', 'Quick'],
      calories_per_serving: 280,
      protein_g_per_serving: 28,
      carbs_g_per_serving: 30,
      fat_g_per_serving: 4,
      icon_emoji: '🥤',
      ingredients: [
        {
          name: 'Fresh Organic Baby Spinach',
          amount_imperial: '2 cups packed',
          amount_metric: '60g',
          raw_weight_grams_base: 60,
          calories_base: 15,
          protein_g_base: 2,
          carbs_g_base: 2,
          fat_g_base: 0,
          department: 'produce',
          food_category: 'vegetables',
        },
        {
          name: 'Ripe Yellow Banana',
          amount_imperial: '1 medium',
          amount_metric: '110g',
          raw_weight_grams_base: 110,
          calories_base: 105,
          protein_g_base: 1.3,
          carbs_g_base: 27,
          fat_g_base: 0.3,
          department: 'produce',
          food_category: 'fruits',
        },
        {
          name: 'Vanilla Whey Protein Isolate',
          amount_imperial: '1 scoop',
          amount_metric: '30g',
          raw_weight_grams_base: 30,
          calories_base: 120,
          protein_g_base: 24,
          carbs_g_base: 2,
          fat_g_base: 1,
          department: 'supplements',
          food_category: 'protein',
        },
        {
          name: 'Unsweetened Vanilla Almond Milk',
          amount_imperial: '1 cup',
          amount_metric: '240ml',
          raw_weight_grams_base: 240,
          calories_base: 35,
          protein_g_base: 1,
          carbs_g_base: 1,
          fat_g_base: 2.5,
          department: 'dairy_eggs',
          food_category: 'dairy_alternative',
        },
      ],
      instructions: [
        'Add almond milk and fresh baby spinach to the blender cup first.',
        'Blend on high for 20 seconds to liquefy the greens smoothly.',
        'Add ripe banana, whey protein isolate, and 3 ice cubes.',
        'Blend on high for 30 seconds until frosty, silky, and electric green.',
      ],
      chef_notes: 'Blending the greens with almond milk first breaks down cell walls so you get a smooth texture without gritty leafy bits.',
    },
  },
  {
    id: 'veggie-egg-scramble',
    name: '🍳 Spinach, Mushroom & Feta Scramble',
    shortName: 'Spinach & Feta Scramble',
    desc: 'Fluffy whole eggs scrambled with tender baby spinach, cremini mushrooms, and crumbly feta',
    cals: 320,
    protein_g: 26,
    carbs_g: 10,
    fat_g: 20,
    mealIndex: 1,
    category: 'breakfast',
    categoryLabel: 'Breakfast • Meal 1',
    foodName: 'Farm Fresh Egg Scramble with Spinach, Mushrooms & Feta',
    grams: 230,
    emoji: '🍳',
    tags: ['Wholesome', 'Low-Carb', 'Keto-Friendly', 'High-Protein'],
    is_gluten_free: true,
    is_dairy_free: false,
    recipe: {
      id: 'wholesome-veggie-egg-scramble',
      title: 'Spinach, Cremini Mushroom & Feta Farm Scramble',
      description: 'Fresh cracked whole eggs and egg whites softly scrambled with sliced baby bella mushrooms, wilted spinach, and crumbled feta.',
      category: 'breakfast',
      sub_category: 'high_protein_eggs',
      prep_time_minutes: 5,
      cook_time_minutes: 6,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'Low-Carb', 'Keto-Friendly', 'High-Protein'],
      calories_per_serving: 320,
      protein_g_per_serving: 26,
      carbs_g_per_serving: 10,
      fat_g_per_serving: 20,
      icon_emoji: '🍳',
      ingredients: [
        {
          name: 'Large Whole Eggs',
          amount_imperial: '2 whole',
          amount_metric: '100g',
          raw_weight_grams_base: 100,
          calories_base: 140,
          protein_g_base: 12,
          carbs_g_base: 1,
          fat_g_base: 10,
          department: 'dairy_eggs',
          food_category: 'dairy_eggs',
        },
        {
          name: 'Liquid Egg Whites',
          amount_imperial: '1/3 cup',
          amount_metric: '80g',
          raw_weight_grams_base: 80,
          calories_base: 40,
          protein_g_base: 9,
          carbs_g_base: 0.5,
          fat_g_base: 0,
          department: 'dairy_eggs',
          food_category: 'dairy_eggs',
        },
        {
          name: 'Sliced Cremini Mushrooms',
          amount_imperial: '1/2 cup',
          amount_metric: '40g',
          raw_weight_grams_base: 40,
          calories_base: 15,
          protein_g_base: 1.5,
          carbs_g_base: 2,
          fat_g_base: 0.2,
          department: 'produce',
          food_category: 'vegetables',
        },
        {
          name: 'Baby Spinach',
          amount_imperial: '1.5 cups',
          amount_metric: '45g',
          raw_weight_grams_base: 45,
          calories_base: 10,
          protein_g_base: 1.3,
          carbs_g_base: 1.6,
          fat_g_base: 0.2,
          department: 'produce',
          food_category: 'vegetables',
        },
        {
          name: 'Crumbled Sheep Feta Cheese',
          amount_imperial: '2 tbsp',
          amount_metric: '28g',
          raw_weight_grams_base: 28,
          calories_base: 75,
          protein_g_base: 4,
          carbs_g_base: 1,
          fat_g_base: 6,
          department: 'dairy_eggs',
          food_category: 'dairy_eggs',
        },
      ],
      instructions: [
        'Whisk whole eggs and egg whites together in a bowl with a pinch of black pepper.',
        'Sauté sliced mushrooms in a non-stick skillet over medium heat for 3 minutes until lightly browned.',
        'Toss in baby spinach and stir for 45 seconds until wilted.',
        'Pour in eggs and gently push with a spatula over low heat until soft curds form (about 2 minutes).',
        'Fold in crumbled feta right before removing from heat so it softens without melting away.',
      ],
      chef_notes: 'Combining whole eggs with egg whites keeps the healthy choline and micronutrients while boosting the protein ratio.',
    },
  },

  // =========================================================================
  // LUNCH (Meal 2)
  // =========================================================================
  {
    id: 'grilled-chicken-power-bowl',
    name: '🥗 Grilled Chicken & Jasmine Rice Power Bowl',
    shortName: 'Chicken Jasmine Power Bowl',
    desc: 'Charred chicken breast, fragrant jasmine rice, steamed broccoli florets & sesame seeds',
    cals: 520,
    protein_g: 44,
    carbs_g: 56,
    fat_g: 12,
    mealIndex: 2,
    category: 'lunch',
    categoryLabel: 'Lunch • Meal 2',
    foodName: 'Grilled Chicken Breast with Jasmine Rice & Steamed Broccoli',
    grams: 320,
    emoji: '🥗',
    tags: ['Wholesome', 'Athlete Macro Gold', 'Lean Protein', 'Clean Carbs'],
    is_gluten_free: true,
    is_dairy_free: true,
    recipe: {
      id: 'wholesome-grilled-chicken-power-bowl',
      title: 'Grilled Chicken & Jasmine Rice Power Bowl',
      description: 'Char-grilled chicken breast seasoned with garlic herbs, served over fragrant steamed jasmine rice and crisp broccoli with toasted sesame seeds.',
      category: 'lunch',
      sub_category: 'power_bowls',
      prep_time_minutes: 10,
      cook_time_minutes: 12,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'High-Protein', 'Clean Fuel', 'Meal Prep Classic'],
      calories_per_serving: 520,
      protein_g_per_serving: 44,
      carbs_g_per_serving: 56,
      fat_g_per_serving: 12,
      icon_emoji: '🥗',
      ingredients: [
        {
          name: 'Boneless Skinless Chicken Breast',
          amount_imperial: '6 oz',
          amount_metric: '170g',
          raw_weight_grams_base: 170,
          calories_base: 220,
          protein_g_base: 38,
          carbs_g_base: 0,
          fat_g_base: 5,
          department: 'meat_seafood',
          food_category: 'poultry_meat',
        },
        {
          name: 'Steamed Jasmine Rice',
          amount_imperial: '1 cup (cooked)',
          amount_metric: '150g',
          raw_weight_grams_base: 150,
          calories_base: 205,
          protein_g_base: 4,
          carbs_g_base: 45,
          fat_g_base: 0.5,
          department: 'grains_bakery',
          food_category: 'grains_carbs',
        },
        {
          name: 'Fresh Broccoli Florets',
          amount_imperial: '1.5 cups',
          amount_metric: '100g',
          raw_weight_grams_base: 100,
          calories_base: 35,
          protein_g_base: 2.5,
          carbs_g_base: 7,
          fat_g_base: 0.4,
          department: 'produce',
          food_category: 'vegetables',
        },
        {
          name: 'Toasted Sesame Oil & Tamari Sauce',
          amount_imperial: '1.5 tsp',
          amount_metric: '7g',
          raw_weight_grams_base: 7,
          calories_base: 55,
          protein_g_base: 0.5,
          carbs_g_base: 1,
          fat_g_base: 6,
          department: 'healthy_fats',
          food_category: 'nuts_fats_oils',
        },
      ],
      instructions: [
        'Season chicken breast with garlic powder, onion powder, and smoked paprika.',
        'Grill or sear in a hot skillet for 5-6 minutes per side until internal temperature reaches 165°F.',
        'Steam broccoli florets in a covered pot with 2 tbsp water for 3-4 minutes until bright green and tender-crisp.',
        'Slice chicken against the grain. Scoop warm jasmine rice into a bowl, arrange chicken and broccoli alongside, and drizzle with sesame tamari.',
      ],
      chef_notes: 'The golden ratio of clean bodybuilding and athletic nutrition: lean protein, fast-digesting starch, and sulfur-rich brassica greens.',
    },
  },
  {
    id: 'turkey-avocado-sourdough',
    name: '🥪 Roasted Turkey & Avocado Sourdough',
    shortName: 'Turkey & Avocado Sourdough',
    desc: 'Deli-style roasted turkey breast, ripe avocado, crisp arugula & stoneground mustard',
    cals: 420,
    protein_g: 34,
    carbs_g: 38,
    fat_g: 14,
    mealIndex: 2,
    category: 'lunch',
    categoryLabel: 'Lunch • Meal 2',
    foodName: 'Roasted Turkey Breast & Avocado Sourdough Sandwich',
    grams: 240,
    emoji: '🥪',
    tags: ['Wholesome', 'Quick Prep', 'High-Protein', 'Comforting'],
    is_gluten_free: false,
    is_dairy_free: true,
    recipe: {
      id: 'wholesome-turkey-avocado-sourdough',
      title: 'Roasted Turkey & Avocado Sourdough Sandwich',
      description: 'Sliced lean roasted turkey breast stacked with ripe avocado, wild arugula, and coarse stoneground mustard on toasted sourdough.',
      category: 'lunch',
      sub_category: 'wraps_sandwiches',
      prep_time_minutes: 5,
      cook_time_minutes: 2,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'Quick Lunch', 'High-Protein', 'Lean'],
      calories_per_serving: 420,
      protein_g_per_serving: 34,
      carbs_g_per_serving: 38,
      fat_g_per_serving: 14,
      icon_emoji: '🥪',
      ingredients: [
        {
          name: 'Roasted Turkey Breast (Deli or Home-Cooked)',
          amount_imperial: '5 oz',
          amount_metric: '140g',
          raw_weight_grams_base: 140,
          calories_base: 160,
          protein_g_base: 30,
          carbs_g_base: 1,
          fat_g_base: 2,
          department: 'meat_seafood',
          food_category: 'poultry_meat',
        },
        {
          name: 'Artisan Sourdough Bread Slices',
          amount_imperial: '2 slices',
          amount_metric: '60g',
          raw_weight_grams_base: 60,
          calories_base: 160,
          protein_g_base: 5,
          carbs_g_base: 32,
          fat_g_base: 1,
          department: 'grains_bakery',
          food_category: 'grains_carbs',
        },
        {
          name: 'Ripe Hass Avocado',
          amount_imperial: '1/3 whole avocado',
          amount_metric: '50g',
          raw_weight_grams_base: 50,
          calories_base: 80,
          protein_g_base: 1,
          carbs_g_base: 4,
          fat_g_base: 7.5,
          department: 'produce',
          food_category: 'fruits',
        },
        {
          name: 'Baby Arugula & Stoneground Mustard',
          amount_imperial: '1/2 cup + 1 tbsp',
          amount_metric: '30g',
          raw_weight_grams_base: 30,
          calories_base: 20,
          protein_g_base: 1,
          carbs_g_base: 2,
          fat_g_base: 0.5,
          department: 'produce',
          food_category: 'vegetables',
        },
      ],
      instructions: [
        'Lightly toast sourdough slices until firm.',
        'Spread mashed avocado on one slice and stoneground mustard on the other.',
        'Stack the sliced roasted turkey breast and top with fresh baby arugula.',
        'Close sandwich, slice diagonally, and enjoy with chilled mineral water.',
      ],
      chef_notes: 'Replacing mayonnaise with nutrient-dense mashed avocado cuts saturated fat and infuses oleic fatty acids.',
    },
  },
  {
    id: 'southwest-fajita-bowl',
    name: '🌯 Southwest Chicken & Black Bean Bowl',
    shortName: 'Southwest Fajita Bowl',
    desc: 'Grilled spiced chicken, black beans, sweet corn, charred bell peppers & fire-roasted salsa',
    cals: 480,
    protein_g: 40,
    carbs_g: 52,
    fat_g: 13,
    mealIndex: 2,
    category: 'lunch',
    categoryLabel: 'Lunch • Meal 2',
    foodName: 'Southwest Spiced Chicken & Black Bean Bowl',
    grams: 330,
    emoji: '🌯',
    tags: ['Wholesome', 'High-Fiber', 'Flavor Packed', 'Lean Protein'],
    is_gluten_free: true,
    is_dairy_free: true,
    recipe: {
      id: 'wholesome-southwest-fajita-bowl',
      title: 'Southwest Chicken, Black Bean & Charred Pepper Bowl',
      description: 'Chili-lime chicken breast, organic black beans, sweet corn, and blistered fajita bell peppers topped with cilantro and fire-roasted salsa.',
      category: 'lunch',
      sub_category: 'power_bowls',
      prep_time_minutes: 10,
      cook_time_minutes: 10,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'High-Fiber', 'Lean Protein', 'Gluten-Free'],
      calories_per_serving: 480,
      protein_g_per_serving: 40,
      carbs_g_per_serving: 52,
      fat_g_per_serving: 13,
      icon_emoji: '🌯',
      ingredients: [
        {
          name: 'Chili-Spiced Chicken Breast',
          amount_imperial: '5 oz',
          amount_metric: '140g',
          raw_weight_grams_base: 140,
          calories_base: 180,
          protein_g_base: 32,
          carbs_g_base: 1,
          fat_g_base: 4,
          department: 'meat_seafood',
          food_category: 'poultry_meat',
        },
        {
          name: 'Canned Black Beans (rinsed & drained)',
          amount_imperial: '1/2 cup',
          amount_metric: '90g',
          raw_weight_grams_base: 90,
          calories_base: 110,
          protein_g_base: 7,
          carbs_g_base: 20,
          fat_g_base: 0.5,
          department: 'pantry_spices',
          food_category: 'grains_carbs',
        },
        {
          name: 'Charred Sliced Bell Peppers & Onions',
          amount_imperial: '1 cup',
          amount_metric: '120g',
          raw_weight_grams_base: 120,
          calories_base: 45,
          protein_g_base: 1.5,
          carbs_g_base: 9,
          fat_g_base: 0.5,
          department: 'produce',
          food_category: 'vegetables',
        },
        {
          name: 'Brown Rice or Quinoa',
          amount_imperial: '1/2 cup (cooked)',
          amount_metric: '75g',
          raw_weight_grams_base: 75,
          calories_base: 105,
          protein_g_base: 2.5,
          carbs_g_base: 22,
          fat_g_base: 1,
          department: 'grains_bakery',
          food_category: 'grains_carbs',
        },
        {
          name: 'Fire-Roasted Red Salsa & Lime',
          amount_imperial: '3 tbsp',
          amount_metric: '45g',
          raw_weight_grams_base: 45,
          calories_base: 25,
          protein_g_base: 0.5,
          carbs_g_base: 5,
          fat_g_base: 0,
          department: 'pantry_spices',
          food_category: 'pantry_staple',
        },
      ],
      instructions: [
        'Season chicken cubes with chili powder, cumin, lime juice, and garlic.',
        'Sear chicken and sliced peppers in a hot skillet for 6-8 minutes until charred and cooked through.',
        'Warm black beans and brown rice together in a microwave or skillet.',
        'Assemble the bowl with grains and beans on the bottom, top with chicken and peppers, and spoon salsa generously.',
      ],
      chef_notes: 'Black beans provide prebiotic resistant starch that fuels gut microbiome health and keeps hunger locked down for 5+ hours.',
    },
  },
  {
    id: 'lemon-herb-chicken-salad',
    name: '🥙 Crisp Mediterranean Lemon Chicken Salad',
    shortName: 'Mediterranean Chicken Salad',
    desc: 'Chopped romaine, grilled lemon-herb chicken, cucumbers, cherry tomatoes & vinaigrette',
    cals: 410,
    protein_g: 42,
    carbs_g: 16,
    fat_g: 20,
    mealIndex: 2,
    category: 'lunch',
    categoryLabel: 'Lunch • Meal 2',
    foodName: 'Crisp Mediterranean Lemon Herb Chicken Salad',
    grams: 290,
    emoji: '🥙',
    tags: ['Wholesome', 'Low-Carb', 'Heart-Healthy Olive Oil', 'Hydrating'],
    is_gluten_free: true,
    is_dairy_free: true,
    recipe: {
      id: 'wholesome-lemon-herb-chicken-salad',
      title: 'Crisp Mediterranean Lemon Herb Chicken Salad',
      description: 'Crisp chopped hearts of romaine, grilled oregano chicken, seedless cucumbers, sweet grape tomatoes, and extra virgin olive oil vinaigrette.',
      category: 'lunch',
      sub_category: 'fresh_salads',
      prep_time_minutes: 10,
      cook_time_minutes: 8,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'Low-Carb', 'Mediterranean', 'Keto-Friendly'],
      calories_per_serving: 410,
      protein_g_per_serving: 42,
      carbs_g_per_serving: 16,
      fat_g_per_serving: 20,
      icon_emoji: '🥙',
      ingredients: [
        {
          name: 'Lemon-Herb Grilled Chicken Breast',
          amount_imperial: '6 oz',
          amount_metric: '170g',
          raw_weight_grams_base: 170,
          calories_base: 220,
          protein_g_base: 38,
          carbs_g_base: 0,
          fat_g_base: 5,
          department: 'meat_seafood',
          food_category: 'poultry_meat',
        },
        {
          name: 'Chopped Romaine Hearts',
          amount_imperial: '3 cups',
          amount_metric: '120g',
          raw_weight_grams_base: 120,
          calories_base: 20,
          protein_g_base: 1.5,
          carbs_g_base: 4,
          fat_g_base: 0.3,
          department: 'produce',
          food_category: 'vegetables',
        },
        {
          name: 'English Cucumbers & Cherry Tomatoes',
          amount_imperial: '1 cup mix',
          amount_metric: '100g',
          raw_weight_grams_base: 100,
          calories_base: 30,
          protein_g_base: 1,
          carbs_g_base: 6,
          fat_g_base: 0.2,
          department: 'produce',
          food_category: 'vegetables',
        },
        {
          name: 'Extra Virgin Olive Oil & Red Wine Vinegar',
          amount_imperial: '1 tbsp olive oil + vinegar',
          amount_metric: '15ml',
          raw_weight_grams_base: 15,
          calories_base: 120,
          protein_g_base: 0,
          carbs_g_base: 0,
          fat_g_base: 14,
          department: 'healthy_fats',
          food_category: 'nuts_fats_oils',
        },
      ],
      instructions: [
        'Toss chicken with oregano, garlic, lemon juice, salt, and pepper; sear until internal temp hits 165°F (about 8 min).',
        'Chop romaine hearts and toss into a large salad bowl with sliced cucumbers and halved cherry tomatoes.',
        'Whisk extra virgin olive oil with red wine vinegar, dried oregano, and sea salt.',
        'Slice grilled chicken, arrange over greens, and drizzle with the vinaigrette.',
      ],
      chef_notes: 'High volume, low caloric density: over 3 cups of crisp fresh vegetables with 42g of satiating protein.',
    },
  },
  {
    id: 'hearty-turkey-chili',
    name: '🍲 Slow-Simmered Turkey & Sweet Potato Chili',
    shortName: 'Turkey Sweet Potato Chili',
    desc: '93% lean ground turkey, cubed roasted sweet potato, kidney beans & rich cumin chili broth',
    cals: 440,
    protein_g: 38,
    carbs_g: 46,
    fat_g: 12,
    mealIndex: 2,
    category: 'lunch',
    categoryLabel: 'Lunch • Meal 2',
    foodName: 'Slow-Simmered Lean Turkey & Sweet Potato Chili',
    grams: 340,
    emoji: '🍲',
    tags: ['Wholesome', 'Comfort Food', 'Meal Prep Classic', 'High-Protein'],
    is_gluten_free: true,
    is_dairy_free: true,
    recipe: {
      id: 'wholesome-hearty-turkey-chili',
      title: 'Slow-Simmered Turkey & Sweet Potato Chili',
      description: 'Lean 93% ground turkey simmered in rich fire-roasted tomato broth with cubed sweet potatoes, kidney beans, and warming ancho chili spices.',
      category: 'lunch',
      sub_category: 'soups_chilis',
      prep_time_minutes: 10,
      cook_time_minutes: 25,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'High-Protein', 'One-Pot', 'Complex Carbs'],
      calories_per_serving: 440,
      protein_g_per_serving: 38,
      carbs_g_per_serving: 46,
      fat_g_per_serving: 12,
      icon_emoji: '🍲',
      ingredients: [
        {
          name: '93% Lean Ground Turkey',
          amount_imperial: '5 oz',
          amount_metric: '140g',
          raw_weight_grams_base: 140,
          calories_base: 200,
          protein_g_base: 28,
          carbs_g_base: 0,
          fat_g_base: 9,
          department: 'meat_seafood',
          food_category: 'poultry_meat',
        },
        {
          name: 'Diced Sweet Potato',
          amount_imperial: '3/4 cup',
          amount_metric: '100g',
          raw_weight_grams_base: 100,
          calories_base: 85,
          protein_g_base: 1.5,
          carbs_g_base: 20,
          fat_g_base: 0.1,
          department: 'produce',
          food_category: 'vegetables',
        },
        {
          name: 'Dark Red Kidney Beans (cooked/canned)',
          amount_imperial: '1/2 cup',
          amount_metric: '90g',
          raw_weight_grams_base: 90,
          calories_base: 110,
          protein_g_base: 7,
          carbs_g_base: 20,
          fat_g_base: 0.5,
          department: 'pantry_spices',
          food_category: 'grains_carbs',
        },
        {
          name: 'Crushed Fire-Roasted Tomatoes & Chili Spices',
          amount_imperial: '3/4 cup',
          amount_metric: '180g',
          raw_weight_grams_base: 180,
          calories_base: 45,
          protein_g_base: 1.5,
          carbs_g_base: 8,
          fat_g_base: 0.4,
          department: 'pantry_spices',
          food_category: 'vegetables',
        },
      ],
      instructions: [
        'Brown ground turkey in a deep pot over medium heat with diced onions and garlic until cooked through.',
        'Stir in chili powder, ground cumin, smoked paprika, and diced sweet potatoes.',
        'Add crushed tomatoes and rinsed kidney beans, plus 1/2 cup water or bone broth.',
        'Cover and simmer gently for 20 minutes until sweet potatoes are fork-tender and chili is thick.',
      ],
      chef_notes: 'Sweet potatoes balance the spicy chili broth naturally without need for brown sugar or molasses.',
    },
  },
  {
    id: 'teriyaki-salmon-rice-bowl',
    name: '🍚 Teriyaki Salmon & Steamed Edamame Bowl',
    shortName: 'Teriyaki Salmon Rice Bowl',
    desc: 'Glazed wild salmon, brown rice, shelled edamame, shredded carrots & toasted nori',
    cals: 540,
    protein_g: 38,
    carbs_g: 58,
    fat_g: 18,
    mealIndex: 2,
    category: 'lunch',
    categoryLabel: 'Lunch • Meal 2',
    foodName: 'Teriyaki Wild Salmon Brown Rice Bowl with Edamame',
    grams: 320,
    emoji: '🍚',
    tags: ['Wholesome', 'Omega-3', 'Brain Fuel', 'Satiating'],
    is_gluten_free: true,
    is_dairy_free: true,
    recipe: {
      id: 'wholesome-teriyaki-salmon-rice-bowl',
      title: 'Teriyaki Wild Salmon & Steamed Edamame Brown Rice Bowl',
      description: 'Pan-seared wild salmon glazed with low-sodium ginger teriyaki over nutty brown rice, sweet steamed edamame, and shredded carrots.',
      category: 'lunch',
      sub_category: 'power_bowls',
      prep_time_minutes: 10,
      cook_time_minutes: 10,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'Omega-3', 'Brain Fuel', 'Heart-Healthy'],
      calories_per_serving: 540,
      protein_g_per_serving: 38,
      carbs_g_per_serving: 58,
      fat_g_per_serving: 18,
      icon_emoji: '🍚',
      ingredients: [
        {
          name: 'Wild Alaskan Salmon Fillet',
          amount_imperial: '5 oz',
          amount_metric: '140g',
          raw_weight_grams_base: 140,
          calories_base: 220,
          protein_g_base: 28,
          carbs_g_base: 0,
          fat_g_base: 12,
          department: 'meat_seafood',
          food_category: 'fish_seafood',
        },
        {
          name: 'Steamed Brown Rice',
          amount_imperial: '1 cup (cooked)',
          amount_metric: '150g',
          raw_weight_grams_base: 150,
          calories_base: 215,
          protein_g_base: 4.5,
          carbs_g_base: 45,
          fat_g_base: 1.5,
          department: 'grains_bakery',
          food_category: 'grains_carbs',
        },
        {
          name: 'Shelled Edamame (Mukimame)',
          amount_imperial: '1/3 cup',
          amount_metric: '50g',
          raw_weight_grams_base: 50,
          calories_base: 60,
          protein_g_base: 5.5,
          carbs_g_base: 4,
          fat_g_base: 2.5,
          department: 'frozen',
          food_category: 'plant_protein',
        },
        {
          name: 'Low-Sodium Ginger Teriyaki Glaze',
          amount_imperial: '1.5 tbsp',
          amount_metric: '22ml',
          raw_weight_grams_base: 22,
          calories_base: 45,
          protein_g_base: 0.5,
          carbs_g_base: 9,
          fat_g_base: 0,
          department: 'pantry_spices',
          food_category: 'pantry_staple',
        },
      ],
      instructions: [
        'Sear wild salmon fillet in a non-stick skillet skin-side down for 4 minutes until crisp, then flip for 3 minutes.',
        'Brush top with ginger teriyaki glaze in the final 60 seconds.',
        'Warm brown rice and steam shelled edamame.',
        'Layer rice into bowl, top with edamame and shredded carrots, and rest the glazed salmon on top.',
      ],
      chef_notes: 'Wild salmon provides high concentrations of EPA/DHA omega-3 fatty acids for cognitive clarity and cellular recovery.',
    },
  },
  {
    id: 'quinoa-chickpea-tahini-bowl',
    name: '🥗 Warm Quinoa, Chickpeas & Herb Tahini Bowl',
    shortName: 'Quinoa & Chickpea Tahini',
    desc: 'Tri-color quinoa, roasted spiced chickpeas, sautéed kale & lemon garlic tahini drizzle',
    cals: 460,
    protein_g: 18,
    carbs_g: 64,
    fat_g: 16,
    mealIndex: 2,
    category: 'lunch',
    categoryLabel: 'Lunch • Meal 2',
    foodName: 'Warm Quinoa, Chickpea & Herb Tahini Grain Bowl',
    grams: 310,
    emoji: '🥗',
    tags: ['Wholesome', 'Plant Power', 'High-Fiber', 'Micronutrient Dense'],
    is_gluten_free: true,
    is_dairy_free: true,
    recipe: {
      id: 'wholesome-quinoa-chickpea-tahini-bowl',
      title: 'Warm Tri-Color Quinoa, Chickpea & Lemon Tahini Bowl',
      description: 'Fluffy whole tri-color quinoa, crispy spiced chickpeas, tender sautéed tuscan kale, and zesty lemon garlic tahini dressing.',
      category: 'lunch',
      sub_category: 'power_bowls',
      prep_time_minutes: 10,
      cook_time_minutes: 12,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'Plant-Based', 'High-Fiber', 'Gluten-Free'],
      calories_per_serving: 460,
      protein_g_per_serving: 18,
      carbs_g_per_serving: 64,
      fat_g_per_serving: 16,
      icon_emoji: '🥗',
      ingredients: [
        {
          name: 'Cooked Tri-Color Quinoa',
          amount_imperial: '1 cup',
          amount_metric: '185g',
          raw_weight_grams_base: 185,
          calories_base: 220,
          protein_g_base: 8,
          carbs_g_base: 39,
          fat_g_base: 3.5,
          department: 'grains_bakery',
          food_category: 'grains_carbs',
        },
        {
          name: 'Canned Garbanzo Beans (Chickpeas)',
          amount_imperial: '1/2 cup',
          amount_metric: '85g',
          raw_weight_grams_base: 85,
          calories_base: 130,
          protein_g_base: 7,
          carbs_g_base: 22,
          fat_g_base: 2,
          department: 'pantry_spices',
          food_category: 'plant_protein',
        },
        {
          name: 'Tuscan Kale (chopped & sautéed)',
          amount_imperial: '1.5 cups',
          amount_metric: '60g',
          raw_weight_grams_base: 60,
          calories_base: 25,
          protein_g_base: 1.5,
          carbs_g_base: 4,
          fat_g_base: 0.3,
          department: 'produce',
          food_category: 'vegetables',
        },
        {
          name: 'Pure Sesame Tahini & Lemon Dressing',
          amount_imperial: '1 tbsp',
          amount_metric: '15g',
          raw_weight_grams_base: 15,
          calories_base: 85,
          protein_g_base: 2.5,
          carbs_g_base: 3,
          fat_g_base: 8,
          department: 'healthy_fats',
          food_category: 'nuts_fats_oils',
        },
      ],
      instructions: [
        'Rinse and dry chickpeas; toss in a skillet with cumin, garlic powder, and paprika for 5 minutes until toasted.',
        'Add chopped kale to the pan and toss for 1-2 minutes until vibrant green and tender.',
        'Layer warm quinoa in a wide bowl, top with seasoned chickpeas and kale.',
        'Whisk sesame tahini with lemon juice, a splash of water, and salt; drizzle over bowl.',
      ],
      chef_notes: 'Quinoa is one of the rare plant sources with all 9 essential amino acids, making it a complete biological protein.',
    },
  },

  // =========================================================================
  // DINNER (Meal 3)
  // =========================================================================
  {
    id: 'salmon-sweet-potato',
    name: '🐟 Wild Alaskan Salmon & Roasted Sweet Potato',
    shortName: 'Wild Salmon & Sweet Potato',
    desc: 'Oven-baked wild salmon fillet, roasted rosemary sweet potato wedges & grilled asparagus',
    cals: 580,
    protein_g: 44,
    carbs_g: 46,
    fat_g: 22,
    mealIndex: 3,
    category: 'dinner',
    categoryLabel: 'Dinner • Meal 3',
    foodName: 'Wild Alaskan Salmon with Roasted Sweet Potato & Grilled Asparagus',
    grams: 340,
    emoji: '🐟',
    tags: ['Wholesome', 'Omega-3 Rich', 'Anti-Inflammatory', 'Athletic Gold'],
    is_gluten_free: true,
    is_dairy_free: true,
    recipe: {
      id: 'wholesome-salmon-sweet-potato',
      title: 'Wild Alaskan Salmon with Rosemary Sweet Potatoes & Asparagus',
      description: 'Crispy skin wild Alaskan salmon paired with caramelized rosemary sweet potato cubes and tender charred garlic asparagus spears.',
      category: 'dinner',
      sub_category: 'seafood_fish',
      prep_time_minutes: 10,
      cook_time_minutes: 18,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'Omega-3', 'Clean Dinner', 'Athletic Recovery'],
      calories_per_serving: 580,
      protein_g_per_serving: 44,
      carbs_g_per_serving: 46,
      fat_g_per_serving: 22,
      icon_emoji: '🐟',
      ingredients: [
        {
          name: 'Wild Alaskan Sockeye Salmon Fillet',
          amount_imperial: '6 oz',
          amount_metric: '170g',
          raw_weight_grams_base: 170,
          calories_base: 280,
          protein_g_base: 38,
          carbs_g_base: 0,
          fat_g_base: 14,
          department: 'meat_seafood',
          food_category: 'fish_seafood',
        },
        {
          name: 'Cubed Sweet Potato',
          amount_imperial: '1 cup',
          amount_metric: '130g',
          raw_weight_grams_base: 130,
          calories_base: 140,
          protein_g_base: 2.5,
          carbs_g_base: 33,
          fat_g_base: 0.2,
          department: 'produce',
          food_category: 'vegetables',
        },
        {
          name: 'Fresh Asparagus Spears',
          amount_imperial: '8 spears',
          amount_metric: '120g',
          raw_weight_grams_base: 120,
          calories_base: 30,
          protein_g_base: 3,
          carbs_g_base: 5,
          fat_g_base: 0.3,
          department: 'produce',
          food_category: 'vegetables',
        },
        {
          name: 'Extra Virgin Olive Oil & Rosemary',
          amount_imperial: '1 tbsp',
          amount_metric: '14ml',
          raw_weight_grams_base: 14,
          calories_base: 130,
          protein_g_base: 0,
          carbs_g_base: 0,
          fat_g_base: 14,
          department: 'healthy_fats',
          food_category: 'nuts_fats_oils',
        },
      ],
      instructions: [
        'Preheat oven or air fryer to 400°F (200°C).',
        'Toss cubed sweet potatoes with half the olive oil, rosemary, sea salt, and roast for 18 minutes until tender and caramelized.',
        'Toss asparagus with remaining oil, minced garlic, and pepper.',
        'Pan-sear salmon skin-side down in a hot cast-iron skillet for 4-5 minutes until crisp; flip and sear for 2-3 minutes.',
        'Plate the wild salmon alongside roasted sweet potatoes and tender asparagus with fresh lemon wedges.',
      ],
      chef_notes: 'Astaxanthin in wild salmon provides its deep coral color and acts as one of nature’s most potent lipid antioxidant protectors.',
    },
  },
  {
    id: 'sirloin-garlic-asparagus',
    name: '🥩 Seared Grass-Fed Sirloin & Baby Potatoes',
    shortName: 'Sirloin & Baby Potatoes',
    desc: '6oz cast-iron seared top sirloin steak, crushed roasted gold potatoes & garlic asparagus',
    cals: 530,
    protein_g: 48,
    carbs_g: 28,
    fat_g: 22,
    mealIndex: 3,
    category: 'dinner',
    categoryLabel: 'Dinner • Meal 3',
    foodName: 'Grass-Fed Sirloin Steak with Roasted Baby Potatoes & Asparagus',
    grams: 310,
    emoji: '🥩',
    tags: ['Wholesome', 'Iron & Zinc', 'Muscle Recovery', 'Satiating'],
    is_gluten_free: true,
    is_dairy_free: true,
    recipe: {
      id: 'wholesome-sirloin-garlic-asparagus',
      title: 'Cast-Iron Grass-Fed Top Sirloin & Crushed Gold Potatoes',
      description: 'Lean 6oz grass-fed top sirloin seared with garlic herb crust, served with fork-crushed baby Yukon gold potatoes and grilled asparagus.',
      category: 'dinner',
      sub_category: 'beef_steaks',
      prep_time_minutes: 5,
      cook_time_minutes: 12,
      servings_yield: 1,
      difficulty: 'moderate',
      tags: ['Wholesome', 'High-Protein', 'Iron & Zinc', 'Clean Fuel'],
      calories_per_serving: 530,
      protein_g_per_serving: 48,
      carbs_g_per_serving: 28,
      fat_g_per_serving: 22,
      icon_emoji: '🥩',
      ingredients: [
        {
          name: 'Grass-Fed Beef Top Sirloin Steak',
          amount_imperial: '6 oz',
          amount_metric: '170g',
          raw_weight_grams_base: 170,
          calories_base: 310,
          protein_g_base: 44,
          carbs_g_base: 0,
          fat_g_base: 14,
          department: 'meat_seafood',
          food_category: 'poultry_meat',
        },
        {
          name: 'Baby Yukon Gold Potatoes',
          amount_imperial: '3/4 cup (halved)',
          amount_metric: '110g',
          raw_weight_grams_base: 110,
          calories_base: 110,
          protein_g_base: 2.5,
          carbs_g_base: 24,
          fat_g_base: 0.2,
          department: 'produce',
          food_category: 'vegetables',
        },
        {
          name: 'Garlic Asparagus Spears',
          amount_imperial: '6 spears',
          amount_metric: '90g',
          raw_weight_grams_base: 90,
          calories_base: 25,
          protein_g_base: 2,
          carbs_g_base: 4,
          fat_g_base: 0.2,
          department: 'produce',
          food_category: 'vegetables',
        },
        {
          name: 'Cold-Pressed Olive Oil & Minced Garlic',
          amount_imperial: '2 tsp',
          amount_metric: '10ml',
          raw_weight_grams_base: 10,
          calories_base: 85,
          protein_g_base: 0,
          carbs_g_base: 1,
          fat_g_base: 9,
          department: 'healthy_fats',
          food_category: 'nuts_fats_oils',
        },
      ],
      instructions: [
        'Boil baby potatoes in salted water for 10 minutes, drain, and lightly crush flat with a fork.',
        'Season sirloin generously with coarse sea salt and cracked black pepper on both sides.',
        'Heat a cast-iron skillet on high heat until smoking lightly with half the olive oil.',
        'Sear sirloin for 3-4 minutes per side for a juicy medium-rare (135°F); rest for 5 minutes before slicing.',
        'Crisp crushed potatoes in the remaining steak drippings for 3 minutes alongside asparagus spears.',
      ],
      chef_notes: 'Grass-fed sirloin has higher omega-3s and conjugated linoleic acid (CLA) compared to grain-finished cuts while keeping calories lean.',
    },
  },
  {
    id: 'crispy-chicken-cutlet-quinoa',
    name: '🍗 Herb Panko Chicken Breast & Tri-Color Quinoa',
    shortName: 'Crisp Herb Chicken & Quinoa',
    desc: 'Air-fried crisp herb chicken breast served with fluffy quinoa and steamed green beans',
    cals: 490,
    protein_g: 48,
    carbs_g: 42,
    fat_g: 14,
    mealIndex: 3,
    category: 'dinner',
    categoryLabel: 'Dinner • Meal 3',
    foodName: 'Herb Panko Crusted Chicken Breast with Tri-Color Quinoa',
    grams: 320,
    emoji: '🍗',
    tags: ['Wholesome', 'Ultra High Protein', 'Lean Fuel', 'Crispy & Clean'],
    is_gluten_free: false,
    is_dairy_free: true,
    recipe: {
      id: 'wholesome-crispy-chicken-cutlet-quinoa',
      title: 'Herb Panko Crusted Chicken Breast with Tri-Color Quinoa',
      description: 'Thin-cut chicken breast coated in herb panko crumbs, air-fried until crunchy, paired with fluffy quinoa and tender haricots verts.',
      category: 'dinner',
      sub_category: 'poultry_dishes',
      prep_time_minutes: 10,
      cook_time_minutes: 12,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'High-Protein', 'Clean Comfort', 'Air Fryer'],
      calories_per_serving: 490,
      protein_g_per_serving: 48,
      carbs_g_per_serving: 42,
      fat_g_per_serving: 14,
      icon_emoji: '🍗',
      ingredients: [
        {
          name: 'Chicken Breast Cutlet',
          amount_imperial: '6 oz',
          amount_metric: '170g',
          raw_weight_grams_base: 170,
          calories_base: 220,
          protein_g_base: 38,
          carbs_g_base: 0,
          fat_g_base: 5,
          department: 'meat_seafood',
          food_category: 'poultry_meat',
        },
        {
          name: 'Whole Grain Herb Panko Breadcrumbs',
          amount_imperial: '1/4 cup',
          amount_metric: '25g',
          raw_weight_grams_base: 25,
          calories_base: 95,
          protein_g_base: 3.5,
          carbs_g_base: 18,
          fat_g_base: 1,
          department: 'grains_bakery',
          food_category: 'grains_carbs',
        },
        {
          name: 'Cooked Tri-Color Quinoa',
          amount_imperial: '1/2 cup',
          amount_metric: '95g',
          raw_weight_grams_base: 95,
          calories_base: 110,
          protein_g_base: 4,
          carbs_g_base: 20,
          fat_g_base: 1.8,
          department: 'grains_bakery',
          food_category: 'grains_carbs',
        },
        {
          name: 'Steamed Haricots Verts (Green Beans)',
          amount_imperial: '1 cup',
          amount_metric: '100g',
          raw_weight_grams_base: 100,
          calories_base: 35,
          protein_g_base: 2,
          carbs_g_base: 7,
          fat_g_base: 0.2,
          department: 'produce',
          food_category: 'vegetables',
        },
        {
          name: 'Dijon Mustard & Olive Oil Spray',
          amount_imperial: '1 tbsp mustard',
          amount_metric: '15g',
          raw_weight_grams_base: 15,
          calories_base: 30,
          protein_g_base: 0.5,
          carbs_g_base: 1,
          fat_g_base: 2.5,
          department: 'pantry_spices',
          food_category: 'pantry_staple',
        },
      ],
      instructions: [
        'Brush chicken cutlet lightly with Dijon mustard, then press firmly into seasoned herb panko crumbs.',
        'Lightly mist with olive oil spray and air-fry at 390°F (200°C) for 10-12 minutes until deeply golden and crisp.',
        'Steam green beans for 3 minutes until tender-crisp.',
        'Slice crispy chicken over a warm bed of quinoa and serve with green beans and lemon.',
      ],
      chef_notes: 'Using Dijon as the binder eliminates heavy egg washes and creates a crispy crust with zero deep-frying.',
    },
  },
  {
    id: 'garlic-shrimp-zoodles',
    name: '🍤 Sunkissed Garlic Shrimp & Zucchini Noodles',
    shortName: 'Garlic Shrimp & Zoodles',
    desc: 'Tender jumbo shrimp sautéed in cold-pressed olive oil, fresh garlic, basil & zoodles',
    cals: 360,
    protein_g: 38,
    carbs_g: 14,
    fat_g: 16,
    mealIndex: 3,
    category: 'dinner',
    categoryLabel: 'Dinner • Meal 3',
    foodName: 'Sunkissed Garlic Butter Shrimp with Fresh Zucchini Noodles',
    grams: 290,
    emoji: '🍤',
    tags: ['Wholesome', 'Light Dinner', 'Low-Carb', 'Fast Digesting'],
    is_gluten_free: true,
    is_dairy_free: false,
    recipe: {
      id: 'wholesome-garlic-shrimp-zoodles',
      title: 'Sunkissed Garlic Butter Shrimp with Zucchini Noodles',
      description: 'Jumbo wild shrimp sautéed in extra virgin olive oil, minced fresh garlic, cherry tomatoes, and spiralized zucchini noodles.',
      category: 'dinner',
      sub_category: 'seafood_fish',
      prep_time_minutes: 8,
      cook_time_minutes: 6,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'Low-Carb', 'Keto-Friendly', 'Fast Cooking'],
      calories_per_serving: 360,
      protein_g_per_serving: 38,
      carbs_g_per_serving: 14,
      fat_g_per_serving: 16,
      icon_emoji: '🍤',
      ingredients: [
        {
          name: 'Wild Jumbo Shrimp (peeled & deveined)',
          amount_imperial: '7 oz',
          amount_metric: '200g',
          raw_weight_grams_base: 200,
          calories_base: 180,
          protein_g_base: 36,
          carbs_g_base: 1,
          fat_g_base: 2,
          department: 'meat_seafood',
          food_category: 'fish_seafood',
        },
        {
          name: 'Fresh Spiralized Zucchini Noodles',
          amount_imperial: '2 cups',
          amount_metric: '180g',
          raw_weight_grams_base: 180,
          calories_base: 35,
          protein_g_base: 2,
          carbs_g_base: 6,
          fat_g_base: 0.5,
          department: 'produce',
          food_category: 'vegetables',
        },
        {
          name: 'Sweet Cherry Tomatoes (halved)',
          amount_imperial: '1/2 cup',
          amount_metric: '75g',
          raw_weight_grams_base: 75,
          calories_base: 20,
          protein_g_base: 1,
          carbs_g_base: 4,
          fat_g_base: 0.2,
          department: 'produce',
          food_category: 'vegetables',
        },
        {
          name: 'Extra Virgin Olive Oil & Grass-Fed Butter',
          amount_imperial: '1 tbsp total',
          amount_metric: '14g',
          raw_weight_grams_base: 14,
          calories_base: 125,
          protein_g_base: 0,
          carbs_g_base: 0,
          fat_g_base: 14,
          department: 'healthy_fats',
          food_category: 'nuts_fats_oils',
        },
      ],
      instructions: [
        'Melt olive oil and butter in a wide skillet over medium-high heat with minced garlic and chili flakes.',
        'Add shrimp and cherry tomatoes; sear for 2 minutes per side until shrimp are pink and opaque.',
        'Toss in spiralized zucchini noodles for just 90 seconds until heated through but still tender-crisp.',
        'Finish with a squeeze of fresh lemon juice, grated parmesan, and torn fresh basil.',
      ],
      chef_notes: 'Do not overcook zucchini noodles—90 seconds in a hot pan keeps them al dente without releasing excess water.',
    },
  },
  {
    id: 'tuscan-roasted-chicken',
    name: '🥘 1-Pan Tuscan Herb Chicken & Roasted Veggies',
    shortName: 'Tuscan Herb Chicken',
    desc: 'Oven roasted chicken breast with red potatoes, zucchini, and blistered cherry tomatoes',
    cals: 520,
    protein_g: 46,
    carbs_g: 36,
    fat_g: 20,
    mealIndex: 3,
    category: 'dinner',
    categoryLabel: 'Dinner • Meal 3',
    foodName: '1-Pan Tuscan Herb Roasted Chicken with Red Potatoes & Veggies',
    grams: 330,
    emoji: '🥘',
    tags: ['Wholesome', 'Simple Sheet Pan', 'Antioxidants', 'Balanced'],
    is_gluten_free: true,
    is_dairy_free: true,
    recipe: {
      id: 'wholesome-tuscan-roasted-chicken',
      title: '1-Pan Tuscan Herb Roasted Chicken Breast & Summer Vegetables',
      description: 'Rosemary-marinated chicken breast roasted on a single sheet pan alongside quartered baby red potatoes, zucchini rounds, and sweet cherry tomatoes.',
      category: 'dinner',
      sub_category: 'sheet_pan_meals',
      prep_time_minutes: 10,
      cook_time_minutes: 20,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'One-Pan', 'Easy Cleanup', 'Balanced Macros'],
      calories_per_serving: 520,
      protein_g_per_serving: 46,
      carbs_g_per_serving: 36,
      fat_g_per_serving: 20,
      icon_emoji: '🥘',
      ingredients: [
        {
          name: 'Boneless Skinless Chicken Breast',
          amount_imperial: '6 oz',
          amount_metric: '170g',
          raw_weight_grams_base: 170,
          calories_base: 220,
          protein_g_base: 38,
          carbs_g_base: 0,
          fat_g_base: 5,
          department: 'meat_seafood',
          food_category: 'poultry_meat',
        },
        {
          name: 'Baby Red Potatoes (quartered)',
          amount_imperial: '3/4 cup',
          amount_metric: '110g',
          raw_weight_grams_base: 110,
          calories_base: 100,
          protein_g_base: 2.5,
          carbs_g_base: 23,
          fat_g_base: 0.2,
          department: 'produce',
          food_category: 'vegetables',
        },
        {
          name: 'Zucchini & Cherry Tomatoes',
          amount_imperial: '1.5 cups mix',
          amount_metric: '120g',
          raw_weight_grams_base: 120,
          calories_base: 35,
          protein_g_base: 2,
          carbs_g_base: 7,
          fat_g_base: 0.3,
          department: 'produce',
          food_category: 'vegetables',
        },
        {
          name: 'Extra Virgin Olive Oil & Italian Herbs',
          amount_imperial: '1.2 tbsp',
          amount_metric: '17ml',
          raw_weight_grams_base: 17,
          calories_base: 165,
          protein_g_base: 0,
          carbs_g_base: 0,
          fat_g_base: 18,
          department: 'healthy_fats',
          food_category: 'nuts_fats_oils',
        },
      ],
      instructions: [
        'Toss chicken and diced vegetables in olive oil, dried rosemary, thyme, garlic, salt, and pepper.',
        'Spread in a single layer on a parchment-lined baking sheet.',
        'Roast at 400°F (200°C) for 20-22 minutes until potatoes are golden and chicken reaches 165°F.',
        'Serve hot directly from the pan with pan juices spooned over the chicken.',
      ],
      chef_notes: '1-sheet pan meals capture roasted vegetable sugars and infuse them into the lean chicken juices.',
    },
  },
  {
    id: 'turkey-bolognese-penne',
    name: '🍝 Lean Turkey Bolognese with Durum Penne',
    shortName: 'Turkey Bolognese Penne',
    desc: '93% lean ground turkey simmered in rich garlic herb marinara over al dente durum penne',
    cals: 510,
    protein_g: 42,
    carbs_g: 58,
    fat_g: 13,
    mealIndex: 3,
    category: 'dinner',
    categoryLabel: 'Dinner • Meal 3',
    foodName: 'Lean Ground Turkey Bolognese over Durum Wheat Penne',
    grams: 340,
    emoji: '🍝',
    tags: ['Wholesome', 'Post-Workout Fuel', 'Comfort Food', 'High Protein'],
    is_gluten_free: false,
    is_dairy_free: true,
    recipe: {
      id: 'wholesome-turkey-bolognese-penne',
      title: 'Lean Turkey Bolognese with Al Dente Durum Penne',
      description: 'Slow-simmered 93% lean ground turkey in rich crushed tomato, basil, and garlic bolognese sauce served over durum wheat penne pasta.',
      category: 'dinner',
      sub_category: 'pasta_comfort',
      prep_time_minutes: 8,
      cook_time_minutes: 15,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'High-Protein', 'Comfort Food', 'Post-Workout'],
      calories_per_serving: 510,
      protein_g_per_serving: 42,
      carbs_g_per_serving: 58,
      fat_g_per_serving: 13,
      icon_emoji: '🍝',
      ingredients: [
        {
          name: '93% Lean Ground Turkey',
          amount_imperial: '5.5 oz',
          amount_metric: '155g',
          raw_weight_grams_base: 155,
          calories_base: 220,
          protein_g_base: 31,
          carbs_g_base: 0,
          fat_g_base: 10,
          department: 'meat_seafood',
          food_category: 'poultry_meat',
        },
        {
          name: 'Durum Wheat Penne Rigate (dry weight)',
          amount_imperial: '2 oz (dry) / 1 cup (cooked)',
          amount_metric: '60g',
          raw_weight_grams_base: 60,
          calories_base: 210,
          protein_g_base: 8,
          carbs_g_base: 44,
          fat_g_base: 1,
          department: 'grains_bakery',
          food_category: 'grains_carbs',
        },
        {
          name: 'Crushed San Marzano Marinara Sauce',
          amount_imperial: '3/4 cup',
          amount_metric: '180g',
          raw_weight_grams_base: 180,
          calories_base: 60,
          protein_g_base: 2,
          carbs_g_base: 12,
          fat_g_base: 1,
          department: 'pantry_spices',
          food_category: 'vegetables',
        },
        {
          name: 'Grated Parmigiano-Reggiano',
          amount_imperial: '1 tbsp',
          amount_metric: '8g',
          raw_weight_grams_base: 8,
          calories_base: 30,
          protein_g_base: 3,
          carbs_g_base: 0.5,
          fat_g_base: 2,
          department: 'dairy_eggs',
          food_category: 'dairy_eggs',
        },
      ],
      instructions: [
        'Cook penne in heavily salted boiling water for 10 minutes until al dente; drain and reserve 2 tbsp pasta water.',
        'Brown ground turkey in a skillet with garlic, oregano, and salt until cooked through.',
        'Stir in marinara sauce and simmer gently for 5 minutes.',
        'Toss hot penne directly into the sauce with pasta water, top with Parmigiano-Reggiano, and serve.',
      ],
      chef_notes: 'Durum wheat has a naturally high gluten and protein index, keeping pasta firm with a sustained glycemic burn.',
    },
  },
  {
    id: 'baked-cod-lemon-potatoes',
    name: '🐟 Lemon Herb Baked Atlantic Cod & Potatoes',
    shortName: 'Baked Cod & Herb Potatoes',
    desc: 'Flaky wild Atlantic cod fillet with roasted baby yellow potatoes and steamed lemon broccoli',
    cals: 430,
    protein_g: 40,
    carbs_g: 38,
    fat_g: 12,
    mealIndex: 3,
    category: 'dinner',
    categoryLabel: 'Dinner • Meal 3',
    foodName: 'Lemon Herb Baked Wild Cod with Roasted Potatoes & Broccoli',
    grams: 300,
    emoji: '🐟',
    tags: ['Wholesome', 'Lean White Fish', 'Easy Digestion', 'Clean Nutrition'],
    is_gluten_free: true,
    is_dairy_free: true,
    recipe: {
      id: 'wholesome-baked-cod-lemon-potatoes',
      title: 'Lemon Herb Baked Atlantic Cod & Rosemary Potatoes',
      description: 'Pristine wild Atlantic cod fillet baked tender with lemon slices, fresh dill, roasted baby yellow potatoes, and steamed lemon broccoli.',
      category: 'dinner',
      sub_category: 'seafood_fish',
      prep_time_minutes: 8,
      cook_time_minutes: 15,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'Lean White Fish', 'Clean Plate', 'Anti-Inflammatory'],
      calories_per_serving: 430,
      protein_g_per_serving: 40,
      carbs_g_per_serving: 38,
      fat_g_per_serving: 12,
      icon_emoji: '🐟',
      ingredients: [
        {
          name: 'Wild Atlantic Cod Fillet',
          amount_imperial: '7 oz',
          amount_metric: '200g',
          raw_weight_grams_base: 200,
          calories_base: 170,
          protein_g_base: 36,
          carbs_g_base: 0,
          fat_g_base: 1.5,
          department: 'meat_seafood',
          food_category: 'fish_seafood',
        },
        {
          name: 'Roasted Baby Yellow Potatoes',
          amount_imperial: '1 cup',
          amount_metric: '130g',
          raw_weight_grams_base: 130,
          calories_base: 130,
          protein_g_base: 3,
          carbs_g_base: 29,
          fat_g_base: 0.2,
          department: 'produce',
          food_category: 'vegetables',
        },
        {
          name: 'Steamed Lemon Broccoli',
          amount_imperial: '1.5 cups',
          amount_metric: '100g',
          raw_weight_grams_base: 100,
          calories_base: 35,
          protein_g_base: 2.5,
          carbs_g_base: 7,
          fat_g_base: 0.4,
          department: 'produce',
          food_category: 'vegetables',
        },
        {
          name: 'Extra Virgin Olive Oil & Lemon Dill',
          amount_imperial: '2 tsp',
          amount_metric: '10ml',
          raw_weight_grams_base: 10,
          calories_base: 95,
          protein_g_base: 0,
          carbs_g_base: 1,
          fat_g_base: 10,
          department: 'healthy_fats',
          food_category: 'nuts_fats_oils',
        },
      ],
      instructions: [
        'Place cod fillet in a baking dish, brush with olive oil, and season with sea salt, pepper, dill, and lemon slices.',
        'Bake at 400°F (200°C) for 12-14 minutes until cod flakes easily with a fork.',
        'Serve with roasted baby potatoes and steamed broccoli with extra lemon juice.',
      ],
      chef_notes: 'Cod is one of the highest protein-to-calorie density foods in the human diet, providing 36g protein for only 170 base calories.',
    },
  },

  // =========================================================================
  // SNACKS & FUEL (Meal 4)
  // =========================================================================
  {
    id: 'cottage-cheese-berries',
    name: '🫐 Cottage Cheese & Wild Blueberries',
    shortName: 'Cottage Cheese & Berries',
    desc: 'Slow-digesting low-fat cottage cheese topped with fresh wild blueberries & cinnamon',
    cals: 190,
    protein_g: 24,
    carbs_g: 18,
    fat_g: 2,
    mealIndex: 4,
    category: 'snack',
    categoryLabel: 'Snack • Meal 4',
    foodName: 'Low-Fat Cottage Cheese with Fresh Blueberries & Cinnamon',
    grams: 200,
    emoji: '🫐',
    tags: ['Wholesome', 'Casein Protein', 'Nighttime Fuel', 'Low-Fat'],
    is_gluten_free: true,
    is_dairy_free: false,
    recipe: {
      id: 'wholesome-cottage-cheese-berries',
      title: 'Low-Fat Cottage Cheese & Wild Blueberries',
      description: 'Slow-digesting cultured 2% cottage cheese paired with antioxidant-rich fresh blueberries and a dusting of Ceylon cinnamon.',
      category: 'snack_dessert',
      sub_category: 'sweet_treats',
      prep_time_minutes: 2,
      cook_time_minutes: 0,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'Casein Protein', 'Bedtime Recovery', 'High-Protein'],
      calories_per_serving: 190,
      protein_g_per_serving: 24,
      carbs_g_per_serving: 18,
      fat_g_per_serving: 2,
      icon_emoji: '🫐',
      ingredients: [
        {
          name: '2% Low-Fat Cottage Cheese',
          amount_imperial: '3/4 cup (6 oz)',
          amount_metric: '170g',
          raw_weight_grams_base: 170,
          calories_base: 140,
          protein_g_base: 22,
          carbs_g_base: 6,
          fat_g_base: 2.5,
          department: 'dairy_eggs',
          food_category: 'dairy_eggs',
        },
        {
          name: 'Fresh Wild Blueberries',
          amount_imperial: '1/2 cup',
          amount_metric: '75g',
          raw_weight_grams_base: 75,
          calories_base: 42,
          protein_g_base: 1,
          carbs_g_base: 10,
          fat_g_base: 0,
          department: 'produce',
          food_category: 'fruits',
        },
        {
          name: 'Ground Ceylon Cinnamon',
          amount_imperial: '1/4 tsp',
          amount_metric: '1g',
          raw_weight_grams_base: 1,
          calories_base: 3,
          protein_g_base: 0.1,
          carbs_g_base: 1,
          fat_g_base: 0,
          department: 'pantry_spices',
          food_category: 'pantry_staple',
        },
      ],
      instructions: [
        'Spoon cottage cheese into a chilled bowl.',
        'Top with fresh blueberries and dust with cinnamon.',
        'Enjoy as a nighttime snack or clean afternoon fuel.',
      ],
      chef_notes: 'Slow-digesting micellar casein feeds muscle amino acid pools over 6-7 hours while you sleep.',
    },
  },
  {
    id: 'apple-almond-butter',
    name: '🍎 Crisp Honeycrisp Apple & Raw Almond Butter',
    shortName: 'Apple & Almond Butter',
    desc: 'Sweet, chilled Honeycrisp apple slices paired with 2 tbsp of stoneground raw almond butter',
    cals: 210,
    protein_g: 5,
    carbs_g: 28,
    fat_g: 11,
    mealIndex: 4,
    category: 'snack',
    categoryLabel: 'Snack • Meal 4',
    foodName: 'Crisp Apple Slices with Pure Raw Almond Butter',
    grams: 180,
    emoji: '🍎',
    tags: ['Wholesome', 'Whole Fruit', 'Satisfying Crunch', 'Healthy Fats'],
    is_gluten_free: true,
    is_dairy_free: true,
    recipe: {
      id: 'wholesome-apple-almond-butter',
      title: 'Honeycrisp Apple Slices with Raw Almond Butter',
      description: 'Chilled sweet Honeycrisp apple slices paired with creamy stoneground raw almond butter and a pinch of cinnamon.',
      category: 'snack_dessert',
      sub_category: 'savory_crunch',
      prep_time_minutes: 3,
      cook_time_minutes: 0,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'Whole Fruit', 'Natural Crunch', 'Paleo'],
      calories_per_serving: 210,
      protein_g_per_serving: 5,
      carbs_g_per_serving: 28,
      fat_g_per_serving: 11,
      icon_emoji: '🍎',
      ingredients: [
        {
          name: 'Fresh Honeycrisp Apple (sliced)',
          amount_imperial: '1 medium',
          amount_metric: '150g',
          raw_weight_grams_base: 150,
          calories_base: 95,
          protein_g_base: 0.5,
          carbs_g_base: 24,
          fat_g_base: 0.3,
          department: 'produce',
          food_category: 'fruits',
        },
        {
          name: 'Raw Unsweetened Almond Butter',
          amount_imperial: '1.2 tbsp',
          amount_metric: '18g',
          raw_weight_grams_base: 18,
          calories_base: 115,
          protein_g_base: 4.5,
          carbs_g_base: 3.5,
          fat_g_base: 10,
          department: 'healthy_fats',
          food_category: 'nuts_fats_oils',
        },
      ],
      instructions: [
        'Core and slice Honeycrisp apple into thin crunchy wedges.',
        'Spoon almond butter into a dipping ramekin.',
        'Dip apple slices directly into almond butter.',
      ],
      chef_notes: 'Soluble pectin fiber in the apple slows digestion of natural sugars, avoiding blood glucose spikes.',
    },
  },
  {
    id: 'dark-chocolate-energy-bites',
    name: '🍫 Dark Chocolate & Oat Energy Bites',
    shortName: 'Dark Chocolate Energy Bites',
    desc: 'No-bake energy rounds made with rolled oats, dates, crushed almonds & 70% dark chocolate',
    cals: 190,
    protein_g: 8,
    carbs_g: 24,
    fat_g: 8,
    mealIndex: 4,
    category: 'snack',
    categoryLabel: 'Snack • Meal 4',
    foodName: 'No-Bake Rolled Oat & Dark Chocolate Energy Bites',
    grams: 60,
    emoji: '🍫',
    tags: ['Wholesome', 'Natural Energy', 'Pre-Workout', 'Wholesome Sweet'],
    is_gluten_free: true,
    is_dairy_free: true,
    recipe: {
      id: 'wholesome-dark-chocolate-energy-bites',
      title: 'No-Bake Rolled Oat & Dark Chocolate Energy Bites',
      description: 'Rolled oats, Medjool dates, natural peanut butter, and 70% dark chocolate chips rolled into satisfying bite-sized snack balls.',
      category: 'snack_dessert',
      sub_category: 'protein_bites_bars',
      prep_time_minutes: 8,
      cook_time_minutes: 0,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'Pre-Workout', 'Clean Energy', 'No-Bake'],
      calories_per_serving: 190,
      protein_g_per_serving: 8,
      carbs_g_per_serving: 24,
      fat_g_per_serving: 8,
      icon_emoji: '🍫',
      ingredients: [
        {
          name: 'Rolled Oats & Medjool Dates Paste',
          amount_imperial: '1/3 cup mix',
          amount_metric: '40g',
          raw_weight_grams_base: 40,
          calories_base: 110,
          protein_g_base: 3,
          carbs_g_base: 20,
          fat_g_base: 2,
          department: 'grains_bakery',
          food_category: 'grains_carbs',
        },
        {
          name: '70% Dark Chocolate Chips',
          amount_imperial: '1 tbsp',
          amount_metric: '12g',
          raw_weight_grams_base: 12,
          calories_base: 60,
          protein_g_base: 1,
          carbs_g_base: 6,
          fat_g_base: 4,
          department: 'pantry_spices',
          food_category: 'pantry_staple',
        },
        {
          name: 'Chia Seeds & Protein Powder',
          amount_imperial: '1 tsp',
          amount_metric: '6g',
          raw_weight_grams_base: 6,
          calories_base: 25,
          protein_g_base: 3.5,
          carbs_g_base: 1,
          fat_g_base: 1,
          department: 'supplements',
          food_category: 'protein',
        },
      ],
      instructions: [
        'Pulse oats, pitted dates, and peanut butter in a food processor until a cohesive dough forms.',
        'Stir in dark chocolate chips and chia seeds.',
        'Roll into 2 bite-sized rounds and chill in the fridge.',
      ],
      chef_notes: 'Provides sustained carbohydrates and flavanols 45 minutes before athletic training or lifting.',
    },
  },
  {
    id: 'steamed-edamame-pods',
    name: '🫛 Steamed Himalayan Pink Salt Edamame',
    shortName: 'Steamed Edamame Pods',
    desc: 'Warm tender young soybean pods sprinkled with coarse mineral-rich pink salt',
    cals: 160,
    protein_g: 14,
    carbs_g: 12,
    fat_g: 6,
    mealIndex: 4,
    category: 'snack',
    categoryLabel: 'Snack • Meal 4',
    foodName: 'Steamed Edamame Pods with Himalayan Pink Salt',
    grams: 150,
    emoji: '🫛',
    tags: ['Wholesome', 'Plant Protein', 'High-Fiber', 'Mineral-Rich'],
    is_gluten_free: true,
    is_dairy_free: true,
    recipe: {
      id: 'wholesome-steamed-edamame-pods',
      title: 'Steamed Himalayan Pink Salt Edamame Pods',
      description: 'Warm, tender young green soybean pods steamed fresh and tossed with coarse Himalayan pink mineral salt.',
      category: 'snack_dessert',
      sub_category: 'savory_crunch',
      prep_time_minutes: 2,
      cook_time_minutes: 4,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'Plant Protein', 'Whole Soybean', 'Clean Snack'],
      calories_per_serving: 160,
      protein_g_per_serving: 14,
      carbs_g_per_serving: 12,
      fat_g_per_serving: 6,
      icon_emoji: '🫛',
      ingredients: [
        {
          name: 'Whole Soybean Pods (Edamame in shell)',
          amount_imperial: '1.5 cups in shell',
          amount_metric: '150g',
          raw_weight_grams_base: 150,
          calories_base: 160,
          protein_g_base: 14,
          carbs_g_base: 12,
          fat_g_base: 6,
          department: 'frozen',
          food_category: 'plant_protein',
        },
        {
          name: 'Coarse Himalayan Pink Salt',
          amount_imperial: '1/2 tsp',
          amount_metric: '2g',
          raw_weight_grams_base: 2,
          calories_base: 0,
          protein_g_base: 0,
          carbs_g_base: 0,
          fat_g_base: 0,
          department: 'pantry_spices',
          food_category: 'pantry_staple',
        },
      ],
      instructions: [
        'Bring 2 cups of water to a boil in a covered pot with a pinch of salt.',
        'Add edamame pods and steam for 4 minutes until bright green and tender.',
        'Drain and toss in a bowl with coarse pink salt.',
      ],
      chef_notes: 'Eating edamame straight from the shell slows down consumption and provides full spectrum amino acids.',
    },
  },
  {
    id: 'cucumber-feta-dip',
    name: '🥒 Chilled Cucumbers & Greek Whipped Feta Dip',
    shortName: 'Cucumbers & Whipped Feta',
    desc: 'Crisp Persian cucumber wheels with lemon garlic whipped feta & Greek yogurt dip',
    cals: 150,
    protein_g: 8,
    carbs_g: 10,
    fat_g: 9,
    mealIndex: 4,
    category: 'snack',
    categoryLabel: 'Snack • Meal 4',
    foodName: 'Chilled Persian Cucumbers with Whipped Feta & Greek Yogurt',
    grams: 170,
    emoji: '🥒',
    tags: ['Wholesome', 'Hydrating', 'Low-Calorie', 'Savory Crunch'],
    is_gluten_free: true,
    is_dairy_free: false,
    recipe: {
      id: 'wholesome-cucumber-feta-dip',
      title: 'Chilled Persian Cucumbers with Lemon Whipped Feta Dip',
      description: 'Crisp mini Persian cucumber coins paired with tangy whipped Greek feta, nonfat yogurt, lemon juice, and dried oregano.',
      category: 'snack_dessert',
      sub_category: 'savory_crunch',
      prep_time_minutes: 5,
      cook_time_minutes: 0,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'Low-Calorie', 'Hydrating', 'Mediterranean'],
      calories_per_serving: 150,
      protein_g_per_serving: 8,
      carbs_g_per_serving: 10,
      fat_g_per_serving: 9,
      icon_emoji: '🥒',
      ingredients: [
        {
          name: 'Mini Persian Cucumbers (sliced)',
          amount_imperial: '2 whole cucumbers',
          amount_metric: '120g',
          raw_weight_grams_base: 120,
          calories_base: 20,
          protein_g_base: 1,
          carbs_g_base: 4,
          fat_g_base: 0.2,
          department: 'produce',
          food_category: 'vegetables',
        },
        {
          name: 'Greek Feta Cheese',
          amount_imperial: '1 oz (crumbled)',
          amount_metric: '28g',
          raw_weight_grams_base: 28,
          calories_base: 75,
          protein_g_base: 4,
          carbs_g_base: 1,
          fat_g_base: 6,
          department: 'dairy_eggs',
          food_category: 'dairy_eggs',
        },
        {
          name: 'Plain Greek Yogurt (0%) & Lemon Juice',
          amount_imperial: '2 tbsp',
          amount_metric: '30g',
          raw_weight_grams_base: 30,
          calories_base: 25,
          protein_g_base: 3,
          carbs_g_base: 1,
          fat_g_base: 0,
          department: 'dairy_eggs',
          food_category: 'dairy_eggs',
        },
        {
          name: 'Extra Virgin Olive Oil & Oregano',
          amount_imperial: '1/2 tsp',
          amount_metric: '2.5ml',
          raw_weight_grams_base: 2.5,
          calories_base: 25,
          protein_g_base: 0,
          carbs_g_base: 0,
          fat_g_base: 2.8,
          department: 'healthy_fats',
          food_category: 'nuts_fats_oils',
        },
      ],
      instructions: [
        'Whisk feta, Greek yogurt, olive oil, lemon juice, and oregano in a small bowl until creamy.',
        'Slice cucumbers into crisp rounds.',
        'Dip chilled cucumber rounds into the whipped feta.',
      ],
      chef_notes: 'A savory, crunchy alternative to chips with 95% water volume for deep cellular hydration.',
    },
  },
  {
    id: 'banana-whey-shake',
    name: '🍌 Banana Whey Protein Recovery Shake',
    shortName: 'Banana Whey Shake',
    desc: 'Cold blended whey protein isolate, half banana, and unsweetened vanilla almond milk',
    cals: 260,
    protein_g: 30,
    carbs_g: 30,
    fat_g: 2,
    mealIndex: 4,
    category: 'snack',
    categoryLabel: 'Snack • Meal 4',
    foodName: 'Banana Whey Protein Recovery Shake',
    grams: 320,
    emoji: '🍌',
    tags: ['Wholesome', 'Post-Workout', 'Rapid Recovery', 'High Protein'],
    is_gluten_free: true,
    is_dairy_free: true,
    recipe: {
      id: 'wholesome-banana-whey-shake',
      title: 'Banana Cream Whey Protein Recovery Shake',
      description: 'Cold blended whey protein isolate with ripe banana, unsweetened almond milk, and a dusting of cinnamon for rapid post-workout replenishment.',
      category: 'snack_dessert',
      sub_category: 'sweet_treats',
      prep_time_minutes: 3,
      cook_time_minutes: 0,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'High-Protein', 'Post-Workout', 'Fast Digesting'],
      calories_per_serving: 260,
      protein_g_per_serving: 30,
      carbs_g_per_serving: 30,
      fat_g_per_serving: 2,
      icon_emoji: '🍌',
      ingredients: [
        {
          name: 'Whey Protein Isolate (Vanilla or Chocolate)',
          amount_imperial: '1 rounded scoop',
          amount_metric: '32g',
          raw_weight_grams_base: 32,
          calories_base: 130,
          protein_g_base: 27,
          carbs_g_base: 2,
          fat_g_base: 1,
          department: 'supplements',
          food_category: 'protein',
        },
        {
          name: 'Ripe Yellow Banana',
          amount_imperial: '1 medium',
          amount_metric: '100g',
          raw_weight_grams_base: 100,
          calories_base: 95,
          protein_g_base: 1.2,
          carbs_g_base: 24,
          fat_g_base: 0.3,
          department: 'produce',
          food_category: 'fruits',
        },
        {
          name: 'Unsweetened Almond Milk',
          amount_imperial: '1 cup (8 oz)',
          amount_metric: '240ml',
          raw_weight_grams_base: 240,
          calories_base: 35,
          protein_g_base: 1,
          carbs_g_base: 1,
          fat_g_base: 2.5,
          department: 'dairy_eggs',
          food_category: 'dairy_alternative',
        },
      ],
      instructions: [
        'Add almond milk to the shaker cup or blender first.',
        'Add broken banana chunks and whey protein isolate.',
        'Blend on high for 30 seconds until smooth, frothy, and creamy.',
      ],
      chef_notes: 'Quick-absorbing fast carbohydrates replenish depleted muscle glycogen within the critical post-exercise window.',
    },
  },
  {
    id: 'mixed-raw-nuts-cranberries',
    name: '🥜 Artisan Raw Almond, Walnut & Cranberry Mix',
    shortName: 'Almonds, Walnuts & Cranberries',
    desc: 'Dry-roasted California almonds, English walnuts, and tart ruby cranberries',
    cals: 220,
    protein_g: 6,
    carbs_g: 16,
    fat_g: 16,
    mealIndex: 4,
    category: 'snack',
    categoryLabel: 'Snack • Meal 4',
    foodName: 'Raw Almonds, Walnuts & Dried Cranberries Trail Mix',
    grams: 45,
    emoji: '🥜',
    tags: ['Wholesome', 'Brain Healthy Fats', 'Antioxidants', 'Portable Fuel'],
    is_gluten_free: true,
    is_dairy_free: true,
    recipe: {
      id: 'wholesome-mixed-raw-nuts-cranberries',
      title: 'Artisan Raw Almond, Walnut & Ruby Cranberry Trail Mix',
      description: 'Raw California almonds, brain-healthy English walnuts, and antioxidant-rich dried ruby cranberries.',
      category: 'snack_dessert',
      sub_category: 'savory_crunch',
      prep_time_minutes: 1,
      cook_time_minutes: 0,
      servings_yield: 1,
      difficulty: 'easy',
      tags: ['Wholesome', 'Brain Healthy', 'Clean Fats', 'Portable'],
      calories_per_serving: 220,
      protein_g_per_serving: 6,
      carbs_g_per_serving: 16,
      fat_g_per_serving: 16,
      icon_emoji: '🥜',
      ingredients: [
        {
          name: 'Raw California Almonds',
          amount_imperial: '1 oz (about 20 nuts)',
          amount_metric: '25g',
          raw_weight_grams_base: 25,
          calories_base: 140,
          protein_g_base: 5,
          carbs_g_base: 5,
          fat_g_base: 12,
          department: 'healthy_fats',
          food_category: 'nuts_fats_oils',
        },
        {
          name: 'Raw English Walnut Halves',
          amount_imperial: '1/2 oz',
          amount_metric: '10g',
          raw_weight_grams_base: 10,
          calories_base: 65,
          protein_g_base: 1.5,
          carbs_g_base: 1.5,
          fat_g_base: 6.5,
          department: 'healthy_fats',
          food_category: 'nuts_fats_oils',
        },
        {
          name: 'Dried Ruby Cranberries',
          amount_imperial: '1 tbsp',
          amount_metric: '10g',
          raw_weight_grams_base: 10,
          calories_base: 30,
          protein_g_base: 0.1,
          carbs_g_base: 8,
          fat_g_base: 0.1,
          department: 'produce',
          food_category: 'fruits',
        },
      ],
      instructions: [
        'Measure portions into a small snack pouch or palm.',
        'Enjoy slowly with cold water for clean sustained cognitive energy.',
      ],
      chef_notes: 'Walnuts contain the plant omega-3 alpha-linolenic acid (ALA) for cellular resilience.',
    },
  },
];

// All 28 recipes ready to extend the Recipe Section
export const WHOLESOME_RECIPE_ITEMS: RecipeItem[] = WHOLESOME_MEAL_CATALOG.map((m) => m.recipe);

// Partition by category
export const BREAKFAST_MEALS = WHOLESOME_MEAL_CATALOG.filter((m) => m.category === 'breakfast');
export const LUNCH_MEALS = WHOLESOME_MEAL_CATALOG.filter((m) => m.category === 'lunch');
export const DINNER_MEALS = WHOLESOME_MEAL_CATALOG.filter((m) => m.category === 'dinner');
export const SNACK_MEALS = WHOLESOME_MEAL_CATALOG.filter((m) => m.category === 'snack');

/**
 * Deterministically retrieves 4 balanced wholesome meals for a specific date (Breakfast, Lunch, Dinner, Snack).
 * Automatically changes each calendar day. Supports manual shuffle offset to cycle combinations.
 */
export function getDailyWholesomeMeals(
  dateStr: string = new Date().toISOString().split('T')[0],
  shuffleOffset: number = 0
): WholesomeMeal[] {
  let hash = 0;
  for (let i = 0; i < dateStr.length; i++) {
    hash = (hash << 5) - hash + dateStr.charCodeAt(i);
    hash |= 0;
  }
  const baseSeed = Math.abs(hash) + shuffleOffset;

  const bIndex = (baseSeed + 0) % BREAKFAST_MEALS.length;
  const lIndex = (baseSeed + 2) % LUNCH_MEALS.length;
  const dIndex = (baseSeed + 4) % DINNER_MEALS.length;
  const sIndex = (baseSeed + 6) % SNACK_MEALS.length;

  return [
    BREAKFAST_MEALS[bIndex],
    LUNCH_MEALS[lIndex],
    DINNER_MEALS[dIndex],
    SNACK_MEALS[sIndex],
  ];
}

export interface SmartMealSuggestion {
  meal: WholesomeMeal;
  reason: string;
  periodLabel: string;
  timingHint: string;
}

/**
 * Intelligent suggestion engine that recommends a wholesome meal tailored to:
 * 1. Current time of day (Breakfast, Lunch, Dinner, Snack)
 * 2. Remaining calorie budget
 * 3. Fasting status
 */
export function getSmartWholesomeSuggestion(options?: {
  remainingCalories?: number;
  isFasting?: boolean;
  currentHour?: number;
  suggestionIndex?: number;
}): SmartMealSuggestion {
  const currentHour = options?.currentHour ?? new Date().getHours();
  const remainingCals = options?.remainingCalories ?? 1800;
  const isFasting = options?.isFasting ?? false;
  const index = Math.abs(options?.suggestionIndex ?? 0);

  let targetPool: WholesomeMeal[];
  let periodLabel: string;
  let timingHint: string;
  let reason: string;

  if (isFasting) {
    targetPool = [...BREAKFAST_MEALS, ...SNACK_MEALS];
    periodLabel = 'Gentle Fast-Breaker';
    timingHint = 'Ideal for opening your eating window with clean whole food';
    reason = 'Gentle on digestion, nutrient-dense, and curbs cravings after fasting.';
  } else if (currentHour < 11) {
    targetPool = BREAKFAST_MEALS;
    periodLabel = 'Morning Fuel • Breakfast';
    timingHint = 'High protein & complex carbs to start your day strong';
    const cand = targetPool[index % targetPool.length];
    reason = `Kickstarts your metabolism with ${cand.protein_g}g protein and clean morning energy.`;
  } else if (currentHour >= 11 && currentHour < 16) {
    targetPool = LUNCH_MEALS;
    periodLabel = 'Midday Energy • Power Lunch';
    timingHint = 'Sustained energy to power through the afternoon without a crash';
    const cand = targetPool[index % targetPool.length];
    reason = `Macro-balanced power plate with clean carbs and ${cand.protein_g}g lean protein.`;
  } else if (currentHour >= 16 && currentHour < 21) {
    if (remainingCals < 450) {
      targetPool = [...DINNER_MEALS.filter((d) => d.cals <= 460), ...LUNCH_MEALS.filter((l) => l.cals <= 450)];
      periodLabel = 'Light Evening Plate • Dinner';
      timingHint = 'High protein, lower calories to stay within your daily goal';
      reason = `Calorie-conscious dinner perfectly fitting your remaining ~${remainingCals} kcal budget.`;
    } else {
      targetPool = DINNER_MEALS;
      periodLabel = 'Evening Nourishment • Dinner';
      timingHint = 'Nourishes deep muscle recovery and restores glycogen stores';
      const cand = targetPool[index % targetPool.length];
      reason = `Satisfying evening plate delivering ${cand.protein_g}g protein for overnight recovery.`;
    }
  } else {
    targetPool = SNACK_MEALS;
    periodLabel = 'Late Evening • Recovery Fuel';
    timingHint = 'Light, slow-digesting protein to support overnight rest';
    const cand = targetPool[index % targetPool.length];
    reason = `A light, wholesome bite under ${cand.cals} kcal to satisfy cravings without feeling heavy.`;
  }

  const selectedMeal = targetPool[index % targetPool.length];

  return {
    meal: selectedMeal,
    reason,
    periodLabel,
    timingHint,
  };
}

/**
 * Converts a WholesomeMeal into a valid FoodItem object for the logging engine.
 */
export function createFoodItemFromWholesomeMeal(
  meal: WholesomeMeal,
  customMacros?: { calories: number; protein_g: number; carbs_g: number; fat_g: number; name?: string }
): FoodItem {
  const cals = customMacros?.calories ?? meal.cals;
  const protein = customMacros?.protein_g ?? meal.protein_g;
  const carbs = customMacros?.carbs_g ?? meal.carbs_g;
  const fat = customMacros?.fat_g ?? meal.fat_g;
  const name = customMacros?.name ?? meal.foodName;

  return {
    id: `wholesome-${meal.id}`,
    name,
    category: 'protein',
    sub_category: meal.category,
    calories_per_100g: Math.round((cals / meal.grams) * 100),
    protein_per_100g: Number(((protein / meal.grams) * 100).toFixed(1)),
    carbs_per_100g: Number(((carbs / meal.grams) * 100).toFixed(1)),
    fat_per_100g: Number(((fat / meal.grams) * 100).toFixed(1)),
    is_gluten_free: meal.is_gluten_free,
    is_dairy_free: meal.is_dairy_free,
    serving_size_g: meal.grams,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
  };
}
