import { FoodItem } from '../types';

export const BEVERAGES_HYDRATION_DATABASE: FoodItem[] = [
  {
    "id": "bv-cof-001",
    "name": "Fresh Brewed Black Drip Coffee (Medium Roast Arabica)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 1,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-cof-002",
    "name": "Cold Brew Coffee (Black Steeped Concentrate)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 2,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-cof-003",
    "name": "Espresso (Single Shot 1 oz)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 9,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 1.7,
    "fat_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-cof-004",
    "name": "Espresso (Double Shot Doppio 2 oz)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 9,
    "protein_per_100g": 0.2,
    "carbs_per_100g": 1.7,
    "fat_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 60,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-cof-005",
    "name": "Caffè Americano (Espresso + Hot Water)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 2,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.3,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-cof-006",
    "name": "Decaffeinated Swiss Water Process Drip Coffee",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 1,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-cof-007",
    "name": "Nitro Cold Brew Coffee (Draft Infused Creamy Head)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 2,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 350,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-cof-008",
    "name": "Caffè Latte with Skim Milk (Tall 12 oz)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 38,
    "protein_per_100g": 3.5,
    "carbs_per_100g": 5,
    "fat_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 350,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "milk_dairy"
  },
  {
    "id": "bv-cof-009",
    "name": "Caffè Latte with Unsweetened Almond Milk (Tall 12 oz)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 18,
    "protein_per_100g": 0.8,
    "carbs_per_100g": 1.2,
    "fat_per_100g": 1.1,
    "fiber_per_100g": 0.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 350,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "plant_milk"
  },
  {
    "id": "bv-cof-010",
    "name": "Caffè Latte with Oat Milk (Tall 12 oz)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 48,
    "protein_per_100g": 1.5,
    "carbs_per_100g": 7,
    "fat_per_100g": 1.6,
    "fiber_per_100g": 0.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 350,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "plant_milk"
  },
  {
    "id": "bv-cof-011",
    "name": "Cappuccino with Whole Milk (6 oz Traditional)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 45,
    "protein_per_100g": 2.5,
    "carbs_per_100g": 3.5,
    "fat_per_100g": 2.3,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 180,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "milk_dairy"
  },
  {
    "id": "bv-tea-001",
    "name": "Organic Ceremonial Grade Japanese Matcha Green Tea (Whisked in Hot Water)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 3,
    "protein_per_100g": 0.3,
    "carbs_per_100g": 0.4,
    "fat_per_100g": 0,
    "fiber_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-002",
    "name": "Japanese Sencha Green Tea (Loose Leaf Brewed)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-003",
    "name": "Japanese Gyokuro Shade-Grown Green Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-004",
    "name": "Genmaicha (Green Tea with Toasted Brown Rice)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-005",
    "name": "Hojicha (Roasted Japanese Green Tea)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.1,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-006",
    "name": "Jasmine Blossom Green Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-007",
    "name": "English Breakfast Black Tea (Brewed Unsweetened)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.3,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-008",
    "name": "Earl Grey Black Tea (Bergamot Infused)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.3,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-009",
    "name": "Assam Black Tea (Single Estate Malty)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.3,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-010",
    "name": "Darjeeling First Flush Black Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-011",
    "name": "Formosa Oolong Tea (Semi-Oxidized Brewed)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-012",
    "name": "Ti Kuan Yin Iron Goddess Oolong Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-013",
    "name": "Silver Needle Pure White Tea (Bai Hao Yin Zhen)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-014",
    "name": "Aged Pu-erh Fermented Dark Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 2,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.3,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-015",
    "name": "Yerba Mate (Traditional Argentine Brewed)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 2,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.4,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-016",
    "name": "Peppermint Pure Herbal Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-017",
    "name": "Spearmint Pure Herbal Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-018",
    "name": "Chamomile Flower Herbal Infusion (Caffeine-Free Sleep)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-019",
    "name": "Rooibos Red Bush Tea (South African Caffeine-Free)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-020",
    "name": "Hibiscus Flower Tea / Agua de Jamaica (Ruby Tart)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.3,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-021",
    "name": "Ginger Turmeric Root Herbal Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 2,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.4,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-022",
    "name": "Holy Basil / Tulsi Herbal Stress Relief Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-023",
    "name": "Lemon Verbena Herbal Infusion",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-wtr-001",
    "name": "Pure Filtered Drinking Water",
    "category": "beverages_hydration",
    "sub_category": "waters_sparkling",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-wtr-002",
    "name": "Gerolsteiner Natural Sparkling Mineral Water (High Calcium & Magnesium)",
    "category": "beverages_hydration",
    "sub_category": "waters_sparkling",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 330,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-wtr-003",
    "name": "San Pellegrino Sparkling Natural Mineral Water (Italian Bottle)",
    "category": "beverages_hydration",
    "sub_category": "waters_sparkling",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 330,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-wtr-004",
    "name": "Topo Chico Carbonated Mineral Water (Glass Bottle)",
    "category": "beverages_hydration",
    "sub_category": "waters_sparkling",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 355,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-wtr-005",
    "name": "Perrier Sparkling Natural Mineral Water",
    "category": "beverages_hydration",
    "sub_category": "waters_sparkling",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 330,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-wtr-006",
    "name": "Lemon Essence Sparkling Seltzer Water (0 Calorie LaCroix/Spindrift style)",
    "category": "beverages_hydration",
    "sub_category": "waters_sparkling",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 355,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-wtr-007",
    "name": "Grapefruit Essence Sparkling Water (0 Calorie)",
    "category": "beverages_hydration",
    "sub_category": "waters_sparkling",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 355,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-wtr-008",
    "name": "Lime Essence Sparkling Water (0 Calorie)",
    "category": "beverages_hydration",
    "sub_category": "waters_sparkling",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 355,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-fun-001",
    "name": "100% Pure Organic Coconut Water (Harmless Harvest Pink)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 19,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 3.7,
    "fat_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-fun-002",
    "name": "Zero-Sugar Electrolyte Hydration Drink (LMNT / Liquid I.V. Zero Sodium-Potassium)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 2,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.5,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 480,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-fun-003",
    "name": "Organic Chicken Bone Broth (Simmered 24h High Collagen Kettle & Fire)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 19,
    "protein_per_100g": 4.2,
    "carbs_per_100g": 0,
    "fat_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "bv-fun-004",
    "name": "Grass-Fed Beef Bone Broth (Simmered 24h Kettle & Fire)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 21,
    "protein_per_100g": 4.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 0.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "bv-fun-005",
    "name": "Free-Range Turkey Bone Broth (Rich Gelatin)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 19,
    "protein_per_100g": 4.2,
    "carbs_per_100g": 0,
    "fat_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "bv-fun-006",
    "name": "Raw Fermented Ginger Kombucha (Low Sugar <2g GT's Synergy)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 13,
    "protein_per_100g": 0,
    "carbs_per_100g": 3.3,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 350,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-fun-007",
    "name": "100% Pure Tart Cherry Juice (Sleep & Recovery Tonic Cheribundi)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 54,
    "protein_per_100g": 0.5,
    "carbs_per_100g": 13.5,
    "fat_per_100g": 0.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "bv-fun-008",
    "name": "Organic Raw Apple Cider Vinegar Tonic (Bragg with Mother)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 21,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.9,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 15,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "condiment"
  },
  {
    "id": "bv-ext-001",
    "name": "Pour-Over Chemex Single-Origin Ethiopian Light Roast Coffee",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 1,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-002",
    "name": "French Press Dark Roast Colombian Coffee",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 2,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.1,
    "fat_per_100g": 0.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-003",
    "name": "Flat White Coffee with Skim Milk (8 oz)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 35,
    "protein_per_100g": 3.5,
    "carbs_per_100g": 4.8,
    "fat_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "milk_dairy"
  },
  {
    "id": "bv-ext-004",
    "name": "Cortado Coffee (Equal Parts Espresso & Steamed Whole Milk 4 oz)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 40,
    "protein_per_100g": 2,
    "carbs_per_100g": 3,
    "fat_per_100g": 2.2,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 120,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "milk_dairy"
  },
  {
    "id": "bv-ext-005",
    "name": "Iced Shaken Espresso with Unsweetened Oat Milk",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 30,
    "protein_per_100g": 0.8,
    "carbs_per_100g": 4.5,
    "fat_per_100g": 1,
    "fiber_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 350,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "plant_milk"
  },
  {
    "id": "bv-ext-006",
    "name": "Black Cherry Essence Sparkling Water (0 Calorie)",
    "category": "beverages_hydration",
    "sub_category": "waters_sparkling",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 355,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-007",
    "name": "Cucumber Mint Natural Essence Seltzer",
    "category": "beverages_hydration",
    "sub_category": "waters_sparkling",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 355,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-008",
    "name": "Dragonfruit Sparkling Mineral Water (Spindrift Real Fruit)",
    "category": "beverages_hydration",
    "sub_category": "waters_sparkling",
    "calories_per_100g": 3,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.8,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 355,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-009",
    "name": "100% Pure Coconut Water with Pineapple Juice",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 22,
    "protein_per_100g": 0.5,
    "carbs_per_100g": 4.8,
    "fat_per_100g": 0.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-010",
    "name": "Pure Organic Aloe Vera Hydration Juice Drink (Unsweetened George's)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 4,
    "protein_per_100g": 0,
    "carbs_per_100g": 1,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-011",
    "name": "Organic Simmered Vegetable Mineral Broth (Mirepoix & Sea Salt)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 10,
    "protein_per_100g": 0.5,
    "carbs_per_100g": 1.8,
    "fat_per_100g": 0.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "bv-ext-012",
    "name": "Traditional Miso Sipping Broth (Shiro Miso & Wakame)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 18,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 2.5,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-013",
    "name": "Roasted Dandelion Root Coffee-Alternative Herbal Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 2,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.4,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-014",
    "name": "Organic Stinging Nettle Leaf Mineral Herbal Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-015",
    "name": "Fennel Seed & Peppermint Digestive Herbal Infusion",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.3,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-016",
    "name": "Valerian Root & Passionflower Deep Sleep Herbal Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-017",
    "name": "Guayusa Organic Amazonian Energy Leaf Brewed",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 2,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.4,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-018",
    "name": "Raw Passionfruit Guava Kombucha (Live Probiotics)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 14,
    "protein_per_100g": 0,
    "carbs_per_100g": 3.5,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 350,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-019",
    "name": "Water Kefir Cultured Lemon Ginger Probiotic Soda",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 12,
    "protein_per_100g": 0,
    "carbs_per_100g": 3,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 350,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-rtd-fl-001",
    "name": "Fairlife Core Power Elite High Protein Shake - Chocolate (42g Protein)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 56,
    "protein_per_100g": 10.1,
    "carbs_per_100g": 1.9,
    "fat_per_100g": 0.8,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 414,
    "default_unit": "bottle (14 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Fairlife",
    "fiber_per_100g": 0.2,
    "sugar_per_100g": 1.7,
    "saturated_fat_per_100g": 0.5,
    "sodium_per_100g": 80,
    "potassium_per_100g": 205,
    "calcium_per_100g": 217,
    "iron_per_100g": 0.4
  },
  {
    "id": "bv-rtd-fl-002",
    "name": "Fairlife Core Power Elite High Protein Shake - Vanilla (42g Protein)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 56,
    "protein_per_100g": 10.1,
    "carbs_per_100g": 1.9,
    "fat_per_100g": 0.8,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 414,
    "default_unit": "bottle (14 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Fairlife",
    "fiber_per_100g": 0,
    "sugar_per_100g": 1.7,
    "saturated_fat_per_100g": 0.5,
    "sodium_per_100g": 75,
    "potassium_per_100g": 193,
    "calcium_per_100g": 217,
    "iron_per_100g": 0.1
  },
  {
    "id": "bv-rtd-fl-003",
    "name": "Fairlife Core Power Elite High Protein Shake - Strawberry Banana (42g Protein)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 56,
    "protein_per_100g": 10.1,
    "carbs_per_100g": 1.9,
    "fat_per_100g": 0.8,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 414,
    "default_unit": "bottle (14 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Fairlife",
    "fiber_per_100g": 0,
    "sugar_per_100g": 1.7,
    "saturated_fat_per_100g": 0.5,
    "sodium_per_100g": 75,
    "potassium_per_100g": 193,
    "calcium_per_100g": 217,
    "iron_per_100g": 0.1
  },
  {
    "id": "bv-rtd-fl-004",
    "name": "Fairlife Core Power 26g High Protein Shake - Chocolate",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 41,
    "protein_per_100g": 6.3,
    "carbs_per_100g": 1.7,
    "fat_per_100g": 1.1,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 414,
    "default_unit": "bottle (14 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Fairlife",
    "fiber_per_100g": 0.2,
    "sugar_per_100g": 1.2,
    "saturated_fat_per_100g": 0.6,
    "sodium_per_100g": 68,
    "potassium_per_100g": 169,
    "calcium_per_100g": 169,
    "iron_per_100g": 0.2
  },
  {
    "id": "bv-rtd-fl-005",
    "name": "Fairlife Core Power 26g High Protein Shake - Vanilla",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 41,
    "protein_per_100g": 6.3,
    "carbs_per_100g": 1.4,
    "fat_per_100g": 1.1,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 414,
    "default_unit": "bottle (14 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Fairlife",
    "fiber_per_100g": 0,
    "sugar_per_100g": 1.2,
    "saturated_fat_per_100g": 0.6,
    "sodium_per_100g": 63,
    "potassium_per_100g": 157,
    "calcium_per_100g": 169,
    "iron_per_100g": 0.1
  },
  {
    "id": "bv-rtd-fl-006",
    "name": "Fairlife Nutrition Plan High Protein Shake - Chocolate (30g Protein)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 44,
    "protein_per_100g": 8.8,
    "carbs_per_100g": 0.9,
    "fat_per_100g": 0.7,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 340,
    "default_unit": "bottle (11.5 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Fairlife",
    "fiber_per_100g": 0.3,
    "sugar_per_100g": 0.6,
    "saturated_fat_per_100g": 0.4,
    "sodium_per_100g": 62,
    "potassium_per_100g": 147,
    "calcium_per_100g": 191,
    "iron_per_100g": 0.3
  },
  {
    "id": "bv-rtd-fl-007",
    "name": "Fairlife Nutrition Plan High Protein Shake - Vanilla (30g Protein)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 44,
    "protein_per_100g": 8.8,
    "carbs_per_100g": 0.9,
    "fat_per_100g": 0.7,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 340,
    "default_unit": "bottle (11.5 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Fairlife",
    "fiber_per_100g": 0,
    "sugar_per_100g": 0.6,
    "saturated_fat_per_100g": 0.4,
    "sodium_per_100g": 59,
    "potassium_per_100g": 138,
    "calcium_per_100g": 191,
    "iron_per_100g": 0.1
  },
  {
    "id": "bv-rtd-fl-008",
    "name": "Fairlife Nutrition Plan High Protein Shake - Salted Caramel (30g Protein)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 44,
    "protein_per_100g": 8.8,
    "carbs_per_100g": 0.9,
    "fat_per_100g": 0.7,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 340,
    "default_unit": "bottle (11.5 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Fairlife",
    "fiber_per_100g": 0,
    "sugar_per_100g": 0.6,
    "saturated_fat_per_100g": 0.4,
    "sodium_per_100g": 76,
    "potassium_per_100g": 141,
    "calcium_per_100g": 191,
    "iron_per_100g": 0.1
  },
  {
    "id": "bv-rtd-fl-009",
    "name": "Fairlife Nutrition Plan High Protein Shake - Coffee with 100mg Caffeine (30g Protein)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 44,
    "protein_per_100g": 8.8,
    "carbs_per_100g": 0.9,
    "fat_per_100g": 0.7,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 340,
    "default_unit": "bottle (11.5 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Fairlife",
    "fiber_per_100g": 0,
    "sugar_per_100g": 0.6,
    "saturated_fat_per_100g": 0.4,
    "sodium_per_100g": 62,
    "potassium_per_100g": 150,
    "calcium_per_100g": 191,
    "iron_per_100g": 0.1
  },
  {
    "id": "bv-rtd-prm-001",
    "name": "Premier Protein 30g High Protein Shake - Chocolate",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 47,
    "protein_per_100g": 8.8,
    "carbs_per_100g": 1.2,
    "fat_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 340,
    "default_unit": "carton (11.5 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Premier Protein",
    "fiber_per_100g": 0.3,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.1,
    "sodium_per_100g": 68,
    "potassium_per_100g": 132,
    "calcium_per_100g": 191,
    "iron_per_100g": 1.3
  },
  {
    "id": "bv-rtd-prm-002",
    "name": "Premier Protein 30g High Protein Shake - Vanilla",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 47,
    "protein_per_100g": 8.8,
    "carbs_per_100g": 0.9,
    "fat_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 340,
    "default_unit": "carton (11.5 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Premier Protein",
    "fiber_per_100g": 0.3,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.1,
    "sodium_per_100g": 62,
    "potassium_per_100g": 118,
    "calcium_per_100g": 191,
    "iron_per_100g": 1.3
  },
  {
    "id": "bv-rtd-prm-003",
    "name": "Premier Protein 30g High Protein Shake - Cafe Latte (with Caffeine)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 47,
    "protein_per_100g": 8.8,
    "carbs_per_100g": 1.2,
    "fat_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 340,
    "default_unit": "carton (11.5 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Premier Protein",
    "fiber_per_100g": 0.3,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.1,
    "sodium_per_100g": 65,
    "potassium_per_100g": 132,
    "calcium_per_100g": 191,
    "iron_per_100g": 1.3
  },
  {
    "id": "bv-rtd-prm-004",
    "name": "Premier Protein 30g High Protein Shake - Caramel",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 47,
    "protein_per_100g": 8.8,
    "carbs_per_100g": 1.2,
    "fat_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 340,
    "default_unit": "carton (11.5 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Premier Protein",
    "fiber_per_100g": 0.3,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.1,
    "sodium_per_100g": 106,
    "potassium_per_100g": 124,
    "calcium_per_100g": 191,
    "iron_per_100g": 1.3
  },
  {
    "id": "bv-rtd-prm-005",
    "name": "Premier Protein 30g High Protein Shake - Strawberries & Cream",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 47,
    "protein_per_100g": 8.8,
    "carbs_per_100g": 0.9,
    "fat_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 340,
    "default_unit": "carton (11.5 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Premier Protein",
    "fiber_per_100g": 0.3,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.1,
    "sodium_per_100g": 62,
    "potassium_per_100g": 121,
    "calcium_per_100g": 191,
    "iron_per_100g": 1.3
  },
  {
    "id": "bv-rtd-prm-006",
    "name": "Premier Protein 30g High Protein Shake - Bananas & Cream",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 47,
    "protein_per_100g": 8.8,
    "carbs_per_100g": 1.2,
    "fat_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 340,
    "default_unit": "carton (11.5 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Premier Protein",
    "fiber_per_100g": 0.3,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.1,
    "sodium_per_100g": 62,
    "potassium_per_100g": 126,
    "calcium_per_100g": 191,
    "iron_per_100g": 1.3
  },
  {
    "id": "bv-rtd-prm-007",
    "name": "Premier Protein 30g High Protein Shake - Cookies & Cream",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 47,
    "protein_per_100g": 8.8,
    "carbs_per_100g": 1.2,
    "fat_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 340,
    "default_unit": "carton (11.5 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Premier Protein",
    "fiber_per_100g": 0.3,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.1,
    "sodium_per_100g": 68,
    "potassium_per_100g": 124,
    "calcium_per_100g": 191,
    "iron_per_100g": 1.3
  },
  {
    "id": "bv-rtd-prm-008",
    "name": "Premier Protein 30g High Protein Shake - Cinnamon Roll",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 47,
    "protein_per_100g": 8.8,
    "carbs_per_100g": 1.2,
    "fat_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 340,
    "default_unit": "carton (11.5 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Premier Protein",
    "fiber_per_100g": 0.3,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.1,
    "sodium_per_100g": 68,
    "potassium_per_100g": 121,
    "calcium_per_100g": 191,
    "iron_per_100g": 1.3
  },
  {
    "id": "bv-rtd-prm-009",
    "name": "Premier Protein 30g High Protein Shake - Chocolate Peanut Butter",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 47,
    "protein_per_100g": 8.8,
    "carbs_per_100g": 1.2,
    "fat_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 340,
    "default_unit": "carton (11.5 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Premier Protein",
    "fiber_per_100g": 0.3,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.1,
    "sodium_per_100g": 74,
    "potassium_per_100g": 135,
    "calcium_per_100g": 191,
    "iron_per_100g": 1.3
  },
  {
    "id": "bv-rtd-atk-001",
    "name": "Atkins Plus 30g High Protein Shake - Creamy Chocolate (7g Fiber, 1g Sugar)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 58,
    "protein_per_100g": 9.2,
    "carbs_per_100g": 2.5,
    "fat_per_100g": 1.4,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 325,
    "default_unit": "carton (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Atkins",
    "fiber_per_100g": 2.2,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.5,
    "sodium_per_100g": 80,
    "potassium_per_100g": 200,
    "calcium_per_100g": 246,
    "iron_per_100g": 1.4
  },
  {
    "id": "bv-rtd-atk-002",
    "name": "Atkins Plus 30g High Protein Shake - Creamy Vanilla (7g Fiber, 1g Sugar)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 58,
    "protein_per_100g": 9.2,
    "carbs_per_100g": 2.5,
    "fat_per_100g": 1.4,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 325,
    "default_unit": "carton (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Atkins",
    "fiber_per_100g": 2.2,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.5,
    "sodium_per_100g": 74,
    "potassium_per_100g": 185,
    "calcium_per_100g": 246,
    "iron_per_100g": 1.4
  },
  {
    "id": "bv-rtd-atk-003",
    "name": "Atkins Meal 15g Protein Shake - Milk Chocolate Delight (5g Fiber, 1g Sugar)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 49,
    "protein_per_100g": 4.6,
    "carbs_per_100g": 2.2,
    "fat_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 325,
    "default_unit": "carton (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Atkins",
    "fiber_per_100g": 1.5,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.8,
    "sodium_per_100g": 62,
    "potassium_per_100g": 154,
    "calcium_per_100g": 185,
    "iron_per_100g": 1.2
  },
  {
    "id": "bv-rtd-atk-004",
    "name": "Atkins Meal 15g Protein Shake - Dark Chocolate Royale (5g Fiber, 1g Sugar)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 49,
    "protein_per_100g": 4.6,
    "carbs_per_100g": 1.8,
    "fat_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 325,
    "default_unit": "carton (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Atkins",
    "fiber_per_100g": 1.5,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.8,
    "sodium_per_100g": 65,
    "potassium_per_100g": 160,
    "calcium_per_100g": 185,
    "iron_per_100g": 1.4
  },
  {
    "id": "bv-rtd-atk-005",
    "name": "Atkins Meal 15g Protein Shake - French Vanilla (5g Fiber, 1g Sugar)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 49,
    "protein_per_100g": 4.6,
    "carbs_per_100g": 1.8,
    "fat_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 325,
    "default_unit": "carton (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Atkins",
    "fiber_per_100g": 1.5,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.8,
    "sodium_per_100g": 58,
    "potassium_per_100g": 138,
    "calcium_per_100g": 185,
    "iron_per_100g": 1.1
  },
  {
    "id": "bv-rtd-atk-006",
    "name": "Atkins Meal 15g Protein Shake - Strawberry (5g Fiber, 1g Sugar)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 49,
    "protein_per_100g": 4.6,
    "carbs_per_100g": 1.8,
    "fat_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 325,
    "default_unit": "carton (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Atkins",
    "fiber_per_100g": 1.5,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.8,
    "sodium_per_100g": 58,
    "potassium_per_100g": 142,
    "calcium_per_100g": 185,
    "iron_per_100g": 1.1
  },
  {
    "id": "bv-rtd-atk-007",
    "name": "Atkins Meal 15g Protein Shake - Cafe Caramel with Caffeine (5g Fiber)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 49,
    "protein_per_100g": 4.6,
    "carbs_per_100g": 1.8,
    "fat_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 325,
    "default_unit": "carton (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Atkins",
    "fiber_per_100g": 1.5,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.8,
    "sodium_per_100g": 71,
    "potassium_per_100g": 148,
    "calcium_per_100g": 185,
    "iron_per_100g": 1.1
  },
  {
    "id": "bv-rtd-atk-008",
    "name": "Atkins Meal 15g Protein Shake - Mocha Latte with Caffeine (5g Fiber)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 49,
    "protein_per_100g": 4.6,
    "carbs_per_100g": 1.8,
    "fat_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 325,
    "default_unit": "carton (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Atkins",
    "fiber_per_100g": 1.5,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.8,
    "sodium_per_100g": 62,
    "potassium_per_100g": 154,
    "calcium_per_100g": 185,
    "iron_per_100g": 1.2
  },
  {
    "id": "bv-rtd-atk-009",
    "name": "Atkins Iced Coffee Protein Shake - Vanilla Latte",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 49,
    "protein_per_100g": 4.6,
    "carbs_per_100g": 1.5,
    "fat_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 325,
    "default_unit": "carton (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Atkins",
    "fiber_per_100g": 1.2,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.8,
    "sodium_per_100g": 62,
    "potassium_per_100g": 145,
    "calcium_per_100g": 185,
    "iron_per_100g": 1.1
  },
  {
    "id": "bv-rtd-atk-010",
    "name": "Atkins Iced Coffee Protein Shake - Caramel Latte",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 49,
    "protein_per_100g": 4.6,
    "carbs_per_100g": 1.5,
    "fat_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 325,
    "default_unit": "carton (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Atkins",
    "fiber_per_100g": 1.2,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.8,
    "sodium_per_100g": 68,
    "potassium_per_100g": 145,
    "calcium_per_100g": 185,
    "iron_per_100g": 1.1
  },
  {
    "id": "bv-rtd-mm-001",
    "name": "Muscle Milk Genuine Protein Shake - Chocolate (25g Protein)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 48,
    "protein_per_100g": 7.6,
    "carbs_per_100g": 2.7,
    "fat_per_100g": 1.4,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 330,
    "default_unit": "carton (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Muscle Milk",
    "fiber_per_100g": 1.5,
    "sugar_per_100g": 0,
    "saturated_fat_per_100g": 0.3,
    "sodium_per_100g": 61,
    "potassium_per_100g": 167,
    "calcium_per_100g": 197,
    "iron_per_100g": 1.4
  },
  {
    "id": "bv-rtd-mm-002",
    "name": "Muscle Milk Genuine Protein Shake - Vanilla (25g Protein)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 48,
    "protein_per_100g": 7.6,
    "carbs_per_100g": 2.7,
    "fat_per_100g": 1.4,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 330,
    "default_unit": "carton (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Muscle Milk",
    "fiber_per_100g": 1.5,
    "sugar_per_100g": 0,
    "saturated_fat_per_100g": 0.3,
    "sodium_per_100g": 58,
    "potassium_per_100g": 152,
    "calcium_per_100g": 197,
    "iron_per_100g": 1.4
  },
  {
    "id": "bv-rtd-mm-003",
    "name": "Muscle Milk Pro Advanced Nutrition Shake - Intense Vanilla (40g Protein)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 51,
    "protein_per_100g": 9.7,
    "carbs_per_100g": 2.2,
    "fat_per_100g": 0.6,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 414,
    "default_unit": "carton (14 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Muscle Milk",
    "fiber_per_100g": 1.2,
    "sugar_per_100g": 0.2,
    "saturated_fat_per_100g": 0.2,
    "sodium_per_100g": 70,
    "potassium_per_100g": 157,
    "calcium_per_100g": 193,
    "iron_per_100g": 1.2
  },
  {
    "id": "bv-rtd-mm-004",
    "name": "Muscle Milk Pro Advanced Nutrition Shake - Knockout Chocolate (40g Protein)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 51,
    "protein_per_100g": 9.7,
    "carbs_per_100g": 2.2,
    "fat_per_100g": 0.6,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 414,
    "default_unit": "carton (14 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Muscle Milk",
    "fiber_per_100g": 1.2,
    "sugar_per_100g": 0.2,
    "saturated_fat_per_100g": 0.2,
    "sodium_per_100g": 75,
    "potassium_per_100g": 169,
    "calcium_per_100g": 193,
    "iron_per_100g": 1.3
  },
  {
    "id": "bv-rtd-mm-005",
    "name": "Muscle Milk Zero Protein Shake - Chocolate (20g Protein, 0g Sugar)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 30,
    "protein_per_100g": 6.1,
    "carbs_per_100g": 1.5,
    "fat_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 330,
    "default_unit": "carton (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Muscle Milk",
    "fiber_per_100g": 0.9,
    "sugar_per_100g": 0,
    "saturated_fat_per_100g": 0.2,
    "sodium_per_100g": 52,
    "potassium_per_100g": 136,
    "calcium_per_100g": 152,
    "iron_per_100g": 1.1
  },
  {
    "id": "bv-rtd-qst-001",
    "name": "Quest Ready-to-Drink Protein Shake - Chocolate (30g Protein)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 49,
    "protein_per_100g": 9.2,
    "carbs_per_100g": 0.9,
    "fat_per_100g": 1.1,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 325,
    "default_unit": "carton (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Quest Nutrition",
    "fiber_per_100g": 0.3,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.2,
    "sodium_per_100g": 86,
    "potassium_per_100g": 108,
    "calcium_per_100g": 200,
    "iron_per_100g": 1.1
  },
  {
    "id": "bv-rtd-qst-002",
    "name": "Quest Ready-to-Drink Protein Shake - Vanilla (30g Protein)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 49,
    "protein_per_100g": 9.2,
    "carbs_per_100g": 0.9,
    "fat_per_100g": 1.1,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 325,
    "default_unit": "carton (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Quest Nutrition",
    "fiber_per_100g": 0.3,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.2,
    "sodium_per_100g": 80,
    "potassium_per_100g": 98,
    "calcium_per_100g": 200,
    "iron_per_100g": 0.6
  },
  {
    "id": "bv-rtd-qst-003",
    "name": "Quest Ready-to-Drink Protein Shake - Salted Caramel (30g Protein)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 49,
    "protein_per_100g": 9.2,
    "carbs_per_100g": 0.9,
    "fat_per_100g": 1.1,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 325,
    "default_unit": "carton (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Quest Nutrition",
    "fiber_per_100g": 0.3,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.2,
    "sodium_per_100g": 117,
    "potassium_per_100g": 102,
    "calcium_per_100g": 200,
    "iron_per_100g": 0.6
  },
  {
    "id": "bv-rtd-ens-001",
    "name": "Ensure Max Protein Shake - Milk Chocolate (30g Protein, 1g Sugar)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 45,
    "protein_per_100g": 9.1,
    "carbs_per_100g": 1.8,
    "fat_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 330,
    "default_unit": "carton (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Ensure",
    "fiber_per_100g": 1.2,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.2,
    "sodium_per_100g": 70,
    "potassium_per_100g": 152,
    "calcium_per_100g": 197,
    "iron_per_100g": 2.4
  },
  {
    "id": "bv-rtd-ens-002",
    "name": "Ensure Max Protein Shake - French Vanilla (30g Protein, 1g Sugar)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 45,
    "protein_per_100g": 9.1,
    "carbs_per_100g": 1.8,
    "fat_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 330,
    "default_unit": "carton (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Ensure",
    "fiber_per_100g": 1.2,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.2,
    "sodium_per_100g": 64,
    "potassium_per_100g": 136,
    "calcium_per_100g": 197,
    "iron_per_100g": 2.4
  },
  {
    "id": "bv-rtd-bst-001",
    "name": "Boost High Protein Shake - Rich Chocolate (20g Protein)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 105,
    "protein_per_100g": 8.4,
    "carbs_per_100g": 11.8,
    "fat_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 237,
    "default_unit": "bottle (8 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Boost",
    "fiber_per_100g": 1.3,
    "sugar_per_100g": 4.6,
    "saturated_fat_per_100g": 0.4,
    "sodium_per_100g": 89,
    "potassium_per_100g": 211,
    "calcium_per_100g": 169,
    "iron_per_100g": 1.9
  },
  {
    "id": "bv-rtd-bst-002",
    "name": "Boost Max Protein Shake - Rich Chocolate (30g Protein, 1g Sugar)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 49,
    "protein_per_100g": 9.2,
    "carbs_per_100g": 1.2,
    "fat_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 325,
    "default_unit": "carton (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Boost",
    "fiber_per_100g": 0.3,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.2,
    "sodium_per_100g": 74,
    "potassium_per_100g": 160,
    "calcium_per_100g": 200,
    "iron_per_100g": 1.5
  },
  {
    "id": "bv-rtd-org-001",
    "name": "Orgain Organic Plant Protein Shake - Creamy Chocolate Fudge (20g Protein)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 42,
    "protein_per_100g": 6.1,
    "carbs_per_100g": 2.7,
    "fat_per_100g": 0.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 330,
    "default_unit": "carton (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Orgain",
    "fiber_per_100g": 1.2,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.2,
    "sodium_per_100g": 67,
    "potassium_per_100g": 91,
    "calcium_per_100g": 106,
    "iron_per_100g": 1.4
  },
  {
    "id": "bv-rtd-org-002",
    "name": "Orgain Clean Protein Grass-Fed Milk Shake - Creamy Chocolate (20g Protein)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 39,
    "protein_per_100g": 6.1,
    "carbs_per_100g": 3.3,
    "fat_per_100g": 0.6,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 330,
    "default_unit": "carton (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Orgain",
    "fiber_per_100g": 0.3,
    "sugar_per_100g": 0.9,
    "saturated_fat_per_100g": 0.3,
    "sodium_per_100g": 64,
    "potassium_per_100g": 136,
    "calcium_per_100g": 121,
    "iron_per_100g": 1.1
  },
  {
    "id": "bv-rtd-owy-001",
    "name": "OWYN Pro Elite High Protein Shake - Chocolate (32g Plant Protein, 0g Sugar)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 56,
    "protein_per_100g": 9,
    "carbs_per_100g": 2,
    "fat_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 355,
    "default_unit": "carton (12 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "OWYN",
    "fiber_per_100g": 1.4,
    "sugar_per_100g": 0,
    "saturated_fat_per_100g": 0.3,
    "sodium_per_100g": 104,
    "potassium_per_100g": 107,
    "calcium_per_100g": 127,
    "iron_per_100g": 1.7
  },
  {
    "id": "bv-rtd-owy-002",
    "name": "OWYN Pro Elite High Protein Shake - Vanilla (32g Plant Protein, 0g Sugar)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 56,
    "protein_per_100g": 9,
    "carbs_per_100g": 2,
    "fat_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 355,
    "default_unit": "carton (12 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "OWYN",
    "fiber_per_100g": 1.4,
    "sugar_per_100g": 0,
    "saturated_fat_per_100g": 0.3,
    "sodium_per_100g": 99,
    "potassium_per_100g": 99,
    "calcium_per_100g": 127,
    "iron_per_100g": 1.5
  },
  {
    "id": "bv-rtd-chb-001",
    "name": "Chobani Complete Mixed Berry Vanilla High Protein Drink (20g Protein, 0g Added Sugar)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 58,
    "protein_per_100g": 6.8,
    "carbs_per_100g": 5.8,
    "fat_per_100g": 0.8,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 295,
    "default_unit": "bottle (10 fl oz)",
    "storage_type": "fresh_weekly",
    "swap_group": "protein_shake",
    "brand": "Chobani",
    "fiber_per_100g": 1,
    "sugar_per_100g": 4.1,
    "saturated_fat_per_100g": 0.5,
    "sodium_per_100g": 42,
    "potassium_per_100g": 142,
    "calcium_per_100g": 186,
    "iron_per_100g": 0.2
  },
  {
    "id": "bv-rtd-oik-001",
    "name": "Oikos Pro Cultured Dairy Drink - Strawberry Banana (23g Protein, 0g Added Sugar)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 68,
    "protein_per_100g": 11.1,
    "carbs_per_100g": 3.9,
    "fat_per_100g": 1.2,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 207,
    "default_unit": "bottle (7 fl oz)",
    "storage_type": "fresh_weekly",
    "swap_group": "protein_shake",
    "brand": "Dannon Oikos",
    "fiber_per_100g": 0,
    "sugar_per_100g": 2.4,
    "saturated_fat_per_100g": 0.5,
    "sodium_per_100g": 48,
    "potassium_per_100g": 169,
    "calcium_per_100g": 290,
    "iron_per_100g": 0.1
  },
  {
    "id": "bv-rtd-ghs-001",
    "name": "Ghost RTD Protein Shake - Cereal Milk (25g Protein)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 48,
    "protein_per_100g": 7.6,
    "carbs_per_100g": 2.1,
    "fat_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 330,
    "default_unit": "bottle (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Ghost",
    "fiber_per_100g": 0.3,
    "sugar_per_100g": 1.2,
    "saturated_fat_per_100g": 0.5,
    "sodium_per_100g": 67,
    "potassium_per_100g": 136,
    "calcium_per_100g": 197,
    "iron_per_100g": 0.3
  },
  {
    "id": "bv-rtd-slt-001",
    "name": "Slate Milk Classic Chocolate High Protein Shake (20g Protein, 0g Added Sugar)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 37,
    "protein_per_100g": 6.2,
    "carbs_per_100g": 2.8,
    "fat_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 325,
    "default_unit": "can (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Slate Milk",
    "fiber_per_100g": 1.5,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.3,
    "sodium_per_100g": 71,
    "potassium_per_100g": 200,
    "calcium_per_100g": 169,
    "iron_per_100g": 0.5
  },
  {
    "id": "bv-rtd-rck-001",
    "name": "Shamrock Farms Rockin' Protein Builder - Chocolate (30g Protein)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 54,
    "protein_per_100g": 8.5,
    "carbs_per_100g": 2.5,
    "fat_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 355,
    "default_unit": "bottle (12 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Rockin' Protein",
    "fiber_per_100g": 0.3,
    "sugar_per_100g": 1.7,
    "saturated_fat_per_100g": 0.6,
    "sodium_per_100g": 68,
    "potassium_per_100g": 183,
    "calcium_per_100g": 197,
    "iron_per_100g": 0.4
  },
  {
    "id": "bv-rtd-gat-001",
    "name": "Gatorade Recover Protein Shake - Chocolate (30g Protein)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 85,
    "protein_per_100g": 9.1,
    "carbs_per_100g": 10,
    "fat_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 330,
    "default_unit": "bottle (11.16 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Gatorade",
    "fiber_per_100g": 0.3,
    "sugar_per_100g": 8.5,
    "saturated_fat_per_100g": 0.5,
    "sodium_per_100g": 100,
    "potassium_per_100g": 152,
    "calcium_per_100g": 197,
    "iron_per_100g": 0.6
  },
  {
    "id": "bv-rtd-on-001",
    "name": "Optimum Nutrition Gold Standard 100% Whey RTD - Chocolate (24g Protein)",
    "category": "beverages_hydration",
    "sub_category": "protein_drinks",
    "calories_per_100g": 42,
    "protein_per_100g": 7.3,
    "carbs_per_100g": 1.5,
    "fat_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 330,
    "default_unit": "bottle (11 fl oz)",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_shake",
    "brand": "Optimum Nutrition",
    "fiber_per_100g": 0.3,
    "sugar_per_100g": 0.3,
    "saturated_fat_per_100g": 0.5,
    "sodium_per_100g": 64,
    "potassium_per_100g": 136,
    "calcium_per_100g": 167,
    "iron_per_100g": 0.5
  }
];
