import { FoodItem } from '../types';

export const BEVERAGES_HYDRATION_DATABASE: FoodItem[] = [
  // ==========================================
  // COFFEE & ESPRESSO (10+ items)
  // ==========================================
  {
    id: 'bv-cof-001',
    name: 'Black Drip Coffee (Unsweetened, 0 Cal)',
    category: 'beverages_hydration',
    sub_category: 'coffee_espresso',
    calories_per_100g: 2,
    protein_per_100g: 0.3,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'bv-cof-002',
    name: 'Cold Brew Coffee (Slow Steeped, Black)',
    category: 'beverages_hydration',
    sub_category: 'coffee_espresso',
    calories_per_100g: 3,
    protein_per_100g: 0.3,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 350,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'bv-cof-003',
    name: 'Double Espresso Shot (Doppio)',
    category: 'beverages_hydration',
    sub_category: 'coffee_espresso',
    calories_per_100g: 9,
    protein_per_100g: 0.8,
    carbs_per_100g: 1.5,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 60,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'bv-cof-004',
    name: 'Iced Americano (Espresso & Cold Water)',
    category: 'beverages_hydration',
    sub_category: 'coffee_espresso',
    calories_per_100g: 2,
    protein_per_100g: 0.2,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 350,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },

  // ==========================================
  // TEAS & INFUSIONS (15+ items)
  // ==========================================
  {
    id: 'bv-tea-001',
    name: 'Organic Sencha Green Tea (Brewed Unsweetened)',
    category: 'beverages_hydration',
    sub_category: 'teas_infusions',
    calories_per_100g: 1,
    protein_per_100g: 0.2,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'bv-tea-002',
    name: 'Ceremonial Grade Matcha Green Tea (Whisked in Water)',
    category: 'beverages_hydration',
    sub_category: 'teas_infusions',
    calories_per_100g: 5,
    protein_per_100g: 0.6,
    carbs_per_100g: 0.8,
    fat_per_100g: 0.1,
    fiber_per_100g: 0.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 200,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'bv-tea-003',
    name: 'English Breakfast Black Tea (Brewed Unsweetened)',
    category: 'beverages_hydration',
    sub_category: 'teas_infusions',
    calories_per_100g: 1,
    protein_per_100g: 0.1,
    carbs_per_100g: 0.3,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'bv-tea-004',
    name: 'Organic Chamomile & Peppermint Herbal Infusion',
    category: 'beverages_hydration',
    sub_category: 'teas_infusions',
    calories_per_100g: 1,
    protein_per_100g: 0.0,
    carbs_per_100g: 0.2,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'bv-tea-005',
    name: 'Yerba Mate (Traditional Loose Leaf Brew)',
    category: 'beverages_hydration',
    sub_category: 'teas_infusions',
    calories_per_100g: 2,
    protein_per_100g: 0.3,
    carbs_per_100g: 0.4,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },

  // ==========================================
  // SPARKLING & MINERAL WATERS (10+ items)
  // ==========================================
  {
    id: 'bv-wat-001',
    name: 'Pure Sparkling Water / Seltzer (0 Cal)',
    category: 'beverages_hydration',
    sub_category: 'waters_sparkling',
    calories_per_100g: 0,
    protein_per_100g: 0.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 355,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'bv-wat-002',
    name: 'San Pellegrino Sparkling Natural Mineral Water',
    category: 'beverages_hydration',
    sub_category: 'waters_sparkling',
    calories_per_100g: 0,
    protein_per_100g: 0.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 500,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'bv-wat-003',
    name: 'Mountain Spring Water (Still)',
    category: 'beverages_hydration',
    sub_category: 'waters_sparkling',
    calories_per_100g: 0,
    protein_per_100g: 0.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 500,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },

  // ==========================================
  // FUNCTIONAL HYDRATION & ELECTROLYTES (10+ items)
  // ==========================================
  {
    id: 'bv-coc-001',
    name: '100% Pure Organic Coconut Water (Harmless Harvest / Vita Coco)',
    category: 'beverages_hydration',
    sub_category: 'functional_hydration',
    calories_per_100g: 19,
    protein_per_100g: 0.7,
    carbs_per_100g: 3.7,
    fat_per_100g: 0.2,
    fiber_per_100g: 1.1,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'bv-ele-001',
    name: 'Zero-Sugar Electrolyte Drink (LMNT / Liquid I.V. Zero)',
    category: 'beverages_hydration',
    sub_category: 'functional_hydration',
    calories_per_100g: 2,
    protein_per_100g: 0.0,
    carbs_per_100g: 0.5,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 500,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'bv-ele-002',
    name: 'Organic Grass-Fed Beef Bone Broth (Warm Sipping Broth)',
    category: 'beverages_hydration',
    sub_category: 'functional_hydration',
    calories_per_100g: 17,
    protein_per_100g: 3.8,
    carbs_per_100g: 0.2,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'lean_protein',
  },
];
