import { FoodItem } from '../types';

export const BEVERAGES_HYDRATION_DATABASE: FoodItem[] = [
  {
    "id": "bv-cof-001",
    "name": "Fresh Brewed Black Drip Coffee (Medium Roast Arabica)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 1,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-cof-002",
    "name": "Cold Brew Coffee (Black Steeped Concentrate)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 2,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-cof-003",
    "name": "Espresso (Single Shot 1 oz)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 9,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 1.7,
    "fat_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-cof-004",
    "name": "Espresso (Double Shot Doppio 2 oz)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 9,
    "protein_per_100g": 0.2,
    "carbs_per_100g": 1.7,
    "fat_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 60,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-cof-005",
    "name": "Caffè Americano (Espresso + Hot Water)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 2,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.3,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-cof-006",
    "name": "Decaffeinated Swiss Water Process Drip Coffee",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 1,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-cof-007",
    "name": "Nitro Cold Brew Coffee (Draft Infused Creamy Head)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 2,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 350,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-cof-008",
    "name": "Caffè Latte with Skim Milk (Tall 12 oz)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 38,
    "protein_per_100g": 3.5,
    "carbs_per_100g": 5,
    "fat_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 350,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "milk_dairy"
  },
  {
    "id": "bv-cof-009",
    "name": "Caffè Latte with Unsweetened Almond Milk (Tall 12 oz)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 18,
    "protein_per_100g": 0.8,
    "carbs_per_100g": 1.2,
    "fat_per_100g": 1.1,
    "fiber_per_100g": 0.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 350,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "plant_milk"
  },
  {
    "id": "bv-cof-010",
    "name": "Caffè Latte with Oat Milk (Tall 12 oz)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 48,
    "protein_per_100g": 1.5,
    "carbs_per_100g": 7,
    "fat_per_100g": 1.6,
    "fiber_per_100g": 0.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 350,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "plant_milk"
  },
  {
    "id": "bv-cof-011",
    "name": "Cappuccino with Whole Milk (6 oz Traditional)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 45,
    "protein_per_100g": 2.5,
    "carbs_per_100g": 3.5,
    "fat_per_100g": 2.3,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 180,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "milk_dairy"
  },
  {
    "id": "bv-tea-001",
    "name": "Organic Ceremonial Grade Japanese Matcha Green Tea (Whisked in Hot Water)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 3,
    "protein_per_100g": 0.3,
    "carbs_per_100g": 0.4,
    "fat_per_100g": 0,
    "fiber_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-002",
    "name": "Japanese Sencha Green Tea (Loose Leaf Brewed)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-003",
    "name": "Japanese Gyokuro Shade-Grown Green Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-004",
    "name": "Genmaicha (Green Tea with Toasted Brown Rice)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-005",
    "name": "Hojicha (Roasted Japanese Green Tea)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.1,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-006",
    "name": "Jasmine Blossom Green Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-007",
    "name": "English Breakfast Black Tea (Brewed Unsweetened)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.3,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-008",
    "name": "Earl Grey Black Tea (Bergamot Infused)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.3,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-009",
    "name": "Assam Black Tea (Single Estate Malty)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.3,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-010",
    "name": "Darjeeling First Flush Black Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-011",
    "name": "Formosa Oolong Tea (Semi-Oxidized Brewed)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-012",
    "name": "Ti Kuan Yin Iron Goddess Oolong Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-013",
    "name": "Silver Needle Pure White Tea (Bai Hao Yin Zhen)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-014",
    "name": "Aged Pu-erh Fermented Dark Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 2,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.3,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-015",
    "name": "Yerba Mate (Traditional Argentine Brewed)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 2,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.4,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-016",
    "name": "Peppermint Pure Herbal Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-017",
    "name": "Spearmint Pure Herbal Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-018",
    "name": "Chamomile Flower Herbal Infusion (Caffeine-Free Sleep)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-019",
    "name": "Rooibos Red Bush Tea (South African Caffeine-Free)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-020",
    "name": "Hibiscus Flower Tea / Agua de Jamaica (Ruby Tart)",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.3,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-021",
    "name": "Ginger Turmeric Root Herbal Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 2,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.4,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-022",
    "name": "Holy Basil / Tulsi Herbal Stress Relief Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-tea-023",
    "name": "Lemon Verbena Herbal Infusion",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-wtr-001",
    "name": "Pure Filtered Drinking Water",
    "category": "beverages_hydration",
    "sub_category": "waters_sparkling",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-wtr-002",
    "name": "Gerolsteiner Natural Sparkling Mineral Water (High Calcium & Magnesium)",
    "category": "beverages_hydration",
    "sub_category": "waters_sparkling",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 330,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-wtr-003",
    "name": "San Pellegrino Sparkling Natural Mineral Water (Italian Bottle)",
    "category": "beverages_hydration",
    "sub_category": "waters_sparkling",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 330,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-wtr-004",
    "name": "Topo Chico Carbonated Mineral Water (Glass Bottle)",
    "category": "beverages_hydration",
    "sub_category": "waters_sparkling",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 355,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-wtr-005",
    "name": "Perrier Sparkling Natural Mineral Water",
    "category": "beverages_hydration",
    "sub_category": "waters_sparkling",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 330,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-wtr-006",
    "name": "Lemon Essence Sparkling Seltzer Water (0 Calorie LaCroix/Spindrift style)",
    "category": "beverages_hydration",
    "sub_category": "waters_sparkling",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 355,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-wtr-007",
    "name": "Grapefruit Essence Sparkling Water (0 Calorie)",
    "category": "beverages_hydration",
    "sub_category": "waters_sparkling",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 355,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-wtr-008",
    "name": "Lime Essence Sparkling Water (0 Calorie)",
    "category": "beverages_hydration",
    "sub_category": "waters_sparkling",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 355,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-fun-001",
    "name": "100% Pure Organic Coconut Water (Harmless Harvest Pink)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 19,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 3.7,
    "fat_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-fun-002",
    "name": "Zero-Sugar Electrolyte Hydration Drink (LMNT / Liquid I.V. Zero Sodium-Potassium)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 2,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.5,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 480,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-fun-003",
    "name": "Organic Chicken Bone Broth (Simmered 24h High Collagen Kettle & Fire)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 19,
    "protein_per_100g": 4.2,
    "carbs_per_100g": 0,
    "fat_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "bv-fun-004",
    "name": "Grass-Fed Beef Bone Broth (Simmered 24h Kettle & Fire)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 21,
    "protein_per_100g": 4.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 0.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "bv-fun-005",
    "name": "Free-Range Turkey Bone Broth (Rich Gelatin)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 19,
    "protein_per_100g": 4.2,
    "carbs_per_100g": 0,
    "fat_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "bv-fun-006",
    "name": "Raw Fermented Ginger Kombucha (Low Sugar <2g GT's Synergy)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 13,
    "protein_per_100g": 0,
    "carbs_per_100g": 3.3,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 350,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-fun-007",
    "name": "100% Pure Tart Cherry Juice (Sleep & Recovery Tonic Cheribundi)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 54,
    "protein_per_100g": 0.5,
    "carbs_per_100g": 13.5,
    "fat_per_100g": 0.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "bv-fun-008",
    "name": "Organic Raw Apple Cider Vinegar Tonic (Bragg with Mother)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 21,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.9,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 15,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "condiment"
  },
  {
    "id": "bv-ext-001",
    "name": "Pour-Over Chemex Single-Origin Ethiopian Light Roast Coffee",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 1,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-002",
    "name": "French Press Dark Roast Colombian Coffee",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 2,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.1,
    "fat_per_100g": 0.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-003",
    "name": "Flat White Coffee with Skim Milk (8 oz)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 35,
    "protein_per_100g": 3.5,
    "carbs_per_100g": 4.8,
    "fat_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "milk_dairy"
  },
  {
    "id": "bv-ext-004",
    "name": "Cortado Coffee (Equal Parts Espresso & Steamed Whole Milk 4 oz)",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 40,
    "protein_per_100g": 2,
    "carbs_per_100g": 3,
    "fat_per_100g": 2.2,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 120,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "milk_dairy"
  },
  {
    "id": "bv-ext-005",
    "name": "Iced Shaken Espresso with Unsweetened Oat Milk",
    "category": "beverages_hydration",
    "sub_category": "coffee_espresso",
    "calories_per_100g": 30,
    "protein_per_100g": 0.8,
    "carbs_per_100g": 4.5,
    "fat_per_100g": 1,
    "fiber_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 350,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "plant_milk"
  },
  {
    "id": "bv-ext-006",
    "name": "Black Cherry Essence Sparkling Water (0 Calorie)",
    "category": "beverages_hydration",
    "sub_category": "waters_sparkling",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 355,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-007",
    "name": "Cucumber Mint Natural Essence Seltzer",
    "category": "beverages_hydration",
    "sub_category": "waters_sparkling",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 355,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-008",
    "name": "Dragonfruit Sparkling Mineral Water (Spindrift Real Fruit)",
    "category": "beverages_hydration",
    "sub_category": "waters_sparkling",
    "calories_per_100g": 3,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.8,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 355,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-009",
    "name": "100% Pure Coconut Water with Pineapple Juice",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 22,
    "protein_per_100g": 0.5,
    "carbs_per_100g": 4.8,
    "fat_per_100g": 0.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-010",
    "name": "Pure Organic Aloe Vera Hydration Juice Drink (Unsweetened George's)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 4,
    "protein_per_100g": 0,
    "carbs_per_100g": 1,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-011",
    "name": "Organic Simmered Vegetable Mineral Broth (Mirepoix & Sea Salt)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 10,
    "protein_per_100g": 0.5,
    "carbs_per_100g": 1.8,
    "fat_per_100g": 0.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "bv-ext-012",
    "name": "Traditional Miso Sipping Broth (Shiro Miso & Wakame)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 18,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 2.5,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-013",
    "name": "Roasted Dandelion Root Coffee-Alternative Herbal Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 2,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.4,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-014",
    "name": "Organic Stinging Nettle Leaf Mineral Herbal Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-015",
    "name": "Fennel Seed & Peppermint Digestive Herbal Infusion",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.3,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-016",
    "name": "Valerian Root & Passionflower Deep Sleep Herbal Tea",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 1,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-017",
    "name": "Guayusa Organic Amazonian Energy Leaf Brewed",
    "category": "beverages_hydration",
    "sub_category": "teas_infusions",
    "calories_per_100g": 2,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.4,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-018",
    "name": "Raw Passionfruit Guava Kombucha (Live Probiotics)",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 14,
    "protein_per_100g": 0,
    "carbs_per_100g": 3.5,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 350,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  },
  {
    "id": "bv-ext-019",
    "name": "Water Kefir Cultured Lemon Ginger Probiotic Soda",
    "category": "beverages_hydration",
    "sub_category": "functional_hydration",
    "calories_per_100g": 12,
    "protein_per_100g": 0,
    "carbs_per_100g": 3,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 350,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "hydration_base"
  }
];
