import { FoodItem } from '../types';

export const DAIRY_EGGS_DATABASE: FoodItem[] = [
  // ==========================================
  // EGGS & EGG WHITES (10+ items)
  // ==========================================
  {
    id: 'de-egg-001',
    name: 'Pasture-Raised Large Whole Egg (Raw)',
    category: 'dairy_eggs',
    sub_category: 'eggs',
    calories_per_100g: 143,
    protein_per_100g: 12.6,
    carbs_per_100g: 0.7,
    fat_per_100g: 9.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'egg_source',
  },
  {
    id: 'de-egg-002',
    name: 'Hard-Boiled Egg (Large)',
    category: 'dairy_eggs',
    sub_category: 'eggs',
    calories_per_100g: 155,
    protein_per_100g: 12.6,
    carbs_per_100g: 1.1,
    fat_per_100g: 10.6,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 50,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'egg_source',
  },
  {
    id: 'de-egg-003',
    name: '100% Pure Liquid Egg Whites',
    category: 'dairy_eggs',
    sub_category: 'eggs',
    calories_per_100g: 52,
    protein_per_100g: 11.0,
    carbs_per_100g: 0.7,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'de-egg-004',
    name: 'Scrambled Egg Whites (Cooked with Olive Spray)',
    category: 'dairy_eggs',
    sub_category: 'eggs',
    calories_per_100g: 54,
    protein_per_100g: 11.5,
    carbs_per_100g: 0.8,
    fat_per_100g: 0.3,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'de-egg-005',
    name: 'Omega-3 Enriched Whole Eggs',
    category: 'dairy_eggs',
    sub_category: 'eggs',
    calories_per_100g: 145,
    protein_per_100g: 12.8,
    carbs_per_100g: 0.6,
    fat_per_100g: 9.8,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'egg_source',
  },

  // ==========================================
  // GREEK YOGURT & SKYR (15+ items)
  // ==========================================
  {
    id: 'de-yog-001',
    name: '0% Nonfat Plain Greek Yogurt',
    category: 'dairy_eggs',
    sub_category: 'greek_yogurt',
    calories_per_100g: 59,
    protein_per_100g: 10.3,
    carbs_per_100g: 3.6,
    fat_per_100g: 0.4,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 200,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },
  {
    id: 'de-yog-002',
    name: '2% Low-Fat Plain Greek Yogurt',
    category: 'dairy_eggs',
    sub_category: 'greek_yogurt',
    calories_per_100g: 73,
    protein_per_100g: 10.0,
    carbs_per_100g: 4.0,
    fat_per_100g: 2.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 200,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },
  {
    id: 'de-yog-003',
    name: '5% Whole Milk Greek Yogurt (Plain)',
    category: 'dairy_eggs',
    sub_category: 'greek_yogurt',
    calories_per_100g: 97,
    protein_per_100g: 9.0,
    carbs_per_100g: 3.8,
    fat_per_100g: 5.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 170,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },
  {
    id: 'de-yog-004',
    name: 'Icelandic Skyr (Plain Nonfat)',
    category: 'dairy_eggs',
    sub_category: 'greek_yogurt',
    calories_per_100g: 63,
    protein_per_100g: 11.0,
    carbs_per_100g: 3.8,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 170,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },
  {
    id: 'de-yog-005',
    name: 'Vanilla Triple Zero Greek Yogurt (No Added Sugar)',
    category: 'dairy_eggs',
    sub_category: 'greek_yogurt',
    calories_per_100g: 60,
    protein_per_100g: 10.0,
    carbs_per_100g: 4.7,
    fat_per_100g: 0.0,
    fiber_per_100g: 2.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },

  // ==========================================
  // COTTAGE CHEESE (8+ items)
  // ==========================================
  {
    id: 'de-cot-001',
    name: 'Low-Fat Cottage Cheese (2% Milkfat)',
    category: 'dairy_eggs',
    sub_category: 'cottage_cheese',
    calories_per_100g: 81,
    protein_per_100g: 11.0,
    carbs_per_100g: 4.7,
    fat_per_100g: 2.3,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },
  {
    id: 'de-cot-002',
    name: 'Fat-Free Cottage Cheese (0% Nonfat)',
    category: 'dairy_eggs',
    sub_category: 'cottage_cheese',
    calories_per_100g: 72,
    protein_per_100g: 12.5,
    carbs_per_100g: 4.5,
    fat_per_100g: 0.3,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },
  {
    id: 'de-cot-003',
    name: '4% Whole Milk Cottage Cheese (Good Culture)',
    category: 'dairy_eggs',
    sub_category: 'cottage_cheese',
    calories_per_100g: 105,
    protein_per_100g: 13.0,
    carbs_per_100g: 3.5,
    fat_per_100g: 4.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },

  // ==========================================
  // CHEESES (15+ items)
  // ==========================================
  {
    id: 'de-chs-001',
    name: 'Part-Skim Mozzarella String Cheese',
    category: 'dairy_eggs',
    sub_category: 'cheeses',
    calories_per_100g: 280,
    protein_per_100g: 24.0,
    carbs_per_100g: 2.5,
    fat_per_100g: 20.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },
  {
    id: 'de-chs-002',
    name: 'Fresh Mozzarella Ball (Water Packed)',
    category: 'dairy_eggs',
    sub_category: 'cheeses',
    calories_per_100g: 240,
    protein_per_100g: 18.0,
    carbs_per_100g: 2.0,
    fat_per_100g: 18.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 40,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'healthy_fat',
  },
  {
    id: 'de-chs-003',
    name: 'Sharp Cheddar Cheese (Aged Block)',
    category: 'dairy_eggs',
    sub_category: 'cheeses',
    calories_per_100g: 403,
    protein_per_100g: 25.0,
    carbs_per_100g: 1.3,
    fat_per_100g: 33.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'healthy_fat',
  },
  {
    id: 'de-chs-004',
    name: 'Crumbled Feta Cheese (Sheep / Goat Milk)',
    category: 'dairy_eggs',
    sub_category: 'cheeses',
    calories_per_100g: 264,
    protein_per_100g: 14.2,
    carbs_per_100g: 4.1,
    fat_per_100g: 21.3,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'healthy_fat',
  },
  {
    id: 'de-chs-005',
    name: 'Aged Parmigiano-Reggiano (Grated)',
    category: 'dairy_eggs',
    sub_category: 'cheeses',
    calories_per_100g: 431,
    protein_per_100g: 38.5,
    carbs_per_100g: 4.1,
    fat_per_100g: 28.6,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 20,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'healthy_fat',
  },
  {
    id: 'de-chs-006',
    name: 'Part-Skim Ricotta Cheese',
    category: 'dairy_eggs',
    sub_category: 'cheeses',
    calories_per_100g: 138,
    protein_per_100g: 11.3,
    carbs_per_100g: 5.1,
    fat_per_100g: 7.9,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 60,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },

  // ==========================================
  // MILKS & PLANT MILKS (15+ items)
  // ==========================================
  {
    id: 'de-mlk-001',
    name: 'Fairlife Ultra-Filtered Skim Milk (High Protein)',
    category: 'dairy_eggs',
    sub_category: 'dairy_milks',
    calories_per_100g: 35,
    protein_per_100g: 5.4,
    carbs_per_100g: 2.5,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },
  {
    id: 'de-mlk-002',
    name: 'Fairlife 2% Reduced Fat Ultra-Filtered Milk',
    category: 'dairy_eggs',
    sub_category: 'dairy_milks',
    calories_per_100g: 50,
    protein_per_100g: 5.4,
    carbs_per_100g: 2.5,
    fat_per_100g: 2.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'fresh_weekly',
    swap_group: 'dairy_protein',
  },
  {
    id: 'de-mlk-003',
    name: 'Unsweetened Almond Milk (Silk / Califia)',
    category: 'dairy_eggs',
    sub_category: 'plant_milks',
    calories_per_100g: 15,
    protein_per_100g: 0.6,
    carbs_per_100g: 0.3,
    fat_per_100g: 1.2,
    fiber_per_100g: 0.2,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'de-mlk-004',
    name: 'Unsweetened Vanilla Almond Milk',
    category: 'dairy_eggs',
    sub_category: 'plant_milks',
    calories_per_100g: 15,
    protein_per_100g: 0.6,
    carbs_per_100g: 0.4,
    fat_per_100g: 1.2,
    fiber_per_100g: 0.3,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'de-mlk-005',
    name: 'Unsweetened Oat Milk (Oatly / Planet Oat)',
    category: 'dairy_eggs',
    sub_category: 'plant_milks',
    calories_per_100g: 45,
    protein_per_100g: 1.0,
    carbs_per_100g: 6.5,
    fat_per_100g: 1.5,
    fiber_per_100g: 0.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
  {
    id: 'de-mlk-006',
    name: 'Unsweetened Organic Soy Milk (Silk)',
    category: 'dairy_eggs',
    sub_category: 'plant_milks',
    calories_per_100g: 33,
    protein_per_100g: 3.3,
    carbs_per_100g: 1.2,
    fat_per_100g: 1.7,
    fiber_per_100g: 0.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 240,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },
];
