import { FoodItem } from '../types';

export const DAIRY_EGGS_DATABASE: FoodItem[] = [
  {
    "id": "de-egg-001",
    "name": "Whole Egg (Large Grade A, Raw)",
    "category": "dairy_eggs",
    "sub_category": "eggs",
    "calories_per_100g": 143,
    "protein_per_100g": 12.6,
    "carbs_per_100g": 0.7,
    "fat_per_100g": 9.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "whole_egg"
  },
  {
    "id": "de-egg-002",
    "name": "Whole Egg (Hard-Boiled)",
    "category": "dairy_eggs",
    "sub_category": "eggs",
    "calories_per_100g": 155,
    "protein_per_100g": 13,
    "carbs_per_100g": 1.1,
    "fat_per_100g": 10.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "whole_egg"
  },
  {
    "id": "de-egg-003",
    "name": "Whole Egg (Scrambled with Olive Oil)",
    "category": "dairy_eggs",
    "sub_category": "eggs",
    "calories_per_100g": 165,
    "protein_per_100g": 11.5,
    "carbs_per_100g": 1.2,
    "fat_per_100g": 12.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "whole_egg"
  },
  {
    "id": "de-egg-004",
    "name": "Liquid Egg Whites (100% Pure Pasteurized)",
    "category": "dairy_eggs",
    "sub_category": "eggs",
    "calories_per_100g": 52,
    "protein_per_100g": 11,
    "carbs_per_100g": 0.7,
    "fat_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "egg_white"
  },
  {
    "id": "de-egg-005",
    "name": "Cooked Egg Whites (Pan-Seared / Steamed)",
    "category": "dairy_eggs",
    "sub_category": "eggs",
    "calories_per_100g": 54,
    "protein_per_100g": 11.5,
    "carbs_per_100g": 0.8,
    "fat_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "egg_white"
  },
  {
    "id": "de-egg-006",
    "name": "Organic Pasture-Raised Whole Eggs (Vital Farms style)",
    "category": "dairy_eggs",
    "sub_category": "eggs",
    "calories_per_100g": 145,
    "protein_per_100g": 13,
    "carbs_per_100g": 0.6,
    "fat_per_100g": 9.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "whole_egg"
  },
  {
    "id": "de-egg-007",
    "name": "Poached Egg (Large)",
    "category": "dairy_eggs",
    "sub_category": "eggs",
    "calories_per_100g": 143,
    "protein_per_100g": 12.5,
    "carbs_per_100g": 0.7,
    "fat_per_100g": 9.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "whole_egg"
  },
  {
    "id": "de-egg-008",
    "name": "Sunny-Side Up Fried Egg (Light Olive Oil)",
    "category": "dairy_eggs",
    "sub_category": "eggs",
    "calories_per_100g": 175,
    "protein_per_100g": 12,
    "carbs_per_100g": 0.8,
    "fat_per_100g": 13.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 55,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "whole_egg"
  },
  {
    "id": "de-egg-009",
    "name": "Soft-Boiled Jammy Egg",
    "category": "dairy_eggs",
    "sub_category": "eggs",
    "calories_per_100g": 150,
    "protein_per_100g": 12.8,
    "carbs_per_100g": 0.9,
    "fat_per_100g": 10,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "whole_egg"
  },
  {
    "id": "de-egg-010",
    "name": "Over-Easy Fried Egg",
    "category": "dairy_eggs",
    "sub_category": "eggs",
    "calories_per_100g": 175,
    "protein_per_100g": 12,
    "carbs_per_100g": 0.8,
    "fat_per_100g": 13.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 55,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "whole_egg"
  },
  {
    "id": "de-egg-011",
    "name": "Sous Vide Egg Bites (Bacon & Gruyere style)",
    "category": "dairy_eggs",
    "sub_category": "eggs",
    "calories_per_100g": 210,
    "protein_per_100g": 14,
    "carbs_per_100g": 5,
    "fat_per_100g": 15,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "whole_egg"
  },
  {
    "id": "de-egg-012",
    "name": "Sous Vide Egg Bites (Egg White & Roasted Red Pepper)",
    "category": "dairy_eggs",
    "sub_category": "eggs",
    "calories_per_100g": 130,
    "protein_per_100g": 12,
    "carbs_per_100g": 6,
    "fat_per_100g": 6,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "egg_white"
  },
  {
    "id": "de-egg-013",
    "name": "Duck Egg (Large Whole Raw)",
    "category": "dairy_eggs",
    "sub_category": "eggs",
    "calories_per_100g": 185,
    "protein_per_100g": 12.8,
    "carbs_per_100g": 1.4,
    "fat_per_100g": 13.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 70,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "whole_egg"
  },
  {
    "id": "de-egg-014",
    "name": "Quail Eggs (Whole Raw / Boiled)",
    "category": "dairy_eggs",
    "sub_category": "eggs",
    "calories_per_100g": 158,
    "protein_per_100g": 13,
    "carbs_per_100g": 0.4,
    "fat_per_100g": 11,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 45,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "whole_egg"
  },
  {
    "id": "de-egg-015",
    "name": "Omelet (Whole Egg with Herbs & Sea Salt)",
    "category": "dairy_eggs",
    "sub_category": "eggs",
    "calories_per_100g": 154,
    "protein_per_100g": 11,
    "carbs_per_100g": 0.6,
    "fat_per_100g": 12,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "whole_egg"
  },
  {
    "id": "de-egg-016",
    "name": "Egg White Omelet (Spinach & Herb)",
    "category": "dairy_eggs",
    "sub_category": "eggs",
    "calories_per_100g": 60,
    "protein_per_100g": 11,
    "carbs_per_100g": 1.5,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "egg_white"
  },
  {
    "id": "de-yog-001",
    "name": "0% Fat Plain Greek Yogurt (Fage / Chobani style)",
    "category": "dairy_eggs",
    "sub_category": "greek_yogurt",
    "calories_per_100g": 59,
    "protein_per_100g": 10.3,
    "carbs_per_100g": 3.6,
    "fat_per_100g": 0.4,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "yogurt_protein"
  },
  {
    "id": "de-yog-002",
    "name": "2% Reduced Fat Plain Greek Yogurt",
    "category": "dairy_eggs",
    "sub_category": "greek_yogurt",
    "calories_per_100g": 73,
    "protein_per_100g": 9.8,
    "carbs_per_100g": 3.9,
    "fat_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "yogurt_protein"
  },
  {
    "id": "de-yog-003",
    "name": "5% Whole Milk Plain Greek Yogurt",
    "category": "dairy_eggs",
    "sub_category": "greek_yogurt",
    "calories_per_100g": 97,
    "protein_per_100g": 9,
    "carbs_per_100g": 3.8,
    "fat_per_100g": 5,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "yogurt_protein"
  },
  {
    "id": "de-yog-004",
    "name": "0% Plain Skyr (Icelandic High-Protein Strained Yogurt)",
    "category": "dairy_eggs",
    "sub_category": "greek_yogurt",
    "calories_per_100g": 65,
    "protein_per_100g": 11.5,
    "carbs_per_100g": 4,
    "fat_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "yogurt_protein"
  },
  {
    "id": "de-yog-005",
    "name": "Vanilla 0% Greek Yogurt (Low Sugar)",
    "category": "dairy_eggs",
    "sub_category": "greek_yogurt",
    "calories_per_100g": 75,
    "protein_per_100g": 10,
    "carbs_per_100g": 6.5,
    "fat_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "yogurt_protein"
  },
  {
    "id": "de-yog-006",
    "name": "Organic Grass-Fed Whole Milk Yogurt (Plain Unsweetened)",
    "category": "dairy_eggs",
    "sub_category": "greek_yogurt",
    "calories_per_100g": 61,
    "protein_per_100g": 3.5,
    "carbs_per_100g": 4.7,
    "fat_per_100g": 3.3,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "yogurt_protein"
  },
  {
    "id": "de-yog-007",
    "name": "Low-Fat Plain Kefir (Probiotic Drinkable Yogurt)",
    "category": "dairy_eggs",
    "sub_category": "greek_yogurt",
    "calories_per_100g": 43,
    "protein_per_100g": 3.8,
    "carbs_per_100g": 4.8,
    "fat_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "yogurt_protein"
  },
  {
    "id": "de-yog-008",
    "name": "Whole Milk Plain Kefir (Lifeway style)",
    "category": "dairy_eggs",
    "sub_category": "greek_yogurt",
    "calories_per_100g": 65,
    "protein_per_100g": 3.5,
    "carbs_per_100g": 4.8,
    "fat_per_100g": 3.5,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "yogurt_protein"
  },
  {
    "id": "de-yog-009",
    "name": "Labneh (Middle Eastern Strained Yogurt Spread)",
    "category": "dairy_eggs",
    "sub_category": "greek_yogurt",
    "calories_per_100g": 130,
    "protein_per_100g": 7.5,
    "carbs_per_100g": 4.5,
    "fat_per_100g": 9,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 60,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "yogurt_protein"
  },
  {
    "id": "de-yog-010",
    "name": "Quark (Traditional High-Protein German Fresh Cheese)",
    "category": "dairy_eggs",
    "sub_category": "greek_yogurt",
    "calories_per_100g": 68,
    "protein_per_100g": 12,
    "carbs_per_100g": 3.5,
    "fat_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "yogurt_protein"
  },
  {
    "id": "de-yog-011",
    "name": "Strawberry 0% Greek Yogurt (Single Serve)",
    "category": "dairy_eggs",
    "sub_category": "greek_yogurt",
    "calories_per_100g": 80,
    "protein_per_100g": 9.5,
    "carbs_per_100g": 9,
    "fat_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "yogurt_protein"
  },
  {
    "id": "de-yog-012",
    "name": "Blueberry 0% Greek Yogurt (Single Serve)",
    "category": "dairy_eggs",
    "sub_category": "greek_yogurt",
    "calories_per_100g": 80,
    "protein_per_100g": 9.5,
    "carbs_per_100g": 9,
    "fat_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "yogurt_protein"
  },
  {
    "id": "de-yog-013",
    "name": "Coconut Milk Greek-Style Yogurt (Dairy-Free Silk/Siggi style)",
    "category": "dairy_eggs",
    "sub_category": "greek_yogurt",
    "calories_per_100g": 90,
    "protein_per_100g": 2,
    "carbs_per_100g": 8,
    "fat_per_100g": 6,
    "fiber_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "yogurt_protein"
  },
  {
    "id": "de-yog-014",
    "name": "Almond Milk Plain Yogurt (Forager / Kite Hill style)",
    "category": "dairy_eggs",
    "sub_category": "greek_yogurt",
    "calories_per_100g": 85,
    "protein_per_100g": 3,
    "carbs_per_100g": 6,
    "fat_per_100g": 5.5,
    "fiber_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "yogurt_protein"
  },
  {
    "id": "de-yog-015",
    "name": "Soy Milk Plain Greek Yogurt (High Plant Protein)",
    "category": "dairy_eggs",
    "sub_category": "greek_yogurt",
    "calories_per_100g": 70,
    "protein_per_100g": 7,
    "carbs_per_100g": 4,
    "fat_per_100g": 2.5,
    "fiber_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "yogurt_protein"
  },
  {
    "id": "de-cot-001",
    "name": "2% Low-Fat Cottage Cheese (Good Culture style)",
    "category": "dairy_eggs",
    "sub_category": "cottage_cheese",
    "calories_per_100g": 86,
    "protein_per_100g": 12,
    "carbs_per_100g": 3,
    "fat_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cottage_protein"
  },
  {
    "id": "de-cot-002",
    "name": "4% Whole Milk Cottage Cheese",
    "category": "dairy_eggs",
    "sub_category": "cottage_cheese",
    "calories_per_100g": 98,
    "protein_per_100g": 11.5,
    "carbs_per_100g": 3.4,
    "fat_per_100g": 4.3,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cottage_protein"
  },
  {
    "id": "de-cot-003",
    "name": "0% Nonfat Cottage Cheese",
    "category": "dairy_eggs",
    "sub_category": "cottage_cheese",
    "calories_per_100g": 72,
    "protein_per_100g": 12.5,
    "carbs_per_100g": 4,
    "fat_per_100g": 0.3,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cottage_protein"
  },
  {
    "id": "de-cot-004",
    "name": "Whipped Smooth Cottage Cheese",
    "category": "dairy_eggs",
    "sub_category": "cottage_cheese",
    "calories_per_100g": 88,
    "protein_per_100g": 12,
    "carbs_per_100g": 3,
    "fat_per_100g": 2.2,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cottage_protein"
  },
  {
    "id": "de-cot-005",
    "name": "Dry Curd Farmer Cheese (0% Fat High Protein)",
    "category": "dairy_eggs",
    "sub_category": "cottage_cheese",
    "calories_per_100g": 92,
    "protein_per_100g": 16,
    "carbs_per_100g": 2.5,
    "fat_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cottage_protein"
  },
  {
    "id": "de-cot-006",
    "name": "Organic Lactose-Free Cottage Cheese (Good Culture)",
    "category": "dairy_eggs",
    "sub_category": "cottage_cheese",
    "calories_per_100g": 86,
    "protein_per_100g": 12,
    "carbs_per_100g": 3,
    "fat_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cottage_protein"
  },
  {
    "id": "de-mlk-001",
    "name": "Fairlife Ultra-Filtered Skim Milk (High Protein, Lactose Free)",
    "category": "dairy_eggs",
    "sub_category": "dairy_milks",
    "calories_per_100g": 33,
    "protein_per_100g": 5.4,
    "carbs_per_100g": 2.5,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "milk_dairy"
  },
  {
    "id": "de-mlk-002",
    "name": "Fairlife Ultra-Filtered 2% Reduced Fat Milk",
    "category": "dairy_eggs",
    "sub_category": "dairy_milks",
    "calories_per_100g": 50,
    "protein_per_100g": 5.4,
    "carbs_per_100g": 2.5,
    "fat_per_100g": 2.1,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "milk_dairy"
  },
  {
    "id": "de-mlk-003",
    "name": "Fairlife Ultra-Filtered Whole Milk",
    "category": "dairy_eggs",
    "sub_category": "dairy_milks",
    "calories_per_100g": 63,
    "protein_per_100g": 5.4,
    "carbs_per_100g": 2.5,
    "fat_per_100g": 3.3,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "milk_dairy"
  },
  {
    "id": "de-mlk-004",
    "name": "Whole Cow Milk (Grade A Pasteurized)",
    "category": "dairy_eggs",
    "sub_category": "dairy_milks",
    "calories_per_100g": 61,
    "protein_per_100g": 3.2,
    "carbs_per_100g": 4.8,
    "fat_per_100g": 3.3,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "milk_dairy"
  },
  {
    "id": "de-mlk-005",
    "name": "2% Reduced Fat Cow Milk",
    "category": "dairy_eggs",
    "sub_category": "dairy_milks",
    "calories_per_100g": 50,
    "protein_per_100g": 3.3,
    "carbs_per_100g": 4.8,
    "fat_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "milk_dairy"
  },
  {
    "id": "de-mlk-006",
    "name": "1% Low-Fat Cow Milk",
    "category": "dairy_eggs",
    "sub_category": "dairy_milks",
    "calories_per_100g": 42,
    "protein_per_100g": 3.4,
    "carbs_per_100g": 5,
    "fat_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "milk_dairy"
  },
  {
    "id": "de-mlk-007",
    "name": "Skim / Nonfat Cow Milk",
    "category": "dairy_eggs",
    "sub_category": "dairy_milks",
    "calories_per_100g": 35,
    "protein_per_100g": 3.4,
    "carbs_per_100g": 5,
    "fat_per_100g": 0.1,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "milk_dairy"
  },
  {
    "id": "de-mlk-008",
    "name": "Cultured Low-Fat Buttermilk",
    "category": "dairy_eggs",
    "sub_category": "dairy_milks",
    "calories_per_100g": 40,
    "protein_per_100g": 3.3,
    "carbs_per_100g": 4.8,
    "fat_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "milk_dairy"
  },
  {
    "id": "de-mlk-009",
    "name": "Lactaid 100% Lactose-Free Whole Milk",
    "category": "dairy_eggs",
    "sub_category": "dairy_milks",
    "calories_per_100g": 61,
    "protein_per_100g": 3.3,
    "carbs_per_100g": 4.8,
    "fat_per_100g": 3.3,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "milk_dairy"
  },
  {
    "id": "de-mlk-010",
    "name": "Lactaid 100% Lactose-Free 2% Milk",
    "category": "dairy_eggs",
    "sub_category": "dairy_milks",
    "calories_per_100g": 50,
    "protein_per_100g": 3.3,
    "carbs_per_100g": 4.8,
    "fat_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "milk_dairy"
  },
  {
    "id": "de-mlk-011",
    "name": "Lactaid 100% Lactose-Free Fat-Free Skim Milk",
    "category": "dairy_eggs",
    "sub_category": "dairy_milks",
    "calories_per_100g": 35,
    "protein_per_100g": 3.4,
    "carbs_per_100g": 5,
    "fat_per_100g": 0.1,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "milk_dairy"
  },
  {
    "id": "de-mlk-012",
    "name": "Organic Whole Goat Milk (Meyenberg Fresh)",
    "category": "dairy_eggs",
    "sub_category": "dairy_milks",
    "calories_per_100g": 69,
    "protein_per_100g": 3.6,
    "carbs_per_100g": 4.5,
    "fat_per_100g": 4.1,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "milk_dairy"
  },
  {
    "id": "de-mlk-013",
    "name": "Heavy Whipping Cream (Grade A 36% Fat)",
    "category": "dairy_eggs",
    "sub_category": "dairy_milks",
    "calories_per_100g": 345,
    "protein_per_100g": 2.1,
    "carbs_per_100g": 2.8,
    "fat_per_100g": 36.5,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 15,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-mlk-014",
    "name": "Half and Half Milk & Cream",
    "category": "dairy_eggs",
    "sub_category": "dairy_milks",
    "calories_per_100g": 130,
    "protein_per_100g": 3,
    "carbs_per_100g": 4.3,
    "fat_per_100g": 11.5,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 30,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "milk_dairy"
  },
  {
    "id": "de-plt-001",
    "name": "Unsweetened Almond Milk (Almond Breeze / Silk style)",
    "category": "dairy_eggs",
    "sub_category": "plant_milks",
    "calories_per_100g": 13,
    "protein_per_100g": 0.5,
    "carbs_per_100g": 0.3,
    "fat_per_100g": 1.1,
    "fiber_per_100g": 0.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "plant_milk"
  },
  {
    "id": "de-plt-002",
    "name": "Unsweetened Vanilla Almond Milk",
    "category": "dairy_eggs",
    "sub_category": "plant_milks",
    "calories_per_100g": 13,
    "protein_per_100g": 0.5,
    "carbs_per_100g": 0.3,
    "fat_per_100g": 1.1,
    "fiber_per_100g": 0.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "plant_milk"
  },
  {
    "id": "de-plt-003",
    "name": "Unsweetened Cashew Milk (Creamy Silk style)",
    "category": "dairy_eggs",
    "sub_category": "plant_milks",
    "calories_per_100g": 10,
    "protein_per_100g": 0.4,
    "carbs_per_100g": 0.4,
    "fat_per_100g": 0.8,
    "fiber_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "plant_milk"
  },
  {
    "id": "de-plt-004",
    "name": "Unsweetened Oat Milk (Oatly style)",
    "category": "dairy_eggs",
    "sub_category": "plant_milks",
    "calories_per_100g": 45,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 6.5,
    "fat_per_100g": 1.5,
    "fiber_per_100g": 0.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "plant_milk"
  },
  {
    "id": "de-plt-005",
    "name": "Extra Creamy Oat Milk (Barista Blend)",
    "category": "dairy_eggs",
    "sub_category": "plant_milks",
    "calories_per_100g": 60,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 7.5,
    "fat_per_100g": 3,
    "fiber_per_100g": 0.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "plant_milk"
  },
  {
    "id": "de-plt-006",
    "name": "Unsweetened Soy Milk (High Protein Organic)",
    "category": "dairy_eggs",
    "sub_category": "plant_milks",
    "calories_per_100g": 33,
    "protein_per_100g": 3.3,
    "carbs_per_100g": 1.2,
    "fat_per_100g": 1.7,
    "fiber_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "plant_milk"
  },
  {
    "id": "de-plt-007",
    "name": "Unsweetened Coconut Milk Beverage (Light Carton)",
    "category": "dairy_eggs",
    "sub_category": "plant_milks",
    "calories_per_100g": 19,
    "protein_per_100g": 0.2,
    "carbs_per_100g": 0.4,
    "fat_per_100g": 1.9,
    "fiber_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "plant_milk"
  },
  {
    "id": "de-plt-008",
    "name": "Canned Light Coconut Milk (Culinary Grade)",
    "category": "dairy_eggs",
    "sub_category": "plant_milks",
    "calories_per_100g": 70,
    "protein_per_100g": 0.8,
    "carbs_per_100g": 2,
    "fat_per_100g": 7,
    "fiber_per_100g": 0.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 60,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "de-plt-009",
    "name": "Canned Full-Fat Coconut Milk (Organic Creamy)",
    "category": "dairy_eggs",
    "sub_category": "plant_milks",
    "calories_per_100g": 197,
    "protein_per_100g": 2,
    "carbs_per_100g": 2.8,
    "fat_per_100g": 21.3,
    "fiber_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 60,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "de-plt-010",
    "name": "Unsweetened Macadamia Nut Milk (Milkadamia)",
    "category": "dairy_eggs",
    "sub_category": "plant_milks",
    "calories_per_100g": 21,
    "protein_per_100g": 0.4,
    "carbs_per_100g": 0.4,
    "fat_per_100g": 2.1,
    "fiber_per_100g": 0.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "plant_milk"
  },
  {
    "id": "de-plt-011",
    "name": "Unsweetened Pea Protein Milk (Ripple style)",
    "category": "dairy_eggs",
    "sub_category": "plant_milks",
    "calories_per_100g": 33,
    "protein_per_100g": 3.3,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.9,
    "fiber_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "plant_milk"
  },
  {
    "id": "de-plt-012",
    "name": "Unsweetened Hemp Seed Milk",
    "category": "dairy_eggs",
    "sub_category": "plant_milks",
    "calories_per_100g": 25,
    "protein_per_100g": 1.3,
    "carbs_per_100g": 0.4,
    "fat_per_100g": 2.1,
    "fiber_per_100g": 0.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "plant_milk"
  },
  {
    "id": "de-plt-013",
    "name": "Unsweetened Flax Milk with Protein",
    "category": "dairy_eggs",
    "sub_category": "plant_milks",
    "calories_per_100g": 25,
    "protein_per_100g": 3.3,
    "carbs_per_100g": 0.4,
    "fat_per_100g": 1.1,
    "fiber_per_100g": 0.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "plant_milk"
  },
  {
    "id": "de-chs-001",
    "name": "Part-Skim Mozzarella String Cheese",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 280,
    "protein_per_100g": 24,
    "carbs_per_100g": 2,
    "fat_per_100g": 20,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-002",
    "name": "Shredded Low-Moisture Part-Skim Mozzarella",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 295,
    "protein_per_100g": 24.5,
    "carbs_per_100g": 2.5,
    "fat_per_100g": 21,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-003",
    "name": "Fresh Mozzarella Pearls / Bocconcini (in Water)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 245,
    "protein_per_100g": 18,
    "carbs_per_100g": 2,
    "fat_per_100g": 18.5,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-004",
    "name": "Burrata Fresh Italian Cheese (Mozzarella & Stracciatella Cream)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 260,
    "protein_per_100g": 15,
    "carbs_per_100g": 2,
    "fat_per_100g": 22,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-005",
    "name": "Aged Sharp White Cheddar Cheese (Cabot / Kerrygold style)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 403,
    "protein_per_100g": 25,
    "carbs_per_100g": 1.3,
    "fat_per_100g": 33,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-006",
    "name": "Mild Yellow Cheddar Cheese Slices",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 400,
    "protein_per_100g": 24.5,
    "carbs_per_100g": 1.5,
    "fat_per_100g": 33,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-007",
    "name": "Sharp Provolone Cheese Slices",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 351,
    "protein_per_100g": 25.5,
    "carbs_per_100g": 2.1,
    "fat_per_100g": 26.6,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-008",
    "name": "Swiss Cheese (Baby Swiss Slices)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 380,
    "protein_per_100g": 27,
    "carbs_per_100g": 1.5,
    "fat_per_100g": 29.5,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-009",
    "name": "Grated Parmigiano-Reggiano (Aged Italian Parmesan)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 392,
    "protein_per_100g": 35.8,
    "carbs_per_100g": 3.2,
    "fat_per_100g": 25.8,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 15,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-010",
    "name": "Pecorino Romano (Aged Italian Sheep Milk Cheese)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 387,
    "protein_per_100g": 34,
    "carbs_per_100g": 3,
    "fat_per_100g": 26.9,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 15,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-011",
    "name": "Crumbled Greek Feta Cheese (in Brine Sheep/Goat Milk)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 264,
    "protein_per_100g": 14.2,
    "carbs_per_100g": 4.1,
    "fat_per_100g": 21.3,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-012",
    "name": "Soft Goat Cheese (Chevre Log)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 268,
    "protein_per_100g": 18.5,
    "carbs_per_100g": 0.9,
    "fat_per_100g": 21,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-013",
    "name": "Part-Skim Ricotta Cheese",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 138,
    "protein_per_100g": 11.4,
    "carbs_per_100g": 5.1,
    "fat_per_100g": 7.9,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 60,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-014",
    "name": "Whole Milk Ricotta Cheese",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 174,
    "protein_per_100g": 11.3,
    "carbs_per_100g": 3,
    "fat_per_100g": 13,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 60,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-015",
    "name": "Ricotta Salata (Salted Pressed Aged Sheep Cheese)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 280,
    "protein_per_100g": 17.5,
    "carbs_per_100g": 3.5,
    "fat_per_100g": 22,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 25,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-016",
    "name": "Gruyere Cheese (Cave Aged Swiss)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 413,
    "protein_per_100g": 29.8,
    "carbs_per_100g": 0.4,
    "fat_per_100g": 32.3,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-017",
    "name": "Monterey Jack Cheese Slices",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 373,
    "protein_per_100g": 24.5,
    "carbs_per_100g": 0.7,
    "fat_per_100g": 30.3,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-018",
    "name": "Pepper Jack Cheese (with Jalapenos)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 375,
    "protein_per_100g": 24,
    "carbs_per_100g": 1,
    "fat_per_100g": 30.5,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-019",
    "name": "Smoked Gouda Cheese",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 356,
    "protein_per_100g": 25,
    "carbs_per_100g": 2.2,
    "fat_per_100g": 27.4,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-020",
    "name": "Aged Dutch Gouda (Old Amsterdam style)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 380,
    "protein_per_100g": 26,
    "carbs_per_100g": 1,
    "fat_per_100g": 30,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-021",
    "name": "Manchego Cheese (Spanish Sheep Milk D.O.P.)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 416,
    "protein_per_100g": 26,
    "carbs_per_100g": 0.5,
    "fat_per_100g": 35,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-022",
    "name": "Asiago Cheese (Aged Italian Hard)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 392,
    "protein_per_100g": 29,
    "carbs_per_100g": 1.5,
    "fat_per_100g": 30,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-023",
    "name": "Fontina Cheese (Italian Melty Mountain)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 389,
    "protein_per_100g": 25.6,
    "carbs_per_100g": 1.5,
    "fat_per_100g": 31.1,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-024",
    "name": "Gorgonzola Dolce (Italian Blue Veined Creamy)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 353,
    "protein_per_100g": 21.4,
    "carbs_per_100g": 2.3,
    "fat_per_100g": 28.7,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 25,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-025",
    "name": "Roquefort Blue Cheese (French Sheep Milk)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 369,
    "protein_per_100g": 21.5,
    "carbs_per_100g": 2,
    "fat_per_100g": 30.6,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 25,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-026",
    "name": "Paneer (Traditional Indian Fresh Cooking Cheese)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 296,
    "protein_per_100g": 18.3,
    "carbs_per_100g": 4.5,
    "fat_per_100g": 22,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-027",
    "name": "Halloumi Grilling Cheese (Cypriot Pan-Seared)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 321,
    "protein_per_100g": 21.5,
    "carbs_per_100g": 2,
    "fat_per_100g": 25,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 40,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-028",
    "name": "Queso Fresco (Mexican Crumbly Fresh)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 299,
    "protein_per_100g": 18.2,
    "carbs_per_100g": 3.1,
    "fat_per_100g": 23.8,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-029",
    "name": "Cotija Cheese (Aged Mexican Grating)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 366,
    "protein_per_100g": 21,
    "carbs_per_100g": 3.5,
    "fat_per_100g": 29.5,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 20,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-030",
    "name": "Light Cream Cheese (Neufchatel 1/3 Less Fat)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 255,
    "protein_per_100g": 9,
    "carbs_per_100g": 6,
    "fat_per_100g": 22,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-031",
    "name": "Whipped Plain Cream Cheese",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 300,
    "protein_per_100g": 6.5,
    "carbs_per_100g": 5,
    "fat_per_100g": 29,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 25,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-032",
    "name": "Brie French Soft-Ripened Cheese",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 334,
    "protein_per_100g": 20.8,
    "carbs_per_100g": 0.5,
    "fat_per_100g": 27.7,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-033",
    "name": "Camembert French Soft Cheese",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 300,
    "protein_per_100g": 19.8,
    "carbs_per_100g": 0.5,
    "fat_per_100g": 24.3,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-034",
    "name": "Havarti Cheese Slices (Creamy Danish)",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 416,
    "protein_per_100g": 18,
    "carbs_per_100g": 0.8,
    "fat_per_100g": 38,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  },
  {
    "id": "de-chs-035",
    "name": "Mueller / Muenster Cheese Slices",
    "category": "dairy_eggs",
    "sub_category": "cheeses",
    "calories_per_100g": 368,
    "protein_per_100g": 23.4,
    "carbs_per_100g": 1.1,
    "fat_per_100g": 30,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cheese_fat"
  }
];
