import { FoodItem } from '../types';

export const FISH_SEAFOOD_DATABASE: FoodItem[] = [
  {
    "id": "fs-sal-001",
    "name": "Wild Alaskan Sockeye Salmon (Raw Fillet)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 133,
    "protein_per_100g": 21.3,
    "carbs_per_100g": 0,
    "fat_per_100g": 4.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-sal-002",
    "name": "Wild Alaskan Sockeye Salmon (Pan-Seared)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 169,
    "protein_per_100g": 27,
    "carbs_per_100g": 0,
    "fat_per_100g": 6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-sal-003",
    "name": "Wild Alaskan Sockeye Salmon (Baked Fillet)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 169,
    "protein_per_100g": 27,
    "carbs_per_100g": 0,
    "fat_per_100g": 6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-sal-004",
    "name": "Wild Alaskan King Salmon / Chinook (Raw Fillet)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 180,
    "protein_per_100g": 20,
    "carbs_per_100g": 0,
    "fat_per_100g": 10.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-sal-005",
    "name": "Wild Alaskan King Salmon (Grilled)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 230,
    "protein_per_100g": 26,
    "carbs_per_100g": 0,
    "fat_per_100g": 13.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-sal-006",
    "name": "Wild Alaskan Coho Salmon / Silver (Raw Fillet)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 140,
    "protein_per_100g": 21.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 5.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-sal-007",
    "name": "Wild Alaskan Coho Salmon (Grilled)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 175,
    "protein_per_100g": 27.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-sal-008",
    "name": "Atlantic Salmon (Farm-Raised Fresh Raw Fillet)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 208,
    "protein_per_100g": 20.4,
    "carbs_per_100g": 0,
    "fat_per_100g": 13.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-sal-009",
    "name": "Atlantic Salmon (Pan-Seared Crispy Skin)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 245,
    "protein_per_100g": 25,
    "carbs_per_100g": 0,
    "fat_per_100g": 15.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-sal-010",
    "name": "Atlantic Salmon (Oven-Baked Fillet)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 245,
    "protein_per_100g": 25,
    "carbs_per_100g": 0,
    "fat_per_100g": 15.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-sal-011",
    "name": "Atlantic Salmon (Cedar Plank Grilled)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 240,
    "protein_per_100g": 25.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 15,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-sal-012",
    "name": "Atlantic Salmon (Poached with Dill)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 230,
    "protein_per_100g": 26,
    "carbs_per_100g": 0,
    "fat_per_100g": 14,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-sal-013",
    "name": "Smoked Atlantic Salmon (Cold-Smoked Nova Lox Slices)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 117,
    "protein_per_100g": 18.3,
    "carbs_per_100g": 0,
    "fat_per_100g": 4.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 85,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-sal-014",
    "name": "Hot-Smoked Wild Alaskan Salmon (Flaked Fillet)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 175,
    "protein_per_100g": 24.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-sal-015",
    "name": "Salmon Burger Patty (100% Wild Salmon Grilled)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 165,
    "protein_per_100g": 22,
    "carbs_per_100g": 1,
    "fat_per_100g": 8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-sal-016",
    "name": "Steelhead Trout (Fresh Pink Fillet Raw)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 145,
    "protein_per_100g": 20.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 6.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-sal-017",
    "name": "Steelhead Trout (Baked with Lemon & Herbs)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 185,
    "protein_per_100g": 26.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 8.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-sal-018",
    "name": "Rainbow Trout (Fresh Whole / Fillet Pan-Fried)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 160,
    "protein_per_100g": 24,
    "carbs_per_100g": 0,
    "fat_per_100g": 6.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-sal-019",
    "name": "Brook Trout (Fresh Mountain Trout Broiled)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 150,
    "protein_per_100g": 23.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 5.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-sal-020",
    "name": "Arctic Char (Sustainable Cold-Water Fillet Pan-Seared)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 170,
    "protein_per_100g": 24,
    "carbs_per_100g": 0,
    "fat_per_100g": 8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-wht-001",
    "name": "Pacific Cod (Wild Raw Fillet)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 82,
    "protein_per_100g": 17.8,
    "carbs_per_100g": 0,
    "fat_per_100g": 0.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-002",
    "name": "Pacific Cod (Baked with Lemon Pepper)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 105,
    "protein_per_100g": 23,
    "carbs_per_100g": 0,
    "fat_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-003",
    "name": "Atlantic Cod (Wild Steamed / Poached Fillet)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 105,
    "protein_per_100g": 23,
    "carbs_per_100g": 0,
    "fat_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-004",
    "name": "Pacific Halibut (Wild Fresh Raw Fillet)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 110,
    "protein_per_100g": 20.8,
    "carbs_per_100g": 0,
    "fat_per_100g": 2.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-005",
    "name": "Pacific Halibut (Pan-Seared Steak)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 140,
    "protein_per_100g": 27,
    "carbs_per_100g": 0,
    "fat_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-006",
    "name": "Haddock (Wild Raw Fillet)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 90,
    "protein_per_100g": 20,
    "carbs_per_100g": 0,
    "fat_per_100g": 0.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-007",
    "name": "Haddock (Baked Lemon Herb Fillet)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 112,
    "protein_per_100g": 24.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-008",
    "name": "Alaskan Pollock (Wild Raw Fillet)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 92,
    "protein_per_100g": 19.4,
    "carbs_per_100g": 0,
    "fat_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-009",
    "name": "Alaskan Pollock (Baked Fillet)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 115,
    "protein_per_100g": 24.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-010",
    "name": "Chilean Sea Bass / Patagonian Toothfish (Pan-Seared)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 220,
    "protein_per_100g": 22,
    "carbs_per_100g": 0,
    "fat_per_100g": 14.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-wht-011",
    "name": "Mediterranean Sea Bass / Branzino (Whole Roasted)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 135,
    "protein_per_100g": 24,
    "carbs_per_100g": 0,
    "fat_per_100g": 4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-012",
    "name": "Red Snapper (Gulf Wild Fillet Pan-Seared)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 128,
    "protein_per_100g": 26,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-013",
    "name": "Yellowtail Snapper (Grilled Fillet)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 125,
    "protein_per_100g": 25.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-014",
    "name": "Grouper (Black / Red Grouper Grilled Fillet)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 118,
    "protein_per_100g": 25,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-015",
    "name": "Mahi-Mahi / Dorado (Wild Grilled Fillet)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 110,
    "protein_per_100g": 23.7,
    "carbs_per_100g": 0,
    "fat_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-016",
    "name": "Mahi-Mahi (Blackened Cajun Spiced Grilled)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 115,
    "protein_per_100g": 24,
    "carbs_per_100g": 0.5,
    "fat_per_100g": 1.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-017",
    "name": "Swordfish (Grilled Loin Steak)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 155,
    "protein_per_100g": 25.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 5.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-018",
    "name": "Tilapia (Fresh Farmed Raw Fillet)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 96,
    "protein_per_100g": 20.1,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-019",
    "name": "Tilapia (Baked Garlic Herb Fillet)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 120,
    "protein_per_100g": 26,
    "carbs_per_100g": 0,
    "fat_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-020",
    "name": "Catfish (US Farm-Raised Blackened / Baked)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 145,
    "protein_per_100g": 21,
    "carbs_per_100g": 0,
    "fat_per_100g": 6.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-021",
    "name": "Flounder / Summer Fluke (Delicate White Fillet Baked)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 95,
    "protein_per_100g": 20.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-022",
    "name": "Dover Sole (Pan-Seared French Meuniere style)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 110,
    "protein_per_100g": 22,
    "carbs_per_100g": 0.5,
    "fat_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-023",
    "name": "Monkfish / Poor Man's Lobster (Roasted Loin)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 97,
    "protein_per_100g": 19.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-024",
    "name": "Turbot (European Flatfish Roasted)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 122,
    "protein_per_100g": 21,
    "carbs_per_100g": 0,
    "fat_per_100g": 3.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-025",
    "name": "Walleye (Freshwater Wild Fillet Pan-Fried)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 120,
    "protein_per_100g": 24,
    "carbs_per_100g": 0,
    "fat_per_100g": 2.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-wht-026",
    "name": "Yellow Perch (Great Lakes Freshwater Fillet Pan-Seared)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 115,
    "protein_per_100g": 23.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-tun-001",
    "name": "Yellowfin Ahi Tuna (Sashimi Grade Raw Loin)",
    "category": "fish_seafood",
    "sub_category": "tuna_pelagic",
    "calories_per_100g": 109,
    "protein_per_100g": 24.4,
    "carbs_per_100g": 0,
    "fat_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-tun-002",
    "name": "Yellowfin Ahi Tuna (Seared Rare Steak)",
    "category": "fish_seafood",
    "sub_category": "tuna_pelagic",
    "calories_per_100g": 130,
    "protein_per_100g": 29,
    "carbs_per_100g": 0,
    "fat_per_100g": 0.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-tun-003",
    "name": "Bigeye Tuna (Raw Sashimi Cuts)",
    "category": "fish_seafood",
    "sub_category": "tuna_pelagic",
    "calories_per_100g": 125,
    "protein_per_100g": 25,
    "carbs_per_100g": 0,
    "fat_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-tun-004",
    "name": "Bluefin Tuna (Otoro Fatty Belly Sashimi)",
    "category": "fish_seafood",
    "sub_category": "tuna_pelagic",
    "calories_per_100g": 280,
    "protein_per_100g": 22,
    "carbs_per_100g": 0,
    "fat_per_100g": 21,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-tun-005",
    "name": "Bluefin Tuna (Akami Lean Red Meat Sashimi)",
    "category": "fish_seafood",
    "sub_category": "tuna_pelagic",
    "calories_per_100g": 120,
    "protein_per_100g": 26,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-tun-006",
    "name": "Albacore Tuna (Fresh Loin Grilled Steak)",
    "category": "fish_seafood",
    "sub_category": "tuna_pelagic",
    "calories_per_100g": 140,
    "protein_per_100g": 27,
    "carbs_per_100g": 0,
    "fat_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-tun-007",
    "name": "Canned Solid White Albacore Tuna in Water (Drained)",
    "category": "fish_seafood",
    "sub_category": "tuna_pelagic",
    "calories_per_100g": 109,
    "protein_per_100g": 24,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 113,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-tun-008",
    "name": "Canned Chunk Light Tuna in Water (Low Mercury Drained)",
    "category": "fish_seafood",
    "sub_category": "tuna_pelagic",
    "calories_per_100g": 90,
    "protein_per_100g": 21,
    "carbs_per_100g": 0,
    "fat_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 113,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-tun-009",
    "name": "Canned Yellowfin Tuna in Extra Virgin Olive Oil (Drained)",
    "category": "fish_seafood",
    "sub_category": "tuna_pelagic",
    "calories_per_100g": 198,
    "protein_per_100g": 29,
    "carbs_per_100g": 0,
    "fat_per_100g": 8.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 113,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-tun-010",
    "name": "Wild Pacific Sardines (Grilled Whole Fresh)",
    "category": "fish_seafood",
    "sub_category": "tuna_pelagic",
    "calories_per_100g": 185,
    "protein_per_100g": 21,
    "carbs_per_100g": 0,
    "fat_per_100g": 10.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-tun-011",
    "name": "Canned Sardines in Extra Virgin Olive Oil (Skin & Bones Rich in Calcium)",
    "category": "fish_seafood",
    "sub_category": "tuna_pelagic",
    "calories_per_100g": 208,
    "protein_per_100g": 24.6,
    "carbs_per_100g": 0,
    "fat_per_100g": 11.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 106,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-tun-012",
    "name": "Canned Sardines in Spring Water (Drained)",
    "category": "fish_seafood",
    "sub_category": "tuna_pelagic",
    "calories_per_100g": 160,
    "protein_per_100g": 22,
    "carbs_per_100g": 0,
    "fat_per_100g": 7.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 106,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-tun-013",
    "name": "Atlantic Mackerel (Fresh Grilled Rich in Omega-3 EPA/DHA)",
    "category": "fish_seafood",
    "sub_category": "tuna_pelagic",
    "calories_per_100g": 262,
    "protein_per_100g": 23.9,
    "carbs_per_100g": 0,
    "fat_per_100g": 17.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-tun-014",
    "name": "Smoked Mackerel Fillet (Peppered Hot-Smoked)",
    "category": "fish_seafood",
    "sub_category": "tuna_pelagic",
    "calories_per_100g": 290,
    "protein_per_100g": 22,
    "carbs_per_100g": 0,
    "fat_per_100g": 22,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-tun-015",
    "name": "Spanish Mackerel (Baked / Broiled Fillet)",
    "category": "fish_seafood",
    "sub_category": "tuna_pelagic",
    "calories_per_100g": 190,
    "protein_per_100g": 24,
    "carbs_per_100g": 0,
    "fat_per_100g": 9.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-tun-016",
    "name": "Mediterranean Anchovies (Fresh Broiled / Grilled)",
    "category": "fish_seafood",
    "sub_category": "tuna_pelagic",
    "calories_per_100g": 160,
    "protein_per_100g": 22,
    "carbs_per_100g": 0,
    "fat_per_100g": 7.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-tun-017",
    "name": "Canned Flat Anchovy Fillets in Olive Oil (Drained Savory Umami)",
    "category": "fish_seafood",
    "sub_category": "tuna_pelagic",
    "calories_per_100g": 210,
    "protein_per_100g": 29,
    "carbs_per_100g": 0,
    "fat_per_100g": 10,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-tun-018",
    "name": "Herring / Kipper (Traditional Smoked Fillet)",
    "category": "fish_seafood",
    "sub_category": "tuna_pelagic",
    "calories_per_100g": 215,
    "protein_per_100g": 24,
    "carbs_per_100g": 0,
    "fat_per_100g": 12.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-tun-019",
    "name": "Pickled Herring in Wine Sauce (Sweet Onion Brine)",
    "category": "fish_seafood",
    "sub_category": "tuna_pelagic",
    "calories_per_100g": 195,
    "protein_per_100g": 14,
    "carbs_per_100g": 9.5,
    "fat_per_100g": 11,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 85,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-cru-001",
    "name": "Wild Gulf White Shrimp (Raw Peeled & Deveined)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 85,
    "protein_per_100g": 20.1,
    "carbs_per_100g": 0,
    "fat_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-002",
    "name": "Wild Gulf White Shrimp (Steamed / Boiled Cocktail)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 99,
    "protein_per_100g": 24,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-003",
    "name": "Wild Gulf White Shrimp (Grilled Skewers)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 105,
    "protein_per_100g": 24.5,
    "carbs_per_100g": 0.2,
    "fat_per_100g": 0.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-004",
    "name": "Jumbo Tiger Prawns (Grilled Garlic Herb)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 110,
    "protein_per_100g": 25,
    "carbs_per_100g": 0.5,
    "fat_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-005",
    "name": "Argentine Red Shrimp (Sweet Lobster-like Seared)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 90,
    "protein_per_100g": 21,
    "carbs_per_100g": 0,
    "fat_per_100g": 0.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-006",
    "name": "Maine Lobster Tail (Steamed Meat Only)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 89,
    "protein_per_100g": 19,
    "carbs_per_100g": 0,
    "fat_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-007",
    "name": "Maine Lobster Claw & Knuckle Meat (Cooked Fresh)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 90,
    "protein_per_100g": 19.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 0.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-008",
    "name": "Alaskan King Crab Legs (Steamed Meat Only)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 97,
    "protein_per_100g": 19.4,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-009",
    "name": "Alaskan Snow Crab Meat (Steamed Clusters)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 90,
    "protein_per_100g": 18.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-010",
    "name": "Maryland Blue Crab Lump Meat (Fresh Pasteurized)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 83,
    "protein_per_100g": 18,
    "carbs_per_100g": 0,
    "fat_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-011",
    "name": "Maryland Blue Crab Jumbo Lump (Premium White Meat)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 85,
    "protein_per_100g": 19,
    "carbs_per_100g": 0,
    "fat_per_100g": 0.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-012",
    "name": "Dungeness Crab Meat (Pacific Steamed)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 110,
    "protein_per_100g": 22,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-013",
    "name": "Soft-Shell Blue Crab (Pan-Seared)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 120,
    "protein_per_100g": 19,
    "carbs_per_100g": 1,
    "fat_per_100g": 4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-014",
    "name": "Crawfish / Crayfish Tail Meat (Louisiana Boiled Spiced)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 82,
    "protein_per_100g": 17.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-015",
    "name": "Wild Sea Scallops (Jumbo Dry-Packed Raw U-10)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 69,
    "protein_per_100g": 12.1,
    "carbs_per_100g": 3.2,
    "fat_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-016",
    "name": "Wild Sea Scallops (Pan-Seared Golden Crust)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 111,
    "protein_per_100g": 20.5,
    "carbs_per_100g": 4.5,
    "fat_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-017",
    "name": "Bay Scallops (Sweet Tender Sauteed)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 95,
    "protein_per_100g": 18,
    "carbs_per_100g": 3.5,
    "fat_per_100g": 0.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-018",
    "name": "Wild Maine Blue Mussels (Steamed in White Wine Garlic Broth)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 86,
    "protein_per_100g": 11.9,
    "carbs_per_100g": 3.7,
    "fat_per_100g": 2.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-019",
    "name": "Littleneck Hard Clams (Steamed in Broth)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 74,
    "protein_per_100g": 12.8,
    "carbs_per_100g": 2.6,
    "fat_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-020",
    "name": "Manila Clams (Steamed / Sautéed)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 75,
    "protein_per_100g": 13,
    "carbs_per_100g": 2.5,
    "fat_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-021",
    "name": "Fresh Raw Oysters on the Half Shell (Pacific / Atlantic Kumamoto)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 68,
    "protein_per_100g": 7,
    "carbs_per_100g": 3.9,
    "fat_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-022",
    "name": "Pacific Squid / Calamari Tubes & Tentacles (Grilled Charred)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 92,
    "protein_per_100g": 15.6,
    "carbs_per_100g": 3.1,
    "fat_per_100g": 1.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-023",
    "name": "Spanish Octopus (Tender Braised & Charred on Grill)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 82,
    "protein_per_100g": 14.9,
    "carbs_per_100g": 2.2,
    "fat_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-cru-024",
    "name": "Cuttlefish (Cleaned Strips Pan-Seared)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 79,
    "protein_per_100g": 16.2,
    "carbs_per_100g": 0.8,
    "fat_per_100g": 0.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-ext-001",
    "name": "Wild Alaskan Pink Salmon (Raw Fillet)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 116,
    "protein_per_100g": 20,
    "carbs_per_100g": 0,
    "fat_per_100g": 3.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-ext-002",
    "name": "Wild Alaskan Keta / Chum Salmon (Baked Fillet)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 120,
    "protein_per_100g": 22,
    "carbs_per_100g": 0,
    "fat_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-ext-003",
    "name": "Wahoo / Ono (Hawaiian White Gamefish Grilled Steak)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 130,
    "protein_per_100g": 24.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-ext-004",
    "name": "Hamachi / Japanese Yellowtail Amberjack (Sashimi Grade Raw)",
    "category": "fish_seafood",
    "sub_category": "tuna_pelagic",
    "calories_per_100g": 146,
    "protein_per_100g": 23.1,
    "carbs_per_100g": 0,
    "fat_per_100g": 5.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-ext-005",
    "name": "Opah / Moonfish (Rich Pan-Seared Loin Steak)",
    "category": "fish_seafood",
    "sub_category": "tuna_pelagic",
    "calories_per_100g": 150,
    "protein_per_100g": 23,
    "carbs_per_100g": 0,
    "fat_per_100g": 6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-ext-006",
    "name": "Corvina White Sea Bass (Pan-Seared Fillet)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 115,
    "protein_per_100g": 23,
    "carbs_per_100g": 0,
    "fat_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-ext-007",
    "name": "Wild Atlantic Black Sea Bass (Whole Roasted)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 97,
    "protein_per_100g": 18.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-ext-008",
    "name": "Striped Bass / Rockfish (Broiled Fillet)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 124,
    "protein_per_100g": 23.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-ext-009",
    "name": "Pacific Sanddab (Delicate Sweet Flatfish Pan-Fried)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 90,
    "protein_per_100g": 19,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-ext-010",
    "name": "Sablefish / Black Cod (Miso Glazed Rich Butterfish)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 250,
    "protein_per_100g": 17.5,
    "carbs_per_100g": 3,
    "fat_per_100g": 19.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-ext-011",
    "name": "Barramundi / Asian Sea Bass (Sustainably Farmed Pan-Seared)",
    "category": "fish_seafood",
    "sub_category": "white_fish",
    "calories_per_100g": 108,
    "protein_per_100g": 20,
    "carbs_per_100g": 0,
    "fat_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-ext-012",
    "name": "Florida Stone Crab Claws (Cooked Chilled with Mustard Sauce)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 95,
    "protein_per_100g": 19,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-ext-013",
    "name": "Jonah Crab Meat (Sweet Atlantic Cooked)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 88,
    "protein_per_100g": 18.2,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-ext-014",
    "name": "Langoustines / Norway Lobsters (Split Broiled Garlic Butter)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 90,
    "protein_per_100g": 18.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-ext-015",
    "name": "Canned Wild Alaskan Sockeye Salmon (Skinless Boneless Drained)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 135,
    "protein_per_100g": 23.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 113,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-ext-016",
    "name": "Canned Smoked Oysters in Olive Oil (Drained Iron Rich Crown Prince)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 175,
    "protein_per_100g": 14.5,
    "carbs_per_100g": 7,
    "fat_per_100g": 9.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 85,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-ext-017",
    "name": "Canned Smoked Tiny Mussels in Extra Virgin Olive Oil (Patagonia Provisions)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 180,
    "protein_per_100g": 16,
    "carbs_per_100g": 6,
    "fat_per_100g": 10,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 85,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "shellfish_lean"
  },
  {
    "id": "fs-ext-018",
    "name": "Salmon Roe / Ikura (Cured Red Caviar Pearls)",
    "category": "fish_seafood",
    "sub_category": "salmon_trout",
    "calories_per_100g": 250,
    "protein_per_100g": 29,
    "carbs_per_100g": 3,
    "fat_per_100g": 14,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  },
  {
    "id": "fs-ext-019",
    "name": "Tobiko Flying Fish Roe (Crispy Orange Pearls)",
    "category": "fish_seafood",
    "sub_category": "tuna_pelagic",
    "calories_per_100g": 130,
    "protein_per_100g": 22,
    "carbs_per_100g": 4,
    "fat_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_lean"
  },
  {
    "id": "fs-ext-020",
    "name": "Fresh Sea Urchin / Uni (Santa Barbara Sweet Creamy Raw)",
    "category": "fish_seafood",
    "sub_category": "crustaceans",
    "calories_per_100g": 120,
    "protein_per_100g": 16,
    "carbs_per_100g": 4.5,
    "fat_per_100g": 4.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fish_fatty"
  }
];
