import { FoodItem } from '../types';

export const FISH_SEAFOOD_DATABASE: FoodItem[] = [
  // ==========================================
  // SALMON & FATTY FISH (15+ items)
  // ==========================================
  {
    id: 'fs-sal-001',
    name: 'Wild Atlantic Salmon Fillet (Raw)',
    category: 'fish_seafood',
    sub_category: 'salmon_trout',
    calories_per_100g: 142,
    protein_per_100g: 19.8,
    carbs_per_100g: 0.0,
    fat_per_100g: 6.3,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fatty_protein',
  },
  {
    id: 'fs-sal-002',
    name: 'Wild Atlantic Salmon Fillet (Pan-Seared / Baked)',
    category: 'fish_seafood',
    sub_category: 'salmon_trout',
    calories_per_100g: 208,
    protein_per_100g: 20.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 13.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fatty_protein',
  },
  {
    id: 'fs-sal-003',
    name: 'Wild Alaskan Sockeye Salmon (Cooked)',
    category: 'fish_seafood',
    sub_category: 'salmon_trout',
    calories_per_100g: 169,
    protein_per_100g: 22.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 8.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fatty_protein',
  },
  {
    id: 'fs-sal-004',
    name: 'Wild King / Chinook Salmon (Grilled)',
    category: 'fish_seafood',
    sub_category: 'salmon_trout',
    calories_per_100g: 231,
    protein_per_100g: 25.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 13.4,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fatty_protein',
  },
  {
    id: 'fs-sal-005',
    name: 'Rainbow Trout Fillet (Baked)',
    category: 'fish_seafood',
    sub_category: 'salmon_trout',
    calories_per_100g: 141,
    protein_per_100g: 20.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 6.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fatty_protein',
  },
  {
    id: 'fs-sal-006',
    name: 'Steelhead Trout Fillet (Broiled)',
    category: 'fish_seafood',
    sub_category: 'salmon_trout',
    calories_per_100g: 160,
    protein_per_100g: 21.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 7.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fatty_protein',
  },
  {
    id: 'fs-sal-007',
    name: 'Smoked Salmon / Nova Lox',
    category: 'fish_seafood',
    sub_category: 'salmon_trout',
    calories_per_100g: 117,
    protein_per_100g: 18.3,
    carbs_per_100g: 0.0,
    fat_per_100g: 4.3,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 85,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fatty_protein',
  },

  // ==========================================
  // LEAN WHITE FISH (20+ items)
  // ==========================================
  {
    id: 'fs-wht-001',
    name: 'Atlantic Cod Fillet (Raw)',
    category: 'fish_seafood',
    sub_category: 'white_fish',
    calories_per_100g: 82,
    protein_per_100g: 18.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.7,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 170,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-wht-002',
    name: 'Baked Atlantic Cod Fillet',
    category: 'fish_seafood',
    sub_category: 'white_fish',
    calories_per_100g: 105,
    protein_per_100g: 22.8,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.9,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 170,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-wht-003',
    name: 'Fresh Tilapia Fillet (Pan-Seared)',
    category: 'fish_seafood',
    sub_category: 'white_fish',
    calories_per_100g: 96,
    protein_per_100g: 20.1,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.7,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-wht-004',
    name: 'Pacific Halibut Fillet (Broiled)',
    category: 'fish_seafood',
    sub_category: 'white_fish',
    calories_per_100g: 110,
    protein_per_100g: 23.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.6,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-wht-005',
    name: 'Mahi Mahi Fillet (Grilled)',
    category: 'fish_seafood',
    sub_category: 'white_fish',
    calories_per_100g: 85,
    protein_per_100g: 18.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.7,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-wht-006',
    name: 'Haddock Fillet (Baked)',
    category: 'fish_seafood',
    sub_category: 'white_fish',
    calories_per_100g: 90,
    protein_per_100g: 20.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.7,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-wht-007',
    name: 'Red Snapper Fillet (Grilled)',
    category: 'fish_seafood',
    sub_category: 'white_fish',
    calories_per_100g: 100,
    protein_per_100g: 20.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.3,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-wht-008',
    name: 'Chilean Sea Bass / Patagonian Toothfish',
    category: 'fish_seafood',
    sub_category: 'white_fish',
    calories_per_100g: 184,
    protein_per_100g: 18.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 12.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fatty_protein',
  },
  {
    id: 'fs-wht-009',
    name: 'Flounder / Sole Fillet (Steamed)',
    category: 'fish_seafood',
    sub_category: 'white_fish',
    calories_per_100g: 86,
    protein_per_100g: 18.2,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.2,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-wht-010',
    name: 'Alaskan Pollock Fillet (Poached)',
    category: 'fish_seafood',
    sub_category: 'white_fish',
    calories_per_100g: 92,
    protein_per_100g: 19.4,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.8,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },

  // ==========================================
  // TUNA & FRESH STEAKS (10+ items)
  // ==========================================
  {
    id: 'fs-tna-001',
    name: 'Fresh Yellowfin Ahi Tuna Steak (Raw / Sashimi)',
    category: 'fish_seafood',
    sub_category: 'tuna_swordfish',
    calories_per_100g: 109,
    protein_per_100g: 24.4,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-tna-002',
    name: 'Seared Sesame Crusted Ahi Tuna Steak',
    category: 'fish_seafood',
    sub_category: 'tuna_swordfish',
    calories_per_100g: 135,
    protein_per_100g: 28.0,
    carbs_per_100g: 1.0,
    fat_per_100g: 2.0,
    fiber_per_100g: 0.2,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-tna-003',
    name: 'Swordfish Steak (Grilled)',
    category: 'fish_seafood',
    sub_category: 'tuna_swordfish',
    calories_per_100g: 144,
    protein_per_100g: 20.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 6.6,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },

  // ==========================================
  // SHRIMP & PRAWNS (10+ items)
  // ==========================================
  {
    id: 'fs-shm-001',
    name: 'Raw Jumbo White Shrimp (Peeled & Deveined)',
    category: 'fish_seafood',
    sub_category: 'shrimp_shellfish',
    calories_per_100g: 85,
    protein_per_100g: 20.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-shm-002',
    name: 'Steamed Cocktail Shrimp',
    category: 'fish_seafood',
    sub_category: 'shrimp_shellfish',
    calories_per_100g: 99,
    protein_per_100g: 24.0,
    carbs_per_100g: 0.2,
    fat_per_100g: 0.3,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-shm-003',
    name: 'Grilled Garlic Herb Tiger Prawns',
    category: 'fish_seafood',
    sub_category: 'shrimp_shellfish',
    calories_per_100g: 110,
    protein_per_100g: 23.0,
    carbs_per_100g: 1.0,
    fat_per_100g: 1.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },

  // ==========================================
  // SCALLOPS, CRAB & LOBSTER (12+ items)
  // ==========================================
  {
    id: 'fs-scl-001',
    name: 'Wild Sea Scallops (Pan-Seared)',
    category: 'fish_seafood',
    sub_category: 'scallops_crab_lobster',
    calories_per_100g: 111,
    protein_per_100g: 20.5,
    carbs_per_100g: 5.4,
    fat_per_100g: 0.8,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-scl-002',
    name: 'Wild Alaskan King Crab Meat (Steamed)',
    category: 'fish_seafood',
    sub_category: 'scallops_crab_lobster',
    calories_per_100g: 84,
    protein_per_100g: 18.3,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.6,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 140,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-scl-003',
    name: 'Maine Lobster Tail Meat (Steamed)',
    category: 'fish_seafood',
    sub_category: 'scallops_crab_lobster',
    calories_per_100g: 89,
    protein_per_100g: 19.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.9,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 140,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-scl-004',
    name: 'Steamed Blue Mussels (Meat Only)',
    category: 'fish_seafood',
    sub_category: 'scallops_crab_lobster',
    calories_per_100g: 86,
    protein_per_100g: 11.9,
    carbs_per_100g: 3.7,
    fat_per_100g: 2.2,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-scl-005',
    name: 'Grilled Calamari / Squid (Tubes)',
    category: 'fish_seafood',
    sub_category: 'scallops_crab_lobster',
    calories_per_100g: 92,
    protein_per_100g: 15.6,
    carbs_per_100g: 3.1,
    fat_per_100g: 1.4,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 140,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },

  // ==========================================
  // CANNED & PRESERVED FISH (10+ items)
  // ==========================================
  {
    id: 'fs-can-001',
    name: 'Canned Chunk Light Tuna (in Spring Water, Drained)',
    category: 'fish_seafood',
    sub_category: 'canned_seafood',
    calories_per_100g: 116,
    protein_per_100g: 25.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.8,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-can-002',
    name: 'Canned Solid White Albacore Tuna (in Water, Drained)',
    category: 'fish_seafood',
    sub_category: 'canned_seafood',
    calories_per_100g: 128,
    protein_per_100g: 27.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 2.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'lean_protein',
  },
  {
    id: 'fs-can-003',
    name: 'Wild Sardines in Spring Water (Drained)',
    category: 'fish_seafood',
    sub_category: 'canned_seafood',
    calories_per_100g: 185,
    protein_per_100g: 24.6,
    carbs_per_100g: 0.0,
    fat_per_100g: 9.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 90,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'fatty_protein',
  },
  {
    id: 'fs-can-004',
    name: 'Wild Sardines in Extra Virgin Olive Oil',
    category: 'fish_seafood',
    sub_category: 'canned_seafood',
    calories_per_100g: 208,
    protein_per_100g: 24.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 11.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 90,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'fatty_protein',
  },
  {
    id: 'fs-can-005',
    name: 'Canned Wild Alaskan Salmon (Pink / Red, Drained)',
    category: 'fish_seafood',
    sub_category: 'canned_seafood',
    calories_per_100g: 142,
    protein_per_100g: 22.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 5.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'fatty_protein',
  },
];
