import { FoodItem } from '../types';

export const FRUITS_BERRIES_DATABASE: FoodItem[] = [
  {
    "id": "fb-ber-001",
    "name": "Fresh Organic Strawberries",
    "category": "fruits",
    "sub_category": "berries",
    "calories_per_100g": 32,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 7.7,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ber-002",
    "name": "Frozen Unsweetened Strawberries",
    "category": "fruits",
    "sub_category": "berries",
    "calories_per_100g": 35,
    "protein_per_100g": 0.6,
    "carbs_per_100g": 8.5,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "freezer_monthly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ber-003",
    "name": "Fresh Blueberries",
    "category": "fruits",
    "sub_category": "berries",
    "calories_per_100g": 57,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 14.5,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 2.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 125,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ber-004",
    "name": "Wild Frozen Blueberries (Antioxidant Rich Wyman's)",
    "category": "fruits",
    "sub_category": "berries",
    "calories_per_100g": 55,
    "protein_per_100g": 0.8,
    "carbs_per_100g": 14,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 3.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 125,
    "default_unit": "g",
    "storage_type": "freezer_monthly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ber-005",
    "name": "Fresh Blackberries",
    "category": "fruits",
    "sub_category": "berries",
    "calories_per_100g": 43,
    "protein_per_100g": 1.4,
    "carbs_per_100g": 9.6,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 5.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 125,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ber-006",
    "name": "Fresh Raspberries",
    "category": "fruits",
    "sub_category": "berries",
    "calories_per_100g": 52,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 11.9,
    "fat_per_100g": 0.7,
    "fiber_per_100g": 6.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 125,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ber-007",
    "name": "Fresh Boysenberries",
    "category": "fruits",
    "sub_category": "berries",
    "calories_per_100g": 50,
    "protein_per_100g": 1.1,
    "carbs_per_100g": 12.2,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 125,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ber-008",
    "name": "Fresh Marionberries (Pacific Northwest Blackberry)",
    "category": "fruits",
    "sub_category": "berries",
    "calories_per_100g": 48,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 11.5,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 5.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 125,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ber-009",
    "name": "Fresh Cranberries (Raw Whole Tart)",
    "category": "fruits",
    "sub_category": "berries",
    "calories_per_100g": 46,
    "protein_per_100g": 0.4,
    "carbs_per_100g": 12,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 4.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ber-010",
    "name": "Frozen Unsweetened Mixed Berries (Triple Berry Blend)",
    "category": "fruits",
    "sub_category": "berries",
    "calories_per_100g": 50,
    "protein_per_100g": 1,
    "carbs_per_100g": 12.5,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 4.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "freezer_monthly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ber-011",
    "name": "Organic Pure Acai Puree Packets (Sambazon Unsweetened 0g Sugar)",
    "category": "fruits",
    "sub_category": "berries",
    "calories_per_100g": 70,
    "protein_per_100g": 1,
    "carbs_per_100g": 4,
    "fat_per_100g": 5,
    "fiber_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "freezer_monthly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ber-012",
    "name": "Fresh Red Currants",
    "category": "fruits",
    "sub_category": "berries",
    "calories_per_100g": 56,
    "protein_per_100g": 1.4,
    "carbs_per_100g": 13.8,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 4.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ber-013",
    "name": "Fresh Black Currants",
    "category": "fruits",
    "sub_category": "berries",
    "calories_per_100g": 63,
    "protein_per_100g": 1.4,
    "carbs_per_100g": 15.4,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 6.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ber-014",
    "name": "Fresh Mulberries (Black / Red)",
    "category": "fruits",
    "sub_category": "berries",
    "calories_per_100g": 43,
    "protein_per_100g": 1.4,
    "carbs_per_100g": 9.8,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 1.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ber-015",
    "name": "Fresh Gooseberries (Tart Green)",
    "category": "fruits",
    "sub_category": "berries",
    "calories_per_100g": 44,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 10.2,
    "fat_per_100g": 0.6,
    "fiber_per_100g": 4.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ber-016",
    "name": "Fresh Lingonberries (Wild Scandinavian)",
    "category": "fruits",
    "sub_category": "berries",
    "calories_per_100g": 50,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 11.5,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 3.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ber-017",
    "name": "Freeze-Dried Strawberries (Crunchy Whole)",
    "category": "fruits",
    "sub_category": "berries",
    "calories_per_100g": 320,
    "protein_per_100g": 7,
    "carbs_per_100g": 75,
    "fat_per_100g": 2.5,
    "fiber_per_100g": 14,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ber-018",
    "name": "Freeze-Dried Blueberries",
    "category": "fruits",
    "sub_category": "berries",
    "calories_per_100g": 340,
    "protein_per_100g": 4,
    "carbs_per_100g": 80,
    "fat_per_100g": 2,
    "fiber_per_100g": 15,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-001",
    "name": "Honeycrisp Apple (Crisp Sweet Whole)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 52,
    "protein_per_100g": 0.3,
    "carbs_per_100g": 13.8,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-002",
    "name": "Granny Smith Apple (Tart Green Whole)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 50,
    "protein_per_100g": 0.4,
    "carbs_per_100g": 13.6,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-003",
    "name": "Fuji Apple (Crisp Sweet Whole)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 54,
    "protein_per_100g": 0.3,
    "carbs_per_100g": 14.2,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-004",
    "name": "Gala Apple (Sweet Red Whole)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 52,
    "protein_per_100g": 0.3,
    "carbs_per_100g": 13.7,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-005",
    "name": "Pink Lady / Cripps Pink Apple",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 53,
    "protein_per_100g": 0.3,
    "carbs_per_100g": 13.9,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-006",
    "name": "Golden Delicious Apple",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 52,
    "protein_per_100g": 0.3,
    "carbs_per_100g": 13.6,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-007",
    "name": "McIntosh Apple (Juicy Tart)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 50,
    "protein_per_100g": 0.3,
    "carbs_per_100g": 13.5,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-008",
    "name": "Bartlett Pear (Juicy Sweet Yellow Whole)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 57,
    "protein_per_100g": 0.4,
    "carbs_per_100g": 15.2,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 3.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 175,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-009",
    "name": "Bosc Pear (Firm Brown Russet)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 58,
    "protein_per_100g": 0.4,
    "carbs_per_100g": 15.5,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 3.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 175,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-010",
    "name": "D'Anjou Green Pear",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 57,
    "protein_per_100g": 0.4,
    "carbs_per_100g": 15,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 3.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 175,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-011",
    "name": "Red D'Anjou Pear",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 57,
    "protein_per_100g": 0.4,
    "carbs_per_100g": 15,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 3.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 175,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-012",
    "name": "Asian Pear / Apple Pear (Crisp Round)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 42,
    "protein_per_100g": 0.5,
    "carbs_per_100g": 10.6,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 3.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-013",
    "name": "Unsweetened Applesauce (Organic 100% Apples)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 42,
    "protein_per_100g": 0.2,
    "carbs_per_100g": 11.3,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 1.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-014",
    "name": "Yellow Freestone Peach (Fresh Ripe Whole)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 39,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 9.5,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-015",
    "name": "White Flesh Peach (Sweet Floral)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 39,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 9.5,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-016",
    "name": "Yellow Nectarine (Smooth Skin)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 44,
    "protein_per_100g": 1.1,
    "carbs_per_100g": 10.6,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 1.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-017",
    "name": "White Nectarine (Sweet Mild)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 44,
    "protein_per_100g": 1.1,
    "carbs_per_100g": 10.6,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 1.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-018",
    "name": "Red Plum / Santa Rosa (Juicy Sweet-Tart)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 46,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 11.4,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 1.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-019",
    "name": "Black Amber Plum (Deep Purple Flesh)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 46,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 11.4,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 1.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-020",
    "name": "Pluot / Dinosaur Egg (Plum-Apricot Hybrid)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 50,
    "protein_per_100g": 0.8,
    "carbs_per_100g": 12,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-021",
    "name": "Fresh Apricots (Whole Sweet Golden)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 48,
    "protein_per_100g": 1.4,
    "carbs_per_100g": 11.1,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-022",
    "name": "Sweet Dark Bing Cherries (Fresh Stemmed)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 63,
    "protein_per_100g": 1.1,
    "carbs_per_100g": 16,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-023",
    "name": "Rainier Sweet Cherries (Yellow & Red Blush)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 65,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 16.5,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-024",
    "name": "Tart Montmorency Sour Cherries (Frozen Pitted)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 50,
    "protein_per_100g": 1,
    "carbs_per_100g": 12.2,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 1.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "freezer_monthly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-orc-025",
    "name": "Fuyu Persimmon (Firm Sweet Tomato-shaped)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 70,
    "protein_per_100g": 0.6,
    "carbs_per_100g": 18.6,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 3.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-trp-001",
    "name": "Banana (Medium Ripe Whole)",
    "category": "fruits",
    "sub_category": "tropical_fruits",
    "calories_per_100g": 89,
    "protein_per_100g": 1.1,
    "carbs_per_100g": 22.8,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 2.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 118,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-trp-002",
    "name": "Green-Tipped Unripe Banana (High Resistant Starch)",
    "category": "fruits",
    "sub_category": "tropical_fruits",
    "calories_per_100g": 85,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 22,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 3.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 118,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-trp-003",
    "name": "Baby Bananas / Nino (Sweet Miniature)",
    "category": "fruits",
    "sub_category": "tropical_fruits",
    "calories_per_100g": 90,
    "protein_per_100g": 1.1,
    "carbs_per_100g": 23,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 2.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-trp-004",
    "name": "Fresh Pineapple Chunks (Sweet Gold)",
    "category": "fruits",
    "sub_category": "tropical_fruits",
    "calories_per_100g": 50,
    "protein_per_100g": 0.5,
    "carbs_per_100g": 13.1,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 1.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 165,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-trp-005",
    "name": "Fresh Mango Slices (Ataulfo / Honey Mango)",
    "category": "fruits",
    "sub_category": "tropical_fruits",
    "calories_per_100g": 60,
    "protein_per_100g": 0.8,
    "carbs_per_100g": 15,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 1.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 165,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-trp-006",
    "name": "Tommy Atkins Red Mango (Fresh Cubes)",
    "category": "fruits",
    "sub_category": "tropical_fruits",
    "calories_per_100g": 60,
    "protein_per_100g": 0.8,
    "carbs_per_100g": 15,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 1.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 165,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-trp-007",
    "name": "Fresh Papaya (Hawaiian Red Flesh Chunks)",
    "category": "fruits",
    "sub_category": "tropical_fruits",
    "calories_per_100g": 43,
    "protein_per_100g": 0.5,
    "carbs_per_100g": 10.8,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 1.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-trp-008",
    "name": "Green Kiwi Fruit (Fuzzy Brown Skin Peeled)",
    "category": "fruits",
    "sub_category": "tropical_fruits",
    "calories_per_100g": 61,
    "protein_per_100g": 1.1,
    "carbs_per_100g": 14.7,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 75,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-trp-009",
    "name": "Golden SunGold Kiwi (Sweet Yellow Flesh)",
    "category": "fruits",
    "sub_category": "tropical_fruits",
    "calories_per_100g": 63,
    "protein_per_100g": 1.3,
    "carbs_per_100g": 15.8,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 1.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-trp-010",
    "name": "Passion Fruit (Fresh Purple Pulp & Seeds)",
    "category": "fruits",
    "sub_category": "tropical_fruits",
    "calories_per_100g": 97,
    "protein_per_100g": 2.2,
    "carbs_per_100g": 23.4,
    "fat_per_100g": 0.7,
    "fiber_per_100g": 10.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-trp-011",
    "name": "White Dragon Fruit / Pitaya (Fresh Cubed)",
    "category": "fruits",
    "sub_category": "tropical_fruits",
    "calories_per_100g": 60,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 13,
    "fat_per_100g": 0.6,
    "fiber_per_100g": 2.9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-trp-012",
    "name": "Red Flesh Pitaya / Dragon Fruit",
    "category": "fruits",
    "sub_category": "tropical_fruits",
    "calories_per_100g": 60,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 13,
    "fat_per_100g": 0.6,
    "fiber_per_100g": 2.9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-trp-013",
    "name": "Pink Guava (Fresh Tropical Slices)",
    "category": "fruits",
    "sub_category": "tropical_fruits",
    "calories_per_100g": 68,
    "protein_per_100g": 2.6,
    "carbs_per_100g": 14.3,
    "fat_per_100g": 1,
    "fiber_per_100g": 5.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-trp-014",
    "name": "Starfruit / Carambola (Sliced Five-Point Star)",
    "category": "fruits",
    "sub_category": "tropical_fruits",
    "calories_per_100g": 31,
    "protein_per_100g": 1,
    "carbs_per_100g": 6.7,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-trp-015",
    "name": "Fresh Lychees (Translucent Sweet Peeled)",
    "category": "fruits",
    "sub_category": "tropical_fruits",
    "calories_per_100g": 66,
    "protein_per_100g": 0.8,
    "carbs_per_100g": 16.5,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 1.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-mel-001",
    "name": "Seedless Red Watermelon (Fresh Crisp Cubes)",
    "category": "fruits",
    "sub_category": "melons",
    "calories_per_100g": 30,
    "protein_per_100g": 0.6,
    "carbs_per_100g": 7.6,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 0.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 280,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-mel-002",
    "name": "Yellow Flesh Watermelon (Sweet Sunshine)",
    "category": "fruits",
    "sub_category": "melons",
    "calories_per_100g": 30,
    "protein_per_100g": 0.6,
    "carbs_per_100g": 7.6,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 0.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 280,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-mel-003",
    "name": "Cantaloupe / Muskmelon (Orange Chunks)",
    "category": "fruits",
    "sub_category": "melons",
    "calories_per_100g": 34,
    "protein_per_100g": 0.8,
    "carbs_per_100g": 8.2,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-mel-004",
    "name": "Honeydew Melon (Pale Green Sweet Chunks)",
    "category": "fruits",
    "sub_category": "melons",
    "calories_per_100g": 36,
    "protein_per_100g": 0.5,
    "carbs_per_100g": 9.1,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 0.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-mel-005",
    "name": "Galia Melon (Aromatic Green Flesh)",
    "category": "fruits",
    "sub_category": "melons",
    "calories_per_100g": 35,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 8.5,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 0.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-mel-006",
    "name": "Canary Yellow Melon (Crisp White Flesh)",
    "category": "fruits",
    "sub_category": "melons",
    "calories_per_100g": 34,
    "protein_per_100g": 0.6,
    "carbs_per_100g": 8.5,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 0.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-cit-001",
    "name": "Navel Orange (Large Sweet Peeled)",
    "category": "fruits",
    "sub_category": "citrus_fruits",
    "calories_per_100g": 47,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 11.8,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 2.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-cit-002",
    "name": "Cara Cara Pink Navel Orange (Sweet Low Acid)",
    "category": "fruits",
    "sub_category": "citrus_fruits",
    "calories_per_100g": 48,
    "protein_per_100g": 1,
    "carbs_per_100g": 12,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-cit-003",
    "name": "Moro Blood Orange (Crimson Flesh)",
    "category": "fruits",
    "sub_category": "citrus_fruits",
    "calories_per_100g": 50,
    "protein_per_100g": 1,
    "carbs_per_100g": 12,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-cit-004",
    "name": "Clementines / Cuties (Peeled Easy-Peeler)",
    "category": "fruits",
    "sub_category": "citrus_fruits",
    "calories_per_100g": 47,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 12,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 74,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-cit-005",
    "name": "Ruby Red Grapefruit (Fresh Sectioned Half)",
    "category": "fruits",
    "sub_category": "citrus_fruits",
    "calories_per_100g": 42,
    "protein_per_100g": 0.8,
    "carbs_per_100g": 10.7,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 1.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-cit-006",
    "name": "Meyer Lemon (Fresh Squeezed Juice & Zest)",
    "category": "fruits",
    "sub_category": "citrus_fruits",
    "calories_per_100g": 29,
    "protein_per_100g": 1.1,
    "carbs_per_100g": 9.3,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-cit-007",
    "name": "Persian Green Lime (Juice & Wedges)",
    "category": "fruits",
    "sub_category": "citrus_fruits",
    "calories_per_100g": 30,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 10.5,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 40,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-cit-008",
    "name": "Key Limes (Floral Tart Citrus)",
    "category": "fruits",
    "sub_category": "citrus_fruits",
    "calories_per_100g": 30,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 10.5,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-cit-009",
    "name": "Fresh Kumquats (Whole Sweet Skin)",
    "category": "fruits",
    "sub_category": "citrus_fruits",
    "calories_per_100g": 71,
    "protein_per_100g": 1.9,
    "carbs_per_100g": 15.9,
    "fat_per_100g": 0.9,
    "fiber_per_100g": 6.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-cit-010",
    "name": "Minneola Tangelo / Honeybell (Honey Citrus)",
    "category": "fruits",
    "sub_category": "citrus_fruits",
    "calories_per_100g": 48,
    "protein_per_100g": 1,
    "carbs_per_100g": 12,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 2.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-grp-001",
    "name": "Red Seedless Grapes (Flame / Crimson)",
    "category": "fruits",
    "sub_category": "grapes_figs",
    "calories_per_100g": 69,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 18.1,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-grp-002",
    "name": "Green Seedless Grapes (Autumn Crisp)",
    "category": "fruits",
    "sub_category": "grapes_figs",
    "calories_per_100g": 69,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 18.1,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-grp-003",
    "name": "Black Seedless Grapes (Midnight Beauty)",
    "category": "fruits",
    "sub_category": "grapes_figs",
    "calories_per_100g": 70,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 18.3,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-grp-004",
    "name": "Cotton Candy Grapes (Sweet Specialty)",
    "category": "fruits",
    "sub_category": "grapes_figs",
    "calories_per_100g": 72,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 18.8,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-grp-005",
    "name": "Fresh Black Mission Figs (Ripe Sweet)",
    "category": "fruits",
    "sub_category": "grapes_figs",
    "calories_per_100g": 74,
    "protein_per_100g": 0.8,
    "carbs_per_100g": 19.2,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 2.9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-grp-006",
    "name": "Fresh Brown Turkey Figs",
    "category": "fruits",
    "sub_category": "grapes_figs",
    "calories_per_100g": 74,
    "protein_per_100g": 0.8,
    "carbs_per_100g": 19.2,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 2.9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-grp-007",
    "name": "Fresh Medjool Dates (Pitted Jumbo)",
    "category": "fruits",
    "sub_category": "grapes_figs",
    "calories_per_100g": 277,
    "protein_per_100g": 1.8,
    "carbs_per_100g": 75,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 6.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 48,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-grp-008",
    "name": "Deglet Noor Dates (Pitted Cooking Dates)",
    "category": "fruits",
    "sub_category": "grapes_figs",
    "calories_per_100g": 282,
    "protein_per_100g": 2.5,
    "carbs_per_100g": 75,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 40,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-grp-009",
    "name": "Dried Golden Thompson Raisins",
    "category": "fruits",
    "sub_category": "grapes_figs",
    "calories_per_100g": 299,
    "protein_per_100g": 3.1,
    "carbs_per_100g": 79.2,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 3.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 40,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-grp-010",
    "name": "Dried Black Corinthian Zante Currants",
    "category": "fruits",
    "sub_category": "grapes_figs",
    "calories_per_100g": 283,
    "protein_per_100g": 4.1,
    "carbs_per_100g": 74,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 6.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 40,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-grp-011",
    "name": "Dried Turkish Prunes (Pitted Dried Plums Sunsweet)",
    "category": "fruits",
    "sub_category": "grapes_figs",
    "calories_per_100g": 240,
    "protein_per_100g": 2.2,
    "carbs_per_100g": 63.9,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 7.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 40,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-grp-012",
    "name": "Dried Turkish Apricots (Unsulfured Organic)",
    "category": "fruits",
    "sub_category": "grapes_figs",
    "calories_per_100g": 241,
    "protein_per_100g": 3.4,
    "carbs_per_100g": 62.6,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 7.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 40,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-grp-013",
    "name": "Dried Wild Blueberries (Unsweetened)",
    "category": "fruits",
    "sub_category": "grapes_figs",
    "calories_per_100g": 310,
    "protein_per_100g": 2.5,
    "carbs_per_100g": 78,
    "fat_per_100g": 1,
    "fiber_per_100g": 8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-grp-014",
    "name": "Dried Cranberries / Craisins (50% Less Sugar)",
    "category": "fruits",
    "sub_category": "grapes_figs",
    "calories_per_100g": 308,
    "protein_per_100g": 0.2,
    "carbs_per_100g": 82,
    "fat_per_100g": 1.4,
    "fiber_per_100g": 5.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-grp-015",
    "name": "Fresh Pomegranate Arils (Ruby Red Tart-Sweet Seeds)",
    "category": "fruits",
    "sub_category": "grapes_figs",
    "calories_per_100g": 83,
    "protein_per_100g": 1.7,
    "carbs_per_100g": 18.7,
    "fat_per_100g": 1.2,
    "fiber_per_100g": 4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ext-001",
    "name": "Fresh Cloudberries (Arctic Golden Super Berry)",
    "category": "fruits",
    "sub_category": "berries",
    "calories_per_100g": 51,
    "protein_per_100g": 1.3,
    "carbs_per_100g": 8.6,
    "fat_per_100g": 0.8,
    "fiber_per_100g": 6.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ext-002",
    "name": "Fresh Wild Huckleberries (Mountain Sweet-Tart)",
    "category": "fruits",
    "sub_category": "berries",
    "calories_per_100g": 37,
    "protein_per_100g": 0.4,
    "carbs_per_100g": 8.7,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ext-003",
    "name": "Fresh Elderberries (Rich Anthocyanin Immune Berry)",
    "category": "fruits",
    "sub_category": "berries",
    "calories_per_100g": 73,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 18.4,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ext-004",
    "name": "Cape Gooseberries / Goldenberries (Incan Tart Berry)",
    "category": "fruits",
    "sub_category": "berries",
    "calories_per_100g": 53,
    "protein_per_100g": 1.9,
    "carbs_per_100g": 11.2,
    "fat_per_100g": 0.7,
    "fiber_per_100g": 4.9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ext-005",
    "name": "Honeygold Apple (Sweet Golden Honey Flavor)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 52,
    "protein_per_100g": 0.3,
    "carbs_per_100g": 13.7,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ext-006",
    "name": "Seckel Sugar Pear (Miniature Sweet Sugar Pear)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 60,
    "protein_per_100g": 0.4,
    "carbs_per_100g": 15.8,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 3.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ext-007",
    "name": "Forelle Pear (Tender Sweet Freckled Red Pear)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 57,
    "protein_per_100g": 0.4,
    "carbs_per_100g": 15,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ext-008",
    "name": "Mirabelle Golden Plums (French Sweet Preserves Plum)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 46,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 11.5,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ext-009",
    "name": "Donut / Saturn Peach (Flat Sweet White Peach)",
    "category": "fruits",
    "sub_category": "orchard_fruits",
    "calories_per_100g": 39,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 9.5,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ext-010",
    "name": "Yellow Passion Fruit / Maracuya (Tropical Citrus Pulp)",
    "category": "fruits",
    "sub_category": "tropical_fruits",
    "calories_per_100g": 97,
    "protein_per_100g": 2.2,
    "carbs_per_100g": 23.4,
    "fat_per_100g": 0.7,
    "fiber_per_100g": 10.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ext-011",
    "name": "Horned Melon / Kiwano (Jelly-like Green Seed Pulp)",
    "category": "fruits",
    "sub_category": "tropical_fruits",
    "calories_per_100g": 44,
    "protein_per_100g": 1.8,
    "carbs_per_100g": 7.6,
    "fat_per_100g": 1.3,
    "fiber_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  },
  {
    "id": "fb-ext-012",
    "name": "Purple Mangosteen (Queen of Tropical Fruits Sweet Segments)",
    "category": "fruits",
    "sub_category": "tropical_fruits",
    "calories_per_100g": 73,
    "protein_per_100g": 0.4,
    "carbs_per_100g": 17.9,
    "fat_per_100g": 0.6,
    "fiber_per_100g": 1.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "fruit_carb"
  }
];
