import { FoodItem } from '../types';

export const FRUITS_BERRIES_DATABASE: FoodItem[] = [
  // ==========================================
  // BERRIES & SUPER BERRIES (15+ items)
  // ==========================================
  {
    id: 'fb-ber-001',
    name: 'Fresh Blueberries',
    category: 'fruits',
    sub_category: 'berries',
    calories_per_100g: 57,
    protein_per_100g: 0.7,
    carbs_per_100g: 14.5,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 125,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-ber-002',
    name: 'Wild Frozen Blueberries (Antioxidant Rich)',
    category: 'fruits',
    sub_category: 'berries',
    calories_per_100g: 55,
    protein_per_100g: 0.8,
    carbs_per_100g: 14.0,
    fat_per_100g: 0.3,
    fiber_per_100g: 3.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 125,
    default_unit: 'g',
    storage_type: 'freezer_monthly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-ber-003',
    name: 'Fresh Strawberries (Sliced)',
    category: 'fruits',
    sub_category: 'berries',
    calories_per_100g: 32,
    protein_per_100g: 0.7,
    carbs_per_100g: 7.7,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-ber-004',
    name: 'Fresh Raspberries',
    category: 'fruits',
    sub_category: 'berries',
    calories_per_100g: 52,
    protein_per_100g: 1.2,
    carbs_per_100g: 11.9,
    fat_per_100g: 0.7,
    fiber_per_100g: 6.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 125,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-ber-005',
    name: 'Fresh Blackberries',
    category: 'fruits',
    sub_category: 'berries',
    calories_per_100g: 43,
    protein_per_100g: 1.4,
    carbs_per_100g: 9.6,
    fat_per_100g: 0.5,
    fiber_per_100g: 5.3,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 125,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },

  // ==========================================
  // APPLES, PEARS & STONE FRUITS (15+ items)
  // ==========================================
  {
    id: 'fb-orc-001',
    name: 'Honeycrisp Apple (Large with Skin)',
    category: 'fruits',
    sub_category: 'orchard_fruits',
    calories_per_100g: 52,
    protein_per_100g: 0.3,
    carbs_per_100g: 13.8,
    fat_per_100g: 0.2,
    fiber_per_100g: 2.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 180,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-orc-002',
    name: 'Granny Smith Green Apple (Tart)',
    category: 'fruits',
    sub_category: 'orchard_fruits',
    calories_per_100g: 50,
    protein_per_100g: 0.3,
    carbs_per_100g: 13.6,
    fat_per_100g: 0.1,
    fiber_per_100g: 2.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 180,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-orc-003',
    name: 'Sweet Dark Cherries (Pitted)',
    category: 'fruits',
    sub_category: 'orchard_fruits',
    calories_per_100g: 63,
    protein_per_100g: 1.1,
    carbs_per_100g: 16.0,
    fat_per_100g: 0.2,
    fiber_per_100g: 2.1,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 140,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-orc-004',
    name: 'Fresh Yellow Peach (Sliced)',
    category: 'fruits',
    sub_category: 'orchard_fruits',
    calories_per_100g: 39,
    protein_per_100g: 0.9,
    carbs_per_100g: 9.5,
    fat_per_100g: 0.3,
    fiber_per_100g: 1.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-orc-005',
    name: 'Bartlett Pear (Medium)',
    category: 'fruits',
    sub_category: 'orchard_fruits',
    calories_per_100g: 57,
    protein_per_100g: 0.4,
    carbs_per_100g: 15.2,
    fat_per_100g: 0.1,
    fiber_per_100g: 3.1,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 170,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },

  // ==========================================
  // TROPICAL FRUITS & BANANAS (15+ items)
  // ==========================================
  {
    id: 'fb-trp-001',
    name: 'Fresh Cavendish Banana (Medium)',
    category: 'fruits',
    sub_category: 'tropical_fruits',
    calories_per_100g: 89,
    protein_per_100g: 1.1,
    carbs_per_100g: 22.8,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.6,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-trp-002',
    name: 'Fresh Pineapple Chunks',
    category: 'fruits',
    sub_category: 'tropical_fruits',
    calories_per_100g: 50,
    protein_per_100g: 0.5,
    carbs_per_100g: 13.1,
    fat_per_100g: 0.1,
    fiber_per_100g: 1.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-trp-003',
    name: 'Fresh Mango Cubes (Tommy Atkins / Champagne)',
    category: 'fruits',
    sub_category: 'tropical_fruits',
    calories_per_100g: 60,
    protein_per_100g: 0.8,
    carbs_per_100g: 15.0,
    fat_per_100g: 0.4,
    fiber_per_100g: 1.6,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-trp-004',
    name: 'Green / Golden Kiwi Fruit (Sliced)',
    category: 'fruits',
    sub_category: 'tropical_fruits',
    calories_per_100g: 61,
    protein_per_100g: 1.1,
    carbs_per_100g: 14.7,
    fat_per_100g: 0.5,
    fiber_per_100g: 3.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-trp-005',
    name: 'Fresh Papaya (Cubed)',
    category: 'fruits',
    sub_category: 'tropical_fruits',
    calories_per_100g: 43,
    protein_per_100g: 0.5,
    carbs_per_100g: 10.8,
    fat_per_100g: 0.3,
    fiber_per_100g: 1.7,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },

  // ==========================================
  // MELONS & CITRUS (15+ items)
  // ==========================================
  {
    id: 'fb-mel-001',
    name: 'Fresh Watermelon Slices (High Hydration)',
    category: 'fruits',
    sub_category: 'melons',
    calories_per_100g: 30,
    protein_per_100g: 0.6,
    carbs_per_100g: 7.6,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 200,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-mel-002',
    name: 'Fresh Cantaloupe / Rockmelon (Cubed)',
    category: 'fruits',
    sub_category: 'melons',
    calories_per_100g: 34,
    protein_per_100g: 0.8,
    carbs_per_100g: 8.2,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.9,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 180,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-cit-001',
    name: 'Navel Orange (Peeled)',
    category: 'fruits',
    sub_category: 'citrus_fruits',
    calories_per_100g: 47,
    protein_per_100g: 0.9,
    carbs_per_100g: 11.8,
    fat_per_100g: 0.1,
    fiber_per_100g: 2.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-cit-002',
    name: 'Ruby Red Grapefruit (Half)',
    category: 'fruits',
    sub_category: 'citrus_fruits',
    calories_per_100g: 42,
    protein_per_100g: 0.8,
    carbs_per_100g: 10.7,
    fat_per_100g: 0.1,
    fiber_per_100g: 1.6,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },

  // ==========================================
  // GRAPES & FIGS (10+ items)
  // ==========================================
  {
    id: 'fb-grp-001',
    name: 'Red Seedless Grapes',
    category: 'fruits',
    sub_category: 'grapes_figs',
    calories_per_100g: 69,
    protein_per_100g: 0.7,
    carbs_per_100g: 18.1,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.9,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-grp-002',
    name: 'Fresh Black Mission Figs',
    category: 'fruits',
    sub_category: 'grapes_figs',
    calories_per_100g: 74,
    protein_per_100g: 0.8,
    carbs_per_100g: 19.2,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.9,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'fb-grp-003',
    name: 'Medjool Dates (Pitted)',
    category: 'fruits',
    sub_category: 'grapes_figs',
    calories_per_100g: 277,
    protein_per_100g: 1.8,
    carbs_per_100g: 75.0,
    fat_per_100g: 0.2,
    fiber_per_100g: 6.7,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 48,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'fruit_carb',
  },
];
