import { FoodItem } from '../types';

export const GRAINS_CARBS_DATABASE: FoodItem[] = [
  {
    "id": "gc-oat-001",
    "name": "Rolled Old-Fashioned Oats (Whole Grain, Dry Quaker style)",
    "category": "grains_carbs",
    "sub_category": "oats_cereals",
    "calories_per_100g": 379,
    "protein_per_100g": 13.2,
    "carbs_per_100g": 67.7,
    "fat_per_100g": 6.5,
    "fiber_per_100g": 10.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 45,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-oat-002",
    "name": "Rolled Oats (Cooked Oatmeal in Water)",
    "category": "grains_carbs",
    "sub_category": "oats_cereals",
    "calories_per_100g": 71,
    "protein_per_100g": 2.5,
    "carbs_per_100g": 12,
    "fat_per_100g": 1.4,
    "fiber_per_100g": 1.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 230,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-oat-003",
    "name": "Steel-Cut Oats (Irish Whole Groats, Dry McCann's)",
    "category": "grains_carbs",
    "sub_category": "oats_cereals",
    "calories_per_100g": 375,
    "protein_per_100g": 12.5,
    "carbs_per_100g": 68,
    "fat_per_100g": 6,
    "fiber_per_100g": 10,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 45,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-oat-004",
    "name": "Steel-Cut Oats (Cooked Porridge in Water)",
    "category": "grains_carbs",
    "sub_category": "oats_cereals",
    "calories_per_100g": 75,
    "protein_per_100g": 2.8,
    "carbs_per_100g": 13.5,
    "fat_per_100g": 1.3,
    "fiber_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 230,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-oat-005",
    "name": "Quick 1-Minute Oats (Dry Flakes)",
    "category": "grains_carbs",
    "sub_category": "oats_cereals",
    "calories_per_100g": 370,
    "protein_per_100g": 13,
    "carbs_per_100g": 68,
    "fat_per_100g": 6,
    "fiber_per_100g": 9.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 40,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-oat-006",
    "name": "Raw Oat Bran (High Soluble Beta-Glucan Fiber)",
    "category": "grains_carbs",
    "sub_category": "oats_cereals",
    "calories_per_100g": 246,
    "protein_per_100g": 17.3,
    "carbs_per_100g": 66.2,
    "fat_per_100g": 7,
    "fiber_per_100g": 15.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-oat-007",
    "name": "Scottish Oatmeal (Stone-Ground Groats)",
    "category": "grains_carbs",
    "sub_category": "oats_cereals",
    "calories_per_100g": 375,
    "protein_per_100g": 13,
    "carbs_per_100g": 68,
    "fat_per_100g": 6,
    "fiber_per_100g": 10,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 45,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-oat-008",
    "name": "Cream of Rice (Ground White Rice Hot Cereal, Dry)",
    "category": "grains_carbs",
    "sub_category": "oats_cereals",
    "calories_per_100g": 360,
    "protein_per_100g": 7,
    "carbs_per_100g": 80,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 45,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "starchy_carb"
  },
  {
    "id": "gc-oat-009",
    "name": "Cream of Rice (Cooked in Water)",
    "category": "grains_carbs",
    "sub_category": "oats_cereals",
    "calories_per_100g": 60,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 13.5,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 0.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 240,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "starchy_carb"
  },
  {
    "id": "gc-oat-010",
    "name": "Cream of Wheat / Farina (Dry Enriched)",
    "category": "grains_carbs",
    "sub_category": "oats_cereals",
    "calories_per_100g": 367,
    "protein_per_100g": 10.8,
    "carbs_per_100g": 77.5,
    "fat_per_100g": 0.8,
    "fiber_per_100g": 3.3,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 35,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-oat-011",
    "name": "Toasted Wheat Germ Flakes (Bob's Red Mill)",
    "category": "grains_carbs",
    "sub_category": "oats_cereals",
    "calories_per_100g": 360,
    "protein_per_100g": 23,
    "carbs_per_100g": 51.8,
    "fat_per_100g": 9.7,
    "fiber_per_100g": 13.2,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-oat-012",
    "name": "Shredded Wheat Cereal (100% Whole Wheat Biscuits)",
    "category": "grains_carbs",
    "sub_category": "oats_cereals",
    "calories_per_100g": 350,
    "protein_per_100g": 11.5,
    "carbs_per_100g": 80,
    "fat_per_100g": 2,
    "fiber_per_100g": 12,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-oat-013",
    "name": "Whole Grain Cheerios Cereal (Toasted Whole Oat Os)",
    "category": "grains_carbs",
    "sub_category": "oats_cereals",
    "calories_per_100g": 370,
    "protein_per_100g": 12,
    "carbs_per_100g": 73.5,
    "fat_per_100g": 6,
    "fiber_per_100g": 10.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 39,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ric-001",
    "name": "Jasmine White Rice (Cooked Steamed)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 130,
    "protein_per_100g": 2.7,
    "carbs_per_100g": 28.2,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 0.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "starchy_carb"
  },
  {
    "id": "gc-ric-002",
    "name": "Basmati White Rice (Royal Indian Long-Grain Cooked)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 121,
    "protein_per_100g": 3,
    "carbs_per_100g": 25.2,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 0.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "starchy_carb"
  },
  {
    "id": "gc-ric-003",
    "name": "Long-Grain Brown Rice (Cooked Whole Grain)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 112,
    "protein_per_100g": 2.6,
    "carbs_per_100g": 23.5,
    "fat_per_100g": 0.9,
    "fiber_per_100g": 1.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ric-004",
    "name": "Brown Basmati Rice (Cooked Aromatic Whole Grain)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 115,
    "protein_per_100g": 2.8,
    "carbs_per_100g": 24,
    "fat_per_100g": 0.8,
    "fiber_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ric-005",
    "name": "Wild Rice (Pure Cultivated Aquatic Grass, Cooked)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 101,
    "protein_per_100g": 4,
    "carbs_per_100g": 21.3,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 1.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ric-006",
    "name": "Forbidden Black Rice (Heirloom Antioxidant Cooked)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 120,
    "protein_per_100g": 3.5,
    "carbs_per_100g": 25,
    "fat_per_100g": 1,
    "fiber_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ric-007",
    "name": "Red Cargo Rice (Cooked Thai Whole Grain)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 118,
    "protein_per_100g": 3,
    "carbs_per_100g": 24.5,
    "fat_per_100g": 1,
    "fiber_per_100g": 2.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ric-008",
    "name": "Sushi Short-Grain White Rice (Cooked Seasoned)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 130,
    "protein_per_100g": 2.5,
    "carbs_per_100g": 28.5,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 0.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "starchy_carb"
  },
  {
    "id": "gc-ric-009",
    "name": "Italian Arborio Risotto Rice (Cooked Creamy)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 130,
    "protein_per_100g": 2.4,
    "carbs_per_100g": 28,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 0.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "starchy_carb"
  },
  {
    "id": "gc-ric-010",
    "name": "Organic White Quinoa (Cooked Fluffy)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 120,
    "protein_per_100g": 4.4,
    "carbs_per_100g": 21.3,
    "fat_per_100g": 1.9,
    "fiber_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ric-011",
    "name": "Red & Tri-Color Quinoa Blend (Cooked)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 122,
    "protein_per_100g": 4.5,
    "carbs_per_100g": 21,
    "fat_per_100g": 2,
    "fiber_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ric-012",
    "name": "Pearled Farro (Italian Emmer Wheat, Cooked)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 135,
    "protein_per_100g": 5.5,
    "carbs_per_100g": 28,
    "fat_per_100g": 0.8,
    "fiber_per_100g": 3.5,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ric-013",
    "name": "Whole Spelt Grain (Cooked Ancient Wheat)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 127,
    "protein_per_100g": 5.5,
    "carbs_per_100g": 26,
    "fat_per_100g": 0.9,
    "fiber_per_100g": 3.9,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ric-014",
    "name": "Buckwheat Groats / Kasha (Roasted Cooked)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 92,
    "protein_per_100g": 3.4,
    "carbs_per_100g": 19.9,
    "fat_per_100g": 0.6,
    "fiber_per_100g": 2.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ric-015",
    "name": "Pearled Barley (Cooked Tender)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 123,
    "protein_per_100g": 2.3,
    "carbs_per_100g": 28.2,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 3.8,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ric-016",
    "name": "Hulled Barley (Whole Grain High Beta-Glucan, Cooked)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 115,
    "protein_per_100g": 2.8,
    "carbs_per_100g": 25,
    "fat_per_100g": 0.6,
    "fiber_per_100g": 5,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ric-017",
    "name": "Whole Grain Bulgur Wheat (Cooked Tabbouleh Grain)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 83,
    "protein_per_100g": 3.1,
    "carbs_per_100g": 18.6,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 4.5,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ric-018",
    "name": "Whole Wheat Couscous (Steamed)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 112,
    "protein_per_100g": 3.8,
    "carbs_per_100g": 23.2,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.2,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ric-019",
    "name": "Israeli Pearl Couscous (Cooked Al Dente)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 130,
    "protein_per_100g": 4.5,
    "carbs_per_100g": 26.5,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 1.5,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "starchy_carb"
  },
  {
    "id": "gc-ric-020",
    "name": "Yellow Corn Polenta / Grits (Cooked in Water)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 70,
    "protein_per_100g": 1.5,
    "carbs_per_100g": 15,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 1.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ric-021",
    "name": "Millet Grain (Cooked Ancient Seed)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 119,
    "protein_per_100g": 3.5,
    "carbs_per_100g": 23.7,
    "fat_per_100g": 1,
    "fiber_per_100g": 1.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ric-022",
    "name": "Whole Grain Sorghum (Cooked Gluten-Free Grain)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 130,
    "protein_per_100g": 4,
    "carbs_per_100g": 28,
    "fat_per_100g": 1.2,
    "fiber_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ric-023",
    "name": "Cracked Green Freekeh (Roasted Green Wheat Cooked)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 125,
    "protein_per_100g": 5,
    "carbs_per_100g": 24,
    "fat_per_100g": 0.8,
    "fiber_per_100g": 4.5,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-pot-001",
    "name": "Sweet Potato (Baked with Skin Whole)",
    "category": "grains_carbs",
    "sub_category": "potatoes_yams",
    "calories_per_100g": 90,
    "protein_per_100g": 2,
    "carbs_per_100g": 20.7,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 3.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "sweet_potato_carb"
  },
  {
    "id": "gc-pot-002",
    "name": "Japanese Sweet Potato / Murasaki (Purple Skin White Flesh Baked)",
    "category": "grains_carbs",
    "sub_category": "potatoes_yams",
    "calories_per_100g": 118,
    "protein_per_100g": 1.9,
    "carbs_per_100g": 28,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 3.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "sweet_potato_carb"
  },
  {
    "id": "gc-pot-003",
    "name": "Stokes Purple Sweet Potato (Deep Purple Baked)",
    "category": "grains_carbs",
    "sub_category": "potatoes_yams",
    "calories_per_100g": 110,
    "protein_per_100g": 2,
    "carbs_per_100g": 25.5,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 3.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "sweet_potato_carb"
  },
  {
    "id": "gc-pot-004",
    "name": "Russet Idaho Potato (Baked with Crispy Skin)",
    "category": "grains_carbs",
    "sub_category": "potatoes_yams",
    "calories_per_100g": 93,
    "protein_per_100g": 2.5,
    "carbs_per_100g": 21.2,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 2.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 200,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "potato_carb"
  },
  {
    "id": "gc-pot-005",
    "name": "Yukon Gold Potatoes (Boiled / Steamed Yellow Flesh)",
    "category": "grains_carbs",
    "sub_category": "potatoes_yams",
    "calories_per_100g": 87,
    "protein_per_100g": 2,
    "carbs_per_100g": 20,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 1.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "potato_carb"
  },
  {
    "id": "gc-pot-006",
    "name": "Red Baby Bliss Potatoes (Roasted Quartered)",
    "category": "grains_carbs",
    "sub_category": "potatoes_yams",
    "calories_per_100g": 89,
    "protein_per_100g": 2.2,
    "carbs_per_100g": 20.2,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "potato_carb"
  },
  {
    "id": "gc-pot-007",
    "name": "Fingerling Potatoes (French Baby Herb Roasted)",
    "category": "grains_carbs",
    "sub_category": "potatoes_yams",
    "calories_per_100g": 90,
    "protein_per_100g": 2.1,
    "carbs_per_100g": 20.5,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "potato_carb"
  },
  {
    "id": "gc-pot-008",
    "name": "Mashed Russet Potatoes (with Light Milk & Salt)",
    "category": "grains_carbs",
    "sub_category": "potatoes_yams",
    "calories_per_100g": 88,
    "protein_per_100g": 2,
    "carbs_per_100g": 17.5,
    "fat_per_100g": 1.2,
    "fiber_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 200,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "potato_carb"
  },
  {
    "id": "gc-pot-009",
    "name": "Butternut Squash (Baked Cubes)",
    "category": "grains_carbs",
    "sub_category": "potatoes_yams",
    "calories_per_100g": 45,
    "protein_per_100g": 1,
    "carbs_per_100g": 11.7,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 200,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "sweet_potato_carb"
  },
  {
    "id": "gc-pot-010",
    "name": "Kabocha Squash (Japanese Sweet Pumpkin Steamed)",
    "category": "grains_carbs",
    "sub_category": "potatoes_yams",
    "calories_per_100g": 35,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 8.5,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 200,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "sweet_potato_carb"
  },
  {
    "id": "gc-pot-011",
    "name": "Acorn Squash (Roasted Half with Sea Salt)",
    "category": "grains_carbs",
    "sub_category": "potatoes_yams",
    "calories_per_100g": 40,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 10.4,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 200,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "sweet_potato_carb"
  },
  {
    "id": "gc-pot-012",
    "name": "Delicata Squash (Roasted Sweet Rings with Edible Skin)",
    "category": "grains_carbs",
    "sub_category": "potatoes_yams",
    "calories_per_100g": 34,
    "protein_per_100g": 0.8,
    "carbs_per_100g": 8.8,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 1.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "sweet_potato_carb"
  },
  {
    "id": "gc-pot-013",
    "name": "Spaghetti Squash (Baked Fork-Pulled Strands)",
    "category": "grains_carbs",
    "sub_category": "potatoes_yams",
    "calories_per_100g": 31,
    "protein_per_100g": 0.6,
    "carbs_per_100g": 7,
    "fat_per_100g": 0.6,
    "fiber_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "gc-pot-014",
    "name": "Yellow Sweet Corn on the Cob (Steamed Fresh)",
    "category": "grains_carbs",
    "sub_category": "potatoes_yams",
    "calories_per_100g": 96,
    "protein_per_100g": 3.4,
    "carbs_per_100g": 21,
    "fat_per_100g": 1.5,
    "fiber_per_100g": 2.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-brd-001",
    "name": "100% Sprouted Whole Grain Bread (Food for Life Ezekiel 4:9)",
    "category": "grains_carbs",
    "sub_category": "breads_toast",
    "calories_per_100g": 235,
    "protein_per_100g": 14.7,
    "carbs_per_100g": 44.1,
    "fat_per_100g": 1.5,
    "fiber_per_100g": 8.8,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 34,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "bread_carb"
  },
  {
    "id": "gc-brd-002",
    "name": "Artisan Sourdough Bread (Naturally Fermented 3-Ingredient)",
    "category": "grains_carbs",
    "sub_category": "breads_toast",
    "calories_per_100g": 250,
    "protein_per_100g": 9.5,
    "carbs_per_100g": 49,
    "fat_per_100g": 1.2,
    "fiber_per_100g": 2.4,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "bread_carb"
  },
  {
    "id": "gc-brd-003",
    "name": "100% Whole Wheat Sandwich Bread (Dave's Killer Bread style)",
    "category": "grains_carbs",
    "sub_category": "breads_toast",
    "calories_per_100g": 247,
    "protein_per_100g": 12,
    "carbs_per_100g": 43,
    "fat_per_100g": 3.5,
    "fiber_per_100g": 6.8,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 40,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "bread_carb"
  },
  {
    "id": "gc-brd-004",
    "name": "Traditional German Dark Rye Bread (Pumpernickel / Roggenbrot)",
    "category": "grains_carbs",
    "sub_category": "breads_toast",
    "calories_per_100g": 220,
    "protein_per_100g": 7,
    "carbs_per_100g": 45,
    "fat_per_100g": 1.5,
    "fiber_per_100g": 7.5,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "bread_carb"
  },
  {
    "id": "gc-brd-005",
    "name": "Whole Wheat Bagel Thins (110 Cal Thomas style)",
    "category": "grains_carbs",
    "sub_category": "breads_toast",
    "calories_per_100g": 239,
    "protein_per_100g": 10.9,
    "carbs_per_100g": 47.8,
    "fat_per_100g": 1.1,
    "fiber_per_100g": 8.7,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 46,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "bread_carb"
  },
  {
    "id": "gc-brd-006",
    "name": "100% Whole Wheat English Muffin (Toasted)",
    "category": "grains_carbs",
    "sub_category": "breads_toast",
    "calories_per_100g": 215,
    "protein_per_100g": 9,
    "carbs_per_100g": 44,
    "fat_per_100g": 1.5,
    "fiber_per_100g": 6,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 57,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "bread_carb"
  },
  {
    "id": "gc-brd-007",
    "name": "Gluten-Free 7-Grain Bread (Canyon Bakehouse Heritage style)",
    "category": "grains_carbs",
    "sub_category": "breads_toast",
    "calories_per_100g": 243,
    "protein_per_100g": 4.8,
    "carbs_per_100g": 45.2,
    "fat_per_100g": 4.8,
    "fiber_per_100g": 4.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 42,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "bread_carb"
  },
  {
    "id": "gc-brd-008",
    "name": "Seeded Multigrain Sourdough Bread",
    "category": "grains_carbs",
    "sub_category": "breads_toast",
    "calories_per_100g": 260,
    "protein_per_100g": 10.5,
    "carbs_per_100g": 46,
    "fat_per_100g": 4,
    "fiber_per_100g": 5.5,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "bread_carb"
  },
  {
    "id": "gc-brd-009",
    "name": "French Baguette (Crispy Crust Slices)",
    "category": "grains_carbs",
    "sub_category": "breads_toast",
    "calories_per_100g": 270,
    "protein_per_100g": 9,
    "carbs_per_100g": 56,
    "fat_per_100g": 1,
    "fiber_per_100g": 2.5,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "bread_carb"
  },
  {
    "id": "gc-brd-010",
    "name": "Italian Ciabatta Bread (Olive Oil Infused)",
    "category": "grains_carbs",
    "sub_category": "breads_toast",
    "calories_per_100g": 265,
    "protein_per_100g": 8.8,
    "carbs_per_100g": 52,
    "fat_per_100g": 2.5,
    "fiber_per_100g": 2.2,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "bread_carb"
  },
  {
    "id": "gc-pas-001",
    "name": "100% Whole Wheat Spaghetti (Cooked Al Dente)",
    "category": "grains_carbs",
    "sub_category": "pastas_noodles",
    "calories_per_100g": 124,
    "protein_per_100g": 5.3,
    "carbs_per_100g": 26.5,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 3.9,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-pas-002",
    "name": "100% Whole Wheat Penne Rigate (Cooked Barilla)",
    "category": "grains_carbs",
    "sub_category": "pastas_noodles",
    "calories_per_100g": 124,
    "protein_per_100g": 5.3,
    "carbs_per_100g": 26.5,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 3.9,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-pas-003",
    "name": "Chickpea Penne Pasta (Banza High Protein / Fiber, Cooked)",
    "category": "grains_carbs",
    "sub_category": "pastas_noodles",
    "calories_per_100g": 160,
    "protein_per_100g": 9.5,
    "carbs_per_100g": 24.5,
    "fat_per_100g": 2.5,
    "fiber_per_100g": 6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-pas-004",
    "name": "Red Lentil Rotini Pasta (Barilla Legume, Cooked)",
    "category": "grains_carbs",
    "sub_category": "pastas_noodles",
    "calories_per_100g": 155,
    "protein_per_100g": 11,
    "carbs_per_100g": 25,
    "fat_per_100g": 1,
    "fiber_per_100g": 4.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-pas-005",
    "name": "100% Pure Buckwheat Soba Noodles (Japanese, Cooked)",
    "category": "grains_carbs",
    "sub_category": "pastas_noodles",
    "calories_per_100g": 99,
    "protein_per_100g": 5.1,
    "carbs_per_100g": 21.4,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-pas-006",
    "name": "Brown Rice & Quinoa Fusilli (Cooked Gluten-Free)",
    "category": "grains_carbs",
    "sub_category": "pastas_noodles",
    "calories_per_100g": 135,
    "protein_per_100g": 3.5,
    "carbs_per_100g": 28.5,
    "fat_per_100g": 1,
    "fiber_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-pas-007",
    "name": "Traditional Italian Semolina Fettuccine (Cooked)",
    "category": "grains_carbs",
    "sub_category": "pastas_noodles",
    "calories_per_100g": 158,
    "protein_per_100g": 5.8,
    "carbs_per_100g": 30.5,
    "fat_per_100g": 0.9,
    "fiber_per_100g": 1.8,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-pas-008",
    "name": "Shirataki Konjac Miracle Noodles (Zero Net Carb)",
    "category": "grains_carbs",
    "sub_category": "pastas_noodles",
    "calories_per_100g": 9,
    "protein_per_100g": 0.2,
    "carbs_per_100g": 3,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 200,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "gc-pas-009",
    "name": "Vietnamese Brown Rice Vermicelli Noodles (Cooked)",
    "category": "grains_carbs",
    "sub_category": "pastas_noodles",
    "calories_per_100g": 110,
    "protein_per_100g": 2.5,
    "carbs_per_100g": 24,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-pas-010",
    "name": "Japanese Fresh Udon Noodles (Cooked)",
    "category": "grains_carbs",
    "sub_category": "pastas_noodles",
    "calories_per_100g": 130,
    "protein_per_100g": 3.5,
    "carbs_per_100g": 27,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 1,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-tor-001",
    "name": "Yellow Corn Tortillas (Traditional 6-inch)",
    "category": "grains_carbs",
    "sub_category": "tortillas_wraps",
    "calories_per_100g": 218,
    "protein_per_100g": 5.7,
    "carbs_per_100g": 44.6,
    "fat_per_100g": 2.8,
    "fiber_per_100g": 6.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "bread_carb"
  },
  {
    "id": "gc-tor-002",
    "name": "Low-Carb High-Fiber Tortilla Wrap (Mission Carb Balance style)",
    "category": "grains_carbs",
    "sub_category": "tortillas_wraps",
    "calories_per_100g": 167,
    "protein_per_100g": 11.9,
    "carbs_per_100g": 45.2,
    "fat_per_100g": 4.8,
    "fiber_per_100g": 35.7,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 42,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "bread_carb"
  },
  {
    "id": "gc-tor-003",
    "name": "100% Whole Wheat Soft Taco Tortillas",
    "category": "grains_carbs",
    "sub_category": "tortillas_wraps",
    "calories_per_100g": 275,
    "protein_per_100g": 9.5,
    "carbs_per_100g": 47.5,
    "fat_per_100g": 6,
    "fiber_per_100g": 5,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 40,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "bread_carb"
  },
  {
    "id": "gc-tor-004",
    "name": "100% Whole Wheat Greek Pita Pocket Bread",
    "category": "grains_carbs",
    "sub_category": "tortillas_wraps",
    "calories_per_100g": 255,
    "protein_per_100g": 10.5,
    "carbs_per_100g": 49,
    "fat_per_100g": 2,
    "fiber_per_100g": 7,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 60,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "bread_carb"
  },
  {
    "id": "gc-tor-005",
    "name": "Cassava Flour Grain-Free Tortillas (Siete style)",
    "category": "grains_carbs",
    "sub_category": "tortillas_wraps",
    "calories_per_100g": 260,
    "protein_per_100g": 2,
    "carbs_per_100g": 48,
    "fat_per_100g": 7,
    "fiber_per_100g": 4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "bread_carb"
  },
  {
    "id": "gc-tor-006",
    "name": "Almond Flour Grain-Free Tortillas (Siete)",
    "category": "grains_carbs",
    "sub_category": "tortillas_wraps",
    "calories_per_100g": 290,
    "protein_per_100g": 6,
    "carbs_per_100g": 20,
    "fat_per_100g": 20,
    "fiber_per_100g": 6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "bread_carb"
  },
  {
    "id": "gc-tor-007",
    "name": "Lavash Flatbread (Whole Grain Joseph's style)",
    "category": "grains_carbs",
    "sub_category": "tortillas_wraps",
    "calories_per_100g": 185,
    "protein_per_100g": 15,
    "carbs_per_100g": 31,
    "fat_per_100g": 3.5,
    "fiber_per_100g": 12,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 64,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "bread_carb"
  },
  {
    "id": "gc-ext-001",
    "name": "Kamut Khorasan Whole Grain (Ancient Egyptian Wheat Cooked)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 135,
    "protein_per_100g": 6,
    "carbs_per_100g": 27,
    "fat_per_100g": 0.9,
    "fiber_per_100g": 4,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ext-002",
    "name": "Whole Emmer Wheat Grain (Cooked Farro Medio)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 130,
    "protein_per_100g": 5,
    "carbs_per_100g": 26.5,
    "fat_per_100g": 0.8,
    "fiber_per_100g": 3.8,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ext-003",
    "name": "Teff Grain (Ethiopian Whole Ancient Grain Cooked)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 101,
    "protein_per_100g": 3.9,
    "carbs_per_100g": 20,
    "fat_per_100g": 0.7,
    "fiber_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ext-004",
    "name": "Amaranth Grain (Cooked Whole Grain Ancient Seed)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 102,
    "protein_per_100g": 3.8,
    "carbs_per_100g": 19,
    "fat_per_100g": 1.6,
    "fiber_per_100g": 2.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ext-005",
    "name": "Heirloom Red Corn Grits / Polenta (Bob's Red Mill)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 72,
    "protein_per_100g": 1.6,
    "carbs_per_100g": 15.5,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 1.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ext-006",
    "name": "Blue Cornmeal Masa (Whole Blue Corn Cooked)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 85,
    "protein_per_100g": 2,
    "carbs_per_100g": 18,
    "fat_per_100g": 0.8,
    "fiber_per_100g": 2.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ext-007",
    "name": "Calrose Medium Grain White Rice (Cooked Steamed)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 130,
    "protein_per_100g": 2.6,
    "carbs_per_100g": 28.5,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 0.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "starchy_carb"
  },
  {
    "id": "gc-ext-008",
    "name": "Kokuho Rose Heirloom Medium Grain Rice (Cooked)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 130,
    "protein_per_100g": 2.7,
    "carbs_per_100g": 28,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 0.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "starchy_carb"
  },
  {
    "id": "gc-ext-009",
    "name": "Jasmine Brown Rice (Cooked Whole Grain Aromatic)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 115,
    "protein_per_100g": 2.7,
    "carbs_per_100g": 24,
    "fat_per_100g": 0.9,
    "fiber_per_100g": 1.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ext-010",
    "name": "Carnaroli Italian Risotto Rice (The King of Rices Cooked)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 132,
    "protein_per_100g": 2.5,
    "carbs_per_100g": 28.5,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 0.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "starchy_carb"
  },
  {
    "id": "gc-ext-011",
    "name": "Germinated GABA Brown Rice (High Antioxidant Cooked)",
    "category": "grains_carbs",
    "sub_category": "rice_grains",
    "calories_per_100g": 118,
    "protein_per_100g": 3,
    "carbs_per_100g": 24.5,
    "fat_per_100g": 1,
    "fiber_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "complex_carb"
  },
  {
    "id": "gc-ext-012",
    "name": "Garnet Sweet Potato (Baked Orange Flesh)",
    "category": "grains_carbs",
    "sub_category": "potatoes_yams",
    "calories_per_100g": 90,
    "protein_per_100g": 2,
    "carbs_per_100g": 20.7,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 3.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "sweet_potato_carb"
  },
  {
    "id": "gc-ext-013",
    "name": "White Sweet Potato / O'Henry (Creamy Sweet Flesh Baked)",
    "category": "grains_carbs",
    "sub_category": "potatoes_yams",
    "calories_per_100g": 86,
    "protein_per_100g": 1.8,
    "carbs_per_100g": 20,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "sweet_potato_carb"
  },
  {
    "id": "gc-ext-014",
    "name": "Pattypan Squash / Flying Saucer (Steamed Whole Baby)",
    "category": "grains_carbs",
    "sub_category": "potatoes_yams",
    "calories_per_100g": 18,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 3.8,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "gc-ext-015",
    "name": "Roasted Potato Wedges (Air-Roasted Russet with Olive Oil & Sea Salt)",
    "category": "grains_carbs",
    "sub_category": "potatoes_yams",
    "calories_per_100g": 125,
    "protein_per_100g": 2.5,
    "carbs_per_100g": 22,
    "fat_per_100g": 3.2,
    "fiber_per_100g": 2.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "potato_carb"
  },
  {
    "id": "gc-ext-016",
    "name": "100% Sprouted Cinnamon Raisin Ezekiel Bread",
    "category": "grains_carbs",
    "sub_category": "breads_toast",
    "calories_per_100g": 235,
    "protein_per_100g": 11.8,
    "carbs_per_100g": 47.1,
    "fat_per_100g": 1.5,
    "fiber_per_100g": 5.9,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 34,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "bread_carb"
  },
  {
    "id": "gc-ext-017",
    "name": "100% Sprouted Sesame Ezekiel Bread",
    "category": "grains_carbs",
    "sub_category": "breads_toast",
    "calories_per_100g": 235,
    "protein_per_100g": 14.7,
    "carbs_per_100g": 44.1,
    "fat_per_100g": 2.5,
    "fiber_per_100g": 8.8,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 34,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "bread_carb"
  },
  {
    "id": "gc-ext-018",
    "name": "Vollkornbrot (German 100% Whole Rye Kernel Loaf)",
    "category": "grains_carbs",
    "sub_category": "breads_toast",
    "calories_per_100g": 200,
    "protein_per_100g": 6.5,
    "carbs_per_100g": 41,
    "fat_per_100g": 1.5,
    "fiber_per_100g": 9,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "bread_carb"
  },
  {
    "id": "gc-ext-019",
    "name": "Blue Corn Tortillas (Traditional Mexican 6-inch)",
    "category": "grains_carbs",
    "sub_category": "tortillas_wraps",
    "calories_per_100g": 215,
    "protein_per_100g": 6,
    "carbs_per_100g": 44,
    "fat_per_100g": 2.8,
    "fiber_per_100g": 6.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "bread_carb"
  },
  {
    "id": "gc-ext-020",
    "name": "Organic Brown Rice Tortillas (Food for Life Gluten-Free)",
    "category": "grains_carbs",
    "sub_category": "tortillas_wraps",
    "calories_per_100g": 220,
    "protein_per_100g": 4,
    "carbs_per_100g": 48,
    "fat_per_100g": 2.5,
    "fiber_per_100g": 4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "bread_carb"
  }
];
