import { FoodItem } from '../types';

export const GRAINS_CARBS_DATABASE: FoodItem[] = [
  // ==========================================
  // OATS & HOT CEREALS (15+ items)
  // ==========================================
  {
    id: 'gc-oat-001',
    name: 'Certified Gluten-Free Old Fashioned Rolled Oats',
    category: 'grains_carbs',
    sub_category: 'oats_cereals',
    calories_per_100g: 379,
    protein_per_100g: 13.2,
    carbs_per_100g: 67.7,
    fat_per_100g: 6.5,
    fiber_per_100g: 10.1,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 60,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-oat-002',
    name: 'Steel-Cut Oats (Dry)',
    category: 'grains_carbs',
    sub_category: 'oats_cereals',
    calories_per_100g: 375,
    protein_per_100g: 12.5,
    carbs_per_100g: 68.0,
    fat_per_100g: 6.0,
    fiber_per_100g: 10.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 50,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-oat-003',
    name: 'Quick 1-Minute Cooking Oats',
    category: 'grains_carbs',
    sub_category: 'oats_cereals',
    calories_per_100g: 370,
    protein_per_100g: 13.0,
    carbs_per_100g: 68.0,
    fat_per_100g: 5.5,
    fiber_per_100g: 9.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 50,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-oat-004',
    name: 'Cream of Rice Hot Cereal (Dry)',
    category: 'grains_carbs',
    sub_category: 'oats_cereals',
    calories_per_100g: 360,
    protein_per_100g: 7.0,
    carbs_per_100g: 80.0,
    fat_per_100g: 0.5,
    fiber_per_100g: 1.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 45,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-oat-005',
    name: 'Organic Oat Bran (High Soluble Beta-Glucan Fiber)',
    category: 'grains_carbs',
    sub_category: 'oats_cereals',
    calories_per_100g: 246,
    protein_per_100g: 17.3,
    carbs_per_100g: 66.2,
    fat_per_100g: 7.0,
    fiber_per_100g: 15.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 40,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },

  // ==========================================
  // RICE & ANCIENT GRAINS (15+ items)
  // ==========================================
  {
    id: 'gc-ric-001',
    name: 'Steamed Jasmine White Rice',
    category: 'grains_carbs',
    sub_category: 'rice_grains',
    calories_per_100g: 130,
    protein_per_100g: 2.7,
    carbs_per_100g: 28.2,
    fat_per_100g: 0.3,
    fiber_per_100g: 0.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 180,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-ric-002',
    name: 'Cooked Brown Basmati Rice',
    category: 'grains_carbs',
    sub_category: 'rice_grains',
    calories_per_100g: 123,
    protein_per_100g: 2.7,
    carbs_per_100g: 25.6,
    fat_per_100g: 1.0,
    fiber_per_100g: 1.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 180,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-ric-003',
    name: 'Organic Tri-Color Quinoa (Cooked)',
    category: 'grains_carbs',
    sub_category: 'rice_grains',
    calories_per_100g: 120,
    protein_per_100g: 4.4,
    carbs_per_100g: 21.3,
    fat_per_100g: 1.9,
    fiber_per_100g: 2.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-ric-004',
    name: 'Cooked Pearled Farro',
    category: 'grains_carbs',
    sub_category: 'rice_grains',
    calories_per_100g: 135,
    protein_per_100g: 5.0,
    carbs_per_100g: 27.0,
    fat_per_100g: 0.8,
    fiber_per_100g: 3.5,
    is_gluten_free: false,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-ric-005',
    name: 'Cooked Wild Rice',
    category: 'grains_carbs',
    sub_category: 'rice_grains',
    calories_per_100g: 101,
    protein_per_100g: 4.0,
    carbs_per_100g: 21.3,
    fat_per_100g: 0.3,
    fiber_per_100g: 1.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },

  // ==========================================
  // POTATOES & SWEET YAMS (15+ items)
  // ==========================================
  {
    id: 'gc-pot-001',
    name: 'Baked Garnet Sweet Potato',
    category: 'grains_carbs',
    sub_category: 'potatoes_yams',
    calories_per_100g: 90,
    protein_per_100g: 2.0,
    carbs_per_100g: 20.7,
    fat_per_100g: 0.2,
    fiber_per_100g: 3.3,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 200,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-pot-002',
    name: 'Japanese White Sweet Potato (Roasted)',
    category: 'grains_carbs',
    sub_category: 'potatoes_yams',
    calories_per_100g: 100,
    protein_per_100g: 2.1,
    carbs_per_100g: 23.0,
    fat_per_100g: 0.2,
    fiber_per_100g: 3.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 200,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-pot-003',
    name: 'Boiled Russet / Idaho Potato (Flesh & Skin)',
    category: 'grains_carbs',
    sub_category: 'potatoes_yams',
    calories_per_100g: 87,
    protein_per_100g: 1.9,
    carbs_per_100g: 20.1,
    fat_per_100g: 0.1,
    fiber_per_100g: 1.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 200,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-pot-004',
    name: 'Yukon Gold Potatoes (Steamed)',
    category: 'grains_carbs',
    sub_category: 'potatoes_yams',
    calories_per_100g: 80,
    protein_per_100g: 2.0,
    carbs_per_100g: 18.0,
    fat_per_100g: 0.1,
    fiber_per_100g: 1.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 180,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-pot-005',
    name: 'Roasted Butternut Squash Cubes',
    category: 'grains_carbs',
    sub_category: 'potatoes_yams',
    calories_per_100g: 45,
    protein_per_100g: 1.0,
    carbs_per_100g: 11.7,
    fat_per_100g: 0.1,
    fiber_per_100g: 2.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 180,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'complex_carb',
  },

  // ==========================================
  // BREADS & ARTISAN TOAST (15+ items)
  // ==========================================
  {
    id: 'gc-brd-001',
    name: '100% Sourdough Artisan Bread Slice',
    category: 'grains_carbs',
    sub_category: 'breads_toast',
    calories_per_100g: 240,
    protein_per_100g: 8.5,
    carbs_per_100g: 48.0,
    fat_per_100g: 1.2,
    fiber_per_100g: 2.5,
    is_gluten_free: false,
    is_dairy_free: true,
    serving_size_g: 50,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-brd-002',
    name: 'Ezekiel 4:9 Sprouted Whole Grain Bread',
    category: 'grains_carbs',
    sub_category: 'breads_toast',
    calories_per_100g: 235,
    protein_per_100g: 14.0,
    carbs_per_100g: 44.0,
    fat_per_100g: 1.5,
    fiber_per_100g: 7.5,
    is_gluten_free: false,
    is_dairy_free: true,
    serving_size_g: 45,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-brd-003',
    name: 'Dave’s Killer Bread 21 Whole Grains & Seeds',
    category: 'grains_carbs',
    sub_category: 'breads_toast',
    calories_per_100g: 244,
    protein_per_100g: 11.1,
    carbs_per_100g: 48.9,
    fat_per_100g: 3.3,
    fiber_per_100g: 11.1,
    is_gluten_free: false,
    is_dairy_free: true,
    serving_size_g: 45,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-brd-004',
    name: 'Plain Bagel Thins (110 Cal)',
    category: 'grains_carbs',
    sub_category: 'breads_toast',
    calories_per_100g: 240,
    protein_per_100g: 10.0,
    carbs_per_100g: 48.0,
    fat_per_100g: 1.0,
    fiber_per_100g: 4.0,
    is_gluten_free: false,
    is_dairy_free: true,
    serving_size_g: 46,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-brd-005',
    name: '100% Whole Wheat English Muffin',
    category: 'grains_carbs',
    sub_category: 'breads_toast',
    calories_per_100g: 220,
    protein_per_100g: 10.0,
    carbs_per_100g: 44.0,
    fat_per_100g: 1.5,
    fiber_per_100g: 5.0,
    is_gluten_free: false,
    is_dairy_free: true,
    serving_size_g: 57,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'complex_carb',
  },

  // ==========================================
  // PASTAS & TORTILLAS (15+ items)
  // ==========================================
  {
    id: 'gc-pst-001',
    name: 'Cooked Whole Wheat Penne Pasta',
    category: 'grains_carbs',
    sub_category: 'pastas_noodles',
    calories_per_100g: 124,
    protein_per_100g: 5.3,
    carbs_per_100g: 26.5,
    fat_per_100g: 0.5,
    fiber_per_100g: 3.9,
    is_gluten_free: false,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-pst-002',
    name: 'Chickpea Pasta (Banza Rotini, Cooked)',
    category: 'grains_carbs',
    sub_category: 'pastas_noodles',
    calories_per_100g: 150,
    protein_per_100g: 9.5,
    carbs_per_100g: 24.0,
    fat_per_100g: 2.2,
    fiber_per_100g: 4.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 140,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-pst-003',
    name: '100% Soba Buckwheat Japanese Noodles (Cooked)',
    category: 'grains_carbs',
    sub_category: 'pastas_noodles',
    calories_per_100g: 99,
    protein_per_100g: 5.1,
    carbs_per_100g: 21.4,
    fat_per_100g: 0.1,
    fiber_per_100g: 2.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-tor-001',
    name: 'Yellow Corn Tortillas (Street Taco Size)',
    category: 'grains_carbs',
    sub_category: 'tortillas_wraps',
    calories_per_100g: 218,
    protein_per_100g: 5.7,
    carbs_per_100g: 45.0,
    fat_per_100g: 2.9,
    fiber_per_100g: 6.3,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 50,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'gc-tor-002',
    name: 'Whole Wheat Low-Carb Tortilla Wrap (Mission Carb Balance)',
    category: 'grains_carbs',
    sub_category: 'tortillas_wraps',
    calories_per_100g: 160,
    protein_per_100g: 11.0,
    carbs_per_100g: 42.0,
    fat_per_100g: 5.0,
    fiber_per_100g: 33.0,
    is_gluten_free: false,
    is_dairy_free: true,
    serving_size_g: 45,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
];
