import { FoodItem } from '../types';

export const NUTS_FATS_OILS_DATABASE: FoodItem[] = [
  // ==========================================
  // AVOCADOS & OLIVES (10+ items)
  // ==========================================
  {
    id: 'hf-avo-001',
    name: 'Fresh Hass Avocado (Sliced)',
    category: 'nuts_fats_oils',
    sub_category: 'avocados_olives',
    calories_per_100g: 160,
    protein_per_100g: 2.0,
    carbs_per_100g: 8.5,
    fat_per_100g: 14.7,
    fiber_per_100g: 6.7,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 75,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'healthy_fat',
  },
  {
    id: 'hf-avo-002',
    name: 'Fresh Guacamole (Avocado, Lime, Cilantro)',
    category: 'nuts_fats_oils',
    sub_category: 'avocados_olives',
    calories_per_100g: 155,
    protein_per_100g: 2.0,
    carbs_per_100g: 8.0,
    fat_per_100g: 14.0,
    fiber_per_100g: 6.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 60,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'healthy_fat',
  },
  {
    id: 'hf-avo-003',
    name: 'Kalamata Greek Olives (Pitted)',
    category: 'nuts_fats_oils',
    sub_category: 'avocados_olives',
    calories_per_100g: 240,
    protein_per_100g: 1.5,
    carbs_per_100g: 3.0,
    fat_per_100g: 25.0,
    fiber_per_100g: 2.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'healthy_fat',
  },
  {
    id: 'hf-avo-004',
    name: 'Castelvetrano Sicilian Green Olives',
    category: 'nuts_fats_oils',
    sub_category: 'avocados_olives',
    calories_per_100g: 145,
    protein_per_100g: 1.0,
    carbs_per_100g: 4.0,
    fat_per_100g: 15.0,
    fiber_per_100g: 3.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'healthy_fat',
  },

  // ==========================================
  // WHOLE TREE NUTS (15+ items)
  // ==========================================
  {
    id: 'hf-nut-001',
    name: 'Raw Whole Almonds (California)',
    category: 'nuts_fats_oils',
    sub_category: 'whole_nuts',
    calories_per_100g: 579,
    protein_per_100g: 21.2,
    carbs_per_100g: 21.6,
    fat_per_100g: 49.9,
    fiber_per_100g: 12.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'nut_fat',
  },
  {
    id: 'hf-nut-002',
    name: 'Dry Roasted Unsalted Almonds',
    category: 'nuts_fats_oils',
    sub_category: 'whole_nuts',
    calories_per_100g: 585,
    protein_per_100g: 21.5,
    carbs_per_100g: 21.0,
    fat_per_100g: 50.5,
    fiber_per_100g: 12.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'nut_fat',
  },
  {
    id: 'hf-nut-003',
    name: 'Raw English Walnut Halves (Omega-3 ALA Rich)',
    category: 'nuts_fats_oils',
    sub_category: 'whole_nuts',
    calories_per_100g: 654,
    protein_per_100g: 15.2,
    carbs_per_100g: 13.7,
    fat_per_100g: 65.2,
    fiber_per_100g: 6.7,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'nut_fat',
  },
  {
    id: 'hf-nut-004',
    name: 'Raw Cashews (Whole Kernels)',
    category: 'nuts_fats_oils',
    sub_category: 'whole_nuts',
    calories_per_100g: 553,
    protein_per_100g: 18.2,
    carbs_per_100g: 30.2,
    fat_per_100g: 43.8,
    fiber_per_100g: 3.3,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'nut_fat',
  },
  {
    id: 'hf-nut-005',
    name: 'Roasted Unsalted Pistachios (Shelled)',
    category: 'nuts_fats_oils',
    sub_category: 'whole_nuts',
    calories_per_100g: 560,
    protein_per_100g: 20.2,
    carbs_per_100g: 27.2,
    fat_per_100g: 45.3,
    fiber_per_100g: 10.6,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'nut_fat',
  },
  {
    id: 'hf-nut-006',
    name: 'Raw Pecan Halves',
    category: 'nuts_fats_oils',
    sub_category: 'whole_nuts',
    calories_per_100g: 691,
    protein_per_100g: 9.2,
    carbs_per_100g: 13.9,
    fat_per_100g: 72.0,
    fiber_per_100g: 9.6,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'nut_fat',
  },
  {
    id: 'hf-nut-007',
    name: 'Brazil Nuts (Natural Selenium Source)',
    category: 'nuts_fats_oils',
    sub_category: 'whole_nuts',
    calories_per_100g: 659,
    protein_per_100g: 14.3,
    carbs_per_100g: 12.3,
    fat_per_100g: 67.1,
    fiber_per_100g: 7.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 15,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'nut_fat',
  },

  // ==========================================
  // NATURAL NUT & SEED BUTTERS (10+ items)
  // ==========================================
  {
    id: 'hf-but-001',
    name: 'Natural Creamy Peanut Butter (100% Peanuts & Salt)',
    category: 'nuts_fats_oils',
    sub_category: 'nut_butters',
    calories_per_100g: 588,
    protein_per_100g: 25.0,
    carbs_per_100g: 20.0,
    fat_per_100g: 50.0,
    fiber_per_100g: 8.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 32,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'nut_fat',
  },
  {
    id: 'hf-but-002',
    name: 'Natural Crunchy Peanut Butter',
    category: 'nuts_fats_oils',
    sub_category: 'nut_butters',
    calories_per_100g: 590,
    protein_per_100g: 25.0,
    carbs_per_100g: 19.5,
    fat_per_100g: 50.5,
    fiber_per_100g: 8.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 32,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'nut_fat',
  },
  {
    id: 'hf-but-003',
    name: 'Natural Creamy Almond Butter',
    category: 'nuts_fats_oils',
    sub_category: 'nut_butters',
    calories_per_100g: 614,
    protein_per_100g: 21.0,
    carbs_per_100g: 19.0,
    fat_per_100g: 55.5,
    fiber_per_100g: 10.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 32,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'nut_fat',
  },
  {
    id: 'hf-but-004',
    name: 'Organic Tahini (100% Ground Roasted Sesame Seed Paste)',
    category: 'nuts_fats_oils',
    sub_category: 'nut_butters',
    calories_per_100g: 595,
    protein_per_100g: 17.0,
    carbs_per_100g: 21.2,
    fat_per_100g: 53.8,
    fiber_per_100g: 9.3,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'nut_fat',
  },

  // ==========================================
  // SUPER SEEDS (10+ items)
  // ==========================================
  {
    id: 'hf-sed-001',
    name: 'Organic Whole Black Chia Seeds',
    category: 'nuts_fats_oils',
    sub_category: 'super_seeds',
    calories_per_100g: 486,
    protein_per_100g: 16.5,
    carbs_per_100g: 42.1,
    fat_per_100g: 30.7,
    fiber_per_100g: 34.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 20,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'healthy_fat',
  },
  {
    id: 'hf-sed-002',
    name: 'Ground Golden Flaxseed Meal (Cold-Milled)',
    category: 'nuts_fats_oils',
    sub_category: 'super_seeds',
    calories_per_100g: 534,
    protein_per_100g: 18.3,
    carbs_per_100g: 28.9,
    fat_per_100g: 42.2,
    fiber_per_100g: 27.3,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 15,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'healthy_fat',
  },
  {
    id: 'hf-sed-003',
    name: 'Raw Pumpkin Seeds / Pepitas',
    category: 'nuts_fats_oils',
    sub_category: 'super_seeds',
    calories_per_100g: 559,
    protein_per_100g: 30.2,
    carbs_per_100g: 10.7,
    fat_per_100g: 49.0,
    fiber_per_100g: 6.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'nut_fat',
  },

  // ==========================================
  // COLD-PRESSED OILS & GHEE (10+ items)
  // ==========================================
  {
    id: 'hf-oil-001',
    name: 'Extra Virgin First Cold-Pressed Olive Oil',
    category: 'nuts_fats_oils',
    sub_category: 'healthy_oils',
    calories_per_100g: 884,
    protein_per_100g: 0.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 100.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 15,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'cooking_fat',
  },
  {
    id: 'hf-oil-002',
    name: 'Pure Avocado Oil (High Smoke Point)',
    category: 'nuts_fats_oils',
    sub_category: 'healthy_oils',
    calories_per_100g: 884,
    protein_per_100g: 0.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 100.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 15,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'cooking_fat',
  },
  {
    id: 'hf-oil-003',
    name: 'Extra Virgin Unrefined Coconut Oil',
    category: 'nuts_fats_oils',
    sub_category: 'healthy_oils',
    calories_per_100g: 862,
    protein_per_100g: 0.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 100.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 14,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'cooking_fat',
  },
  {
    id: 'hf-oil-004',
    name: 'Grass-Fed Clarified Butter / Ghee',
    category: 'nuts_fats_oils',
    sub_category: 'healthy_oils',
    calories_per_100g: 876,
    protein_per_100g: 0.3,
    carbs_per_100g: 0.0,
    fat_per_100g: 99.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 14,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'cooking_fat',
  },
];
