import { FoodItem } from '../types';

export const NUTS_FATS_OILS_DATABASE: FoodItem[] = [
  {
    "id": "hf-avo-001",
    "name": "Hass Avocado (Fresh Ripe Slices)",
    "category": "nuts_fats_oils",
    "sub_category": "avocados_olives",
    "calories_per_100g": 160,
    "protein_per_100g": 2,
    "carbs_per_100g": 8.5,
    "fat_per_100g": 14.7,
    "fiber_per_100g": 6.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "hf-avo-002",
    "name": "Florida / Reed Avocado (Smooth Green Skin)",
    "category": "nuts_fats_oils",
    "sub_category": "avocados_olives",
    "calories_per_100g": 120,
    "protein_per_100g": 1.5,
    "carbs_per_100g": 7.5,
    "fat_per_100g": 10,
    "fiber_per_100g": 5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 60,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "hf-avo-003",
    "name": "Fresh Guacamole (Avocado, Lime, Cilantro & Sea Salt)",
    "category": "nuts_fats_oils",
    "sub_category": "avocados_olives",
    "calories_per_100g": 155,
    "protein_per_100g": 1.8,
    "carbs_per_100g": 8,
    "fat_per_100g": 14,
    "fiber_per_100g": 6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 60,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "hf-avo-004",
    "name": "Kalamata Greek Black Olives (in Brine Pitted)",
    "category": "nuts_fats_oils",
    "sub_category": "avocados_olives",
    "calories_per_100g": 239,
    "protein_per_100g": 1.8,
    "carbs_per_100g": 4.8,
    "fat_per_100g": 23.5,
    "fiber_per_100g": 3.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "hf-avo-005",
    "name": "Castelvetrano Sicilian Bright Green Olives (Pitted)",
    "category": "nuts_fats_oils",
    "sub_category": "avocados_olives",
    "calories_per_100g": 145,
    "protein_per_100g": 1,
    "carbs_per_100g": 3.8,
    "fat_per_100g": 15,
    "fiber_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "hf-avo-006",
    "name": "Spanish Manzanilla Green Olives (Stuffed with Pimento)",
    "category": "nuts_fats_oils",
    "sub_category": "avocados_olives",
    "calories_per_100g": 140,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 3.5,
    "fat_per_100g": 14.5,
    "fiber_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "hf-avo-007",
    "name": "Black Mission Olives (Ripe Canned Sliced)",
    "category": "nuts_fats_oils",
    "sub_category": "avocados_olives",
    "calories_per_100g": 115,
    "protein_per_100g": 0.8,
    "carbs_per_100g": 6.3,
    "fat_per_100g": 10.7,
    "fiber_per_100g": 3.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "hf-avo-008",
    "name": "Cerignola Giant Italian Green Olives",
    "category": "nuts_fats_oils",
    "sub_category": "avocados_olives",
    "calories_per_100g": 150,
    "protein_per_100g": 1.1,
    "carbs_per_100g": 4,
    "fat_per_100g": 15.5,
    "fiber_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 40,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "hf-avo-009",
    "name": "Gaeta Italian Small Black Olives",
    "category": "nuts_fats_oils",
    "sub_category": "avocados_olives",
    "calories_per_100g": 240,
    "protein_per_100g": 1.8,
    "carbs_per_100g": 4.5,
    "fat_per_100g": 24,
    "fiber_per_100g": 3.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "hf-nut-001",
    "name": "Raw Whole California Almonds",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 579,
    "protein_per_100g": 21.2,
    "carbs_per_100g": 21.6,
    "fat_per_100g": 49.9,
    "fiber_per_100g": 12.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-nut-002",
    "name": "Dry Roasted Almonds (Unsalted)",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 598,
    "protein_per_100g": 21,
    "carbs_per_100g": 21,
    "fat_per_100g": 52.5,
    "fiber_per_100g": 11,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-nut-003",
    "name": "Marcona Spanish Almonds (Skinless Fried in Olive Oil & Salt)",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 620,
    "protein_per_100g": 19,
    "carbs_per_100g": 18,
    "fat_per_100g": 57,
    "fiber_per_100g": 10,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-nut-004",
    "name": "Raw English Walnut Halves & Pieces (Omega-3 ALA)",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 654,
    "protein_per_100g": 15.2,
    "carbs_per_100g": 13.7,
    "fat_per_100g": 65.2,
    "fiber_per_100g": 6.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-nut-005",
    "name": "Raw Georgia Pecan Halves",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 691,
    "protein_per_100g": 9.2,
    "carbs_per_100g": 13.9,
    "fat_per_100g": 72,
    "fiber_per_100g": 9.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-nut-006",
    "name": "Raw Whole Cashews",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 553,
    "protein_per_100g": 18.2,
    "carbs_per_100g": 30.2,
    "fat_per_100g": 43.9,
    "fiber_per_100g": 3.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-nut-007",
    "name": "Dry Roasted Cashews (Unsalted)",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 574,
    "protein_per_100g": 15.3,
    "carbs_per_100g": 32.7,
    "fat_per_100g": 46.4,
    "fiber_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-nut-008",
    "name": "Raw Pistachio Kernels (Shelled)",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 560,
    "protein_per_100g": 20.2,
    "carbs_per_100g": 27.2,
    "fat_per_100g": 45.3,
    "fiber_per_100g": 10.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-nut-009",
    "name": "Dry Roasted Pistachios in Shell (Lightly Salted Wonderful)",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 568,
    "protein_per_100g": 21,
    "carbs_per_100g": 26.8,
    "fat_per_100g": 45.8,
    "fiber_per_100g": 10.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-nut-010",
    "name": "Raw Hawaiian Macadamia Nuts",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 718,
    "protein_per_100g": 7.9,
    "carbs_per_100g": 13.8,
    "fat_per_100g": 75.8,
    "fiber_per_100g": 8.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-nut-011",
    "name": "Dry Roasted Salted Macadamia Nuts",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 725,
    "protein_per_100g": 7.8,
    "carbs_per_100g": 14,
    "fat_per_100g": 76.5,
    "fiber_per_100g": 8.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-nut-012",
    "name": "Raw Brazil Nuts (Selenium Rich Whole)",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 659,
    "protein_per_100g": 14.3,
    "carbs_per_100g": 12.3,
    "fat_per_100g": 67.1,
    "fiber_per_100g": 7.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-nut-013",
    "name": "Raw Oregon Hazelnuts / Filberts",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 628,
    "protein_per_100g": 15,
    "carbs_per_100g": 16.7,
    "fat_per_100g": 60.8,
    "fiber_per_100g": 9.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-nut-014",
    "name": "Mediterranean Pine Nuts / Pignolias",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 673,
    "protein_per_100g": 13.7,
    "carbs_per_100g": 13.1,
    "fat_per_100g": 68.4,
    "fiber_per_100g": 3.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 25,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-nut-015",
    "name": "Raw Peanuts (Skinless Shelled)",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 567,
    "protein_per_100g": 25.8,
    "carbs_per_100g": 16.1,
    "fat_per_100g": 49.2,
    "fiber_per_100g": 8.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-nut-016",
    "name": "Dry Roasted Peanuts (Unsalted)",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 585,
    "protein_per_100g": 24,
    "carbs_per_100g": 21,
    "fat_per_100g": 49.5,
    "fiber_per_100g": 8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-but-001",
    "name": "All-Natural Creamy Peanut Butter (Peanuts & Salt Smucker's)",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 588,
    "protein_per_100g": 25.1,
    "carbs_per_100g": 20,
    "fat_per_100g": 50.4,
    "fiber_per_100g": 6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 32,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-but-002",
    "name": "All-Natural Crunchy Peanut Butter",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 588,
    "protein_per_100g": 25.1,
    "carbs_per_100g": 20,
    "fat_per_100g": 50.4,
    "fiber_per_100g": 6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 32,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-but-003",
    "name": "Powdered Peanut Butter (PB2 85% Less Fat)",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 375,
    "protein_per_100g": 45,
    "carbs_per_100g": 30,
    "fat_per_100g": 8,
    "fiber_per_100g": 15,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 16,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-but-004",
    "name": "Organic Creamy Raw Almond Butter (100% Almonds Artisana)",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 614,
    "protein_per_100g": 20.9,
    "carbs_per_100g": 18.8,
    "fat_per_100g": 55.5,
    "fiber_per_100g": 10.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 32,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-but-005",
    "name": "Roasted Creamy Almond Butter (Justin's / MaraNatha)",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 614,
    "protein_per_100g": 21,
    "carbs_per_100g": 18.5,
    "fat_per_100g": 55.5,
    "fiber_per_100g": 10.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 32,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-but-006",
    "name": "Creamy Cashew Butter (100% Cashews)",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 587,
    "protein_per_100g": 17.6,
    "carbs_per_100g": 27.6,
    "fat_per_100g": 49.3,
    "fiber_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 32,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-but-007",
    "name": "Pure Tahini (100% Ground Roasted Sesame Paste Soom style)",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 595,
    "protein_per_100g": 17,
    "carbs_per_100g": 21.2,
    "fat_per_100g": 53.8,
    "fiber_per_100g": 9.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-but-008",
    "name": "Sunflower Seed Butter (SunButter Natural Unsweetened)",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 617,
    "protein_per_100g": 19.8,
    "carbs_per_100g": 22,
    "fat_per_100g": 54,
    "fiber_per_100g": 6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 32,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-but-009",
    "name": "Raw Walnut Butter (Rich in Plant Omega-3)",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 650,
    "protein_per_100g": 15,
    "carbs_per_100g": 14,
    "fat_per_100g": 65,
    "fiber_per_100g": 6.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 32,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-but-010",
    "name": "Macadamia Nut Butter (Artisana Raw)",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 715,
    "protein_per_100g": 8,
    "carbs_per_100g": 14,
    "fat_per_100g": 75,
    "fiber_per_100g": 8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 32,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-but-011",
    "name": "Jif Creamy Peanut Butter",
    "brand": "Jif",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 576,
    "protein_per_100g": 21.2,
    "carbs_per_100g": 24.2,
    "fat_per_100g": 48.5,
    "fiber_per_100g": 6.1,
    "sugar_per_100g": 9.1,
    "added_sugar_per_100g": 6.1,
    "saturated_fat_per_100g": 7.6,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 424,
    "potassium_per_100g": 606,
    "calcium_per_100g": 61,
    "iron_per_100g": 2.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 33,
    "default_unit": "tbsp (16.5g)",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-but-012",
    "name": "Jif Extra Crunchy Peanut Butter",
    "brand": "Jif",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 576,
    "protein_per_100g": 21.2,
    "carbs_per_100g": 24.2,
    "fat_per_100g": 48.5,
    "fiber_per_100g": 6.1,
    "sugar_per_100g": 9.1,
    "added_sugar_per_100g": 6.1,
    "saturated_fat_per_100g": 7.6,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 424,
    "potassium_per_100g": 606,
    "calcium_per_100g": 61,
    "iron_per_100g": 2.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 33,
    "default_unit": "tbsp (16.5g)",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-but-013",
    "name": "Jif Natural Creamy Peanut Butter (90% Peanuts)",
    "brand": "Jif",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 576,
    "protein_per_100g": 21.2,
    "carbs_per_100g": 24.2,
    "fat_per_100g": 48.5,
    "fiber_per_100g": 6.1,
    "sugar_per_100g": 9.1,
    "added_sugar_per_100g": 6.1,
    "saturated_fat_per_100g": 7.6,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 242,
    "potassium_per_100g": 606,
    "calcium_per_100g": 61,
    "iron_per_100g": 2.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 33,
    "default_unit": "tbsp (16.5g)",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-but-014",
    "name": "Skippy Creamy Peanut Butter",
    "brand": "Skippy",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 594,
    "protein_per_100g": 21.9,
    "carbs_per_100g": 21.9,
    "fat_per_100g": 50.0,
    "fiber_per_100g": 6.3,
    "sugar_per_100g": 9.4,
    "added_sugar_per_100g": 6.3,
    "saturated_fat_per_100g": 9.4,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 469,
    "potassium_per_100g": 656,
    "calcium_per_100g": 63,
    "iron_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 32,
    "default_unit": "tbsp (16g)",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-but-015",
    "name": "Skippy Super Chunk Peanut Butter",
    "brand": "Skippy",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 594,
    "protein_per_100g": 21.9,
    "carbs_per_100g": 21.9,
    "fat_per_100g": 50.0,
    "fiber_per_100g": 6.3,
    "sugar_per_100g": 9.4,
    "added_sugar_per_100g": 6.3,
    "saturated_fat_per_100g": 9.4,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 469,
    "potassium_per_100g": 656,
    "calcium_per_100g": 63,
    "iron_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 32,
    "default_unit": "tbsp (16g)",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-but-016",
    "name": "Skippy Natural Creamy Peanut Butter",
    "brand": "Skippy",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 594,
    "protein_per_100g": 21.9,
    "carbs_per_100g": 18.8,
    "fat_per_100g": 50.0,
    "fiber_per_100g": 6.3,
    "sugar_per_100g": 9.4,
    "added_sugar_per_100g": 6.3,
    "saturated_fat_per_100g": 9.4,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 469,
    "potassium_per_100g": 656,
    "calcium_per_100g": 63,
    "iron_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 32,
    "default_unit": "tbsp (16g)",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-but-017",
    "name": "Peter Pan Creamy Peanut Butter",
    "brand": "Peter Pan",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 656,
    "protein_per_100g": 25.0,
    "carbs_per_100g": 18.8,
    "fat_per_100g": 53.1,
    "fiber_per_100g": 6.3,
    "sugar_per_100g": 9.4,
    "added_sugar_per_100g": 6.3,
    "saturated_fat_per_100g": 9.4,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 438,
    "potassium_per_100g": 625,
    "calcium_per_100g": 63,
    "iron_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 32,
    "default_unit": "tbsp (16g)",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-but-018",
    "name": "Smucker's Natural Creamy Peanut Butter",
    "brand": "Smucker's",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 594,
    "protein_per_100g": 25.0,
    "carbs_per_100g": 18.8,
    "fat_per_100g": 50.0,
    "fiber_per_100g": 6.3,
    "sugar_per_100g": 6.3,
    "added_sugar_per_100g": 0,
    "saturated_fat_per_100g": 7.8,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 328,
    "potassium_per_100g": 625,
    "calcium_per_100g": 63,
    "iron_per_100g": 3.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 32,
    "default_unit": "tbsp (16g)",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-but-019",
    "name": "Justin's Classic Peanut Butter",
    "brand": "Justin's",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 656,
    "protein_per_100g": 25.0,
    "carbs_per_100g": 15.6,
    "fat_per_100g": 56.3,
    "fiber_per_100g": 3.1,
    "sugar_per_100g": 6.3,
    "added_sugar_per_100g": 0,
    "saturated_fat_per_100g": 9.4,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 0,
    "potassium_per_100g": 625,
    "calcium_per_100g": 63,
    "iron_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 32,
    "default_unit": "tbsp (16g)",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-but-020",
    "name": "PBfit All-Natural Peanut Butter Powder (87% Less Fat)",
    "brand": "BetterBody Foods PBfit",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 438,
    "protein_per_100g": 50.0,
    "carbs_per_100g": 31.3,
    "fat_per_100g": 12.5,
    "fiber_per_100g": 18.8,
    "sugar_per_100g": 12.5,
    "added_sugar_per_100g": 12.5,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 875,
    "potassium_per_100g": 938,
    "calcium_per_100g": 125,
    "iron_per_100g": 6.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 16,
    "default_unit": "tbsp (8g)",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-sed-001",
    "name": "Whole Black Chia Seeds (Raw Omega-3 Mamma Chia)",
    "category": "nuts_fats_oils",
    "sub_category": "super_seeds",
    "calories_per_100g": 486,
    "protein_per_100g": 16.5,
    "carbs_per_100g": 42.1,
    "fat_per_100g": 30.7,
    "fiber_per_100g": 34.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 15,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-sed-002",
    "name": "Whole White Chia Seeds",
    "category": "nuts_fats_oils",
    "sub_category": "super_seeds",
    "calories_per_100g": 486,
    "protein_per_100g": 16.5,
    "carbs_per_100g": 42.1,
    "fat_per_100g": 30.7,
    "fiber_per_100g": 34.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 15,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-sed-003",
    "name": "Ground Golden Flaxseed Meal (Cold-Milled Bob's Red Mill)",
    "category": "nuts_fats_oils",
    "sub_category": "super_seeds",
    "calories_per_100g": 534,
    "protein_per_100g": 18.3,
    "carbs_per_100g": 28.9,
    "fat_per_100g": 42.2,
    "fiber_per_100g": 27.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 15,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-sed-004",
    "name": "Whole Golden Flaxseeds",
    "category": "nuts_fats_oils",
    "sub_category": "super_seeds",
    "calories_per_100g": 534,
    "protein_per_100g": 18.3,
    "carbs_per_100g": 28.9,
    "fat_per_100g": 42.2,
    "fiber_per_100g": 27.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 15,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-sed-005",
    "name": "Raw Pumpkin Seeds / Pepitas (Hulled Green)",
    "category": "nuts_fats_oils",
    "sub_category": "super_seeds",
    "calories_per_100g": 559,
    "protein_per_100g": 30.2,
    "carbs_per_100g": 10.7,
    "fat_per_100g": 49.1,
    "fiber_per_100g": 6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-sed-006",
    "name": "Dry Roasted Salted Pumpkin Seeds",
    "category": "nuts_fats_oils",
    "sub_category": "super_seeds",
    "calories_per_100g": 570,
    "protein_per_100g": 30,
    "carbs_per_100g": 12,
    "fat_per_100g": 50,
    "fiber_per_100g": 6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-sed-007",
    "name": "Raw Sunflower Seed Kernels",
    "category": "nuts_fats_oils",
    "sub_category": "super_seeds",
    "calories_per_100g": 584,
    "protein_per_100g": 20.8,
    "carbs_per_100g": 20,
    "fat_per_100g": 51.5,
    "fiber_per_100g": 8.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-sed-008",
    "name": "White Sesame Seeds (Toasted)",
    "category": "nuts_fats_oils",
    "sub_category": "super_seeds",
    "calories_per_100g": 573,
    "protein_per_100g": 17.7,
    "carbs_per_100g": 23.4,
    "fat_per_100g": 49.7,
    "fiber_per_100g": 11.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 15,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-sed-009",
    "name": "Black Sesame Seeds (Japanese Toasted)",
    "category": "nuts_fats_oils",
    "sub_category": "super_seeds",
    "calories_per_100g": 575,
    "protein_per_100g": 18,
    "carbs_per_100g": 23,
    "fat_per_100g": 50,
    "fiber_per_100g": 12,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 15,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-sed-010",
    "name": "Blue Poppy Seeds (Whole Baking)",
    "category": "nuts_fats_oils",
    "sub_category": "super_seeds",
    "calories_per_100g": 525,
    "protein_per_100g": 18,
    "carbs_per_100g": 28,
    "fat_per_100g": 42,
    "fiber_per_100g": 19.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 15,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-oil-001",
    "name": "Extra Virgin Olive Oil (First Cold-Pressed Single Origin)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 884,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 100,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-002",
    "name": "Pure Cold-Pressed Avocado Oil (Chosen Foods style)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 884,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 100,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-003",
    "name": "Virgin Unrefined Coconut Oil (Cold Pressed Organic)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 862,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 100,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-004",
    "name": "Toasted Dark Sesame Oil (Aromatic Kadoya)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 884,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 100,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 7,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-005",
    "name": "Pure MCT Oil (100% C8 Caprylic / C10 Capric Bulletproof)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 860,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 100,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-006",
    "name": "Organic Grass-Fed Ghee (Clarified Butter 4th & Heart)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 876,
    "protein_per_100g": 0.3,
    "carbs_per_100g": 0,
    "fat_per_100g": 99.5,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 14,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-007",
    "name": "European Style Grass-Fed Butter (Kerrygold Pure Irish)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 717,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 0.1,
    "fat_per_100g": 81.1,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 14,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-008",
    "name": "Raw Cacao Nibs (Crushed Unsweetened Criollo Cacao Navitas)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 600,
    "protein_per_100g": 14,
    "carbs_per_100g": 30,
    "fat_per_100g": 50,
    "fiber_per_100g": 18,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 15,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "hf-oil-009",
    "name": "Cold-Pressed Walnut Oil (La Tourangelle)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 884,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 100,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-010",
    "name": "Cold-Pressed Flaxseed Oil (Refrigerated Flora)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 884,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 100,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-011",
    "name": "Land O'Lakes Salted Butter (Sticks)",
    "brand": "Land O'Lakes",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 714,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 0.1,
    "fat_per_100g": 81.1,
    "saturated_fat_per_100g": 50.0,
    "trans_fat_per_100g": 2.9,
    "cholesterol_per_100g": 214,
    "sodium_per_100g": 643,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-012",
    "name": "Land O'Lakes Unsalted Butter (Sticks)",
    "brand": "Land O'Lakes",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 714,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 0.1,
    "fat_per_100g": 81.1,
    "saturated_fat_per_100g": 50.0,
    "trans_fat_per_100g": 2.9,
    "cholesterol_per_100g": 214,
    "sodium_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-013",
    "name": "Land O'Lakes Butter with Canola Oil (Spreadable Tub)",
    "brand": "Land O'Lakes",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 714,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 78.6,
    "saturated_fat_per_100g": 35.7,
    "monounsaturated_fat_per_100g": 28.6,
    "polyunsaturated_fat_per_100g": 10.7,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 107,
    "sodium_per_100g": 643,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-014",
    "name": "Land O'Lakes Light Butter with Canola Oil (Spreadable Tub)",
    "brand": "Land O'Lakes",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 357,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 35.7,
    "saturated_fat_per_100g": 17.9,
    "monounsaturated_fat_per_100g": 10.7,
    "polyunsaturated_fat_per_100g": 7.1,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 71,
    "sodium_per_100g": 714,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-015",
    "name": "Kerrygold Pure Irish Butter - Salted (Gold Foil Sticks)",
    "brand": "Kerrygold",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 714,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 0.1,
    "fat_per_100g": 80.0,
    "saturated_fat_per_100g": 57.1,
    "trans_fat_per_100g": 2.9,
    "cholesterol_per_100g": 214,
    "sodium_per_100g": 714,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-016",
    "name": "Kerrygold Pure Irish Butter - Unsalted (Silver Foil Sticks)",
    "brand": "Kerrygold",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 714,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 0.1,
    "fat_per_100g": 80.0,
    "saturated_fat_per_100g": 57.1,
    "trans_fat_per_100g": 2.9,
    "cholesterol_per_100g": 214,
    "sodium_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-017",
    "name": "Kerrygold Naturally Softer Pure Irish Butter (Spreadable Tub)",
    "brand": "Kerrygold",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 714,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 0.1,
    "fat_per_100g": 80.0,
    "saturated_fat_per_100g": 53.6,
    "trans_fat_per_100g": 2.9,
    "cholesterol_per_100g": 214,
    "sodium_per_100g": 714,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-018",
    "name": "Country Crock Original Spread (Tub)",
    "brand": "Country Crock",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 357,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 35.7,
    "saturated_fat_per_100g": 10.7,
    "monounsaturated_fat_per_100g": 10.7,
    "polyunsaturated_fat_per_100g": 14.3,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 714,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-019",
    "name": "Country Crock Plant Butter with Olive Oil (Sticks)",
    "brand": "Country Crock",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 714,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 78.6,
    "saturated_fat_per_100g": 35.7,
    "monounsaturated_fat_per_100g": 28.6,
    "polyunsaturated_fat_per_100g": 14.3,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 750,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-020",
    "name": "Country Crock Plant Butter with Olive Oil (Tub)",
    "brand": "Country Crock",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 714,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 78.6,
    "saturated_fat_per_100g": 28.6,
    "monounsaturated_fat_per_100g": 35.7,
    "polyunsaturated_fat_per_100g": 14.3,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 643,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-021",
    "name": "I Can't Believe It's Not Butter! Original (Tub)",
    "brand": "I Can't Believe It's Not Butter!",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 429,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 42.9,
    "saturated_fat_per_100g": 14.3,
    "monounsaturated_fat_per_100g": 10.7,
    "polyunsaturated_fat_per_100g": 17.9,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 643,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-022",
    "name": "I Can't Believe It's Not Butter! Light (Tub)",
    "brand": "I Can't Believe It's Not Butter!",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 250,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 28.6,
    "saturated_fat_per_100g": 7.1,
    "monounsaturated_fat_per_100g": 7.1,
    "polyunsaturated_fat_per_100g": 14.3,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 714,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-023",
    "name": "I Can't Believe It's Not Butter! Original (Sticks)",
    "brand": "I Can't Believe It's Not Butter!",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 571,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 64.3,
    "saturated_fat_per_100g": 25.0,
    "monounsaturated_fat_per_100g": 17.9,
    "polyunsaturated_fat_per_100g": 21.4,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 643,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-024",
    "name": "Challenge Dairy Salted Butter (Sticks)",
    "brand": "Challenge Dairy",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 714,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 0.1,
    "fat_per_100g": 81.1,
    "saturated_fat_per_100g": 50.0,
    "trans_fat_per_100g": 2.9,
    "cholesterol_per_100g": 214,
    "sodium_per_100g": 643,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-025",
    "name": "Challenge Dairy Unsalted Butter (Sticks)",
    "brand": "Challenge Dairy",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 714,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 0.1,
    "fat_per_100g": 81.1,
    "saturated_fat_per_100g": 50.0,
    "trans_fat_per_100g": 2.9,
    "cholesterol_per_100g": 214,
    "sodium_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-026",
    "name": "Challenge Butter with Olive Oil & Sea Salt (Spreadable Tub)",
    "brand": "Challenge Dairy",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 714,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 78.6,
    "saturated_fat_per_100g": 35.7,
    "monounsaturated_fat_per_100g": 28.6,
    "polyunsaturated_fat_per_100g": 10.7,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 143,
    "sodium_per_100g": 607,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-027",
    "name": "Countryside Creamery (Aldi) Salted Sweet Cream Butter (Sticks)",
    "brand": "Countryside Creamery (Aldi)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 714,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 0.1,
    "fat_per_100g": 81.1,
    "saturated_fat_per_100g": 50.0,
    "trans_fat_per_100g": 2.9,
    "cholesterol_per_100g": 214,
    "sodium_per_100g": 643,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-028",
    "name": "Countryside Creamery (Aldi) Unsalted Sweet Cream Butter (Sticks)",
    "brand": "Countryside Creamery (Aldi)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 714,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 0.1,
    "fat_per_100g": 81.1,
    "saturated_fat_per_100g": 50.0,
    "trans_fat_per_100g": 2.9,
    "cholesterol_per_100g": 214,
    "sodium_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-029",
    "name": "Countryside Creamery (Aldi) Butter with Canola Oil (Spreadable Tub)",
    "brand": "Countryside Creamery (Aldi)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 714,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 78.6,
    "saturated_fat_per_100g": 35.7,
    "monounsaturated_fat_per_100g": 28.6,
    "polyunsaturated_fat_per_100g": 10.7,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 107,
    "sodium_per_100g": 643,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-030",
    "name": "Countryside Creamery (Aldi) Homestyle Spread (Tub)",
    "brand": "Countryside Creamery (Aldi)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 429,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 50.0,
    "saturated_fat_per_100g": 14.3,
    "monounsaturated_fat_per_100g": 14.3,
    "polyunsaturated_fat_per_100g": 21.4,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 714,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-031",
    "name": "Countryside Creamery (Aldi) Pure Irish Butter - Salted (Gold Foil Bar / Sticks)",
    "brand": "Countryside Creamery (Aldi)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 714,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 0.1,
    "fat_per_100g": 80.0,
    "saturated_fat_per_100g": 57.1,
    "trans_fat_per_100g": 2.9,
    "cholesterol_per_100g": 214,
    "sodium_per_100g": 679,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-032",
    "name": "Countryside Creamery (Aldi) Naturally Softer Pure Irish Butter (Spreadable Tub)",
    "brand": "Countryside Creamery (Aldi)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 714,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 0.1,
    "fat_per_100g": 80.0,
    "saturated_fat_per_100g": 53.6,
    "trans_fat_per_100g": 2.9,
    "cholesterol_per_100g": 214,
    "sodium_per_100g": 679,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-033",
    "name": "Countryside Creamery (Aldi) Plant Based Butter with Olive Oil (Sticks)",
    "brand": "Countryside Creamery (Aldi)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 714,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 78.6,
    "saturated_fat_per_100g": 35.7,
    "monounsaturated_fat_per_100g": 28.6,
    "polyunsaturated_fat_per_100g": 14.3,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 714,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-oil-034",
    "name": "Countryside Creamery (Aldi) Plant Based Butter with Olive Oil (Tub)",
    "brand": "Countryside Creamery (Aldi)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 714,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 78.6,
    "saturated_fat_per_100g": 28.6,
    "monounsaturated_fat_per_100g": 35.7,
    "polyunsaturated_fat_per_100g": 14.3,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 643,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "tbsp (14g)",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-ext-001",
    "name": "Chopped Raw Pecan Pieces",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 691,
    "protein_per_100g": 9.2,
    "carbs_per_100g": 13.9,
    "fat_per_100g": 72,
    "fiber_per_100g": 9.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-ext-002",
    "name": "Toasted Sliced Blanched Almonds",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 590,
    "protein_per_100g": 21,
    "carbs_per_100g": 21,
    "fat_per_100g": 52,
    "fiber_per_100g": 11,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-ext-003",
    "name": "Chili Roasted Spicy Pistachio Kernels",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 570,
    "protein_per_100g": 20,
    "carbs_per_100g": 27,
    "fat_per_100g": 46,
    "fiber_per_100g": 10,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-ext-004",
    "name": "Dark Chocolate Covered Almonds (70% Cacao Skin)",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 540,
    "protein_per_100g": 10,
    "carbs_per_100g": 45,
    "fat_per_100g": 38,
    "fiber_per_100g": 8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "hf-ext-005",
    "name": "Dark Chocolate Covered Roasted Espresso Beans",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 510,
    "protein_per_100g": 7,
    "carbs_per_100g": 56,
    "fat_per_100g": 30,
    "fiber_per_100g": 6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 25,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "hf-ext-006",
    "name": "Pure Hazelnut Butter (100% Roasted Hazelnuts Artisana)",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 640,
    "protein_per_100g": 15,
    "carbs_per_100g": 17,
    "fat_per_100g": 61,
    "fiber_per_100g": 10,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 32,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-ext-007",
    "name": "Superfood 4-Nut Butter (Almonds, Cashews, Chia & Flax NuttZo)",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 600,
    "protein_per_100g": 19,
    "carbs_per_100g": 20,
    "fat_per_100g": 53,
    "fiber_per_100g": 9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 32,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-ext-008",
    "name": "Organic Coconut Butter / Coconut Manna (Artisana Whole Pure)",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 660,
    "protein_per_100g": 7,
    "carbs_per_100g": 24,
    "fat_per_100g": 65,
    "fiber_per_100g": 16,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "hf-ext-009",
    "name": "Cold-Pressed Virgin Hemp Seed Oil (Omega 3-6-9)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 884,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 100,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-ext-010",
    "name": "Cold-Pressed Virgin Pumpkin Seed Oil (Styrian Green)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 884,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 100,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-ext-011",
    "name": "Grass-Fed Beef Tallow (Traditional Cooking Fat Epic)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 900,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 100,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-ext-012",
    "name": "Rendered Duck Fat for High-Heat Roasting (Rougie)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 900,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 100,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-ext-013",
    "name": "Organic Cacao Butter Wafers (Pure Unrefined Navitas)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 884,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 100,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "hf-ext-014",
    "name": "Raw California Black Walnuts (Rich Earthy Wild)",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 618,
    "protein_per_100g": 24.1,
    "carbs_per_100g": 9.9,
    "fat_per_100g": 56.6,
    "fiber_per_100g": 6.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-ext-015",
    "name": "Roasted Sea Salt Watermelon Seeds (Sprouted Super Seed)",
    "category": "nuts_fats_oils",
    "sub_category": "super_seeds",
    "calories_per_100g": 600,
    "protein_per_100g": 31,
    "carbs_per_100g": 15,
    "fat_per_100g": 48,
    "fiber_per_100g": 7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-ext-016",
    "name": "Raw Whole Black Walnuts (Nutrient-Dense Wild Foraged)",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 618,
    "protein_per_100g": 24.1,
    "carbs_per_100g": 9.9,
    "fat_per_100g": 56.6,
    "fiber_per_100g": 6.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-ext-017",
    "name": "Unpasteurized Raw European Almonds (Truly Raw Non-Steam Treated)",
    "category": "nuts_fats_oils",
    "sub_category": "whole_nuts",
    "calories_per_100g": 579,
    "protein_per_100g": 21.2,
    "carbs_per_100g": 21.6,
    "fat_per_100g": 49.9,
    "fiber_per_100g": 12.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nuts_seeds"
  },
  {
    "id": "hf-ext-018",
    "name": "Coconut Cream (Rich Unsweetened Culinary Can Aroy-D)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 330,
    "protein_per_100g": 3,
    "carbs_per_100g": 6,
    "fat_per_100g": 34,
    "fiber_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 45,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "hf-ext-019",
    "name": "Cold-Pressed Camelina Wild Flax Seed Oil",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 884,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 100,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "ml",
    "storage_type": "fresh_weekly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-ext-020",
    "name": "Organic Extra Virgin Red Palm Fruit Oil (Unrefined Nutiva)",
    "category": "nuts_fats_oils",
    "sub_category": "healthy_oils",
    "calories_per_100g": 884,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 100,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "cooking_oil"
  },
  {
    "id": "hf-ext-021",
    "name": "Pistachio Butter (100% Roasted Green Pistachios)",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 590,
    "protein_per_100g": 20,
    "carbs_per_100g": 25,
    "fat_per_100g": 47,
    "fiber_per_100g": 10,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  },
  {
    "id": "hf-ext-022",
    "name": "Pecan Butter (Rich Georgia Roasted Pecans Artisana)",
    "category": "nuts_fats_oils",
    "sub_category": "nut_butters",
    "calories_per_100g": 700,
    "protein_per_100g": 9,
    "carbs_per_100g": 14,
    "fat_per_100g": 72,
    "fiber_per_100g": 9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "nut_butter"
  }
];
