import { FoodItem } from '../types';

export const PANTRY_SNACKS_DATABASE: FoodItem[] = [
  {
    "id": "sp-pro-001",
    "name": "100% Whey Protein Isolate (Unflavored Pure CFM Optimum / Dymatize)",
    "category": "snacks_pantry",
    "sub_category": "protein_powders",
    "calories_per_100g": 370,
    "protein_per_100g": 90,
    "carbs_per_100g": 1,
    "fat_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_supplement"
  },
  {
    "id": "sp-pro-002",
    "name": "100% Whey Protein Isolate (Vanilla Bean)",
    "category": "snacks_pantry",
    "sub_category": "protein_powders",
    "calories_per_100g": 375,
    "protein_per_100g": 86,
    "carbs_per_100g": 3,
    "fat_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 32,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_supplement"
  },
  {
    "id": "sp-pro-003",
    "name": "100% Whey Protein Isolate (Dutch Chocolate)",
    "category": "snacks_pantry",
    "sub_category": "protein_powders",
    "calories_per_100g": 380,
    "protein_per_100g": 84,
    "carbs_per_100g": 4,
    "fat_per_100g": 1.5,
    "fiber_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 32,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_supplement"
  },
  {
    "id": "sp-pro-004",
    "name": "100% Whey Protein Isolate (Strawberry Milkshake)",
    "category": "snacks_pantry",
    "sub_category": "protein_powders",
    "calories_per_100g": 375,
    "protein_per_100g": 85,
    "carbs_per_100g": 3.5,
    "fat_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 32,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_supplement"
  },
  {
    "id": "sp-pro-005",
    "name": "Micellar Casein Protein Powder (Slow-Release Bedtime Vanilla)",
    "category": "snacks_pantry",
    "sub_category": "protein_powders",
    "calories_per_100g": 360,
    "protein_per_100g": 80,
    "carbs_per_100g": 4,
    "fat_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 32,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_supplement"
  },
  {
    "id": "sp-pro-006",
    "name": "Micellar Casein Protein Powder (Chocolate)",
    "category": "snacks_pantry",
    "sub_category": "protein_powders",
    "calories_per_100g": 360,
    "protein_per_100g": 78,
    "carbs_per_100g": 5,
    "fat_per_100g": 1.5,
    "fiber_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 32,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_supplement"
  },
  {
    "id": "sp-pro-007",
    "name": "Egg White Protein Powder (Pure Pasteurized Albumen Now Sports)",
    "category": "snacks_pantry",
    "sub_category": "protein_powders",
    "calories_per_100g": 380,
    "protein_per_100g": 80,
    "carbs_per_100g": 4.5,
    "fat_per_100g": 0.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_supplement"
  },
  {
    "id": "sp-pro-008",
    "name": "Hydrolyzed Bovine Collagen Peptides (Type I & III Vital Proteins)",
    "category": "snacks_pantry",
    "sub_category": "protein_powders",
    "calories_per_100g": 360,
    "protein_per_100g": 90,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_supplement"
  },
  {
    "id": "sp-pro-009",
    "name": "Pure Micronized Creatine Monohydrate (Creapure Unflavored)",
    "category": "snacks_pantry",
    "sub_category": "protein_powders",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 5,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_supplement"
  },
  {
    "id": "sp-pro-010",
    "name": "L-Glutamine Powder (Pure Fermented Amino Acid)",
    "category": "snacks_pantry",
    "sub_category": "protein_powders",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 5,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_supplement"
  },
  {
    "id": "sp-snk-001",
    "name": "Organic Plain Brown Rice Cakes (Unsalted Lundberg Whole Grain)",
    "category": "snacks_pantry",
    "sub_category": "rice_cakes_snacks",
    "calories_per_100g": 387,
    "protein_per_100g": 8.2,
    "carbs_per_100g": 81.5,
    "fat_per_100g": 2.8,
    "fiber_per_100g": 4.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 9,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "grain_carb"
  },
  {
    "id": "sp-snk-002",
    "name": "Lightly Salted Brown Rice Cakes (Lundberg)",
    "category": "snacks_pantry",
    "sub_category": "rice_cakes_snacks",
    "calories_per_100g": 387,
    "protein_per_100g": 8.2,
    "carbs_per_100g": 81.5,
    "fat_per_100g": 2.8,
    "fiber_per_100g": 4.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 9,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "grain_carb"
  },
  {
    "id": "sp-snk-003",
    "name": "Sesame Tamari Brown Rice Cakes",
    "category": "snacks_pantry",
    "sub_category": "rice_cakes_snacks",
    "calories_per_100g": 390,
    "protein_per_100g": 8.5,
    "carbs_per_100g": 80,
    "fat_per_100g": 3.5,
    "fiber_per_100g": 4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 9,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "grain_carb"
  },
  {
    "id": "sp-snk-004",
    "name": "Air-Popped Popcorn (Plain Unsalted Whole Grain Kernel)",
    "category": "snacks_pantry",
    "sub_category": "rice_cakes_snacks",
    "calories_per_100g": 387,
    "protein_per_100g": 12.9,
    "carbs_per_100g": 77.9,
    "fat_per_100g": 4.5,
    "fiber_per_100g": 14.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 28,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "grain_carb"
  },
  {
    "id": "sp-snk-005",
    "name": "Whole Grain Rye Crispbread (Wasa Light 3-Ingredient)",
    "category": "snacks_pantry",
    "sub_category": "rice_cakes_snacks",
    "calories_per_100g": 334,
    "protein_per_100g": 9,
    "carbs_per_100g": 65,
    "fat_per_100g": 1.5,
    "fiber_per_100g": 20,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "bread_carb"
  },
  {
    "id": "sp-snk-006",
    "name": "Sourdough Rye Crispbread (Finn Crisp)",
    "category": "snacks_pantry",
    "sub_category": "rice_cakes_snacks",
    "calories_per_100g": 340,
    "protein_per_100g": 10,
    "carbs_per_100g": 62,
    "fat_per_100g": 2,
    "fiber_per_100g": 19,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 25,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "bread_carb"
  },
  {
    "id": "sp-snk-007",
    "name": "Roasted Seaweed Snacks / Nori Sheets (with Olive Oil & Sea Salt GimMe)",
    "category": "snacks_pantry",
    "sub_category": "rice_cakes_snacks",
    "calories_per_100g": 500,
    "protein_per_100g": 20,
    "carbs_per_100g": 20,
    "fat_per_100g": 40,
    "fiber_per_100g": 10,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 5,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "sp-snk-008",
    "name": "Wasabi Roasted Seaweed Sheets",
    "category": "snacks_pantry",
    "sub_category": "rice_cakes_snacks",
    "calories_per_100g": 500,
    "protein_per_100g": 20,
    "carbs_per_100g": 20,
    "fat_per_100g": 40,
    "fiber_per_100g": 10,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 5,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "sp-snk-009",
    "name": "Mary's Gone Crackers (Organic Seed & Brown Rice Crackers)",
    "category": "snacks_pantry",
    "sub_category": "rice_cakes_snacks",
    "calories_per_100g": 450,
    "protein_per_100g": 10,
    "carbs_per_100g": 60,
    "fat_per_100g": 18,
    "fiber_per_100g": 10,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "grain_carb"
  },
  {
    "id": "sp-snk-010",
    "name": "Simple Mills Fine Ground Sea Salt Almond Flour Crackers",
    "category": "snacks_pantry",
    "sub_category": "rice_cakes_snacks",
    "calories_per_100g": 500,
    "protein_per_100g": 10,
    "carbs_per_100g": 56,
    "fat_per_100g": 26,
    "fiber_per_100g": 6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "grain_carb"
  },
  {
    "id": "sp-cnd-001",
    "name": "Traditional French Dijon Mustard (Grey Poupon style)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 66,
    "protein_per_100g": 4.4,
    "carbs_per_100g": 5,
    "fat_per_100g": 3.5,
    "fiber_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 10,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "condiment"
  },
  {
    "id": "sp-cnd-002",
    "name": "Whole Grain Stone-Ground Mustard (Maille style)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 75,
    "protein_per_100g": 5,
    "carbs_per_100g": 6,
    "fat_per_100g": 4,
    "fiber_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 10,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "condiment"
  },
  {
    "id": "sp-cnd-003",
    "name": "Classic Yellow Mustard (Zero Calorie / Sugar Seasoning)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 60,
    "protein_per_100g": 4,
    "carbs_per_100g": 5,
    "fat_per_100g": 3,
    "fiber_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 10,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "condiment"
  },
  {
    "id": "sp-cnd-004",
    "name": "Spicy Brown Mustard (Gulden's style)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 70,
    "protein_per_100g": 4.5,
    "carbs_per_100g": 5.5,
    "fat_per_100g": 3.5,
    "fiber_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 10,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "condiment"
  },
  {
    "id": "sp-cnd-005",
    "name": "Fresh Tomato Pico de Gallo Salsa (Diced Tomato, Onion, Cilantro & Jalapeno)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 25,
    "protein_per_100g": 1,
    "carbs_per_100g": 5,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment"
  },
  {
    "id": "sp-cnd-006",
    "name": "Roasted Tomatillo Salsa Verde (Mild Green)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 35,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 6.5,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment"
  },
  {
    "id": "sp-cnd-007",
    "name": "Chipotle Smoky Roasted Red Salsa",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 35,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 6.5,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment"
  },
  {
    "id": "sp-cnd-008",
    "name": "Sriracha Hot Chili Sauce (Huy Fong style)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 100,
    "protein_per_100g": 2,
    "carbs_per_100g": 20,
    "fat_per_100g": 1,
    "fiber_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 10,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "condiment"
  },
  {
    "id": "sp-cnd-009",
    "name": "Frank's RedHot Original Cayenne Pepper Hot Sauce",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 15,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "condiment"
  },
  {
    "id": "sp-cnd-010",
    "name": "Cholula Original Mexican Hot Sauce",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 10,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "condiment"
  },
  {
    "id": "sp-cnd-011",
    "name": "Tamari Soy Sauce (Gluten-Free San-J Brewed)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 60,
    "protein_per_100g": 10.5,
    "carbs_per_100g": 5.5,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 15,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "condiment"
  },
  {
    "id": "sp-cnd-012",
    "name": "Coconut Aminos (Organic Low-Sodium Soy Free Coconut Secret)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 100,
    "protein_per_100g": 0,
    "carbs_per_100g": 24,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 15,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "condiment"
  },
  {
    "id": "sp-cnd-013",
    "name": "Organic Apple Cider Vinegar (Bragg Raw Unfiltered with Mother)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 21,
    "protein_per_100g": 0,
    "carbs_per_100g": 0.9,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 15,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "condiment"
  },
  {
    "id": "sp-cnd-014",
    "name": "Aged Balsamic Vinegar of Modena (I.G.P. Sweet Barrel Aged)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 88,
    "protein_per_100g": 0.5,
    "carbs_per_100g": 17,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 15,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "condiment"
  },
  {
    "id": "sp-cnd-015",
    "name": "Red Wine Vinegar (Aged Italian Dressing Base)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 19,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 0.3,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 15,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "condiment"
  },
  {
    "id": "sp-cnd-016",
    "name": "Unseasoned Rice Vinegar (Marukan Japanese)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 18,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 15,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "condiment"
  },
  {
    "id": "sp-cnd-017",
    "name": "Authentic Korean Kimchi (Fermented Napa Cabbage Probiotic Jongga)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 23,
    "protein_per_100g": 1.5,
    "carbs_per_100g": 3.5,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "sp-cnd-018",
    "name": "Raw Unpasteurized Sauerkraut (Wildbrine Live Cultured)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 19,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 4.3,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 2.9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "sp-cnd-019",
    "name": "Kosher Dill Pickle Spears (Naturally Fermented in Brine Claussen)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 12,
    "protein_per_100g": 0.5,
    "carbs_per_100g": 2.3,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 35,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "sp-cnd-020",
    "name": "Pickled Jalapeno Pepper Slices (Escabeche in Brine)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 27,
    "protein_per_100g": 0.8,
    "carbs_per_100g": 5,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "condiment"
  },
  {
    "id": "sp-cnd-021",
    "name": "Non-Pareil Capers (in Sea Salt Brine, Drained)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 23,
    "protein_per_100g": 2.4,
    "carbs_per_100g": 4.9,
    "fat_per_100g": 0.9,
    "fiber_per_100g": 3.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 15,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "condiment"
  },
  {
    "id": "sp-cnd-022",
    "name": "Kalamata Olive Tapenade (Minced Olives & Herbs)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 220,
    "protein_per_100g": 1.5,
    "carbs_per_100g": 4,
    "fat_per_100g": 22,
    "fiber_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "sp-cnd-023",
    "name": "Fresh Basil Pesto (Genovese Basil, Pine Nuts, Olive Oil & Parmigiano)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 420,
    "protein_per_100g": 5.5,
    "carbs_per_100g": 6,
    "fat_per_100g": 42,
    "fiber_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 20,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "sp-cnd-024",
    "name": "Vegan Cashew Basil Pesto (Dairy-Free)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 390,
    "protein_per_100g": 6,
    "carbs_per_100g": 8,
    "fat_per_100g": 38,
    "fiber_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "sp-cnd-025",
    "name": "Avocado Oil Mayonnaise (Primal Kitchen 100% Pure Avocado Oil)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 714,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 78.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 14,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "sp-cnd-026",
    "name": "Smucker's Concord Grape Jelly",
    "brand": "Smucker's",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 250,
    "protein_per_100g": 0,
    "carbs_per_100g": 65.0,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 60.0,
    "added_sugar_per_100g": 60.0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "tbsp (20g)",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment_sauce"
  },
  {
    "id": "sp-cnd-027",
    "name": "Smucker's Strawberry Jam",
    "brand": "Smucker's",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 250,
    "protein_per_100g": 0,
    "carbs_per_100g": 65.0,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 60.0,
    "added_sugar_per_100g": 60.0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "tbsp (20g)",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment_sauce"
  },
  {
    "id": "sp-cnd-028",
    "name": "Smucker's Natural Strawberry Fruit Spread",
    "brand": "Smucker's Natural",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 200,
    "protein_per_100g": 0,
    "carbs_per_100g": 50.0,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 50.0,
    "added_sugar_per_100g": 45.0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "tbsp (20g)",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment_sauce"
  },
  {
    "id": "sp-cnd-029",
    "name": "Smucker's Sugar Free Strawberry Jam (with Splenda)",
    "brand": "Smucker's Sugar Free",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 59,
    "protein_per_100g": 0,
    "carbs_per_100g": 29.4,
    "fat_per_100g": 0,
    "fiber_per_100g": 11.8,
    "sugar_per_100g": 0,
    "added_sugar_per_100g": 0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 17,
    "default_unit": "tbsp (17g)",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment_sauce"
  },
  {
    "id": "sp-cnd-030",
    "name": "Smucker's Sugar Free Concord Grape Jam (with Splenda)",
    "brand": "Smucker's Sugar Free",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 59,
    "protein_per_100g": 0,
    "carbs_per_100g": 29.4,
    "fat_per_100g": 0,
    "fiber_per_100g": 11.8,
    "sugar_per_100g": 0,
    "added_sugar_per_100g": 0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 17,
    "default_unit": "tbsp (17g)",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment_sauce"
  },
  {
    "id": "sp-cnd-031",
    "name": "Bonne Maman Strawberry Preserves",
    "brand": "Bonne Maman",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 250,
    "protein_per_100g": 0,
    "carbs_per_100g": 65.0,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 65.0,
    "added_sugar_per_100g": 60.0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "tbsp (20g)",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment_sauce"
  },
  {
    "id": "sp-cnd-032",
    "name": "Bonne Maman Four Fruits Preserves",
    "brand": "Bonne Maman",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 250,
    "protein_per_100g": 0,
    "carbs_per_100g": 65.0,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 65.0,
    "added_sugar_per_100g": 60.0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "tbsp (20g)",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment_sauce"
  },
  {
    "id": "sp-cnd-033",
    "name": "Bonne Maman Wild Blueberry Preserves",
    "brand": "Bonne Maman",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 250,
    "protein_per_100g": 0,
    "carbs_per_100g": 65.0,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 65.0,
    "added_sugar_per_100g": 60.0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "tbsp (20g)",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment_sauce"
  },
  {
    "id": "sp-cnd-034",
    "name": "Welch's Concord Grape Jelly",
    "brand": "Welch's",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 250,
    "protein_per_100g": 0,
    "carbs_per_100g": 65.0,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 55.0,
    "added_sugar_per_100g": 50.0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 25,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "tbsp (20g)",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment_sauce"
  },
  {
    "id": "sp-cnd-035",
    "name": "Polaner All Fruit Strawberry Spreadable Fruit",
    "brand": "Polaner",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 175,
    "protein_per_100g": 0,
    "carbs_per_100g": 45.0,
    "fat_per_100g": 0,
    "fiber_per_100g": 5.0,
    "sugar_per_100g": 35.0,
    "added_sugar_per_100g": 0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "tbsp (20g)",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment_sauce"
  },
  {
    "id": "sp-cnd-036",
    "name": "Meijer Concord Grape Jelly",
    "brand": "Meijer",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 250,
    "protein_per_100g": 0,
    "carbs_per_100g": 65.0,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 60.0,
    "added_sugar_per_100g": 55.0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 25,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "tbsp (20g)",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment_sauce"
  },
  {
    "id": "sp-cnd-037",
    "name": "Meijer Strawberry Jam",
    "brand": "Meijer",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 250,
    "protein_per_100g": 0,
    "carbs_per_100g": 65.0,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 60.0,
    "added_sugar_per_100g": 55.0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "tbsp (20g)",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment_sauce"
  },
  {
    "id": "sp-cnd-038",
    "name": "Meijer Sugar Free Strawberry Fruit Spread",
    "brand": "Meijer",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 50,
    "protein_per_100g": 0,
    "carbs_per_100g": 25.0,
    "fat_per_100g": 0,
    "fiber_per_100g": 5.0,
    "sugar_per_100g": 0,
    "added_sugar_per_100g": 0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "tbsp (20g)",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment_sauce"
  },
  {
    "id": "sp-cnd-039",
    "name": "Great Value (Walmart) Concord Grape Jelly",
    "brand": "Great Value (Walmart)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 250,
    "protein_per_100g": 0,
    "carbs_per_100g": 65.0,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 60.0,
    "added_sugar_per_100g": 55.0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 25,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "tbsp (20g)",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment_sauce"
  },
  {
    "id": "sp-cnd-040",
    "name": "Great Value (Walmart) Strawberry Preserves",
    "brand": "Great Value (Walmart)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 250,
    "protein_per_100g": 0,
    "carbs_per_100g": 65.0,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 60.0,
    "added_sugar_per_100g": 55.0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "tbsp (20g)",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment_sauce"
  },
  {
    "id": "sp-cnd-041",
    "name": "Great Value (Walmart) Sugar Free Strawberry Preserves",
    "brand": "Great Value (Walmart)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 50,
    "protein_per_100g": 0,
    "carbs_per_100g": 25.0,
    "fat_per_100g": 0,
    "fiber_per_100g": 5.0,
    "sugar_per_100g": 0,
    "added_sugar_per_100g": 0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "tbsp (20g)",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment_sauce"
  },
  {
    "id": "sp-cnd-042",
    "name": "Specially Selected (Aldi) Strawberry Preserves",
    "brand": "Specially Selected (Aldi)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 200,
    "protein_per_100g": 0,
    "carbs_per_100g": 50.0,
    "fat_per_100g": 0,
    "fiber_per_100g": 1.0,
    "sugar_per_100g": 45.0,
    "added_sugar_per_100g": 40.0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "tbsp (20g)",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment_sauce"
  },
  {
    "id": "sp-cnd-043",
    "name": "Grandessa / Specially Selected (Aldi) Concord Grape Jelly",
    "brand": "Grandessa (Aldi)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 250,
    "protein_per_100g": 0,
    "carbs_per_100g": 65.0,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 60.0,
    "added_sugar_per_100g": 55.0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 25,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "tbsp (20g)",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment_sauce"
  },
  {
    "id": "sp-cnd-044",
    "name": "Member's Mark (Sam's Club) Organic Strawberry Fruit Spread",
    "brand": "Member's Mark (Sam's Club)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 200,
    "protein_per_100g": 0,
    "carbs_per_100g": 50.0,
    "fat_per_100g": 0,
    "fiber_per_100g": 1.0,
    "sugar_per_100g": 45.0,
    "added_sugar_per_100g": 40.0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "tbsp (20g)",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment_sauce"
  },
  {
    "id": "sp-cnd-045",
    "name": "Kirkland Signature (Costco) Organic Strawberry Spread",
    "brand": "Kirkland Signature (Costco)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 200,
    "protein_per_100g": 0,
    "carbs_per_100g": 50.0,
    "fat_per_100g": 0,
    "fiber_per_100g": 1.0,
    "sugar_per_100g": 45.0,
    "added_sugar_per_100g": 40.0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "tbsp (20g)",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment_sauce"
  },
  {
    "id": "sp-swt-001",
    "name": "Raw Local Wildflower Honey (Unfiltered Unpasteurized)",
    "category": "snacks_pantry",
    "sub_category": "natural_sweeteners",
    "calories_per_100g": 304,
    "protein_per_100g": 0.3,
    "carbs_per_100g": 82.4,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 21,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "sweetener"
  },
  {
    "id": "sp-swt-002",
    "name": "100% Pure Grade A Amber Rich Maple Syrup (Vermont Pure)",
    "category": "snacks_pantry",
    "sub_category": "natural_sweeteners",
    "calories_per_100g": 260,
    "protein_per_100g": 0,
    "carbs_per_100g": 67,
    "fat_per_100g": 0.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "sweetener"
  },
  {
    "id": "sp-swt-003",
    "name": "Organic Blackstrap Molasses (Unsulfured Iron-Rich Plantation)",
    "category": "snacks_pantry",
    "sub_category": "natural_sweeteners",
    "calories_per_100g": 290,
    "protein_per_100g": 0,
    "carbs_per_100g": 75,
    "fat_per_100g": 0.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "sweetener"
  },
  {
    "id": "sp-swt-004",
    "name": "100% Pure Monk Fruit Extract (Zero Calorie Mogroside V Lakanto)",
    "category": "snacks_pantry",
    "sub_category": "natural_sweeteners",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 1,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "sweetener"
  },
  {
    "id": "sp-swt-005",
    "name": "Organic Stevia Leaf Liquid Drops (SweetLeaf)",
    "category": "snacks_pantry",
    "sub_category": "natural_sweeteners",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 1,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "sweetener"
  },
  {
    "id": "sp-swt-006",
    "name": "Granulated Non-GMO Erythritol Sweetener (NOW Real Food)",
    "category": "snacks_pantry",
    "sub_category": "natural_sweeteners",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 100,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 8,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "sweetener"
  },
  {
    "id": "sp-swt-007",
    "name": "Pure Allulose Natural Sweetener (0 Net Carb Wholesome)",
    "category": "snacks_pantry",
    "sub_category": "natural_sweeteners",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 100,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 8,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "sweetener"
  },
  {
    "id": "sp-swt-008",
    "name": "Mrs. Butterworth's Sugar Free Thick & Rich Pancake Syrup",
    "brand": "Mrs. Butterworth's",
    "category": "snacks_pantry",
    "sub_category": "natural_sweeteners",
    "calories_per_100g": 76,
    "protein_per_100g": 0,
    "carbs_per_100g": 18.2,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 0,
    "added_sugar_per_100g": 0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 333,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 33,
    "default_unit": "tbsp (16.5ml)",
    "storage_type": "pantry_monthly",
    "swap_group": "sweetener"
  },
  {
    "id": "sp-swt-009",
    "name": "Log Cabin Sugar Free Pancake Syrup",
    "brand": "Log Cabin",
    "category": "snacks_pantry",
    "sub_category": "natural_sweeteners",
    "calories_per_100g": 61,
    "protein_per_100g": 0,
    "carbs_per_100g": 18.2,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 0,
    "added_sugar_per_100g": 0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 394,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 33,
    "default_unit": "tbsp (16.5ml)",
    "storage_type": "pantry_monthly",
    "swap_group": "sweetener"
  },
  {
    "id": "sp-swt-010",
    "name": "Cary's Sugar Free Low Calorie Syrup",
    "brand": "Cary's",
    "category": "snacks_pantry",
    "sub_category": "natural_sweeteners",
    "calories_per_100g": 61,
    "protein_per_100g": 0,
    "carbs_per_100g": 18.2,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 0,
    "added_sugar_per_100g": 0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 333,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 33,
    "default_unit": "tbsp (16.5ml)",
    "storage_type": "pantry_monthly",
    "swap_group": "sweetener"
  },
  {
    "id": "sp-swt-011",
    "name": "Walden Farms Calorie Free Pancake Syrup",
    "brand": "Walden Farms",
    "category": "snacks_pantry",
    "sub_category": "natural_sweeteners",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 0,
    "added_sugar_per_100g": 0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 317,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "tbsp (15ml)",
    "storage_type": "pantry_monthly",
    "swap_group": "sweetener"
  },
  {
    "id": "sp-swt-012",
    "name": "ChocZero Sugar Free Maple Syrup (Monk Fruit Sweetened)",
    "brand": "ChocZero",
    "category": "snacks_pantry",
    "sub_category": "natural_sweeteners",
    "calories_per_100g": 160,
    "protein_per_100g": 0,
    "carbs_per_100g": 75.0,
    "fat_per_100g": 0,
    "fiber_per_100g": 70.0,
    "sugar_per_100g": 0,
    "added_sugar_per_100g": 0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "tbsp (20g)",
    "storage_type": "pantry_monthly",
    "swap_group": "sweetener"
  },
  {
    "id": "sp-swt-013",
    "name": "Lakanto Sugar Free Maple Flavored Syrup (Monk Fruit)",
    "brand": "Lakanto",
    "category": "snacks_pantry",
    "sub_category": "natural_sweeteners",
    "calories_per_100g": 74,
    "protein_per_100g": 0,
    "carbs_per_100g": 26.5,
    "fat_per_100g": 0,
    "fiber_per_100g": 8.8,
    "sugar_per_100g": 0,
    "added_sugar_per_100g": 0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 103,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 34,
    "default_unit": "tbsp (17ml)",
    "storage_type": "pantry_monthly",
    "swap_group": "sweetener"
  },
  {
    "id": "sp-swt-014",
    "name": "Smucker's Sugar Free Breakfast Syrup",
    "brand": "Smucker's Sugar Free",
    "category": "snacks_pantry",
    "sub_category": "natural_sweeteners",
    "calories_per_100g": 61,
    "protein_per_100g": 0,
    "carbs_per_100g": 18.2,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 0,
    "added_sugar_per_100g": 0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 348,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 33,
    "default_unit": "tbsp (16.5ml)",
    "storage_type": "pantry_monthly",
    "swap_group": "sweetener"
  },
  {
    "id": "sp-swt-015",
    "name": "Hungry Jack Sugar Free Butter Flavor Pancake Syrup",
    "brand": "Hungry Jack",
    "category": "snacks_pantry",
    "sub_category": "natural_sweeteners",
    "calories_per_100g": 61,
    "protein_per_100g": 0,
    "carbs_per_100g": 18.2,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 0,
    "added_sugar_per_100g": 0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 333,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 33,
    "default_unit": "tbsp (16.5ml)",
    "storage_type": "pantry_monthly",
    "swap_group": "sweetener"
  },
  {
    "id": "sp-swt-016",
    "name": "Torani Sugar Free Vanilla Syrup",
    "brand": "Torani",
    "category": "snacks_pantry",
    "sub_category": "natural_sweeteners",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 0,
    "added_sugar_per_100g": 0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 17,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "tbsp (15ml)",
    "storage_type": "pantry_monthly",
    "swap_group": "sweetener"
  },
  {
    "id": "sp-swt-017",
    "name": "Jordan's Skinny Syrups - Sugar Free Salted Caramel",
    "brand": "Jordan's Skinny Syrups",
    "category": "snacks_pantry",
    "sub_category": "natural_sweeteners",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 0,
    "added_sugar_per_100g": 0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 17,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "tbsp (15ml)",
    "storage_type": "pantry_monthly",
    "swap_group": "sweetener"
  },
  {
    "id": "sp-swt-018",
    "name": "Meijer Sugar Free Pancake Syrup",
    "brand": "Meijer",
    "category": "snacks_pantry",
    "sub_category": "natural_sweeteners",
    "calories_per_100g": 61,
    "protein_per_100g": 0,
    "carbs_per_100g": 18.2,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 0,
    "added_sugar_per_100g": 0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 364,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 33,
    "default_unit": "tbsp (16.5ml)",
    "storage_type": "pantry_monthly",
    "swap_group": "sweetener"
  },
  {
    "id": "sp-swt-019",
    "name": "Great Value (Walmart) Sugar Free Pancake Syrup",
    "brand": "Great Value (Walmart)",
    "category": "snacks_pantry",
    "sub_category": "natural_sweeteners",
    "calories_per_100g": 61,
    "protein_per_100g": 0,
    "carbs_per_100g": 18.2,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 0,
    "added_sugar_per_100g": 0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 364,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 33,
    "default_unit": "tbsp (16.5ml)",
    "storage_type": "pantry_monthly",
    "swap_group": "sweetener"
  },
  {
    "id": "sp-swt-020",
    "name": "Aunt Maple's (Aldi) Sugar Free Syrup",
    "brand": "Aunt Maple's (Aldi)",
    "category": "snacks_pantry",
    "sub_category": "natural_sweeteners",
    "calories_per_100g": 61,
    "protein_per_100g": 0,
    "carbs_per_100g": 18.2,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 0,
    "added_sugar_per_100g": 0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 364,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 33,
    "default_unit": "tbsp (16.5ml)",
    "storage_type": "pantry_monthly",
    "swap_group": "sweetener"
  },
  {
    "id": "sp-swt-021",
    "name": "Member's Mark (Sam's Club) Sugar Free Pancake Syrup",
    "brand": "Member's Mark (Sam's Club)",
    "category": "snacks_pantry",
    "sub_category": "natural_sweeteners",
    "calories_per_100g": 61,
    "protein_per_100g": 0,
    "carbs_per_100g": 18.2,
    "fat_per_100g": 0,
    "fiber_per_100g": 0,
    "sugar_per_100g": 0,
    "added_sugar_per_100g": 0,
    "saturated_fat_per_100g": 0,
    "trans_fat_per_100g": 0,
    "cholesterol_per_100g": 0,
    "sodium_per_100g": 364,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 33,
    "default_unit": "tbsp (16.5ml)",
    "storage_type": "pantry_monthly",
    "swap_group": "sweetener"
  },
  {
    "id": "sp-spc-001",
    "name": "Pure Ceylon True Cinnamon Powder (Cinnamomum Verum Frontier Co-op)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 247,
    "protein_per_100g": 4,
    "carbs_per_100g": 80.6,
    "fat_per_100g": 1.2,
    "fiber_per_100g": 53.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 3,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-spc-002",
    "name": "Ground Turmeric Root Powder (High Curcumin)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 312,
    "protein_per_100g": 9.7,
    "carbs_per_100g": 67.1,
    "fat_per_100g": 3.2,
    "fiber_per_100g": 22.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 3,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-spc-003",
    "name": "Smoked Spanish Paprika (Pimenton de la Vera Dulce)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 282,
    "protein_per_100g": 14.1,
    "carbs_per_100g": 54,
    "fat_per_100g": 12.9,
    "fiber_per_100g": 34.9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 3,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-spc-004",
    "name": "Ground Cumin Seed Powder (Aromatic Comino)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 375,
    "protein_per_100g": 17.8,
    "carbs_per_100g": 44.2,
    "fat_per_100g": 22.3,
    "fiber_per_100g": 10.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 3,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-spc-005",
    "name": "Ground Coriander Seed Powder",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 298,
    "protein_per_100g": 12.4,
    "carbs_per_100g": 55,
    "fat_per_100g": 17.8,
    "fiber_per_100g": 41.9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 3,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-spc-006",
    "name": "Ground Cayenne Red Pepper Powder (40,000 Heat Units)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 318,
    "protein_per_100g": 12,
    "carbs_per_100g": 56.6,
    "fat_per_100g": 17.3,
    "fiber_per_100g": 27.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 2,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-spc-007",
    "name": "Crushed Red Pepper Chili Flakes (Pizza style)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 318,
    "protein_per_100g": 12,
    "carbs_per_100g": 56.6,
    "fat_per_100g": 17.3,
    "fiber_per_100g": 27.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 2,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-spc-008",
    "name": "California Granulated Garlic Powder",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 331,
    "protein_per_100g": 16.6,
    "carbs_per_100g": 72.7,
    "fat_per_100g": 0.7,
    "fiber_per_100g": 9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 3,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-spc-009",
    "name": "Granulated Onion Powder (Toasted White Onion)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 341,
    "protein_per_100g": 10.1,
    "carbs_per_100g": 79.1,
    "fat_per_100g": 1,
    "fiber_per_100g": 15.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 3,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-spc-010",
    "name": "Freshly Cracked Tellicherry Black Pepper (Whole Peppercorn Mill)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 251,
    "protein_per_100g": 10.4,
    "carbs_per_100g": 64,
    "fat_per_100g": 3.3,
    "fiber_per_100g": 25.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 2,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-spc-011",
    "name": "Ground White Peppercorn Powder",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 296,
    "protein_per_100g": 10.4,
    "carbs_per_100g": 68.6,
    "fat_per_100g": 2.1,
    "fiber_per_100g": 26.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 2,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-spc-012",
    "name": "Italian Herb Seasoning (Oregano, Basil, Rosemary, Thyme, Marjoram, Sage)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 265,
    "protein_per_100g": 9,
    "carbs_per_100g": 50,
    "fat_per_100g": 7,
    "fiber_per_100g": 30,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 2,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-spc-013",
    "name": "Dried Greek Mountain Oregano",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 265,
    "protein_per_100g": 9,
    "carbs_per_100g": 68.9,
    "fat_per_100g": 4.3,
    "fiber_per_100g": 42.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 2,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-spc-014",
    "name": "Dried Rosemary Leaves (Crushed)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 331,
    "protein_per_100g": 4.9,
    "carbs_per_100g": 64.1,
    "fat_per_100g": 15.2,
    "fiber_per_100g": 42.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 2,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-spc-015",
    "name": "Dried French Thyme Leaves",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 276,
    "protein_per_100g": 9.1,
    "carbs_per_100g": 64.3,
    "fat_per_100g": 7.4,
    "fiber_per_100g": 37,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 2,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-spc-016",
    "name": "Ground Ginger Root Powder (Baking & Curry)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 335,
    "protein_per_100g": 9,
    "carbs_per_100g": 71.6,
    "fat_per_100g": 4.2,
    "fiber_per_100g": 14.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 2,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-spc-017",
    "name": "Ground Nutmeg Powder (Freshly Grated)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 525,
    "protein_per_100g": 5.8,
    "carbs_per_100g": 49.3,
    "fat_per_100g": 36.3,
    "fiber_per_100g": 20.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 2,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-spc-018",
    "name": "Ground Cardamom Seed Powder",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 311,
    "protein_per_100g": 10.8,
    "carbs_per_100g": 68.5,
    "fat_per_100g": 6.7,
    "fiber_per_100g": 28,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 2,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-spc-019",
    "name": "Pure Vanilla Extract (Nielsen-Massey Madagascar Bourbon)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 288,
    "protein_per_100g": 0.1,
    "carbs_per_100g": 12.7,
    "fat_per_100g": 0.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 5,
    "default_unit": "ml",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-spc-020",
    "name": "100% Pure Unsweetened Dutch-Process Cocoa Powder (Droste / Guittard)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 228,
    "protein_per_100g": 19.6,
    "carbs_per_100g": 57.9,
    "fat_per_100g": 13.7,
    "fiber_per_100g": 33.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 10,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-spc-021",
    "name": "Raw Organic Non-Alkalized Cacao Powder (High Flavonoid Navitas)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 320,
    "protein_per_100g": 25,
    "carbs_per_100g": 50,
    "fat_per_100g": 11,
    "fiber_per_100g": 30,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 10,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-spc-022",
    "name": "100% Pure Unsweetened Baking Dark Chocolate (Baker's style)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 650,
    "protein_per_100g": 13,
    "carbs_per_100g": 28,
    "fat_per_100g": 53,
    "fiber_per_100g": 17,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 15,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "sp-spc-023",
    "name": "85% Extra Dark Chocolate Bar (Lindt Excellence Rich Dark)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 585,
    "protein_per_100g": 11,
    "carbs_per_100g": 36,
    "fat_per_100g": 46,
    "fiber_per_100g": 13,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "sp-spc-024",
    "name": "90% Dark Chocolate Bar (Lindt Low Sugar High Antioxidant)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 592,
    "protein_per_100g": 10,
    "carbs_per_100g": 30,
    "fat_per_100g": 55,
    "fiber_per_100g": 15,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "sp-spc-025",
    "name": "99% Absolute Dark Chocolate Bar (Artisanal Pure Cacao)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 620,
    "protein_per_100g": 12,
    "carbs_per_100g": 20,
    "fat_per_100g": 58,
    "fiber_per_100g": 16,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "sp-ext-001",
    "name": "Whey Protein Isolate (Rich Chocolate Peanut Butter)",
    "category": "snacks_pantry",
    "sub_category": "protein_powders",
    "calories_per_100g": 385,
    "protein_per_100g": 82,
    "carbs_per_100g": 5,
    "fat_per_100g": 3,
    "fiber_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 32,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_supplement"
  },
  {
    "id": "sp-ext-002",
    "name": "Whey Protein Isolate (Cookies & Cream)",
    "category": "snacks_pantry",
    "sub_category": "protein_powders",
    "calories_per_100g": 380,
    "protein_per_100g": 83,
    "carbs_per_100g": 5,
    "fat_per_100g": 2,
    "fiber_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": false,
    "serving_size_g": 32,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "protein_supplement"
  },
  {
    "id": "sp-ext-003",
    "name": "Pickled Banana Pepper Rings (Mild in Brine)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 20,
    "protein_per_100g": 0.8,
    "carbs_per_100g": 4,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "condiment"
  },
  {
    "id": "sp-ext-004",
    "name": "Pickled Red Onions (Apple Cider Vinegar Brine)",
    "category": "snacks_pantry",
    "sub_category": "condiments_sauces",
    "calories_per_100g": 35,
    "protein_per_100g": 1,
    "carbs_per_100g": 8,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment"
  },
  {
    "id": "sp-ext-005",
    "name": "Smoked Maldon Sea Salt Flakes",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 2,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-ext-006",
    "name": "Celtic Grey Sea Salt (Mineral-Rich Sel Gris)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 2,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-ext-007",
    "name": "Himalayan Pink Rock Salt (Fine Ground)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 0,
    "protein_per_100g": 0,
    "carbs_per_100g": 0,
    "fat_per_100g": 0,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 2,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-ext-008",
    "name": "Dried Rubbed Sage Leaves",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 315,
    "protein_per_100g": 10.6,
    "carbs_per_100g": 60.7,
    "fat_per_100g": 12.8,
    "fiber_per_100g": 40.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 2,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-ext-009",
    "name": "Ground Cloves Powder (Aromatic)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 274,
    "protein_per_100g": 6,
    "carbs_per_100g": 65.5,
    "fat_per_100g": 13,
    "fiber_per_100g": 33.9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 2,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-ext-010",
    "name": "Everything Bagel Seasoning Blend (Sesame, Poppy, Garlic, Onion, Flaky Salt)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 400,
    "protein_per_100g": 15,
    "carbs_per_100g": 35,
    "fat_per_100g": 25,
    "fiber_per_100g": 15,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 3,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  },
  {
    "id": "sp-ext-011",
    "name": "Taco Seasoning Blend (Cumin, Chili, Garlic, Paprika, Oregano)",
    "category": "snacks_pantry",
    "sub_category": "spices_seasonings",
    "calories_per_100g": 280,
    "protein_per_100g": 10,
    "carbs_per_100g": 50,
    "fat_per_100g": 5,
    "fiber_per_100g": 20,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 5,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "spice"
  }
];
