import { FoodItem } from '../types';

export const PANTRY_SNACKS_DATABASE: FoodItem[] = [
  // ==========================================
  // PROTEIN POWDERS & RTDS (15+ items)
  // ==========================================
  {
    id: 'sp-pow-001',
    name: '100% Whey Protein Isolate (Vanilla)',
    category: 'snacks_pantry',
    sub_category: 'protein_powders',
    calories_per_100g: 370,
    protein_per_100g: 85.0,
    carbs_per_100g: 3.0,
    fat_per_100g: 1.5,
    fiber_per_100g: 0.5,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'powder_protein',
  },
  {
    id: 'sp-pow-002',
    name: '100% Whey Protein Isolate (Chocolate)',
    category: 'snacks_pantry',
    sub_category: 'protein_powders',
    calories_per_100g: 375,
    protein_per_100g: 83.0,
    carbs_per_100g: 4.0,
    fat_per_100g: 2.0,
    fiber_per_100g: 1.0,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 32,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'powder_protein',
  },
  {
    id: 'sp-pow-003',
    name: 'Plant-Based Pea & Brown Rice Protein Powder',
    category: 'snacks_pantry',
    sub_category: 'protein_powders',
    calories_per_100g: 380,
    protein_per_100g: 78.0,
    carbs_per_100g: 6.0,
    fat_per_100g: 4.0,
    fiber_per_100g: 3.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 35,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'powder_protein',
  },
  {
    id: 'sp-pow-004',
    name: 'Micellar Casein Protein Powder (Slow Digesting Bedtime)',
    category: 'snacks_pantry',
    sub_category: 'protein_powders',
    calories_per_100g: 360,
    protein_per_100g: 80.0,
    carbs_per_100g: 4.0,
    fat_per_100g: 1.5,
    fiber_per_100g: 0.5,
    is_gluten_free: true,
    is_dairy_free: false,
    serving_size_g: 34,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'powder_protein',
  },
  {
    id: 'sp-pow-005',
    name: 'Hydrolyzed Collagen Peptides (Unflavored)',
    category: 'snacks_pantry',
    sub_category: 'protein_powders',
    calories_per_100g: 360,
    protein_per_100g: 90.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 20,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'powder_protein',
  },

  // ==========================================
  // RICE CAKES & CRISPBREADS (10+ items)
  // ==========================================
  {
    id: 'sp-snk-001',
    name: 'Organic Plain Brown Rice Cakes (Lundberg)',
    category: 'snacks_pantry',
    sub_category: 'rice_cakes_snacks',
    calories_per_100g: 387,
    protein_per_100g: 8.0,
    carbs_per_100g: 82.0,
    fat_per_100g: 2.8,
    fiber_per_100g: 4.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 20,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'sp-snk-002',
    name: 'Lightly Salted Rice Cakes (Quaker)',
    category: 'snacks_pantry',
    sub_category: 'rice_cakes_snacks',
    calories_per_100g: 388,
    protein_per_100g: 7.8,
    carbs_per_100g: 83.0,
    fat_per_100g: 2.5,
    fiber_per_100g: 3.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 18,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'sp-snk-003',
    name: 'Wasa Whole Grain Sourdough Crispbread',
    category: 'snacks_pantry',
    sub_category: 'rice_cakes_snacks',
    calories_per_100g: 333,
    protein_per_100g: 10.0,
    carbs_per_100g: 63.3,
    fat_per_100g: 1.7,
    fiber_per_100g: 20.0,
    is_gluten_free: false,
    is_dairy_free: true,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },

  // ==========================================
  // SAUCES, SALSAS & CONDIMENTS (15+ items)
  // ==========================================
  {
    id: 'sp-hum-001',
    name: 'Classic Garlic Hummus (Chickpeas & Tahini)',
    category: 'snacks_pantry',
    sub_category: 'condiments_sauces',
    calories_per_100g: 166,
    protein_per_100g: 7.9,
    carbs_per_100g: 14.3,
    fat_per_100g: 9.6,
    fiber_per_100g: 6.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'healthy_fat',
  },
  {
    id: 'sp-sal-001',
    name: 'Fresh Mild / Medium Tomato Salsa',
    category: 'snacks_pantry',
    sub_category: 'condiments_sauces',
    calories_per_100g: 36,
    protein_per_100g: 1.5,
    carbs_per_100g: 7.0,
    fat_per_100g: 0.2,
    fiber_per_100g: 1.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 50,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },
  {
    id: 'sp-sau-001',
    name: 'Dijon Mustard (Grey Poupon)',
    category: 'snacks_pantry',
    sub_category: 'condiments_sauces',
    calories_per_100g: 66,
    protein_per_100g: 4.4,
    carbs_per_100g: 5.5,
    fat_per_100g: 4.0,
    fiber_per_100g: 3.3,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 10,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'cooking_fat',
  },
  {
    id: 'sp-sau-002',
    name: 'Sriracha Chili Hot Sauce (Huy Fong)',
    category: 'snacks_pantry',
    sub_category: 'condiments_sauces',
    calories_per_100g: 100,
    protein_per_100g: 2.0,
    carbs_per_100g: 20.0,
    fat_per_100g: 1.0,
    fiber_per_100g: 2.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 10,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'cooking_fat',
  },
  {
    id: 'sp-sau-003',
    name: 'Aged Balsamic Vinegar of Modena',
    category: 'snacks_pantry',
    sub_category: 'condiments_sauces',
    calories_per_100g: 88,
    protein_per_100g: 0.5,
    carbs_per_100g: 17.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 15,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'fruit_carb',
  },

  // ==========================================
  // NATURAL SWEETENERS (10+ items)
  // ==========================================
  {
    id: 'sp-sw-001',
    name: 'Pure Raw Wildflower Honey',
    category: 'snacks_pantry',
    sub_category: 'natural_sweeteners',
    calories_per_100g: 304,
    protein_per_100g: 0.3,
    carbs_per_100g: 82.4,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.2,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 20,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'sp-sw-002',
    name: '100% Pure Grade A Amber Maple Syrup',
    category: 'snacks_pantry',
    sub_category: 'natural_sweeteners',
    calories_per_100g: 260,
    protein_per_100g: 0.0,
    carbs_per_100g: 67.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 20,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'fruit_carb',
  },
  {
    id: 'sp-sw-003',
    name: '100% Pure Organic Liquid Stevia Extract (0 Cal)',
    category: 'snacks_pantry',
    sub_category: 'natural_sweeteners',
    calories_per_100g: 0,
    protein_per_100g: 0.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 1,
    default_unit: 'ml',
    storage_type: 'pantry_monthly',
    swap_group: 'beverage',
  },

  // ==========================================
  // SPICES & PURE COCOA (10+ items)
  // ==========================================
  {
    id: 'sp-spc-001',
    name: 'Ceylon Cinnamon Ground (True Cinnamon)',
    category: 'snacks_pantry',
    sub_category: 'spices_seasonings',
    calories_per_100g: 247,
    protein_per_100g: 4.0,
    carbs_per_100g: 80.0,
    fat_per_100g: 1.2,
    fiber_per_100g: 53.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 5,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'fiber_veg',
  },
  {
    id: 'sp-spc-002',
    name: '100% Pure Unsweetened Raw Cacao Powder',
    category: 'snacks_pantry',
    sub_category: 'spices_seasonings',
    calories_per_100g: 228,
    protein_per_100g: 19.6,
    carbs_per_100g: 57.9,
    fat_per_100g: 13.7,
    fiber_per_100g: 33.2,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 15,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'healthy_fat',
  },
  {
    id: 'sp-spc-003',
    name: 'Dark Chocolate 85% Cocoa (Lindt / Ghirardelli)',
    category: 'snacks_pantry',
    sub_category: 'spices_seasonings',
    calories_per_100g: 580,
    protein_per_100g: 9.0,
    carbs_per_100g: 36.0,
    fat_per_100g: 46.0,
    fiber_per_100g: 11.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 25,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'healthy_fat',
  },
];
