import { FoodItem } from '../types';

export const PLANT_PROTEIN_DATABASE: FoodItem[] = [
  {
    "id": "pp-tof-001",
    "name": "Organic Extra Firm Tofu (Pressed Raw)",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 94,
    "protein_per_100g": 10,
    "carbs_per_100g": 2.3,
    "fat_per_100g": 5.3,
    "fiber_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-tof-002",
    "name": "Extra Firm Tofu (Baked Cubes with Tamari)",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 135,
    "protein_per_100g": 14.5,
    "carbs_per_100g": 3.2,
    "fat_per_100g": 7.5,
    "fiber_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-tof-003",
    "name": "Organic Firm Tofu (Water Packed)",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 83,
    "protein_per_100g": 9,
    "carbs_per_100g": 1.9,
    "fat_per_100g": 4.8,
    "fiber_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-tof-004",
    "name": "Organic Medium Firm Tofu",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 72,
    "protein_per_100g": 7.8,
    "carbs_per_100g": 2,
    "fat_per_100g": 4,
    "fiber_per_100g": 0.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-tof-005",
    "name": "Silken Tofu (Smooth Japanese Style)",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 55,
    "protein_per_100g": 5.8,
    "carbs_per_100g": 2,
    "fat_per_100g": 2.7,
    "fiber_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-tof-006",
    "name": "Sprouted Super Firm Tofu (Wildwood High Protein)",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 130,
    "protein_per_100g": 15,
    "carbs_per_100g": 2,
    "fat_per_100g": 7,
    "fiber_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-tof-007",
    "name": "Smoked Tofu Block (Firm European style)",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 145,
    "protein_per_100g": 16,
    "carbs_per_100g": 2.5,
    "fat_per_100g": 8,
    "fiber_per_100g": 1.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-tof-008",
    "name": "Five-Spice Pressed Tofu / Dougan (Chinese Deli style)",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 150,
    "protein_per_100g": 16.5,
    "carbs_per_100g": 3,
    "fat_per_100g": 8.2,
    "fiber_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-tof-009",
    "name": "Tofu Skins / Fresh Yuba Sheets (Braised)",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 140,
    "protein_per_100g": 14,
    "carbs_per_100g": 4,
    "fat_per_100g": 7.5,
    "fiber_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-tof-010",
    "name": "Organic Soy Tempeh (Steamed / Sauteed Cubes)",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 192,
    "protein_per_100g": 20.3,
    "carbs_per_100g": 7.6,
    "fat_per_100g": 10.8,
    "fiber_per_100g": 4.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-tof-011",
    "name": "Organic Flax & Multi-Grain Tempeh",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 205,
    "protein_per_100g": 19.5,
    "carbs_per_100g": 9,
    "fat_per_100g": 11.5,
    "fiber_per_100g": 5,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-tof-012",
    "name": "Smoked Tempeh Strips (Maple Bacon style Lightlife)",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 220,
    "protein_per_100g": 21,
    "carbs_per_100g": 11,
    "fat_per_100g": 10.5,
    "fiber_per_100g": 4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 60,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-tof-013",
    "name": "Hemp & Black Bean Tempeh",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 195,
    "protein_per_100g": 20,
    "carbs_per_100g": 8,
    "fat_per_100g": 10,
    "fiber_per_100g": 5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-tof-014",
    "name": "Edamame Beans (Shelled Steamed)",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 121,
    "protein_per_100g": 11.9,
    "carbs_per_100g": 8.9,
    "fat_per_100g": 5.2,
    "fiber_per_100g": 5.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-tof-015",
    "name": "Edamame in Pods (Steamed with Flaky Sea Salt)",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 122,
    "protein_per_100g": 11,
    "carbs_per_100g": 9,
    "fat_per_100g": 5,
    "fiber_per_100g": 5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-tof-016",
    "name": "Dry Roasted Edamame (Crunchy Sea Salt Snack)",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 440,
    "protein_per_100g": 43,
    "carbs_per_100g": 28,
    "fat_per_100g": 16,
    "fiber_per_100g": 17,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-bns-001",
    "name": "Organic Black Beans (Cooked / Canned Low Sodium)",
    "category": "plant_protein",
    "sub_category": "beans",
    "calories_per_100g": 132,
    "protein_per_100g": 8.9,
    "carbs_per_100g": 23.7,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 8.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-bns-002",
    "name": "Dark Red Kidney Beans (Cooked / Canned)",
    "category": "plant_protein",
    "sub_category": "beans",
    "calories_per_100g": 127,
    "protein_per_100g": 8.7,
    "carbs_per_100g": 22.8,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 7.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-bns-003",
    "name": "Pinto Beans (Cooked Low Sodium)",
    "category": "plant_protein",
    "sub_category": "beans",
    "calories_per_100g": 143,
    "protein_per_100g": 9,
    "carbs_per_100g": 26.2,
    "fat_per_100g": 0.7,
    "fiber_per_100g": 9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-bns-004",
    "name": "Cannellini Beans / White Kidney Beans (Cooked)",
    "category": "plant_protein",
    "sub_category": "beans",
    "calories_per_100g": 139,
    "protein_per_100g": 9.7,
    "carbs_per_100g": 25.1,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 6.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-bns-005",
    "name": "Great Northern White Beans (Cooked)",
    "category": "plant_protein",
    "sub_category": "beans",
    "calories_per_100g": 118,
    "protein_per_100g": 8.3,
    "carbs_per_100g": 21.1,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-bns-006",
    "name": "Navy Beans (Cooked from Dry)",
    "category": "plant_protein",
    "sub_category": "beans",
    "calories_per_100g": 140,
    "protein_per_100g": 8.2,
    "carbs_per_100g": 26,
    "fat_per_100g": 0.6,
    "fiber_per_100g": 9.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-bns-007",
    "name": "Lupini Beans (Pickled High-Protein Brami style)",
    "category": "plant_protein",
    "sub_category": "beans",
    "calories_per_100g": 119,
    "protein_per_100g": 15.6,
    "carbs_per_100g": 9.9,
    "fat_per_100g": 2.9,
    "fiber_per_100g": 4.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-bns-008",
    "name": "Black-Eyed Peas / Cowpeas (Cooked)",
    "category": "plant_protein",
    "sub_category": "beans",
    "calories_per_100g": 116,
    "protein_per_100g": 7.7,
    "carbs_per_100g": 20.8,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 6.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-bns-009",
    "name": "Adzuki Red Beans (Cooked Japanese Small Red)",
    "category": "plant_protein",
    "sub_category": "beans",
    "calories_per_100g": 128,
    "protein_per_100g": 7.5,
    "carbs_per_100g": 24.8,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 7.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-bns-010",
    "name": "Refried Black Beans (Fat-Free Vegetarian)",
    "category": "plant_protein",
    "sub_category": "beans",
    "calories_per_100g": 90,
    "protein_per_100g": 6,
    "carbs_per_100g": 16,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-bns-011",
    "name": "Refried Pinto Beans (Traditional Low-Fat)",
    "category": "plant_protein",
    "sub_category": "beans",
    "calories_per_100g": 100,
    "protein_per_100g": 6,
    "carbs_per_100g": 17,
    "fat_per_100g": 1.2,
    "fiber_per_100g": 5.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-bns-012",
    "name": "Mung Beans (Cooked Green Whole)",
    "category": "plant_protein",
    "sub_category": "beans",
    "calories_per_100g": 105,
    "protein_per_100g": 7,
    "carbs_per_100g": 19.2,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 7.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-bns-013",
    "name": "Fava Beans / Broad Beans (Cooked Tender)",
    "category": "plant_protein",
    "sub_category": "beans",
    "calories_per_100g": 110,
    "protein_per_100g": 7.6,
    "carbs_per_100g": 19.5,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 5.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-bns-014",
    "name": "Lima Beans / Butter Beans (Steamed Baby)",
    "category": "plant_protein",
    "sub_category": "beans",
    "calories_per_100g": 115,
    "protein_per_100g": 6.8,
    "carbs_per_100g": 20.9,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 4.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-chk-001",
    "name": "Garbanzo Beans / Chickpeas (Cooked / Canned)",
    "category": "plant_protein",
    "sub_category": "chickpeas_lentils",
    "calories_per_100g": 164,
    "protein_per_100g": 8.9,
    "carbs_per_100g": 27.4,
    "fat_per_100g": 2.6,
    "fiber_per_100g": 7.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-chk-002",
    "name": "Roasted Crunchy Chickpeas (Sea Salt Snack Biena style)",
    "category": "plant_protein",
    "sub_category": "chickpeas_lentils",
    "calories_per_100g": 380,
    "protein_per_100g": 18,
    "carbs_per_100g": 58,
    "fat_per_100g": 8,
    "fiber_per_100g": 15,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 40,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-chk-003",
    "name": "Traditional Hummus (Chickpeas, Tahini, Olive Oil & Lemon)",
    "category": "plant_protein",
    "sub_category": "chickpeas_lentils",
    "calories_per_100g": 166,
    "protein_per_100g": 7.9,
    "carbs_per_100g": 14.3,
    "fat_per_100g": 9.6,
    "fiber_per_100g": 6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 60,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "healthy_fat"
  },
  {
    "id": "pp-chk-004",
    "name": "Brown Lentils (Boiled / Cooked)",
    "category": "plant_protein",
    "sub_category": "chickpeas_lentils",
    "calories_per_100g": 116,
    "protein_per_100g": 9,
    "carbs_per_100g": 20.1,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 7.9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-chk-005",
    "name": "French Green Lentils / Puy Lentils (Cooked Firm)",
    "category": "plant_protein",
    "sub_category": "chickpeas_lentils",
    "calories_per_100g": 115,
    "protein_per_100g": 9.5,
    "carbs_per_100g": 19.5,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 8.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-chk-006",
    "name": "Red Split Lentils (Boiled Indian Masoor Dal)",
    "category": "plant_protein",
    "sub_category": "chickpeas_lentils",
    "calories_per_100g": 110,
    "protein_per_100g": 8.8,
    "carbs_per_100g": 18.5,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-chk-007",
    "name": "Black Beluga Lentils (Cooked Caviar-style)",
    "category": "plant_protein",
    "sub_category": "chickpeas_lentils",
    "calories_per_100g": 120,
    "protein_per_100g": 10.2,
    "carbs_per_100g": 19.8,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 8.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-chk-008",
    "name": "Yellow Split Peas (Cooked Dal)",
    "category": "plant_protein",
    "sub_category": "chickpeas_lentils",
    "calories_per_100g": 118,
    "protein_per_100g": 8.3,
    "carbs_per_100g": 21.1,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 8.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-chk-009",
    "name": "Green Split Peas (Cooked Hearty Soup)",
    "category": "plant_protein",
    "sub_category": "chickpeas_lentils",
    "calories_per_100g": 118,
    "protein_per_100g": 8.3,
    "carbs_per_100g": 21.1,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 8.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-chk-010",
    "name": "Chana Dal (Bengal Split Gram Cooked)",
    "category": "plant_protein",
    "sub_category": "chickpeas_lentils",
    "calories_per_100g": 130,
    "protein_per_100g": 9,
    "carbs_per_100g": 22,
    "fat_per_100g": 1.5,
    "fiber_per_100g": 8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-chk-011",
    "name": "Toor Dal / Pigeon Peas (Cooked Yellow Dal)",
    "category": "plant_protein",
    "sub_category": "chickpeas_lentils",
    "calories_per_100g": 125,
    "protein_per_100g": 8.5,
    "carbs_per_100g": 21.5,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 7.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-stn-001",
    "name": "Organic Seitan Strips (Traditional Wheat Meat)",
    "category": "plant_protein",
    "sub_category": "seitan_wheat",
    "calories_per_100g": 148,
    "protein_per_100g": 28,
    "carbs_per_100g": 5.5,
    "fat_per_100g": 1.5,
    "fiber_per_100g": 1,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-stn-002",
    "name": "Vital Wheat Gluten Flour (75% Protein Bob's Red Mill)",
    "category": "plant_protein",
    "sub_category": "seitan_wheat",
    "calories_per_100g": 370,
    "protein_per_100g": 75,
    "carbs_per_100g": 13.8,
    "fat_per_100g": 1.9,
    "fiber_per_100g": 1.5,
    "is_gluten_free": false,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-stn-003",
    "name": "Textured Vegetable Protein / TVP (Dry Minced Granules)",
    "category": "plant_protein",
    "sub_category": "seitan_wheat",
    "calories_per_100g": 325,
    "protein_per_100g": 52,
    "carbs_per_100g": 33,
    "fat_per_100g": 1,
    "fiber_per_100g": 17.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 35,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-stn-004",
    "name": "Soy Curls (Butler Dehydrated Whole Soy Strips)",
    "category": "plant_protein",
    "sub_category": "seitan_wheat",
    "calories_per_100g": 330,
    "protein_per_100g": 37,
    "carbs_per_100g": 33,
    "fat_per_100g": 11,
    "fiber_per_100g": 22,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-stn-005",
    "name": "Organic Baked Falafel Patties (Chickpea & Herb)",
    "category": "plant_protein",
    "sub_category": "seitan_wheat",
    "calories_per_100g": 215,
    "protein_per_100g": 8.5,
    "carbs_per_100g": 24,
    "fat_per_100g": 9.5,
    "fiber_per_100g": 5.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 90,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-stn-006",
    "name": "Plant-Based Ground (Beyond Meat / Impossible style Raw)",
    "category": "plant_protein",
    "sub_category": "seitan_wheat",
    "calories_per_100g": 220,
    "protein_per_100g": 17,
    "carbs_per_100g": 5,
    "fat_per_100g": 14,
    "fiber_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 113,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-stn-007",
    "name": "Plant-Based Burger Patty (Cooked Seared)",
    "category": "plant_protein",
    "sub_category": "seitan_wheat",
    "calories_per_100g": 250,
    "protein_per_100g": 19,
    "carbs_per_100g": 6,
    "fat_per_100g": 16,
    "fiber_per_100g": 3.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 113,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-stn-008",
    "name": "Plant-Based Italian Sausage Link",
    "category": "plant_protein",
    "sub_category": "seitan_wheat",
    "calories_per_100g": 220,
    "protein_per_100g": 16,
    "carbs_per_100g": 5,
    "fat_per_100g": 15,
    "fiber_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-spr-001",
    "name": "Nutritional Yeast Flakes (Fortified with Vitamin B12 Bragg style)",
    "category": "plant_protein",
    "sub_category": "super_plant_proteins",
    "calories_per_100g": 380,
    "protein_per_100g": 50,
    "carbs_per_100g": 33,
    "fat_per_100g": 5,
    "fiber_per_100g": 25,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 15,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-spr-002",
    "name": "Raw Shelled Hemp Hearts (Manitoba Harvest Complete Protein)",
    "category": "plant_protein",
    "sub_category": "super_plant_proteins",
    "calories_per_100g": 553,
    "protein_per_100g": 31.6,
    "carbs_per_100g": 8.7,
    "fat_per_100g": 48.8,
    "fiber_per_100g": 4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-spr-003",
    "name": "Organic Spirulina Powder (Pure Blue-Green Algae)",
    "category": "plant_protein",
    "sub_category": "super_plant_proteins",
    "calories_per_100g": 290,
    "protein_per_100g": 57.5,
    "carbs_per_100g": 23.9,
    "fat_per_100g": 7.7,
    "fiber_per_100g": 3.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 10,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-spr-004",
    "name": "Organic Chlorella Powder (Broken Cell Wall)",
    "category": "plant_protein",
    "sub_category": "super_plant_proteins",
    "calories_per_100g": 320,
    "protein_per_100g": 58,
    "carbs_per_100g": 17,
    "fat_per_100g": 9,
    "fiber_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 10,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-spr-005",
    "name": "Organic Pea Protein Isolate (Unflavored 85% Protein)",
    "category": "plant_protein",
    "sub_category": "super_plant_proteins",
    "calories_per_100g": 380,
    "protein_per_100g": 82,
    "carbs_per_100g": 3,
    "fat_per_100g": 6,
    "fiber_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-spr-006",
    "name": "Organic Brown Rice Protein Powder (80% Protein)",
    "category": "plant_protein",
    "sub_category": "super_plant_proteins",
    "calories_per_100g": 390,
    "protein_per_100g": 80,
    "carbs_per_100g": 5,
    "fat_per_100g": 4.5,
    "fiber_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-spr-007",
    "name": "Pumpkin Seed Protein Powder (Organic Cold-Pressed)",
    "category": "plant_protein",
    "sub_category": "super_plant_proteins",
    "calories_per_100g": 385,
    "protein_per_100g": 65,
    "carbs_per_100g": 10,
    "fat_per_100g": 9,
    "fiber_per_100g": 8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-ext-001",
    "name": "Heirloom Christmas Lima Beans (Cooked Nutty)",
    "category": "plant_protein",
    "sub_category": "beans",
    "calories_per_100g": 125,
    "protein_per_100g": 7.8,
    "carbs_per_100g": 22,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-ext-002",
    "name": "Mayocoba / Peruano Beans (Cooked Creamy Yellow)",
    "category": "plant_protein",
    "sub_category": "beans",
    "calories_per_100g": 130,
    "protein_per_100g": 8.5,
    "carbs_per_100g": 23.5,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 7.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-ext-003",
    "name": "French Flageolet Beans (Delicate Green Tender)",
    "category": "plant_protein",
    "sub_category": "beans",
    "calories_per_100g": 112,
    "protein_per_100g": 7,
    "carbs_per_100g": 20,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 5.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-ext-004",
    "name": "Anasazi Heirloom Beans (Cooked Sweet Southwest)",
    "category": "plant_protein",
    "sub_category": "beans",
    "calories_per_100g": 135,
    "protein_per_100g": 9,
    "carbs_per_100g": 24,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-ext-005",
    "name": "Black Soybean Edamame (High Protein Low Carb)",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 135,
    "protein_per_100g": 13.5,
    "carbs_per_100g": 6,
    "fat_per_100g": 6,
    "fiber_per_100g": 5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-ext-006",
    "name": "Organic Black Soybean Tofu",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 98,
    "protein_per_100g": 11,
    "carbs_per_100g": 2.5,
    "fat_per_100g": 5.5,
    "fiber_per_100g": 1.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-ext-007",
    "name": "Sweet Potato & Herb Baked Tofu Cutlets",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 140,
    "protein_per_100g": 13,
    "carbs_per_100g": 8,
    "fat_per_100g": 6,
    "fiber_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-ext-008",
    "name": "Sprouted Sesame & Garlic Tofu Block",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 125,
    "protein_per_100g": 14,
    "carbs_per_100g": 3,
    "fat_per_100g": 6.5,
    "fiber_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-ext-009",
    "name": "Sriracha Roasted Crunchy Chickpeas",
    "category": "plant_protein",
    "sub_category": "chickpeas_lentils",
    "calories_per_100g": 380,
    "protein_per_100g": 18,
    "carbs_per_100g": 58,
    "fat_per_100g": 8,
    "fiber_per_100g": 15,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 40,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-ext-010",
    "name": "Spanish Pardina Brown Lentils (Cooked)",
    "category": "plant_protein",
    "sub_category": "chickpeas_lentils",
    "calories_per_100g": 115,
    "protein_per_100g": 9.2,
    "carbs_per_100g": 19.8,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 7.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-ext-011",
    "name": "Urad Dal (Split Black Gram Cooked White Dal)",
    "category": "plant_protein",
    "sub_category": "chickpeas_lentils",
    "calories_per_100g": 120,
    "protein_per_100g": 8.5,
    "carbs_per_100g": 20.5,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-ext-012",
    "name": "Whole Moong Dal (Cooked Green Gram)",
    "category": "plant_protein",
    "sub_category": "chickpeas_lentils",
    "calories_per_100g": 110,
    "protein_per_100g": 7.5,
    "carbs_per_100g": 19.5,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 7.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-ext-013",
    "name": "Organic Sacha Inchi Seed Protein Powder",
    "category": "plant_protein",
    "sub_category": "super_plant_proteins",
    "calories_per_100g": 390,
    "protein_per_100g": 60,
    "carbs_per_100g": 15,
    "fat_per_100g": 10,
    "fiber_per_100g": 12,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-ext-014",
    "name": "Watermelon Seed Protein Powder (Sprouted)",
    "category": "plant_protein",
    "sub_category": "super_plant_proteins",
    "calories_per_100g": 400,
    "protein_per_100g": 65,
    "carbs_per_100g": 10,
    "fat_per_100g": 12,
    "fiber_per_100g": 8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-ext-015",
    "name": "Organic Sunflower Seed Protein Powder",
    "category": "plant_protein",
    "sub_category": "super_plant_proteins",
    "calories_per_100g": 380,
    "protein_per_100g": 55,
    "carbs_per_100g": 18,
    "fat_per_100g": 9,
    "fiber_per_100g": 14,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-ext-016",
    "name": "Lupin Bean Flour (Low Carb High Protein Flour)",
    "category": "plant_protein",
    "sub_category": "super_plant_proteins",
    "calories_per_100g": 370,
    "protein_per_100g": 40,
    "carbs_per_100g": 40,
    "fat_per_100g": 9,
    "fiber_per_100g": 37,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-ext-017",
    "name": "White Shiro Miso Paste (Sweet Fermented Soy)",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 198,
    "protein_per_100g": 12,
    "carbs_per_100g": 26,
    "fat_per_100g": 4.5,
    "fiber_per_100g": 5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment"
  },
  {
    "id": "pp-ext-018",
    "name": "Red Aka Miso Paste (Aged Robust Fermented Soy)",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 210,
    "protein_per_100g": 13,
    "carbs_per_100g": 24,
    "fat_per_100g": 6,
    "fiber_per_100g": 5.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment"
  },
  {
    "id": "pp-ext-019",
    "name": "Natto (Traditional Japanese Fermented Soybeans with Nattokinase)",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 212,
    "protein_per_100g": 17.7,
    "carbs_per_100g": 14.4,
    "fat_per_100g": 11,
    "fiber_per_100g": 5.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-ext-020",
    "name": "Sprouted Fresh Mung Bean Sprouts (Raw Crisp)",
    "category": "plant_protein",
    "sub_category": "beans",
    "calories_per_100g": 30,
    "protein_per_100g": 3,
    "carbs_per_100g": 5.9,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "pp-ext-021",
    "name": "Sprouted Fresh Soybean Sprouts (Kongnamul)",
    "category": "plant_protein",
    "sub_category": "beans",
    "calories_per_100g": 122,
    "protein_per_100g": 13.1,
    "carbs_per_100g": 9.6,
    "fat_per_100g": 6.7,
    "fiber_per_100g": 1.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "pp-ext-022",
    "name": "Sprouted Brown Lentils (Fresh Salad Sprouts)",
    "category": "plant_protein",
    "sub_category": "chickpeas_lentils",
    "calories_per_100g": 106,
    "protein_per_100g": 9,
    "carbs_per_100g": 22.1,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "legume_carb"
  },
  {
    "id": "pp-ext-023",
    "name": "Organic Golden Pea Protein Flakes (Crunchy Granola Add-in)",
    "category": "plant_protein",
    "sub_category": "super_plant_proteins",
    "calories_per_100g": 380,
    "protein_per_100g": 80,
    "carbs_per_100g": 5,
    "fat_per_100g": 4,
    "fiber_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-ext-024",
    "name": "Okara (Nutritious Soy Fiber Pulp from Fresh Tofu Making)",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 77,
    "protein_per_100g": 3.2,
    "carbs_per_100g": 12.5,
    "fat_per_100g": 1.7,
    "fiber_per_100g": 4.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "pp-ext-025",
    "name": "Soy Protein Isolate (Unflavored 90% Protein)",
    "category": "plant_protein",
    "sub_category": "super_plant_proteins",
    "calories_per_100g": 388,
    "protein_per_100g": 88,
    "carbs_per_100g": 1,
    "fat_per_100g": 3.4,
    "fiber_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-ext-026",
    "name": "Dry Roasted Salted Soy Nuts",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 450,
    "protein_per_100g": 40,
    "carbs_per_100g": 30,
    "fat_per_100g": 20,
    "fiber_per_100g": 8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegan_protein"
  },
  {
    "id": "pp-ext-027",
    "name": "Yellow Shinshu Miso Paste (Medium Fermented)",
    "category": "plant_protein",
    "sub_category": "tofu_tempeh",
    "calories_per_100g": 200,
    "protein_per_100g": 12.5,
    "carbs_per_100g": 25,
    "fat_per_100g": 5,
    "fiber_per_100g": 5.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "condiment"
  },
  {
    "id": "pp-ext-028",
    "name": "Hemp & Flax Plant Protein Burger (Dr. Praeger style)",
    "category": "plant_protein",
    "sub_category": "seitan_wheat",
    "calories_per_100g": 180,
    "protein_per_100g": 15,
    "carbs_per_100g": 10,
    "fat_per_100g": 8,
    "fiber_per_100g": 6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegan_protein"
  }
];
