import { FoodItem } from '../types';

export const PLANT_PROTEIN_DATABASE: FoodItem[] = [
  // ==========================================
  // TOFU, TEMPEH & EDAMAME (15+ items)
  // ==========================================
  {
    id: 'pp-tof-001',
    name: 'Organic Extra Firm Tofu (Pressed)',
    category: 'plant_protein',
    sub_category: 'tofu_tempeh',
    calories_per_100g: 83,
    protein_per_100g: 10.0,
    carbs_per_100g: 1.5,
    fat_per_100g: 5.0,
    fiber_per_100g: 0.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'plant_protein',
  },
  {
    id: 'pp-tof-002',
    name: 'High Protein Super Firm Tofu (Wildwood / Trader Joe)',
    category: 'plant_protein',
    sub_category: 'tofu_tempeh',
    calories_per_100g: 130,
    protein_per_100g: 14.5,
    carbs_per_100g: 2.5,
    fat_per_100g: 7.0,
    fiber_per_100g: 1.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'plant_protein',
  },
  {
    id: 'pp-tof-003',
    name: 'Organic Soy Tempeh (Steamed / Baked)',
    category: 'plant_protein',
    sub_category: 'tofu_tempeh',
    calories_per_100g: 192,
    protein_per_100g: 20.3,
    carbs_per_100g: 7.6,
    fat_per_100g: 10.8,
    fiber_per_100g: 5.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'plant_protein',
  },
  {
    id: 'pp-tof-004',
    name: 'Steamed Edamame (Shelled Soybeans)',
    category: 'plant_protein',
    sub_category: 'tofu_tempeh',
    calories_per_100g: 121,
    protein_per_100g: 11.9,
    carbs_per_100g: 8.9,
    fat_per_100g: 5.2,
    fiber_per_100g: 5.2,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'plant_protein',
  },
  {
    id: 'pp-tof-005',
    name: 'Edamame in Pods (Steamed with Sea Salt)',
    category: 'plant_protein',
    sub_category: 'tofu_tempeh',
    calories_per_100g: 80,
    protein_per_100g: 8.0,
    carbs_per_100g: 6.0,
    fat_per_100g: 3.5,
    fiber_per_100g: 4.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'plant_protein',
  },
  {
    id: 'pp-tof-006',
    name: 'Silken Tofu (Mori-Nu Firm)',
    category: 'plant_protein',
    sub_category: 'tofu_tempeh',
    calories_per_100g: 55,
    protein_per_100g: 5.8,
    carbs_per_100g: 1.8,
    fat_per_100g: 2.7,
    fiber_per_100g: 0.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'plant_protein',
  },

  // ==========================================
  // BEANS & LEGUMES (15+ items)
  // ==========================================
  {
    id: 'pp-ben-001',
    name: 'Cooked Black Beans (Simmered)',
    category: 'plant_protein',
    sub_category: 'beans',
    calories_per_100g: 132,
    protein_per_100g: 8.9,
    carbs_per_100g: 23.7,
    fat_per_100g: 0.5,
    fiber_per_100g: 8.7,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'pp-ben-002',
    name: 'Cooked Pinto Beans',
    category: 'plant_protein',
    sub_category: 'beans',
    calories_per_100g: 143,
    protein_per_100g: 9.0,
    carbs_per_100g: 26.2,
    fat_per_100g: 0.7,
    fiber_per_100g: 9.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'pp-ben-003',
    name: 'Cooked Red Kidney Beans',
    category: 'plant_protein',
    sub_category: 'beans',
    calories_per_100g: 127,
    protein_per_100g: 8.7,
    carbs_per_100g: 22.8,
    fat_per_100g: 0.5,
    fiber_per_100g: 7.4,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'pp-ben-004',
    name: 'Cooked Cannellini / White Kidney Beans',
    category: 'plant_protein',
    sub_category: 'beans',
    calories_per_100g: 139,
    protein_per_100g: 9.7,
    carbs_per_100g: 25.1,
    fat_per_100g: 0.5,
    fiber_per_100g: 6.3,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },

  // ==========================================
  // CHICKPEAS & LENTILS (15+ items)
  // ==========================================
  {
    id: 'pp-chk-001',
    name: 'Cooked Chickpeas / Garbanzo Beans',
    category: 'plant_protein',
    sub_category: 'chickpeas_lentils',
    calories_per_100g: 164,
    protein_per_100g: 8.9,
    carbs_per_100g: 27.4,
    fat_per_100g: 2.6,
    fiber_per_100g: 7.6,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'pp-len-001',
    name: 'Cooked Red Lentils',
    category: 'plant_protein',
    sub_category: 'chickpeas_lentils',
    calories_per_100g: 116,
    protein_per_100g: 9.0,
    carbs_per_100g: 20.0,
    fat_per_100g: 0.4,
    fiber_per_100g: 7.9,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'pp-len-002',
    name: 'Cooked Brown / Green Lentils',
    category: 'plant_protein',
    sub_category: 'chickpeas_lentils',
    calories_per_100g: 115,
    protein_per_100g: 9.0,
    carbs_per_100g: 20.1,
    fat_per_100g: 0.4,
    fiber_per_100g: 7.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },
  {
    id: 'pp-len-003',
    name: 'Cooked French Green Puy Lentils',
    category: 'plant_protein',
    sub_category: 'chickpeas_lentils',
    calories_per_100g: 120,
    protein_per_100g: 9.5,
    carbs_per_100g: 21.0,
    fat_per_100g: 0.5,
    fiber_per_100g: 8.2,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'complex_carb',
  },

  // ==========================================
  // SEITAN & SUPER PROTEINS (10+ items)
  // ==========================================
  {
    id: 'pp-stn-001',
    name: 'Organic Traditional Seitan Strips (Wheat Gluten)',
    category: 'plant_protein',
    sub_category: 'seitan_wheat',
    calories_per_100g: 140,
    protein_per_100g: 25.0,
    carbs_per_100g: 5.0,
    fat_per_100g: 1.5,
    fiber_per_100g: 1.0,
    is_gluten_free: false,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pp-nut-001',
    name: 'Nutritional Yeast Flakes (Fortified B-Complex)',
    category: 'plant_protein',
    sub_category: 'super_plant_proteins',
    calories_per_100g: 380,
    protein_per_100g: 50.0,
    carbs_per_100g: 35.0,
    fat_per_100g: 5.0,
    fiber_per_100g: 25.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 15,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'powder_protein',
  },
  {
    id: 'pp-nut-002',
    name: 'Organic Raw Shelled Hemp Hearts',
    category: 'plant_protein',
    sub_category: 'super_plant_proteins',
    calories_per_100g: 553,
    protein_per_100g: 31.6,
    carbs_per_100g: 8.7,
    fat_per_100g: 48.8,
    fiber_per_100g: 4.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 30,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'healthy_fat',
  },
];
