import { FoodItem } from '../types';

export const POULTRY_MEATS_DATABASE: FoodItem[] = [
  // ==========================================
  // CHICKEN (40+ items)
  // ==========================================
  {
    id: 'pm-chk-001',
    name: 'Boneless Skinless Chicken Breast (Raw)',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 120,
    protein_per_100g: 26.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-002',
    name: 'Grilled Chicken Breast (Skinless)',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 165,
    protein_per_100g: 31.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 3.6,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-003',
    name: 'Baked Herb-Crusted Chicken Breast',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 170,
    protein_per_100g: 30.5,
    carbs_per_100g: 1.0,
    fat_per_100g: 4.0,
    fiber_per_100g: 0.2,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-004',
    name: 'Poached / Shredded Chicken Breast',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 158,
    protein_per_100g: 32.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 2.8,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 140,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-005',
    name: 'Chicken Tenderloins (Raw)',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 110,
    protein_per_100g: 24.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-006',
    name: 'Grilled Chicken Tenderloins',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 155,
    protein_per_100g: 30.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 3.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-007',
    name: 'Boneless Skinless Chicken Thigh (Raw)',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 130,
    protein_per_100g: 20.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 5.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-008',
    name: 'Roasted Chicken Thigh (Skinless, Trimmed)',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 177,
    protein_per_100g: 24.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 8.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-009',
    name: 'Rotisserie Chicken Breast (Skin Removed)',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 140,
    protein_per_100g: 28.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 3.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-010',
    name: 'Rotisserie Chicken Dark Meat (Skin Removed)',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 185,
    protein_per_100g: 25.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 9.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-011',
    name: '99/1 Extra Lean Ground Chicken Breast',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 115,
    protein_per_100g: 25.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-012',
    name: '92/8 Lean Ground Chicken',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 150,
    protein_per_100g: 21.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 7.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-013',
    name: 'Smoked Pulled Chicken (Dry Rubbed)',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 160,
    protein_per_100g: 29.0,
    carbs_per_100g: 1.0,
    fat_per_100g: 4.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 140,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-014',
    name: 'Chicken Drumstick (Boiled / Baked, Skinless)',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 161,
    protein_per_100g: 24.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 6.2,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-015',
    name: 'Organic Pasture-Raised Chicken Breast',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 122,
    protein_per_100g: 26.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.6,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-016',
    name: 'Chicken Liver (Pan-Seared Lean)',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 167,
    protein_per_100g: 24.5,
    carbs_per_100g: 0.9,
    fat_per_100g: 6.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-017',
    name: 'Air-Fried Crispy Skinless Chicken Breast',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 168,
    protein_per_100g: 31.5,
    carbs_per_100g: 0.5,
    fat_per_100g: 4.2,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-chk-018',
    name: 'Lean Chicken Sausage (Italian Herb, Nitrate-Free)',
    category: 'poultry_meat',
    sub_category: 'chicken',
    calories_per_100g: 150,
    protein_per_100g: 18.0,
    carbs_per_100g: 2.0,
    fat_per_100g: 7.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },

  // ==========================================
  // TURKEY (20+ items)
  // ==========================================
  {
    id: 'pm-trk-001',
    name: '93/7 Lean Ground Turkey',
    category: 'poultry_meat',
    sub_category: 'turkey',
    calories_per_100g: 152,
    protein_per_100g: 22.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 7.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-trk-002',
    name: '99/1 Extra Lean Ground Turkey Breast',
    category: 'poultry_meat',
    sub_category: 'turkey',
    calories_per_100g: 110,
    protein_per_100g: 26.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-trk-003',
    name: 'Turkey Breast Cutlet (Raw)',
    category: 'poultry_meat',
    sub_category: 'turkey',
    calories_per_100g: 114,
    protein_per_100g: 24.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-trk-004',
    name: 'Oven Roasted Turkey Breast (Cooked)',
    category: 'poultry_meat',
    sub_category: 'turkey',
    calories_per_100g: 135,
    protein_per_100g: 29.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 2.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-trk-005',
    name: 'Turkey Tenderloin (Roasted)',
    category: 'poultry_meat',
    sub_category: 'turkey',
    calories_per_100g: 125,
    protein_per_100g: 27.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 1.8,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-trk-006',
    name: '85/15 Ground Turkey',
    category: 'poultry_meat',
    sub_category: 'turkey',
    calories_per_100g: 210,
    protein_per_100g: 19.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 14.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-trk-007',
    name: 'Uncured Turkey Bacon (Cooked)',
    category: 'poultry_meat',
    sub_category: 'turkey',
    calories_per_100g: 218,
    protein_per_100g: 28.0,
    carbs_per_100g: 2.0,
    fat_per_100g: 11.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 60,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-trk-008',
    name: 'Turkey Breakfast Sausage Links (Nitrate Free)',
    category: 'poultry_meat',
    sub_category: 'turkey',
    calories_per_100g: 170,
    protein_per_100g: 19.0,
    carbs_per_100g: 1.0,
    fat_per_100g: 10.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 90,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-trk-009',
    name: 'Smoked Turkey Drumstick Meat (Skinless)',
    category: 'poultry_meat',
    sub_category: 'turkey',
    calories_per_100g: 155,
    protein_per_100g: 26.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 5.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 140,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },

  // ==========================================
  // BEEF & STEAKS (25+ items)
  // ==========================================
  {
    id: 'pm-bf-001',
    name: 'Grass-Fed Top Sirloin Steak (Trimmed, Cooked)',
    category: 'poultry_meat',
    sub_category: 'beef',
    calories_per_100g: 183,
    protein_per_100g: 27.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 8.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 170,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-bf-002',
    name: 'Beef Tenderloin / Filet Mignon (Trimmed, Cooked)',
    category: 'poultry_meat',
    sub_category: 'beef',
    calories_per_100g: 190,
    protein_per_100g: 26.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 9.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-bf-003',
    name: 'Flank Steak (Lean Trimmed, Grilled)',
    category: 'poultry_meat',
    sub_category: 'beef',
    calories_per_100g: 192,
    protein_per_100g: 28.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 8.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-bf-004',
    name: 'Top Round Steak / London Broil (Broiled)',
    category: 'poultry_meat',
    sub_category: 'beef',
    calories_per_100g: 165,
    protein_per_100g: 29.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 4.8,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-bf-005',
    name: 'NY Strip Steak (Choice, Trimmed)',
    category: 'poultry_meat',
    sub_category: 'beef',
    calories_per_100g: 215,
    protein_per_100g: 26.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 12.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 170,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-bf-006',
    name: 'Flat Iron Steak (Top Blade, Grilled)',
    category: 'poultry_meat',
    sub_category: 'beef',
    calories_per_100g: 185,
    protein_per_100g: 27.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 8.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-bf-007',
    name: 'Skirt Steak (Trimmed Lean, Grilled)',
    category: 'poultry_meat',
    sub_category: 'beef',
    calories_per_100g: 205,
    protein_per_100g: 26.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 11.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-bf-008',
    name: 'Beef Eye of Round Roast (Cooked)',
    category: 'poultry_meat',
    sub_category: 'beef',
    calories_per_100g: 155,
    protein_per_100g: 30.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 3.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-bf-009',
    name: 'Grass-Fed Beef Liver (Pan-Seared)',
    category: 'poultry_meat',
    sub_category: 'beef',
    calories_per_100g: 175,
    protein_per_100g: 26.0,
    carbs_per_100g: 5.0,
    fat_per_100g: 4.8,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-bf-010',
    name: 'Ribeye Steak (Lean Portion, Trimmed)',
    category: 'poultry_meat',
    sub_category: 'beef',
    calories_per_100g: 245,
    protein_per_100g: 24.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 16.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 170,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fatty_protein',
  },

  // ==========================================
  // LEAN GROUND MEATS (15+ items)
  // ==========================================
  {
    id: 'pm-grd-001',
    name: '96/4 Extra Lean Ground Beef',
    category: 'poultry_meat',
    sub_category: 'ground_meats',
    calories_per_100g: 133,
    protein_per_100g: 22.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 4.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-grd-002',
    name: '93/7 Lean Ground Beef',
    category: 'poultry_meat',
    sub_category: 'ground_meats',
    calories_per_100g: 150,
    protein_per_100g: 21.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 7.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-grd-003',
    name: '90/10 Lean Ground Beef',
    category: 'poultry_meat',
    sub_category: 'ground_meats',
    calories_per_100g: 176,
    protein_per_100g: 20.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 10.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-grd-004',
    name: 'Lean Ground Bison (90/10)',
    category: 'poultry_meat',
    sub_category: 'ground_meats',
    calories_per_100g: 146,
    protein_per_100g: 20.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 7.2,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-grd-005',
    name: '90/10 Lean Ground Pork',
    category: 'poultry_meat',
    sub_category: 'ground_meats',
    calories_per_100g: 172,
    protein_per_100g: 19.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 10.2,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-grd-006',
    name: 'Lean Ground Elk Meat (90/10)',
    category: 'poultry_meat',
    sub_category: 'ground_meats',
    calories_per_100g: 135,
    protein_per_100g: 22.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 4.8,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-grd-007',
    name: 'Lean Ground Venison (90/10)',
    category: 'poultry_meat',
    sub_category: 'ground_meats',
    calories_per_100g: 140,
    protein_per_100g: 22.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 5.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },

  // ==========================================
  // PORK (15+ items)
  // ==========================================
  {
    id: 'pm-prk-001',
    name: 'Pork Tenderloin Roast (Trimmed, Cooked)',
    category: 'poultry_meat',
    sub_category: 'pork',
    calories_per_100g: 143,
    protein_per_100g: 26.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 3.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-prk-002',
    name: 'Center Cut Pork Loin Chops (Boneless, Lean)',
    category: 'poultry_meat',
    sub_category: 'pork',
    calories_per_100g: 165,
    protein_per_100g: 25.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 6.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-prk-003',
    name: 'Canadian Bacon (Lean Back Bacon)',
    category: 'poultry_meat',
    sub_category: 'pork',
    calories_per_100g: 157,
    protein_per_100g: 20.5,
    carbs_per_100g: 1.5,
    fat_per_100g: 7.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 60,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-prk-004',
    name: 'Pork Sirloin Roast (Lean, Cooked)',
    category: 'poultry_meat',
    sub_category: 'pork',
    calories_per_100g: 175,
    protein_per_100g: 27.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 7.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-prk-005',
    name: 'Prosciutto di Parma (Lean Slices)',
    category: 'poultry_meat',
    sub_category: 'pork',
    calories_per_100g: 220,
    protein_per_100g: 28.0,
    carbs_per_100g: 0.5,
    fat_per_100g: 12.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 40,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },

  // ==========================================
  // BISON, LAMB & GAME (15+ items)
  // ==========================================
  {
    id: 'pm-gam-001',
    name: 'Bison Top Sirloin Steak',
    category: 'poultry_meat',
    sub_category: 'game_lamb',
    calories_per_100g: 145,
    protein_per_100g: 28.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 3.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 160,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-gam-002',
    name: 'Bison Ribeye Steak (Lean Trimmed)',
    category: 'poultry_meat',
    sub_category: 'game_lamb',
    calories_per_100g: 175,
    protein_per_100g: 26.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 7.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 170,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-gam-003',
    name: 'Venison Steak / Medallions',
    category: 'poultry_meat',
    sub_category: 'game_lamb',
    calories_per_100g: 120,
    protein_per_100g: 23.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 2.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-gam-004',
    name: 'Lamb Loin Chops (Lean Trimmed, Grilled)',
    category: 'poultry_meat',
    sub_category: 'game_lamb',
    calories_per_100g: 198,
    protein_per_100g: 24.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 10.8,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-gam-005',
    name: 'Leg of Lamb (Roasted Lean Meat)',
    category: 'poultry_meat',
    sub_category: 'game_lamb',
    calories_per_100g: 180,
    protein_per_100g: 25.5,
    carbs_per_100g: 0.0,
    fat_per_100g: 8.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-gam-006',
    name: 'Elk Steak (Grilled Lean)',
    category: 'poultry_meat',
    sub_category: 'game_lamb',
    calories_per_100g: 145,
    protein_per_100g: 30.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 2.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-gam-007',
    name: 'Duck Breast (Skinless, Pan-Seared)',
    category: 'poultry_meat',
    sub_category: 'game_lamb',
    calories_per_100g: 140,
    protein_per_100g: 28.0,
    carbs_per_100g: 0.0,
    fat_per_100g: 2.5,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 140,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },

  // ==========================================
  // DELI & PREPARED MEATS (15+ items)
  // ==========================================
  {
    id: 'pm-dli-001',
    name: 'Oven-Roasted Deli Turkey Breast (Low Sodium)',
    category: 'poultry_meat',
    sub_category: 'deli_meats',
    calories_per_100g: 104,
    protein_per_100g: 17.5,
    carbs_per_100g: 4.0,
    fat_per_100g: 2.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-dli-002',
    name: 'Lean Roast Beef Deli Slices',
    category: 'poultry_meat',
    sub_category: 'deli_meats',
    calories_per_100g: 125,
    protein_per_100g: 20.0,
    carbs_per_100g: 2.0,
    fat_per_100g: 4.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-dli-003',
    name: 'Black Forest Ham Deli Slices (97% Fat Free)',
    category: 'poultry_meat',
    sub_category: 'deli_meats',
    calories_per_100g: 110,
    protein_per_100g: 18.0,
    carbs_per_100g: 2.5,
    fat_per_100g: 3.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-dli-004',
    name: 'Deli Chicken Breast (Smoked, Sliced)',
    category: 'poultry_meat',
    sub_category: 'deli_meats',
    calories_per_100g: 105,
    protein_per_100g: 18.5,
    carbs_per_100g: 2.0,
    fat_per_100g: 2.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'lean_protein',
  },
  {
    id: 'pm-dli-005',
    name: 'Beef Biltong / Jerky (Sugar-Free, High Protein)',
    category: 'poultry_meat',
    sub_category: 'deli_meats',
    calories_per_100g: 260,
    protein_per_100g: 50.0,
    carbs_per_100g: 2.0,
    fat_per_100g: 6.0,
    fiber_per_100g: 0.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 50,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'lean_protein',
  },
];
