import { FoodItem } from '../types';

export const POULTRY_MEATS_DATABASE: FoodItem[] = [
  {
    "id": "pm-chk-001",
    "name": "Boneless Skinless Chicken Breast (Raw)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 120,
    "protein_per_100g": 22.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 2.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-002",
    "name": "Boneless Skinless Chicken Breast (Grilled)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 165,
    "protein_per_100g": 31,
    "carbs_per_100g": 0,
    "fat_per_100g": 3.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-003",
    "name": "Boneless Skinless Chicken Breast (Oven Roasted)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 165,
    "protein_per_100g": 31,
    "carbs_per_100g": 0,
    "fat_per_100g": 3.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-004",
    "name": "Boneless Skinless Chicken Breast (Poached / Boiled Shredded)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 158,
    "protein_per_100g": 30.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 3.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-005",
    "name": "Organic Free-Range Chicken Breast Fillet",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 120,
    "protein_per_100g": 23,
    "carbs_per_100g": 0,
    "fat_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-006",
    "name": "Chicken Tenderloins / Tenders (Raw)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 115,
    "protein_per_100g": 23,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-007",
    "name": "Chicken Tenderloins (Grilled)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 160,
    "protein_per_100g": 31.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-008",
    "name": "Boneless Skinless Chicken Thigh (Raw)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 130,
    "protein_per_100g": 20,
    "carbs_per_100g": 0,
    "fat_per_100g": 5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-chk-009",
    "name": "Boneless Skinless Chicken Thigh (Grilled)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 175,
    "protein_per_100g": 26,
    "carbs_per_100g": 0,
    "fat_per_100g": 7.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-chk-010",
    "name": "Boneless Skinless Chicken Thigh (Roasted)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 175,
    "protein_per_100g": 26,
    "carbs_per_100g": 0,
    "fat_per_100g": 7.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-chk-011",
    "name": "Bone-In Skin-On Chicken Thigh (Raw)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 220,
    "protein_per_100g": 17.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 16,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 200,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-chk-012",
    "name": "Bone-In Skin-On Chicken Thigh (Crispy Roasted)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 235,
    "protein_per_100g": 24,
    "carbs_per_100g": 0,
    "fat_per_100g": 15,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-chk-013",
    "name": "Chicken Drumsticks (Bone-In Skinless Raw)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 120,
    "protein_per_100g": 19,
    "carbs_per_100g": 0,
    "fat_per_100g": 4.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-chk-014",
    "name": "Chicken Drumsticks (Roasted Skinless)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 165,
    "protein_per_100g": 27,
    "carbs_per_100g": 0,
    "fat_per_100g": 5.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-chk-015",
    "name": "Chicken Drumsticks (Crispy Skin Roasted)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 215,
    "protein_per_100g": 24.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 12.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-chk-016",
    "name": "Chicken Whole Wings (Raw)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 210,
    "protein_per_100g": 18,
    "carbs_per_100g": 0,
    "fat_per_100g": 15,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-chk-017",
    "name": "Chicken Wings (Party Flats & Drumettes, Baked Dry Rub)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 240,
    "protein_per_100g": 26,
    "carbs_per_100g": 0,
    "fat_per_100g": 15,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-chk-018",
    "name": "Chicken Wings (Air-Fried Naked Crisp)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 225,
    "protein_per_100g": 27,
    "carbs_per_100g": 0,
    "fat_per_100g": 13,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-chk-019",
    "name": "Rotisserie Chicken Breast (Skinless Pulled)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 145,
    "protein_per_100g": 28,
    "carbs_per_100g": 0,
    "fat_per_100g": 3.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-020",
    "name": "Rotisserie Chicken Dark Meat (Skinless Pulled)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 180,
    "protein_per_100g": 25,
    "carbs_per_100g": 0,
    "fat_per_100g": 8.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-chk-021",
    "name": "Ground Chicken Breast (98% Lean Raw)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 110,
    "protein_per_100g": 23,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-022",
    "name": "Ground Chicken Breast (98% Lean Cooked Crumbles)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 150,
    "protein_per_100g": 31,
    "carbs_per_100g": 0,
    "fat_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-023",
    "name": "Ground Chicken (92% Lean / 8% Fat Raw)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 150,
    "protein_per_100g": 19.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-024",
    "name": "Ground Chicken (92% Lean Cooked)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 190,
    "protein_per_100g": 26,
    "carbs_per_100g": 0,
    "fat_per_100g": 9.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-025",
    "name": "Ground Chicken (85% Lean / 15% Fat Raw)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 190,
    "protein_per_100g": 17.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 13,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-chk-026",
    "name": "Chicken Gizzards (Braised / Simmered)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 145,
    "protein_per_100g": 26.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 3.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-027",
    "name": "Chicken Livers (Sauteed / Pan-Seared)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 170,
    "protein_per_100g": 24.5,
    "carbs_per_100g": 1,
    "fat_per_100g": 6.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-028",
    "name": "Chicken Hearts (Grilled Skewers)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 185,
    "protein_per_100g": 26,
    "carbs_per_100g": 0.5,
    "fat_per_100g": 8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-029",
    "name": "Smoked Pulled Chicken Breast (BBQ Style Unsauced)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 155,
    "protein_per_100g": 30,
    "carbs_per_100g": 0,
    "fat_per_100g": 3.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-030",
    "name": "Blackened Chicken Breast (Cajun Spiced Grilled)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 168,
    "protein_per_100g": 30.5,
    "carbs_per_100g": 0.5,
    "fat_per_100g": 4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-031",
    "name": "Lemon Herb Marinated Chicken Cutlet",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 160,
    "protein_per_100g": 29.5,
    "carbs_per_100g": 1,
    "fat_per_100g": 4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-032",
    "name": "Chicken Shawarma Slices (Spiced Grilled Thigh)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 195,
    "protein_per_100g": 25,
    "carbs_per_100g": 1.5,
    "fat_per_100g": 9.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-chk-033",
    "name": "Chicken Souvlaki Skewers (Oregano Garlic Lemon)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 165,
    "protein_per_100g": 29,
    "carbs_per_100g": 0.8,
    "fat_per_100g": 4.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-034",
    "name": "Cornish Game Hen (Half Hen Roasted)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 190,
    "protein_per_100g": 23,
    "carbs_per_100g": 0,
    "fat_per_100g": 10.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 200,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-chk-035",
    "name": "Capon Meat (Roast Rooster Dark & White)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 210,
    "protein_per_100g": 27,
    "carbs_per_100g": 0,
    "fat_per_100g": 11,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-chk-036",
    "name": "Chicken Sausage Links (Italian Style Lean)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 150,
    "protein_per_100g": 19,
    "carbs_per_100g": 2,
    "fat_per_100g": 7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-037",
    "name": "Chicken Apple Breakfast Sausage Links",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 160,
    "protein_per_100g": 16,
    "carbs_per_100g": 4,
    "fat_per_100g": 8.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 85,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-038",
    "name": "Spicy Jalapeno Chicken Sausage",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 150,
    "protein_per_100g": 18,
    "carbs_per_100g": 2,
    "fat_per_100g": 7.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-039",
    "name": "Spinach & Feta Chicken Sausage",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 155,
    "protein_per_100g": 18.5,
    "carbs_per_100g": 2.5,
    "fat_per_100g": 7.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-chk-040",
    "name": "Organic Chicken Bone-In Whole Roasted (White Meat)",
    "category": "poultry_meat",
    "sub_category": "chicken",
    "calories_per_100g": 155,
    "protein_per_100g": 29,
    "carbs_per_100g": 0,
    "fat_per_100g": 3.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-tur-001",
    "name": "Boneless Skinless Turkey Breast (Raw Cutlets)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 110,
    "protein_per_100g": 24,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-tur-002",
    "name": "Boneless Turkey Breast (Oven Roasted Sliced)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 135,
    "protein_per_100g": 30,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-tur-003",
    "name": "Ground Turkey (99% Fat-Free Breast Raw)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 105,
    "protein_per_100g": 24.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-tur-004",
    "name": "Ground Turkey (99% Fat-Free Breast Cooked)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 140,
    "protein_per_100g": 32,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-tur-005",
    "name": "Ground Turkey (93% Lean / 7% Fat Raw)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 150,
    "protein_per_100g": 19.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-tur-006",
    "name": "Ground Turkey (93% Lean Cooked Crumbles)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 190,
    "protein_per_100g": 27,
    "carbs_per_100g": 0,
    "fat_per_100g": 9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-tur-007",
    "name": "Ground Turkey (85% Lean / 15% Fat Raw)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 195,
    "protein_per_100g": 17.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 14,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-tur-008",
    "name": "Ground Turkey (85% Lean Cooked)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 230,
    "protein_per_100g": 24,
    "carbs_per_100g": 0,
    "fat_per_100g": 15,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-tur-009",
    "name": "Turkey Tenderloin (Raw Roast)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 115,
    "protein_per_100g": 24,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-tur-010",
    "name": "Turkey Tenderloin (Grilled Medallions)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 145,
    "protein_per_100g": 30.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 2.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-tur-011",
    "name": "Bone-In Turkey Drumstick (Roasted Skinless)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 155,
    "protein_per_100g": 27,
    "carbs_per_100g": 0,
    "fat_per_100g": 5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 200,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-tur-012",
    "name": "Bone-In Turkey Thigh (Roasted Skinless)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 170,
    "protein_per_100g": 26,
    "carbs_per_100g": 0,
    "fat_per_100g": 7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-tur-013",
    "name": "Smoked Turkey Breast Slices (Deli Style Low Sodium)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 105,
    "protein_per_100g": 22,
    "carbs_per_100g": 1.5,
    "fat_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-tur-014",
    "name": "Oven-Roasted Turkey Breast Slices (Deli Cuts)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 105,
    "protein_per_100g": 22,
    "carbs_per_100g": 1,
    "fat_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-tur-015",
    "name": "Mesquite Wood Smoked Turkey Breast",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 110,
    "protein_per_100g": 22.5,
    "carbs_per_100g": 1.5,
    "fat_per_100g": 1.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-tur-016",
    "name": "Honey Smoked Turkey Breast Slices",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 115,
    "protein_per_100g": 21,
    "carbs_per_100g": 4,
    "fat_per_100g": 1.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-tur-017",
    "name": "Cured Turkey Bacon (Pan-Crisped Strips)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 300,
    "protein_per_100g": 28,
    "carbs_per_100g": 2,
    "fat_per_100g": 20,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 40,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-tur-018",
    "name": "Uncured All-Natural Turkey Bacon (Baked)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 280,
    "protein_per_100g": 26,
    "carbs_per_100g": 1.5,
    "fat_per_100g": 18.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 40,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-tur-019",
    "name": "Turkey Breakfast Sausage Patties (Cooked)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 200,
    "protein_per_100g": 22,
    "carbs_per_100g": 1,
    "fat_per_100g": 12,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 75,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-tur-020",
    "name": "Turkey Italian Sweet Sausage Links",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 160,
    "protein_per_100g": 18,
    "carbs_per_100g": 2,
    "fat_per_100g": 8.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-tur-021",
    "name": "Turkey Italian Hot & Spicy Sausage Links",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 160,
    "protein_per_100g": 18,
    "carbs_per_100g": 2,
    "fat_per_100g": 8.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-tur-022",
    "name": "Turkey Kielbasa / Smoked Sausage (Lean Polish)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 170,
    "protein_per_100g": 17,
    "carbs_per_100g": 3,
    "fat_per_100g": 10,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-tur-023",
    "name": "Turkey Meatballs (Baked Lean Seasoned)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 175,
    "protein_per_100g": 20,
    "carbs_per_100g": 6,
    "fat_per_100g": 7.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-tur-024",
    "name": "Turkey Jerky (Teriyaki Flavor)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 280,
    "protein_per_100g": 36,
    "carbs_per_100g": 22,
    "fat_per_100g": 3.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 35,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-tur-025",
    "name": "Turkey Jerky (Black Pepper & Sea Salt)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 270,
    "protein_per_100g": 40,
    "carbs_per_100g": 14,
    "fat_per_100g": 3.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 35,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-tur-026",
    "name": "Smoked Turkey Wings (Braised Seasoned)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 210,
    "protein_per_100g": 25,
    "carbs_per_100g": 0,
    "fat_per_100g": 12,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-tur-027",
    "name": "Smoked Turkey Leg (Theme Park Style Jumbo)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 215,
    "protein_per_100g": 26,
    "carbs_per_100g": 0,
    "fat_per_100g": 12,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 250,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-tur-028",
    "name": "Turkey Gizzards (Simmered Tender)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 150,
    "protein_per_100g": 27,
    "carbs_per_100g": 0,
    "fat_per_100g": 4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-tur-029",
    "name": "Turkey Liver (Pan-Seared with Onions)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 175,
    "protein_per_100g": 25,
    "carbs_per_100g": 2,
    "fat_per_100g": 7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-tur-030",
    "name": "Roast Whole Turkey (Dark & White Meat Mix)",
    "category": "poultry_meat",
    "sub_category": "turkey",
    "calories_per_100g": 160,
    "protein_per_100g": 28,
    "carbs_per_100g": 0,
    "fat_per_100g": 5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-bef-001",
    "name": "USDA Choice Beef Top Sirloin Steak (Lean Trimmed, Raw)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 135,
    "protein_per_100g": 22.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 4.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 200,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-002",
    "name": "USDA Choice Beef Top Sirloin Steak (Grilled Medium-Rare)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 185,
    "protein_per_100g": 30.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 6.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-003",
    "name": "USDA Prime Beef Tenderloin / Filet Mignon (Raw)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 160,
    "protein_per_100g": 22,
    "carbs_per_100g": 0,
    "fat_per_100g": 7.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-004",
    "name": "USDA Prime Beef Tenderloin / Filet Mignon (Pan-Seared)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 210,
    "protein_per_100g": 29.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 10,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-005",
    "name": "Grass-Fed Beef Tenderloin Steak (Pasture-Raised Grilled)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 175,
    "protein_per_100g": 31,
    "carbs_per_100g": 0,
    "fat_per_100g": 5.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-006",
    "name": "USDA Choice Beef New York Strip Steak (Raw Trimmed)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 160,
    "protein_per_100g": 22,
    "carbs_per_100g": 0,
    "fat_per_100g": 7.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 220,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-007",
    "name": "USDA Choice Beef New York Strip Steak (Grilled)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 215,
    "protein_per_100g": 29,
    "carbs_per_100g": 0,
    "fat_per_100g": 10.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-008",
    "name": "USDA Choice Beef Ribeye Steak (Boneless Raw)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 225,
    "protein_per_100g": 20,
    "carbs_per_100g": 0,
    "fat_per_100g": 16,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 250,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_fat"
  },
  {
    "id": "pm-bef-009",
    "name": "USDA Choice Beef Ribeye Steak (Grilled Seared)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 270,
    "protein_per_100g": 26.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 18,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 200,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_fat"
  },
  {
    "id": "pm-bef-010",
    "name": "USDA Prime Bone-In Cowboy Ribeye Steak",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 285,
    "protein_per_100g": 25,
    "carbs_per_100g": 0,
    "fat_per_100g": 20,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 250,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_fat"
  },
  {
    "id": "pm-bef-011",
    "name": "USDA Choice Flank Steak (Lean Marinated, Raw)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 140,
    "protein_per_100g": 21.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 5.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 200,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-012",
    "name": "USDA Choice Flank Steak (Grilled Sliced)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 195,
    "protein_per_100g": 29.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-013",
    "name": "USDA Choice Flat Iron Steak / Top Blade (Grilled)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 190,
    "protein_per_100g": 28.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-014",
    "name": "USDA Choice Beef Skirt Steak (Carne Asada Grilled)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 215,
    "protein_per_100g": 27,
    "carbs_per_100g": 0,
    "fat_per_100g": 11.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-015",
    "name": "USDA Choice Beef Hanger Steak (Bistro Cut Grilled)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 185,
    "protein_per_100g": 28,
    "carbs_per_100g": 0,
    "fat_per_100g": 7.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-016",
    "name": "USDA Choice Beef Tri-Tip Roast (Trimmed Grilled)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 190,
    "protein_per_100g": 28,
    "carbs_per_100g": 0,
    "fat_per_100g": 8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-017",
    "name": "Eye of Round Steak (Ultra Lean Beef, Raw)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 120,
    "protein_per_100g": 23,
    "carbs_per_100g": 0,
    "fat_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-018",
    "name": "Eye of Round Steak (Braised / Roasted)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 165,
    "protein_per_100g": 31,
    "carbs_per_100g": 0,
    "fat_per_100g": 4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-019",
    "name": "Beef Bottom Round Roast (Pot Roast Lean)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 175,
    "protein_per_100g": 30,
    "carbs_per_100g": 0,
    "fat_per_100g": 5.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-020",
    "name": "Beef Chuck Roast (Braised Pot Roast Shreds)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 230,
    "protein_per_100g": 27,
    "carbs_per_100g": 0,
    "fat_per_100g": 13,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_fat"
  },
  {
    "id": "pm-bef-021",
    "name": "Beef Short Ribs (Bone-In Braised Tender)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 290,
    "protein_per_100g": 24,
    "carbs_per_100g": 0,
    "fat_per_100g": 21,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_fat"
  },
  {
    "id": "pm-bef-022",
    "name": "Beef Brisket (Flat Cut Lean, Smoked Texas BBQ)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 215,
    "protein_per_100g": 30,
    "carbs_per_100g": 0,
    "fat_per_100g": 10,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-023",
    "name": "Beef Brisket (Point Cut Marbled Smoked)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 280,
    "protein_per_100g": 25,
    "carbs_per_100g": 0,
    "fat_per_100g": 19.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_fat"
  },
  {
    "id": "pm-bef-024",
    "name": "Ground Beef (96% Extra Lean / 4% Fat Raw)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 130,
    "protein_per_100g": 22,
    "carbs_per_100g": 0,
    "fat_per_100g": 4.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-025",
    "name": "Ground Beef (96% Extra Lean Cooked Crumbles)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 170,
    "protein_per_100g": 30,
    "carbs_per_100g": 0,
    "fat_per_100g": 5.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-026",
    "name": "Ground Beef (93% Lean / 7% Fat Raw)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 150,
    "protein_per_100g": 21,
    "carbs_per_100g": 0,
    "fat_per_100g": 7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-027",
    "name": "Ground Beef (93% Lean Cooked Crumbles)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 195,
    "protein_per_100g": 28,
    "carbs_per_100g": 0,
    "fat_per_100g": 8.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-028",
    "name": "Ground Beef (90% Lean / 10% Fat Raw)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 175,
    "protein_per_100g": 20,
    "carbs_per_100g": 0,
    "fat_per_100g": 10,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-029",
    "name": "Ground Beef (90% Lean Cooked Crumbles)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 215,
    "protein_per_100g": 26.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 11.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-030",
    "name": "Ground Beef (85% Lean / 15% Fat Raw)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 215,
    "protein_per_100g": 18.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 15,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_fat"
  },
  {
    "id": "pm-bef-031",
    "name": "Ground Beef (85% Lean Cooked Patties)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 250,
    "protein_per_100g": 25,
    "carbs_per_100g": 0,
    "fat_per_100g": 16.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_fat"
  },
  {
    "id": "pm-bef-032",
    "name": "Ground Beef (80% Lean / 20% Fat Raw)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 255,
    "protein_per_100g": 17,
    "carbs_per_100g": 0,
    "fat_per_100g": 20,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_fat"
  },
  {
    "id": "pm-bef-033",
    "name": "Ground Beef (80% Lean Cooked Burger Patty)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 285,
    "protein_per_100g": 23.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 21,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_fat"
  },
  {
    "id": "pm-bef-034",
    "name": "Ground Bison / American Buffalo (90% Lean Raw)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 145,
    "protein_per_100g": 22,
    "carbs_per_100g": 0,
    "fat_per_100g": 6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-035",
    "name": "Ground Bison (90% Lean Cooked)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 185,
    "protein_per_100g": 29,
    "carbs_per_100g": 0,
    "fat_per_100g": 7.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-036",
    "name": "Bison Ribeye Steak (Grass-Fed Grilled)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 175,
    "protein_per_100g": 29,
    "carbs_per_100g": 0,
    "fat_per_100g": 6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-037",
    "name": "Bison Top Sirloin Steak (Grilled)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 150,
    "protein_per_100g": 30,
    "carbs_per_100g": 0,
    "fat_per_100g": 3.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-038",
    "name": "Bison Strip Loin Steak (Pan-Seared)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 155,
    "protein_per_100g": 29.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 3.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-039",
    "name": "Beef Liver (Fresh Grass-Fed Pan-Seared)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 175,
    "protein_per_100g": 26.5,
    "carbs_per_100g": 5,
    "fat_per_100g": 4.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-040",
    "name": "Beef Heart (Grilled Anticuchos Skewers)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 165,
    "protein_per_100g": 28.5,
    "carbs_per_100g": 0.1,
    "fat_per_100g": 4.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-041",
    "name": "Beef Tongue / Lengua (Braised Mexican Style)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 225,
    "protein_per_100g": 19.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 16,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_fat"
  },
  {
    "id": "pm-bef-042",
    "name": "Beef Oxtail (Slow Braised Stew Meat)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 260,
    "protein_per_100g": 26,
    "carbs_per_100g": 0,
    "fat_per_100g": 17,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_fat"
  },
  {
    "id": "pm-bef-043",
    "name": "Beef Marrow Bones (Roasted Bone Marrow)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 480,
    "protein_per_100g": 7,
    "carbs_per_100g": 0,
    "fat_per_100g": 50,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 60,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_fat"
  },
  {
    "id": "pm-bef-044",
    "name": "Beef Biltong (Traditional South African Air-Dried Slices)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 270,
    "protein_per_100g": 52,
    "carbs_per_100g": 1.5,
    "fat_per_100g": 5.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 40,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-045",
    "name": "Original Beef Jerky (Smoked Strips)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 280,
    "protein_per_100g": 40,
    "carbs_per_100g": 18,
    "fat_per_100g": 4.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 35,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-046",
    "name": "Peppered Beef Jerky (Dry Smoked Slices)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 275,
    "protein_per_100g": 41,
    "carbs_per_100g": 16,
    "fat_per_100g": 4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 35,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-047",
    "name": "Roast Beef Slices (Deli Thin Rare Cut)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 125,
    "protein_per_100g": 22,
    "carbs_per_100g": 1,
    "fat_per_100g": 3.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-048",
    "name": "Pastrami (Cured Spiced Smoked Beef Brisket Slices)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 145,
    "protein_per_100g": 20,
    "carbs_per_100g": 2,
    "fat_per_100g": 6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-bef-049",
    "name": "Corned Beef (Cured Brisket Slices Deli)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 210,
    "protein_per_100g": 18,
    "carbs_per_100g": 0.5,
    "fat_per_100g": 15,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_fat"
  },
  {
    "id": "pm-bef-050",
    "name": "Beef Meatballs (Baked Homestyle Italian)",
    "category": "poultry_meat",
    "sub_category": "beef",
    "calories_per_100g": 220,
    "protein_per_100g": 18,
    "carbs_per_100g": 8,
    "fat_per_100g": 13,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_fat"
  },
  {
    "id": "pm-prk-001",
    "name": "Boneless Pork Tenderloin (Raw Extra Lean)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 120,
    "protein_per_100g": 22,
    "carbs_per_100g": 0,
    "fat_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_lean"
  },
  {
    "id": "pm-prk-002",
    "name": "Boneless Pork Tenderloin (Roasted Medallions)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 145,
    "protein_per_100g": 26,
    "carbs_per_100g": 0,
    "fat_per_100g": 4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_lean"
  },
  {
    "id": "pm-prk-003",
    "name": "Boneless Center-Cut Pork Chop (Raw Lean)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 135,
    "protein_per_100g": 22,
    "carbs_per_100g": 0,
    "fat_per_100g": 4.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_lean"
  },
  {
    "id": "pm-prk-004",
    "name": "Center-Cut Pork Chop (Pan-Seared / Grilled)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 175,
    "protein_per_100g": 28,
    "carbs_per_100g": 0,
    "fat_per_100g": 6.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_lean"
  },
  {
    "id": "pm-prk-005",
    "name": "Bone-In Pork Rib Chops (Grilled)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 195,
    "protein_per_100g": 26.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 9.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_lean"
  },
  {
    "id": "pm-prk-006",
    "name": "Ground Pork (96% Extra Lean Raw)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 130,
    "protein_per_100g": 22,
    "carbs_per_100g": 0,
    "fat_per_100g": 4.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_lean"
  },
  {
    "id": "pm-prk-007",
    "name": "Ground Pork (96% Lean Cooked)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 170,
    "protein_per_100g": 29.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 5.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_lean"
  },
  {
    "id": "pm-prk-008",
    "name": "Ground Pork (80% Lean / 20% Fat Raw)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 260,
    "protein_per_100g": 17,
    "carbs_per_100g": 0,
    "fat_per_100g": 21,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_fat"
  },
  {
    "id": "pm-prk-009",
    "name": "Ground Pork (80% Lean Cooked)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 290,
    "protein_per_100g": 23.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 21.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_fat"
  },
  {
    "id": "pm-prk-010",
    "name": "Pork Sirloin Roast (Lean Roasted)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 160,
    "protein_per_100g": 27.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_lean"
  },
  {
    "id": "pm-prk-011",
    "name": "Pork Boston Butt / Shoulder (Smoked Pulled Pork)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 240,
    "protein_per_100g": 25,
    "carbs_per_100g": 0,
    "fat_per_100g": 15,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_fat"
  },
  {
    "id": "pm-prk-012",
    "name": "Pork Baby Back Ribs (Smoked Dry Rub Meat)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 270,
    "protein_per_100g": 24,
    "carbs_per_100g": 0,
    "fat_per_100g": 19,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_fat"
  },
  {
    "id": "pm-prk-013",
    "name": "Pork St. Louis Spare Ribs (Smoked)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 290,
    "protein_per_100g": 22,
    "carbs_per_100g": 0,
    "fat_per_100g": 22,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_fat"
  },
  {
    "id": "pm-prk-014",
    "name": "Pork Belly (Crisp Skin Roasted Chicharron style)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 450,
    "protein_per_100g": 15,
    "carbs_per_100g": 0,
    "fat_per_100g": 43,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_fat"
  },
  {
    "id": "pm-prk-015",
    "name": "Center-Cut Bacon (Pan-Fried Crisp Strips)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 460,
    "protein_per_100g": 35,
    "carbs_per_100g": 1.5,
    "fat_per_100g": 35,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 35,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_fat"
  },
  {
    "id": "pm-prk-016",
    "name": "Thick-Cut Applewood Smoked Bacon (Baked)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 480,
    "protein_per_100g": 34,
    "carbs_per_100g": 1.5,
    "fat_per_100g": 38,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 40,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_fat"
  },
  {
    "id": "pm-prk-017",
    "name": "Uncured All-Natural Bacon (Crisp)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 450,
    "protein_per_100g": 36,
    "carbs_per_100g": 1,
    "fat_per_100g": 34,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 35,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_fat"
  },
  {
    "id": "pm-prk-018",
    "name": "Canadian Bacon / Back Bacon (Lean Slices)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 120,
    "protein_per_100g": 20,
    "carbs_per_100g": 1.5,
    "fat_per_100g": 3.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 60,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_lean"
  },
  {
    "id": "pm-prk-019",
    "name": "Prosciutto di Parma (Aged Italian Dry-Cured Ham)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 220,
    "protein_per_100g": 27,
    "carbs_per_100g": 0.5,
    "fat_per_100g": 12.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_lean"
  },
  {
    "id": "pm-prk-020",
    "name": "Jamon Serrano (Spanish Dry-Cured Ham)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 230,
    "protein_per_100g": 28,
    "carbs_per_100g": 0.5,
    "fat_per_100g": 13,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_lean"
  },
  {
    "id": "pm-prk-021",
    "name": "Bone-In Spiral Sliced Honey Glazed Ham",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 145,
    "protein_per_100g": 19,
    "carbs_per_100g": 5,
    "fat_per_100g": 5.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_lean"
  },
  {
    "id": "pm-prk-022",
    "name": "Extra Lean Smoked Cooked Ham (Deli Slices 97% Fat Free)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 105,
    "protein_per_100g": 19,
    "carbs_per_100g": 2,
    "fat_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_lean"
  },
  {
    "id": "pm-prk-023",
    "name": "Black Forest Ham Slices",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 110,
    "protein_per_100g": 19.5,
    "carbs_per_100g": 2,
    "fat_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_lean"
  },
  {
    "id": "pm-prk-024",
    "name": "Italian Sweet Pork Sausage Links (Grilled)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 280,
    "protein_per_100g": 16,
    "carbs_per_100g": 2,
    "fat_per_100g": 23,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_fat"
  },
  {
    "id": "pm-prk-025",
    "name": "Italian Hot & Spicy Pork Sausage Links",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 280,
    "protein_per_100g": 16,
    "carbs_per_100g": 2,
    "fat_per_100g": 23,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_fat"
  },
  {
    "id": "pm-prk-026",
    "name": "Pork Breakfast Sausage Links (Cooked)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 300,
    "protein_per_100g": 15,
    "carbs_per_100g": 1,
    "fat_per_100g": 26,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 70,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_fat"
  },
  {
    "id": "pm-prk-027",
    "name": "Pork Chorizo Sausage (Mexican Crumbled Cooked)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 340,
    "protein_per_100g": 19,
    "carbs_per_100g": 2.5,
    "fat_per_100g": 28,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_fat"
  },
  {
    "id": "pm-prk-028",
    "name": "Spanish Cured Chorizo Salami",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 380,
    "protein_per_100g": 23,
    "carbs_per_100g": 2,
    "fat_per_100g": 31,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 40,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_fat"
  },
  {
    "id": "pm-prk-029",
    "name": "Genoa Salami Slices",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 400,
    "protein_per_100g": 21,
    "carbs_per_100g": 1.5,
    "fat_per_100g": 35,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 35,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_fat"
  },
  {
    "id": "pm-prk-030",
    "name": "Pepperoni Slices (Pork & Beef)",
    "category": "poultry_meat",
    "sub_category": "pork",
    "calories_per_100g": 460,
    "protein_per_100g": 20,
    "carbs_per_100g": 2,
    "fat_per_100g": 42,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_fat"
  },
  {
    "id": "pm-gam-001",
    "name": "Grass-Fed New Zealand Lamb Leg Steak (Raw Lean)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 140,
    "protein_per_100g": 21.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 5.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-gam-002",
    "name": "Lamb Leg (Roasted Slices Lean)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 190,
    "protein_per_100g": 28,
    "carbs_per_100g": 0,
    "fat_per_100g": 8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-gam-003",
    "name": "Lamb Loin Chops (Grilled Tender)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 215,
    "protein_per_100g": 26,
    "carbs_per_100g": 0,
    "fat_per_100g": 12,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-gam-004",
    "name": "Rack of Lamb Chops (Herb Crusted Roasted)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 260,
    "protein_per_100g": 23,
    "carbs_per_100g": 1,
    "fat_per_100g": 18.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_fat"
  },
  {
    "id": "pm-gam-005",
    "name": "Lamb Shank (Slow Braised Rosemary Stew)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 205,
    "protein_per_100g": 28,
    "carbs_per_100g": 0,
    "fat_per_100g": 9.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 200,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-gam-006",
    "name": "Ground Lamb (85% Lean Cooked)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 250,
    "protein_per_100g": 24,
    "carbs_per_100g": 0,
    "fat_per_100g": 17,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_fat"
  },
  {
    "id": "pm-gam-007",
    "name": "Lamb Shoulder (Slow Roasted Greek Kleftiko)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 235,
    "protein_per_100g": 25,
    "carbs_per_100g": 0,
    "fat_per_100g": 14.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_fat"
  },
  {
    "id": "pm-gam-008",
    "name": "Veal Cutlet / Escalope (Lean Raw)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 115,
    "protein_per_100g": 23,
    "carbs_per_100g": 0,
    "fat_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-gam-009",
    "name": "Veal Cutlet (Pan-Seared Piccata)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 160,
    "protein_per_100g": 29,
    "carbs_per_100g": 1.5,
    "fat_per_100g": 4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-gam-010",
    "name": "Veal Osso Buco Shank (Braised Tender)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 185,
    "protein_per_100g": 27.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 200,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-gam-011",
    "name": "Veal Chop (Grilled Loin)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 180,
    "protein_per_100g": 28,
    "carbs_per_100g": 0,
    "fat_per_100g": 7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 180,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-gam-012",
    "name": "Venison Steak / Deer Tenderloin (Wild Game Lean Grilled)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 150,
    "protein_per_100g": 30,
    "carbs_per_100g": 0,
    "fat_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-gam-013",
    "name": "Ground Venison (90% Lean Cooked)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 175,
    "protein_per_100g": 30.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 5.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-gam-014",
    "name": "Venison Roast (Slow Cooked Autumn Game)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 160,
    "protein_per_100g": 31,
    "carbs_per_100g": 0,
    "fat_per_100g": 3.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-gam-015",
    "name": "Wild Boar Tenderloin (Roasted)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 140,
    "protein_per_100g": 27,
    "carbs_per_100g": 0,
    "fat_per_100g": 3.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_lean"
  },
  {
    "id": "pm-gam-016",
    "name": "Ground Wild Boar (Cooked)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 205,
    "protein_per_100g": 27,
    "carbs_per_100g": 0,
    "fat_per_100g": 10.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "pork_fat"
  },
  {
    "id": "pm-gam-017",
    "name": "Elk Steak (Rocky Mountain Lean Cut Grilled)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 145,
    "protein_per_100g": 30.5,
    "carbs_per_100g": 0,
    "fat_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 170,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-gam-018",
    "name": "Ground Elk (Cooked)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 165,
    "protein_per_100g": 30,
    "carbs_per_100g": 0,
    "fat_per_100g": 4.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  },
  {
    "id": "pm-gam-019",
    "name": "Duck Breast (Boneless Skinless Pan-Seared)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 140,
    "protein_per_100g": 28,
    "carbs_per_100g": 0,
    "fat_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-gam-020",
    "name": "Duck Breast (Seared Crisp Skin)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 230,
    "protein_per_100g": 22,
    "carbs_per_100g": 0,
    "fat_per_100g": 15.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-gam-021",
    "name": "Duck Leg Confit (Slow Cooked in Duck Fat)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 290,
    "protein_per_100g": 24,
    "carbs_per_100g": 0,
    "fat_per_100g": 21,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-gam-022",
    "name": "Pheasant Breast (Roasted Game Bird Skinless)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 135,
    "protein_per_100g": 29,
    "carbs_per_100g": 0,
    "fat_per_100g": 1.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-gam-023",
    "name": "Quail (Whole Roasted Game Bird)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 190,
    "protein_per_100g": 25,
    "carbs_per_100g": 0,
    "fat_per_100g": 9.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-gam-024",
    "name": "Goose Breast (Roasted Sliced)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 195,
    "protein_per_100g": 25,
    "carbs_per_100g": 0,
    "fat_per_100g": 10.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_thigh"
  },
  {
    "id": "pm-gam-025",
    "name": "Rabbit Meat (Stewed / Roasted Farm Raised)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 160,
    "protein_per_100g": 29,
    "carbs_per_100g": 0,
    "fat_per_100g": 4.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "poultry_lean"
  },
  {
    "id": "pm-gam-026",
    "name": "Goat Meat / Cabrito (Braised Stew Lean)",
    "category": "poultry_meat",
    "sub_category": "game_meats",
    "calories_per_100g": 145,
    "protein_per_100g": 27,
    "carbs_per_100g": 0,
    "fat_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "red_meat_lean"
  }
];
