import { FoodItem } from '../types';

export const VEGETABLES_GREENS_DATABASE: FoodItem[] = [
  {
    "id": "vg-cru-001",
    "name": "Fresh Broccoli Florets (Raw Crisp)",
    "category": "vegetables",
    "sub_category": "cruciferous_veg",
    "calories_per_100g": 34,
    "protein_per_100g": 2.8,
    "carbs_per_100g": 6.6,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 2.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cruciferous_green"
  },
  {
    "id": "vg-cru-002",
    "name": "Steamed Broccoli Florets (Tender-Crisp)",
    "category": "vegetables",
    "sub_category": "cruciferous_veg",
    "calories_per_100g": 35,
    "protein_per_100g": 2.4,
    "carbs_per_100g": 7.2,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 3.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cruciferous_green"
  },
  {
    "id": "vg-cru-003",
    "name": "Roasted Broccoli (Olive Oil & Garlic)",
    "category": "vegetables",
    "sub_category": "cruciferous_veg",
    "calories_per_100g": 65,
    "protein_per_100g": 3,
    "carbs_per_100g": 6.8,
    "fat_per_100g": 3.5,
    "fiber_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cruciferous_green"
  },
  {
    "id": "vg-cru-004",
    "name": "Broccolini / Baby Broccoli (Steamed Tender Stems)",
    "category": "vegetables",
    "sub_category": "cruciferous_veg",
    "calories_per_100g": 35,
    "protein_per_100g": 3,
    "carbs_per_100g": 6,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cruciferous_green"
  },
  {
    "id": "vg-cru-005",
    "name": "Broccoli Rabe / Rapini (Sauteed Bitter Greens)",
    "category": "vegetables",
    "sub_category": "cruciferous_veg",
    "calories_per_100g": 32,
    "protein_per_100g": 3.2,
    "carbs_per_100g": 2.9,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 2.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cruciferous_green"
  },
  {
    "id": "vg-cru-006",
    "name": "Romanesco Broccoli (Fractal Green Florets Steamed)",
    "category": "vegetables",
    "sub_category": "cruciferous_veg",
    "calories_per_100g": 30,
    "protein_per_100g": 2.5,
    "carbs_per_100g": 5.5,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cruciferous_green"
  },
  {
    "id": "vg-cru-007",
    "name": "Fresh Cauliflower Florets (Raw)",
    "category": "vegetables",
    "sub_category": "cruciferous_veg",
    "calories_per_100g": 25,
    "protein_per_100g": 1.9,
    "carbs_per_100g": 5,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cruciferous_green"
  },
  {
    "id": "vg-cru-008",
    "name": "Riced Cauliflower (Steamed Low-Carb Base)",
    "category": "vegetables",
    "sub_category": "cruciferous_veg",
    "calories_per_100g": 25,
    "protein_per_100g": 1.9,
    "carbs_per_100g": 5,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cruciferous_green"
  },
  {
    "id": "vg-cru-009",
    "name": "Roasted Cauliflower Steaks (Turmeric & Garlic)",
    "category": "vegetables",
    "sub_category": "cruciferous_veg",
    "calories_per_100g": 55,
    "protein_per_100g": 2.2,
    "carbs_per_100g": 5.5,
    "fat_per_100g": 3,
    "fiber_per_100g": 2.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 160,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cruciferous_green"
  },
  {
    "id": "vg-cru-010",
    "name": "Brussels Sprouts (Roasted Crispy Halves)",
    "category": "vegetables",
    "sub_category": "cruciferous_veg",
    "calories_per_100g": 55,
    "protein_per_100g": 3.4,
    "carbs_per_100g": 9,
    "fat_per_100g": 1.5,
    "fiber_per_100g": 3.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cruciferous_green"
  },
  {
    "id": "vg-cru-011",
    "name": "Shaved Brussels Sprouts (Raw Slaw Salad)",
    "category": "vegetables",
    "sub_category": "cruciferous_veg",
    "calories_per_100g": 43,
    "protein_per_100g": 3.4,
    "carbs_per_100g": 9,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 3.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cruciferous_green"
  },
  {
    "id": "vg-cru-012",
    "name": "Green Cabbage (Shredded Slaw / Steamed Wedges)",
    "category": "vegetables",
    "sub_category": "cruciferous_veg",
    "calories_per_100g": 25,
    "protein_per_100g": 1.3,
    "carbs_per_100g": 5.8,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cruciferous_green"
  },
  {
    "id": "vg-cru-013",
    "name": "Red Cabbage (Raw Shredded Vitamin C Rich)",
    "category": "vegetables",
    "sub_category": "cruciferous_veg",
    "calories_per_100g": 31,
    "protein_per_100g": 1.4,
    "carbs_per_100g": 7.4,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cruciferous_green"
  },
  {
    "id": "vg-cru-014",
    "name": "Savoy Cabbage (Crinkled Leaf Braised)",
    "category": "vegetables",
    "sub_category": "cruciferous_veg",
    "calories_per_100g": 27,
    "protein_per_100g": 2,
    "carbs_per_100g": 6.1,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 3.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cruciferous_green"
  },
  {
    "id": "vg-cru-015",
    "name": "Baby Bok Choy (Steamed / Stir-Fried Whole)",
    "category": "vegetables",
    "sub_category": "cruciferous_veg",
    "calories_per_100g": 13,
    "protein_per_100g": 1.5,
    "carbs_per_100g": 2.2,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cruciferous_green"
  },
  {
    "id": "vg-cru-016",
    "name": "Napa Cabbage / Chinese Cabbage (Sweet Crisp)",
    "category": "vegetables",
    "sub_category": "cruciferous_veg",
    "calories_per_100g": 16,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 3.2,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cruciferous_green"
  },
  {
    "id": "vg-cru-017",
    "name": "Gai Lan / Chinese Broccoli (Steamed with Garlic)",
    "category": "vegetables",
    "sub_category": "cruciferous_veg",
    "calories_per_100g": 26,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 4.7,
    "fat_per_100g": 0.7,
    "fiber_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 140,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cruciferous_green"
  },
  {
    "id": "vg-cru-018",
    "name": "Kohlrabi (Crisp German Turnip Slices Raw)",
    "category": "vegetables",
    "sub_category": "cruciferous_veg",
    "calories_per_100g": 27,
    "protein_per_100g": 1.7,
    "carbs_per_100g": 6.2,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 3.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cruciferous_green"
  },
  {
    "id": "vg-grn-001",
    "name": "Baby Spinach (Fresh Raw Organic Leaves)",
    "category": "vegetables",
    "sub_category": "leafy_greens",
    "calories_per_100g": 23,
    "protein_per_100g": 2.9,
    "carbs_per_100g": 3.6,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 2.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 85,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "leafy_green"
  },
  {
    "id": "vg-grn-002",
    "name": "Sauteed Baby Spinach (in Olive Oil & Garlic)",
    "category": "vegetables",
    "sub_category": "leafy_greens",
    "calories_per_100g": 45,
    "protein_per_100g": 3,
    "carbs_per_100g": 3.8,
    "fat_per_100g": 2.5,
    "fiber_per_100g": 2.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "leafy_green"
  },
  {
    "id": "vg-grn-003",
    "name": "Curly Green Kale (Raw Chopped & Massaged)",
    "category": "vegetables",
    "sub_category": "leafy_greens",
    "calories_per_100g": 49,
    "protein_per_100g": 4.3,
    "carbs_per_100g": 8.8,
    "fat_per_100g": 0.9,
    "fiber_per_100g": 3.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 70,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "leafy_green"
  },
  {
    "id": "vg-grn-004",
    "name": "Lacinato / Dinosaur Kale (Tuscan Kale Steamed)",
    "category": "vegetables",
    "sub_category": "leafy_greens",
    "calories_per_100g": 45,
    "protein_per_100g": 3.8,
    "carbs_per_100g": 8,
    "fat_per_100g": 0.7,
    "fiber_per_100g": 3.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "leafy_green"
  },
  {
    "id": "vg-grn-005",
    "name": "Fresh Arugula / Wild Rocket (Peppery Greens)",
    "category": "vegetables",
    "sub_category": "leafy_greens",
    "calories_per_100g": 25,
    "protein_per_100g": 2.6,
    "carbs_per_100g": 3.7,
    "fat_per_100g": 0.7,
    "fiber_per_100g": 1.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 60,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "leafy_green"
  },
  {
    "id": "vg-grn-006",
    "name": "Romaine Lettuce Hearts (Crisp Caesar Base)",
    "category": "vegetables",
    "sub_category": "leafy_greens",
    "calories_per_100g": 17,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 3.3,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 2.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "leafy_green"
  },
  {
    "id": "vg-grn-007",
    "name": "Butterhead / Bibb Lettuce (Tender Sweet Cups)",
    "category": "vegetables",
    "sub_category": "leafy_greens",
    "calories_per_100g": 13,
    "protein_per_100g": 1.4,
    "carbs_per_100g": 2.2,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "leafy_green"
  },
  {
    "id": "vg-grn-008",
    "name": "Swiss Chard (Rainbow Stems & Leaves Sauteed)",
    "category": "vegetables",
    "sub_category": "leafy_greens",
    "calories_per_100g": 20,
    "protein_per_100g": 1.9,
    "carbs_per_100g": 4.1,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 2.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "leafy_green"
  },
  {
    "id": "vg-grn-009",
    "name": "Collard Greens (Braised Tender Southern style)",
    "category": "vegetables",
    "sub_category": "leafy_greens",
    "calories_per_100g": 33,
    "protein_per_100g": 2.7,
    "carbs_per_100g": 5.4,
    "fat_per_100g": 0.7,
    "fiber_per_100g": 4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "leafy_green"
  },
  {
    "id": "vg-grn-010",
    "name": "Mustard Greens (Spicy Peppery Braised)",
    "category": "vegetables",
    "sub_category": "leafy_greens",
    "calories_per_100g": 27,
    "protein_per_100g": 2.7,
    "carbs_per_100g": 4.7,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 3.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "leafy_green"
  },
  {
    "id": "vg-grn-011",
    "name": "Watercress (Aquatic Peppery Salad Greens)",
    "category": "vegetables",
    "sub_category": "leafy_greens",
    "calories_per_100g": 11,
    "protein_per_100g": 2.3,
    "carbs_per_100g": 1.3,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "leafy_green"
  },
  {
    "id": "vg-grn-012",
    "name": "Radicchio (Italian Purple Bitter Salad Head)",
    "category": "vegetables",
    "sub_category": "leafy_greens",
    "calories_per_100g": 23,
    "protein_per_100g": 1.4,
    "carbs_per_100g": 4.5,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 0.9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "leafy_green"
  },
  {
    "id": "vg-grn-013",
    "name": "Belgian Endive (Pale Yellow Crisp Spear)",
    "category": "vegetables",
    "sub_category": "leafy_greens",
    "calories_per_100g": 17,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 4,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 3.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "leafy_green"
  },
  {
    "id": "vg-grn-014",
    "name": "Frisée / Curly Endive (Bistro Salad Green)",
    "category": "vegetables",
    "sub_category": "leafy_greens",
    "calories_per_100g": 17,
    "protein_per_100g": 1.3,
    "carbs_per_100g": 3.3,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 3.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 60,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "leafy_green"
  },
  {
    "id": "vg-grn-015",
    "name": "Dandelion Greens (Raw / Sautéed Bitter Detox)",
    "category": "vegetables",
    "sub_category": "leafy_greens",
    "calories_per_100g": 45,
    "protein_per_100g": 2.7,
    "carbs_per_100g": 9.2,
    "fat_per_100g": 0.7,
    "fiber_per_100g": 3.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 70,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "leafy_green"
  },
  {
    "id": "vg-rot-001",
    "name": "Baby Carrots (Fresh Crisp Snack)",
    "category": "vegetables",
    "sub_category": "root_veg",
    "calories_per_100g": 35,
    "protein_per_100g": 0.8,
    "carbs_per_100g": 8.2,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 2.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-rot-002",
    "name": "Whole Large Orange Carrots (Raw Slices / Roasted)",
    "category": "vegetables",
    "sub_category": "root_veg",
    "calories_per_100g": 41,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 9.6,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-rot-003",
    "name": "Rainbow Heirloom Carrots (Purple, Yellow, Orange)",
    "category": "vegetables",
    "sub_category": "root_veg",
    "calories_per_100g": 41,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 9.6,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-rot-004",
    "name": "Red Table Beets (Boiled / Roasted Slices)",
    "category": "vegetables",
    "sub_category": "root_veg",
    "calories_per_100g": 44,
    "protein_per_100g": 1.7,
    "carbs_per_100g": 10,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-rot-005",
    "name": "Golden Beets (Sweet Mild Yellow Roasted)",
    "category": "vegetables",
    "sub_category": "root_veg",
    "calories_per_100g": 45,
    "protein_per_100g": 1.6,
    "carbs_per_100g": 10.2,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 2.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-rot-006",
    "name": "Chioggia Beets (Candy Cane Striped Raw Slices)",
    "category": "vegetables",
    "sub_category": "root_veg",
    "calories_per_100g": 43,
    "protein_per_100g": 1.6,
    "carbs_per_100g": 9.8,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-rot-007",
    "name": "Red Globe Radishes (Sliced Crisp Salad)",
    "category": "vegetables",
    "sub_category": "root_veg",
    "calories_per_100g": 16,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 3.4,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 1.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-rot-008",
    "name": "French Breakfast Radishes (Mild Elongated)",
    "category": "vegetables",
    "sub_category": "root_veg",
    "calories_per_100g": 16,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 3.4,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 1.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-rot-009",
    "name": "Watermelon Radish (Vibrant Pink Heirloom Slices)",
    "category": "vegetables",
    "sub_category": "root_veg",
    "calories_per_100g": 18,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 3.8,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 1.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-rot-010",
    "name": "Daikon White Japanese Radish (Crisp Slices)",
    "category": "vegetables",
    "sub_category": "root_veg",
    "calories_per_100g": 18,
    "protein_per_100g": 0.6,
    "carbs_per_100g": 4.1,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 1.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-rot-011",
    "name": "Parsnips (Sweet Caramelized Roasted Root)",
    "category": "vegetables",
    "sub_category": "root_veg",
    "calories_per_100g": 75,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 18,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 4.9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-rot-012",
    "name": "Purple Top Turnips (Steamed / Roasted Cubes)",
    "category": "vegetables",
    "sub_category": "root_veg",
    "calories_per_100g": 28,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 6.4,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 1.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-rot-013",
    "name": "Rutabaga / Swede (Sweet Yellow Roasted)",
    "category": "vegetables",
    "sub_category": "root_veg",
    "calories_per_100g": 37,
    "protein_per_100g": 1.1,
    "carbs_per_100g": 8.6,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-rot-014",
    "name": "Jicama (Crisp Mexican Yam Slices with Lime & Chili)",
    "category": "vegetables",
    "sub_category": "root_veg",
    "calories_per_100g": 38,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 8.8,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 4.9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-rot-015",
    "name": "Sunchokes / Jerusalem Artichokes (Roasted Prebiotic)",
    "category": "vegetables",
    "sub_category": "root_veg",
    "calories_per_100g": 73,
    "protein_per_100g": 2,
    "carbs_per_100g": 17.4,
    "fat_per_100g": 0,
    "fiber_per_100g": 1.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ngh-001",
    "name": "Red Bell Pepper (Sweet Crisp Raw Slices)",
    "category": "vegetables",
    "sub_category": "nightshades",
    "calories_per_100g": 31,
    "protein_per_100g": 1,
    "carbs_per_100g": 6,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 2.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ngh-002",
    "name": "Green Bell Pepper (Raw / Sauteed Fajita Slices)",
    "category": "vegetables",
    "sub_category": "nightshades",
    "calories_per_100g": 20,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 4.6,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ngh-003",
    "name": "Yellow Bell Pepper (Sweet Sunny Raw)",
    "category": "vegetables",
    "sub_category": "nightshades",
    "calories_per_100g": 27,
    "protein_per_100g": 1,
    "carbs_per_100g": 6.3,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ngh-004",
    "name": "Orange Bell Pepper (Sweet Crisp)",
    "category": "vegetables",
    "sub_category": "nightshades",
    "calories_per_100g": 28,
    "protein_per_100g": 1,
    "carbs_per_100g": 6.4,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ngh-005",
    "name": "Poblano Pepper (Mild Roasted Green Pepper)",
    "category": "vegetables",
    "sub_category": "nightshades",
    "calories_per_100g": 20,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 4.7,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ngh-006",
    "name": "Jalapeno Pepper (Fresh Raw Slices)",
    "category": "vegetables",
    "sub_category": "nightshades",
    "calories_per_100g": 29,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 6.5,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ngh-007",
    "name": "Serrano Chili Pepper (Fresh Spicy Minced)",
    "category": "vegetables",
    "sub_category": "nightshades",
    "calories_per_100g": 32,
    "protein_per_100g": 1.7,
    "carbs_per_100g": 7,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 3.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 20,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ngh-008",
    "name": "Anaheim Pepper (Mild Sweet Green Chili)",
    "category": "vegetables",
    "sub_category": "nightshades",
    "calories_per_100g": 20,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 4.5,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ngh-009",
    "name": "Roma Plum Tomatoes (Fresh Diced)",
    "category": "vegetables",
    "sub_category": "nightshades",
    "calories_per_100g": 18,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 3.9,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ngh-010",
    "name": "Vine-Ripened Campari Tomatoes (Sweet Sweet)",
    "category": "vegetables",
    "sub_category": "nightshades",
    "calories_per_100g": 18,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 3.9,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ngh-011",
    "name": "Cherry Tomatoes (Sweet Red Halves)",
    "category": "vegetables",
    "sub_category": "nightshades",
    "calories_per_100g": 18,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 3.9,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ngh-012",
    "name": "Heirloom Rainbow Tomatoes (Cherokee Purple / Brandywine)",
    "category": "vegetables",
    "sub_category": "nightshades",
    "calories_per_100g": 20,
    "protein_per_100g": 1,
    "carbs_per_100g": 4.2,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ngh-013",
    "name": "San Marzano Whole Peeled Tomatoes (Canned D.O.P. Plum)",
    "category": "vegetables",
    "sub_category": "nightshades",
    "calories_per_100g": 22,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 4.5,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ngh-014",
    "name": "Fresh Tomatillos (Husked Green Salsa Base)",
    "category": "vegetables",
    "sub_category": "nightshades",
    "calories_per_100g": 32,
    "protein_per_100g": 1,
    "carbs_per_100g": 5.8,
    "fat_per_100g": 1,
    "fiber_per_100g": 1.9,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ngh-015",
    "name": "Globe Eggplant / Aubergine (Grilled / Roasted Slices)",
    "category": "vegetables",
    "sub_category": "nightshades",
    "calories_per_100g": 25,
    "protein_per_100g": 1,
    "carbs_per_100g": 5.9,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ngh-016",
    "name": "Japanese Slender Eggplant (Quick Sauteed)",
    "category": "vegetables",
    "sub_category": "nightshades",
    "calories_per_100g": 24,
    "protein_per_100g": 1,
    "carbs_per_100g": 5.7,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-csp-001",
    "name": "English Hothouse Seedless Cucumber (Sliced)",
    "category": "vegetables",
    "sub_category": "crisp_veg",
    "calories_per_100g": 15,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 3.6,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-csp-002",
    "name": "Persian Mini Cucumbers (Crisp Snacking)",
    "category": "vegetables",
    "sub_category": "crisp_veg",
    "calories_per_100g": 15,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 3.6,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 0.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-csp-003",
    "name": "Celery Stalks (Fresh Crisp Ribs)",
    "category": "vegetables",
    "sub_category": "crisp_veg",
    "calories_per_100g": 14,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 3,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 110,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-csp-004",
    "name": "Green Asparagus Spears (Steamed / Roasted Tender)",
    "category": "vegetables",
    "sub_category": "crisp_veg",
    "calories_per_100g": 20,
    "protein_per_100g": 2.2,
    "carbs_per_100g": 3.9,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 2.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-csp-005",
    "name": "White Asparagus Spears (Delicate European Braised)",
    "category": "vegetables",
    "sub_category": "crisp_veg",
    "calories_per_100g": 20,
    "protein_per_100g": 2,
    "carbs_per_100g": 3.8,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-csp-006",
    "name": "Fresh Green String Beans / Haricots Verts (Steamed)",
    "category": "vegetables",
    "sub_category": "crisp_veg",
    "calories_per_100g": 31,
    "protein_per_100g": 1.8,
    "carbs_per_100g": 7,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-csp-007",
    "name": "Sugar Snap Peas (Whole Sweet Edible Pods)",
    "category": "vegetables",
    "sub_category": "crisp_veg",
    "calories_per_100g": 42,
    "protein_per_100g": 2.8,
    "carbs_per_100g": 7.5,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-csp-008",
    "name": "Snow Peas (Flat Chinese Pods Stir-Fried)",
    "category": "vegetables",
    "sub_category": "crisp_veg",
    "calories_per_100g": 42,
    "protein_per_100g": 2.8,
    "carbs_per_100g": 7.5,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-csp-009",
    "name": "Zucchini / Courgette (Raw Slices / Grilled Ribbons)",
    "category": "vegetables",
    "sub_category": "crisp_veg",
    "calories_per_100g": 17,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 3.1,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-csp-010",
    "name": "Spiralized Zucchini Noodles / Zoodles",
    "category": "vegetables",
    "sub_category": "crisp_veg",
    "calories_per_100g": 17,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 3.1,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-csp-011",
    "name": "Yellow Summer Squash (Sauteed Half Moons)",
    "category": "vegetables",
    "sub_category": "crisp_veg",
    "calories_per_100g": 16,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 3.4,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-csp-012",
    "name": "Artichoke Hearts (Canned in Water Drained)",
    "category": "vegetables",
    "sub_category": "crisp_veg",
    "calories_per_100g": 47,
    "protein_per_100g": 2.9,
    "carbs_per_100g": 10.5,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 5.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-csp-013",
    "name": "Whole Globe Artichoke (Steamed Leaf & Heart)",
    "category": "vegetables",
    "sub_category": "crisp_veg",
    "calories_per_100g": 47,
    "protein_per_100g": 3.3,
    "carbs_per_100g": 10.5,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 5.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-csp-014",
    "name": "Hearts of Palm (Canned in Water Drained)",
    "category": "vegetables",
    "sub_category": "crisp_veg",
    "calories_per_100g": 28,
    "protein_per_100g": 2.5,
    "carbs_per_100g": 4.6,
    "fat_per_100g": 0.6,
    "fiber_per_100g": 2.4,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-csp-015",
    "name": "Fresh Okra (Steamed / Sautéed Pods)",
    "category": "vegetables",
    "sub_category": "crisp_veg",
    "calories_per_100g": 33,
    "protein_per_100g": 1.9,
    "carbs_per_100g": 7.5,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 3.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-csp-016",
    "name": "Fennel Bulb (Raw Shaved Anise Salad)",
    "category": "vegetables",
    "sub_category": "crisp_veg",
    "calories_per_100g": 31,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 7.3,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 3.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-msh-001",
    "name": "Cremini / Baby Bella Mushrooms (Sliced)",
    "category": "vegetables",
    "sub_category": "mushrooms_alliums",
    "calories_per_100g": 22,
    "protein_per_100g": 2.5,
    "carbs_per_100g": 3.3,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 0.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-msh-002",
    "name": "White Button Mushrooms (Whole / Sliced)",
    "category": "vegetables",
    "sub_category": "mushrooms_alliums",
    "calories_per_100g": 22,
    "protein_per_100g": 3.1,
    "carbs_per_100g": 3.3,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-msh-003",
    "name": "Portobello Mushroom Caps (Grilled Cap Whole)",
    "category": "vegetables",
    "sub_category": "mushrooms_alliums",
    "calories_per_100g": 22,
    "protein_per_100g": 2.1,
    "carbs_per_100g": 3.9,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 1.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-msh-004",
    "name": "Shiitake Mushrooms (Fresh Wood-Ear Sauteed)",
    "category": "vegetables",
    "sub_category": "mushrooms_alliums",
    "calories_per_100g": 34,
    "protein_per_100g": 2.2,
    "carbs_per_100g": 6.8,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-msh-005",
    "name": "Oyster Mushrooms (Pearl Clusters Pan-Seared)",
    "category": "vegetables",
    "sub_category": "mushrooms_alliums",
    "calories_per_100g": 33,
    "protein_per_100g": 3.3,
    "carbs_per_100g": 6.1,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 2.3,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-msh-006",
    "name": "King Trumpet / King Oyster Mushrooms (Thick Slices Seared)",
    "category": "vegetables",
    "sub_category": "mushrooms_alliums",
    "calories_per_100g": 35,
    "protein_per_100g": 3.1,
    "carbs_per_100g": 6,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 2.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-msh-007",
    "name": "Maitake / Hen of the Woods Mushrooms (Crispy Roasted)",
    "category": "vegetables",
    "sub_category": "mushrooms_alliums",
    "calories_per_100g": 31,
    "protein_per_100g": 1.9,
    "carbs_per_100g": 7,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-msh-008",
    "name": "Chanterelle Golden Mushrooms (Wild Sautéed)",
    "category": "vegetables",
    "sub_category": "mushrooms_alliums",
    "calories_per_100g": 32,
    "protein_per_100g": 1.5,
    "carbs_per_100g": 6.9,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 3.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-msh-009",
    "name": "Enoki Mushrooms (Delicate White Straw Clusters)",
    "category": "vegetables",
    "sub_category": "mushrooms_alliums",
    "calories_per_100g": 37,
    "protein_per_100g": 2.7,
    "carbs_per_100g": 7.8,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 2.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 60,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-msh-010",
    "name": "Yellow Cooking Onions (Diced / Sliced)",
    "category": "vegetables",
    "sub_category": "mushrooms_alliums",
    "calories_per_100g": 40,
    "protein_per_100g": 1.1,
    "carbs_per_100g": 9.3,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 1.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-msh-011",
    "name": "Sweet Vidalia Onions (Raw Sweet Rings)",
    "category": "vegetables",
    "sub_category": "mushrooms_alliums",
    "calories_per_100g": 32,
    "protein_per_100g": 0.8,
    "carbs_per_100g": 7.5,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 1.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-msh-012",
    "name": "Red Onions (Crisp Salad Slices / Pickled)",
    "category": "vegetables",
    "sub_category": "mushrooms_alliums",
    "calories_per_100g": 40,
    "protein_per_100g": 1.2,
    "carbs_per_100g": 9.3,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 1.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 60,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-msh-013",
    "name": "French Shallots (Mild Gourmet Diced)",
    "category": "vegetables",
    "sub_category": "mushrooms_alliums",
    "calories_per_100g": 72,
    "protein_per_100g": 2.5,
    "carbs_per_100g": 16.8,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 3.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 40,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-msh-014",
    "name": "Scallions / Green Onions (Fresh Chopped)",
    "category": "vegetables",
    "sub_category": "mushrooms_alliums",
    "calories_per_100g": 32,
    "protein_per_100g": 1.8,
    "carbs_per_100g": 7.3,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 30,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-msh-015",
    "name": "Leeks (Cleaned White & Light Green Stalk Braised)",
    "category": "vegetables",
    "sub_category": "mushrooms_alliums",
    "calories_per_100g": 61,
    "protein_per_100g": 1.5,
    "carbs_per_100g": 14.2,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 1.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-msh-016",
    "name": "Fresh Garlic Cloves (Minced Aromatic)",
    "category": "vegetables",
    "sub_category": "mushrooms_alliums",
    "calories_per_100g": 149,
    "protein_per_100g": 6.4,
    "carbs_per_100g": 33.1,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 2.1,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 10,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-msh-017",
    "name": "Fresh Ginger Root (Grated Aromatic)",
    "category": "vegetables",
    "sub_category": "mushrooms_alliums",
    "calories_per_100g": 80,
    "protein_per_100g": 1.8,
    "carbs_per_100g": 17.8,
    "fat_per_100g": 0.8,
    "fiber_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 15,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-msh-018",
    "name": "Fresh Turmeric Root (Raw Grated Golden)",
    "category": "vegetables",
    "sub_category": "mushrooms_alliums",
    "calories_per_100g": 65,
    "protein_per_100g": 1.5,
    "carbs_per_100g": 14,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 10,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ext-001",
    "name": "Purple Cauliflower Florets (Anthocyanin Rich Steamed)",
    "category": "vegetables",
    "sub_category": "cruciferous_veg",
    "calories_per_100g": 25,
    "protein_per_100g": 2,
    "carbs_per_100g": 5,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 2.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cruciferous_green"
  },
  {
    "id": "vg-ext-002",
    "name": "Orange Cheddar Cauliflower Florets (Beta-Carotene Rich)",
    "category": "vegetables",
    "sub_category": "cruciferous_veg",
    "calories_per_100g": 25,
    "protein_per_100g": 2,
    "carbs_per_100g": 5,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 2.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 150,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "cruciferous_green"
  },
  {
    "id": "vg-ext-003",
    "name": "Baby Little Gem Lettuce Heads (Crisp Sweet Halves)",
    "category": "vegetables",
    "sub_category": "leafy_greens",
    "calories_per_100g": 15,
    "protein_per_100g": 1.3,
    "carbs_per_100g": 2.8,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 1.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 100,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "leafy_green"
  },
  {
    "id": "vg-ext-004",
    "name": "Escarole Greens (Italian Soup & Salad Braised)",
    "category": "vegetables",
    "sub_category": "leafy_greens",
    "calories_per_100g": 19,
    "protein_per_100g": 1.3,
    "carbs_per_100g": 3.4,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 120,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "leafy_green"
  },
  {
    "id": "vg-ext-005",
    "name": "Organic Microgreens Blend (Broccoli, Radish, Cabbage, Mustard)",
    "category": "vegetables",
    "sub_category": "leafy_greens",
    "calories_per_100g": 29,
    "protein_per_100g": 3,
    "carbs_per_100g": 4,
    "fat_per_100g": 0.5,
    "fiber_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 40,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "leafy_green"
  },
  {
    "id": "vg-ext-006",
    "name": "Fresh Pea Shoots / Tendrils (Sweet Crisp Sautéed)",
    "category": "vegetables",
    "sub_category": "leafy_greens",
    "calories_per_100g": 31,
    "protein_per_100g": 3.5,
    "carbs_per_100g": 4.5,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "leafy_green"
  },
  {
    "id": "vg-ext-007",
    "name": "Sunflower Sprouts / Microgreens (Nutty Raw)",
    "category": "vegetables",
    "sub_category": "leafy_greens",
    "calories_per_100g": 35,
    "protein_per_100g": 3.2,
    "carbs_per_100g": 4,
    "fat_per_100g": 0.8,
    "fiber_per_100g": 2.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 50,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "leafy_green"
  },
  {
    "id": "vg-ext-008",
    "name": "Black Spanish Winter Radish (Spicy White Flesh)",
    "category": "vegetables",
    "sub_category": "root_veg",
    "calories_per_100g": 16,
    "protein_per_100g": 0.7,
    "carbs_per_100g": 3.4,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 1.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ext-009",
    "name": "Yellow Wax Beans (Steamed Tender-Crisp)",
    "category": "vegetables",
    "sub_category": "crisp_veg",
    "calories_per_100g": 31,
    "protein_per_100g": 1.8,
    "carbs_per_100g": 7,
    "fat_per_100g": 0.2,
    "fiber_per_100g": 2.7,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 130,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ext-010",
    "name": "Sliced Water Chestnuts (Canned in Water Crisp Drained)",
    "category": "vegetables",
    "sub_category": "crisp_veg",
    "calories_per_100g": 50,
    "protein_per_100g": 0.9,
    "carbs_per_100g": 11.8,
    "fat_per_100g": 0.1,
    "fiber_per_100g": 2.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ext-011",
    "name": "Bamboo Shoots (Canned Tender Strips Drained)",
    "category": "vegetables",
    "sub_category": "crisp_veg",
    "calories_per_100g": 27,
    "protein_per_100g": 2.6,
    "carbs_per_100g": 5.2,
    "fat_per_100g": 0.3,
    "fiber_per_100g": 2.2,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "pantry_monthly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ext-012",
    "name": "Morel Wild Mushrooms (Fresh Spring Sautéed in Butter)",
    "category": "vegetables",
    "sub_category": "mushrooms_alliums",
    "calories_per_100g": 31,
    "protein_per_100g": 3.1,
    "carbs_per_100g": 5.1,
    "fat_per_100g": 0.6,
    "fiber_per_100g": 2.8,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ext-013",
    "name": "Porcini / Cep Mushrooms (Wild Sautéed Slices)",
    "category": "vegetables",
    "sub_category": "mushrooms_alliums",
    "calories_per_100g": 30,
    "protein_per_100g": 3,
    "carbs_per_100g": 4.8,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 2.5,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  },
  {
    "id": "vg-ext-014",
    "name": "Black Trumpet Mushrooms (Earthy Gourmet Wild)",
    "category": "vegetables",
    "sub_category": "mushrooms_alliums",
    "calories_per_100g": 28,
    "protein_per_100g": 2.8,
    "carbs_per_100g": 4.5,
    "fat_per_100g": 0.4,
    "fiber_per_100g": 2.6,
    "is_gluten_free": true,
    "is_dairy_free": true,
    "serving_size_g": 80,
    "default_unit": "g",
    "storage_type": "fresh_weekly",
    "swap_group": "vegetable_fiber"
  }
];
