import { FoodItem } from '../types';

export const VEGETABLES_GREENS_DATABASE: FoodItem[] = [
  // ==========================================
  // CRUCIFEROUS VEGETABLES (15+ items)
  // ==========================================
  {
    id: 'vg-cru-001',
    name: 'Fresh Steamed Broccoli Florets',
    category: 'vegetables',
    sub_category: 'cruciferous_veg',
    calories_per_100g: 35,
    protein_per_100g: 2.4,
    carbs_per_100g: 7.2,
    fat_per_100g: 0.4,
    fiber_per_100g: 2.6,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'cruciferous_veg',
  },
  {
    id: 'vg-cru-002',
    name: 'Steamed Cauliflower Florets',
    category: 'vegetables',
    sub_category: 'cruciferous_veg',
    calories_per_100g: 25,
    protein_per_100g: 1.9,
    carbs_per_100g: 5.0,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'cruciferous_veg',
  },
  {
    id: 'vg-cru-003',
    name: 'Riced Cauliflower (Sautéed)',
    category: 'vegetables',
    sub_category: 'cruciferous_veg',
    calories_per_100g: 25,
    protein_per_100g: 2.0,
    carbs_per_100g: 4.8,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.1,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'cruciferous_veg',
  },
  {
    id: 'vg-cru-004',
    name: 'Brussels Sprouts (Halved & Roasted)',
    category: 'vegetables',
    sub_category: 'cruciferous_veg',
    calories_per_100g: 43,
    protein_per_100g: 3.4,
    carbs_per_100g: 9.0,
    fat_per_100g: 0.3,
    fiber_per_100g: 3.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'cruciferous_veg',
  },
  {
    id: 'vg-cru-005',
    name: 'Shredded Red / Green Cabbage',
    category: 'vegetables',
    sub_category: 'cruciferous_veg',
    calories_per_100g: 25,
    protein_per_100g: 1.3,
    carbs_per_100g: 5.8,
    fat_per_100g: 0.1,
    fiber_per_100g: 2.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'cruciferous_veg',
  },
  {
    id: 'vg-cru-006',
    name: 'Baby Bok Choy (Steamed with Ginger)',
    category: 'vegetables',
    sub_category: 'cruciferous_veg',
    calories_per_100g: 13,
    protein_per_100g: 1.5,
    carbs_per_100g: 2.2,
    fat_per_100g: 0.2,
    fiber_per_100g: 1.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'cruciferous_veg',
  },

  // ==========================================
  // LEAFY SALAD GREENS & SPINACH (15+ items)
  // ==========================================
  {
    id: 'vg-lfg-001',
    name: 'Organic Baby Spinach (Raw / Steamed)',
    category: 'vegetables',
    sub_category: 'leafy_greens',
    calories_per_100g: 23,
    protein_per_100g: 2.9,
    carbs_per_100g: 3.6,
    fat_per_100g: 0.4,
    fiber_per_100g: 2.2,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'leafy_veg',
  },
  {
    id: 'vg-lfg-002',
    name: 'Tuscan Lacinato Kale (Raw Chopped)',
    category: 'vegetables',
    sub_category: 'leafy_greens',
    calories_per_100g: 49,
    protein_per_100g: 4.3,
    carbs_per_100g: 8.8,
    fat_per_100g: 0.9,
    fiber_per_100g: 3.6,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'leafy_veg',
  },
  {
    id: 'vg-lfg-003',
    name: 'Fresh Wild Arugula / Rocket',
    category: 'vegetables',
    sub_category: 'leafy_greens',
    calories_per_100g: 25,
    protein_per_100g: 2.6,
    carbs_per_100g: 3.7,
    fat_per_100g: 0.7,
    fiber_per_100g: 1.6,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 80,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'leafy_veg',
  },
  {
    id: 'vg-lfg-004',
    name: 'Crisp Romaine Lettuce Hearts',
    category: 'vegetables',
    sub_category: 'leafy_greens',
    calories_per_100g: 17,
    protein_per_100g: 1.2,
    carbs_per_100g: 3.3,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.1,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'leafy_veg',
  },
  {
    id: 'vg-lfg-005',
    name: 'Swiss Chard (Steamed Leaves & Stems)',
    category: 'vegetables',
    sub_category: 'leafy_greens',
    calories_per_100g: 19,
    protein_per_100g: 1.8,
    carbs_per_100g: 3.7,
    fat_per_100g: 0.2,
    fiber_per_100g: 1.6,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'leafy_veg',
  },

  // ==========================================
  // ROOT VEGETABLES & CARROTS (10+ items)
  // ==========================================
  {
    id: 'vg-rot-001',
    name: 'Whole Fresh Carrots (Raw / Steamed)',
    category: 'vegetables',
    sub_category: 'root_veg',
    calories_per_100g: 41,
    protein_per_100g: 0.9,
    carbs_per_100g: 9.6,
    fat_per_100g: 0.2,
    fiber_per_100g: 2.8,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },
  {
    id: 'vg-rot-002',
    name: 'Cooked Red Beets (Sliced / Roasted)',
    category: 'vegetables',
    sub_category: 'root_veg',
    calories_per_100g: 44,
    protein_per_100g: 1.7,
    carbs_per_100g: 10.0,
    fat_per_100g: 0.2,
    fiber_per_100g: 2.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },
  {
    id: 'vg-rot-003',
    name: 'Red Radishes (Sliced Crisp)',
    category: 'vegetables',
    sub_category: 'root_veg',
    calories_per_100g: 16,
    protein_per_100g: 0.7,
    carbs_per_100g: 3.4,
    fat_per_100g: 0.1,
    fiber_per_100g: 1.6,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },

  // ==========================================
  // PEPPERS & TOMATOES (10+ items)
  // ==========================================
  {
    id: 'vg-ngt-001',
    name: 'Sweet Red Bell Peppers (Sliced)',
    category: 'vegetables',
    sub_category: 'nightshades',
    calories_per_100g: 31,
    protein_per_100g: 1.0,
    carbs_per_100g: 6.0,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.1,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },
  {
    id: 'vg-ngt-002',
    name: 'Fresh Cherry / Grape Tomatoes',
    category: 'vegetables',
    sub_category: 'nightshades',
    calories_per_100g: 18,
    protein_per_100g: 0.9,
    carbs_per_100g: 3.9,
    fat_per_100g: 0.2,
    fiber_per_100g: 1.2,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },
  {
    id: 'vg-ngt-003',
    name: 'Roasted Italian Eggplant (Cubed)',
    category: 'vegetables',
    sub_category: 'nightshades',
    calories_per_100g: 25,
    protein_per_100g: 1.0,
    carbs_per_100g: 5.9,
    fat_per_100g: 0.2,
    fiber_per_100g: 3.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },

  // ==========================================
  // CRISP VEGETABLES & ASPARAGUS (15+ items)
  // ==========================================
  {
    id: 'vg-csp-001',
    name: 'Fresh Green Asparagus Spears (Steamed / Grilled)',
    category: 'vegetables',
    sub_category: 'crisp_veg',
    calories_per_100g: 20,
    protein_per_100g: 2.2,
    carbs_per_100g: 3.9,
    fat_per_100g: 0.1,
    fiber_per_100g: 2.1,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },
  {
    id: 'vg-csp-002',
    name: 'English Seedless Cucumber (Sliced)',
    category: 'vegetables',
    sub_category: 'crisp_veg',
    calories_per_100g: 15,
    protein_per_100g: 0.7,
    carbs_per_100g: 3.6,
    fat_per_100g: 0.1,
    fiber_per_100g: 0.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },
  {
    id: 'vg-csp-003',
    name: 'Zucchini / Courgette (Grilled Slices)',
    category: 'vegetables',
    sub_category: 'crisp_veg',
    calories_per_100g: 17,
    protein_per_100g: 1.2,
    carbs_per_100g: 3.1,
    fat_per_100g: 0.3,
    fiber_per_100g: 1.0,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },
  {
    id: 'vg-csp-004',
    name: 'Crisp Celery Stalks',
    category: 'vegetables',
    sub_category: 'crisp_veg',
    calories_per_100g: 14,
    protein_per_100g: 0.7,
    carbs_per_100g: 3.0,
    fat_per_100g: 0.2,
    fiber_per_100g: 1.6,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },
  {
    id: 'vg-csp-005',
    name: 'French Green Beans / Haricots Verts (Steamed)',
    category: 'vegetables',
    sub_category: 'crisp_veg',
    calories_per_100g: 31,
    protein_per_100g: 1.8,
    carbs_per_100g: 7.0,
    fat_per_100g: 0.2,
    fiber_per_100g: 2.7,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 150,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },

  // ==========================================
  // MUSHROOMS & ALLIUMS (10+ items)
  // ==========================================
  {
    id: 'vg-msh-001',
    name: 'Cremini / Baby Bella Mushrooms (Sautéed)',
    category: 'vegetables',
    sub_category: 'mushrooms_alliums',
    calories_per_100g: 22,
    protein_per_100g: 2.5,
    carbs_per_100g: 3.3,
    fat_per_100g: 0.1,
    fiber_per_100g: 0.6,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },
  {
    id: 'vg-msh-002',
    name: 'Shiitake Mushrooms (Pan-Seared)',
    category: 'vegetables',
    sub_category: 'mushrooms_alliums',
    calories_per_100g: 34,
    protein_per_100g: 2.2,
    carbs_per_100g: 6.8,
    fat_per_100g: 0.5,
    fiber_per_100g: 2.5,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 100,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },
  {
    id: 'vg-msh-003',
    name: 'Portobello Mushroom Cap (Grilled)',
    category: 'vegetables',
    sub_category: 'mushrooms_alliums',
    calories_per_100g: 22,
    protein_per_100g: 2.1,
    carbs_per_100g: 3.9,
    fat_per_100g: 0.3,
    fiber_per_100g: 1.3,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 120,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },
  {
    id: 'vg-msh-004',
    name: 'Sweet Vidalia Onion (Diced / Sautéed)',
    category: 'vegetables',
    sub_category: 'mushrooms_alliums',
    calories_per_100g: 40,
    protein_per_100g: 1.1,
    carbs_per_100g: 9.3,
    fat_per_100g: 0.1,
    fiber_per_100g: 1.7,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 80,
    default_unit: 'g',
    storage_type: 'fresh_weekly',
    swap_group: 'fiber_veg',
  },
  {
    id: 'vg-msh-005',
    name: 'Fresh Garlic Cloves (Minced)',
    category: 'vegetables',
    sub_category: 'mushrooms_alliums',
    calories_per_100g: 149,
    protein_per_100g: 6.4,
    carbs_per_100g: 33.1,
    fat_per_100g: 0.5,
    fiber_per_100g: 2.1,
    is_gluten_free: true,
    is_dairy_free: true,
    serving_size_g: 10,
    default_unit: 'g',
    storage_type: 'pantry_monthly',
    swap_group: 'fiber_veg',
  },
];
